### ISSUE TITLE
TLSA/DANE deployment

### ISSUE THREAD

**Issue by PSSGCSim** [Neilpang/acme.sh#1004]
Hello,
I was looking through the wiki, issues and stuff and I could not find any mention of [TLSA](https://tools.ietf.org/html/rfc6698)/[DANE](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities). Have anyone tried to set-up automatic TLSA with acme.sh? If so do you have any advice where should I put it? I was thinking of deployment script for a specific DNS API like with DNS Acme challenge scripts.
Thank you in advance.

Best regards,
PSSGCSim

**Comment by PSSGCSim** [comment]
Hello,
I have made a script that does the trick. Could please anyone take a look whether it is worth submitting in?
Thank you in advance.

[tlsa_knot.sh](https://gist.github.com/PSSGCSim/43000582860f808fd700b894c88f7cd3)

Best regards,
PSSGCSim

**Comment by PSSGCSim** [comment]
Hello,
could I please get your stance on this issue @Neilpang ?
Thank you in advance.

Best regards,
PSSGCSim

**Comment by Neilpang** [comment]
@PSSGCSim 
what is this for ?  sorry, I don't quite understand.

**Comment by PSSGCSim** [comment]
@Neilpang it makes hash of the certificate and deploys it to the DNS. It is used mostly with SMTP but web pages implement it as well.
You can check it out on my domain https://en.internet.nl/domain/psb1.org/104651/. It has some details on what it is. (This tool is recommended by DMARC website.)

**Comment by Neilpang** [comment]
Sorry, I don't think it should be included in acme.sh.

You can use it as a `--post-hook`.  but I don't think it's a part of acme.sh.

It's not a good idea to include anything into acme.sh,  let's keep it simple, just for the cert.

**Comment by PSSGCSim** [comment]
Ok, I understand. Closing this issue.
