### ISSUE TITLE
How to run acme.sh --install-cert when you have both regular (rsa) and ECC (ec-256) certificates?

### ISSUE THREAD

**Issue by djvdorp** [Neilpang/acme.sh#1011]
On one of my servers, I have both `domain.com` and `domain.com_ecc` in `~/.acme.sh/`.
However, I am having a hard time telling `acme.sh --install-cert` that I want to use the ECC version and **not** the regular (rsa) version. How should this be done? Below is what I have tried so far.

Eg. `acme.sh --install-cert -d domain.com --keylength ec-256` seems to make no difference. And `acme.sh --install-cert -d domain.com_ecc` seems to also not give the desired result. Any clue here?

**Comment by Neilpang** [comment]
Add --ecc

**Comment by djvdorp** [comment]
@Neilpang thanks, that is what I needed!
