### ISSUE TITLE
Does the cronjob install new certificate files totheir  correct locations?

### ISSUE THREAD

**Issue by janpieper** [Neilpang/acme.sh#1018]
Hey guys, i just set up a new ssl certificate for a website and now i wonder if the cronjob copies the new certificate files to the correct location if the certificate needs to be renewed?

I've used the following command to copy the certificate files to their correct locations:

```
acme.sh --install-cert \
  -d example.com \
  --cert-file /etc/ssl/letsencrypt/example.com.crt \
  --key-file /etc/ssl/letsencrypt/example.com.key \
  --reloadcmd "service nginx reload"
```

What happens if a new certificate is needed? Does `acme.sh` issue a new certificate and copy the files to their correct locations or do i need to do this by myself (e.g. via another cronjob)?

**Comment by Neilpang** [comment]
yes

**Comment by Tronde** [comment]
@janpieper I asked a very similar questions in #1091 which was answered there. Long story short: The certificate is copied to the correct location after it was renewed.

Could this issue be closed then? Or do you have additional questions?
