### ISSUE TITLE
Where do I get crontab?

### ISSUE THREAD

**Issue by teenangst** [Neilpang/acme.sh#1021]
Ok, so I don't have a whole lot of experience with command line and it might be a simple thing, but it's telling me to `install crontab first` - but I cannot find anywhere to install crontab at all online (just a thread where people were telling OP to not use crontab 😑)

Steps to reproduce
`curl https://get.acme.sh | sh` without crontab

Debug log
```
[Mon Sep 11 21:48:40 UTC 2017] Installing from online archive.
[Mon Sep 11 21:48:40 UTC 2017] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Mon Sep 11 21:48:41 UTC 2017] Extracting master.tar.gz
[Mon Sep 11 21:48:42 UTC 2017] It is recommended to install crontab first. try to install 'cron, crontab, crontabs or vixie-cron'.
[Mon Sep 11 21:48:42 UTC 2017] We need to set cron job to renew the certs automatically.
[Mon Sep 11 21:48:42 UTC 2017] Otherwise, your certs will not be able to be renewed automatically.
[Mon Sep 11 21:48:42 UTC 2017] Please add '--force' and try install again to go without crontab.
[Mon Sep 11 21:48:42 UTC 2017] ./acme.sh --install --force
[Mon Sep 11 21:48:42 UTC 2017] Pre-check failed, can not install.
```

**Comment by Neilpang** [comment]
it depends on what OS you are using.  
for example, if you are using  ubuntu,   
please search google for keywords:  `how to install crontab on ubuntu`, etc.

**Comment by teenangst** [comment]
I have no idea what OS I am using as `uname -a` and `lab_release -a` do not tell me.
`how to install crontab on ubuntu` obviously I've tried that but no results at all except for CentOS.

**Comment by Neilpang** [comment]
well,  then how can I know ?

do you have one of the following command ?

`apt-get`, `yum`, `zypper`, `apk`, `pacman`, `dnf` or `emerge` ?

you must know what OS you are on.

**Comment by teenangst** [comment]
I have absolutely no idea.

None of those commands are found.

It's not listed by my provider and I cannot see anywhere to find it.
