### ISSUE TITLE
Upgrade from old acme.sh 2.2.5

### ISSUE THREAD

**Issue by layanto** [Neilpang/acme.sh#1022]
I am using old acme.sh 2.2.5. How to upgrade to latest version? Do I need to uninstall old one first? I would like to keep account settings and existing certs and cronjob.

**Comment by FernandoMiguel** [comment]
run acme.sh --upgrade

**Comment by layanto** [comment]
Old acme.sh 2.2.5 does not have --upgrade

**Comment by Neilpang** [comment]
just install again.  acme.sh is clever enough to know how to upgrade from an existing installation.

```
curl https://get.acme.sh | sh
```

**Comment by layanto** [comment]
I previously installed acme.sh 2.2.5 to /etc/acme.sh so I tried cloning acme.sh git then called acme.sh --install --home /etc/acme.sh but running acme.sh --list post install list 0 certs. What happened to my previous certs issues with acme.sh 2.2.5?

**Comment by Neilpang** [comment]
don't worry,  your certs never get deleted.

**Comment by Neilpang** [comment]
show me your crontab:
```
crontab -l
```

**Comment by Neilpang** [comment]
and show me your envs

```
env

```

**Comment by Neilpang** [comment]
show me the install dir:

```
ls  /etc/acme.sh
```

**Comment by layanto** [comment]
To be honest, I don't remember how I installed acme.sh 2.2.5 over a year ago.

crontab -l
![image](https://user-images.githubusercontent.com/245078/30321940-261a7050-97fb-11e7-90e0-48b340c10187.png)

env
```
HOSTNAME=xxx
TERM=xterm
HISTSIZE=1000
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/admin
LANG=en_US.UTF-8
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
LOGNAME=root
USER=root
USERNAME=root
HOME=/root
SUDO_COMMAND=/bin/env
SUDO_USER=admin
SUDO_UID=500
SUDO_GID=500
```

ls /etc/acme.sh
![image](https://user-images.githubusercontent.com/245078/30322011-64b56982-97fb-11e7-9f72-635e725f3808.png)

**Comment by layanto** [comment]
I tried installing latest acme.sh by:
```
git clone https://github.com/Neilpang/acme.sh.git
cd acme.sh
./acme.sh --install --home /etc/acme.sh --certhome /etc/acme.sh/certs --accountemail "my@email.addr" --accountkey /etc/acme.sh/accounts/account.key --accountconf /etc/acme.sh/accounts.account.conf
```

**Comment by layanto** [comment]
While my previous certs are still in /etc/acme.sh/certs, not sure if they will still be renewed before expiry

**Comment by layanto** [comment]
Never mind.. my mistake. It appears that I have installed acme.sh under root but when I ran --list I was running as a different user.
