### ISSUE TITLE
Socat shows help when debugging

### ISSUE THREAD

**Issue by dugwood** [Neilpang/acme.sh#1023]
Steps to reproduce
------------------
Run acme.sh with `--debug` on a faulty domain

It must be missing a `socat -V`, or perhaps it OS dependent.

I'm running Linux Debian stable (Stretch).

Debug log
-----------------
[mercredi 13 septembre 2017, 15:12:22 (UTC+0200)] _ret='0'
[mercredi 13 septembre 2017, 15:12:22 (UTC+0200)] code='400'
[mercredi 13 septembre 2017, 15:12:22 (UTC+0200)] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.0f  25 May 2017
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:
socat by Gerhard Rieger - see [removed url]
Usage:
socat [options] <bi-address> <bi-address>
   options:
      -V     print version and feature information to stdout, and exit
      -h|-?  print a help text describing command line options and addresses
      -hh    like -h, plus a list of all common address option names
      -hhh   like -hh, plus a list of all available address option names
      -d     increase verbosity (use up to 4 times; 2 are recommended)
      -D     analyze file descriptors before loop
[ removed all the help message ]

**Comment by dugwood** [comment]
It must be the `-h` instead of `-V`:
https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L169

**Comment by Neilpang** [comment]
we used `socat -h`


https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L169

**Comment by dugwood** [comment]
Yes, but it dumps the whole help instead of the version. See:
https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L155 => Apache's version
https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L162 => Nginx' version

So there's no reason to pollute the debug with Socat's help, isn't it? It's really painful, must go up 2 pages to see the useful debug :-) Not that harmful, but it makes sense that all tools dump their versions, not their help :-)

**Comment by Neilpang** [comment]
>> Yes, but it dumps the whole help instead of the version.

That's intended,  I want to see as much info of the socat tool as we can.  Not only the version.

**Comment by dugwood** [comment]
Okay :-)
