### ISSUE TITLE
OCSP Must Staple with an existing CSR

### ISSUE THREAD

**Issue by itsallinyourhead** [Neilpang/acme.sh#1024]
I tried to get a certificate with DNS manual mode with an existing CSR. That CSR contains `1.3.6.1.5.5.7.1.24 = DER:30:03:02:01:05` but this line is removed in `~/.acme.sh/example.com_ecc/example.com.csr.conf`. So OCSP Must Staple does not work that way.
Even inserting that line into that file does not work, it is also removed after renewing the certificate.

Is there another way to get OCSP Must Staple working?

**Comment by Neilpang** [comment]
what command line parameter you are using.
The more info you give, the faster you can get answer.

**Comment by itsallinyourhead** [comment]
I've got it now. My bad.
I mixed something up with `--issue`, `--renew` and `--signcsr` parameters. It seems like `--renew` is not necessary for DNS manual mode with an existing CSR.
As long as I don't change CSR or private key, I do not need to change the TXT records, I guess. Would be much easier for deploying public key pining.
Thanks a lot.

**Comment by Neilpang** [comment]
>> As long as I don't change CSR or private key, I do not need to change the TXT records,

No,  every time you issue/renew a new cert,  you need to add a new txt record.

**Comment by itsallinyourhead** [comment]
Ok.
I will not use `--renew`.
I tried `acme.sh --signcsr --csr /path/to/csr --dns dns_cf --force` a few minutes ago and I got a new certificate without changing the TXT records. Hopefully this will also work after a longer period of time.
Thanks again.

**Comment by Neilpang** [comment]
`--dns dns_cf`  is cloudflare dns api mode,   not dns manual mode.
The api mode can renew automatically.

**Comment by itsallinyourhead** [comment]
None of my domains/dns settings are hosted on cloudflare. (https://www.transip.eu/)
And I want to keep it as simple as possible. No need to install an API. Everything works fine as it is now.

**Comment by Neilpang** [comment]
OK, anyway,  just remember that your cert will be expired in 90 days.  and  don't forget to renew it by your hand.  It CAN NOT renew automatically.

**Comment by itsallinyourhead** [comment]
Ok. I will enable a cronjob that does the acme.sh --signcsr command once in a while and copies the certificate files to another folder. No big deal.

**Comment by Neilpang** [comment]
let me recap.   you will have to add a new txt record by your hand, not just a cronjob.

**Comment by itsallinyourhead** [comment]
I understand what you are saying.
But on the other hand, I got yesterday and today a certificate with the same TXT records. I just used `--signcsr` today again and not `--issue` or `--renew`.

**Comment by Neilpang** [comment]
Letsencrypt CA has a 7-days cache.   you can issue a cert without verification in 7 days.

**Comment by itsallinyourhead** [comment]
Oh, I wasn't aware of that time limit. Makes it much harder, especially for public key pinning.

Thank you for explaining.

**Comment by Neilpang** [comment]
your key will not change on renewal.

**Comment by itsallinyourhead** [comment]
Hi again, a few minutes ago I used `acme.sh --signcsr --csr /path/to/csr --force` again and it still worked without changing the TXT records.
7 day limit didn't apply.
