### ISSUE TITLE
Unable to update acme.sh - error 60

### ISSUE THREAD

**Issue by justClouds** [Neilpang/acme.sh#1025]
Running upgrade on a DD-WRT setup (Kong v3) I get error 60:

root@gateway:/jffs/usr/ssl# ./acme.sh --upgrade --debug
[Thu Sep 14 14:09:48 CEST 2017] Using default home:/tmp/root/.acme.sh
[Thu Sep 14 14:09:48 CEST 2017] Using config home:/tmp/root/.acme.sh
https://github.com/Neilpang/acme.sh
v2.7.3
[Thu Sep 14 14:09:48 CEST 2017] Using config home:/tmp/root/.acme.sh
./acme.sh: cd: line 1: can't cd to /tmp/root/.acme.sh
[Thu Sep 14 14:09:48 CEST 2017] Installing from online archive.
[Thu Sep 14 14:09:48 CEST 2017] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Thu Sep 14 14:09:48 CEST 2017] GET
[Thu Sep 14 14:09:48 CEST 2017] url='https://github.com/Neilpang/acme.sh/archive/master.tar.gz'
[Thu Sep 14 14:09:48 CEST 2017] timeout
touch: /tmp/root/.acme.sh/http.header: No such file or directory
[Thu Sep 14 14:09:48 CEST 2017] _CURL='curl -L --silent --dump-header /tmp/acme.shwefADf24sf.1505390988.tmp '
[Thu Sep 14 14:09:48 CEST 2017] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Thu Sep 14 14:09:48 CEST 2017] ret='60'
[Thu Sep 14 14:09:48 CEST 2017] Download error.
[Thu Sep 14 14:09:48 CEST 2017] Upgrade failed!

The current version is 2.7.3.

**Comment by Neilpang** [comment]
```
 ./acme.sh --upgrade   --insecure
```
