### ISSUE TITLE
installcert error Domain not valid

### ISSUE THREAD

**Issue by justClouds** [Neilpang/acme.sh#1026]
Running "./acme.sh --installcert -d home.moerman.cc --certpath /opt/etc/nginx/cert --keypath /opt/etc/nginx/cert --fullchainpath /opt/etc/nginx/cert --debug" gives error:

[Thu Sep 14 14:14:41 CEST 2017] Using default home:/tmp/root/.acme.sh
[Thu Sep 14 14:14:41 CEST 2017] Using config home:/tmp/root/.acme.sh
https://github.com/Neilpang/acme.sh
v2.7.3
[Thu Sep 14 14:14:41 CEST 2017] Using config home:/tmp/root/.acme.sh
[Thu Sep 14 14:14:41 CEST 2017] DOMAIN_PATH='/tmp/root/.acme.sh/home.moerman.cc'
[Thu Sep 14 14:14:41 CEST 2017] Domain is not valid:'home.moerman.cc'

I've just succesfully issued the 'issue' command for the domain...

**Comment by Neilpang** [comment]
```
ls  /tmp/root/.acme.sh/home.moerman.cc
```
