### ISSUE TITLE
[Q] when renew-hook start?

### ISSUE THREAD

**Issue by historype** [Neilpang/acme.sh#1027]
When certificate renewed, I want to submit ct log my certificate too.So I decide to use ct-submit for SCT TLS Extension.For automatic update I want to set renew-hook /path/ct-submit.sh.ct-submit.sh need to set certificate path.So I have a question.Renewed certificate will copied to install-cert setting path.Right?When renew-hook start?After copied or before?

**Comment by Neilpang** [comment]
Yes,  you are right.  when renew-hook is called, all the cert/key is already copied to the target position.

But there are 2 recommended ways for you to use to get the cert/key file.  you can use either one of them.

1. You can use the vars:  `CERT_PATH`, `CERT_KEY_PATH` and  `CA_CERT_PATH`. 

2. If you set the real cert/key path in the `--install-cert` command.  you can also use `_readdomainconf()` function to read the cert/key file.

```sh
domain_cert_file=$(_readdomainconf Le_RealCertPath)
domain_key_file=$(_readdomainconf Le_RealKeyPath)
ca_file=$(_readdomainconf Le_RealKeyPath Le_RealCACertPath)
```
