### ISSUE TITLE
ecc keys by default

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#1039]
@Neilpang do you plan at any point in the near future to default to --keylength ec-256 --ecc keys, or plan to run RSA forever?
are there any guidelines from LE on the subject?

**Comment by Neilpang** [comment]
>> do you plan at any point in the near future to default to --keylength ec-256 

No.  RSA is and will be much more widely used than ECC.


>> are there any guidelines from LE on the subject?

No, I don't see that.

**Comment by FernandoMiguel** [comment]
thanks
