### ISSUE TITLE
Upgraded to 2.7.4, still asked for socat tools

### ISSUE THREAD

**Issue by charlieartist** [Neilpang/acme.sh#1043]
I updated acme.sh to v.2.7.4 on web server, and when running:

`acme.sh  --issue  -d [My Domain]  --standalone  --debug 2`

Got this (paths redacted for security): 
[Sun Sep 24 08:29:24 EDT 2017] Lets find script dir.
[Sun Sep 24 08:29:24 EDT 2017] _SCRIPT_='/[server_path]/.acme.sh/acme.sh'
[Sun Sep 24 08:29:24 EDT 2017] _script='/[server_path]/.acme.sh/acme.sh'
[Sun Sep 24 08:29:24 EDT 2017] _script_home='/[server_path]/.acme.sh'
[Sun Sep 24 08:29:24 EDT 2017] Using config home:/[server_path]/.acme.sh
[Sun Sep 24 08:29:24 EDT 2017] LE_WORKING_DIR='/[server_path]/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.7.4
[Sun Sep 24 08:29:24 EDT 2017] Using config home:/[server_path]/.acme.sh
[Sun Sep 24 08:29:24 EDT 2017] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Sep 24 08:29:24 EDT 2017] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Sep 24 08:29:24 EDT 2017] DOMAIN_PATH='/usr/home/iaweb2/.acme.sh/[My Domain] '
[Sun Sep 24 08:29:24 EDT 2017] Using ACME_DIRECTORY: https://acme-v01.api.letsencrypt.org/directory
[Sun Sep 24 08:29:24 EDT 2017] _init api for server: https://acme-v01.api.letsencrypt.org/directory
[Sun Sep 24 08:29:24 EDT 2017] ACME_KEY_CHANGE='https://acme-v01.api.letsencrypt.org/acme/key-change'
[Sun Sep 24 08:29:24 EDT 2017] ACME_NEW_AUTHZ='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Sun Sep 24 08:29:24 EDT 2017] ACME_NEW_ORDER='https://acme-v01.api.letsencrypt.org/acme/new-cert'
[Sun Sep 24 08:29:24 EDT 2017] ACME_NEW_ACCOUNT='https://acme-v01.api.letsencrypt.org/acme/new-reg'
[Sun Sep 24 08:29:24 EDT 2017] ACME_REVOKE_CERT='https://acme-v01.api.letsencrypt.org/acme/revoke-cert'
[Sun Sep 24 08:29:24 EDT 2017] Le_NextRenewTime
[Sun Sep 24 08:29:24 EDT 2017] _on_before_issue
[Sun Sep 24 08:29:24 EDT 2017] 'no' contains 'no'
[Sun Sep 24 08:29:24 EDT 2017] Please install socat tools first.
[Sun Sep 24 08:29:24 EDT 2017] _on_before_issue.

If it's any help, this server is running Free BSD.

Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
why not install socat ?

**Comment by charlieartist** [comment]
@Neilpang Correct me if I'm wrong, but was this to be addressed in the 2.7.4 update?

**Comment by Neilpang** [comment]
you need to install socat by yourself.  acme.sh never installs anything in your system.
