### ISSUE TITLE
Crashes of 2.7.4 in Standalone mode server

### ISSUE THREAD

**Issue by JanCejka** [Neilpang/acme.sh#1047]
**System / version:**
Fresh install of 2.7.4 on Proxmox 5 server (Debian Stretch).

**Original behavour:**
Error from socat when trying to verify domain in Standalone mode server (port 80)

**Error message example:**
```
2017/09/27 01:38:21 socat[18572] E poll(...[18573]: invalid request
sh: 1: ▒▒▒xU: not found
```

**Probable cause:**
Apostrophe in the following code. Without apostrophe everything works as expected. Or the other possibility - opening apostrophe is missing? Actually - anyone could explain me how it could work with just one apostrophe? Should not apostrophe technically open string that is not closed?

```
$_NC TCP-LISTEN:$Le_HTTPPort,crlf,reuseaddr,fork SYSTEM:"sleep 0.5; echo HTTP/1.1 200 OK'; echo ; echo  $content; echo;" &
```

Jan

**Comment by Neilpang** [comment]
Please upgrade to the latest version and try again.

```sh
acme.sh --upgrade
```

**Comment by JanCejka** [comment]
After upgrade, all is working as expected...

Thanks for correction. :-)

Jan
