### ISSUE TITLE
Requesting addition of GPLv3 license to repo

### ISSUE THREAD

**Issue by tbehling** [Neilpang/acme.sh#1050]
Hello, I am trying to use acme.sh in a project, but I am getting pushback due to the lack of a clear license in this project.  The README says `License is GPLv3`, but for our team there is a concern that statement might not be sufficient.

Would it be possible for the project to integrate the GNU project's guidance on the GPL at https://www.gnu.org/licenses/gpl-howto.html ?

**Comment by Neilpang** [comment]
Yes, it's GPLv3
I just don't want to add any files to the project just for license stuffs.  I want a clean project.

Thanks.

**Comment by tbehling** [comment]
Understood; thanks for the quick consideration!

**Comment by TBK** [comment]
Which variant of GPLv3 - GPL-3.0-only or GPL-3.0-or-later (https://spdx.org/licenses/)?
