### ISSUE TITLE
更新证书的时候非得用root吗？所以说实际上是--reloadcmd     "sudo service apache2 force-reload"

### ISSUE THREAD

**Issue by daiaji** [Neilpang/acme.sh#1057]
还是说不用重载http服务器也没问题？

**Comment by Neilpang** [comment]
理论上 apache 或者 nginx 服务器需要root权限才能操作.
不过,  可以设置某个用户操作nginx 或者 apache 服务器时不需要密码.
参考:
https://joshtronic.com/2014/12/21/sudo-without-password/

**Comment by daiaji** [comment]
@Neilpang 果然要让证书更新生效就需要重启apache吗。
那就绕不开root了

那个Issues我是看到了啦
我只是来确认一下是否存在着低权限也能重载http服务器的可能

**Comment by WordlessEcho** [comment]
I special the `service nginx force-reload` command as no password command.
Add this line to your `sudoers`:
```
<username>       ALL=(ALL) NOPASSWORD: /usr/sbin/service nginx force-reload
```
Then add sudo to `--reloadcmd`:
```
<acme.sh install command before>
--reloadcmd     "sudo service nginx force-reload"
```

**Comment by Konano** [comment]
> I special the `service nginx force-reload` command as no password command. **Add** this line to your `sudoers`:
> 
> ```
> <username>     ALL=(ALL) NOPASSWORD: /usr/sbin/service nginx force-reload
> ```
> 
> Then add sudo to `--reloadcmd`:
> 
> ```
> <acme.sh install command before>
> --reloadcmd     "sudo service nginx force-reload"
> ```

It should be:

```
<username>     ALL=(ALL) NOPASSWD: /usr/sbin/service nginx force-reload
```

**Comment by WordlessEcho** [comment]
> > I special the `service nginx force-reload` command as no password command. **Add** this line to your `sudoers`:
> > ```
> > <username>     ALL=(ALL) NOPASSWORD: /usr/sbin/service nginx force-reload
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then add sudo to `--reloadcmd`:
> > ```
> > <acme.sh install command before>
> > --reloadcmd     "sudo service nginx force-reload"
> > ```
> 
> It should be:
> 
> ```
> <username>     ALL=(ALL) NOPASSWD: /usr/sbin/service nginx force-reload
> ```

Sorry for my fault. Original comment updated.
