### ISSUE TITLE
how to edit nginx config to turn on ssl

### ISSUE THREAD

**Issue by kazaff** [Neilpang/acme.sh#1058]
Thank author first.

I think i create cert success. And i also run "--installcert" command, but my website still can not be visited by https.
I found that the nginx conf file had not include the ssl config content. So how can i update the nginx config?

When i run "--installcert" command, i only found two files in the target folder:  ***.cer,  ***.key. Is't right?

**Comment by Neilpang** [comment]
`--installcert` is just to copy the cert/key to the target paths.
You must modify your nginx conf by yourself to enable ssl.

you can search google for "enable nginx ssl".
