### ISSUE TITLE
Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed

### ISSUE THREAD

**Issue by mato4711** [Neilpang/acme.sh#1068]
Hello, I'm trying to use acme.sh in Windows 10 bash shell (WSL), but keep getting the following error:

curl: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
[Mon Oct  9 22:26:02 DST 2017] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 134

I tried deactivating ipv6 but that didn't make a difference. Cannot find libcurl error code 134 either. Any advice?

---------------
[Mon Oct  9 22:25:53 DST 2017] ok, let's start to verify
[Mon Oct  9 22:25:56 DST 2017] Verifying:XXXXXX.duckdns.org
[Mon Oct  9 22:25:56 DST 2017] d='XXXXXX.duckdns.org'
[Mon Oct  9 22:25:56 DST 2017] keyauthorization='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
[Mon Oct  9 22:25:56 DST 2017] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
[Mon Oct  9 22:25:56 DST 2017] _currentRoot='dns_duckdns'
[Mon Oct  9 22:25:57 DST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
[Mon Oct  9 22:25:57 DST 2017] payload='{"resource": "challenge", "keyAuthorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}'
[Mon Oct  9 22:26:00 DST 2017] POST
[Mon Oct  9 22:26:00 DST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
[Mon Oct  9 22:26:01 DST 2017] _CURL='curl -L --silent --dump-header /home/sysadmin/.acme.sh/http.header '
curl: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
[Mon Oct  9 22:26:02 DST 2017] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 134
[Mon Oct  9 22:26:02 DST 2017] _ret='134'
[Mon Oct  9 22:26:04 DST 2017] code
[Mon Oct  9 22:26:04 DST 2017] sleep 2 secs to verify
[Mon Oct  9 22:26:07 DST 2017] checking
[Mon Oct  9 22:26:07 DST 2017] GET
[Mon Oct  9 22:26:07 DST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
[Mon Oct  9 22:26:08 DST 2017] timeout
[Mon Oct  9 22:26:08 DST 2017] _CURL='curl -L --silent --dump-header /home/sysadmin/.acme.sh/http.header '
curl: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
[Mon Oct  9 22:26:09 DST 2017] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 134
[Mon Oct  9 22:26:09 DST 2017] ret='134'
[Mon Oct  9 22:26:09 DST 2017] XXXXXX.duckdns.org:Verify error:
[Mon Oct  9 22:26:10 DST 2017] Skip for removelevel:
[Mon Oct  9 22:26:10 DST 2017] pid
[Mon Oct  9 22:26:10 DST 2017] No need to restore nginx, skip.
[Mon Oct  9 22:26:10 DST 2017] _clearupdns

**Comment by Neilpang** [comment]
can you please try `wget` ?

**Comment by mato4711** [comment]
I'm not quite sure what you mean. Should I modify acme.sh to use wget instead curl? The acme.sh works fine until it gets to the verification part:

acme.sh --issue --dns dns_duckdns --domain XXXXXX.duckdns.org --key-file /mnt/c/Users/XXXXX/.minio/certs/private.key --fullchain-file /mnt/c/Users/XXXXX/.minio/certs/public.crt
[Mon Oct  9 20:05:34 DST 2017] Single domain='XXXXXX.duckdns.org'
[Mon Oct  9 20:05:37 DST 2017] Getting domain auth token for each domain
[Mon Oct  9 20:05:37 DST 2017] Getting webroot for domain='XXXXXX.duckdns.org'
[Mon Oct  9 20:05:38 DST 2017] Getting new-authz for domain='XXXXXX.duckdns.org'
[Mon Oct  9 20:06:07 DST 2017] The new-authz request is ok.
[Mon Oct  9 20:06:14 DST 2017] Found domain api file: /home/XXXXX/.acme.sh/dnsapi/dns_duckdns.sh
[Mon Oct  9 20:06:16 DST 2017] Trying to add TXT record
[Mon Oct  9 20:06:19 DST 2017] TXT record has been successfully added to your DuckDNS domain.
[Mon Oct  9 20:06:19 DST 2017] Note that all subdomains under this domain uses the same TXT record.
[Mon Oct  9 20:06:19 DST 2017] Sleep 120 seconds for the txt records to take effect
**[Mon Oct  9 20:08:54 DST 2017] Verifying:XXXXX.duckdns.org
curl: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
[Mon Oct  9 20:08:58 DST 2017] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 134**

**Comment by Neilpang** [comment]
good.
BTW,  there is a command option to force to use wget:
```sh
acme.sh --issue .....   --use-wget
```
