### ISSUE TITLE
Selecting from multiple AWS IAM users for DNS challenge

### ISSUE THREAD

**Issue by shanedobson-ibboost** [Neilpang/acme.sh#1076]
I'm attempting to use the AWS DNS API to issue and renew certs. Seems to working OK until I hit a snag.

I have one AWS user which creates snapshots of the server and I've created another one for the DNS challenge. I've added the second user to the aws credentials file as  "user2" but I can't figure out how to instruct acme.sh to use this second one so it is failing at the authorisation stage. Is there a way to do this?

Steps to reproduce
------------------

/home/jenkins/.acme.sh/acme.sh --cron -d mydomain.com

Debug log
-----------------
```
[Fri Oct 20 10:56:27 UTC 2017] Lets find script dir.
[Fri Oct 20 10:56:27 UTC 2017] _SCRIPT_='/home/jenkins/.acme.sh/acme.sh'
[Fri Oct 20 10:56:27 UTC 2017] _script='/home/jenkins/.acme.sh/acme.sh'
[Fri Oct 20 10:56:27 UTC 2017] _script_home='/home/jenkins/.acme.sh'
[Fri Oct 20 10:56:27 UTC 2017] Using config home:/home/jenkins/.acme.sh
https://github.com/Neilpang/acme.sh
v2.7.1
[Fri Oct 20 10:56:27 UTC 2017] Using config home:/home/jenkins/.acme.sh
[Fri Oct 20 10:56:27 UTC 2017] ===Starting cron===
[Fri Oct 20 10:56:27 UTC 2017] Using config home:/home/jenkins/.acme.sh
[Fri Oct 20 10:56:27 UTC 2017] _stopRenewOnError
[Fri Oct 20 10:56:27 UTC 2017] di='/home/jenkins/.acme.sh/mydomain.com/'
[Fri Oct 20 10:56:27 UTC 2017] d='mydomain.com'
[Fri Oct 20 10:56:27 UTC 2017] Using config home:/home/jenkins/.acme.sh
[Fri Oct 20 10:56:27 UTC 2017] DOMAIN_PATH='/home/jenkins/.acme.sh/mydomain.com'
[Fri Oct 20 10:56:27 UTC 2017] Renew: 'mydomain.com'
[Fri Oct 20 10:56:27 UTC 2017] Using config home:/home/jenkins/.acme.sh
[Fri Oct 20 10:56:27 UTC 2017] Using api: https://acme-v01.api.letsencrypt.org
[Fri Oct 20 10:56:27 UTC 2017] Le_NextRenewTime='1502721976'
[Fri Oct 20 10:56:27 UTC 2017] _on_before_issue
[Fri Oct 20 10:56:27 UTC 2017] Le_LocalAddress
[Fri Oct 20 10:56:27 UTC 2017] Check for domain='mydomain.com'
[Fri Oct 20 10:56:27 UTC 2017] _currentRoot='dns'
[Fri Oct 20 10:56:27 UTC 2017] _saved_account_key_hash is not changed, skip register account.
[Fri Oct 20 10:56:27 UTC 2017] Read key length:
[Fri Oct 20 10:56:27 UTC 2017] _createcsr
[Fri Oct 20 10:56:27 UTC 2017] Single domain='mydomain.com'
[Fri Oct 20 10:56:27 UTC 2017] Getting domain auth token for each domain
[Fri Oct 20 10:56:27 UTC 2017] ok, let's start to verify
[Fri Oct 20 10:56:27 UTC 2017] Verifying:mydomain.com
[Fri Oct 20 10:56:27 UTC 2017] d='mydomain.com'
[Fri Oct 20 10:56:27 UTC 2017] keyauthorization='hQCudzUqGAEr-80-BB_F5K6jK5VZtBu6SZtjBE8A8n8.tXRg1phuO7FLQdd8O5wJ7MQd_4OoYPMjrlxrWUQ4lGU'
[Fri Oct 20 10:56:27 UTC 2017] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/1UjyjCUxWOKx-nTJ5ELbbJwrw185MQavNgR7GXQpvhU/1753603739'
[Fri Oct 20 10:56:27 UTC 2017] _currentRoot='dns'
[Fri Oct 20 10:56:27 UTC 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/1UjyjCUxWOKx-nTJ5ELbbJwrw185MQavNgR7GXQpvhU/1753603739'
[Fri Oct 20 10:56:27 UTC 2017] payload='{"resource": "challenge", "keyAuthorization": "hQCudzUqGAEr-80-BB_F5K6jK5VZtBu6SZtjBE8A8n8.tXRg1phuO7FLQdd8O5wJ7MQd_4OoYPMjrlxrWUQ4lGU"}'
[Fri Oct 20 10:56:27 UTC 2017] RSA key
[Fri Oct 20 10:56:27 UTC 2017] GET
[Fri Oct 20 10:56:27 UTC 2017] url='https://acme-v01.api.letsencrypt.org/directory'
[Fri Oct 20 10:56:27 UTC 2017] timeout
[Fri Oct 20 10:56:27 UTC 2017] _CURL='curl -L --silent --dump-header /home/jenkins/.acme.sh/http.header '
[Fri Oct 20 10:56:28 UTC 2017] ret='0'
[Fri Oct 20 10:56:28 UTC 2017] POST
[Fri Oct 20 10:56:28 UTC 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/1UjyjCUxWOKx-nTJ5ELbbJwrw185MQavNgR7GXQpvhU/1753603739'
[Fri Oct 20 10:56:28 UTC 2017] _CURL='curl -L --silent --dump-header /home/jenkins/.acme.sh/http.header '
[Fri Oct 20 10:56:28 UTC 2017] _ret='0'
[Fri Oct 20 10:56:28 UTC 2017] code='404'
[Fri Oct 20 10:56:28 UTC 2017] mydomain.com:Challenge error: {"type":"urn:acme:error:malformed","detail":"Expired authorization","status": 404}
[Fri Oct 20 10:56:28 UTC 2017] Skip for removelevel:
[Fri Oct 20 10:56:28 UTC 2017] pid
[Fri Oct 20 10:56:28 UTC 2017] No need to restore nginx, skip.
[Fri Oct 20 10:56:28 UTC 2017] _clearupdns
[Fri Oct 20 10:56:28 UTC 2017] skip dns.
[Fri Oct 20 10:56:28 UTC 2017] _on_issue_err
[Fri Oct 20 10:56:28 UTC 2017] Please add '--debug' or '--log' to check more details.
[Fri Oct 20 10:56:28 UTC 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Fri Oct 20 10:56:28 UTC 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/1UjyjCUxWOKx-nTJ5ELbbJwrw185MQavNgR7GXQpvhU/1753603739'
[Fri Oct 20 10:56:28 UTC 2017] payload='{"resource": "challenge", "keyAuthorization": "hQCudzUqGAEr-80-BB_F5K6jK5VZtBu6SZtjBE8A8n8.tXRg1phuO7FLQdd8O5wJ7MQd_4OoYPMjrlxrWUQ4lGU"}'
[Fri Oct 20 10:56:28 UTC 2017] POST
[Fri Oct 20 10:56:28 UTC 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/1UjyjCUxWOKx-nTJ5ELbbJwrw185MQavNgR7GXQpvhU/1753603739'
[Fri Oct 20 10:56:28 UTC 2017] _CURL='curl -L --silent --dump-header /home/jenkins/.acme.sh/http.header '
[Fri Oct 20 10:56:29 UTC 2017] _ret='0'
[Fri Oct 20 10:56:29 UTC 2017] code='404'
[Fri Oct 20 10:56:29 UTC 2017] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.1f 6 Jan 2014
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.4.6 (Ubuntu)
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module
nc:
OpenBSD netcat (Debian patchlevel 1.105-7ubuntu1)
This is nc from the netcat-openbsd package. An alternative nc is available
in the netcat-traditional package.
usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
          [-P proxy_username] [-p source_port] [-q seconds] [-s source]
          [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
          [-x proxy_address[:port]] [destination] [port]
        Command Summary:
                -4              Use IPv4
                -6              Use IPv6
                -b              Allow broadcast
                -C              Send CRLF as line-ending
                -D              Enable the debug socket option
                -d              Detach from stdin
                -h              This help text
                -I length       TCP receive buffer length
                -i secs         Delay interval for lines sent, ports scanned
                -j              Use jumbo frame
                -k              Keep inbound sockets open for multiple connects
                -l              Listen mode, for inbound connects
                -n              Suppress name/port resolutions
                -O length       TCP send buffer length
                -P proxyuser    Username for proxy authentication
                -p port         Specify local port for remote connects
                -q secs         quit after EOF on stdin and delay of secs
                -r              Randomize remote ports
                -S              Enable the TCP MD5 signature option
                -s addr         Local source address
                -T toskeyword   Set IP Type of Service
                -t              Answer TELNET negotiation
                -U              Use UNIX domain socket
                -u              UDP mode
                -V rtable       Specify alternate routing table
                -v              Verbose
                -w secs         Timeout for connects and final net reads
                -X proto        Proxy protocol: "4", "5" (SOCKS) or "connect"
                -x addr[:port]  Specify proxy address and port
                -Z              DCCP mode
                -z              Zero-I/O mode [used for scanning]
        Port numbers can be individual or ranges: lo-hi [inclusive]
[Fri Oct 20 10:56:29 UTC 2017] Return code: 1
[Fri Oct 20 10:56:29 UTC 2017] Error renew mydomain.com.
[Fri Oct 20 10:56:29 UTC 2017] ===End cron===

```

**Comment by FernandoMiguel** [comment]
you should instead use ec2 roles attached to your instance that will grant what privs it needs to do what.
if you really want to have separate users, you should use assume role to switch between privs

the 3rd option, would be to export the second user as var envs and that will be the ones used by acme.sh but more unsecure

**Comment by shanedobson-ibboost** [comment]
I'm not clear on what you mean by "you should use assume role to switch between privs"?

**Comment by FernandoMiguel** [comment]
@shanedobson-ibboost see if this helps
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html

**Comment by shanedobson-ibboost** [comment]
Thanks, but that's really too general to help. I'm following all the instructions but I'm being told by acme.sh that I haven't set up aws credentials yet - but I have.

```
jenkins@ldap:/home/admin$ /home/jenkins/.acme.sh/acme.sh --cron --dns dns_aws
[Fri Oct 20 13:59:42 UTC 2017] ===Starting cron===
[Fri Oct 20 13:59:42 UTC 2017] Renew: 'mydomain.com'
[Fri Oct 20 13:59:42 UTC 2017] Single domain='mydomain.com'
[Fri Oct 20 13:59:42 UTC 2017] Getting domain auth token for each domain
[Fri Oct 20 13:59:42 UTC 2017] Verifying:mydomain.com
[Fri Oct 20 13:59:43 UTC 2017] mydomain.com:Challenge error: {"type":"urn:acme:error:malformed","detail":"Expired authorization","status": 404}
[Fri Oct 20 13:59:43 UTC 2017] Please add '--debug' or '--log' to check more details.
[Fri Oct 20 13:59:43 UTC 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Fri Oct 20 13:59:44 UTC 2017] Error renew ldap.internal.ibboost.com.
[Fri Oct 20 13:59:44 UTC 2017] ===End cron===
```

**Comment by Neilpang** [comment]
@shanedobson-ibboost 

The cert was firstly issued by dns manually mode. so it can not renew.

Please issue a new one.

**Comment by shanedobson-ibboost** [comment]
I get the same issue if I run the command

`/home/jenkins/.acme.sh/acme.sh --issue --dns dns_aws -d mydomain.com`

The problem here is that acme.sh isn't recognising that I have configured AWS credentials. I'm using the exact method on another server, which was also originally issues by dns manual mode and, and it works fine.

You can see from the error output that it's not recognising the AWS credentials I have configured.

**Comment by Neilpang** [comment]
why not paste the output here:
```
/home/jenkins/.acme.sh/acme.sh --issue --dns dns_aws -d mydomain.com --debug 2
```

**Comment by shanedobson-ibboost** [comment]
`enkins@ldap:/home/admin$ /home/jenkins/.acme.sh/acme.sh --issue --dns dns_aws -d mydomain.com --debug 2
[Fri Oct 20 14:15:22 UTC 2017] Lets find script dir.
[Fri Oct 20 14:15:22 UTC 2017] _SCRIPT_='/home/jenkins/.acme.sh/acme.sh'
[Fri Oct 20 14:15:22 UTC 2017] _script='/home/jenkins/.acme.sh/acme.sh'
[Fri Oct 20 14:15:22 UTC 2017] _script_home='/home/jenkins/.acme.sh'
[Fri Oct 20 14:15:22 UTC 2017] Using config home:/home/jenkins/.acme.sh
[Fri Oct 20 14:15:22 UTC 2017] LE_WORKING_DIR='/home/jenkins/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.7.1
[Fri Oct 20 14:15:22 UTC 2017] Using api:
[Fri Oct 20 14:15:22 UTC 2017] Using config home:/home/jenkins/.acme.sh
[Fri Oct 20 14:15:22 UTC 2017] DOMAIN_PATH='/home/jenkins/.acme.sh/mydomain.com'
[Fri Oct 20 14:15:22 UTC 2017] Le_NextRenewTime='1502719844'
[Fri Oct 20 14:15:22 UTC 2017] _on_before_issue
[Fri Oct 20 14:15:22 UTC 2017] 'dns_aws' does not contain 'no'
[Fri Oct 20 14:15:22 UTC 2017] Le_LocalAddress
[Fri Oct 20 14:15:22 UTC 2017] Check for domain='mydomain.com'
[Fri Oct 20 14:15:22 UTC 2017] _currentRoot='dns_aws'
[Fri Oct 20 14:15:22 UTC 2017] 'dns_aws' does not contain 'apache'
[Fri Oct 20 14:15:22 UTC 2017] _saved_account_key_hash='wGIe87SLdQzjcifldvHI0bYltEmirDSxG57/6BqiL+E='
[Fri Oct 20 14:15:22 UTC 2017] _saved_account_key_hash is not changed, skip register account.
[Fri Oct 20 14:15:22 UTC 2017] Read key length:
[Fri Oct 20 14:15:22 UTC 2017] _createcsr
[Fri Oct 20 14:15:22 UTC 2017] domain='mydomain.com'
[Fri Oct 20 14:15:22 UTC 2017] domainlist
[Fri Oct 20 14:15:22 UTC 2017] csrkey='/home/jenkins/.acme.sh/mydomain.com/mydomain.com.key'
[Fri Oct 20 14:15:22 UTC 2017] csr='/home/jenkins/.acme.sh/mydomain.com/mydomain.com.csr'
[Fri Oct 20 14:15:22 UTC 2017] csrconf='/home/jenkins/.acme.sh/mydomain.com/mydomain.com.csr.conf'
[Fri Oct 20 14:15:22 UTC 2017] Single domain='mydomain.com'
[Fri Oct 20 14:15:22 UTC 2017] _is_idn_d='mydomain.com'
[Fri Oct 20 14:15:22 UTC 2017] _idn_temp
[Fri Oct 20 14:15:22 UTC 2017] _csr_cn='mydomain.com'
[Fri Oct 20 14:15:22 UTC 2017] Getting domain auth token for each domain
[Fri Oct 20 14:15:22 UTC 2017] Getting webroot for domain='mydomain.com'
[Fri Oct 20 14:15:22 UTC 2017] _w='dns_aws'
[Fri Oct 20 14:15:22 UTC 2017] _currentRoot='dns_aws'
[Fri Oct 20 14:15:22 UTC 2017] Getting new-authz for domain='mydomain.com'
[Fri Oct 20 14:15:22 UTC 2017] Try new-authz for the 0 time.
[Fri Oct 20 14:15:22 UTC 2017] _is_idn_d='mydomain.com'
[Fri Oct 20 14:15:22 UTC 2017] _idn_temp
[Fri Oct 20 14:15:22 UTC 2017] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Fri Oct 20 14:15:22 UTC 2017] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "mydomain.com"}}'
[Fri Oct 20 14:15:22 UTC 2017] RSA key
[Fri Oct 20 14:15:22 UTC 2017] Get nonce.
[Fri Oct 20 14:15:22 UTC 2017] GET
[Fri Oct 20 14:15:22 UTC 2017] url='https://acme-v01.api.letsencrypt.org/directory'
[Fri Oct 20 14:15:22 UTC 2017] timeout
[Fri Oct 20 14:15:22 UTC 2017] _CURL='curl -L --silent --dump-header /home/jenkins/.acme.sh/http.header  --trace-ascii /tmp/tmp.OUfK9glctu '
[Fri Oct 20 14:15:22 UTC 2017] ret='0'
[Fri Oct 20 14:15:22 UTC 2017] _headers='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 561
Replay-Nonce: yUHY4Nz6b5ejIE1kWTcAgk56kjBK0wtnZwCn20d49lE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 20 Oct 2017 14:15:32 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 20 Oct 2017 14:15:32 GMT
Connection: keep-alive
'
[Fri Oct 20 14:15:22 UTC 2017] _CACHED_NONCE='yUHY4Nz6b5ejIE1kWTcAgk56kjBK0wtnZwCn20d49lE'
[Fri Oct 20 14:15:22 UTC 2017] nonce='yUHY4Nz6b5ejIE1kWTcAgk56kjBK0wtnZwCn20d49lE'
[Fri Oct 20 14:15:22 UTC 2017] POST
[Fri Oct 20 14:15:22 UTC 2017] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Fri Oct 20 14:15:22 UTC 2017] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "xj5RVey_n5tWkiuUt9VmNVEq9MtSU8Ie0SraXn6sHfTbgQYNHdNby5Vk_bQrB95IfABiqzGEIZ719AwtimuZr0x5iw1QGgSnWgcOBSSvy6d7SisZBKimMcu75A7SmacnUSv2gEVko8Ax2V8v1ZCYBpKYggMICJhTrwhvv8owl_zEnPTbgsm0P2hU9Mh1jsdoBGiiNts36pmZQFVuigS3oB1XtACgso-NiKYH2G1Ll8yAPpGa7tYj658rzWv-ddR4aJvA6WpGTvBdl3teB8IvbnlujcuGWvweivWdRmpFWqiMiujIGSAcJ0LmTWRKm1mlvuwRQlbeeJOsRkDS6vcy1Q"}}, "protected": "eyJub25jZSI6ICJ5VUhZNE56NmI1ZWpJRTFrV1RjQWdrNTZrakJLMHd0blp3Q24yMGQ0OWxFIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAieGo1UlZleV9uNXRXa2l1VXQ5Vm1OVkVxOU10U1U4SWUwU3JhWG42c0hmVGJnUVlOSGROYnk1VmtfYlFyQjk1SWZBQmlxekdFSVo3MTlBd3RpbXVacjB4NWl3MVFHZ1NuV2djT0JTU3Z5NmQ3U2lzWkJLaW1NY3U3NUE3U21hY25VU3YyZ0VWa284QXgyVjh2MVpDWUJwS1lnZ01JQ0poVHJ3aHZ2OG93bF96RW5QVGJnc20wUDJoVTlNaDFqc2RvQkdpaU50czM2cG1aUUZWdWlnUzNvQjFYdEFDZ3NvLU5pS1lIMkcxTGw4eUFQcEdhN3RZajY1OHJ6V3YtZGRSNGFKdkE2V3BHVHZCZGwzdGVCOEl2Ym5sdWpjdUdXdndlaXZXZFJtcEZXcWlNaXVqSUdTQWNKMExtVFdSS20xbWx2dXdSUWxiZWVKT3NSa0RTNnZjeTFRIn19", "payload": "eyJyZXNvdXJjZSI6ICJuZXctYXV0aHoiLCAiaWRlbnRpZmllciI6IHsidHlwZSI6ICJkbnMiLCAidmFsdWUiOiAibGRhcC5pbnRlcm5hbC5pYmJvb3N0LmNvbSJ9fQ", "signature": "bZR9LjQ48u6n65ydz2q2Yrk5uR4MIFqkoN2FCsgJC5C0Tjl_6kRl0VygTyF7sm6gLlffGYZcc9ww6QqJpg4QnAqfzLslovnFNf3AVI45C7c19Ke_MYZtOqOrlTQAGrdbfCiCLsr4u9G0M-qjzn5VFOFH11NmvGZ56MccrJL2ssRA2GSpff1DSj76n3Fe5vYmIxlmlaSuLvOj10ROzOMB4YkQfPjYvHZV8nLFFdCX5a5J56gBZu6lrr-P7qbB1pKsWggegh6mLuzBmA52R3Q86293VhzF2M8zoDKyIUzB8Ru7_qagmXIkppHTRgcqqZkaZuLJUL_iKbSZuQFUSlCOqA"}'
[Fri Oct 20 14:15:22 UTC 2017] _CURL='curl -L --silent --dump-header /home/jenkins/.acme.sh/http.header  --trace-ascii /tmp/tmp.lXGBjw36Ka '
[Fri Oct 20 14:15:23 UTC 2017] _ret='0'
[Fri Oct 20 14:15:23 UTC 2017] original='{
  "identifier": {
    "type": "dns",
    "value": "mydomain.com"
  },
  "status": "pending",
  "expires": "2017-10-27T11:28:24Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843186",
      "token": "4sOL2cFSxwnrg1NNiBrKewwbEY0uDvxItZ1BaqdjlSE"
    },
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843187",
      "token": "JGEdv_q5D8u4sOJjgwp24QslnOIg7_6rA5a5OnZt_9o"
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843188",
      "token": "2DZ309HHjedUClufUNwzaV9D0O93fWFyGQorUgTjuZU"
    }
  ],
  "combinations": [
    [
      2
    ],
    [
      1
    ],
    [
      0
    ]
  ]
}'
[Fri Oct 20 14:15:23 UTC 2017] responseHeaders='HTTP/1.1 100 Continue
Expires: Fri, 20 Oct 2017 14:15:32 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 201 Created
Server: nginx
Content-Type: application/json
Content-Length: 1003
Boulder-Requester: 17212460
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8
Replay-Nonce: EyVmTEQD_A3RWTgO-jrPE9ask20zbzYjUwDF7BaQwGI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 20 Oct 2017 14:15:33 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 20 Oct 2017 14:15:33 GMT
Connection: keep-alive
'
[Fri Oct 20 14:15:23 UTC 2017] response='{"identifier":{"type":"dns","value":"mydomain.com"},"status":"pending","expires":"2017-10-27T11:28:24Z","challenges":[{"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843186","token":"4sOL2cFSxwnrg1NNiBrKewwbEY0uDvxItZ1BaqdjlSE"},{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843187","token":"JGEdv_q5D8u4sOJjgwp24QslnOIg7_6rA5a5OnZt_9o"},{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843188","token":"2DZ309HHjedUClufUNwzaV9D0O93fWFyGQorUgTjuZU"}],"combinations":[[2],[1],[0]]}'
[Fri Oct 20 14:15:23 UTC 2017] code='201'
[Fri Oct 20 14:15:23 UTC 2017] The new-authz request is ok.
[Fri Oct 20 14:15:23 UTC 2017] entry='"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843186","token":"4sOL2cFSxwnrg1NNiBrKewwbEY0uDvxItZ1BaqdjlSE"'
[Fri Oct 20 14:15:23 UTC 2017] token='4sOL2cFSxwnrg1NNiBrKewwbEY0uDvxItZ1BaqdjlSE'
[Fri Oct 20 14:15:23 UTC 2017] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843186'
[Fri Oct 20 14:15:23 UTC 2017] keyauthorization='4sOL2cFSxwnrg1NNiBrKewwbEY0uDvxItZ1BaqdjlSE.QKbystJtbwLrKjWDe0_DxBavdzRnrb50HsNYiiiTzGU'
[Fri Oct 20 14:15:23 UTC 2017] dvlist='mydomain.com#4sOL2cFSxwnrg1NNiBrKewwbEY0uDvxItZ1BaqdjlSE.QKbystJtbwLrKjWDe0_DxBavdzRnrb50HsNYiiiTzGU#https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843186#dns-01#dns_aws'
[Fri Oct 20 14:15:23 UTC 2017] vlist='mydomain.com#4sOL2cFSxwnrg1NNiBrKewwbEY0uDvxItZ1BaqdjlSE.QKbystJtbwLrKjWDe0_DxBavdzRnrb50HsNYiiiTzGU#https://acme-v01.api.letsencrypt.org/acme/challenge/x0HyHhuD3crF2taWVUGk4jM1RmPtTirbeVnTRUZRgW8/2256843186#dns-01#dns_aws,'
[Fri Oct 20 14:15:23 UTC 2017] txtdomain='_acme-challenge.mydomain.com'
[Fri Oct 20 14:15:23 UTC 2017] txt='GNEdDPxGi329Cx02nNSXATmGm45NUpucxZgd6VJ_Ey4'
[Fri Oct 20 14:15:23 UTC 2017] d_api='/home/jenkins/.acme.sh/dnsapi/dns_aws.sh'
[Fri Oct 20 14:15:23 UTC 2017] Found domain api file: /home/jenkins/.acme.sh/dnsapi/dns_aws.sh
[Fri Oct 20 14:15:23 UTC 2017] You don't specify aws route53 api key id and and api key secret yet.
[Fri Oct 20 14:15:23 UTC 2017] Please create you key and try again. see https://github.com/Neilpang/acme.sh/wiki/How-to-use-Amazon-Route53-API
[Fri Oct 20 14:15:23 UTC 2017] Error add txt for domain:_acme-challenge.mydomain.com
[Fri Oct 20 14:15:23 UTC 2017] pid
[Fri Oct 20 14:15:23 UTC 2017] No need to restore nginx, skip.
[Fri Oct 20 14:15:23 UTC 2017] _clearupdns
[Fri Oct 20 14:15:23 UTC 2017] skip dns.
[Fri Oct 20 14:15:23 UTC 2017] _on_issue_err
[Fri Oct 20 14:15:23 UTC 2017] Please add '--debug' or '--log' to check more details.
[Fri Oct 20 14:15:23 UTC 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Fri Oct 20 14:15:23 UTC 2017] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.1t  3 May 2016
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
nc:
OpenBSD netcat (Debian patchlevel 1.105-7)
usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
          [-P proxy_username] [-p source_port] [-q seconds] [-s source]
          [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
          [-x proxy_address[:port]] [destination] [port]
        Command Summary:
                -4              Use IPv4
                -6              Use IPv6
                -b              Allow broadcast
                -C              Send CRLF as line-ending
                -D              Enable the debug socket option
                -d              Detach from stdin
                -h              This help text
                -I length       TCP receive buffer length
                -i secs         Delay interval for lines sent, ports scanned
                -j              Use jumbo frame
                -k              Keep inbound sockets open for multiple connects
                -l              Listen mode, for inbound connects
                -n              Suppress name/port resolutions
                -O length       TCP send buffer length
                -P proxyuser    Username for proxy authentication
                -p port         Specify local port for remote connects
                -q secs         quit after EOF on stdin and delay of secs
                -r              Randomize remote ports
                -S              Enable the TCP MD5 signature option
                -s addr         Local source address
                -T toskeyword   Set IP Type of Service
                -t              Answer TELNET negotiation
                -U              Use UNIX domain socket
                -u              UDP mode
                -V rtable       Specify alternate routing table
                -v              Verbose
                -w secs         Timeout for connects and final net reads
                -X proto        Proxy protocol: "4", "5" (SOCKS) or "connect"
                -x addr[:port]  Specify proxy address and port
                -Z              DCCP mode
                -z              Zero-I/O mode [used for scanning]
        Port numbers can be individual or ranges: lo-hi [inclusive]`

**Comment by Neilpang** [comment]
1. first upgrade your code to the latest version.
```
/home/jenkins/.acme.sh/acme.sh  --upgrade
```

2.  Follow this guide:

https://github.com/Neilpang/acme.sh/tree/master/dnsapi#10-use-amazon-route53-domain-api

**Comment by Neilpang** [comment]
```
export  AWS_ACCESS_KEY_ID=XXXXXXXXXX
export  AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXX
```

**Comment by FernandoMiguel** [comment]
> [Fri Oct 20 14:15:23 UTC 2017] Found domain api file: /home/jenkins/.acme.sh/dnsapi/dns_aws.sh

you said you have two aws users.
are you able to export the creds from the second one as env vars and try again?

**Comment by FernandoMiguel** [comment]
as i said before, if this is from an EC2 instance, the "right" way is to use EC2 Roles
https://aws.amazon.com/blogs/aws/iam-roles-for-ec2-instances-simplified-secure-access-to-aws-service-apis-from-ec2/
if you are running from any other method, let us know so we can help further

**Comment by shanedobson-ibboost** [comment]
I ran the export commands suggested by @Neilpang before running these commands. However, I tried exporting my second IAM user, and the cert issues correctly, then when I exported the correct user again, the commands started working (well, there is another error, but unrelated). Thanks both.
