### ISSUE TITLE
How can I delete old SSL/TSL sertificate  genereated for prev installation with acme.sh? 

### ISSUE THREAD

**Issue by Gurvynyk** [Neilpang/acme.sh#1081]
How can I delete old SSL/TSL sertificate  genereated for prev installation with acme.sh? 

Got generated SSL/TSL sertificates .
Then reinstalled (wiped) system.

Now while making clean install got error 
Sign failed: "detail":"Error creating new cert :: too many certificates already issued for exact set of domains: ***"

I tried to remove using —remove option 

But next  sudo ./acme.sh —issue —standalone -d mydomain

[Mon Oct 23 11:02:59 CEST 2017] Verify finished, start to sign.
[Mon Oct 23 11:03:00 CEST 2017] Sign failed: "detail":"Error creating new cert :: too many certificates already issued for exact set of domains:  mydomain"
[Mon Oct 23 11:03:00 CEST 2017] Please check log file for more details: /root/.acme.sh/acme.sh.log

How can I delete (deactivate) old unused serticifatec for mydomain ?

**Comment by FernandoMiguel** [comment]
that's not acme.sh but let's encrypt API.
you seem to have generated many, and reached the LE API limit

see here 
https://letsencrypt.org/docs/rate-limits/

**Comment by Gurvynyk** [comment]
Is there any way to clean / delete all unised serticifates to free  LE API limit ?

**Comment by FernandoMiguel** [comment]
sadly no. you have to wait til the API resets 

in the future be careful when issuing certs to keep it under the api limits.
for testing, remember to use the --staging flag

**Comment by Gurvynyk** [comment]
> you have to wait til the API resets

what time limits ? Will unused SSL / TSL be auto deleted ?

**Comment by FernandoMiguel** [comment]
nothing gets deleted.
certs will be valid till their expiration date
