### ISSUE TITLE
Certificates should be clasified into three types: RSA, ECC and Custom-CSR

### ISSUE THREAD

**Issue by thynson** [Neilpang/acme.sh#1090]
This issue is a design improvement from my view.

Problem:
When deploying certificates requested from custom CSR, one need to know whether its private key is ECC or not, which make it hard to be correct.

Suggestion:
Certificates should internally clasified into three types: RSA(default), ECC and Custom-CSR. And we will gain some good points:
1. Self-sign certificates won't conflicts with RSA and ECC certificates whose private key was generated by acme.sh.
2. Command line options for issue certificates and deploy certificates will be consistent. For certificates issue by,  supposely say `--custom-csr`, we deploy them with `--custom-csr`. Just like what the ECC certificates do with `--ecc`.

**Comment by Neilpang** [comment]
Sorry, I don't think so.

When you use a custom csr,  acme.sh can detect which key type(RSA or ECC) it is. And it can put the cert files in the correct folder.

The `--ecc` means  **key type**,  not **CSR type**.

**Comment by thynson** [comment]
Yes, certificate type can be detected from CSR. But we don't need to detect it actully. 

IMHO, Custom-CSR should be handled in a very different approch. `acme.sh` don't need know which algorithm, RSA or ECC, or something in the future, is used. Just challenge and sign the cert.

Imagine that somebody do switch from RSA to ECC but finally found certificate auto-deploy is broken because `acme.sh --install-cert` missing `--ecc`

**Comment by thynson** [comment]
OK. Close it.
