### ISSUE TITLE
Do I have to run acme.sh --install-cert every time a cert was renewed?

### ISSUE THREAD

**Issue by Tronde** [Neilpang/acme.sh#1091]
Hello,
I've got a question about the usage of acme.sh. From he [README.md](https://github.com/Neilpang/acme.sh/blob/master/README.md) I know that I could install the issued cert to nginx with the following command:
~~~
acme.sh --install-cert -d example.com \
--key-file       /path/to/keyfile/in/nginx/key.pem  \
--fullchain-file /path/to/fullchain/nginx/cert.pem \
--reloadcmd     "service nginx force-reload"
~~~

Do I have to run this command every time my certs are renewed by the cronjob which was created during `acme.sh --install`? Are the certs installed by the cronjob automatically?

Thank you in advance for your response. I'm looking forward to hearing from you soon.

Best regards,
Tronde

**Comment by Neilpang** [comment]
No,

the parameters are saved automatically,  and will be reused when renewal automatically.

**Comment by Tronde** [comment]
Thanks a lot for your quick answer.

**Comment by liujunhui74** [comment]
> No,
> 
> the parameters are saved automatically, and will be reused when renewal automatically.

Do you know the place where the parameters are saved? I grep-ed everywhere but can't find them.
