### ISSUE TITLE
Is it possible to specify an accountemail after the installation?

### ISSUE THREAD

**Issue by Tronde** [Neilpang/acme.sh#1096]
Hi,
Is it possible to specify an accountemail after the installation?

I've installed the client via `acme.sh --install` without the specification of an accountemail address. I would like to add an email address to receive renewal notifications from letsencrypt. Is it possible to add the accountemail address after the installation by command or editing of a config file?

Best regards,
Tronde

**Comment by Neilpang** [comment]
Yes,

```sh
acme.sh --update-account  --accountemail aaa@example.com
```

**Comment by Tronde** [comment]
Thank you very much!

**Comment by levrik** [comment]
```
--accountemail                    Specifies the account email for registering, Only valid for the '--install' command.
```

@Neilpang Help says it is only working together with `--install`? Also don't see any confirmation that the update was successful when trying above command.

**Comment by FernandoMiguel** [comment]
@levrik --update-account will work.
i've done this many times

**Comment by levrik** [comment]
@FernandoMiguel Okay. Thank you. Maybe the output should be improved for better UX? @Neilpang

**Comment by FernandoMiguel** [comment]
PRs welcome :)
