### ISSUE TITLE
What are the different log levels?

### ISSUE THREAD

**Issue by Tronde** [Neilpang/acme.sh#1097]
Hi,
In ["Enable acme.sh-log"](https://github.com/Neilpang/acme.sh/wiki/Enable-acme.sh-log) I've read that you could specify the log level. Are there any information about the different log level? What will be logged in which log level?

Best regards,
Tronde

**Comment by Neilpang** [comment]
`log level 1 == debug `
`log level 2 == debug 2`

**Comment by Tronde** [comment]
Ok, thought there were more log level. Thanks again.
