### ISSUE TITLE
FreeDNS update script does not work on BSD

### ISSUE THREAD

**Issue by jabbera** [Neilpang/acme.sh#1109]
The [expression ](https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_freedns.sh#L76)to turn a table into CSV does not work with BSD sed (pfsense specifically). The BSD sed has significant differences to the GNU sed. 

Reproduction from sh on pfsense 2.3.4_1 

```
htmlpage="<table><tr><td>Cell 1</td><td>Cell 2</td></tr></table>"

echo "$htmlpage" \
| grep -i -e '</\?TABLE\|</\?TD\|</\?TR\|</\?TH' \
| sed 's/^[\ \t]*//g' \
| tr -d '\n' \
| sed 's/<\/TR[^>]*>/\n/Ig' \
| sed 's/<\/\?\(TABLE\|TR\)[^>]*>//Ig' \
| sed 's/^<T[DH][^>]*>\|<\/\?T[DH][^>]*>$//Ig' \
| sed 's/<\/T[DH][^>]*><T[DH][^>]*>/,/Ig'

```
This should result in printing `Cell1,Cell2\n` (where \n is a newline) to the console instead `<table><tr><td>Cell 1,Cell 2</td>n</table>` is printed

**Comment by Neilpang** [comment]
thanks.  can you please give a `--debug 2` full log.  so that I could fix it.

**Comment by jabbera** [comment]
Here you go: https://gist.github.com/jabbera/6649c0252ac82ad6652079482b28a140

**Comment by autarkis13** [comment]
I am attempting to use afraid.com's FreeDNS as well on FreeBSD 11.1-RELEASE-p2 (pfsense 2.4.1) with no success.  If I can help troubleshoot, please let me know.

**Comment by jabbera** [comment]
Yeah. The bsd/gnu sed differences are killing the script.

**Comment by jabbera** [comment]
Hi @neilpang any luck with this?

Cheers,
Mike

**Comment by Neilpang** [comment]
@jabbera  @autarkis13 

Sorry, I was too busy recently.

I just fixed it in a new branch https://github.com/Neilpang/acme.sh/tree/freedns

Please have a try:
```sh
export BRANCH=freedns
acme.sh --upgrade
```

I don't have a paid account in freedns, so it's not tested yet, I just fix it based on the log.

I hope it works for you now.

If it's still has problem,  please give me the new `--debug 2` log.  I will fix it again.

And if it's lucky enough, it's working now, please also test it on a Linux box.

Thanks.
Looking forwarding for your reply.

**Comment by jabbera** [comment]
Will do for pfsense, no Linux boxes unfortunately.

**Comment by jabbera** [comment]
Confirmed working on bsd!

Thanks!
