### ISSUE TITLE
fullchain.cer: No such file or directory

### ISSUE THREAD

**Issue by wv1124** [Neilpang/acme.sh#1113]
➜  .acme.sh acme.sh --install-cert -d natapp.ddd.top \
--key-file       /usr/local/etc/nginx/ssl/key.pem  \
--fullchain-file /usr/local/etc/nginx/ssl/cert.pem --debug 2
[三 11 15 10:31:40 CST 2017] Lets find script dir.
[三 11 15 10:31:40 CST 2017] _SCRIPT_='/Users/wv/.acme.sh/acme.sh'
[三 11 15 10:31:40 CST 2017] _script='/Users/wv/.acme.sh/acme.sh'
[三 11 15 10:31:40 CST 2017] _script_home='/Users/wv/.acme.sh'
[三 11 15 10:31:40 CST 2017] Using config home:/Users/wv/.acme.sh
[三 11 15 10:31:40 CST 2017] LE_WORKING_DIR='/Users/wv/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.7.5
[三 11 15 10:31:40 CST 2017] Using config home:/Users/wv/.acme.sh
[三 11 15 10:31:40 CST 2017] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[三 11 15 10:31:40 CST 2017] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[三 11 15 10:31:40 CST 2017] DOMAIN_PATH='/Users/wv/.acme.sh/natapp.ddd.top'
[三 11 15 10:31:40 CST 2017] Installing key to:/usr/local/etc/nginx/ssl/key.pem
[三 11 15 10:31:40 CST 2017] Installing full chain to:/usr/local/etc/nginx/ssl/cert.pem
cat: /Users/wv/.acme.sh/natapp.ddd.top/fullchain.cer: No such file or directory

➜  .acme.sh ls -la /Users/wv/.acme.sh/natapp.ddd.top
total 24
drwxr-xr-x  8 wv  272 11 15 09:59 .
drwx------ 11 wv  374 11 15 10:08 ..
-rw-r--r--  1 wv 6148 11 15 10:05 .DS_Store
drwxr-xr-x  4 wv  136 11 15 10:05 backup
-rw-r--r--  1 wv  339 11 15 10:31 natapp.ddd.top.conf
-rw-r--r--  1 wv  940 11 15 09:39 natapp.ddd.top.csr
-rw-r--r--  1 wv  175 11 15 09:39 natapp.ddd.top.csr.conf
-rw-r--r--  1 wv 1679 11 15 09:39 natapp.ddd.top.key
➜  .acme.sh

**Comment by wv1124** [comment]
acme.sh --issue -d example.com fail

**Comment by liudy2162** [comment]
I also no such file fullchain.cer , how do you solve it ? Could you tell me please ?

**Comment by nicbou** [comment]
Same here, 2 years later.

**Comment by hacknorris-aka-penguin** [comment]
SAME HERE !!!!
