### ISSUE TITLE
Certificate path should not depend of the certificate type

### ISSUE THREAD

**Issue by fdutheil** [Neilpang/acme.sh#1114]
Hello,

Just started to use acme.sh to replace dehydrated as it supports natively a DNS API I'm switching to (Gandi LiveDNS).
Manually, so far so good, except one irritating thing I saw when implementing acme.sh use in my Ansible playbook: 
RSA materials go to ~/.acme.sh/[FQDN]/
ECC materials go to ~/.acme.sh/[FQDN]_ecc/

I was quite baffled...
Is it possible not to do that, and simply use the same predictable path for everything (~/.acme.sh/[FQDN]/), please? :)
Adding something related to the crypto algo used makes the automation logic really more complex and ugly.

**Comment by FernandoMiguel** [comment]
You should not be using that folder for anything.
Ideally you run
 https://github.com/Neilpang/acme.sh#3-install-the-issued-cert-to-apachenginx-etc
To place it somewhere else.

**Comment by Neilpang** [comment]
yes,  the path is for internal use only.  you should use the `--installcert` command to copy the cert/key files to wherever you want.

**Comment by fdutheil** [comment]
OK, thank you for your answers, I see what you mean and the "logic" of acme.sh now. Let me detail what I meant. 

Your suggestion mainly applies to trivial setups (for example, where acme.sh is on the same host that use the certificate you manually generate).
When that's not the case, the ```--installcert``` + exhaustive & explicit ```--cert-file/--key-file/--ca-file/--fullchain-file``` mechanism is mandatory and should be used a a workaround to duplicate certificates generated to other temporary locations and then deploy them on remote host. That is then the responsability of the automation process to deal with it and provide with the predictable paths. That is a worthy workaround (I'll do that for now), yet it adds complexity/steps to the whole automation process.

You have a great tool doing lots of things to help people with simple setups. Some people need to take another route: having predictable paths are freaking great in this aspect. I have to say it: dehydrated creates links with generic and predictable names pointing to the last certificates/keys generated, CA CRT, chains, etc all by itself. That is awesome when you simple have to take it from here (with automation) and then simply have to deploy them right away.

Regards,
Florent

**Comment by FernandoMiguel** [comment]
I have a vague idea there is an EXPORT with the path to the certs.
@Neilpang can confirm that.

if so, you can use that as the path for your automation to send the certs somewhere

**Comment by Neilpang** [comment]
>> That is then the responsability of the automation process to deal with it and provide with the predictable paths. 

Yes,  acme.sh is designed to work with RSA and ECC dual certs cases.  That's why the path is different.
And a user should not take care of the internal file structure, they should just rely on the public commandline parameters.

`--issue`  and then `--installcert/--deploy`,  that's the correct steps.

That makes things much simple.

**Comment by Neilpang** [comment]
@FernandoMiguel 

>> I have a vague idea there is an EXPORT with the path to the certs.

Don't touch it, it hurts.  :)

**Comment by fdutheil** [comment]
Thank you both of you for your time, it's much clearer now.

Then I should have read more carefully the "3. Install the issued cert to Apache/Nginx etc." section of the Readme, but I was mislead by it's title. I thought ```--installcert``` was doing automatic installation into a webserver (which seems to be what ```--deploy``` does), and all I needed was to get my hands on the certificate, like an "export" feature.
