### ISSUE TITLE
大神既然sh写的这么6 那么 问一个shell脚本编写的问题

### ISSUE THREAD

**Issue by daiaji** [Neilpang/acme.sh#1118]
就是获取当前脚本所在目录
这东西有没有现成的变量啊
`echo "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"`
找了一下也只找到这个了

似乎我用的zsh也没有这样的特殊变量

**Comment by Neilpang** [comment]
不是大神.
据我所知,  没有一个统一的方法能获得脚本位置.

不过你可以看看这里的实现:
https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L2101

看看 `_SCRIPT_HOME` 的获取方法.

**Comment by jemyzhang** [comment]
@daiaji 试试看
echo "$( cd "$( dirname "${BASH_SOURCE[0]:-$0}" )" && pwd )"
