### ISSUE TITLE
Display /home/username/.acme.sh/acme.sh.env: Not find while login super user

### ISSUE THREAD

**Issue by mskian** [Neilpang/acme.sh#1119]
`/home/username/.acme.sh/acme.sh.env: No such file or directory` 
how to fix this?
while login to superuser it got this error
actually ghost.org team moved acme.sh to  /etc/ folder 
so I remove the acme.sh from home/superuser folder

**Comment by Neilpang** [comment]
check your `~/.bashrc` or `~/.bash_profile` or `~/.profile`
remove the acme.sh.env line.

**Comment by mskian** [comment]
Done Fixed :100:

**Comment by tainguyenbp** [comment]
> check your `~/.bashrc` or `~/.bash_profile` or `~/.profile`
> remove the acme.sh.env line.

tks you

**Comment by gitk01n** [comment]
done fixed， thx
