### ISSUE TITLE
Change home path

### ISSUE THREAD

**Issue by WordlessEcho** [Neilpang/acme.sh#1120]
Change `.bashrc` and `.profile` from:
```bash
. "/home/[Old username]/.acme.sh/acme.sh.env"
```
to:
```bash
. /home/[New username]/.acme.sh/acme.sh.env"
```

And, upgrade `acme.sh`:
```shell
acme.sh --upgrade
```

But DNS API and corn job is lost.

**Comment by dugwood** [comment]
Cron job must have been created with the `Old username` hence cannot run anymore. Try, as root:
```
root# crontab -l -u oldusername
root# crontab -l -u newusername
```
If you see something in the oldusername crontab, switch to this user and remove cronjob:
```acme.sh --uninstall-cronjob```
If you don't see something in the newusername crontab, switch to this user and install cronjob:
```acme.sh --install-cronjob```
