### ISSUE TITLE
World readable key permissions when using --key-file

### ISSUE THREAD

**Issue by kolargol** [Neilpang/acme.sh#1123]
Hi,

acme.sh when using options --key-file to place certificates in place, copy key-file with world readable permission. This is security issue. 

Tested: latest master

**Comment by FernandoMiguel** [comment]
See https://github.com/Neilpang/acme.sh/issues/328

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/how-about-the-private-key-access-modes,--chmod,-or-chown-or-umask

**Comment by kolargol** [comment]
thanks for pointing me to the discussions about that. However i do not agree with assumptions. In general good practice it is never good to leave private keys to be read by any user. Yes - I have read that directory is not readable by others, but once it's copied by install command, wrong permissions are moved to new location.
I also do not agree with: 

"We respect the users choice most. We trust you more than ourselves. you can change the file modes manually, you know your system best. We respect your choice."

this assume users know what they are doing - and this is false. Most users do not care about that, and it would be good if proper file permissions were applied into place. 

Also - there is lack of consequences: you are protecting directory where private keys are held, but when using command to install it out-of-scope of the dir - you are removing that restriction, this is confusing and prone to users errors in implementation.

Last is that "chmod(1) might vary from platform to platform". As far as I know few systems with *nix, *bsd i never faced different implementation of chmod. So hard to agree with that :)

thanks,

**Comment by Neilpang** [comment]
There is not a suitable default access mode.
There could be issues if the file is not readable by other users, for example, www-data or nginx.
We must keep acme.sh work in as more cases as possible out of the box.
If a user cares about the private key, he could change the mode by himself.
And the domain private key is not that much critical. you can revoke the cert anytime.

**Comment by kolargol** [comment]
well, apache, nginx, dovecot, postfix and many more start with priv(root) and drop to unprivileged user. That's why since ever key permissions are set to 0400. 
File permissions are there for a reason, when you left keyfile read to the world, you can easy imagine php or whatever script that read that file, or badly configured apache - that can read keyfile, and user even do not be aware of this (apache run as www, normally when you set o-rwx that user is unable to read keyfile, but since you set o+r - anyone can...)
If private key is not critical for you then i don't know what is? Maybe we should just drop all UNIX file permissions as they only bother users?

**Comment by Neilpang** [comment]
>> you can easy imagine php or whatever script that read that file

The cert/key file is usually placed in somewhere like: '/etc/nginx/ssl/{somepath}/some.key'
I don't think the path '/etc/nginx/ssl/{somepath}/' is readable by the "script" by default.

>> If private key is not critical for you then i don't know what is? Maybe we should just drop all UNIX file permissions as they only bother users?

I didn't say the private key is **"not critical"**,  I said it is **"not that much critical"**.  It's just a domain key, not your account key.  It's usually used just for ssl/tls connection.  In most ssl/tls connections, the cert/key is even just used for signature,  not for encryption at all.   Ok, let's imagine the worst case:  your domain key is read by someone else.  So.....  so, what ?  It's not the end of the world.  As long as your server is under your control.  what can the cert/key be used for ?  man-in-the-middle attack ?  Come on, MIMT is too expensive to  attack a site using just free letsencrypt cert .   If the site is worthy enough for a MIMT, I think the sys admin must remember to configure a correct file access mode of such a "critical private key",  does he ?  Once the admin set correct access mode of the file, it will be kept by acme.sh, and will never be changed.

And you can revoke your cert anytime.

Yes, I don't mean the private key is not critical at all.  I just mean the private key is not as critical as the name seems to be. Don't be so nervous first. It's not the end of the world.

No matter how secure the software is,  the human beings is usually the weakest part of the whole system.
The user/sysadmin  need to  configure the correct access mode of the folders/files.

As a common purpose script,  sufficient security(not extreme security ) and wide usability are the critical goals of acme.sh.

However, I'm open for any advice that can make acme.sh better.  The biggest concern I have is: if we make the private key to `chmod 600`,  a server that is running under a different user would have trouble reading the key file.
what do you think ?  do you have any better solution ?

**Comment by FernandoMiguel** [comment]
If it is being run by a different user, then who ever is setting up, should be educated to install it to the right place and the right owner.
If they fail, the system will fail, and they will be forced to debug.

It's just a bit better than unsafe key permissions

**Comment by kolargol** [comment]
@Neilpang thing that MIMT is expensive is a myth. MIMT cost nothing and anyone who can use google and have little knowledge can commit MIMT using cheapest laptop, on almost any WiFi network or ethernet. Of course - taping into XP (eXchange Point) is more difficult, but at the end also not expensive at all, believe me - i was working for 7 years in one of the biggest ISP in Europe and i know things or to about XP security, but that's out of the scope of this discussion and not the point of it.
Remember that even one successful MIMT attack on non-critical server can ruin people life...

I think as a software vendor who delivers software, your responsibility it to provide software with all the specs that meet good practice and recommendations. You should not focus on making it work with all possible situation - because this is simply impossible, but rather set a standard and users should comply with it. 

And finally to some more tech specs: 

> The biggest concern I have is: if we make the private key to chmod 600, a server that is running under a different user would have trouble reading the key file.

Any daemon who need to run below port 1024 need root privileges - so ower and o+r do not matter at all, other then this - which i know and are common, read keyfile as root before dropping out priv. 
On the other side you have software, like ejabberd that fail to start if private key is set to o+r - and there is more software that at last print warning, or refuse to start with insecure file permissions. 

last thing, is that this issue probably classify to assign CVE as it triggers insecure file permission on sensitive data. Remember that linux is considered multi-user environment, so if you set o+r on sensitive data it might be candidate to CVE. 

and now really last thing in this comment - don't take my nervousness to serious, i use acme.sh in many many servers and i love it, and i appreciate your work on this software.

**Comment by kolargol** [comment]
Thank you.
