### ISSUE TITLE
save/read dnsapi related variables to conf file

### ISSUE THREAD

**Issue by widewing** [Neilpang/acme.sh#1135]
please support this so we can automate cert updating with dns mode

**Comment by Neilpang** [comment]
give me more details please.

**Comment by widewing** [comment]
when we use dns mode with dnsapi, we set the username and password in the environment variable according to the doc, and the dnsapi hook script read it directly, that's ok for the first time, but it's not saved to $domain.conf. If we add them manually, the hook script cannot read it. So next time in cron job it cannot load the credentials and not able to update the cert.

**Comment by Neilpang** [comment]
which dns api hook you are using ?

**Comment by widewing** [comment]
I'm using dns_he.sh but I think this issue is generic

**Comment by Neilpang** [comment]
The username and password are saved to the account conf here:
https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_he.sh#L28

So, I don't understand what your problem is ?

**Comment by widewing** [comment]
ok I see the _saveaccountconf in the script.. but it not appear in my conf file.. weird

**Comment by Neilpang** [comment]
it's saved in the account.conf,  not in the domain.conf file.

**Comment by widewing** [comment]
Wow.. awesome! thank you! sorry i missed this file
