### ISSUE TITLE
How to remove a certificate from the list of certs to be renewed (missing doc)

### ISSUE THREAD

**Issue by fwolfst** [Neilpang/acme.sh#1137]
We issue certificates for subdomains sometimes and will need this only for a couple of hours/days/weeks/months. I guess to remove these domains from automatic removal via the cron job all I have to do is to remove the respective directories in `~/.acme.sh` . If thats the case I can edit the README and create a PR (I would put it as "12 - How to remove a domain"). I will do tests later whether this happens also when revoking a cert. In any case, the documentation (README) should be updated imho and I am happy to help out.

**Comment by FernandoMiguel** [comment]
You can delete the cert folder or use acme remove 

-- 
Fernando Miguel

**Comment by fwolfst** [comment]
@FernandoMiguel Great, thanks.
`  --remove                 Remove the cert from https://github.com/Neilpang/acme.sh`. I can adjust that help text (it should be "remove the certificate from list of certificates known to acme.sh", right?).

**Comment by Neilpang** [comment]
right.

**Comment by daustany** [comment]
Remove-Item -Path "C:\ProgramData\win-acme\*" -Recurse -Force
