### ISSUE TITLE
Dual RSA/ECC cert generation

### ISSUE THREAD

**Issue by blagoeres** [Neilpang/acme.sh#1141]
How to generate, for example 2048-bit RSA and ECDSA P-256 in one command ? Is that possible with acme.sh ? 

Sorry for asking questions here.

**Comment by warrenski** [comment]
I don't believe it's possible, you'll have to do them separately, for example:

```
acme.sh --issue -d example.com \
    --webroot /var/www/html \
    -d www.example.com

```
```
acme.sh --issue -d example.com \
    --webroot /var/www/html \
    -d www.example.com \
    --keylength ec-256

```

**Comment by blagoeres** [comment]
ok thanks.
