### ISSUE TITLE
Question: stateless mode config

### ISSUE THREAD

**Issue by sawan** [Neilpang/acme.sh#1143]
Is it safe to leave the sateless mode config block in the Nginx configuration as shown in the wiki
[here](https://github.com/Neilpang/acme.sh/wiki/Stateless-Mode) after you have completed the issue process? That is, is it required for the renewal? 

Nginx config block:

```
http {
...
server {
...
  location ~ "^/\.well-known/acme-challenge/([-_a-zA-Z0-9]+)$" {
    default_type text/plain;
    return 200 "$1.6fXAG9VyG0IahirPEU2ZerUtItW2DHzDzD9wZaEKpqd";
  }
...
}
}
```

**Comment by Neilpang** [comment]
1. Yes, it's safe.
2. Yes, you need to keep it there.   it's needed for renewal.

**Comment by sawan** [comment]
Appreciated.
