### ISSUE TITLE
dns_pdns not picking up config from acme.sh.env and complaining of missing params

### ISSUE THREAD

**Issue by kobuki** [Neilpang/acme.sh#1146]
Steps to reproduce
------------------

Add pdns details to `acme.sh.env`:

```
export PDNS_Url="http://x.x.x.x:8001"
export PDNS_ServerId="localhost"
export PDNS_Token="secret token"
export PDNS_Ttl=60
```

Now try to issue:

`# acme.sh -d host.example.com --dns dns_pdns --issue --reloadcmd 'service nginx reload'`

And get this error:

```
[Fri Dec 15 13:10:34 CET 2017] You don't specify PowerDNS address.
[Fri Dec 15 13:10:34 CET 2017] Please set PDNS_Url and try again.
[Fri Dec 15 13:10:34 CET 2017] Error add txt for domain:_acme-challenge.host.example.com
```

It only works when I export the variables directly in shell before starting the issue command.

**Comment by kobuki** [comment]
I think I found the cause of the issue. The setup changed in recent versions and the line that gets added at the end of .bashrc is now `. "/etc/.acme.sh/acme.sh.env"`.

This has 2 implications:
* the proper environment is only provided when `.bashrc` gets loaded
* now sensitive data is stored in shell variables permanently for any process to access, running in the same shell environment

I think that `acme.sh.env` should be split to 2 parts: one holding the basic general settings for the acme.sh script; another one holding the sensitive DNS API stuff and this latter one should be loaded at script startup only.

**Comment by Neilpang** [comment]
never  modify the "acme.sh.env" manually.

your pdns credentials are saved automatically in    "account.conf",  not in the env file.

The credentials will be reused  automatically.

if there is problem, please paste log with `--debug 2`.

**Comment by kobuki** [comment]
OK, I can accept that - even though the end result is the same for later runs, since envvars get added to `acme.sh.env`.

Could you please comment on my 2nd point?

**Comment by Neilpang** [comment]
The credentials in account.conf is only accessible by acme.sh.  It's not public envs.
