### ISSUE TITLE
Verify error: Invalid Response

### ISSUE THREAD

**Issue by codifyer** [Neilpang/acme.sh#1147]
I'm trying to use acme.sh to automate https setup on a tomcat server.  
I've setup tomcat to run on port 80 with proper dns setting (customer1.spastasolutions.com). It runs on Amazon Linux.   
when I run   
`$ acme.sh --issue -d customer1.spashtasolutions.com -w /opt/tomcat/webapps`  
I get error 
`customer1.spashtasolutions.com:Verify error:Invalid response from http://customer1.spashtasolutions.com/.well-known/acme-challenge/mh0w6Ga2zCpzRZEdMjIe8AAmpztV-rVq6y8Im10-C5I:` . 

If I run that URL (http://customer1.spashtasolutions.com/.well-known/acme-challenge/mh0w6Ga2zCpzRZEdMjIe8AAmpztV-rVq6y8Im10-C5I) on the browser, I get proper response like below . 
`mh0w6Ga2zCpzRZEdMjIe8AAmpztV-rVq6y8Im10-C5I.noPN1DvgMzGG4Et5bnysoggWLaLvd9CljlGUmKV6QiA`

I spent over a day trying to figure it out but it completely beats me. Wondering if I'm missing something here. I have attached log file of the run. Any help is appreciated.

Steps to reproduce
------------------
- Install acme.sh
- tomcat running on Amazon Linux serving on port 80.
- dns A record setup appropriately to point to correct IP of tomcat server
- run `acme.sh --issue -d customer1.spashtasolutions.com -w /opt/tomcat/webapps` as root

Debug log
-----------------

[acme.log](https://github.com/Neilpang/acme.sh/files/1565567/acme.log)

**Comment by FernandoMiguel** [comment]
it would seem your tomcat is serving garbage to LE servers
```
    "detail": "Invalid response from http://customer1.spashtasolutions.com/.well-known/acme-challenge/mh0w6Ga2zCpzRZEdMjIe8AAmpztV-rVq6y8Im10-C5I: \"\u003c!doctype html\u003e\u003chtml lang=\"en\"\u003e\u003chead\u003e\u003ctitle\u003eHTTP Status 404 – Not Found\u003c/title\u003e\u003cstyle type=\"text/css\"\u003eh1 {font-family:Tahoma,A\"",
    "status": 403
```

also, consider testing against the staging servers to avoid hitting the API limits

**Comment by codifyer** [comment]
Thanks @FernandoMiguel   Any idea why tomcat would serve garbage to LE, while it(tomcat) responds correctly when URL is invoked from browser or via curl?  Wondering if it has got something to do with the time when acme.sh puts .well-known files and file being made available by tomcat? Is it possible to put a, say 10 sec delay between inserting .well-known files and LE running the verification query?

**Comment by FernandoMiguel** [comment]
i also tested with curl and was fine.
and like you, i suspect the 2 sec time might have not been enough. but i dont see an option to change that (without modifying the acme.sh source file)

have you tried running again, against staging server? 
--staging

**Comment by codifyer** [comment]
Seems to work with --staging option  !!!
[acme-staging.log](https://github.com/Neilpang/acme.sh/files/1565614/acme-staging.log)

**Comment by FernandoMiguel** [comment]
have you tried again with production servers?
maybe there was a temporary problem at the time?

do keep in mind the API limits when testing production

**Comment by codifyer** [comment]
I've tried at least ten times on production server over 24 hr period and it has never passed. Maybe its a tomcat thing (using tomcat 8.5). I'm considering increasing sleep from 2 to 10 sec and testing. I'm assuming this is the code   (line 3711)
```
     _debug "sleep 2 secs to verify"   
     sleep 2  
     _debug "checking"  
```

**Comment by FernandoMiguel** [comment]
go for it.

https://letsencrypt.org/docs/rate-limits/
you can only request 20 per week.
careful

**Comment by codifyer** [comment]
ran it with ` sleep 10`, on prod.  No joy, same error - tomcat sending garbage to LE servers.  But running the URL with curl immediately afterwords works just fine.   
Then ran cert issue command again with --staging and it succeeded !!!   
I'm bit lost on whats going on here.   
Has anyone else tried it with tomcat? Any gotchas I should be aware of?

**Comment by codifyer** [comment]
Think I might have hit the solution. I was modifying the wrong sleep statement. The `sleep 2` on line 3722 is giving 2 sec for my server to respond to the challenge, for which 2 sec seems good.  
I added a sleep just before `__trigger_validation` and it worked first time. Need to test some more to ensure it is reliable.  
```shell
    sleep 10 # added by codifyer
    if ! __trigger_validation "$uri" "$keyauthorization"; then
      _err "$d:Can not get challenge: $response"
      _clearupwebbroot "$_currentRoot" "$removelevel" "$token"
      _clearup
      _on_issue_err "$_post_hook" "$vlist"
      return 1
    fi
```
