### ISSUE TITLE
阿里云无法自动添加TXT解析

### ISSUE THREAD

**Issue by 1688pc** [Neilpang/acme.sh#1150]
阿里云无法自动添加TXT解析，只能通过手动添加TXT记录DNS验证方式签发证书。
已确认Ali_Key和Ali_Secret无误
![_li](https://user-images.githubusercontent.com/14054316/34282763-ff7f3924-e702-11e7-9b02-3c885b685cf2.jpg)
尝试多次后提示创建新TXT解析时出错，最近失败的授权太多。
![22](https://user-images.githubusercontent.com/14054316/34282811-3d7ea4ee-e703-11e7-8929-67302ea2f946.PNG)
只能通过手动添加TXT记录DNS验证方式签发证书。DDnspod可以自动添加TXT记录DNS验证方式签发证书。
系统：华硕AC68U koolshare merlin改版固件X7.7
在vps上的Centos 6测试了一下正常
经测试是系统的问题。

**Comment by Neilpang** [comment]
为什么不读一下 红色的 错误提示呢?

**Comment by 1688pc** [comment]
@Neilpang 红色的 错误提示是我尝试很多次后才出现的，本人英文盲，纯机翻，我的理解是阿里云有请求次数限制，被限制了（换一个域名就可以继续申请证书）。
另外在虚拟机CentOS6和CentOS7下多次测试均可以自动添加TXT解析，应该是路由器固件的问题（估计可能需要依赖某种环境或软件，而路由器精减了）。
在这里还要感谢开发者开发出唯一 一个能让我在路由器上申请到证书的软件。

**Comment by Neilpang** [comment]
@1688pc  抱歉, 我不清楚你的情况.  那我给你翻译一下. 
说人话就是: 脚本没能发现你设置的 Ali_Key和Ali_Secret.
换句话说,  你设置的 Ali_Key和Ali_Secret 方式不对, 或者根本就没有设置.

https://github.com/Neilpang/acme.sh/tree/master/dnsapi#11-use-aliyun-domain-api-to-automatically-issue-cert


先执行这两句: 
```
export Ali_Key="sdfsdfsdfljlbjkljlkjsdfoiwje"
export Ali_Secret="jlsdflanljkljlfdsaklkjflsa"
```

然后在 issue

**Comment by 1688pc** [comment]
`echo -e "Ali_Key='sdfsdfsdfljlbjkljlkjsdfoiwje'\nAli_Secret='jlsdflanljkljlfdsaklkjflsa'" >>/root/acme.sh/account.conf`
已经设置了Ali_Key和Ali_Secret并且在account.conf里已经有Ali_Key和Ali_Secret了，一样的执行命令在路由器里不能自动添加TXT，在CentOS 7里就能自动添加TXT，并且这位发教程的人也和我遇到的情况差不多http://koolshare.cn/thread-126778-1-1.html

**Comment by Neilpang** [comment]
请按照我上面的建议做,   这也是正常建议的方式.  你会发现生活变得简单.
acme.sh 会发现并自动保存Ali_Key和Ali_Secret 到合适的位置.

另外, 补充一句, 那个教程太早了,  现在已经不适用: /root/acme.sh/account.conf  这个文件了.

你可以回帖提醒一下,   使用我建议的方式. 这样在未来也会保持兼容性.

**Comment by 1688pc** [comment]
@Neilpang 好的，感谢解答。

**Comment by tianjianchn** [comment]
@1688pc 是对的，顺便纠正下一个手误，应改为：
```
date -u "+%Y-%m-%dT%H%M%SZ"
```
