### ISSUE TITLE
Domain name blocking acme?

### ISSUE THREAD

**Issue by wouterverduin** [Neilpang/acme.sh#1156]
I am running into the following errors while using acme.sh on my pfsense. Both on the latest updates. I am also running into similar problems when i attempted to use certbot on one of my ubuntu servers. 

My domain name points to my IP adress and i got a server listening with ports 80 and 443 forwarded to it. However i cant seem to issue an lets encrypt certificate..

What am i missing? Or is this a problem with my domain name not allowing letsencrypt?

I keep running in this error: XXXX.nl:Verify error:Invalid response from http://XXXX.nl/.well-known/acme-challenge/aA8nxH4358J-Bgqoz-xBU8boAZ4C1QDW3M0792Gm_lI: 

Log:
[acme (2).txt](https://github.com/Neilpang/acme.sh/files/1595406/acme.2.txt)

**Comment by FernandoMiguel** [comment]
I can't resolve
wouterverduin.nl


And from the log you are using the staging server
