### ISSUE TITLE
File path is ignored

### ISSUE THREAD

**Issue by greencopper** [Neilpang/acme.sh#1157]
Latest version from GitHub is used.

There are no issues to report from the debug related to the issue. The certificates gets installed without issues except for a wrong path.

Run the "acme.sh" as root, from the root directory, and use the options "--cert-file", "--key-file", "--ca-file", and "--fullchain-file". I point them all to /etc/ssl, which root has full write access to.

The certificates gets installed in /root/.acme.sh/ and not in /etc/ssl.

**Comment by sjau** [comment]
please provide the full command you have used.

**Comment by greencopper** [comment]
The full command is:

```
./acme.sh --issue --dns dns_mydnsprovider -d mail.example.com \
  --cert-file /etc/ssl/mail.example.com.crt \
  --key-file /etc/ssl/private/mail.example.com.key \
  --ca-file /etc/ssl/ca.crt \
  --fullchain-file /etc/ssl/fullchain.crt
```

The command is run as root in roots home directory. Everything gets installed in `/root/` and not in `/etc/ssl/`

**Comment by sjau** [comment]
--issue and --install are two seperate commands.

**Comment by greencopper** [comment]
So you have to run `--install` before using `--issue` ?

**Comment by sjau** [comment]
If acme.sh is already installed, follow first

https://github.com/Neilpang/acme.sh#2-just-issue-a-cert

then

https://github.com/Neilpang/acme.sh#3-install-the-issued-cert-to-apachenginx-etc

**Comment by greencopper** [comment]
Ah, we have a misunderstanding, maybe because I wrote "Everything gets installed in /root/ and not in /etc/ssl/".

I am sorry, what I mean is that when I run the `--issue` command as illustrated above, the certificate files doesn't get saved in /etc/ssl/, but in /root instead.

**Comment by sjau** [comment]
No, issue doesn't "install" anything. It asks for LE server to hands out certificates and it stores them according to it's own logic. Then you use the install command to get the certs where you want them to be.

It's a 2 step process

**Comment by greencopper** [comment]
Oh! Now I get it! Thank you very much for taking the time to clarifying this. I'm closing the issue.
