### ISSUE TITLE
提交 csr 到 letsencrypt 为何调用 _url_replace?

### ISSUE THREAD

**Issue by deepzz0** [Neilpang/acme.sh#1160]
我想问下，在向 letsencrypt 提交 csr 的时候，为什么会调用 _url_replace 这个函数。替换掉那些字符后 letsencrypt 是如何识别的

**Comment by Neilpang** [comment]
这是一种 base64 url 编码方式.   其实 base64 并不是唯一的编码方式, 而是一个家族. 有很多变种. 为的时在不同的协议上传输.
具体可以参看 维基百科.
