### ISSUE TITLE
acme.sh --upgrade should only upgrade to a release version

### ISSUE THREAD

**Issue by dugwood** [Neilpang/acme.sh#1162]
Running `acme --upgrade` should not install the master version but the latest released version. Fun is the fact that this very issue report starts with:

> If it is a bug report:
> - make sure you are able to repro it on the **latest released version**. 
> You can install the latest version by: `acme.sh --upgrade`

But it's not a released version, it's the latest commit.

Steps to reproduce
------------------
Run `acme --upgrade` and you'll end up with:
```
$ acme.sh -v
https://github.com/Neilpang/acme.sh
v2.7.6
```
Instead of the current latest release (as of 2017-01-05): 2.7.5

Perhaps we should introduce:
--upgrade => for the latest released version
--upgrade --from-master => for the latest master commit

May I create a PR for this?

**Comment by Neilpang** [comment]
Sorry,  that's  designed.
upgrade means to use the latest code.   The master branch is the latest stable code.

**Comment by dugwood** [comment]
That's what reads in the console:
`  --upgrade                Upgrade acme.sh to the latest code from https://github.com/Neilpang/acme.sh.`

The thing is I use the release page to known when there's a new release, and if I run acme.sh --upgrade, I would get a new un-released version, so I'm ahead the new release.

Perhaps the version in the `acme.sh` should be a temporary one? Such as `2.7.6-dev`? Or can we have an option to force a specific revision? For example:
https://github.com/Neilpang/acme.sh/tree/2.7.5
This is the tag for the release, so I should be able to ask for an installation of exactly this one. That's just adding a `--branch 2.7.5` in the `git pull` request you may run.

So inverse what I've proposed:
- keep `upgrade` for latest committed revision
- add `upgrade 2.7.5` for specific stable release

Or remove releases :-) Or I'll change everything and use the latest commit to know if you've updated anything, but I'll have a lot of work when there's 10 commits a day.

The real question: how can I be up to date? Running `aptitude` or `composer` helps with this concern, but in the case of `acme.sh`, there's no real option...

Thoughts?

**Comment by dugwood** [comment]
I see there's a variable for this:
https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L5087

=> so I may be able to set `BRANCH` to `2.7.5` and have the corresponding version.

**Comment by Neilpang** [comment]
Usually,  it's ok to use the released version.  It's stable and has no known big bugs.

>> how can I be up to date?

You can upgrade anytime,  actually, we have a `--auto-upgrade` option:

```sh
acme.sh  --upgrade  --auto-upgrade
```

it can upgrade everyday to keep it fresh.  Autoupgrade will keep compatible, and migrate any changes automatically.

**Comment by Neilpang** [comment]
>> so I may be able to set BRANCH to 2.7.5

Yes

**Comment by dugwood** [comment]
Thanks for your input. I'd rather upgrade it on my end, but the `--auto-upgrade` was worth noticing.

I've just tried `export BRANCH="2.7.5"` and it worked great. I'll stick with it for now!

Thanks for your tool :-)
