### ISSUE TITLE
not idn domain, but ask install 'idn' command first. 

### ISSUE THREAD

**Issue by bannedbook** [Neilpang/acme.sh#1164]
acme.sh --issue -d blog.thedomain.org -d *.blog.thedomain.org --dns dns_cf --debug 2

[...UTC 2018] It seems that *.blog.thedomain.org is an IDN( Internationalized Domain Names), please install 'idn' command first.

**Comment by Neilpang** [comment]
请先 切换到 branch v2

```sh
export BRANCH=2
curl https://get.acme.sh | sh

```

**Comment by bannedbook** [comment]
thanks!
After follow you,

# acme.sh --issue -d blog.bannedbook.org  -d *.blog.bannedbook.org --dns  dns_cf
[Sat Jan  6 12:08:53 UTC 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Sat Jan  6 12:08:53 UTC 2018] Can not init api.
[Sat Jan  6 12:08:53 UTC 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Sat Jan  6 12:08:53 UTC 2018] Can not init api.
[Sat Jan  6 12:08:53 UTC 2018] Registering account
[Sat Jan  6 12:08:53 UTC 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Sat Jan  6 12:08:53 UTC 2018] Can not connect to https://acme-v02.api.letsencrypt.org/directory to get nonce.
[Sat Jan  6 12:08:53 UTC 2018] Register account Error: 
[Sat Jan  6 12:08:53 UTC 2018] Please add '--debug' or '--log' to check more details.
[Sat Jan  6 12:08:53 UTC 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by bannedbook** [comment]
# acme.sh --issue -d blog.bannedbook.org  -d *.blog.bannedbook.org --dns  dns_cf --debug 2
[Sat Jan  6 12:11:50 UTC 2018] Lets find script dir.
[Sat Jan  6 12:11:50 UTC 2018] _SCRIPT_='/root/.acme.sh/acme.sh'
[Sat Jan  6 12:11:50 UTC 2018] _script='/root/.acme.sh/acme.sh'
[Sat Jan  6 12:11:50 UTC 2018] _script_home='/root/.acme.sh'
[Sat Jan  6 12:11:50 UTC 2018] Using config home:/root/.acme.sh
[Sat Jan  6 12:11:50 UTC 2018] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.7.6
[Sat Jan  6 12:11:50 UTC 2018] Using config home:/root/.acme.sh
[Sat Jan  6 12:11:50 UTC 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jan  6 12:11:50 UTC 2018] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Sat Jan  6 12:11:50 UTC 2018] DOMAIN_PATH='/root/.acme.sh/blog.bannedbook.org'
[Sat Jan  6 12:11:50 UTC 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sat Jan  6 12:11:50 UTC 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sat Jan  6 12:11:50 UTC 2018] GET
[Sat Jan  6 12:11:50 UTC 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jan  6 12:11:50 UTC 2018] timeout=
[Sat Jan  6 12:11:50 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.VW7ER7Mcjj '
[Sat Jan  6 12:11:50 UTC 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Sat Jan  6 12:11:50 UTC 2018] Here is the curl dump log:
[Sat Jan  6 12:11:50 UTC 2018] == Info: Hostname was NOT found in DNS cache
== Info: Could not resolve host: acme-v02.api.letsencrypt.org
== Info: Closing connection 0
[Sat Jan  6 12:11:50 UTC 2018] ret='6'
[Sat Jan  6 12:11:50 UTC 2018] response
[Sat Jan  6 12:11:50 UTC 2018] Can not init api.
[Sat Jan  6 12:11:50 UTC 2018] Le_NextRenewTime
[Sat Jan  6 12:11:50 UTC 2018] _on_before_issue
[Sat Jan  6 12:11:50 UTC 2018] 'dns_cf' does not contain 'no'
[Sat Jan  6 12:11:50 UTC 2018] Le_LocalAddress
[Sat Jan  6 12:11:50 UTC 2018] Check for domain='blog.bannedbook.org'
[Sat Jan  6 12:11:50 UTC 2018] _currentRoot='dns_cf'
[Sat Jan  6 12:11:50 UTC 2018] Check for domain='*.blog.bannedbook.org'
[Sat Jan  6 12:11:50 UTC 2018] _currentRoot='dns_cf'
[Sat Jan  6 12:11:50 UTC 2018] 'dns_cf' does not contain 'apache'
[Sat Jan  6 12:11:50 UTC 2018] config file is empty, can not read CA_KEY_HASH
[Sat Jan  6 12:11:50 UTC 2018] _saved_account_key_hash
[Sat Jan  6 12:11:50 UTC 2018] Using config home:/root/.acme.sh
[Sat Jan  6 12:11:50 UTC 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jan  6 12:11:50 UTC 2018] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Sat Jan  6 12:11:50 UTC 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sat Jan  6 12:11:50 UTC 2018] GET
[Sat Jan  6 12:11:50 UTC 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jan  6 12:11:50 UTC 2018] timeout=
[Sat Jan  6 12:11:50 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.Ag6Od2Tx3w '
[Sat Jan  6 12:11:52 UTC 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Sat Jan  6 12:11:52 UTC 2018] Here is the curl dump log:
[Sat Jan  6 12:11:52 UTC 2018] == Info: Hostname was NOT found in DNS cache
== Info: Could not resolve host: acme-v02.api.letsencrypt.org
== Info: Closing connection 0
[Sat Jan  6 12:11:52 UTC 2018] ret='6'
[Sat Jan  6 12:11:52 UTC 2018] response
[Sat Jan  6 12:11:52 UTC 2018] Can not init api.
[Sat Jan  6 12:11:52 UTC 2018] RSA key
[Sat Jan  6 12:11:52 UTC 2018] Registering account
[Sat Jan  6 12:11:52 UTC 2018] url
[Sat Jan  6 12:11:52 UTC 2018] payload='{"termsOfServiceAgreed": true}'
[Sat Jan  6 12:11:52 UTC 2018] Use cached jwk for file: /root/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
[Sat Jan  6 12:11:52 UTC 2018] Get nonce. ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jan  6 12:11:52 UTC 2018] GET
[Sat Jan  6 12:11:52 UTC 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jan  6 12:11:52 UTC 2018] timeout=
[Sat Jan  6 12:11:52 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.Fctpzu4q5J '
[Sat Jan  6 12:11:52 UTC 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Sat Jan  6 12:11:52 UTC 2018] Here is the curl dump log:
[Sat Jan  6 12:11:52 UTC 2018] == Info: Hostname was NOT found in DNS cache
== Info: Could not resolve host: acme-v02.api.letsencrypt.org
== Info: Closing connection 0
[Sat Jan  6 12:11:52 UTC 2018] ret='6'
[Sat Jan  6 12:11:52 UTC 2018] Can not connect to https://acme-v02.api.letsencrypt.org/directory to get nonce.
[Sat Jan  6 12:11:52 UTC 2018] Register account Error: 
[Sat Jan  6 12:11:52 UTC 2018] _on_issue_err
[Sat Jan  6 12:11:52 UTC 2018] Please add '--debug' or '--log' to check more details.
[Sat Jan  6 12:11:52 UTC 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Sat Jan  6 12:11:52 UTC 2018] _chk_vlist
[Sat Jan  6 12:11:53 UTC 2018] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.1t  3 May 2016
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.6.2
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt=-Wl,-z,relro --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module --add-module=/build/nginx-1.6.2/debian/modules/nginx-auth-pam --add-module=/build/nginx-1.6.2/debian/modules/nginx-dav-ext-module --add-module=/build/nginx-1.6.2/debian/modules/nginx-echo --add-module=/build/nginx-1.6.2/debian/modules/nginx-upstream-fair --add-module=/build/nginx-1.6.2/debian/modules/ngx_http_substitutions_filter_module
socat:
socat by Gerhard Rieger - see www.dest-unreach.org
Usage:
socat [options] <bi-address> <bi-address>
   options:
      -V     print version and feature information to stdout, and exit
      -h|-?  print a help text describing command line options and addresses
      -hh    like -h, plus a list of all common address option names
      -hhh   like -hh, plus a list of all available address option names
      -d     increase verbosity (use up to 4 times; 2 are recommended)
      -D     analyze file descriptors before loop
      -ly[facility]  log to syslog, using facility (default is daemon)
      -lf<logfile>   log to file
      -ls            log to stderr (default if no other log)
      -lm[facility]  mixed log mode (stderr during initialization, then syslog)
      -lp<progname>  set the program name used for logging
      -lu            use microseconds for logging timestamps
      -lh            add hostname to log messages
      -v     verbose data traffic, text
      -x     verbose data traffic, hexadecimal
      -b<size_t>     set data buffer size (8192)
      -s     sloppy (continue on error)
      -t<timeout>    wait seconds before closing second channel
      -T<timeout>    total inactivity timeout in seconds
      -u     unidirectional mode (left to right)
      -U     unidirectional mode (right to left)
      -g     do not check option groups
      -L <lockfile>  try to obtain lock, or fail
      -W <lockfile>  try to obtain lock, or wait
      -4     prefer IPv4 if version is not explicitly specified
      -6     prefer IPv6 if version is not explicitly specified
   bi-address:
      pipe[,<opts>]     groups=FD,FIFO
      <single-address>!!<single-address>
      <single-address>
   single-address:
      <address-head>[,<opts>]
   address-head:
      abstract-client:<filename>        groups=FD,SOCKET,RETRY,UNIX
      abstract-connect:<filename>       groups=FD,SOCKET,RETRY,UNIX
      abstract-listen:<filename>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,UNIX
      abstract-recv:<filename>  groups=FD,SOCKET,RETRY,UNIX
      abstract-recvfrom:<filename>      groups=FD,SOCKET,CHILD,RETRY,UNIX
      abstract-sendto:<filename>        groups=FD,SOCKET,RETRY,UNIX
      create:<filename> groups=FD,REG,NAMED
      exec:<command-line>       groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      fd:<num>  groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      gopen:<filename>  groups=FD,FIFO,CHR,BLK,REG,SOCKET,NAMED,OPEN,TERMIOS,UNIX
      interface:<interface>     groups=FD,SOCKET
      ip-datagram:<host>:<protocol>     groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recv:<protocol>        groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recvfrom:<protocol>    groups=FD,SOCKET,CHILD,RANGE,IP4,IP6
      ip-sendto:<host>:<protocol>       groups=FD,SOCKET,IP4,IP6
      ip4-datagram:<host>:<protocol>    groups=FD,SOCKET,RANGE,IP4
      ip4-recv:<protocol>       groups=FD,SOCKET,RANGE,IP4
      ip4-recvfrom:<protocol>   groups=FD,SOCKET,CHILD,RANGE,IP4
      ip4-sendto:<host>:<protocol>      groups=FD,SOCKET,IP4
      ip6-datagram:<host>:<protocol>    groups=FD,SOCKET,RANGE,IP6
      ip6-recv:<protocol>       groups=FD,SOCKET,RANGE,IP6
      ip6-recvfrom:<protocol>   groups=FD,SOCKET,CHILD,RANGE,IP6
      ip6-sendto:<host>:<protocol>      groups=FD,SOCKET,IP6
      open:<filename>   groups=FD,FIFO,CHR,BLK,REG,NAMED,OPEN,TERMIOS
      openssl:<host>:<port>     groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,OPENSSL
      openssl-listen:<port>     groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP,OPENSSL
      pipe:<filename>   groups=FD,FIFO,NAMED,OPEN
      proxy:<proxy-server>:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,HTTP
      pty       groups=FD,NAMED,TERMIOS,PTY
      sctp-connect:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,SCTP
      sctp-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,SCTP
      sctp4-connect:<host>:<port>       groups=FD,SOCKET,CHILD,RETRY,IP4,SCTP
      sctp4-listen:<port>       groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,SCTP
      sctp6-connect:<host>:<port>       groups=FD,SOCKET,CHILD,RETRY,IP6,SCTP
      sctp6-listen:<port>       groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,SCTP
      socket-connect:<domain>:<protocol>:<remote-address>       groups=FD,SOCKET,CHILD,RETRY
      socket-datagram:<domain>:<type>:<protocol>:<remote-address>       groups=FD,SOCKET,RANGE
      socket-listen:<domain>:<protocol>:<local-address> groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE
      socket-recv:<domain>:<type>:<protocol>:<local-address>    groups=FD,SOCKET,RANGE
      socket-recvfrom:<domain>:<type>:<protocol>:<local-address>        groups=FD,SOCKET,CHILD,RANGE
      socket-sendto:<domain>:<type>:<protocol>:<remote-address> groups=FD,SOCKET
      socks4:<socks-server>:<host>:<port>       groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      socks4a:<socks-server>:<host>:<port>      groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      stderr    groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdin     groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdio     groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdout    groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      system:<shell-command>    groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      tcp-connect:<host>:<port> groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP
      tcp-listen:<port> groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP
      tcp4-connect:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP4,TCP
      tcp4-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,TCP
      tcp6-connect:<host>:<port>        groups=FD,SOCKET,CHILD,RETRY,IP6,TCP
      tcp6-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,TCP
      tun[:<ip-addr>/<bits>]    groups=FD,CHR,NAMED,OPEN,INTERFACE
      udp-connect:<host>:<port> groups=FD,SOCKET,IP4,IP6,UDP
      udp-datagram:<host>:<port>        groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-listen:<port> groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,IP6,UDP
      udp-recv:<port>   groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-recvfrom:<port>       groups=FD,SOCKET,CHILD,RANGE,IP4,IP6,UDP
      udp-sendto:<host>:<port>  groups=FD,SOCKET,IP4,IP6,UDP
      udp4-connect:<host>:<port>        groups=FD,SOCKET,IP4,UDP
      udp4-datagram:<remote-address>:<port>     groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,UDP
      udp4-recv:<port>  groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-recvfrom:<host>:<port>       groups=FD,SOCKET,CHILD,RANGE,IP4,UDP
      udp4-sendto:<host>:<port> groups=FD,SOCKET,IP4,UDP
      udp6-connect:<host>:<port>        groups=FD,SOCKET,IP6,UDP
      udp6-datagram:<host>:<port>       groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-listen:<port>        groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP6,UDP
      udp6-recv:<port>  groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-recvfrom:<port>      groups=FD,SOCKET,CHILD,RANGE,IP6,UDP
      udp6-sendto:<host>:<port> groups=FD,SOCKET,IP6,UDP
      unix-client:<filename>    groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-connect:<filename>   groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-listen:<filename>    groups=FD,SOCKET,NAMED,LISTEN,CHILD,RETRY,UNIX
      unix-recv:<filename>      groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-recvfrom:<filename>  groups=FD,SOCKET,NAMED,CHILD,RETRY,UNIX
      unix-sendto:<filename>    groups=FD,SOCKET,NAMED,RETRY,UNIX

**Comment by Neilpang** [comment]
加上 `--test` 命令,  目前 只有测试服务器,  正式服务器没有上线.

```
acme.sh  --issue --test  -d .......
```

**Comment by bannedbook** [comment]
谢谢，加上 --test 可以了
现在这样生成的证书是不是只是测试证书，还不能真正使用？

**Comment by FernandoMiguel** [comment]
Wildcard support?

**Comment by Neilpang** [comment]
@FernandoMiguel 

Yes,  see: https://github.com/Neilpang/acme.sh/issues/934#issuecomment-355738570

**Comment by Lengsir** [comment]
无法安装分支
[Mon May 21 17:12:27 CST 2018] Installing from online archive.
[Mon May 21 17:12:27 CST 2018] Downloading https://github.com/Neilpang/acme.sh/archive/2.tar.gz
[Mon May 21 17:12:30 CST 2018] Extracting 2.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

gzip: stdin: not in gzip format
gtar: Child returned status 1
gtar: Error is not recoverable: exiting now
[Mon May 21 17:12:30 CST 2018] Extraction error.

**Comment by darkrain88** [comment]
ei@aml:~$ acme.sh --upgrade
[Mon Apr 29 12:45:57 CST 2019] Installing from online archive.
[Mon Apr 29 12:45:57 CST 2019] Downloading https://github.com/Neilpang/acme.sh/archive/2.tar.gz
[Mon Apr 29 12:46:00 CST 2019] Extracting 2.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/home/wei/.acme.sh/acme.sh: line 5909: gtar: command not found
[Mon Apr 29 12:46:00 CST 2019] Extraction error.
[Mon Apr 29 12:46:00 CST 2019] Upgrade failed!
