### ISSUE TITLE
DNS Record

### ISSUE THREAD

**Issue by Indjov** [Neilpang/acme.sh#1165]
Hello , 
I have so strange problem with dns recods.
 ./acme.sh --issue --dns -d *.*.info
[Sat Jan  6 14:47:41 EET 2018] Single domain='*.*.info'
[Sat Jan  6 14:47:41 EET 2018] Getting domain auth token for each domain
[Sat Jan  6 14:47:41 EET 2018] Getting webroot for domain='*.*.info'
[Sat Jan  6 14:47:41 EET 2018] Getting new-authz for domain='*.*.info'
[Sat Jan  6 14:47:42 EET 2018] The new-authz request is ok.
[Sat Jan  6 14:47:43 EET 2018] Add the following TXT record:
[Sat Jan  6 14:47:43 EET 2018] Domain: '_acme-challenge.*.*.info'
[Sat Jan  6 14:47:43 EET 2018] TXT value: 'Tt69eCkNIdwBGKHQAzRWSOGTxvftIZ03mg_mBzedVkE'
[Sat Jan  6 14:47:43 EET 2018] Please be aware that you prepend _acme-challenge. before your domain
[Sat Jan  6 14:47:43 EET 2018] so the resulting subdomain will be: _acme-challenge.*.*.info
[Sat Jan  6 14:47:43 EET 2018] Please add the TXT records to the domains, and retry again.
[Sat Jan  6 14:47:43 EET 2018] Please add '--debug' or '--log' to check more details.
[Sat Jan  6 14:47:43 EET 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
nslookup -q=txt _acme-challenge.*.*.info 8.8.8.8|grep text
_acme-challenge.*.info	text = "Tt69eCkNIdwBGKHQAzRWSOGTxvftIZ03mg_mBzedVkE"

So as you can see everything with the dns records it`s ok but still acme tells me that TXT it`s not added.

**Comment by dugwood** [comment]
`..info` will never be a domain name... What are you trying to do?

**Comment by Indjov** [comment]
@dugwood , i`m trying to add SSL for my mikrotik router  by DNS

**Comment by Neilpang** [comment]
@Indjov 
you are using  dns manual mode.  https://github.com/Neilpang/acme.sh#8-use-dns-mode

please use dns api mode instead.

https://github.com/Neilpang/acme.sh#9-automatic-dns-api-integration

**Comment by Indjov** [comment]
But i`m using own dns server ?

**Comment by Neilpang** [comment]
@Indjov 
please update the latest branch v2 code.   and try dns manual mode again:
 https://github.com/Neilpang/acme.sh#8-use-dns-mode

**Comment by Indjov** [comment]
@Neilpang , i do everything but that did`t happend.
I try from 3 differnt machine and the result the same " Please add the TXT records to the domains, and retry again." 
I`m using my own DNS server and as you can see from my firs post that TXT redords it`s added.

**Comment by dugwood** [comment]
@Indjov the issue is that you do an `--issue` every time: this will create a **new** TXT value. See your first message and the latest: different TXT value!

Once you've issued the first request with the domain, you copy the TXT value and set it. Then you run the request again with **`--renew`**. And for renewal, you'll still use `--renew` (or the cron job which will do that too).
