### ISSUE TITLE
Please specify at least one validation method: '--webroot', '--standalone', '--apache', '--nginx' or '--dns' etc.

### ISSUE THREAD

**Issue by klausph** [Neilpang/acme.sh#1168]
hi neilpang
I don't understand this error in log:

"Please specify at least one validation method: '--webroot', '--standalone', '--apache', '--nginx' or '--dns' etc."

there doesn't exist commands or parameters with this name "validation method". 

I have installed in version 2.7.2. whith:
machine:~/.acme.sh # ./acme.sh --issue --apache -d mysubdomain.mydomain.de -d www.mysubdomain.mydomain.de

and cron is:
50 23 * * *     root    /root/.acme.sh/acme.sh --cron --home /root/.acme.sh --log /var/log/acme.log > /dev/null

all has well run since middle of 2017 until december 04 2017.

here are some infos.

`acme.sh --upgrade`
upgrading vom 2.7.2 to actual version 2.7.6

machine:~/.acme.sh # ~/.acme.sh/acme.sh --cron --log /var/log/acme.log --home /root/.acme.sh --force --debug 2
here it is:
[So 7. Jan 17:39:58 CET 2018] Lets find script dir.
[So 7. Jan 17:39:58 CET 2018] _SCRIPT_='/root/.acme.sh/acme.sh'
[So 7. Jan 17:39:58 CET 2018] _script='/root/.acme.sh/acme.sh'
[So 7. Jan 17:39:58 CET 2018] _script_home='/root/.acme.sh'
[So 7. Jan 17:39:58 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:39:58 CET 2018] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.7.6
[So 7. Jan 17:39:58 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:39:58 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:39:58 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:39:58 CET 2018] ===Starting cron===
[So 7. Jan 17:39:58 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:39:58 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:39:58 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:39:58 CET 2018] Installing from online archive.
[So 7. Jan 17:39:58 CET 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[So 7. Jan 17:39:58 CET 2018] GET
[So 7. Jan 17:39:58 CET 2018] url='https://github.com/Neilpang/acme.sh/archive/master.tar.gz'
[So 7. Jan 17:39:58 CET 2018] timeout
[So 7. Jan 17:39:58 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.JdjLW6ciIJ '
[So 7. Jan 17:40:00 CET 2018] ret='0'
[So 7. Jan 17:40:00 CET 2018] Extracting master.tar.gz
[So 7. Jan 17:40:00 CET 2018] Installing to /root/.acme.sh
[So 7. Jan 17:40:00 CET 2018] Installed to /root/.acme.sh/acme.sh
[So 7. Jan 17:40:00 CET 2018] Good, bash is found, so change the shebang to use bash as preferred.
[So 7. Jan 17:40:00 CET 2018] OK
[So 7. Jan 17:40:00 CET 2018] Install success!
[So 7. Jan 17:40:00 CET 2018] Upgrade success!
[So 7. Jan 17:40:00 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:40:00 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:40:00 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:40:00 CET 2018] Auto upgraded to: 2.7.6
[So 7. Jan 17:40:00 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:40:00 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:40:00 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:40:00 CET 2018] _stopRenewOnError
[So 7. Jan 17:40:00 CET 2018] di='/root/.acme.sh/mysubdomain.mydomain.de/'
[So 7. Jan 17:40:00 CET 2018] d='mysubdomain.mydomain.de'
[So 7. Jan 17:40:00 CET 2018] Using config home:/root/.acme.sh
[So 7. Jan 17:40:00 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[So 7. Jan 17:40:00 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[So 7. Jan 17:40:00 CET 2018] DOMAIN_PATH='/root/.acme.sh/mysubdomain.mydomain.de'
[So 7. Jan 17:40:00 CET 2018] Renew: 'mysubdomain.mydomain.de'
Please specify at least one validation method: '--webroot', '--standalone', '--apache', '--nginx' or '--dns' etc.
[So 7. Jan 17:40:00 CET 2018] Return code: 1
[So 7. Jan 17:40:00 CET 2018] Error renew mysubdomain.mydomain.de.
[So 7. Jan 17:40:00 CET 2018] ===End cron===

are there some new parameters or new commands?
thanks a lot, klaus

**Comment by publicarray** [comment]
The error message means that you need to use one of the options: --webroot --standalone --apache --nginx or --dns  to validate that you own the domain that you are attempting to create a signed certificate for. Some options require additional options or arguments. See https://github.com/Neilpang/acme.sh/wiki/Options-and-Params

**Comment by publicarray** [comment]
Hm, If the domain has been validated before than cron should use the saved preferences and should not ask for additional validation.

**Comment by Neilpang** [comment]
can you please show me the conf file at:
```
/root/.acme.sh/mysubdomain.mydomain.de/mysubdomain.mydomain.de.conf'
```

**Comment by klausph** [comment]
here it is...

Le_RealFullChainPath=''
Le_RealCertPath='/etc/apache2/ssl.crt/mysubdomain.mydomain.de.crt'
Le_RealCACertPath=''
Le_RealKeyPath='/etc/apache2/ssl.key/mysubdomain.mydomain.de.key'
Le_ReloadCmd='service apache2 force-reload'
Le_CertCreateTime='1507326617'
Le_CertCreateTimeStr='Fri Oct  6 21:50:17 UTC 2017'
Le_NextRenewTimeStr='Tue Dec  5 21:50:17 UTC 2017'
Le_NextRenewTime='1512424217'

**Comment by klausph** [comment]
Le_RealFullChainPath=''
Le_RealCertPath='/etc/apache2/ssl.crt/mysubdomain.mydomain.de.crt'
Le_RealCACertPath=''
Le_RealKeyPath='/etc/apache2/ssl.key/mysubdomain.mydomain.de.key'
Le_ReloadCmd='service apache2 force-reload'
Le_CertCreateTime='1507326617'
Le_CertCreateTimeStr='Fri Oct  6 21:50:17 UTC 2017'
Le_NextRenewTimeStr='Tue Dec  5 21:50:17 UTC 2017'
Le_NextRenewTime='1512424217'

**Comment by klausph** [comment]
again.... (its NOT closed!)

Le_RealFullChainPath=''
Le_RealCertPath='/etc/apache2/ssl.crt/mysubdomain.mydomain.de.crt'
Le_RealCACertPath=''
Le_RealKeyPath='/etc/apache2/ssl.key/mysubdomain.mydomain.de.key'
Le_ReloadCmd='service apache2 force-reload'
Le_CertCreateTime='1507326617'
Le_CertCreateTimeStr='Fri Oct  6 21:50:17 UTC 2017'
Le_NextRenewTimeStr='Tue Dec  5 21:50:17 UTC 2017'
Le_NextRenewTime='1512424217'

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/issues/1172
