### ISSUE TITLE
Cron is not working - "is not a issued domain, skip"

### ISSUE THREAD

**Issue by dm-m** [Neilpang/acme.sh#1171]
I installed acme.sh as a root user and set up a cronjob for renewal. Here is the job:

`0 4 * * 2 /root/acme/acme.sh --renew -d foo.domain.com >> /var/log/le-renew.log
`

The log shows this one:

```
[Tue Jan  9 11:57:02 EET 2018] Renew: 'foo.domain.com'
[Tue Jan  9 11:57:02 EET 2018] 'foo.domain.com' is not a issued domain, skip.
```

Once I run /root/acme/acme.sh --renew... manually everything works and the output is as expected: 
`Skip, Next renewal time is:`

The issue might not be related to acme.sh but to cron itself and it seems as the command is being run as a normal user (I managed to replicate the same message with "sudo" being logged as a user), however I set up cron when being root.

Does anyone have any ideas on that?

**Comment by dugwood** [comment]
Add `--debug` in the cron command.

Also it makes me think of #1163

**Comment by Neilpang** [comment]
Never change the default cronjob entry, unless you are an expert.
The default cronjob entry is smart enough.

```sh
59 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
```


If you really want to write your cronjob, you must write with `--home` param.

```
0 4 * * 2 /root/acme/acme.sh --renew -d foo.domain.com  --home "/root/.acme.sh"   >> /var/log/le-renew.log
```

**Comment by Neilpang** [comment]
`--home`  tells acme.sh where it lives.   acme.sh runs any actions starting from the `--home` dir.

**Comment by dm-m** [comment]
@Neilpang There was no default cronjob after acme.sh installation. I used the script with `--issue` option and had to set up my own cron entry with further moving of cert files to custom directories.

Thank you, `--home` parameter worked, closing the issue.
