### ISSUE TITLE
Wildcard domain problem,"Error, can not get domain token *.example.com"

### ISSUE THREAD

**Issue by FreeStyleNight** [Neilpang/acme.sh#1175]
my env is `nginx/1.13.8(build with openssl 1.1.1-dev) in the docker image(based on debian 9)`. Sure I did't use `*.example.com` actually, my domain is in my log file. But when I use command `acme.sh --test --issue -d example.io -d www.example.io -d *.example.io --dns dns_cf` then report the error `Error, can not get domain token *.example.com`.
I have  used `export BRANCH=2` , it should already change to the branch 2.
My server supplier is `namecheap.com`
my first A recode like that   `Type: A Record ;  Host:  *  ; Value: 1.2.3.4`
my second A recode like that   `Type: A Record ;  Host:  @ ;  Value: 1.2.3.4`
my CNAME recode like that   `Type: CNAME Record   ;  Host:  www  ;    Value:  example.com`
Would the problem caused by the first wildcard record ?  
I have already cancel the wildcard record . When it affected i will try again.
Thanks in advance.
My log file is here.

PS : It seems I use `--dns` command with wrong way, and I didn't find the dns api of `NameCheap`, I had better find another DNS to support wildcard DNS and list in the dnsapi. 😂 
[acme.sh.log](https://github.com/Neilpang/acme.sh/files/1618825/acme.sh.log)

PSS : Oh...I had changed my dns name server to Cloudflare but seems no use and now my SSR client don't work too 😭 ( I open port 65535,   my SSR client set like `www.example.com:65535`, but it don't get any response now(server is ok)). 
Whatever that's not a big deal,   Important is I have already explored BRANCH 2,  add `--test` and `--log --log 2`.  It returns the same error`can not get domain token *.example.com`
Here is my new log file ,Hope it would be helpful.
And there is a strange phenomenon I cared. In the Cloudflare my "Crypto" panel, I found there seems already have a wildcard certificate in Edge Certificates. But didn't I do that "successful" before ? I would post the screen capture with log file too. Maybe it affect something ?

PSSS: there is another thing I think it could be useful, Before I changed to the ACME, I have already use Certbot to active my domain once. But it looks like didn't support wildcard for now, So I found the ACME. So I actually get a non-wildcard certificate before. However I had already delete the certbot and my certificate from my server.
@Neilpang 
![screen_capture](https://user-images.githubusercontent.com/20919271/34805438-10fe1b46-f6b9-11e7-867c-d7d4fba312b5.png)
[acme.sh-2.log](https://github.com/Neilpang/acme.sh/files/1621011/acme.sh-2.log)

**Comment by FernandoMiguel** [comment]
there is a docker tag https://hub.docker.com/r/neilpang/acme.sh/tags/  (2) which has the write branch.

i see you use dns_cf.
are you exporting cloudflare envs?

**Comment by FernandoMiguel** [comment]
from the log:
`[Wed Jan 10 20:46:15 CST 2018] entry='"type":"dns-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"No TXT record found at _acme-challenge.amlic.io","status": 403'`
there is no TXT record setup

**Comment by FreeStyleNight** [comment]
@FernandoMiguel 
It seems I add too much more things :joy:
emmm, the  message about TXT record is that i tried the first way but no use, So I follow the doc guides, then find method 8, about USE DNS MODE. But soon i found when I run `acme.sh --renew -d *.example.com` then it report the error, seems like can't use `*.example.com` wildcard type to use this method....
And then I try my original method but no use, so I came here use my poor English ask for some help 😂

**Comment by FernandoMiguel** [comment]
you said you were using docker, right?
you need to set cloudflare api key as env vars as inline -e to docker

**Comment by FernandoMiguel** [comment]
@FreeStyleNight i tested docker image tag 2 this weekend and it was working great with cloudflare dns01 validation
maybe @Neilpang can shine some light on the issue

**Comment by Neilpang** [comment]
@FernandoMiguel   @FreeStyleNight 

It could be a bug of acme.sh for ACME v2.    please give more detailed log with `--debug 2`  or `--log --log-level 2`

I will take a look tomorrow.

good night.

**Comment by FernandoMiguel** [comment]
good night @Neilpang 
there was a --debug attached, but i'm sure @FreeStyleNight can get a --debug 2 too

**Comment by FreeStyleNight** [comment]
@Neilpang @FernandoMiguel 
Good night and very thanks to both of you. I am trying method and  sign up a CloudFlare  account , try get a API key. I will send more debug info as fast as possible, hope it would be helpful.

**Comment by FernandoMiguel** [comment]
@FreeStyleNight if you dont have a cloudflare account yet, why did you set the dns api to dns_cf ? (cf is for cloudflare)

**Comment by FernandoMiguel** [comment]
here's another tip
https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by FreeStyleNight** [comment]
Wow, that looks great, thank you. I found letsecrypt support wildcard domain just yesterday , so I can't wait to try this new feature. But....."A watched pot never boils" right ?

**Comment by FernandoMiguel** [comment]
wildcard is announced for the end of february... better calm down man
