### ISSUE TITLE
acme.sh disregarding --tls on issue or renewal of certificate?

### ISSUE THREAD

**Issue by geekazoid** [Neilpang/acme.sh#1176]
Good Day!

As root, I am running the following command:
# acme.sh --issue -d wus.geekazoid.com --tls --home /usr/local/www/gafcerts --debug --test

The output I receive follows.  My interpretation is that acme.sh is attempting to issue the certificate via DNS instead of TLS.  I have also tried the command with --standalone in the command line and receive the same results.

How can I force acme.sh to use --tls?

We do not have anything else running on port 443.

Thank You in Advance!!!

glenn

=====

[Wed Jan 10 04:58:36 PST 2018] Lets find script dir.
[Wed Jan 10 04:58:36 PST 2018] _SCRIPT_='/usr/local/sbin/acme.sh'
[Wed Jan 10 04:58:36 PST 2018] _script='/usr/local/sbin/acme.sh'
[Wed Jan 10 04:58:36 PST 2018] _script_home='/usr/local/sbin'
[Wed Jan 10 04:58:36 PST 2018] Using config home:/usr/local/www/gafcerts
https://github.com/Neilpang/acme.sh
v2.7.5
[Wed Jan 10 04:58:36 PST 2018] Using config home:/usr/local/www/gafcerts
[Wed Jan 10 04:58:36 PST 2018] Using stage ACME_DIRECTORY: https://acme-staging.api.letsencrypt.org/directory
[Wed Jan 10 04:58:36 PST 2018] DOMAIN_PATH='/usr/local/www/gafcerts/wus.geekazoid.com'
[Wed Jan 10 04:58:36 PST 2018] Using ACME_DIRECTORY: https://acme-staging.api.letsencrypt.org/directory
[Wed Jan 10 04:58:36 PST 2018] _init api for server: https://acme-staging.api.letsencrypt.org/directory
[Wed Jan 10 04:58:36 PST 2018] GET
[Wed Jan 10 04:58:36 PST 2018] url='https://acme-staging.api.letsencrypt.org/directory'
[Wed Jan 10 04:58:36 PST 2018] timeout
[Wed Jan 10 04:58:36 PST 2018] _CURL='curl -L --silent --dump-header /usr/local/www/gafcerts/http.header '
[Wed Jan 10 04:58:36 PST 2018] ret='0'
[Wed Jan 10 04:58:36 PST 2018] ACME_KEY_CHANGE='https://acme-staging.api.letsencrypt.org/acme/key-change'
[Wed Jan 10 04:58:36 PST 2018] ACME_NEW_AUTHZ='https://acme-staging.api.letsencrypt.org/acme/new-authz'
[Wed Jan 10 04:58:36 PST 2018] ACME_NEW_ORDER='https://acme-staging.api.letsencrypt.org/acme/new-cert'
[Wed Jan 10 04:58:36 PST 2018] ACME_NEW_ACCOUNT='https://acme-staging.api.letsencrypt.org/acme/new-reg'
[Wed Jan 10 04:58:36 PST 2018] ACME_REVOKE_CERT='https://acme-staging.api.letsencrypt.org/acme/revoke-cert'
[Wed Jan 10 04:58:36 PST 2018] Le_NextRenewTime
[Wed Jan 10 04:58:36 PST 2018] _on_before_issue
[Wed Jan 10 04:58:36 PST 2018] Le_LocalAddress
[Wed Jan 10 04:58:36 PST 2018] Check for domain='wus.geekazoid.com'
[Wed Jan 10 04:58:36 PST 2018] _currentRoot='tls'
[Wed Jan 10 04:58:36 PST 2018] Standalone tls mode.
[Wed Jan 10 04:58:36 PST 2018] _checkport='443'
[Wed Jan 10 04:58:36 PST 2018] _checkaddr
[Wed Jan 10 04:58:36 PST 2018] Using: netstat
[Wed Jan 10 04:58:36 PST 2018] _saved_account_key_hash is not changed, skip register account.
[Wed Jan 10 04:58:36 PST 2018] Read key length:
[Wed Jan 10 04:58:36 PST 2018] _createcsr
[Wed Jan 10 04:58:36 PST 2018] Single domain='wus.geekazoid.com'
[Wed Jan 10 04:58:36 PST 2018] Getting domain auth token for each domain
[Wed Jan 10 04:58:36 PST 2018] Getting webroot for domain='wus.geekazoid.com'
[Wed Jan 10 04:58:36 PST 2018] _w='tls'
[Wed Jan 10 04:58:36 PST 2018] _currentRoot='tls'
[Wed Jan 10 04:58:36 PST 2018] Getting new-authz for domain='wus.geekazoid.com'
[Wed Jan 10 04:58:36 PST 2018] _init api for server: https://acme-staging.api.letsencrypt.org/directory
[Wed Jan 10 04:58:36 PST 2018] ACME_KEY_CHANGE='https://acme-staging.api.letsencrypt.org/acme/key-change'
[Wed Jan 10 04:58:36 PST 2018] ACME_NEW_AUTHZ='https://acme-staging.api.letsencrypt.org/acme/new-authz'
[Wed Jan 10 04:58:36 PST 2018] ACME_NEW_ORDER='https://acme-staging.api.letsencrypt.org/acme/new-cert'
[Wed Jan 10 04:58:36 PST 2018] ACME_NEW_ACCOUNT='https://acme-staging.api.letsencrypt.org/acme/new-reg'
[Wed Jan 10 04:58:36 PST 2018] ACME_REVOKE_CERT='https://acme-staging.api.letsencrypt.org/acme/revoke-cert'
[Wed Jan 10 04:58:36 PST 2018] Try new-authz for the 0 time.
[Wed Jan 10 04:58:36 PST 2018] url='https://acme-staging.api.letsencrypt.org/acme/new-authz'
[Wed Jan 10 04:58:36 PST 2018] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "wus.geekazoid.com"}}'
[Wed Jan 10 04:58:36 PST 2018] RSA key
[Wed Jan 10 04:58:37 PST 2018] GET
[Wed Jan 10 04:58:37 PST 2018] url='https://acme-staging.api.letsencrypt.org/directory'
[Wed Jan 10 04:58:37 PST 2018] timeout
[Wed Jan 10 04:58:37 PST 2018] _CURL='curl -L --silent --dump-header /usr/local/www/gafcerts/http.header '
[Wed Jan 10 04:58:37 PST 2018] ret='0'
[Wed Jan 10 04:58:37 PST 2018] POST
[Wed Jan 10 04:58:37 PST 2018] url='https://acme-staging.api.letsencrypt.org/acme/new-authz'
[Wed Jan 10 04:58:37 PST 2018] _CURL='curl -L --silent --dump-header /usr/local/www/gafcerts/http.header '
[Wed Jan 10 04:58:37 PST 2018] _ret='0'
[Wed Jan 10 04:58:37 PST 2018] code='201'
[Wed Jan 10 04:58:37 PST 2018] The new-authz request is ok.
[Wed Jan 10 04:58:37 PST 2018] entry
[Wed Jan 10 04:58:37 PST 2018] Error, can not get domain token wus.geekazoid.com
[Wed Jan 10 04:58:37 PST 2018] pid
[Wed Jan 10 04:58:37 PST 2018] No need to restore nginx, skip.
[Wed Jan 10 04:58:37 PST 2018] _clearupdns
[Wed Jan 10 04:58:37 PST 2018] skip dns.
[Wed Jan 10 04:58:37 PST 2018] _on_issue_err
[Wed Jan 10 04:58:37 PST 2018] Please add '--debug' or '--log' to check more details.
[Wed Jan 10 04:58:37 PST 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by FernandoMiguel** [comment]
tls-sni01 is temporarily disabled
https://community.letsencrypt.org/t/2018-01-09-issue-with-tls-sni-01-and-shared-hosting-infrastructure/49996

**Comment by Neilpang** [comment]
@FernandoMiguel   Yes

BTW,  please upgrade to the latest v2.7.6.  you will be happier.

**Comment by geekazoid** [comment]
Thank You Both for the fast response!!!  I am impressed!

@Neilpang, Thank You for a great script!!!  I am on FreeBSD and the port maintainer has not updated yet.  I will send him a request.  :-)
Have a Great Day!

**Comment by Neilpang** [comment]
@geekazoid 
>>I will send him a request. :-)

The latest 2.7.6 is not released as a tag in Github yet,  so, the FreeBSD maintainer will not release at either.

So, you don't need to send them a request.  just wait please.
