### ISSUE TITLE
Updating / adding --[...]-hook after initial cert issue

### ISSUE THREAD

**Issue by chrispolley** [Neilpang/acme.sh#1177]
Hi,
The documentation is not clear how to update the configuration to cause acme.sh to run hooks or a reload command if they were not specified on initial issuance of the certificate, or to modify the commands to be run if they were specified but need to be changed.  I was not able to find anything in the wiki.  However a review of the code suggests that the "Le_[Pre|Post|Renew]Hook" or "Le_ReloadCmd" tags in the $DOMAIN_PATH/$domain.conf file might be applicable, but I'm not sure where to find $domain.conf.  A search of my system for a $domain.conf file using the domain listed when running ``acme.sh --renewall`` comes up empty.

Is doing this (updating hooks or reload command after initial issuance) possible, or must it be accomplished by abandoning the current cert and doing a new --issue sequence?  Is there a way to force saving the $domain.conf file so it can be updated by hand?

Finally, are any parameters (e.g. the key filename and/or main domain) passed to the hook calls?

Thanks!

**Comment by FernandoMiguel** [comment]
you set the hooks on issue
renew doesnt use them

the variables you mention are in the conf file inside the .acme.sh folder

**Comment by FernandoMiguel** [comment]
yes, you can manually edit the conf although not recommended... an --issue would save new settings

there are several env vars, but i'm not sure which ones

**Comment by Roy-Orbison** [comment]
The manual method involves editing the certificate's `.conf` file. You are better off using a short command to a script than putting many long instructions into the configuration file. Take the command you want to use, and encode it, _escaped_, as base64, e.g.:
```sh
/path/to/my/script -x -y 'z z z' foo.bar
```
could be encoded thusly (`-n` to prevent a line break at the end):
```sh
echo -n '/path/to/my/script -x -y '\''z z z'\'' foo.bar' | base64
```
producing `L3BhdGgvdG8vbXkvc2NyaXB0IC14IC15ICd6IHogeicgZm9vLmJhcg==`. The extra quoting is a bit of overkill for this specific example, but it demonstrates how to pass the whole command to the encoder as-is. You could also use something like
```sh
cat | base64 > my-encoded-renew-hook
```
paste in your command, press <kbd>Ctrl</kbd> + <kbd>D</kbd> once or twice (until you get your shell prompt back), then view the contents of the `my-encoded-renew-hook` file.

Now test your output to see if you've made any mistakes:
```sh
echo L3BhdGgvdG8vbXkvc2NyaXB0IC14IC15ICd6IHogeicgZm9vLmJhcg== | base64 -d
```
the string should be your original command, _exactly_, with no line break or white space between the end of the output and your new shell prompt.

Now concatenate tokens `__ACME_BASE64__START_` and `__ACME_BASE64__END_` to your base64 string, and paste it into the config file, e.g.:
```ini
Le_RenewHook='__ACME_BASE64__START_L3BhdGgvdG8vbXkvc2NyaXB0IC14IC15ICd6IHogeicgZm9vLmJhcg==__ACME_BASE64__END_'
```
Note the asymmetry of the underscores in the tokens, they must be exactly as shown. Now :crossed_fingers:

**Comment by Roy-Orbison** [comment]
I wrote [a little script for this, named `acmebase64`](https://gist.github.com/Roy-Orbison/10ab882af122fa3fb7ba3cdafc809c62).
