### ISSUE TITLE
camelMode used by v2

### ISSUE THREAD

**Issue by roma2580** [Neilpang/acme.sh#1178]
Hi,
maybe I missed something, but when looking into the code of acme.sh I cannot find out how the new camelMode API is handled. Instead, the response from https://acme-staging-v02.api.letsencrypt.org/directory is scanned for strings like "key-change", "new-order", ... instead for "keyChange", "newOrder" ..
Maybe this could be the reason why I am trying for hours without luck to run the same acme.sh example with the v2 that successfully runs with v1 !

Just to make sure that I am using the latest version:
./acme.sh -v
https://github.com/Neilpang/acme.sh
v2.7.6

This is my example:
./acme.sh --debug 3 --log --force --test --server https://acme-staging-v02.api.letsencrypt.org/directory  --issue -d xxx.yyyy.net --dns -d sub2.xxx.yyyy.net --dns -d sub3.xxx.yyyy.net --dns 

And this is the part of the console output where the error message is displayed:
. . .
[Fri Jan 12 12:43:21 CET 2018] curl exists=0
[Fri Jan 12 12:43:21 CET 2018] mktemp exists=0
[Fri Jan 12 12:43:21 CET 2018] wget exists=0
[Fri Jan 12 12:43:21 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.K7u8GHIuOO '
[Fri Jan 12 12:43:21 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 3
[Fri Jan 12 12:43:21 CET 2018] Here is the curl dump log:
[Fri Jan 12 12:43:21 CET 2018] == Info: <url> malformed
== Info: Closing connection -1
[Fri Jan 12 12:43:21 CET 2018] _ret='3'
. . .

Anything I can do ?

Anyway, many thanks for this admirable masterpiece, this is exactly what is needed !
cheers

**Comment by Neilpang** [comment]
what is that ?

**Comment by roma2580** [comment]
sorry, I hit the wrong key! Presently I am updating this empty message,
hope that will work. This is my first contribution.

Robert


Am 12.01.2018 12:37 schrieb "neil" <notifications@github.com>:

**Comment by Neilpang** [comment]
The v2 api is supported in acme.sh  branch "2",   not in the master branch.
please install the "2" branch.

```
export BRANCH=2
curl https://get.acme.sh | sh

```

**Comment by roma2580** [comment]
Thanks, this solved my previous problem ! 
Unfortunately, now I get "Le_OrderFinalize not found.". Guess this has to do with dns mode, which I am not familiar but would like to use.

**Comment by roma2580** [comment]
Now the 'issue' works, the correct cmd line for my example seems to be:
acme.sh --force --server https://acme-staging-v02.api.letsencrypt.org/directory  --issue --dns -d xxx.yyyy.net   -d sub2.xxx.yyyy.net   -d sub3.xxx.yyyy.net 

Then I entered the 3 TXT records into the config file of my dns server (it is maradns in my case), restarted the dns server, and verified that the new TXT records were properly resolved, using the dig command from a distant machine, e.g.:
 dig txt _acme-challenge.sub3.xxx.yyyy.net 
produced
. . .
;; ANSWER SECTION:
_acme-challenge.sub3.xxx.yyyy.net. 86059 IN TXT "KyNcP2L0IEgzKZ74v3e24IFfgyTf6enMVAhJlyBucuI"
. . .

However, the final command
acme.sh --force --server https://acme-staging-v02.api.letsencrypt.org/directory  --renew  -d xxx.yyyy.net
still produced a 'verify error':
. . .
[Sat Jan 13 02:02:37 CET 2018] Verifying:xxx.yyyy.net
[Sat Jan 13 02:02:38 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 3
[Sat Jan 13 02:02:40 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 3
[Sat Jan 13 02:02:40 CET 2018] xxx.yyyy.net:Verify error:
. . .

What was wrong ?

**Comment by roma2580** [comment]
I am a bit closer now: It seems that the default TTL (time to live) value in my dns server is 1 day, therefore repeated changes of TXT entries while testing were not visible to the letsencrypt server. Now I changed the TTL value, but have to wait one more day until those TXT entries will finally die which were defined with the previous ttl.

**Comment by roma2580** [comment]
That worked now ! When using dns auth, you save a lot of headache if you define the TXT entries with a very low TTL value, at least as long as you are still experimenting. If the TTL is (for example) 24 hrs, then you have to wait a whole day until changes in the dns config become effective !
