### ISSUE TITLE
How to issue wildcard cert acme.sh 2?

### ISSUE THREAD

**Issue by khs1994** [Neilpang/acme.sh#1185]
Steps to reproduce
------------------

Debug log
-----------------

```bash
acme.sh  --issue \
    --dns dns_dp \
    -d test.khs1994.com,test3.khs1994.com \
    --keylength ec-256 --debug 10
```

Is this right?

**Comment by FernandoMiguel** [comment]
First you need to switch to branch 2

And then one of your secondary domains needs to be a wildcard 

Keep in mind that until let's encrypt launches officially wildcard support, you can only issue wildcard certs from the staging server

**Comment by Neilpang** [comment]
```
acme.sh  --issue --test  \
    --dns dns_dp \
    -d test.khs1994.com \
    -d *.khs1994.com \
    --keylength ec-256


```
