### ISSUE TITLE
"Error, can not get domain token ..."

### ISSUE THREAD

**Issue by DdAArt** [Neilpang/acme.sh#1190]
I'm attempting to install ssl certs on dd-wrt router as described in your how to.

I'm attempting to create and add ssl cert to an owncloud install on lighttpd in Kong 34015.

I can install and run acme.sh fine but I get an error near the end of --issue command that says:
"Error, can not get domain token ***.***.net.

ddns is through dynu.

Output appears in expected locations but both "host.crt" and "fullchain.crt" are empty. 

root@DD-WRT 1450-AC:/jffs/usr/ssl# ./acme.sh --test --log --log-level 2 --issue
--tls -d ########### \--home /jffs/usr/ssl --ca-path /opt/etc/ssl/certs \
--pre-hook "stopservice lighttpd" --post-hook "startservice lighttpd"
[Mon Jan 15 10:42:38 PST 2018] Using stage ACME_DIRECTORY: https://acme-staging.api.letsencrypt.org/directory
[Mon Jan 15 10:42:39 PST 2018] Run pre hook:'stopservice lighttpd'
[Mon Jan 15 10:42:39 PST 2018] Standalone tls mode.
[Mon Jan 15 10:42:39 PST 2018] Single domain='#################'
[Mon Jan 15 10:42:39 PST 2018] Getting domain auth token for each domain
[Mon Jan 15 10:42:39 PST 2018] Getting webroot for domain='##################'
[Mon Jan 15 10:42:39 PST 2018] Getting new-authz for domain='##################'
[Mon Jan 15 10:42:40 PST 2018] The new-authz request is ok.
[Mon Jan 15 10:42:40 PST 2018] Error, can not get domain token ##################
[Mon Jan 15 10:42:40 PST 2018] Please check log file for more details: /jffs/usr/ssl/acme.sh.log
[Mon Jan 15 10:42:40 PST 2018] Run post hook:'startservice lighttpd'

[acme.sh.log](https://github.com/Neilpang/acme.sh/files/1632764/acme.sh.log)

**Comment by Night1** [comment]
I'm seeing same issue with 2.7.5-56-ge6cda79

**Comment by Neilpang** [comment]
you can not use `--tls`.

tls validation is disabled: https://community.letsencrypt.org/t/tls-sni-challenges-disabled-for-most-new-issuance/50316/3

**Comment by mrPsycho** [comment]
could you update this https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert#3-standalone-tls-mode ?
