### ISSUE TITLE
URL should be httpS

### ISSUE THREAD

**Issue by schoemaker** [Neilpang/acme.sh#1192]
https://github.com/Neilpang/acme.sh/blob/9a419bd63fadaae41e42ddea9d81a4cae9e195a9/dnsapi/dns_freedns.sh#L318
The url should start with http**s**, just like elsewhere in the code.

Kind regards,
Harold

**Comment by itssimple** [comment]
@Neilpang This can be closed now, or do you want to close it when you make a new release?
