### ISSUE TITLE
passing -f to _readlink breaks the --ca-bundle switch

### ISSUE THREAD

**Issue by hmb** [Neilpang/acme.sh#1202]
When evaluating the parameter ```--ca-bundle``` a ```-f ``` is passed to the ```_readlink``` function. This leads to passing ```-f``` as filename to ```readlink``` which is called from ```_readlink```. A Pull request #1201 has been issued to fix the problem.

call:
```
user@host ~/acme$ acme.sh --ca-bundle DigiCertGlobalRootG2.crt ... --issue -d example.com
```

the log reveals:
```
...
_CURL='curl -L --silent ... --cacert /home/user/acme/-f '
...
```

while it should read:
```
...
_CURL='curl -L --silent ... --cacert /home/user/acme/DigiCertGlobalRootG2.crt '
...
```

**Comment by Neilpang** [comment]
thank you, merged.
