### ISSUE TITLE
Virtualhost with only one IP address an multiple domains/webroots and SSL certificates

### ISSUE THREAD

**Issue by informas** [Neilpang/acme.sh#1205]
It is posible to use in the one server a virtualhost with the same IP address and several domains/subdomains with differents SSL certificates, not wildcarded?

I have tried to apply under Apache 2.2.22 but I can access with HTTPS protocol only one of them, the others I can’t because the browser responses with SSL_ERROR_BAD_CERT_DOMAIN error code. It means that the SSL certificate is for another domain.

TIA

**Comment by FernandoMiguel** [comment]
Yes you can do

-- 
Fernando Miguel

**Comment by informas** [comment]
May be using SNI? But my server don't have prerequisites to use it. It has OpenSSL 0.98e

May be using DNS Mode? I try it but I don't know how to do it. Can you some detailed example of how to do?
TIA

**Comment by digas** [comment]
I have a server with multiple domains and just one public ip , on the script i made to run the acme.sh i have cloned the apachevirtualhostsfile.conf  to respond to port 80  so when i'm requesting the certificates i first change the configuration (reloading the apache) so it responds all domains on port 80 and they are renewed normally with the TXT file .
I don't see any problem on this . It actually is done automatically every month
