### ISSUE TITLE
V2 invalid cert

### ISSUE THREAD

**Issue by ahmettmertt** [Neilpang/acme.sh#1208]
NET::ERR_CERT_AUTHORITY_INVALID
Subject: tspanel.net

Issuer: Fake LE Intermediate X1

Why cert is invalid?

**Comment by FernandoMiguel** [comment]
Because it was issued with the staging api servers from LE

It's user for testing 
Once everything is working, you should issue one without the - - test or - - staging flag, to get a production certificate. 

Keep in mind that if you are trying to use wildcard, that's only available late next month

**Comment by ahmettmertt** [comment]
So it is impossible to getting valid wildcard cert right now isn't it?

**Comment by FernandoMiguel** [comment]
from https://letsencrypt.org/2017/12/07/looking-forward-to-2018.html

>  We are planning to have a public test API endpoint up by January 4, and we’ve set a date for the full launch: Tuesday, February 27.

**Comment by ahmettmertt** [comment]
Thanks for answer
