### ISSUE TITLE
acme2 wildcard with dns_cf

### ISSUE THREAD

**Issue by sinnlosername** [Neilpang/acme.sh#1213]
Steps to reproduce
`acme.sh --test --issue -d domain.tld -d *.domain.tld --dns dns_cf -k ec-256 --debug`

Debug log
https://p.reflex.rip/BOfx.scala

Cloudflare key + email are set correctly. The first TXT entry is still set, but it's unable to set the second entry.

**Comment by FernandoMiguel** [comment]
`$ dig TXT _acme-challenge.reflex.rip +short`
is not returning anything.
seems it failed to authenticate against cloudflare.
have you tried rotating CF key and readd it to acme.sh?

**Comment by sinnlosername** [comment]
Yes, I removed the entry after some time. But it was there at the moment.

It worked afte a clean reinstall of acme.sh. So I'll mark this as closed.
