### ISSUE TITLE
【提问】如何申请泛域名证书？

### ISSUE THREAD

**Issue by airforce-captain** [Neilpang/acme.sh#1215]
据说let's encrypt 在2018年1月开始支持泛域名证书，请问如何使用acme.sh工具申请？

由于我们每个一级域名下有多个子域名分布在多个不同主机，并且站点根目录都不一样，在以前都是使用dns 方式进行申请证书。但是dns 方式无法自动续签证书，dns 是自建的，目前没有自动化API管理，每次都要人工修改。如果支持泛域名申请的话，当然就更好了。

**Comment by Neilpang** [comment]
https://www.v2ex.com/t/420643#reply9

**Comment by airforce-captain** [comment]
感谢回复。

但是我按照帖子上的example 操作提示如下, 真实域名隐去使用xxx代替.
```
#acme.sh --issue -d *.xxx.com --keylength ec-256 --dns
/root/.acme.sh/acme.sh: No match.

# acme.sh --issue -d *.xxx.com 
/root/.acme.sh/acme.sh: No match.

# acme.sh --server https://acme-staging-v02.api.letsencrypt.org/directory --issue -d *.xxx.com --keylength ec-256
/root/.acme.sh/acme.sh: No match.

```

是不是需要特定分支的acme.sh版本才可以？

**Comment by airforce-captain** [comment]
了解了一下，let's 还没正式发布v2。 目前也无法申请,等更新后再试吧.
