### ISSUE TITLE
--standalone with --local-address arg bind to 0.0.0.0

### ISSUE THREAD

**Issue by hcouplet** [Neilpang/acme.sh#1217]
Steps to reproduce
------------------
On a machine with multiple public ip and 0.0.0.0:80 already used.

/root/.acme.sh/acme.sh --issue -d my.domain.com \
--standalone --local-address X.X.X.X --listen-v4

In the code ,there is a comment just before calling socat saying :   #todo  listen address

**Comment by stevebovy** [comment]
Strange; I just did an upgrade,  and I did not get any updated changes

**Comment by stevebovy** [comment]
The fix for this must also be applied the the socket-check;  because a socket open on one interface:80
should not effect a socket:xx open on a different interface;  if this is fixed correctly we should not
get an error warning

**Comment by stevebovy** [comment]
>> UPGRADE does not indicate that this is FIXED <<<

./acme.sh --home . --upgrade
[Fri Feb 16 20:27:57 PST 2018] Installing from online archive.
[Fri Feb 16 20:27:57 PST 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Fri Feb 16 20:27:59 PST 2018] Extracting master.tar.gz
tar: warning: skipping header 'g'
[Fri Feb 16 20:28:00 PST 2018] Installing to .
cp: 'acme.sh' and './acme.sh' are the same file
[Fri Feb 16 20:28:00 PST 2018] Install failed, can not copy acme.sh
[Fri Feb 16 20:28:00 PST 2018] Upgrade success!
admin-280@RT-AC66U_B1:/tmp/mnt/Data/acmesh#

**Comment by stevebovy** [comment]
Warning !!!

#The patched Merged above is incorrect

**Comment by stevebovy** [comment]
The following additional change should be made >>

>> Add $_local_address

_ss() {
  _port="$1"

  if _exists "ss"; then
    _debug "Using: ss"
    ss -ntpl 2>/dev/null | grep "$_local_address:$_port "
    return 0
  fi
  
  if _exists "netstat"; then
    _debug "Using: netstat"
    if netstat -h 2>&1 | grep "\-p proto" >/dev/null; then
      #for windows version netstat tool
      netstat -an -p tcp | grep "LISTENING" | grep "$_local_address:$_port "
    else
      if netstat -help 2>&1 | grep "\-p protocol" >/dev/null; then
        netstat -an -p tcp | grep LISTEN | grep "$_local_address:$_port "
      elif netstat -help 2>&1 | grep -- '-P protocol' >/dev/null; then
        #for solaris
        netstat -an -P tcp | grep "$_local_address\.$_port " | grep "LISTEN"
      elif netstat -help 2>&1 | grep "\-p" >/dev/null; then
        #for full linux
        netstat -ntpl | grep "$_local_address:$_port "
      else
        #for busybox (embedded linux; no pid support)
        netstat -ntl 2>/dev/null | grep "$_local_address:$_port "
      fi
    fi
    return 0
  fi

**Comment by Neilpang** [comment]
It was my fault.  the code was fixed in dev branch,  not in mater branch.

```sh
export BRANCH=dev
acme.sh --upgrade
```

**Comment by stevebovy** [comment]
Thanks;  I got it;   but as I  noted  in my comments  on the merge last night   ;

 

That patch is bad  ( see the $ )  

 

 

  SOCAT_OPTIONS=TCP-LISTEN:$Le_HTTPPort,crlf,reuseaddr,fork

 

  #Adding bind to local-address

  if [ "$ncaddr" ]; then

    $SOCAT_OPTIONS="$SOCAT_OPTIONS,bind=${ncaddr}"

  fi

**Comment by stevebovy** [comment]
The following additional change should be made >>

Add $_local_address  to  netstat  check  !!!!

_ss() {
_port="$1"

if _exists "ss"; then
_debug "Using: ss"
ss -ntpl 2>/dev/null | grep "$_local_address:$_port "
return 0
fi

if _exists "netstat"; then
_debug "Using: netstat"
if netstat -h 2>&1 | grep "-p proto" >/dev/null; then
#for windows version netstat tool
netstat -an -p tcp | grep "LISTENING" | grep "$_local_address:$_port "
else
if netstat -help 2>&1 | grep "-p protocol" >/dev/null; then
netstat -an -p tcp | grep LISTEN | grep "$_local_address:$_port "
elif netstat -help 2>&1 | grep -- '-P protocol' >/dev/null; then
#for solaris
netstat -an -P tcp | grep "$_local_address.$_port " | grep "LISTEN"
elif netstat -help 2>&1 | grep "-p" >/dev/null; then
#for full linux
netstat -ntpl | grep "$_local_address:$_port "
else
#for busybox (embedded linux; no pid support)
netstat -ntl 2>/dev/null | grep "$_local_address:$_port "
fi
fi
return 0
fi

**Comment by stevebovy** [comment]
Sorry  the patch has a bug    

 

That patch is bad  ( see the $ )  

 

 

  SOCAT_OPTIONS=TCP-LISTEN:$Le_HTTPPort,crlf,reuseaddr,fork

 

  #Adding bind to local-address

  if [ "$ncaddr" ]; then

    $SOCAT_OPTIONS="$SOCAT_OPTIONS,bind=${ncaddr}"

  fi
