### ISSUE TITLE
Why is there a --stateless option for http verification but not for dns verification?

### ISSUE THREAD

**Issue by ProBackup-nl** [Neilpang/acme.sh#1235]
# Stateless DNS

Having a webserver setup that is not supported, as well as a DNS provider without an API, it would be nice to `--issue` and `--renew` `--stateless`.

Why does acme.sh `--stateless` only support web/http/nginx and not **DNS verification**?

**Comment by Neilpang** [comment]
stateless mode is only for nginx server

https://github.com/Neilpang/acme.sh/wiki/Stateless-Mode

**Comment by ProBackup-nl** [comment]
@Neilpang Why can't DNS verification do the verification process stateless? Is that an ACME API limit?

**Comment by Neilpang** [comment]
@ProBackup-nl 
It could be in theory, but doesn't make any sense  actually.

for http verification:
```sh
keyauthorization="$token.$thumbprint"
```

nginx server is suitable to return such string.

while for dns verification:

```sh
txt="$(printf "%s" "$keyauthorization" | _digest "sha256" | _url_replace)"
```

I have never heard any dns server can return such complex txt value.

what do you think ?

**Comment by ProBackup-nl** [comment]
@Neilpang There are no DNS servers that can do, because the $token is not supplied to the DNS server in the request. The server would need to ask something like `TXT` for `$token._acme-challenge.domain.tld`. In such a case a DNS server in theory is able to construct the response dynamically.

**Comment by ProBackup-nl** [comment]
A request has been posted https://github.com/ietf-wg-acme/acme/issues/393

**Comment by gertvdijk** [comment]
> @Neilpang There are no DNS servers that can do, because the $token is not supplied to the DNS server in the request. The server would need to ask something like `TXT` for `$token._acme-challenge.domain.tld`. In such a case a DNS server in theory is able to construct the response dynamically.

Uhm, IIUC, just like [this Nginx regular expression for the URI](https://github.com/Neilpang/acme.sh/wiki/Stateless-Mode), you could set up a wildcard subdomain too:

    *._acme-challenge  IN TXT "$1.$thumbprint"

and you don't need anything dynamically on the DNS side, right?

**Comment by ProBackup-nl** [comment]
What is meant with "IIUC"? For which DNS software and starting from which version?

**Comment by gertvdijk** [comment]
> @gertvdijk What is meant with "IIUC"?

If I Understand Correctly.

> For which DNS software and starting from which version?

[DNS wildcards](https://en.wikipedia.org/wiki/Wildcard_DNS_record)! Exists since ever and all software supports that.

**Comment by bjmgeek** [comment]
PowerDNS supports scriptable dns records (in the Lua language). They could be used to make a stateless DNS record.

**Comment by gertvdijk** [comment]
@bjmgeek: I don't see how that's useful. All you need is a wildcard domain and a static value. LUA records are able to produce a value from a script, but exactly that is totally *stateless* here.

<sup>By the way, I like PowerDNS and even contributing to it occasionally, but I don't think it helps here.</sup>
