### ISSUE TITLE
使用手动得到的csr 多域名请求证书时,403

### ISSUE THREAD

**Issue by bensonfx** [Neilpang/acme.sh#1237]
命令 ： acme.sh --signcsr --csr server.csr --dns --debug 2 --staging
1. 手动得到csr证书 包含SAN域名的请求证书
*.example.com
SAN:   example.com   *.example.com
2.使用dns模式

3.前面的过程都显示成功。最后一步出错。

[2018年 02月 05日 星期一 14:47:09 CST] Http already initialized.
[2018年 02月 05日 星期一 14:47:09 CST] _CURL='curl -L --silent --dump-header /benson/.acme.sh/http.header  --trace-ascii /tmp/tmp.Jpr3N3upf1 '
[2018年 02月 05日 星期一 14:47:11 CST] _ret='0'
[2018年 02月 05日 星期一 14:47:11 CST] original='{
  "type": "urn:ietf:params:acme:error:unauthorized",
  "detail": "Error finalizing order :: Order includes different number of names than CSR specifies",
  "status": 403
}'

4.使用acme.sh --issue -d *.example.com  --dns  --staging 生成新证书，可以成功得到证书

**Comment by Neilpang** [comment]
麻烦贴出来完整的 `--debug 2`  log, 并且贴出来 csr 内容.

**Comment by bensonfx** [comment]
报歉这么才回。
1.csr信息：
![image](https://user-images.githubusercontent.com/3302960/36024148-c3048132-0dc9-11e8-9eaf-ba51419d3621.png)
![image](https://user-images.githubusercontent.com/3302960/36024180-e3509656-0dc9-11e8-8258-500ad01236ba.png)
2.得到完整的错误log如下（替换域名为example.com）
[acme.sh.log](https://github.com/Neilpang/acme.sh/files/1710691/acme.sh.log)

**Comment by Neilpang** [comment]
@bensonfx 
你先用 `--issue` 请求一次, 然后到相应的域名目录里面,知道csr,  对比一下给你的csr的差异.
