### ISSUE TITLE
crontab: can't change directory to '/opt/var/spool/cron/crontabs': No such file or directory

### ISSUE THREAD

**Issue by ProBackup-nl** [Neilpang/acme.sh#1240]
[enhancement]

Some router/NAS firmware use the Entware|Entware-ng|Entware-ng-3x package repository. [Entware-ng-3x|entware-3x uses busybox (and crontab) from Entware-3x](https://github.com/Entware-for-kernel-3x/Entware-ng-3x/issues/26).

Entware-ng uses crontab from router firmware:
```
$ grep src/gz /opt/etc/opkg.conf
src/gz entware-ng http://pkg.entware.net/binaries/mipsel
$ echo $0
-sh
$ ls -l `which sh`
/bin/sh -> busybox
```
This is OK for for 2.7.6. acme.sh | sh installation.

Entware-3x that uses entware-3x crontab:
```
$ grep src/gz /opt/etc/opkg.conf
src/gz packages http://entware-3x.zyxmon.org/binaries/mipsel
$ ls -l `which sh`
/opt/bin/sh -> /opt/bin/busybox
$ ls -l /opt/bin/crontab
/opt/bin/crontab -> /opt/bin/busybox
```
Here v2.7.6 of acme.sh | sh installation returns:
```
Installing cron job
crontab: can't change directory to '/opt/var/spool/cron/crontabs': No such file or directory
crontab: can't change directory to '/opt/var/spool/cron/crontabs': No such file or directory
crontab: can't change directory to '/opt/var/spool/cron/crontabs': No such file or directory
Install cron job failed. You need to manually renew your certs.
```
It would be nice if acme.sh would pick the right crontab (even when path/shell/crontab is incorrectly configured):
```
$ locate crontab
/opt/bin/crontab
/usr/bin/crontab
$ which crontab
/opt/bin/crontab
$ ls -l /opt/bin/crontab
/opt/bin/crontab -> /opt/bin/busybox
```
Despite this, choose /usr/bin/crontab over /opt/bin/crontab, when /opt/bin/crontab fails:
```
$ /opt/bin/crontab -l
crontab: can't change directory to '/opt/var/spool/cron/crontabs': No such file or directory
```

**Comment by ProBackup-nl** [comment]
For now I will prepare entware-3x with a `rm /opt/bin/crontab` to make sure that only firmware crontab is being used.

**Comment by Neilpang** [comment]
we don't know where the correct crontab is.  the system admin should make sure the correct crontab.
