### ISSUE TITLE
Getting a curl error 3 on trying to issue a wildcard certificate

### ISSUE THREAD

**Issue by philiplb** [Neilpang/acme.sh#1246]
Hi,
I just tried to run this in multiple ways:
```bash
acme.sh --issue --test -d foo.bar.com  -d *.foo.bar.com --dns dns_inwx --debug 2
```
Upfront, I have set the env vars "INWX_User" and "INWX_Password".

But no matter what, I just get this error:

> [Tue Feb  6 12:53:12 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 3
> [Tue Feb  6 12:53:12 CET 2018] Here is the curl dump log:
> [Tue Feb  6 12:53:12 CET 2018] == Info: <url> malformed
> == Info: Closing connection -1

This is the full log (domain names and secrets redacted):
https://gist.github.com/philiplb/307710a9e186d9da268e46e3ac793c39

OS is Ubuntu 14.04.5 LTS.

Any clue what I'm doing wrong?

The interesting part: If I try to issue a certificate for a non wildcard domain, it works just fine.

**Comment by FernandoMiguel** [comment]
what exactly is the error you are getting?
do keep in mind the generated cert is from the testing LE CA, and as such not trusted

**Comment by philiplb** [comment]
Thank you. It is this:

> [Tue Feb 6 12:53:12 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 3
> [Tue Feb 6 12:53:12 CET 2018] Here is the curl dump log:
> [Tue Feb 6 12:53:12 CET 2018] == Info: malformed
> == Info: Closing connection -1

When I try to issue without --test, I get this:

```bash
acme.sh --issue -d foo.bar.com  -d *.foo.bar.com --dns dns_inwx --debug 2
```

> [Tue Feb  6 13:51:30 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
> [Tue Feb  6 13:51:30 CET 2018] Here is the curl dump log:
> [Tue Feb  6 13:51:30 CET 2018] == Info: Hostname was NOT found in DNS cache
> == Info: Could not resolve host: acme-v02.api.letsencrypt.org
> == Info: Closing connection 0

Full log of this: https://gist.github.com/philiplb/eae96bac1f553a9392b496e4ab247dc1

**Comment by Neilpang** [comment]
It was a known problem of the Letsencrypt. https://github.com/letsencrypt/boulder/issues/3333
The issue was fixed, but not published to the server yet.

I just fixed acme.sh to give a more friendly error message. 
please update to the latest dev branch and try again.

```sh
export BRANCH=dev
acme.sh --upgrade
```

**Comment by philiplb** [comment]
Hi,
thank you very much so far. Unfortunatly, calling this still results in the following log:
acme.sh --issue -d foo.bar.com -d *.foo.bar.com --dns dns_inwx --debug 2

> [Tue Feb  6 14:36:42 CET 2018] Lets find script dir.
> [Tue Feb  6 14:36:42 CET 2018] _SCRIPT_='./.acme.sh/acme.sh'
> [Tue Feb  6 14:36:42 CET 2018] _script='/var/lib/jenkins/.acme.sh/acme.sh'
> [Tue Feb  6 14:36:42 CET 2018] _script_home='/var/lib/jenkins/.acme.sh'
> [Tue Feb  6 14:36:42 CET 2018] Using default home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 14:36:42 CET 2018] Using config home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 14:36:42 CET 2018] LE_WORKING_DIR='/var/lib/jenkins/.acme.sh'
> https://github.com/Neilpang/acme.sh
> v2.7.6
> [Tue Feb  6 14:36:42 CET 2018] Using config home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 14:36:42 CET 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 14:36:42 CET 2018] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
> [Tue Feb  6 14:36:42 CET 2018] DOMAIN_PATH='/var/lib/jenkins/.acme.sh/foo.bar.com'
> [Tue Feb  6 14:36:42 CET 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
> [Tue Feb  6 14:36:42 CET 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
> [Tue Feb  6 14:36:42 CET 2018] GET
> [Tue Feb  6 14:36:42 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 14:36:42 CET 2018] timeout=
> [Tue Feb  6 14:36:42 CET 2018] _CURL='curl -L --silent --dump-header /var/lib/jenkins/.acme.sh/http.header  --trace-ascii /tmp/tmp.rSqdajnqZT '
> [Tue Feb  6 14:36:42 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
> [Tue Feb  6 14:36:42 CET 2018] Here is the curl dump log:
> [Tue Feb  6 14:36:42 CET 2018] == Info: Hostname was NOT found in DNS cache
> == Info: Could not resolve host: acme-v02.api.letsencrypt.org
> == Info: Closing connection 0
> [Tue Feb  6 14:36:42 CET 2018] ret='6'
> [Tue Feb  6 14:36:42 CET 2018] response
> [Tue Feb  6 14:36:42 CET 2018] Can not init api.
> [Tue Feb  6 14:36:42 CET 2018] Le_NextRenewTime
> [Tue Feb  6 14:36:42 CET 2018] _on_before_issue
> [Tue Feb  6 14:36:42 CET 2018] 'dns_inwx' does not contain 'no'
> [Tue Feb  6 14:36:42 CET 2018] Le_LocalAddress
> [Tue Feb  6 14:36:42 CET 2018] Check for domain='foo.bar.com'
> [Tue Feb  6 14:36:42 CET 2018] _currentRoot='dns_inwx'
> [Tue Feb  6 14:36:42 CET 2018] Check for domain='*.foo.bar.com'
> [Tue Feb  6 14:36:42 CET 2018] _currentRoot='dns_inwx'
> [Tue Feb  6 14:36:42 CET 2018] 'dns_inwx' does not contain 'apache'
> [Tue Feb  6 14:36:42 CET 2018] config file is empty, can not read CA_KEY_HASH
> [Tue Feb  6 14:36:42 CET 2018] _saved_account_key_hash
> [Tue Feb  6 14:36:42 CET 2018] Using config home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 14:36:42 CET 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 14:36:42 CET 2018] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
> [Tue Feb  6 14:36:42 CET 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
> [Tue Feb  6 14:36:42 CET 2018] GET
> [Tue Feb  6 14:36:42 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 14:36:42 CET 2018] timeout=
> [Tue Feb  6 14:36:42 CET 2018] _CURL='curl -L --silent --dump-header /var/lib/jenkins/.acme.sh/http.header  --trace-ascii /tmp/tmp.z965A6FV8a '
> [Tue Feb  6 14:36:42 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
> [Tue Feb  6 14:36:42 CET 2018] Here is the curl dump log:
> [Tue Feb  6 14:36:42 CET 2018] == Info: Hostname was NOT found in DNS cache
> == Info: Could not resolve host: acme-v02.api.letsencrypt.org
> == Info: Closing connection 0
> [Tue Feb  6 14:36:42 CET 2018] ret='6'
> [Tue Feb  6 14:36:42 CET 2018] response
> [Tue Feb  6 14:36:42 CET 2018] Can not init api.
> [Tue Feb  6 14:36:42 CET 2018] RSA key
> [Tue Feb  6 14:36:42 CET 2018] Registering account
> [Tue Feb  6 14:36:42 CET 2018] url
> [Tue Feb  6 14:36:42 CET 2018] payload='{"termsOfServiceAgreed": true}'
> [Tue Feb  6 14:36:42 CET 2018] Use cached jwk for file: /var/lib/jenkins/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
> [Tue Feb  6 14:36:42 CET 2018] Get nonce. ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 14:36:42 CET 2018] GET
> [Tue Feb  6 14:36:42 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 14:36:42 CET 2018] timeout=
> [Tue Feb  6 14:36:42 CET 2018] _CURL='curl -L --silent --dump-header /var/lib/jenkins/.acme.sh/http.header  --trace-ascii /tmp/tmp.h6YixLvCSN '
> [Tue Feb  6 14:36:42 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
> [Tue Feb  6 14:36:42 CET 2018] Here is the curl dump log:
> [Tue Feb  6 14:36:42 CET 2018] == Info: Hostname was NOT found in DNS cache
> == Info: Could not resolve host: acme-v02.api.letsencrypt.org
> == Info: Closing connection 0
> [Tue Feb  6 14:36:42 CET 2018] ret='6'
> [Tue Feb  6 14:36:42 CET 2018] Can not connect to https://acme-v02.api.letsencrypt.org/directory to get nonce.
> [Tue Feb  6 14:36:42 CET 2018] Register account Error:
> [Tue Feb  6 14:36:42 CET 2018] _on_issue_err
> [Tue Feb  6 14:36:42 CET 2018] Please add '--debug' or '--log' to check more details.
> [Tue Feb  6 14:36:42 CET 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
> [Tue Feb  6 14:36:42 CET 2018] _chk_vlist
> [Tue Feb  6 14:36:42 CET 2018] socat doesn't exists.
> [Tue Feb  6 14:36:42 CET 2018] Diagnosis versions:
> openssl:openssl
> OpenSSL 1.1.0g  2 Nov 2017
> apache:
> apache doesn't exists.
> nginx:
> nginx doesn't exists.
> socat:

**Comment by Neilpang** [comment]
@philfry   you missed `--test`
```
acme.sh --issue -d foo.bar.com -d *.foo.bar.com --dns dns_inwx --debug 2   --test
```

**Comment by philiplb** [comment]
Yep, just tried that and it works. Thank you so much! :)

**Comment by philiplb** [comment]
Urg, sorry to bother again. Of course --test issues a staging certificate by "Fake LE Intermediate X1".

My attempt to issue the certificate:

```bash
acme.sh --issue -d foo.bar.com -d *.foo.bar.com --dns dns_inwx --debug 2
```

results in:

> [Tue Feb  6 15:23:11 CET 2018] Lets find script dir.
> [Tue Feb  6 15:23:11 CET 2018] _SCRIPT_='./.acme.sh/acme.sh'
> [Tue Feb  6 15:23:11 CET 2018] _script='/var/lib/jenkins/.acme.sh/acme.sh'
> [Tue Feb  6 15:23:11 CET 2018] _script_home='/var/lib/jenkins/.acme.sh'
> [Tue Feb  6 15:23:11 CET 2018] Using default home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 15:23:11 CET 2018] Using config home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 15:23:11 CET 2018] LE_WORKING_DIR='/var/lib/jenkins/.acme.sh'
> https://github.com/Neilpang/acme.sh
> v2.7.6
> [Tue Feb  6 15:23:11 CET 2018] Using config home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 15:23:11 CET 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 15:23:11 CET 2018] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
> [Tue Feb  6 15:23:11 CET 2018] DOMAIN_PATH='/var/lib/jenkins/.acme.sh/foo.bar.com'
> [Tue Feb  6 15:23:11 CET 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
> [Tue Feb  6 15:23:11 CET 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
> [Tue Feb  6 15:23:11 CET 2018] GET
> [Tue Feb  6 15:23:11 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 15:23:11 CET 2018] timeout=
> [Tue Feb  6 15:23:11 CET 2018] _CURL='curl -L --silent --dump-header /var/lib/jenkins/.acme.sh/http.header  --trace-ascii /tmp/tmp.XjeYZ4TEwr '
> [Tue Feb  6 15:23:11 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
> [Tue Feb  6 15:23:11 CET 2018] Here is the curl dump log:
> [Tue Feb  6 15:23:11 CET 2018] == Info: Hostname was NOT found in DNS cache
> == Info: Could not resolve host: acme-v02.api.letsencrypt.org
> == Info: Closing connection 0
> [Tue Feb  6 15:23:11 CET 2018] ret='6'
> [Tue Feb  6 15:23:11 CET 2018] response
> [Tue Feb  6 15:23:11 CET 2018] Can not init api.
> [Tue Feb  6 15:23:11 CET 2018] Le_NextRenewTime='1523022086'
> [Tue Feb  6 15:23:11 CET 2018] _saved_domain='foo.bar.com'
> [Tue Feb  6 15:23:11 CET 2018] _saved_alt='*.foo.bar.com'
> [Tue Feb  6 15:23:11 CET 2018] Domains not changed.
> [Tue Feb  6 15:23:11 CET 2018] Skip, Next renewal time is: Sat Apr  7 13:41:26 UTC 2018
> [Tue Feb  6 15:23:11 CET 2018] Add '--force' to force to renew.

Trying to add --force:

```bash
acme.sh --issue --force -d foo.bar.com -d *.foo.bar.com --dns dns_inwx --debug 2
```

> [Tue Feb  6 15:26:19 CET 2018] Lets find script dir.
> [Tue Feb  6 15:26:19 CET 2018] _SCRIPT_='./.acme.sh/acme.sh'
> [Tue Feb  6 15:26:19 CET 2018] _script='/var/lib/jenkins/.acme.sh/acme.sh'
> [Tue Feb  6 15:26:19 CET 2018] _script_home='/var/lib/jenkins/.acme.sh'
> [Tue Feb  6 15:26:19 CET 2018] Using default home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 15:26:19 CET 2018] Using config home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 15:26:19 CET 2018] LE_WORKING_DIR='/var/lib/jenkins/.acme.sh'
> https://github.com/Neilpang/acme.sh
> v2.7.6
> [Tue Feb  6 15:26:19 CET 2018] Using config home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 15:26:19 CET 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 15:26:19 CET 2018] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
> [Tue Feb  6 15:26:19 CET 2018] DOMAIN_PATH='/var/lib/jenkins/.acme.sh/foo.bar.com'
> [Tue Feb  6 15:26:19 CET 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
> [Tue Feb  6 15:26:19 CET 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
> [Tue Feb  6 15:26:19 CET 2018] GET
> [Tue Feb  6 15:26:19 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 15:26:19 CET 2018] timeout=
> [Tue Feb  6 15:26:19 CET 2018] _CURL='curl -L --silent --dump-header /var/lib/jenkins/.acme.sh/http.header  --trace-ascii /tmp/tmp.aIww9yWEhr '
> [Tue Feb  6 15:26:19 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
> [Tue Feb  6 15:26:19 CET 2018] Here is the curl dump log:
> [Tue Feb  6 15:26:19 CET 2018] == Info: Hostname was NOT found in DNS cache
> == Info: Could not resolve host: acme-v02.api.letsencrypt.org
> == Info: Closing connection 0
> [Tue Feb  6 15:26:19 CET 2018] ret='6'
> [Tue Feb  6 15:26:19 CET 2018] response
> [Tue Feb  6 15:26:19 CET 2018] Can not init api.
> [Tue Feb  6 15:26:19 CET 2018] Le_NextRenewTime='1523022086'
> [Tue Feb  6 15:26:19 CET 2018] _on_before_issue
> [Tue Feb  6 15:26:19 CET 2018] 'dns_inwx' does not contain 'no'
> [Tue Feb  6 15:26:19 CET 2018] Le_LocalAddress
> [Tue Feb  6 15:26:19 CET 2018] Check for domain='foo.bar.com'
> [Tue Feb  6 15:26:19 CET 2018] _currentRoot='dns_inwx'
> [Tue Feb  6 15:26:19 CET 2018] Check for domain='*.foo.bar.com'
> [Tue Feb  6 15:26:19 CET 2018] _currentRoot='dns_inwx'
> [Tue Feb  6 15:26:19 CET 2018] 'dns_inwx' does not contain 'apache'
> [Tue Feb  6 15:26:19 CET 2018] config file is empty, can not read CA_KEY_HASH
> [Tue Feb  6 15:26:19 CET 2018] _saved_account_key_hash
> [Tue Feb  6 15:26:19 CET 2018] Using config home:/var/lib/jenkins/.acme.sh
> [Tue Feb  6 15:26:19 CET 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 15:26:19 CET 2018] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
> [Tue Feb  6 15:26:19 CET 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
> [Tue Feb  6 15:26:19 CET 2018] GET
> [Tue Feb  6 15:26:19 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 15:26:19 CET 2018] timeout=
> [Tue Feb  6 15:26:19 CET 2018] _CURL='curl -L --silent --dump-header /var/lib/jenkins/.acme.sh/http.header  --trace-ascii /tmp/tmp.nDyUx3t1Hh '
> [Tue Feb  6 15:26:19 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
> [Tue Feb  6 15:26:19 CET 2018] Here is the curl dump log:
> [Tue Feb  6 15:26:19 CET 2018] == Info: Hostname was NOT found in DNS cache
> == Info: Could not resolve host: acme-v02.api.letsencrypt.org
> == Info: Closing connection 0
> [Tue Feb  6 15:26:19 CET 2018] ret='6'
> [Tue Feb  6 15:26:19 CET 2018] response
> [Tue Feb  6 15:26:19 CET 2018] Can not init api.
> [Tue Feb  6 15:26:19 CET 2018] RSA key
> [Tue Feb  6 15:26:19 CET 2018] Registering account
> [Tue Feb  6 15:26:19 CET 2018] url
> [Tue Feb  6 15:26:19 CET 2018] payload='{"termsOfServiceAgreed": true}'
> [Tue Feb  6 15:26:19 CET 2018] Use cached jwk for file: /var/lib/jenkins/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
> [Tue Feb  6 15:26:19 CET 2018] Get nonce. ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 15:26:19 CET 2018] GET
> [Tue Feb  6 15:26:19 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
> [Tue Feb  6 15:26:19 CET 2018] timeout=
> [Tue Feb  6 15:26:19 CET 2018] _CURL='curl -L --silent --dump-header /var/lib/jenkins/.acme.sh/http.header  --trace-ascii /tmp/tmp.NAA7qd4Jvp '
> [Tue Feb  6 15:26:19 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
> [Tue Feb  6 15:26:19 CET 2018] Here is the curl dump log:
> [Tue Feb  6 15:26:19 CET 2018] == Info: Hostname was NOT found in DNS cache
> == Info: Could not resolve host: acme-v02.api.letsencrypt.org
> == Info: Closing connection 0
> [Tue Feb  6 15:26:19 CET 2018] ret='6'
> [Tue Feb  6 15:26:19 CET 2018] Can not connect to https://acme-v02.api.letsencrypt.org/directory to get nonce.
> [Tue Feb  6 15:26:19 CET 2018] Register account Error:
> [Tue Feb  6 15:26:19 CET 2018] _on_issue_err
> [Tue Feb  6 15:26:19 CET 2018] Please add '--debug' or '--log' to check more details.
> [Tue Feb  6 15:26:19 CET 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
> [Tue Feb  6 15:26:19 CET 2018] _chk_vlist
> [Tue Feb  6 15:26:19 CET 2018] socat doesn't exists.
> [Tue Feb  6 15:26:19 CET 2018] Diagnosis versions:
> openssl:openssl
> OpenSSL 1.1.0g  2 Nov 2017
> apache:
> apache doesn't exists.
> nginx:
> nginx doesn't exists.
> socat:

**Comment by FernandoMiguel** [comment]
wildcards are only supported in staging.
official release is scheduled for later this month

**Comment by FernandoMiguel** [comment]
https://letsencrypt.org/2017/12/07/looking-forward-to-2018.html

**Comment by philiplb** [comment]
Ah, I understand. Thank you very much! :)
