### ISSUE TITLE
dns_yandex plugin doesn't work on some distros due to different sed behavior

### ISSUE THREAD

**Issue by artello73** [Neilpang/acme.sh#1247]
The plugin dns_yandex doesn't work on some platforms due to different "sed" behavior. 
The error resides within PDD_get_domain() function during JSON response parsing at this line:

**$__all_domains="$__all_domains` $(echo "$res1" | sed -e "s@,@\n@g" | grep '"name"' | cut -d: -f2 | sed -e 's@"@@g')"** 

On some platforms (I have noticed this on pfsense box powerd by FREEBSD 11)  this code `sed -e "s@,@\n@g" ` replacing commas with a symbol 'n' rather than replacing them with line break.  See attached test case. 
[dns_yandex.sed.test.case.txt](https://github.com/Neilpang/acme.sh/files/1700242/dns_yandex.sed.test.case.txt)
I suggest to replace expression `sed -e "s@,@\n@g" ` with a expression `tr -s ',' '\n'` which works in the same way.

**Comment by Neilpang** [comment]
fixed, please upgrade to the latest dev branch and try again.

```sh
export BRANCH=dev
acme.sh --upgrade
```
