### ISSUE TITLE
add hook points/scripts to le.sh

### ISSUE THREAD

**Issue by Fabian-Gruenbichler** [Neilpang/acme.sh#125]
This is more of a feature request, but here it goes anyway.

I think that adding some sort of hook functionality to le.sh would be great, similar to the already existing reloadcmd. One possible use for such hook points would be automatically allowing incoming connections on port 80 before starting the `nc` server, and disallowing them once the verification is complete. I am sure there would be a lot of other use cases as well, so maybe a general `pre` and `post` hook for each of the steps would be nice? With the new `getopt`-style calling syntax these could all be long options only which should not conflict with anything else.

My suggestion would be to pass the command (`issue`, `renew`, `cron`, ..) and the main domain (if applicable) as parameters when calling the hooks. This would greatly extend the utility of le.sh, with minimal changes to le.sh itself. Also way prettier and flexible than wrapping the crontab entries ;)

Thanks for your work!

p.s. if this is a desired feature, I could help with implementing it or provide a first implementation as PR

**Comment by Neilpang** [comment]
Good point.   I'd like to see your PR.

**Comment by Neilpang** [comment]
Supported:　https://github.com/Neilpang/acme.sh/issues/282
