### ISSUE TITLE
Minor error with DNS-Hurricane Electric method on pfSense 2.4.2

### ISSUE THREAD

**Issue by kpaasial** [Neilpang/acme.sh#1252]
I have the DNS of my domain hosted at dns.he.net and I'm using the DNS-Hurricane Electric -method for issue/renew.

I'm using the ACME package on PfSense 2.4.2-RELEASE-p1 which is based on FreeBSD 11.1-RELEASE-p6. The acme.sh version in the pfSense package is 2.7.6.

I noticed this error at the end of a run that issued a certificate with a new SAN:

`IMPORT CERT ....`
`update cert![Wed Feb 7 15:34:53 EET 2018] Reload success`
`sed: 1: "s/.*\([0-9]+','ftp\.rdn ...": RE error: parentheses not balanced`
`[Wed Feb 7 15:34:47 EET 2018] Could not clean (remove) up the record. Please go to HE administration interface and clean it by hand.`
`[Wed Feb 7 15:34:47 EET 2018] Error rm webroot api for domain:dns_he`

Despite the error the TXT record does get removed so the error is very minor and cosmetic. I was informed that a similar error was found and fixed in #1247 and this is on almost exactly the same platform, pfSense 2.4.2.

**Comment by Neilpang** [comment]
@kpaasial 
I tried on my pfsense server,  the he.net hook  doesn't have such problem.
From you log, it seems that  the error happened in the reload script.
