### ISSUE TITLE
dns txt record not recognized

### ISSUE THREAD

**Issue by Ruebezahl11** [Neilpang/acme.sh#1254]
Hi,

I am trying to get a cert using the dns method. I have added the TXT record a few days ago and can verify it. The script keeps telling me I should add the dns entry

Steps to reproduce
------------------
nslookup
set type=txt
_acme-challenge.mail.maas-noten.de

returns
Non-authoritative answer:
_acme-challenge.mail.maas-noten.de      text = "LVFfNRCbmxKt05mtlJhkNx4hSiLeBTLKQAp-DoKI2Po"

Debug log
-----------------

[Do 8. Feb 08:52:22 CET 2018] Lets find script dir.
[Do 8. Feb 08:52:22 CET 2018] _SCRIPT_='/home/wolfgang/.acme.sh/acme.sh'
[Do 8. Feb 08:52:22 CET 2018] _script='/home/wolfgang/.acme.sh/acme.sh'
[Do 8. Feb 08:52:22 CET 2018] _script_home='/home/wolfgang/.acme.sh'
[Do 8. Feb 08:52:22 CET 2018] Using config home:/home/wolfgang/.acme.sh
[Do 8. Feb 08:52:22 CET 2018] LE_WORKING_DIR='/home/wolfgang/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.7.6
[Do 8. Feb 08:52:22 CET 2018] Using config home:/home/wolfgang/.acme.sh
[Do 8. Feb 08:52:22 CET 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Do 8. Feb 08:52:22 CET 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Do 8. Feb 08:52:22 CET 2018] DOMAIN_PATH='/home/wolfgang/.acme.sh/mail.maas-noten.de'
[Do 8. Feb 08:52:22 CET 2018] Using ACME_DIRECTORY: https://acme-v01.api.letsencrypt.org/directory
[Do 8. Feb 08:52:22 CET 2018] _init api for server: https://acme-v01.api.letsencrypt.org/directory
[Do 8. Feb 08:52:22 CET 2018] GET
[Do 8. Feb 08:52:22 CET 2018] url='https://acme-v01.api.letsencrypt.org/directory'
[Do 8. Feb 08:52:22 CET 2018] timeout=
[Do 8. Feb 08:52:22 CET 2018] _CURL='curl -L --silent --dump-header /home/wolfgang/.acme.sh/http.header  --trace-ascii /tmp/tmp.OLLdRZdBUQ '
[Do 8. Feb 08:52:22 CET 2018] ret='0'
[Do 8. Feb 08:52:22 CET 2018] response='{
  "VGa6vCKD5uo": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}'
[Do 8. Feb 08:52:22 CET 2018] ACME_KEY_CHANGE='https://acme-v01.api.letsencrypt.org/acme/key-change'
[Do 8. Feb 08:52:22 CET 2018] ACME_NEW_AUTHZ='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Do 8. Feb 08:52:22 CET 2018] ACME_NEW_ORDER='https://acme-v01.api.letsencrypt.org/acme/new-cert'
[Do 8. Feb 08:52:22 CET 2018] ACME_NEW_ACCOUNT='https://acme-v01.api.letsencrypt.org/acme/new-reg'
[Do 8. Feb 08:52:22 CET 2018] ACME_REVOKE_CERT='https://acme-v01.api.letsencrypt.org/acme/revoke-cert'
[Do 8. Feb 08:52:22 CET 2018] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Do 8. Feb 08:52:22 CET 2018] ACME_NEW_NONCE
[Do 8. Feb 08:52:22 CET 2018] ACME_VERSION
[Do 8. Feb 08:52:22 CET 2018] Le_NextRenewTime
[Do 8. Feb 08:52:22 CET 2018] _on_before_issue
[Do 8. Feb 08:52:22 CET 2018] 'dns' does not contain 'no'
[Do 8. Feb 08:52:22 CET 2018] Le_LocalAddress
[Do 8. Feb 08:52:22 CET 2018] Check for domain='mail.maas-noten.de'
[Do 8. Feb 08:52:22 CET 2018] _currentRoot='dns'
[Do 8. Feb 08:52:22 CET 2018] 'dns' does not contain 'apache'
[Do 8. Feb 08:52:22 CET 2018] _saved_account_key_hash='dlzhUdSn2hTh18HJLN1LUpx2luSz0AAA6NfdHszyXLU='
[Do 8. Feb 08:52:22 CET 2018] _saved_account_key_hash is not changed, skip register account.
[Do 8. Feb 08:52:22 CET 2018] Read key length:
[Do 8. Feb 08:52:22 CET 2018] _createcsr
[Do 8. Feb 08:52:22 CET 2018] domain='mail.maas-noten.de'
[Do 8. Feb 08:52:22 CET 2018] domainlist
[Do 8. Feb 08:52:22 CET 2018] csrkey='/home/wolfgang/.acme.sh/mail.maas-noten.de/mail.maas-noten.de.key'
[Do 8. Feb 08:52:22 CET 2018] csr='/home/wolfgang/.acme.sh/mail.maas-noten.de/mail.maas-noten.de.csr'
[Do 8. Feb 08:52:22 CET 2018] csrconf='/home/wolfgang/.acme.sh/mail.maas-noten.de/mail.maas-noten.de.csr.conf'
[Do 8. Feb 08:52:22 CET 2018] Single domain='mail.maas-noten.de'
[Do 8. Feb 08:52:22 CET 2018] _is_idn_d='mail.maas-noten.de'
[Do 8. Feb 08:52:22 CET 2018] _idn_temp
[Do 8. Feb 08:52:22 CET 2018] _csr_cn='mail.maas-noten.de'
[Do 8. Feb 08:52:22 CET 2018] Getting domain auth token for each domain
[Do 8. Feb 08:52:22 CET 2018] Getting webroot for domain='mail.maas-noten.de'
[Do 8. Feb 08:52:22 CET 2018] _w='dns'
[Do 8. Feb 08:52:22 CET 2018] _currentRoot='dns'
[Do 8. Feb 08:52:22 CET 2018] Getting new-authz for domain='mail.maas-noten.de'
[Do 8. Feb 08:52:22 CET 2018] _init api for server: https://acme-v01.api.letsencrypt.org/directory
[Do 8. Feb 08:52:22 CET 2018] Try new-authz for the 0 time.
[Do 8. Feb 08:52:22 CET 2018] _is_idn_d='mail.maas-noten.de'
[Do 8. Feb 08:52:22 CET 2018] _idn_temp
[Do 8. Feb 08:52:22 CET 2018] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Do 8. Feb 08:52:22 CET 2018] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "mail.maas-noten.de"}}'
[Do 8. Feb 08:52:22 CET 2018] RSA key
[Do 8. Feb 08:52:22 CET 2018] Get nonce. ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Do 8. Feb 08:52:22 CET 2018] GET
[Do 8. Feb 08:52:22 CET 2018] url='https://acme-v01.api.letsencrypt.org/directory'
[Do 8. Feb 08:52:22 CET 2018] timeout=
[Do 8. Feb 08:52:22 CET 2018] _CURL='curl -L --silent --dump-header /home/wolfgang/.acme.sh/http.header  --trace-ascii /tmp/tmp.5nPGRzRuGA '
[Do 8. Feb 08:52:23 CET 2018] ret='0'
[Do 8. Feb 08:52:23 CET 2018] _headers='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 562
Replay-Nonce: 34ZA4mGqDpbB6N8w-fw-CoYvUvHQO1axeRFikikGrXQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Thu, 08 Feb 2018 07:52:22 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 08 Feb 2018 07:52:22 GMT
Connection: keep-alive
^M'
[Do 8. Feb 08:52:23 CET 2018] _CACHED_NONCE='34ZA4mGqDpbB6N8w-fw-CoYvUvHQO1axeRFikikGrXQ'
[Do 8. Feb 08:52:23 CET 2018] nonce='34ZA4mGqDpbB6N8w-fw-CoYvUvHQO1axeRFikikGrXQ'
[Do 8. Feb 08:52:23 CET 2018] POST
[Do 8. Feb 08:52:23 CET 2018] _post_url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Do 8. Feb 08:52:23 CET 2018] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "mCplyyHgk1CRzn9AXptKmONRa-WJ69-fYpGzXf9blArjaXOigUKW2PuoPVpxDwcrhWxsfWpnSGrlvLzWsxWXegUpRHTKWrjWyavGOjHkHGYbcGeRe3pknpdAoEOqhmQqUK7Kh2_B1ecOQavZTzu6YsS2eWjvpsJfwpbeNPA_4-kzFLRjuiXqG54ZRmh8ZISfmmCOqSg5XINXIV8rFfcV4r8wLPIOSD4bdnBmmhiqTDjap8W1x9d6Fb4pPHrGEESWQ7R59Ir7pmLv7Y_GY7Yv5NiyLHxGr1uK-zybmwOsCc8tt0Zp1N8nTpaxeeb3i9loRLAh176Ppt_dz-Jwob0iSw"}}, "protected": "eyJub25jZSI6ICIzNFpBNG1HcURwYkI2Tjh3LWZ3LUNvWXZVdkhRTzFheGVSRmlraWtHclhRIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAxLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctYXV0aHoiLCAiYWxnIjogIlJTMjU2IiwgImp3ayI6IHsiZSI6ICJBUUFCIiwgImt0eSI6ICJSU0EiLCAibiI6ICJtQ3BseXlIZ2sxQ1J6bjlBWHB0S21PTlJhLVdKNjktZllwR3pYZjlibEFyamFYT2lnVUtXMlB1b1BWcHhEd2NyaFd4c2ZXcG5TR3Jsdkx6V3N4V1hlZ1VwUkhUS1dyald5YXZHT2pIa0hHWWJjR2VSZTNwa25wZEFvRU9xaG1RcVVLN0toMl9CMWVjT1FhdlpUenU2WXNTMmVXanZwc0pmd3BiZU5QQV80LWt6RkxSanVpWHFHNTRaUm1oOFpJU2ZtbUNPcVNnNVhJTlhJVjhyRmZjVjRyOHdMUElPU0Q0YmRuQm1taGlxVERqYXA4VzF4OWQ2RmI0cFBIckdFRVNXUTdSNTlJcjdwbUx2N1lfR1k3WXY1Tml5TEh4R3IxdUstenlibXdPc0NjOHR0MFpwMU44blRwYXhlZWIzaTlsb1JMQWgxNzZQcHRfZHotSndvYjBpU3cifX0", "payload": "eyJyZXNvdXJjZSI6ICJuZXctYXV0aHoiLCAiaWRlbnRpZmllciI6IHsidHlwZSI6ICJkbnMiLCAidmFsdWUiOiAibWFpbC5tYWFzLW5vdGVuLmRlIn19", "signature": "KzVvn-ViqxRpGZyek8TK9h6FQOeHIDkYvu3hSVhWYkWrYZYjCVxiGxZ3oSI9ZgNih_OniSxFLgIiKqcgWP0yoJun3ZME0l7wlVxfNW7GIRa9PrHVpSX4U1wAOSFDyWCCJR6JJeBMIlMH3TJzjjKrziuppnyGrHZ9LWBuFjp4LMtvWwyfKuWQAMQH9OhGMHZaaZeewbjsbFMkUccCayTV_A0uWQb1icn6irb7kknbdv6-rLiEMna16xs4dvQhtYVGf865ZTH7rQ1Ky5D0Kk7_VY7qEMyg5KO_RmoYz8VOgd7FhwIw-P7sDqw4YnJBUmSiHdW5e3oIRXEmFdcdqmpbZQ"}'
[Do 8. Feb 08:52:23 CET 2018] _CURL='curl -L --silent --dump-header /home/wolfgang/.acme.sh/http.header  --trace-ascii /tmp/tmp.pjLjYGRSGN '
[Do 8. Feb 08:52:24 CET 2018] _ret='0'
[Do 8. Feb 08:52:24 CET 2018] original='{
  "identifier": {
    "type": "dns",
    "value": "mail.maas-noten.de"
  },
  "status": "pending",
  "expires": "2018-02-12T09:31:47Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/gDD9qos7my5RVjI0LIiTUpSxIGnHQX_3bpgxXTVgb1E/3351731106",
      "token": "R3Ze3es1F5361IwTojrlBkVVMXzFWNp1tHXKyej2Gdk"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/gDD9qos7my5RVjI0LIiTUpSxIGnHQX_3bpgxXTVgb1E/3351731107",
      "token": "TxFQE4BNxKVDAxEZdXuhjuERNz3umd2b-PB7WTwSzfM"
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      1
    ]
  ]
}'
[Do 8. Feb 08:52:24 CET 2018] responseHeaders='HTTP/1.1 100 Continue
Expires: Thu, 08 Feb 2018 07:52:23 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 201 Created
Server: nginx
Content-Type: application/json
Content-Length: 723
Boulder-Requester: 28878953
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/gDD9qos7my5RVjI0LIiTUpSxIGnHQX_3bpgxXTVgb1E
Replay-Nonce: B4_OVdkQYMnxuia1iY2xOW7ECeTOj886ot8Bc8WD7rY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Thu, 08 Feb 2018 07:52:23 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 08 Feb 2018 07:52:23 GMT
Connection: keep-alive
^M'
[Do 8. Feb 08:52:24 CET 2018] response='{"identifier":{"type":"dns","value":"mail.maas-noten.de"},"status":"pending","expires":"2018-02-12T09:31:47Z","challenges":[{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/gDD9qos7my5RVjI0LIiTUpSxIGnHQX_3bpgxXTVgb1E/3351731106","token":"R3Ze3es1F5361IwTojrlBkVVMXzFWNp1tHXKyej2Gdk"},{"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/gDD9qos7my5RVjI0LIiTUpSxIGnHQX_3bpgxXTVgb1E/3351731107","token":"TxFQE4BNxKVDAxEZdXuhjuERNz3umd2b-PB7WTwSzfM"}],"combinations":[[0],[1]]}'
[Do 8. Feb 08:52:24 CET 2018] code='201'
[Do 8. Feb 08:52:24 CET 2018] The new-authz request is ok.
[Do 8. Feb 08:52:24 CET 2018] entry='"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/gDD9qos7my5RVjI0LIiTUpSxIGnHQX_3bpgxXTVgb1E/3351731107","token":"TxFQE4BNxKVDAxEZdXuhjuERNz3umd2b-PB7WTwSzfM"'
[Do 8. Feb 08:52:24 CET 2018] token='TxFQE4BNxKVDAxEZdXuhjuERNz3umd2b-PB7WTwSzfM'
[Do 8. Feb 08:52:24 CET 2018] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/gDD9qos7my5RVjI0LIiTUpSxIGnHQX_3bpgxXTVgb1E/3351731107'
[Do 8. Feb 08:52:24 CET 2018] keyauthorization='TxFQE4BNxKVDAxEZdXuhjuERNz3umd2b-PB7WTwSzfM.3z5PwGCXJuVn4XTf4qyIs2B4znQVA4MjePa10PwOGyo'
[Do 8. Feb 08:52:24 CET 2018] dvlist='mail.maas-noten.de#TxFQE4BNxKVDAxEZdXuhjuERNz3umd2b-PB7WTwSzfM.3z5PwGCXJuVn4XTf4qyIs2B4znQVA4MjePa10PwOGyo#https://acme-v01.api.letsencrypt.org/acme/challenge/gDD9qos7my5RVjI0LIiTUpSxIGnHQX_3bpgxXTVgb1E/3351731107#dns-01#dns'
[Do 8. Feb 08:52:24 CET 2018] vlist='mail.maas-noten.de#TxFQE4BNxKVDAxEZdXuhjuERNz3umd2b-PB7WTwSzfM.3z5PwGCXJuVn4XTf4qyIs2B4znQVA4MjePa10PwOGyo#https://acme-v01.api.letsencrypt.org/acme/challenge/gDD9qos7my5RVjI0LIiTUpSxIGnHQX_3bpgxXTVgb1E/3351731107#dns-01#dns,'
[Do 8. Feb 08:52:24 CET 2018] d='mail.maas-noten.de'
[Do 8. Feb 08:52:24 CET 2018] txtdomain='_acme-challenge.mail.maas-noten.de'
[Do 8. Feb 08:52:24 CET 2018] txt='LVFfNRCbmxKt05mtlJhkNx4hSiLeBTLKQAp-DoKI2Po'
[Do 8. Feb 08:52:24 CET 2018] d_api
[Do 8. Feb 08:52:24 CET 2018] Add the following TXT record:
[Do 8. Feb 08:52:24 CET 2018] Domain: '_acme-challenge.mail.maas-noten.de'
[Do 8. Feb 08:52:24 CET 2018] TXT value: 'LVFfNRCbmxKt05mtlJhkNx4hSiLeBTLKQAp-DoKI2Po'
[Do 8. Feb 08:52:24 CET 2018] Please be aware that you prepend _acme-challenge. before your domain
[Do 8. Feb 08:52:24 CET 2018] so the resulting subdomain will be: _acme-challenge.mail.maas-noten.de
[Do 8. Feb 08:52:24 CET 2018] Dns record not added yet, so, save to /home/wolfgang/.acme.sh/mail.maas-noten.de/mail.maas-noten.de.conf and exit.
[Do 8. Feb 08:52:24 CET 2018] Please add the TXT records to the domains, and retry again.
[Do 8. Feb 08:52:24 CET 2018] pid
[Do 8. Feb 08:52:24 CET 2018] No need to restore nginx, skip.
[Do 8. Feb 08:52:24 CET 2018] _clearupdns
[Do 8. Feb 08:52:24 CET 2018] skip dns.
[Do 8. Feb 08:52:24 CET 2018] _on_issue_err
[Do 8. Feb 08:52:24 CET 2018] Please add '--debug' or '--log' to check more details.
[Do 8. Feb 08:52:24 CET 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Do 8. Feb 08:52:24 CET 2018] _chk_vlist
[Do 8. Feb 08:52:24 CET 2018] socat doesn't exists.
[Do 8. Feb 08:52:24 CET 2018] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.1k 8 Jan 2015
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:

**Comment by Neilpang** [comment]
The second,  please use `--renew`,  not `--issue`

**Comment by vladkras** [comment]
@Neilpang , wow, I spent 2 days trying to figure out why my acme.sh doesn't see my TXT-record
