### ISSUE TITLE
Include Zonomi in DNS Providers

### ISSUE THREAD

**Issue by mpberry** [Neilpang/acme.sh#1255]
I would like to see Zonomi included in the DNS providers list if possible.  I'm not a real programmer or I would probably be able to do it myself.  Their DNS API is pretty simple, it just is a URL that contains the domain, the record to be modified, the value and an API key for authentication.

Here is a link to their API: [http://zonomi.com/app/dns/dyndns.jsp](url)

I think code would really just have to build a string that puts together the TXT challenge, the domain and the API key and then do a WGET.   I'm able to do all my dynamic dns updates with just a WGET.

I found some code online for updating Zonomi DNS records here: [https://codegists.com/code/letsencrypt%20zonomi%20hook/](url)

**Comment by Neilpang** [comment]
please try the dev branch:

```sh
export BRANCH=dev
acme.sh --upgrade

acme.sh  --issue --test -d example.com  -d   --dns dns_zonomi
```

**Comment by Neilpang** [comment]
fixed

**Comment by mpberry** [comment]
Thanks so much!!  I will try it out as soon as I figure out how to update to the dev branch.
