### ISSUE TITLE
acme v2 wildcard dns and aws don't work 

### ISSUE THREAD

**Issue by drybalkadk** [Neilpang/acme.sh#1262]
Hello I writed on https://community.letsencrypt.org/t/acme-sh-supports-acme-v2-wildcard-now/49685/39 
[debug.txt](https://github.com/Neilpang/acme.sh/files/1720458/debug.txt)

##

Debug log
-----------------

```
[debug.txt](https://github.com/Neilpang/acme.sh/files/1720459/debug.txt)

```

**Comment by Neilpang** [comment]
@drybalkadk   fixed , try again.

```sh
export BRANCH=dev
acme.sh --upgrade

```
