### ISSUE TITLE
Instead wildcard www.domain.de with route53

### ISSUE THREAD

**Issue by fnso** [Neilpang/acme.sh#1272]
I tried to issue a test certificate with the command:

`acme.sh --test --issue  -d  *.domain.de    --dns  dns_aws`

I got a certificate, but only for www.domain.de. No wildcard, no domain.de.

My nginx configuration redirects all subdomains and domain.de to www.domain.de. 

Update:

I also tried:

`acme.sh --test --issue --server https://acme-staging-v02.api.letsencrypt.org/directory -d  *.domain.de    --dns  dns_aws`

with the same result: Common Name: www.domain.de  SANs: www.domain.de

Update 2:

in www.domain.de.csr.conf has been generated: 

`subjectAltName=DNS:www.domain.de`

Update 3:

I removed the certificate with the command:

`acme.sh --remove -d *.domain.de`

The output was:

`www.domain.de is removed, the key and cert files are in `

*.domain.de is here again used as www.domain.de

I used also:

`acme.sh --test --issue  --server https://acme-staging-v02.api.letsencrypt.org/directory -d www.domain.de   -d domain.de    -d  *.domain.de    --dns  dns_aws`

in www.domain.de.csr.conf has been generated: 

`subjectAltName=DNS:www.domain.de,DNS:domain.de,DNS:www.domain.de`

**Comment by Neilpang** [comment]
```sh

acme.sh --test --issue  -d www.domain.de    -d domain.de    -d *.domain.de --dns dns_aws
```
