### ISSUE TITLE
--pre-hook timing

### ISSUE THREAD

**Issue by stevebovy** [Neilpang/acme.sh#1275]
Suggestion:   --pre-hook  should not be execute until just before "verification process" begins

>> ok, let's start to verify

Now run  pre-hook 

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
`pre-hook` was designed to run before everything begins.

I wonder the reason why you want to run it there ?

**Comment by stevebovy** [comment]
I am trying to shut down my router interface ;  but there is some type of watch dog that re-starts it within a few seconds;  

 

BUT  -  now I see there is a different solution using  --local-address;  but that needs fixes which I highlighted  in several posts last night
