### ISSUE TITLE
--debug is not saved in LOG file 

### ISSUE THREAD

**Issue by stevebovy** [Neilpang/acme.sh#1280]
--debug can only be found in STDOUT  (does not get saved in LOG file)  

Steps to reproduce
------------------

./acme.sh --home . --test --issue --standalone -f -d home.miscbitbag.org --pre-hook "service stop_htt
pd" --log --debug

acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
That is what `--debug` means. it's not going to log.
For log message ,you should use `--log`  or `--log-level`.
but for the debug message of `socat` I don't want to write it to log at all.
