### ISSUE TITLE
--upgrade with --home .  does not work

### ISSUE THREAD

**Issue by stevebovy** [Neilpang/acme.sh#1281]
>> UPGRADE does not indicate that this is FIXED <<<

NOTE:  Upgrade with --home .    does not work

Steps to reproduce
------------------

./acme.sh --home . --upgrade
[Fri Feb 16 20:27:57 PST 2018] Installing from online archive.
[Fri Feb 16 20:27:57 PST 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Fri Feb 16 20:27:59 PST 2018] Extracting master.tar.gz
tar: warning: skipping header 'g'
[Fri Feb 16 20:28:00 PST 2018] Installing to .
cp: 'acme.sh' and './acme.sh' are the same file
[Fri Feb 16 20:28:00 PST 2018] Install failed, can not copy acme.sh
[Fri Feb 16 20:28:00 PST 2018] Upgrade success!
admin-280@RT-AC66U_B1:/tmp/mnt/Data/acmesh#

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
`--upgrade`  never changes home, it just to upgrade.
