### ISSUE TITLE
Trying to find a better stand-alone (socat) solution 

### ISSUE THREAD

**Issue by stevebovy** [Neilpang/acme.sh#1285]
Excellent Debian SOCAT man page

https://manpages.debian.org/experimental/socat/socat.1.en.html

Socat is a command line based utility that establishes TWO bidirectional byte streams and transfers data between them.

In the transfer phase, socat watches both streams’ read and write file descriptors via select() , and, when data is available on one side and can be written to the other side, socat reads it, performs newline character conversions if required, and writes the data to the write file descriptor of the other stream, then continues waiting for more data in both directions.

When one of the streams effectively reaches EOF, the closing phase begins. Socat transfers the EOF condition to the other stream, i.e. tries to shutdown only its write stream, giving it a chance to terminate gracefully.  For a "defined time" socat continues to transfer data in the other direction, but then closes all remaining channels and terminates. 

-t<timeout>
    When one channel has reached EOF, the write part of the other channel is shut down. Then, socat waits <timeout> [timeval] seconds before terminating. Default is 0.5 seconds. This timeout only applies to addresses where write and read part can be closed independently. When during the timeout interval the read part gives EOF, socat terminates without awaiting the timeout.

BASED on the above descriptions it seems like the current implementation has 
asynchronous time-out problems  ( if address channel 1 gets done before  address Chanel 2 ) or
visa-versa,  then the entire data transfer of the other incomplete channel data transfer gets canceled 

Using the (-t) option might fix the problem

OR

I would like to suggest something like this >

 # "handle" web-server function
handle() {
  # read the get request
  read request
  while /bin/true; do
    read header
    [ "$header" == $'\r' ] && break;
  done
  # write the post data
  echo 'HTTP/1.0 200 OK'
  echo ''
  echo $content
  echo ''
  #cat  #  I do not know if we need this

}

 # new command invokes "handle" function ??
$_NC $SOCAT_OPTIONS SYSTEM:". $0 && handle"

Also; the fork option may not be needed, because this entire conversation only 
has to occur for one-client connection;  multiple client connections do not need to be supported

Some of the above shell syntax is new to me; so I do not fully understand how it works :)

I am not sure what this does or how it works > ". $0 && handle"

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
We don't need to handle the request,  that's why we have `sleep 0.5` there.  It just wait a moment for the http request headers, then return the content.

**Comment by stevebovy** [comment]
Thanks ;   Yes understood.   ( I finally figured out how to use iptables ) My router firewall was getting In the way blocking port 80

**Comment by stevebovy** [comment]
Understood;  I just thought adding the code to receive the request would be a more “robust” solution :)
