### ISSUE TITLE
Can not resolve acme-v02.api.letsencrypt.org

### ISSUE THREAD

**Issue by aressler38** [Neilpang/acme.sh#1288]
There appears to be a problem resolving `acme-v02.api.letsencrypt.org`. I'm not able to access it from different networks. 

This isn't related to the TLS issue resolved by passing --insecure. I think the domain lookup is having issues.

```
[Sun Feb 18 18:36:53 UTC 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Sun Feb 18 18:36:53 UTC 2018] Here is the curl dump log:
[Sun Feb 18 18:36:53 UTC 2018] == Info: Could not resolve host: acme-v02.api.letsencrypt.org
== Info: Closing connection 0
[Sun Feb 18 18:36:53 UTC 2018] ret='6'
[Sun Feb 18 18:36:53 UTC 2018] response
[Sun Feb 18 18:36:53 UTC 2018] Can not init api.
```

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
`acme-v02.api.letsencrypt.org` server is not published yet,
you can only use `--test` server.

**Comment by aressler38** [comment]
Interestingly, this only happened when I tried to issue a wildcard domain. 

    acme.sh --issue -d mydomain.com -d "*.mydomain.com" 

When I leave out the wildcard, it works as expected.

**Comment by FernandoMiguel** [comment]
When not using wildcard, it uses the v1 api

**Comment by bl4ckmesa** [comment]
They're still working on it, looks like: https://community.letsencrypt.org/t/acmev2-and-wildcard-launch-delay/53654
