### ISSUE TITLE
Feature request: Set directory to store all certificates in

### ISSUE THREAD

**Issue by tomsommer** [Neilpang/acme.sh#129]
Would be nice if you could define a separate directory to store all certificate-directories in

**Comment by Neilpang** [comment]
what do you mean ?

**Comment by liuxyon** [comment]
他的意思就是我提的建议，预先可以设置好目录，不用每次要输入目录。最好能自动获取目录. letsencrypt-win-simple 这个软件就可以自动获取域名绑定的目录.

**Comment by lucasRolff** [comment]
@Neilpang - I think instead of storing them in ~/.le/ then you can define a separate directory, let's say /etc/le-ssl/

**Comment by heldchen** [comment]
I'd love this feature as well - being on debian, I'd like to store the lets-encrypt certs in `/etc/ssl/letsencrypt`

**Comment by tomsommer** [comment]
Exactly

**Comment by Neilpang** [comment]
@lucasRolff  @heldchen @tomsommer 

Ok, it's on its way.

**Comment by tomsommer** [comment]
Actually --home does what I want :)

**Comment by heldchen** [comment]
not really, home is also used for all other files acme.sh requires, for example account.conf and the dns scripts.

**Comment by Neilpang** [comment]
@heldchen 
Thanks for you explanation.

your are totally right.

I plan to add a new config "--certhome", which specifies the home for all the certs.

It's coming soon.

**Comment by Neilpang** [comment]
@heldchen 

added:  b2817897774c63bb32ff625207e77f2031cb8ae6

`--certhome` is to override the default dir to save the certs.  It's only valid for `--install` command.
