### ISSUE TITLE
re-verification testing ??

### ISSUE THREAD

**Issue by stevebovy** [Neilpang/acme.sh#1290]
Steps to reproduce
------------------

How do I force the "verify" code to be re-run (for testing purposes)

Debug log
-----------------

[Sun Feb 18 19:48:48 PST 2018] home.miscbitbag.org is already verified, skip http-01.
[Sun Feb 18 19:48:48 PST 2018] ok, let's start to verify
[Sun Feb 18 19:48:48 PST 2018] home.miscbitbag.org is already verified, skip http-01.
[Sun Feb 18 19:48:48 PST 2018] pid
[Sun Feb 18 19:48:48 PST 2018] No need to restore nginx, skip.
[Sun Feb 18 19:48:48 PST 2018] _clearupdns
[Sun Feb 18 19:48:48 PST 2018] skip dns.
[Sun Feb 18 19:48:48 PST 2018] Verify finished, start to sign.

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
no

**Comment by scifibob** [comment]
This must be one of the most arrogant answers I've ever seen.
We are many out there who are testing certificates with "--test" or --staging".
I have found no way to revoke or delete those certs in case I want to use another auth mekanism.
I'm trying the "--challenge-alias" after I successfully made a test certificate with dns_01, but it just succedes with the above mentioned message.
The only way for me to do this is to test with another domain.
Not all of us have an unlimited amount of domains to test with.
If this is a limitation in acme.sh, then just say so. I'm sure there are lots of people out there who are ready to find out if it can be done anyway.

**Comment by Neilpang** [comment]
@scifibob 

>> If this is a limitation in acme.sh, 

It's not a limitation of acme.sh, but of letsencrypt.

Fortunately,  letsencrypt changed its behavior months ago.  With `--test` flag,  it will not cache the validation result.
Everytime you will need to verify your domain again.

**Comment by technotablet** [comment]
I wasn't able to make it work with `--test` flag.
The caching of domain verification is linked with one's account on the Let's Encrypt Servers.
I removed the `ca` directory in the `.acme.sh` folder that led to the creation of a new account on the staging server. I was then able to reverify my domain.

**Comment by damnms** [comment]
--test did not work for me either 
deleting "ca" worked 

@Neilpang maybe you should delete that childish "no".
