### ISSUE TITLE
Something feels wrong in the upgrade function

### ISSUE THREAD

**Issue by Shayan-To** [Neilpang/acme.sh#1294]
I was reading through the code in `acme.sh` and I found [this](https://github.com/Neilpang/acme.sh/blob/4a6b31fbe2a9d14c69bf8e6be973da88eb42ebed/acme.sh#L5405):

```bash
upgrade() {
  if (
    _initpath
    export LE_WORKING_DIR
    cd "$LE_WORKING_DIR"
    _installOnline "nocron"
  ); then
    _info "Upgrade success!"
    exit 0
  else
    _err "Upgrade failed!"
    exit 1
  fi
}
```

The line in the if condition, `_installOnline "nocron"`, shouldn't the `"nocron"` be some variable substitution?

**Comment by Shayan-To** [comment]
And a question has come to my mind. Will the upgrade command honor whether I have chosen to install the cron job? Or will it just install the cron job anyway?

**Comment by Neilpang** [comment]
Your second question answered the first one.

**Comment by Shayan-To** [comment]
But I think that my second question made things worse.

Passing the *string* `"nocron"` to function `_installOnline`, when (I think) it assumes its input to be `1` or nothing, would probably make the upgrade process always install the cron job, regardless of however the installation was done.

**Comment by Neilpang** [comment]
why not try it out ? 
Nobody assumes the "nocron" is "1".
