### ISSUE TITLE
Feature request: Auto install for cPanel Service SSL Certificates

### ISSUE THREAD

**Issue by Tntdruid** [Neilpang/acme.sh#130]
Only thing i need now :)

**Comment by Neilpang** [comment]
what do you mean ?

**Comment by Neilpang** [comment]
I have bought a  shared Cpanel webhosting with Shell access.   it's working there.
So, what do you need ?

I don't quite understand.

**Comment by lucasRolff** [comment]
@Neilpang - I guess what @Tntdruid would like is following:
https://documentation.cpanel.net/display/SDK/UAPI+Functions+-+SSL%3A%3Ainstall_ssl

**Comment by lucasRolff** [comment]
Or following actually:
https://documentation.cpanel.net/display/SDK/WHM+API+1+Functions+-+install_service_ssl_certificate

**Comment by Tntdruid** [comment]
I use this messy code on my test server :)

#!/bin/bash
/bin/mkdir /root/ssl

\cp -f /var/cpanel/ssl/cpanel/* /root/ssl/
/bin/cat /root/.le/$HOSTNAME/$HOSTNAME.key /root/.le/$HOSTNAME/cert.pem /root/.le/$HOSTNAME/ca.pem > /var/cpanel/ssl/cpanel/cpanel.pem
/bin/chown cpanel:cpanel /var/cpanel/ssl/cpanel/cpanel.pem
/sbin/service cpanel restart
/sbin/service httpd restart

\cp -f /var/cpanel/ssl/exim/* /root/ssl/
/bin/cat /root/.le/$HOSTNAME/privkey.pem > /var/cpanel/ssl/exim/exim.key
/bin/cat /root/.le/$HOSTNAME/cert.pem /etc/letsencrypt/live/$HOSTNAME/ca.pem > /var/cpanel/ssl/exim/exim.crt
/bin/chown mailnull:mail /var/cpanel/ssl/exim/exim.*
/sbin/service exim restart

\cp -f /var/cpanel/ssl/ftp/* /root/ssl/
/bin/cat /root/.le/$HOSTNAME/$HOSTNAME.key > /var/cpanel/ssl/ftp/ftpd-rsa-key.pem
/bin/cat /root/.le/$HOSTNAME/cert.pem /root/.le/$HOSTNAME/ca.pem > /var/cpanel/ssl/ftp/ftpd-rsa.pem
/bin/cat /root/.le/$HOSTNAME/$HOSTNAME.key /root/.le/$HOSTNAME/cert.pem /root/.le/$HOSTNAME/ca.pem > /var/cpanel/ssl/ftp/pure-ftpd.pem
/bin/chown root:wheel /var/cpanel/ssl/ftp/*
/sbin/service pure-ftpd restart

\cp -f /var/cpanel/ssl/dovecot/* /root/ssl/
/bin/cat /root/.le/$HOSTNAME/$HOSTNAME.key > /var/cpanel/ssl/dovecot/dovecot.key
/bin/cat /root/.le/$HOSTNAME/cert.pem /root/.le/$HOSTNAME/ca.pem > /var/cpanel/ssl/dovecot/dovecot.crt
/bin/chown root:wheel /var/cpanel/ssl/dovecot/dovecot.*
/sbin/service dovecot restart

have to manual run it, no idea how to call it afler LE issue or renew a cert

**Comment by Neilpang** [comment]
you can write those code in `/root/.le/$HOSTNAME/reload.sh`

```
chmod +x reload.sh

```

Then run command:
```
acme.sh  --installcert   -d $HOSTNAME  --reloadcmd "bash  reload.sh"
```

the `reload.sh` will be called when the cert is renewed.
