### ISSUE TITLE
Subdomain acme-v02.api unresolvable

### ISSUE THREAD

**Issue by alexetgus** [Neilpang/acme.sh#1301]
Hi!

The subdomain **acme-v02.api.letsencrypt.org** is is not resolvable (**NXDOMAIN**).

The IPs of v01 are equal to v02?
If so, I can create a DNS zone temporarily...

**Reproduce:** Issue a wildcard certificat for whatever domain.
acme.sh --issue -d my_domain.tld -d *.my_domain.tld --dns dns_cf

**LOG:**
[ven. févr. 23 12:59:52 CET 2018] Using config home:/root/.acme.sh
[ven. févr. 23 12:59:52 CET 2018] DOMAIN_PATH='/root/.acme.sh/my_domain.tld'
[ven. févr. 23 12:59:52 CET 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[ven. févr. 23 12:59:52 CET 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[ven. févr. 23 12:59:52 CET 2018] GET
[ven. févr. 23 12:59:52 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[ven. févr. 23 12:59:52 CET 2018] timeout=
[ven. févr. 23 12:59:52 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[ven. févr. 23 12:59:52 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[ven. févr. 23 12:59:52 CET 2018] ret='6'
[ven. févr. 23 12:59:52 CET 2018] Can not init api.
[ven. févr. 23 12:59:52 CET 2018] Le_NextRenewTime
[ven. févr. 23 12:59:53 CET 2018] _on_before_issue
[ven. févr. 23 12:59:53 CET 2018] Le_LocalAddress
[ven. févr. 23 12:59:53 CET 2018] Check for domain='my_domain.tld'
[ven. févr. 23 12:59:53 CET 2018] _currentRoot='dns_cf'
[ven. févr. 23 12:59:53 CET 2018] Check for domain='*.my_domain.tld'
[ven. févr. 23 12:59:53 CET 2018] _currentRoot='dns_cf'
[ven. févr. 23 12:59:53 CET 2018] config file is empty, can not read CA_KEY_HASH
[ven. févr. 23 12:59:53 CET 2018] Using config home:/root/.acme.sh
[ven. févr. 23 12:59:53 CET 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[ven. févr. 23 12:59:53 CET 2018] GET
[ven. févr. 23 12:59:53 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[ven. févr. 23 12:59:53 CET 2018] timeout=
[ven. févr. 23 12:59:53 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[ven. févr. 23 12:59:53 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[ven. févr. 23 12:59:53 CET 2018] ret='6'
[ven. févr. 23 12:59:53 CET 2018] Can not init api.
[ven. févr. 23 12:59:53 CET 2018] RSA key
[ven. févr. 23 12:59:53 CET 2018] Registering account
[ven. févr. 23 12:59:53 CET 2018] url
[ven. févr. 23 12:59:53 CET 2018] payload='{"termsOfServiceAgreed": true}'
[ven. févr. 23 12:59:53 CET 2018] GET
[ven. févr. 23 12:59:53 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[ven. févr. 23 12:59:53 CET 2018] timeout=
[ven. févr. 23 12:59:53 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[ven. févr. 23 12:59:53 CET 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[ven. févr. 23 12:59:53 CET 2018] ret='6'
[ven. févr. 23 12:59:53 CET 2018] Can not connect to https://acme-v02.api.letsencrypt.org/directory to get nonce.
[ven. févr. 23 12:59:53 CET 2018] Register account Error: 
[ven. févr. 23 12:59:53 CET 2018] _on_issue_err
[ven. févr. 23 12:59:53 CET 2018] Please check log file for more details: /root/.acme.sh/acme.sh.log

Sorry for my English, I'm French.

**Comment by FernandoMiguel** [comment]
v2 isnt live yet. was supposed to go live end of the month but has been delayed

**Comment by FernandoMiguel** [comment]
https://community.letsencrypt.org/t/acmev2-and-wildcard-launch-delay/53654

**Comment by alexetgus** [comment]
Ah! Ok.
Too bad, we'll wait.
Thank you.
