### ISSUE TITLE
--signcsr is changing own CSR and removes additional data

### ISSUE THREAD

**Issue by JumpleNM** [Neilpang/acme.sh#1306]
Don't know if this is a bug or part of Let's Encrypt, but when I create a CSR with openssl with additional data and extensions they all get removed _before_ acme.sh sends the signing request to Let's Encrypt.
Is there a way to forward my CSR without modifying it ?

**Comment by Neilpang** [comment]
no,  acme.sh never modifies your CSR,  we just send it AS-IS to the CA server.

But, the letsencrypt CA will modify it.  It only keeps a few content that it allows, such as: the subject, the DNS names, and OCSP attributes etc.  Any other content will be dropped.

**Comment by JumpleNM** [comment]
Thanks for the fast response.                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: 24 February 2018 1:43 p.m.To: acme.sh@noreply.github.comReply to: reply@reply.github.comCc: Andre.Springer@netmanagement.net; author@noreply.github.comSubject: Re: [Neilpang/acme.sh] --signcsr is changing own CSR and removes additional data (#1306)  no,  acme.sh never modifies your CSR,  we just send it AS-IS to the CA server.
But, the letsencrypt CA will modify it.  It only keeps a few content that it allows, such as: the subject, the DNS names, and OCSP attributes etc.  Any other content will be dropped.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
