### ISSUE TITLE
所有步骤都走通了，但最后 访问 网站但https 一直超时，证书不生效

### ISSUE THREAD

**Issue by wolaiye1010** [Neilpang/acme.sh#1307]
所有步骤都走通了，但最后 访问 网站但https 一直超时，证书不生效
![image](https://user-images.githubusercontent.com/15831945/36627571-b55534a2-197f-11e8-96a1-4942d6d7ca5b.png)

nginx 配置如下：
server {
        listen 80;

        # SSL configuration
        #
         listen 443 ssl;
         ssl_certificate /etc/nginx/ssl/fullchain.cer;
         ssl_certificate_key /etc/nginx/ssl/zhimawa.key;
         server_name  zhimawa.com www.zhimawa.com *.zhimawa.com;

**Comment by wolaiye1010** [comment]
ip 可以访问 ，域名不行

**Comment by 523860169** [comment]
如果你签署证书是使用--test，acme v2还没有正式开放，也就是说泛域名支持还未完全开放，目前使用需要导入letsencrypt提供的根证书，具体google一下然后导入

**Comment by wolaiye1010** [comment]
@523860169 , 大哥，看不懂 什么意思啊，需要我真么做啊，
我 签署证书就是按照 你github 上的步骤 
acme.sh --issue  -d zhimawa.com  -d www.zhimawa.com vpn.zhimawa.com  --nginx
没有加 --test 啊，
另外 chrome ip 访问 点开证书 浏览器显示证书是有效的啊

![image](https://user-images.githubusercontent.com/15831945/36630341-fa3ac008-199f-11e8-97d3-7ba1bafc4c0a.png)

**Comment by Neilpang** [comment]
这是你nginx 配置问题.
现在好像已经修好了, 我这里能访问域名正常了.

**Comment by Neilpang** [comment]
还有一个可能, 检查你本地的 hosts 文件.
或者 ping 一下.
我怀疑你本地 dns 解析有问题.

**Comment by wolaiye1010** [comment]
@Neilpang , 问题解决了，
我使用的是 阿里云 ubuntu ，根据网上的配置，把证书 分别放到了
ssl_certificate /etc/ssl/certs/fullchain.cer;
ssl_certificate_key /etc/ssl/private/zhimawa.key;
这两个位置，域名就可以放问了
![image](https://user-images.githubusercontent.com/15831945/36630535-d0952c9a-19a2-11e8-93dd-fea2dcae8247.png)
