### ISSUE TITLE
how to use wildcart?

### ISSUE THREAD

**Issue by ColinZeb** [Neilpang/acme.sh#1312]
------------------

Debug log

[Tue Feb 27 13:17:14 CST 2018] Using config home:/root/.acme.sh
[Tue Feb 27 13:17:14 CST 2018] DOMAIN_PATH='/root/.acme.sh/mmin.us'
[Tue Feb 27 13:17:14 CST 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Tue Feb 27 13:17:14 CST 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Tue Feb 27 13:17:14 CST 2018] GET
[Tue Feb 27 13:17:14 CST 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Feb 27 13:17:14 CST 2018] timeout=
[Tue Feb 27 13:17:14 CST 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Feb 27 13:17:14 CST 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 6
[Tue Feb 27 13:17:14 CST 2018] ret='6'
[Tue Feb 27 13:17:14 CST 2018] Can not init api.
[Tue Feb 27 13:17:14 CST 2018] Le_NextRenewTime='1524804845'
[Tue Feb 27 13:17:14 CST 2018] _on_before_issue
[Tue Feb 27 13:17:14 CST 2018] Le_LocalAddress

-----------------

```
export CX_Key=""
export CX_Secret=""
acme.sh  --issue -d #####  -d *.####    --dns dns_cx
```

![screen.png](https://i.loli.net/2018/02/27/5a94e93e4782c.png)

**Comment by Neilpang** [comment]
加上  `--test` 参数.
目前只有测试版, 没有正式版.

**Comment by ColinZeb** [comment]
我以为今天发布了

**Comment by xseven007** [comment]
我在使用命令的时候出现了以下错误，请问是什么原因呢？
[Sun Mar  4 18:25:37 CST 2018] Getting domain auth token for each domain
[Sun Mar  4 18:25:38 CST 2018] Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:malformed","detail":"No Key ID in JWS header","status": 400}
[Sun Mar  4 18:25:38 CST 2018] Please check log file for more details: /root/.acme.sh/acme.sh.log
