### ISSUE TITLE
Verify error:Invalid response

### ISSUE THREAD

**Issue by zwl1619** [Neilpang/acme.sh#132]
```
[root@i001 le]# le.sh  --issue  -d www.aa.com -w /var/www/www.aa.com -d 111.aa.com -w /var/www/111.aa.com[Wed Apr 13 00:03:39 CST 2016] Creating account key
[Wed Apr 13 00:03:39 CST 2016] Use default length 2048
[Wed Apr 13 00:03:40 CST 2016] Registering account
[Wed Apr 13 00:03:43 CST 2016] Registered
[Wed Apr 13 00:03:43 CST 2016] Creating domain key
[Wed Apr 13 00:03:43 CST 2016] Use length 2048
[Wed Apr 13 00:03:43 CST 2016] Creating csr
[Wed Apr 13 00:03:43 CST 2016] Multi domain='DNS:111.aa.com'
[Wed Apr 13 00:03:43 CST 2016] Verify each domain
[Wed Apr 13 00:03:43 CST 2016] Getting webroot for domain='www.aa.com'
[Wed Apr 13 00:03:43 CST 2016] Getting token for domain='www.aa.com'
[Wed Apr 13 00:03:46 CST 2016] Getting webroot for domain='111.aa.com'
[Wed Apr 13 00:03:46 CST 2016] Getting token for domain='111.aa.com'
[Wed Apr 13 00:03:49 CST 2016] Verifying:www.aa.com
[Wed Apr 13 00:03:57 CST 2016] www.aa.com:Verify error:Invalid response from http://www.aa.com/.well-known/acme-challenge/OPGcJDQ2vODKvCj6hstNyWylE000LGbwRZa3CWihx3E [101.**.**.***]: 404
[root@i001 le]# 

```
What should I do?

**Comment by Neilpang** [comment]
你应该用的是 nginx，

请在网站的conf文件中加入：
···
    location /.well-known/acme-challenge/ {
        alias /var/www/challenges/;
        try_files $uri =404;
    }
···


加入后的样子大概是这样：

···
server {
    listen 80;
    server_name yoursite.com www.yoursite.com;

    location /.well-known/acme-challenge/ {
        alias /var/www/challenges/;
        try_files $uri =404;
    }

    ...
}
···

**Comment by zwl1619** [comment]
已经加了上面的配置，仍出现这样的错误。   
这篇博客中说，出现这样的错误，就试一下DNS模式。https://imququ.com/post/letsencrypt-certificate.html
所以尝试dns。

**Comment by slogoo** [comment]
同样遇到这个问题，如果是nginx的话，一般是因为服务器拒绝访问，解决方法2个：

1.在include *.conf; 下方加入以下代码：

…

server {

listen 80;

server_name yoursite.com www.yoursite.com;

include *.conf;

       location ^~ /.well-known/acme-challenge/ 
    {
        default_type "text/plain";
        root  /home/wwwroot/yoursite;
    }
    
    location = /.well-known/acme-challenge/ 
    {
        try_files $uri =404;
    }
    



…

2.在yoursite.conf中，把拒绝访问代码注释掉：

        #location ~ /\.
        #{
        #    deny all;
        #}

**Comment by chjiyun** [comment]
@slogoo 有用   root  /home/wwwroot 就行了
