### ISSUE TITLE
Issue Wildcard certificate with zsh failed

### ISSUE THREAD

**Issue by CloudnuY** [Neilpang/acme.sh#1334]
Steps to reproduce
------------------
In zsh, input the code as follow, then an error occurred...

Debug log
-----------------

```
$ acme.sh --issue -d example.com -d www.example.com -d *.example.com --dns dns_cf --debug 2
```

There is an error with zsh: `zsh: no matches found: *.example.com`.
Nothing debug info.
Bug when I use bash, it's fine.

Zsh version
-----------------
```
$ zsh --version
zsh 5.4.2 (x86_64-apple-darwin16.7.0)
```

**Comment by Neilpang** [comment]
have you tried:
```
acme.sh --issue  -d '*.example.com'   ....
```

**Comment by CloudnuY** [comment]
It's solved......

Thanks for this solution😝
