### ISSUE TITLE
Support for remote servers via SSH

### ISSUE THREAD

**Issue by GustavGenberg** [Neilpang/acme.sh#1339]
Currently lacking the feauture to verify and transfer certificate to remote server via SSH.

Not really an issue, but I wanted to know if this is something you are considering.
I would highly appreciate a SSH function!

**Comment by FernandoMiguel** [comment]
You can use the post hook to move the keys to the remote servers

-- 
Fernando Miguel

**Comment by Neilpang** [comment]
We have ssh deolpy hook to transfer the cert via ssh:
https://github.com/Neilpang/acme.sh/tree/master/deploy#3-deploy-the-cert-to-remote-server-through-ssh-access

**Comment by GustavGenberg** [comment]
Yes, I known....

But the acme verification process is only available via 'webroot', and not ssh.

**Comment by Neilpang** [comment]
Yes,  I don't want to support ssh-webroot mode.
It's too far away.
you can run acme.sh on the target machine.
or you can use dns api mode.
or even you can use dns alias mode  https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode

**Comment by GustavGenberg** [comment]
Okay. I think the dns alias mode is the closest right now!

Thanks.
