### ISSUE TITLE
TLS mode renewal not working

### ISSUE THREAD

**Issue by jult** [Neilpang/acme.sh#1345]
So much for auto-renewal. First time I tried having certs autorenew, and now they all fail with

`The supported validation types are: dns-01 http-01 , but you specified: tls-sni-01`

Using acme.sh 2.7.7
Any idea how to best renew an existing cert now? It's going to expire in 16 hours.
All else is fine, 443 is free etc. Is TLS mode still 'temporarily disabled' for LE? If so, is there a way to renew it in another mode?

**Comment by Neilpang** [comment]
do not use tls mode.  it's removed by Letsencrypt.
please use webroot mode or dns mode instead.

**Comment by FernandoMiguel** [comment]
More info about tls-sni-01 being removed

https://community.letsencrypt.org/t/2018-01-09-issue-with-tls-sni-01-and-shared-hosting-infrastructure/49996

https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811

**Comment by jult** [comment]
Wow, OK, somehow that news had slipped my feeds.
So much for automation with open source :{
