### ISSUE TITLE
acme.sh fails on opnsense

### ISSUE THREAD

**Issue by martgras** [Neilpang/acme.sh#1356]
acmesh fails on opnsense

opnsense starts acme.sh from php using a pattern like this
```
<?php
  $process = popen("/usr/local/sbin/acme.sh","r");
  // ...
  pclose($process);
?>
```

The reason why this fails is a broken pipe error 
I used truss (a tool similar to strace for FreeBSD) and saw errors like this for every printf statement

> write(1,"\n",1)                                  ERR#32 'Broken pipe'
> write(2,"printf: write error on stdout\n",30)    ERR#32 'Broken pipe'
> 

Repro: Start acme.sh using the php code above 

It will fail after createDomainKey

> [Tue Mar 13 10:12:42 CET 2018] ACME_DIRECTORY='https://acme-staging.api.letsencrypt.org/directory'
> [Tue Mar 13 10:12:42 CET 2018] _ACME_SERVER_HOST='acme-staging.api.letsencrypt.org'
> [Tue Mar 13 10:12:42 CET 2018] _createkey for file:/var/etc/acme-client/home/t29.example.com/t29.example.com.key
> [Tue Mar 13 10:12:42 CET 2018] Use length 4096
> [Tue Mar 13 10:12:42 CET 2018] Using RSA: 4096
> [Tue Mar 13 10:12:42 CET 2018] The domain key is here: /var/etc/acme-client/home/t29.example.com/t29.example.com.key
> [Tue Mar 13 10:12:42 CET 2018] Create domain key error.
> 

The reason for that failure a side effect of the _info call in createDomainKey. 
Because the stdout pipe is broken printf fails with exit code 2   and any statement checking $? after _info / _debug will fail because $? is 2 at this point
The failure is triggered by calling _info/_debug as the last operation in a function and then checking the exit code

Possible fixes: 
1) Do nothing - the php code should read the output and avoid the broken pipe error 
2) Make sure your functions return 0 if you are checking the result. See my changes in https://github.com/Neilpang/acme.sh/pull/1350
3) Change _debug and _info to either always return 0 or pass-through the previous exit code (and ignore printf failures)

**Comment by martgras** [comment]
instead of using acme.sh to demonstrate the  problem you can also run this simple shell script using the php code above
```
#!/usr/bin/env sh

printf "Hello Log\n" >t.log
exitlog="$?"
printf "Hello console\n"
exitcon="$?"
result="Exit code from console: $exitcon Exit code from log: $exitlog"
echo "$result"
echo "$result" >>t.log
```
$exitcon will be 2 if called from the php script

**Comment by Neilpang** [comment]
please add `return 0`  and send a PR.
Thanks.

**Comment by martgras** [comment]
return 0 works unless someone uses 
```
response="$(_get "$ep")"
_debug "http response: $response"
if [ "$_ret" != "0" ]; then ..
```

I sent PR #1357 a bit earlier today

**Comment by irgendwr** [comment]
I'm also experiencing this issue in OPNsense.
@Neilpang why don't you merge #1357 or add `return 0` yourself if the fix is that easy?

**Comment by Neilpang** [comment]
merged
