### ISSUE TITLE
多域名renew 存在错误

### ISSUE THREAD

**Issue by liuxyon** [Neilpang/acme.sh#136]
当我使用DNS模式EC256 一次获取多个域名证书时候，实际结果它只输出了头一个域名的证书，后面的域名显示未提交.

$ le --renew  -d mail.1.org -d mail.2.net

$ le --renew  -d mail.2.net
[2016年04月14日  1:28:11] mail.2.net is not a issued domain, skip.

**Comment by Neilpang** [comment]
--renew  的时候,  只需要指定 一个主域名就行了,  只接受一个参数.
```
le --renew -d mail.1.org
```



如果你首次签的时候只签了一个域名,  后期想加域名, 不能用renew,  请重新issue 一个.

**Comment by liuxyon** [comment]
按你说的方法还是只能获得头一个域名的证书.

**Comment by Neilpang** [comment]
@liuxyon 
我刚刚试了,  renew 了 一个 有4个域名的证书, 没有问题.  renew 后的证书依然有4个域名.

请你把 之前的 域名配置都删掉: `~/.le/mail.1.org`

然后重新签发，　然后再尝试renew.

最后,
建议升级到最新的代码：
卸载 le.sh uninstall

然后安装最新的代码.

**Comment by liuxyon** [comment]
没卸载版本情况，安装新域名测试还是只能获得一个域名证书.

**Comment by Neilpang** [comment]
是我理解错了吗?   确实只会生成一个证书,  但是这个证书里面包含了你的所有域名.

**Comment by liuxyon** [comment]
我也才发现一个证书里包含了多个域名在备注里. 

另外为什么改成长的名字acme，为什么这次不能简略输入acme 代替acme.sh?

如何能CMD windows命令支持 按F3直接自动重写上次的内容，每次要重写手工输入很长字母很繁琐.

**Comment by Neilpang** [comment]
因为 `le` 太短了,  容易歧义.  而且不能真正表达项目的内容.  

输入 `acme` 后, 按 `Tab` 键, 会自动补全 为 `acme.sh`

目前正在做进一步参数智能补全功能.

**Comment by liuxyon** [comment]
我觉得到没什么,易于使用才是目的. 安装证书功能怎么用，帮助说明上没具体例子，使用命令能绑定到IIS站点上吗？
你邮箱多少哦。。老乡
