### ISSUE TITLE
the red on black text is really hard to see if you are old

### ISSUE THREAD

**Issue by buddyp1952** [Neilpang/acme.sh#1377]
acme.sh is great, and I know this is really nit-picky but the red on black text is really hard to see if you are old. Please consider us old folks and either use a higher contrast color combination or add an option to turn colorized text off.

**Comment by FernandoMiguel** [comment]
isnt this something your terminal should set ?

**Comment by buddyp1952** [comment]
possibly, but it seems like acme.sh is picking the colors. None of the
other command line programs use red on black like this - see attached
screenshot.

Joel

**Comment by FernandoMiguel** [comment]
no attachment

**Comment by buddyp1952** [comment]
how strange. gmail thinks I sent an attachment

try this URL http://strongbad.freecountryusa.org/foo.png

Joel

**Comment by FernandoMiguel** [comment]
github strips email attachments. 
for future reference, add via web

**Comment by Reborns** [comment]
@buddyp1952 Try "tee", this will remove all colors.  ./acme.sh -foo | tee

**Comment by buddyp1952** [comment]
That's a great solution! I'll just do that and close the issue.

Thanks,

Joel

On Wed, Mar 14, 2018 at 2:05 PM, Sasha Harutyunyan <notifications@github.com

**Comment by Neilpang** [comment]
@Reborns   @FernandoMiguel 
Hi guys, 
why not try the `--no-color` parameters ?

```sh
acme.sh --no-color  --issue   ......
```
