### ISSUE TITLE
Issuing from csr file: bug when Subject has wildcard, and subjectAltName has same domain without wildcard

### ISSUE THREAD

**Issue by joellimberg** [Neilpang/acme.sh#1380]
Steps to reproduce
------------------

Create a CSR with multiple `DNS:` entries in `SubjectAltNames`, and a wildcard domain name as the `subject`.

acme.sh seems to try and remove the duplicate, but also removes another, separate domain.

Debug log
-----------------

Command: `acme.sh /snip/ --signcsr /snip/`

Illustrating the problem with entries from the debug log:

`_csrsubj='*.eelvaade-veeb.example.dev'`

`_dnsAltnames='DNS:*.eelvaade-veeb.example.dev,DNS:eelvaade-veeb.example.dev'`

`AltNames contains subject`

`_csrdomainlist='*.eelvaade-veeb.example.dev,'`

/---/

`_main_domain='*.eelvaade-veeb.example.dev'`
`_alt_domains='*.eelvaade-veeb.example.dev,'`

Note how the `eelvaade-veeb.example.dev` name originally present in the csr disappears, and only the wildcard-prefixed version remains.

This _might_ be done by `_dnsAltnames="$(printf "%s" "$_dnsAltnames," | sed "s/DNS:$_csrsubj,//g")"` (but I'm not _sed_-proficient enough to actually know for sure)

**Comment by joellimberg** [comment]
Actually: the issue might be related to the "AltNames contains subject" check itself.

It seems, that:

- if subject in csr is '*.example.com', and altname is 'example.com'
- … then this is detected as "AltNames contains subject".

**Comment by Neilpang** [comment]
why this issue got closed ?

**Comment by joellimberg** [comment]
Sorry about that — I started thinking that wildcard and non-wildcard domain validation would be the same anyway (TXT record on same domain), so maybe the deduplication is intentional.

And, I was just starting out testing acme.sh, so maybe the entire thing was my fault due to some sort of misconfiguration.

---

I tweaked the `csr` generation code I'm using to add a non-wildcard cert as the `subject`, and other domains as `SubjectAltNames`, so it's not affecting me any more.

Do you think there could still be a bug there in acme.sh?
