### ISSUE TITLE
Issue with TXT record for wildcard

### ISSUE THREAD

**Issue by HepplerDotNet** [Neilpang/acme.sh#1381]
Steps to reproduce:
[root@dev .acme.sh]# ./acme.sh --issue --dns --signcsr --csr /etc/nginx/ssl/ecdsa/example.com/example.com.csr --keylength ec-384 --debug

TXT record is set with TTL 60 and I can run dig -t txt _acme-challenge.example.com and get the right record. I installed acme.sh today, so it's latest version

Debug output (domain changed)
[Mi 14. Mär 19:52:04 CET 2018] Lets find script dir.
[Mi 14. Mär 19:52:04 CET 2018] _SCRIPT_='./acme.sh'
[Mi 14. Mär 19:52:04 CET 2018] _script='/root/.acme.sh/acme.sh'
[Mi 14. Mär 19:52:04 CET 2018] _script_home='/root/.acme.sh'
[Mi 14. Mär 19:52:04 CET 2018] Using default home:/root/.acme.sh
[Mi 14. Mär 19:52:04 CET 2018] Using config home:/root/.acme.sh
https://github.com/Neilpang/acme.sh
v2.7.8
[Mi 14. Mär 19:52:04 CET 2018] _csrsubj='*.example.com'
[Mi 14. Mär 19:52:04 CET 2018] _csrsubj='*.example.com'
[Mi 14. Mär 19:52:04 CET 2018] _dnsAltnames='DNS:*.example.com'
[Mi 14. Mär 19:52:04 CET 2018] AltNames doesn't contain subject
[Mi 14. Mär 19:52:04 CET 2018] _csrdomainlist='*.example.com'
[Mi 14. Mär 19:52:04 CET 2018] ECC CSR
[Mi 14. Mär 19:52:04 CET 2018] Using config home:/root/.acme.sh
[Mi 14. Mär 19:52:04 CET 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mi 14. Mär 19:52:04 CET 2018] DOMAIN_PATH='/root/.acme.sh/*.example.com_ecc'
[Mi 14. Mär 19:52:04 CET 2018] Copy csr to: /root/.acme.sh/*.example.com_ecc/*.example.com.csr
[Mi 14. Mär 19:52:04 CET 2018] _main_domain='*.example.com'
[Mi 14. Mär 19:52:04 CET 2018] _alt_domains='*.example.com'
[Mi 14. Mär 19:52:04 CET 2018] Using config home:/root/.acme.sh
[Mi 14. Mär 19:52:04 CET 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mi 14. Mär 19:52:04 CET 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Mi 14. Mär 19:52:04 CET 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mi 14. Mär 19:52:04 CET 2018] GET
[Mi 14. Mär 19:52:04 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Mi 14. Mär 19:52:04 CET 2018] timeout=
[Mi 14. Mär 19:52:04 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mi 14. Mär 19:52:05 CET 2018] ret='0'
[Mi 14. Mär 19:52:05 CET 2018] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mi 14. Mär 19:52:05 CET 2018] ACME_NEW_AUTHZ
[Mi 14. Mär 19:52:05 CET 2018] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mi 14. Mär 19:52:05 CET 2018] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mi 14. Mär 19:52:05 CET 2018] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Mi 14. Mär 19:52:05 CET 2018] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Mi 14. Mär 19:52:05 CET 2018] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mi 14. Mär 19:52:05 CET 2018] ACME_VERSION='2'
[Mi 14. Mär 19:52:05 CET 2018] Le_NextRenewTime
[Mi 14. Mär 19:52:05 CET 2018] _on_before_issue
[Mi 14. Mär 19:52:05 CET 2018] _chk_main_domain='*.example.com'
[Mi 14. Mär 19:52:05 CET 2018] _chk_alt_domains='*.example.com'
[Mi 14. Mär 19:52:05 CET 2018] Le_LocalAddress
[Mi 14. Mär 19:52:05 CET 2018] d='*.example.com'
[Mi 14. Mär 19:52:05 CET 2018] Check for domain='*.example.com'
[Mi 14. Mär 19:52:05 CET 2018] _currentRoot='dns'
[Mi 14. Mär 19:52:05 CET 2018] d='*.example.com'
[Mi 14. Mär 19:52:05 CET 2018] Check for domain='*.example.com'
[Mi 14. Mär 19:52:05 CET 2018] _currentRoot='dns'
[Mi 14. Mär 19:52:05 CET 2018] d
[Mi 14. Mär 19:52:05 CET 2018] _saved_account_key_hash is not changed, skip register account.
[Mi 14. Mär 19:52:05 CET 2018] Signing from existing CSR.
[Mi 14. Mär 19:52:05 CET 2018] Getting domain auth token for each domain
[Mi 14. Mär 19:52:05 CET 2018] d='*.example.com'
[Mi 14. Mär 19:52:05 CET 2018] d
[Mi 14. Mär 19:52:05 CET 2018] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mi 14. Mär 19:52:05 CET 2018] payload='{"identifiers": [{"type":"dns","value":"*.example.com"},{"type":"dns","value":"*.example.com"}]}'
[Mi 14. Mär 19:52:05 CET 2018] RSA key
[Mi 14. Mär 19:52:05 CET 2018] HEAD
[Mi 14. Mär 19:52:05 CET 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mi 14. Mär 19:52:05 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -H "Content-Type: application/jose+json" '
[Mi 14. Mär 19:52:06 CET 2018] _ret='0'
[Mi 14. Mär 19:52:06 CET 2018] POST
[Mi 14. Mär 19:52:06 CET 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mi 14. Mär 19:52:06 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -H "Content-Type: application/jose+json" '
[Mi 14. Mär 19:52:06 CET 2018] _ret='0'
[Mi 14. Mär 19:52:06 CET 2018] code='201'
[Mi 14. Mär 19:52:06 CET 2018] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/31150218/13722'
[Mi 14. Mär 19:52:06 CET 2018] GET
[Mi 14. Mär 19:52:06 CET 2018] url='https://acme-v02.api.letsencrypt.org/acme/authz/VqOsQdMcPGc99UsvKufv3pXL_iNb67BRgTxwVZEF_3k'
[Mi 14. Mär 19:52:06 CET 2018] timeout=
[Mi 14. Mär 19:52:06 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mi 14. Mär 19:52:07 CET 2018] ret='0'
[Mi 14. Mär 19:52:07 CET 2018] d='*.example.com'
[Mi 14. Mär 19:52:07 CET 2018] Getting webroot for domain='*.example.com'
[Mi 14. Mär 19:52:07 CET 2018] _w='dns'
[Mi 14. Mär 19:52:07 CET 2018] _currentRoot='dns'
[Mi 14. Mär 19:52:07 CET 2018] entry='"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/VqOsQdMcPGc99UsvKufv3pXL_iNb67BRgTxwVZEF_3k/3817297847","token":"-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM"'
[Mi 14. Mär 19:52:07 CET 2018] token='-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM'
[Mi 14. Mär 19:52:07 CET 2018] uri='https://acme-v02.api.letsencrypt.org/acme/challenge/VqOsQdMcPGc99UsvKufv3pXL_iNb67BRgTxwVZEF_3k/3817297847'
[Mi 14. Mär 19:52:07 CET 2018] keyauthorization='-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM.O0WsqhRbqtt3fZETrSHSe9pkVacKHFxnFJOPiNuCE_E'
[Mi 14. Mär 19:52:07 CET 2018] dvlist='*.example.com#-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM.O0WsqhRbqtt3fZETrSHSe9pkVacKHFxnFJOPiNuCE_E#https://acme-v02.api.letsencrypt.org/acme/challenge/VqOsQdMcPGc99UsvKufv3pXL_iNb67BRgTxwVZEF_3k/3817297847#dns-01#dns'
[Mi 14. Mär 19:52:07 CET 2018] d='*.example.com'
[Mi 14. Mär 19:52:07 CET 2018] Getting webroot for domain='*.example.com'
[Mi 14. Mär 19:52:07 CET 2018] _w='dns'
[Mi 14. Mär 19:52:07 CET 2018] _currentRoot='dns'
[Mi 14. Mär 19:52:07 CET 2018] entry='"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/VqOsQdMcPGc99UsvKufv3pXL_iNb67BRgTxwVZEF_3k/3817297847","token":"-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM"'
[Mi 14. Mär 19:52:07 CET 2018] token='-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM'
[Mi 14. Mär 19:52:07 CET 2018] uri='https://acme-v02.api.letsencrypt.org/acme/challenge/VqOsQdMcPGc99UsvKufv3pXL_iNb67BRgTxwVZEF_3k/3817297847'
[Mi 14. Mär 19:52:07 CET 2018] keyauthorization='-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM.O0WsqhRbqtt3fZETrSHSe9pkVacKHFxnFJOPiNuCE_E'
[Mi 14. Mär 19:52:07 CET 2018] dvlist='*.example.com#-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM.O0WsqhRbqtt3fZETrSHSe9pkVacKHFxnFJOPiNuCE_E#https://acme-v02.api.letsencrypt.org/acme/challenge/VqOsQdMcPGc99UsvKufv3pXL_iNb67BRgTxwVZEF_3k/3817297847#dns-01#dns'
[Mi 14. Mär 19:52:07 CET 2018] d
[Mi 14. Mär 19:52:07 CET 2018] vlist='*.example.com#-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM.O0WsqhRbqtt3fZETrSHSe9pkVacKHFxnFJOPiNuCE_E#https://acme-v02.api.letsencrypt.org/acme/challenge/VqOsQdMcPGc99UsvKufv3pXL_iNb67BRgTxwVZEF_3k/3817297847#dns-01#dns,*.example.com#-n0lTe9aL3U0_bIgxS-WBh4z6XbohXOnXe5hSm5JjYM.O0WsqhRbqtt3fZETrSHSe9pkVacKHFxnFJOPiNuCE_E#https://acme-v02.api.letsencrypt.org/acme/challenge/VqOsQdMcPGc99UsvKufv3pXL_iNb67BRgTxwVZEF_3k/3817297847#dns-01#dns,'
[Mi 14. Mär 19:52:07 CET 2018] d='*.example.com'
[Mi 14. Mär 19:52:07 CET 2018] _d_alias
[Mi 14. Mär 19:52:07 CET 2018] txtdomain='_acme-challenge.example.com'
[Mi 14. Mär 19:52:07 CET 2018] txt='PD2beglv57c97EZytpKIh554caQXNmZi3muADaQ0580'
[Mi 14. Mär 19:52:07 CET 2018] d_api
[Mi 14. Mär 19:52:07 CET 2018] Add the following TXT record:
[Mi 14. Mär 19:52:07 CET 2018] Domain: '_acme-challenge.example.com'
[Mi 14. Mär 19:52:07 CET 2018] TXT value: 'PD2beglv57c97EZytpKIh554caQXNmZi3muADaQ0580'
[Mi 14. Mär 19:52:07 CET 2018] Please be aware that you prepend _acme-challenge. before your domain
[Mi 14. Mär 19:52:07 CET 2018] so the resulting subdomain will be: _acme-challenge.example.com
[Mi 14. Mär 19:52:07 CET 2018] d='*.example.com'
[Mi 14. Mär 19:52:07 CET 2018] _d_alias
[Mi 14. Mär 19:52:07 CET 2018] txtdomain='_acme-challenge.example.com'
[Mi 14. Mär 19:52:07 CET 2018] txt='PD2beglv57c97EZytpKIh554caQXNmZi3muADaQ0580'
[Mi 14. Mär 19:52:07 CET 2018] d_api
[Mi 14. Mär 19:52:07 CET 2018] Add the following TXT record:
[Mi 14. Mär 19:52:07 CET 2018] Domain: '_acme-challenge.example.com'
[Mi 14. Mär 19:52:07 CET 2018] TXT value: 'PD2beglv57c97EZytpKIh554caQXNmZi3muADaQ0580'
[Mi 14. Mär 19:52:07 CET 2018] Please be aware that you prepend _acme-challenge. before your domain
[Mi 14. Mär 19:52:07 CET 2018] so the resulting subdomain will be: _acme-challenge.example.com
[Mi 14. Mär 19:52:07 CET 2018] Dns record not added yet, so, save to /root/.acme.sh/*.example.com_ecc/*.example.com.conf and exit.
[Mi 14. Mär 19:52:07 CET 2018] Please add the TXT records to the domains, and retry again.
[Mi 14. Mär 19:52:07 CET 2018] pid
[Mi 14. Mär 19:52:07 CET 2018] No need to restore nginx, skip.
[Mi 14. Mär 19:52:07 CET 2018] _clearupdns
[Mi 14. Mär 19:52:07 CET 2018] skip dns.
[Mi 14. Mär 19:52:07 CET 2018] _on_issue_err
[Mi 14. Mär 19:52:07 CET 2018] Please add '--debug' or '--log' to check more details.
[Mi 14. Mär 19:52:07 CET 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Mi 14. Mär 19:52:07 CET 2018] socat doesn't exists.

**Comment by gitthismoney** [comment]
have the same prob!

**Comment by comfytoday** [comment]
First time setting up for me, but I think I had the same issue.

What happens if you now run the same command, but use --renew?

acme.sh --renew -d example.com

That seemed to work for me...

**Comment by snpwr** [comment]
> acme.sh --renew -d example.com
> 
> That seemed to work for me...

Same here.

Consecutive calls of `acme.sh --issue` just ask to add the TXT records again. 
But using `--renew` successfully issues the cert,

**Comment by Neilpang** [comment]
@gitthismoney   @snpwr 
There are 2 steps if you use dns manual mode.

```sh
acme.sh --issue .....
acme.sh --renew .....
```

dns manual mode can not renew the cert automatically.  please use dns api mode or dns alias mode instead.

**Comment by HepplerDotNet** [comment]
I'm new to acme.sh, I used certbot before, but certbot often breaks my automatism after updates and I don't get it to work with wildcard. I need to use my own csr for wildcard, so I can use HPKP. 
acme.sh -renew worked on my dev box. Have to test it now with HPKP active.

@comfytoday @Neilpang thanks for the hints!

**Comment by cfstras** [comment]
The second step with --renew wasn't obvious to me. Worked like a charm though -- Thanks for the hint.

Added that to the wiki for people coming after me.
