### ISSUE TITLE
手动添加TXT， '_' (下划线)，只允许存在于SRV记录

### ISSUE THREAD

**Issue by gorouter** [Neilpang/acme.sh#1383]
Steps to reproduce

Add the following txt record:
Domain:_acme-challenge.example.com
Txt value:9ihDbjYfTExAYeDs4DBUeuTo18KBzwvTEjUnSwd32-c

------------------

Debug log
添加TXT解析时报“主机记录值仅支持字母、数字、中文和'-'、'.'、'*'、'@'”
看了说明说是“   '_' (下划线)，只允许存在于SRV记录  ”
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
换解析服务商.
或者再注册一个域名, 用 dnsalias 模式 : https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode
