### ISSUE TITLE
泛域名官方已经支持了

### ISSUE THREAD

**Issue by phonehold** [Neilpang/acme.sh#1385]
泛域名官方已经支持了
现在有打算支持泛域名申请吗

**Comment by leavelost** [comment]
我已经在群晖上申请成功了，阿里的~

**Comment by khs1994** [comment]
Now Support！

**Comment by Neilpang** [comment]
@phonehold   现在的年轻人都不看新闻的吗

**Comment by tankren** [comment]
请问如何从v1升级到v2？谢谢

**Comment by khs1994** [comment]
```bash
$ acme.sh --upgrade
```

**Comment by tankren** [comment]
这个是升级客户端 我说我的证书如何升级成泛域名的，重新签发吗

**Comment by khs1994** [comment]
yes

**Comment by Neilpang** [comment]
@tankren  你不用管 v1 v2,  只要你用的是 最新版的acme.sh,  它会自动处理所有问题.

**Comment by tankren** [comment]
@Neilpang 那比如我现在是几个子域名都申请的 升级了客户端会自动申请泛域名吗？

**Comment by Neilpang** [comment]
@tankren   不会, v2 不等于 泛域名.   v2 也可以申请普通域名.   其实申请的证书没有区别,  acme 会根据域名是否泛域名自己决定是否使用 v1 还是v2.

**Comment by tankren** [comment]
@Neilpang嗯 所以作为一个喜欢尝鲜的人我重新申请了 哈哈哈
