### ISSUE TITLE
xxxx is not a issued domain, skip.

### ISSUE THREAD

**Issue by mxdg** [Neilpang/acme.sh#1402]
[Info] input your domain:
(defaultly cancel):libreoffice.cn
[Info] select required type:
1.rsa
2.ecc
(defaultly choose rsa):
[Sat Mar 17 21:25:15 CST 2018] Registering account
[Sat Mar 17 21:25:17 CST 2018] Registered
[Sat Mar 17 21:25:17 CST 2018] ACCOUNT_THUMBPRINT='JmkQkCVstEJ2l8zP4M8Nsm3Z_N2rF0TFjFCTm0ORhBE'
[Sat Mar 17 21:25:17 CST 2018] Creating domain key
[Sat Mar 17 21:25:17 CST 2018] Single domain='libreoffice.cn'
[Sat Mar 17 21:25:17 CST 2018] Getting domain auth token for each domain
[Sat Mar 17 21:25:17 CST 2018] Getting webroot for domain='libreoffice.cn'
[Sat Mar 17 21:25:17 CST 2018] Getting new-authz for domain='libreoffice.cn'
[Sat Mar 17 21:25:20 CST 2018] The new-authz request is ok.
[Sat Mar 17 21:25:20 CST 2018] Add the following TXT record:
[Sat Mar 17 21:25:20 CST 2018] Domain: '_acme-challenge.libreoffice.cn'
[Sat Mar 17 21:25:20 CST 2018] TXT value: 'oOMuknQcc4AMk5_4dMdxQ1alOmvx7P4h1pBepyEniJs'
[Info] now you should perform domain TXT record authorization
then press 'enter' to continue11111111111111111111
[Sat Mar 17 21:29:18 CST 2018] Renew: 'libreoffice.cn'
[Sat Mar 17 21:29:18 CST 2018] 'libreoffice.cn' is not a issued domain, skip.
mv: cannot stat ‘/root/.acme.sh/libreoffice.cn_ecc’: No such file or directory
[Error] failed, please check !

**Comment by FernandoMiguel** [comment]
you seem to be using dns method in manual mode .
please be aware of the limitations of this method and that it should **ONLY** be used for development and testing.

you should use dns with an API

**Comment by FernandoMiguel** [comment]
```
$ dig TXT _acme-challenge.libreoffice.cn +short
"405Ra29_YkSYkhmBT8pQq5GHY1oY98fhTbU0voOs4xY"
```

if you do 
`$ acme.sh --renew libreoffice.cn`
it should validate the txt record and issue you a cert

**Comment by mxdg** [comment]
At last it was successful，thanks
