### ISSUE TITLE
Howto enable auto-upgrade

### ISSUE THREAD

**Issue by 74cmonty** [Neilpang/acme.sh#1403]
I have installed acme.sh on Alpine Linux.
It is working as expected, I can upgrade running acme.sh --upgrade:
`vm102-haproxy:/# acme.sh --upgrade
[Sat Mar 17 14:49:42 CET 2018] Installing from online archive.
[Sat Mar 17 14:49:42 CET 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Sat Mar 17 14:49:44 CET 2018] Extracting master.tar.gz
[Sat Mar 17 14:49:44 CET 2018] It is recommended to install socat first.
[Sat Mar 17 14:49:44 CET 2018] We use socat for standalone server if you use standalone mode.
[Sat Mar 17 14:49:44 CET 2018] If you don't use standalone mode, just ignore this warning.
[Sat Mar 17 14:49:44 CET 2018] Installing to /root/.acme.sh
[Sat Mar 17 14:49:44 CET 2018] Installed to /root/.acme.sh/acme.sh
[Sat Mar 17 14:49:44 CET 2018] Good, bash is found, so change the shebang to use bash as preferred.
[Sat Mar 17 14:49:44 CET 2018] OK
[Sat Mar 17 14:49:44 CET 2018] Install success!
[Sat Mar 17 14:49:44 CET 2018] Upgrade success!`

Question:
How do I enable auto-upgrade?
And how does this auto-upgrade work?

THX

**Comment by FernandoMiguel** [comment]
`$ acme.sh  --upgrade  --auto-upgrade`
will add the option to your conf file and the next time acme.sh runs, it will auto upgraded if needed

**Comment by 74cmonty** [comment]
Which conf file in /root/.acme.sh will be modified? And what is the relevant option?

**Comment by FernandoMiguel** [comment]
you dont need to change anything there.
`$ acme.sh --upgrade --auto-upgrade`
 will do it for you

**Comment by 74cmonty** [comment]
THX
