### ISSUE TITLE
Installed successfully but the bash told me command not found

### ISSUE THREAD

**Issue by CHN-STUDENT** [Neilpang/acme.sh#1412]
Steps to reproduce
------------------
Today,i tried install acme.sh on my server(OS:CentOS7.4).And i read the install guidebook,i downloaded it by curl,And the script told me it installed successfully.but when i tried to use it by command `acme.sh` ,the bash told me command not found.
Like this:
```
[root@VM_6_201_centos acme.sh]# acme.sh
-bash: acme.sh: command not found
```
Also i tried to use another install ways,like using `wget` or `git clone` to install it,the script told me can find this installed it on my server.But the bash told me the command also not found.

```
[root@VM_6_201_centos acme.sh]# ./acme.sh --install
[Sun Mar 18 18:31:06 CST 2018] It is recommended to install socat first.
[Sun Mar 18 18:31:06 CST 2018] We use socat for standalone server if you use standalone mode.
[Sun Mar 18 18:31:06 CST 2018] If you don't use standalone mode, just ignore this warning.
[Sun Mar 18 18:31:06 CST 2018] Installing to /root/.acme.sh
[Sun Mar 18 18:31:06 CST 2018] Installed to /root/.acme.sh/acme.sh
[Sun Mar 18 18:31:06 CST 2018] Installing alias to '/root/.bashrc'
[Sun Mar 18 18:31:06 CST 2018] OK, Close and reopen your terminal to start using acme.sh
[Sun Mar 18 18:31:06 CST 2018] Installing alias to '/root/.cshrc'
[Sun Mar 18 18:31:06 CST 2018] Installing alias to '/root/.tcshrc'
[Sun Mar 18 18:31:07 CST 2018] Installing cron job
31 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Sun Mar 18 18:31:07 CST 2018] Good, bash is found, so change the shebang to use bash as preferred.
[Sun Mar 18 18:31:07 CST 2018] OK
[root@VM_6_201_centos acme.sh]# acme.sh
-bash: acme.sh: command not found
```

Debug log
-----------------
Because i can not use it command,so i used absolute path to run it.
But when i tried to print it,but the the script told me `Unknown parameter : .....`
```
[root@VM_6_201_centos ~]# ./.acme.sh/acme.sh  --issue ..... --debug 2
[Sun Mar 18 18:38:27 CST 2018] Unknown parameter : .....
```

So can you tell me what happend and help me?Thanks!
If you think you need more information,i will give you.

**Comment by Neilpang** [comment]
close your terminal, and open it again.

```
[Sun Mar 18 18:31:06 CST 2018] OK, Close and reopen your terminal to start using acme.sh
```

**Comment by CHN-STUDENT** [comment]
@Neilpang  Ok,i reopen a new terminal now,now i can use it command.
But i find i can not print the debug log?
```
[root@VM_6_201_centos ~]# acme.sh --issue ..... --debug 2
[Sun Mar 18 19:00:50 CST 2018] Unknown parameter : .....

```

**Comment by CHN-STUDENT** [comment]
@Neilpang  sorry,i think i make a mistake... 
And i suggest you add this information `OK, Close and reopen your terminal to start using acme.sh` on the guidebook.
Thanks for your help .
