### ISSUE TITLE
Could not install acme successful

### ISSUE THREAD

**Issue by walker9** [Neilpang/acme.sh#1415]
On other same servers, i've installed the acme client without troubles.

But at one it doesn't work.
Ubuntu 10.04.4 LTS lucid
Apache Version is 2.2.14
OpenSSL is 0.9.8k

Folder .acme.sh in /root was created, but this error occurs.

That was my steps:

wget https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh --no-check-certificate
chmod 777 acme.sh

./acme.sh --issue -d domain.com -w /home/www \
-d www.domain.com -w /home/www \
--certpath /etc/ssl/certs/domain.crt \
--keypath /etc/ssl/certs/domain.key \
--fullchainpath /etc/ssl/certs/domain.pem \
--reloadcmd  "service apache2 restart" --log --debug 2

[log.txt](https://github.com/Neilpang/acme.sh/files/1822804/log.txt)

**Comment by beebird** [comment]
说中文吧。。。
log文件指出了错误的原因：gnu error code: 5 SSL verification failure
猜测是中间某个步骤wget或者curl的时候无法验证letsencrypt的某个https证书。

结合你步骤中用wget下载acme.sh时，也要跳过证书校验的情况看来，你这个ubuntu机器似乎有点问题，比如根证书不全。。

建议检查下机器。

**Comment by walker9** [comment]
@beebird
With Google translate i've understand something and could solved it. It seems the problem was, that curl was not installed.

After installing curl and repeating the steps from bottom, the acme client works now. Thanks!

**Comment by beebird** [comment]
@walker9 :-)
