### ISSUE TITLE
Sign failed: "detail":"Error creating new cert"

### ISSUE THREAD

**Issue by Iodok** [Neilpang/acme.sh#1416]
Hey Neilpang,

I am running acme.sh since several month, allways worked as a charme.
Suddenly today my apache refused to start beacuse openssl could not decode the renewed certificates.
It stopped working with the following in the logs:
139869079996232:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1343:
139869079996232:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:393:Type=X509
139869079996232:error:0906700D:PEM routines:PEM_ASN1_read_bio:ASN1 lib:pem_oth.c:83:

I just restored my certificates from yesterday and it works again.
The same happende on 2 certificates, both where renewed by acme.sh this night.
I am going to stop the cron for now, hoping you find the issue.

Iodok

Steps to reproduce
acme.sh -renew -d fototeam-hessen.de -d www.fototeam-hessen.de

Debug log
-----------------

```
[Sun Mar 18 00:00:26 CET 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -H "Content-Type: application/jose+json" '
[Sun Mar 18 00:00:58 CET 2018] _ret='0'
[Sun Mar 18 00:00:58 CET 2018] code='500'
[Sun Mar 18 00:00:58 CET 2018] Le_LinkCert
[Sun Mar 18 00:00:58 CET 2018] Sign failed: "detail":"Error creating new cert"
[Sun Mar 18 00:00:58 CET 2018] _on_issue_err
[Sun Mar 18 00:00:58 CET 2018] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Sun Mar 18 00:00:58 CET 2018] Return code: 1
[Sun Mar 18 00:00:58 CET 2018] Error renew fototeam-hessen.de.
```

**Comment by Neilpang** [comment]
upgrade to the latest code and  try again with `--debug 2`

```
acme.sh --upgrade
```

**Comment by Iodok** [comment]
It is (and was)  v2.7.8.
After having upgraded it works now.
Thanks a lot

Iodok
