### ISSUE TITLE
用cloudflare的dnsapi，提示invalid domain

### ISSUE THREAD

**Issue by cloudflyz** [Neilpang/acme.sh#1421]
用cloudflare的dnsapi，一直错误是个域名都是错误。。。。
Steps to reproduce
------------------
[error.acme.sh.log](https://github.com/Neilpang/acme.sh/files/1828484/error.acme.sh.log)

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by beebird** [comment]
我遇到过同样的问题，终端也走proxy试试。

**Comment by cloudflyz** [comment]
@beebird 感谢，原来是系统问题，从denbian 9切换到centos后，问题已经解决
