### ISSUE TITLE
Problem with DNS TXT detect

### ISSUE THREAD

**Issue by zdzichu6969** [Neilpang/acme.sh#1423]
Problem with DNS TXT:

command:
acme.sh  --issue -d *.linuxiarz.pl --dns

acme.sh -v
https://github.com/Neilpang/acme.sh
v2.7.8

System: ubuntu 14.04
Bind: 9.11.2

Record exist: 
dig txt @9.9.9.9 _acme-challenge.linuxiarz.pl +short
"ZYl7vS8DeqyqW_SfH-GMB2N5b5rsDNvUII6CX9K-AVA"

dig txt @8.8.4.4 _acme-challenge.linuxiarz.pl +short
"ZYl7vS8DeqyqW_SfH-GMB2N5b5rsDNvUII6CX9K-AVA"

Debug log
-----------------

> 
[debuglog.txt](https://github.com/Neilpang/acme.sh/files/1829471/debuglog.txt)

**Comment by Zurlys** [comment]
Confirmed. Same issue

System: Mac OS.
SHELL: bash

**Comment by Zurlys** [comment]
@zdzichu6969 add --renew to your command and it will solve your issue

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/dns-manual-mode
