### ISSUE TITLE
Wildcard cert -d *.mydomain.com or -d '*.mydomain.com'

### ISSUE THREAD

**Issue by cloudflyz** [Neilpang/acme.sh#1424]
1.
`-d *.mydomain.com or -d '*.mydomain.com'`

readme上申请Wildcard cert示例是带有单引号，网上的教程都没有带单引号，请问是否有影响？还是会自动纠正？

2.
--install-cert 用法，可否后续增加命令，指向多个证书和密钥放置位置？
Wildcard cert在使用--install-cert 时*.example.com 是否需要添加上？如下：
`acme.sh --install-cert -d example.com -d *.example.com\`

**Comment by Neilpang** [comment]
1. 加不加都行. 最早我也是没加的, 但是发现在某些shell下 不加引号会导致歧义.  所以建议都加上. 没区别.
2. 不可以.

**Comment by Neilpang** [comment]
3. --install-cert 后面只需要跟一个主域名就可以了(也就是第一个域名).  多余的没有用.

**Comment by cloudflyz** [comment]
@Neilpang 感谢回答，由于用的宝塔面板，ssl证书管理混乱，目前已经想办法修改nginx配置文件，把多域名指向单个宝塔证书文件夹
