### ISSUE TITLE
Docker Hub tags for v2 are obsolete

### ISSUE THREAD

**Issue by travismiller** [Neilpang/acme.sh#1425]
Should the `2` and `v2` tags on docker hub be caught up with `latest`? Or maybe removed?

Currently, using `neilpang/acme.sh:2` in production does not include the CA cert in the fullchain. Obviously this has been addressed in the last 2 months in `neilpang/acme.sh:latest`. My pre-v2-release scripts were using the `2` tag for testing. Works like a charm with `latest`.

https://hub.docker.com/r/neilpang/acme.sh/tags/

This tool is awesome. ❤️

**Comment by FernandoMiguel** [comment]
Revert to latest 
V2 was for testing 

-- 
Fernando Miguel

**Comment by Neilpang** [comment]
use  latest  instead.
