### ISSUE TITLE
jcloud DNS API integration

### ISSUE THREAD

**Issue by shiny** [Neilpang/acme.sh#1426]
Could you please consider adding jcloud (京东云)  DNS API support? it's quite useful for wildcard domain.

**Comment by Neilpang** [comment]
能不能多给点信息,  链接啊, 文档啊.  节约大家的时间啊.

**Comment by Neilpang** [comment]
建议使用 dns alis 模式:
https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode

**Comment by shiny** [comment]
发出来就意识到这个问题，找了半天文档没有，然后提工单，得知目前还不支持 API 接入。
