### ISSUE TITLE
DNS manual mode: The supported validation types are: dns-01 , but you specified: http-01

### ISSUE THREAD

**Issue by Marcel0024** [Neilpang/acme.sh#1433]
Getting this error requesting a wildcard.

I did use the --dns command:

Steps to reproduce
------------------

![image](https://user-images.githubusercontent.com/14852157/37771069-c1083c98-2dd6-11e8-938f-d6c94711828c.png)

Debug log
-----------------

Thu Mar 22 13:40:48 CET 2018] _main_domain='*.printapi.io'
[Thu Mar 22 13:40:48 CET 2018] _alt_domains='no'
[Thu Mar 22 13:40:48 CET 2018] Using config home:/home/pi/.acme.sh
[Thu Mar 22 13:40:48 CET 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Mar 22 13:40:48 CET 2018] DOMAIN_PATH='/home/pi/.acme.sh/*.printapi.io'
[Thu Mar 22 13:40:48 CET 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Thu Mar 22 13:40:48 CET 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Thu Mar 22 13:40:48 CET 2018] GET
[Thu Mar 22 13:40:48 CET 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Thu Mar 22 13:40:48 CET 2018] timeout=
[Thu Mar 22 13:40:48 CET 2018] _CURL='curl -L --silent --dump-header /home/pi/.acme.sh/http.header  -g '
[Thu Mar 22 13:40:49 CET 2018] ret='0'
[Thu Mar 22 13:40:49 CET 2018] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Thu Mar 22 13:40:49 CET 2018] ACME_NEW_AUTHZ
[Thu Mar 22 13:40:49 CET 2018] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Mar 22 13:40:49 CET 2018] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Thu Mar 22 13:40:49 CET 2018] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Thu Mar 22 13:40:49 CET 2018] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Thu Mar 22 13:40:49 CET 2018] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Mar 22 13:40:49 CET 2018] ACME_VERSION='2'
[Thu Mar 22 13:40:49 CET 2018] Le_NextRenewTime
[Thu Mar 22 13:40:49 CET 2018] _on_before_issue
[Thu Mar 22 13:40:50 CET 2018] _chk_main_domain='*.printapi.io'
[Thu Mar 22 13:40:50 CET 2018] _chk_alt_domains
[Thu Mar 22 13:40:50 CET 2018] Le_LocalAddress
[Thu Mar 22 13:40:50 CET 2018] d='*.printapi.io'
[Thu Mar 22 13:40:50 CET 2018] Check for domain='*.printapi.io'
[Thu Mar 22 13:40:50 CET 2018] _currentRoot=' --yes-I-understand-dns-manual-mode'
[Thu Mar 22 13:40:50 CET 2018] d
[Thu Mar 22 13:40:50 CET 2018] _saved_account_key_hash is not changed, skip register account.
[Thu Mar 22 13:40:50 CET 2018] Read key length:
[Thu Mar 22 13:40:50 CET 2018] _createcsr
[Thu Mar 22 13:40:50 CET 2018] Single domain='*.printapi.io'
[Thu Mar 22 13:40:50 CET 2018] Getting domain auth token for each domain
[Thu Mar 22 13:40:50 CET 2018] d
[Thu Mar 22 13:40:50 CET 2018] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Mar 22 13:40:50 CET 2018] payload='{"identifiers": [{"type":"dns","value":"*.printapi.io"}]}'
[Thu Mar 22 13:40:50 CET 2018] RSA key
[Thu Mar 22 13:40:50 CET 2018] HEAD
[Thu Mar 22 13:40:50 CET 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Mar 22 13:40:50 CET 2018] _CURL='curl -L --silent --dump-header /home/pi/.acme.sh/http.header  -g '
[Thu Mar 22 13:40:51 CET 2018] _ret='0'
[Thu Mar 22 13:40:51 CET 2018] POST
[Thu Mar 22 13:40:51 CET 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Mar 22 13:40:51 CET 2018] _CURL='curl -L --silent --dump-header /home/pi/.acme.sh/http.header  -g '
[Thu Mar 22 13:40:51 CET 2018] _ret='0'
[Thu Mar 22 13:40:51 CET 2018] code='201'
[Thu Mar 22 13:40:52 CET 2018] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/31643007/598777'
[Thu Mar 22 13:40:52 CET 2018] GET
[Thu Mar 22 13:40:52 CET 2018] url='https://acme-v02.api.letsencrypt.org/acme/authz/CypELa1py0EidcgUl9q5tMhIGB30z1dIH9V627B5vdY'
[Thu Mar 22 13:40:52 CET 2018] timeout=
[Thu Mar 22 13:40:52 CET 2018] _CURL='curl -L --silent --dump-header /home/pi/.acme.sh/http.header  -g '
[Thu Mar 22 13:40:52 CET 2018] ret='0'
[Thu Mar 22 13:40:52 CET 2018] d='*.printapi.io'
[Thu Mar 22 13:40:52 CET 2018] Getting webroot for domain='*.printapi.io'
[Thu Mar 22 13:40:52 CET 2018] _w='--yes-I-understand-dns-manual-mode'
[Thu Mar 22 13:40:52 CET 2018] _currentRoot='--yes-I-understand-dns-manual-mode'
[Thu Mar 22 13:40:52 CET 2018] entry
[Thu Mar 22 13:40:52 CET 2018] Error, can not get domain token entry *.printapi.io
[Thu Mar 22 13:40:52 CET 2018] The supported validation types are: dns-01 , but you specified: http-01
[Thu Mar 22 13:40:52 CET 2018] pid
[Thu Mar 22 13:40:52 CET 2018] No need to restore nginx, skip.
[Thu Mar 22 13:40:52 CET 2018] _clearupdns
[Thu Mar 22 13:40:53 CET 2018] skip dns.
[Thu Mar 22 13:40:53 CET 2018] _on_issue_err
[Thu Mar 22 13:40:53 CET 2018] Please check log file for more details: /home/pi/.acme.sh/acme.sh.log

.config file:

![image](https://user-images.githubusercontent.com/14852157/37781807-c06365c2-2df1-11e8-902c-53bb08e8de1f.png)

Le_Webroot should be 'dns' no?

**Comment by Marcel0024** [comment]
@Neilpang Can you confirm this bug was introduced with commit [a092362](https://github.com/Neilpang/acme.sh/commit/a0923622aea8f650be8d92116f464d1c426e49ba)? I had it worked before for a wildcard for another domain.

**Comment by somanos** [comment]
Hi
I'm facing the same issue with acme.sh --issue --test -d '*.drumee.com' --dns /etc/acme/store/dnsapi/dns_ovh.sh
Got in *.drumee.com.conf

Le_Domain='*.drumee.com'
Le_Alt='no'
Le_Webroot='/etc/acme/store/dnsapi/dns_ovh.sh'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-staging-v02.api.letsencrypt.org/directory'
Le_Keylength=''
Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5791370/120877'

**Comment by Marcel0024** [comment]
@somanos  Shouldn't it be 

acme.sh --issue --test -d *.drumee.com --dns dns_ovh ?

**Comment by somanos** [comment]
Thanks @Marcel0024 
Now get 

> It seems that your api file is not correct, it must have a function named: dns_ovh.sh_add

**Comment by Marcel0024** [comment]
@somanos  What version do you have?

acme.sh --version

**Comment by somanos** [comment]
@Marcel0024 
/etc/acme/acme.sh --version
https://github.com/Neilpang/acme.sh
v2.7.8

**Comment by Marcel0024** [comment]
@somanos I don't know. But i do believe it's a separate issue then mine. 

[This issue](https://github.com/Neilpang/acme.sh/issues/395) seems to suggest your credentials may be wrong.

**Comment by somanos** [comment]
@Marcel0024 Thanks for your help.
I misspelled . I used  acme.sh --issue --test -d '*.drumee.com' --dns dns_ovh**.sh**
instead of acme.sh --issue --test -d '*.drumee.com' --dns dns_ovh (without sh extension) :'(

**Comment by Neilpang** [comment]
@Marcel0024    show me your full command line

**Comment by Marcel0024** [comment]
![image](https://user-images.githubusercontent.com/14852157/37834226-931b9d70-2ead-11e8-8498-37adcc23484e.png)

This:

```
acme.sh --issue --test -d *.printapi.io --dns \ --yes-I-understand-dns-manual-mode-enough-go-ahead-please
```

**Comment by flukaxkx** [comment]
I have the same problem

the command line is:
```
sudo ~/.acme.sh/acme.sh --issue --force -d xxx.com -d *.xxx.com --dns yes-I-know-dns-manual-mode-enough-go-ahead-please
```
or
```
sudo ~/.acme.sh/acme.sh --issue --force -d xxx.com -d *.xxx.com --dns \ --yes-I-know-dns-manual-mode-enough-go-ahead-please
```
then get the same reaponse
```
[Sat Mar 24 21:23:38 EDT 2018] Using stage ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Sat Mar 24 21:23:38 EDT 2018] Multi domain='DNS:xxx.com,DNS:*.xxx.com'
[Sat Mar 24 21:23:38 EDT 2018] Getting domain auth token for each domain
[Sat Mar 24 21:23:39 EDT 2018] Getting webroot for domain='xxx.com'
[Sat Mar 24 21:23:39 EDT 2018] Getting webroot for domain='*.xxx.com'
[Sat Mar 24 21:23:39 EDT 2018] Error, can not get domain token entry *.chkacct.com
[Sat Mar 24 21:23:39 EDT 2018] The supported validation types are: dns-01 , but you specified: http-01
[Sat Mar 24 21:23:39 EDT 2018] Please add '--debug' or '--log' to check more details.
[Sat Mar 24 21:23:39 EDT 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

**Comment by flukaxkx** [comment]
@Marcel0024 @Neilpang 
It is OK now
```
sudo ~/.acme.sh/acme.sh --issue --force -d xxx.com -d *.xxx.com --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please
```
then it response:
```
[Sun Mar 25 02:54:08 EDT 2018] Multi domain='DNS:xxx.com,DNS:*.xxx.com'
[Sun Mar 25 02:54:08 EDT 2018] Getting domain auth token for each domain
[Sun Mar 25 02:54:09 EDT 2018] Getting webroot for domain='xxx.com'
[Sun Mar 25 02:54:09 EDT 2018] Getting webroot for domain='*.xxx.com'
[Sun Mar 25 02:54:09 EDT 2018] Add the following TXT record:
[Sun Mar 25 02:54:09 EDT 2018] Domain: '_acme-challenge.xxx.com'
[Sun Mar 25 02:54:09 EDT 2018] TXT value: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbb'
[Sun Mar 25 02:54:09 EDT 2018] Please be aware that you prepend _acme-challenge. before your domain
[Sun Mar 25 02:54:09 EDT 2018] so the resulting subdomain will be: _acme-challenge.xxx.com
[Sun Mar 25 02:54:09 EDT 2018] Add the following TXT record:
[Sun Mar 25 02:54:09 EDT 2018] Domain: '_acme-challenge.xxx.com'
[Sun Mar 25 02:54:09 EDT 2018] TXT value: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaa'
[Sun Mar 25 02:54:09 EDT 2018] Please be aware that you prepend _acme-challenge. before your domain
[Sun Mar 25 02:54:09 EDT 2018] so the resulting subdomain will be: _acme-challenge.xxx.com
[Sun Mar 25 02:54:09 EDT 2018] Please add the TXT records to the domains, and re-run with --renew.
[Sun Mar 25 02:54:09 EDT 2018] Please add '--debug' or '--log' to check more details.
[Sun Mar 25 02:54:09 EDT 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

**Comment by Marcel0024** [comment]
@flukaxkx That did solve it. Wierd. Thanks!

**Comment by eslachance** [comment]
I have a similar issue but since I'm on name.com, which is part of the list of automatically supported registrars, I'm a little confused. The readme does say "You don't have to do anything!" but I'm getting the same error as in the original post. Note that I'm doing a wildcard domain, so the question is, is that supported as-is? 

Command: ```
acme.sh --issue --nginx -d *.evie.codes -d evie.codes -d *.evie-banned.me -d evie-banned.me -w /root/wordpress  
```

Log: ```
[Thu Mar 29 09:49:08 EDT 2018] Lets find script dir.
[Thu Mar 29 09:49:08 EDT 2018] _SCRIPT_='/root/.acme.sh/acme.sh'
[Thu Mar 29 09:49:08 EDT 2018] _script='/root/.acme.sh/acme.sh'
[Thu Mar 29 09:49:08 EDT 2018] _script_home='/root/.acme.sh'
[Thu Mar 29 09:49:08 EDT 2018] Using config home:/root/.acme.sh
https://github.com/Neilpang/acme.sh
v2.7.8
[Thu Mar 29 09:49:08 EDT 2018] _main_domain='*.evie.codes'
[Thu Mar 29 09:49:08 EDT 2018] _alt_domains='evie.codes,*.evie-banned.me,evie-banned.me'
[Thu Mar 29 09:49:08 EDT 2018] Using config home:/root/.acme.sh
[Thu Mar 29 09:49:08 EDT 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Mar 29 09:49:08 EDT 2018] DOMAIN_PATH='/root/.acme.sh/*.evie.codes'
[Thu Mar 29 09:49:08 EDT 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Thu Mar 29 09:49:08 EDT 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Thu Mar 29 09:49:08 EDT 2018] GET
[Thu Mar 29 09:49:08 EDT 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Thu Mar 29 09:49:08 EDT 2018] timeout=
[Thu Mar 29 09:49:08 EDT 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Mar 29 09:49:08 EDT 2018] ret='0'
[Thu Mar 29 09:49:08 EDT 2018] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Thu Mar 29 09:49:08 EDT 2018] ACME_NEW_AUTHZ
[Thu Mar 29 09:49:08 EDT 2018] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Mar 29 09:49:08 EDT 2018] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Thu Mar 29 09:49:08 EDT 2018] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Thu Mar 29 09:49:08 EDT 2018] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Thu Mar 29 09:49:08 EDT 2018] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Mar 29 09:49:08 EDT 2018] ACME_VERSION='2'
[Thu Mar 29 09:49:09 EDT 2018] Le_NextRenewTime
[Thu Mar 29 09:49:09 EDT 2018] _on_before_issue
[Thu Mar 29 09:49:09 EDT 2018] _chk_main_domain='*.evie.codes'
[Thu Mar 29 09:49:09 EDT 2018] _chk_alt_domains='evie.codes,*.evie-banned.me,evie-banned.me'
[Thu Mar 29 09:49:09 EDT 2018] Le_LocalAddress
[Thu Mar 29 09:49:09 EDT 2018] d='*.evie.codes'
[Thu Mar 29 09:49:09 EDT 2018] Check for domain='*.evie.codes'
[Thu Mar 29 09:49:09 EDT 2018] _currentRoot='nginx:'
[Thu Mar 29 09:49:09 EDT 2018] d='evie.codes'
[Thu Mar 29 09:49:09 EDT 2018] Check for domain='evie.codes'
[Thu Mar 29 09:49:09 EDT 2018] _currentRoot='/root/wordpress'
[Thu Mar 29 09:49:09 EDT 2018] d='*.evie-banned.me'
[Thu Mar 29 09:49:09 EDT 2018] Check for domain='*.evie-banned.me'
[Thu Mar 29 09:49:09 EDT 2018] _currentRoot='/root/wordpress'
[Thu Mar 29 09:49:09 EDT 2018] d='evie-banned.me'
[Thu Mar 29 09:49:09 EDT 2018] Check for domain='evie-banned.me'
[Thu Mar 29 09:49:09 EDT 2018] _currentRoot='/root/wordpress'
[Thu Mar 29 09:49:09 EDT 2018] d
[Thu Mar 29 09:49:09 EDT 2018] _saved_account_key_hash is not changed, skip register account.
[Thu Mar 29 09:49:09 EDT 2018] Read key length:
[Thu Mar 29 09:49:09 EDT 2018] _createcsr
[Thu Mar 29 09:49:09 EDT 2018] Multi domain='DNS:*.evie.codes,DNS:evie.codes,DNS:*.evie-banned.me,DNS:evie-banned.me'
[Thu Mar 29 09:49:09 EDT 2018] Getting domain auth token for each domain
[Thu Mar 29 09:49:09 EDT 2018] d='evie.codes'
[Thu Mar 29 09:49:09 EDT 2018] d='*.evie-banned.me'
[Thu Mar 29 09:49:09 EDT 2018] d='evie-banned.me'
[Thu Mar 29 09:49:09 EDT 2018] d
[Thu Mar 29 09:49:09 EDT 2018] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Mar 29 09:49:09 EDT 2018] payload='{"identifiers": [{"type":"dns","value":"*.evie.codes"},{"type":"dns","value":"evie.codes"},{"type":"dns","value":"*.evie-banned.me"},{"type":"dns","value":"evie-banned.me"}]}'
[Thu Mar 29 09:49:09 EDT 2018] RSA key
[Thu Mar 29 09:49:09 EDT 2018] HEAD
[Thu Mar 29 09:49:09 EDT 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Mar 29 09:49:09 EDT 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Mar 29 09:49:09 EDT 2018] _ret='0'
[Thu Mar 29 09:49:09 EDT 2018] POST
[Thu Mar 29 09:49:09 EDT 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Mar 29 09:49:09 EDT 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Mar 29 09:49:10 EDT 2018] _ret='0'
[Thu Mar 29 09:49:10 EDT 2018] code='201'
[Thu Mar 29 09:49:10 EDT 2018] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/32075126/1459143'
[Thu Mar 29 09:49:10 EDT 2018] GET
[Thu Mar 29 09:49:10 EDT 2018] url='https://acme-v02.api.letsencrypt.org/acme/authz/0UGR8mzJLLTskfngdmbdtKwbgNU5qd4coapB1hXSvbo'
[Thu Mar 29 09:49:10 EDT 2018] timeout=
[Thu Mar 29 09:49:10 EDT 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Mar 29 09:49:10 EDT 2018] ret='0'
[Thu Mar 29 09:49:10 EDT 2018] GET
[Thu Mar 29 09:49:10 EDT 2018] url='https://acme-v02.api.letsencrypt.org/acme/authz/7EATNUS-4zOZTA3OwQD7Q29mgPsjdpnXTr6pILRAIJg'
[Thu Mar 29 09:49:10 EDT 2018] timeout=
[Thu Mar 29 09:49:10 EDT 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Mar 29 09:49:10 EDT 2018] ret='0'
[Thu Mar 29 09:49:10 EDT 2018] GET
[Thu Mar 29 09:49:10 EDT 2018] url='https://acme-v02.api.letsencrypt.org/acme/authz/TS-LoQ8hm4czsw5QV1utjdPJ0CrpYJKgTJ6i2Ux4XEw'
[Thu Mar 29 09:49:10 EDT 2018] timeout=
[Thu Mar 29 09:49:10 EDT 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Mar 29 09:49:11 EDT 2018] ret='0'
[Thu Mar 29 09:49:11 EDT 2018] GET
[Thu Mar 29 09:49:11 EDT 2018] url='https://acme-v02.api.letsencrypt.org/acme/authz/_pdwluub_buKPy97FrViRFS33tKI2t4WBJcNQJcIrVc'
[Thu Mar 29 09:49:11 EDT 2018] timeout=
[Thu Mar 29 09:49:11 EDT 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Mar 29 09:49:11 EDT 2018] ret='0'
[Thu Mar 29 09:49:11 EDT 2018] d='*.evie.codes'
[Thu Mar 29 09:49:11 EDT 2018] Getting webroot for domain='*.evie.codes'
[Thu Mar 29 09:49:11 EDT 2018] _w='nginx:'
[Thu Mar 29 09:49:11 EDT 2018] _currentRoot='nginx:'
[Thu Mar 29 09:49:11 EDT 2018] entry
[Thu Mar 29 09:49:11 EDT 2018] Error, can not get domain token entry *.evie.codes
[Thu Mar 29 09:49:11 EDT 2018] The supported validation types are: dns-01 , but you specified: http-01
[Thu Mar 29 09:49:11 EDT 2018] pid
[Thu Mar 29 09:49:11 EDT 2018] No need to restore nginx, skip.
[Thu Mar 29 09:49:11 EDT 2018] _clearupdns
[Thu Mar 29 09:49:11 EDT 2018] skip dns.
[Thu Mar 29 09:49:11 EDT 2018] _on_issue_err
[Thu Mar 29 09:49:11 EDT 2018] Please add '--debug' or '--log' to check more details.
[Thu Mar 29 09:49:11 EDT 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Thu Mar 29 09:49:11 EDT 2018] socat doesn't exists.
[Thu Mar 29 09:49:11 EDT 2018] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2g  1 Mar 2016
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.10.3 (Ubuntu)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-stream --with-stream_ssl_module --with-mail --with-mail_ssl_module --with-threads
socat:
```

I tried reversing the domains with `evie.codes` being first and that seemed to work for that one, but got the same error on the first wildcard one, and it didn't try the rest.

**Comment by Neilpang** [comment]
@eslachance 

```
[Thu Mar 29 09:49:11 EDT 2018] The supported validation types are: dns-01 , but you specified: http-01
```

wildcard domains can only be validated by dns mode.  no other mode at all. you can not use `--nginx` or `-w` for wildcard domains.

**Comment by eslachance** [comment]
I thought name.com support would mean automatic DNS validation. Do you mean it only supports *manual* mode and doesn't support automatic renewals?

**Comment by springstim** [comment]
Regarding the message: "...but you specified: http-01" for multiple wildcards (Subject Alternative Names / SAN) in your CSR, it looks like you need to specify multiple --dns on the command line, one before each -d DOMAIN.  Without that, it will only use DNS manual mode for the first domain in your SAN list.

For example if your CSR contains SAN for *.example-1.com and *.example-2.com, then (at least this is what I'm seeing in v3.0.2) you need to put the extra "--dns" in there before the 2nd domain on the command line:

`acme.sh .....     --dns -d *.example-1.com  --dns -d *.example-2.com   .....`
