### ISSUE TITLE
ln -s做软链接是否也是直接使用安装目录下的证书文件的一种？

### ISSUE THREAD

**Issue by baoang** [Neilpang/acme.sh#1446]
看到说明中有这样一句
> 默认生成的证书都放在安装目录下: ~/.acme.sh/, 请不要直接使用此目录下的文件, 例如: 不要直接让 nginx/apache 的配置文件使用这下面的文件

因而及时撤回了对nginx的配置文件的修改，后来看到Vesta(我使用的主机面板工具)的一份证书使用说明文档提到将原证书所在目录`/home/admin/conf/web`下的(两个)证书文件删除，然后在该目录下做两个软链接，即类似这样的
```
ln -s /root/.acme.sh/<domain>/fullchain.cer /home/admin/conf/web/ssl.<domain>.pem
```
我想问这种操作方式是否也属于直接使用？

说明文件中还提及
>这里指定的所有参数都会被自动记录下来, 并在将来证书自动更新以后, 被再次自动调用.

这是否意味着在证书申请下来之后，只要在服务器上做过一次这个命令行的拷贝操作，以后在比如80天后证书自动更新完成，acme.sh会再次自动执行一次这个拷贝工作？

**Comment by msg7086** [comment]
> 我想问这种操作方式是否也属于直接使用？

Yes

> acme.sh会再次自动执行一次这个拷贝工作？

Check your `.acme.sh/domain/domain.conf`. It only executes whatever `Le_ReloadCmd` writes in the config file.

The best way is to specify fullchain and key path when generating the certificate, in which case acme.sh will automatically copy them out.

In your case, `--fullchain-file /home/admin/conf/web/ssl.domain.crt --key-file /home/admin/conf/web/ssl.domain.key`.

**Comment by baoang** [comment]
Thank you, @msg7086 . It then seems Vesta did a poor job by offering a not-that-secure solution.

Well, there is no Le_ReloadCmd line in my domain.conf?

**Comment by Neilpang** [comment]
不要用软连接.  老老实实的用 `--install-cert` 不好吗.
