### ISSUE TITLE
Issue Wildcard certificates

### ISSUE THREAD

**Issue by lesm** [Neilpang/acme.sh#1449]
could someone tell me where exactly I must put the TXT record?
I'm putting it in the public directory of my app, is it enough?

I'm using the last version
v2.7.8

here what I'm doing.

for example when I run this command
```bash
acme.sh --issue --staging --dns -d '*.demo-application.com' --yes-I-know-dns-manual-mode-enough-go-ahead-please
```
I received this output
```
Add the following TXT record:
Domain: '_acme-challenge.demo-application.com'
TXT value: '1BzfdoJ1-Tr09SwFk46CDbvc_wqO9sKAairNo8zsNVo'
```
and then I'm creating a file with this name **_acme-challenge.demo-application.com** in the public directory of my app with this value **1BzfdoJ1-Tr09SwFk46CDbvc_wqO9sKAairNo8zsNVo**

and when I run this command
```bash
acme.sh --renew -d '*.demo-application.com' --yes-I-know-dns-manual-mode-enough-go-ahead-please
```
I received this error
```
*.demo-application.com:Verify error:No TXT record found at _acme-challenge.demo-application.com
```
And if I re-run the command
```bash
acme.sh --renew --staging -d '*.demo-application.com' --yes-I-know-dns-manual-mode-enough-go-ahead-please
```
I received this output
```bash
*.demo-application.com:Challenge error: {"type":"urn:ietf:params:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}
```

**Comment by baoang** [comment]
my guess, if correct, is that the above codes should be put into, say for instance Cloudflare's DNS, such places.

![cloudflare txt input](https://img.overpic.net/images/m/n/9/xmn9h4llw8kxf7th1j3c.png)

**Comment by lesm** [comment]
Thaks @baoang
