### ISSUE TITLE
你好安装成功后为什么无法使用命令

### ISSUE THREAD

**Issue by hackedbyxx** [Neilpang/acme.sh#1453]
安装成功了
[root /]# wget -O -  https://get.acme.sh | sh
[Tue Mar 27 12:46:07 CST 2018] Installing from online archive.
[Tue Mar 27 12:46:07 CST 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz[Tue Mar 27 12:46:08 CST 2018] Extracting master.tar.gz[Tue Mar 27 12:46:08 CST 2018] Installing to /.acme.sh
[Tue Mar 27 12:46:08 CST 2018] Installed to /.acme.sh/acme.sh[Tue Mar 27 12:46:08 CST 2018] No profile is found, you will need to go into /.acme.sh to use acme.sh
[Tue Mar 27 12:46:08 CST 2018] Installing cron job
1 0 * * * "/.acme.sh"/acme.sh --cron --home "/.acme.sh" > /dev/null
[Tue Mar 27 12:46:08 CST 2018] Good, bash is found, so change the shebang to use bash as preferred.[Tue Mar 27 12:46:08 CST 2018] OK
[Tue Mar 27 12:46:08 CST 2018] Install success!

--2018-03-27 12:46:07--  https://get.acme.sh/
Resolving get.acme.sh... 130.211.247.207
Connecting to get.acme.sh|130.211.247.207|:443... connected.HTTP request sent, awaiting response... 200 OK
Length: 705 [text/plain]
Saving to: “STDOUT”

     0K                                                       100%  136M=0s

2018-03-27 12:46:07 (136 MB/s) - written to stdout [705/705]

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  163k  100  163k    0     0  1224k      0 --:--:-- --:--:-- --:--:-- 1231k

但是无法使用命令
[root /]# acme.sh  --issue .....   --debug 2
bash: line 1: acme.sh: command not found

**Comment by martgras** [comment]
This looks like #1234
Can you update to the latest dev version and try again
```
export BRANCH=dev
curl https://get.acme.sh  | sh
```

**Comment by hackedbyxx** [comment]
i'v done it,but it does't work
Duplicate of #

**Comment by Neilpang** [comment]
为啥不念一遍输出信息呢:
```
[Tue Mar 27 12:46:08 CST 2018] No profile is found, you will need to go into /.acme.sh to use acme.sh
```

或者你自己建一个 alias
```
alias  acme.sh=/.acme.sh/acme.sh
```

**Comment by hackedbyxx** [comment]
没看到但是试了一下还是没有用
[root /.acme.sh]# acme.sh  --issue  .....  --debug
bash: line 1: acme.sh: command not found
[root /]# alias  acme.sh=/.acme.sh/acme.sh

[root /]# acme.sh
bash: line 1: acme.sh: command not found

**Comment by martgras** [comment]
Does ```bash /.acme.sh/acme.sh``` work for you. 
Which platform  are you using

**Comment by hackedbyxx** [comment]
it does't work,i'm using centos 6.8

**Comment by martgras** [comment]
I can't tell what is going wrong here my linux skills are exhausted :) 
Actually I wonder how you  managed to install acme.sh at the root
usually it would be installed in /root/.acme.sh if you do the setup as root
