### ISSUE TITLE
With --debug enabled, help info from socat shows up.

### ISSUE THREAD

**Issue by jimdoe** [Neilpang/acme.sh#1455]
I have socat installed but not using standalone server

When --debug is enabled I always get the (long) help info from socat, so I have to scroll back. 

Looking into the code I found in function _dlg_versions:
  echo "socat:"
  if _exists "socat"; then
    socat -h 2>&1
  else
    _debug "socat doesn't exists."
  fi

Is this necessary ?

BTW: Thank you for this great script.

**Comment by baoang** [comment]
DNS auto mode perhaps is the most recommended solution.

**Comment by Neilpang** [comment]
it's just debug info.

**Comment by jimdoe** [comment]
I would recommend to change it 
from:
socat -h 2>&1
to:
socat -V | grep "socat version" 2>&1
