### ISSUE TITLE
Problem with --domain-alias and SAN domains

### ISSUE THREAD

**Issue by kirompower** [Neilpang/acme.sh#1458]
If I want to issue domain with subdomain using --domain-alias only one TXT record is created on target domain. Using powerdns-api

Steps to reproduce
------------------
acme.sh --issue -d domain1.com --domain-alias acme.domain2.com --dns dns_pdns --dnssleep 120 -d www.domain1.com

try and this without success
acme.sh --issue -d domain1.com --domain-alias acme.domain2.com --dns dns_pdns --dnssleep 120 -d www.domain1.com --domain-alias www.acme.domain2.com

Only one TXT record is created on acme.domain2.com and fail to issue. If I run command again its OK because of skip already validated domain.

**Comment by martgras** [comment]
The PR #1429 from @socat might fix this
