### ISSUE TITLE
!_checkcert: not found

### ISSUE THREAD

**Issue by dlangille** [Neilpang/acme.sh#1462]
I am using acme.sh 2.7.7 (upgraded from 2.7.6 at Mar 28 14:31:11) on FreeBSD 11.1

While running this from the crontab:

```
/usr/local/sbin/acme.sh --cron --home /var/db/acme/.acme.sh > /dev/null
```

I received this email:

```
/usr/local/sbin/acme.sh: !_checkcert: not found
/usr/local/sbin/acme.sh: !_checkcert: not found
````

NOTE: 2 certs were renewed during this run.

Checking, I find that function in the installed code:

```
$ grep _checkcert /usr/local/sbin/acme.sh 
_checkcert() {
  if [ -z "$Le_LinkCert" ] || ! _checkcert "$CERT_PATH"; then
            if !_checkcert "$CA_CERT_PATH"; then
```

I see no errors in the log.

**Comment by Neilpang** [comment]
@dlangille  
I'm Sorry, it was a known bug.  I just created a new release 2.7.8.  please upgrade. thanks.

**Comment by dlangille** [comment]
Very happy to hear this.

**Comment by Neilpang** [comment]
sorry about that.

**Comment by dlangille** [comment]
No worries at all.  Thank you.
