### ISSUE TITLE
SSL generation with additional altnames doesn't work if there's cert already exists

### ISSUE THREAD

**Issue by lucasRolff** [Neilpang/acme.sh#147]
Hi,

If you have an SSL certificate with the domain `example.com` and you want to issue a new SSL certificate containing `example.com` and `example.net` you'll get an error, since there's an already existing cert for `example.com`.

The issue should check if there's an existing certificate with every domain you specified.

**Comment by Neilpang** [comment]
I think  add  `--force` can override the default certs.
Can you please have a try ?

**Comment by lucasRolff** [comment]
It works if I use force - I don't know if it would be an option to add the list of signed domains to the config, and then when issuing a new certificate, to check if the list of domains you supply is the same as the already generated certificate

**Comment by Neilpang** [comment]
Yes,   it seems good. maybe add it later.

**Comment by unclespeedo** [comment]
This is something I am looking for as well, thank you.

**Comment by NielsH** [comment]
lt would be great if something like this could be implemented. We use Ansible to manage Lets Encrypt via acme.sh and it'd be great if the tool could automatically detect the change in the domains that have to be requested for a cert. `--force` does work of course but it requires a comparison against `Le_Alt` in the config file to see if I need to use `force`

**Comment by Neilpang** [comment]
fixed at  bb25febd70cc45e257b349495113c7f282ab8ea0

@lucasRolff  @NielsH @unclespeedo
