### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by hackdefendr** [Neilpang/acme.sh#1472]
```
[Fri Mar 30 19:34:11 CDT 2018] You didn't specify a cloudflare api key and email yet.
[Fri Mar 30 19:34:11 CDT 2018] Please create the key and try again.
[Fri Mar 30 19:34:11 CDT 2018] Error add txt for domain:_acme-challenge.hackdefendr.com
[Fri Mar 30 19:34:11 CDT 2018] Please add '--debug' or '--log' to check more details.
[Fri Mar 30 19:34:11 CDT 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

Steps to reproduce
------------------
Run this command:
```
acme.sh --issue -d hackdefendr.com -d '*.hackdefendr.com' --dns dns_cf
```

Debug log
-----------------
See at top, that is the only message.

**Comment by hackdefendr** [comment]
Thank-you.

**Comment by 70599** [comment]
I run:
```
export CF_KEY="sdfsdfsdfljlbjkljlkjsdfoiwje" && export CF_Email="xxxx@sss.com" && ~/.acme.sh/acme.sh --issue -d example.com -d *.example.com --dns dns_cf --log || echo -e "CF_KEY is $CF_KEY \nCF_Email is $CF_Email"
```

Got this result:
```
[2018年 08月 02日 星期四 01:03:31 JST] Multi domain='DNS:example.com,DNS:*.example.com'
[2018年 08月 02日 星期四 01:03:31 JST] Getting domain auth token for each domain
[2018年 08月 02日 星期四 01:03:33 JST] Getting webroot for domain='example.com'
[2018年 08月 02日 星期四 01:03:33 JST] Getting webroot for domain='*.example.com'
[2018年 08月 02日 星期四 01:03:33 JST] Found domain api file: /root/.acme.sh/dnsapi/dns_cf.sh
[2018年 08月 02日 星期四 01:03:33 JST] You didn't specify a cloudflare api key and email yet.
[2018年 08月 02日 星期四 01:03:33 JST] Please create the key and try again.
[2018年 08月 02日 星期四 01:03:33 JST] Error add txt for domain:_acme-challenge.text.cf
[2018年 08月 02日 星期四 01:03:33 JST] Please check log file for more details: /root/.acme.sh/acme.sh.log
CF_KEY is sdfsdfsdfljlbjkljlkjsdfoiwje
CF_Email is xxxx@sss.com
```

Can someone help me?

**Comment by SimonFearby** [comment]
me too

export CF_Key="####################################"
export CF_Email="#####@######.com"
sudo ./acme.sh --issue --dns dns_cf -d ######.com
[Mon Jun 17 16:46:16 AEST 2019] Single domain='######.com'
[Mon Jun 17 16:46:17 AEST 2019] Getting domain auth token for each domain
[Mon Jun 17 16:46:17 AEST 2019] Getting webroot for domain='######.com'
[Mon Jun 17 16:46:17 AEST 2019] Adding txt value: ################################# for domain:  _acme-challenge.#######.com
[Mon Jun 17 16:46:17 AEST 2019] You didn't specify a Cloudflare api key and email yet.
[Mon Jun 17 16:46:17 AEST 2019] You can get yours from here https://dash.cloudflare.com/profile.
[Mon Jun 17 16:46:17 AEST 2019] Error add txt for domain:_acme-challenge.######.com
[Mon Jun 17 16:46:17 AEST 2019] Please add '--debug' or '--log' to check more details.
[Mon Jun 17 16:46:17 AEST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by SimonFearby** [comment]
# echo $CF_Email
my@email.com
# echo CF_Key
##############################################

I even made persistent via ~/.pam_environment

**Comment by SimonFearby** [comment]
I added the following 3 lines to acme.sh below the VER VARIABLE (Line 3)
----------------------------------------------
CF_Key="#####################"
CF_Email="my@email.com"
CF_Api="https://api.cloudflare.com/client/v4"
----------------------------------------------
Found at https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_cf.sh

Now I get 

[Mon Jun 17 18:33:55 AEST 2019] Getting domain auth token for each domain
[Mon Jun 17 18:33:56 AEST 2019] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429

Rate limiting looks better than the error before
