### ISSUE TITLE
Custom script

### ISSUE THREAD

**Issue by umardraz** [Neilpang/acme.sh#1474]
Hello

Whenever a certificate is successfully renewed through acme.sh cron. I want to run one of my ansible playbook.

So would you please help me where I can trigger my ansible playbook in the cron

**Comment by Neilpang** [comment]
see `--renew-hook`  or `--reload-cmd`

https://github.com/Neilpang/acme.sh/wiki/Using-'--pre-hook',-'--post-hook',-'--renew-hook'-and-'--reload-cmd'
