### ISSUE TITLE
Supply multiple domains with multiple webroots breaks wellknown_path

### ISSUE THREAD

**Issue by lucasRolff** [Neilpang/acme.sh#148]
When issuing a certificate with multiple domains and multiple webroots:
`/root/.acme.sh/acme.sh --debug --test --issue -d secure.optimizer.io -w /home/lucasrol/public_html/secure -d slcoding.com -w /home/slcoding/public_html`

What happens is that the first certificate works fine - `wellknown_path` variable gets set to the correct value.
for 2nd and additional domains, it sets the _currentRoot correctly, but doesn't update the wellknown_path accordingly:
```
[Sat Apr 16 13:07:27 CEST 2016] _currentRoot='/home/slcoding/public_html'
[Sat Apr 16 13:07:27 CEST 2016] wellknown_path='/home/lucasrol/public_html/secure/.well-known/acme-challenge'
```

This causes validation to fail, because it will write the token to the wrong path.

**Comment by Neilpang** [comment]
fixed.  6f93064114195b82c83579e1b8597670f8379c51

Please try again.

**Comment by lucasRolff** [comment]
I can confirm it works perfectly now! Thanks!

**Comment by Neilpang** [comment]
Appreciate your help .

Thanks.
