### ISSUE TITLE
Le_OrderFinalize not found. 

### ISSUE THREAD

**Issue by xiagw** [Neilpang/acme.sh#1484]
$ ./acme.sh --version
https://github.com/Neilpang/acme.sh
v2.7.9

$ ./acme.sh --issue -d home160.com -d .home160.com --dns dns_ali --log --force
[Tue Apr 3 10:07:10 CST 2018] Multi domain='DNS:home160.com,DNS:.home160.com'
[Tue Apr 3 10:07:10 CST 2018] Getting domain auth token for each domain
[Tue Apr 3 10:07:12 CST 2018] Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:malformed","detail":"Malformed account ID in KeyID header","status": 400}
[Tue Apr 3 10:07:12 CST 2018] Please check log file for more details: /home/xia/.acme.sh/acme.sh.log

$ ./acme.sh --renew -d home160.com -d .home160.com --dns dns_ali --log --force
[Tue Apr 3 10:07:27 CST 2018] Renew: 'home160.com'
[Tue Apr 3 10:07:28 CST 2018] Multi domain='DNS:home160.com,DNS:.home160.com'
[Tue Apr 3 10:07:29 CST 2018] Getting domain auth token for each domain
[Tue Apr 3 10:07:30 CST 2018] Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:malformed","detail":"Malformed account ID in KeyID header","status": 400}
[Tue Apr 3 10:07:30 CST 2018] Please check log file for more details: /home/xia/.acme.sh/acme.sh.log

**Comment by xiagw** [comment]
OpenSSL> version
OpenSSL 1.0.2k-fips 26 Jan 2017

**Comment by xiagw** [comment]
[Tue Apr 3 10:07:09 CST 2018] _main_domain='home160.com'
[Tue Apr 3 10:07:09 CST 2018] _alt_domains='.home160.com'
[Tue Apr 3 10:07:09 CST 2018] Using config home:/home/xia/.acme.sh
[Tue Apr 3 10:07:09 CST 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Apr 3 10:07:09 CST 2018] DOMAIN_PATH='/home/xia/.acme.sh/home160.com'
[Tue Apr 3 10:07:09 CST 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Tue Apr 3 10:07:09 CST 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Tue Apr 3 10:07:09 CST 2018] GET
[Tue Apr 3 10:07:09 CST 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Apr 3 10:07:09 CST 2018] timeout=
[Tue Apr 3 10:07:09 CST 2018] _CURL='curl -L --silent --dump-header /home/xia/.acme.sh/http.header -g '
[Tue Apr 3 10:07:10 CST 2018] ret='0'
[Tue Apr 3 10:07:10 CST 2018] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Tue Apr 3 10:07:10 CST 2018] ACME_NEW_AUTHZ
[Tue Apr 3 10:07:10 CST 2018] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Apr 3 10:07:10 CST 2018] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Tue Apr 3 10:07:10 CST 2018] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Tue Apr 3 10:07:10 CST 2018] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Tue Apr 3 10:07:10 CST 2018] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Apr 3 10:07:10 CST 2018] ACME_VERSION='2'
[Tue Apr 3 10:07:10 CST 2018] Le_NextRenewTime
[Tue Apr 3 10:07:10 CST 2018] _on_before_issue
[Tue Apr 3 10:07:10 CST 2018] _chk_main_domain='home160.com'
[Tue Apr 3 10:07:10 CST 2018] _chk_alt_domains='.home160.com'
[Tue Apr 3 10:07:10 CST 2018] Le_LocalAddress
[Tue Apr 3 10:07:10 CST 2018] d='home160.com'
[Tue Apr 3 10:07:10 CST 2018] Check for domain='home160.com'
[Tue Apr 3 10:07:10 CST 2018] _currentRoot='dns_ali'
[Tue Apr 3 10:07:10 CST 2018] d='.home160.com'
[Tue Apr 3 10:07:10 CST 2018] Check for domain='.home160.com'
[Tue Apr 3 10:07:10 CST 2018] _currentRoot='dns_ali'
[Tue Apr 3 10:07:10 CST 2018] d
[Tue Apr 3 10:07:10 CST 2018] _saved_account_key_hash is not changed, skip register account.
[Tue Apr 3 10:07:10 CST 2018] Read key length:
[Tue Apr 3 10:07:10 CST 2018] _createcsr
[Tue Apr 3 10:07:10 CST 2018] Multi domain='DNS:home160.com,DNS:.home160.com'
[Tue Apr 3 10:07:10 CST 2018] Getting domain auth token for each domain
[Tue Apr 3 10:07:10 CST 2018] d='.home160.com'
[Tue Apr 3 10:07:10 CST 2018] d
[Tue Apr 3 10:07:10 CST 2018] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Apr 3 10:07:10 CST 2018] payload='{"identifiers": [{"type":"dns","value":"home160.com"},{"type":"dns","value":".home160.com"}]}'
[Tue Apr 3 10:07:10 CST 2018] RSA key
[Tue Apr 3 10:07:11 CST 2018] HEAD
[Tue Apr 3 10:07:11 CST 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Apr 3 10:07:11 CST 2018] _CURL='curl -L --silent --dump-header /home/xia/.acme.sh/http.header -g '
[Tue Apr 3 10:07:11 CST 2018] _ret='0'
[Tue Apr 3 10:07:11 CST 2018] POST
[Tue Apr 3 10:07:11 CST 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Apr 3 10:07:11 CST 2018] _CURL='curl -L --silent --dump-header /home/xia/.acme.sh/http.header -g '
[Tue Apr 3 10:07:12 CST 2018] _ret='0'
[Tue Apr 3 10:07:12 CST 2018] code='400'
[Tue Apr 3 10:07:12 CST 2018] Le_OrderFinalize
[Tue Apr 3 10:07:12 CST 2018] Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:malformed","detail":"Malformed account ID in KeyID header","status": 400}
[Tue Apr 3 10:07:12 CST 2018] pid
[Tue Apr 3 10:07:12 CST 2018] No need to restore nginx, skip.
[Tue Apr 3 10:07:12 CST 2018] _clearupdns
[Tue Apr 3 10:07:12 CST 2018] skip dns.
[Tue Apr 3 10:07:12 CST 2018] _on_issue_err
[Tue Apr 3 10:07:12 CST 2018] Please check log file for more details: /home/xia/.acme.sh/acme.sh.log
[Tue Apr 3 10:07:27 CST 2018] Using config home:/home/xia/.acme.sh
[Tue Apr 3 10:07:27 CST 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Apr 3 10:07:27 CST 2018] DOMAIN_PATH='/home/xia/.acme.sh/home160.com'
[Tue Apr 3 10:07:27 CST 2018] ESC[1;31;32mRenew: 'home160.com'ESC[0m
[Tue Apr 3 10:07:27 CST 2018] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Tue Apr 3 10:07:27 CST 2018] Using config home:/home/xia/.acme.sh
[Tue Apr 3 10:07:27 CST 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Apr 3 10:07:27 CST 2018] _main_domain='home160.com'
[Tue Apr 3 10:07:27 CST 2018] _alt_domains='.home160.com'
[Tue Apr 3 10:07:27 CST 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Tue Apr 3 10:07:27 CST 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Tue Apr 3 10:07:27 CST 2018] GET
[Tue Apr 3 10:07:27 CST 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Apr 3 10:07:27 CST 2018] timeout=
[Tue Apr 3 10:07:28 CST 2018] _CURL='curl -L --silent --dump-header /home/xia/.acme.sh/http.header -g '
[Tue Apr 3 10:07:28 CST 2018] ret='0'
[Tue Apr 3 10:07:28 CST 2018] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Tue Apr 3 10:07:28 CST 2018] ACME_NEW_AUTHZ
[Tue Apr 3 10:07:28 CST 2018] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Apr 3 10:07:28 CST 2018] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Tue Apr 3 10:07:28 CST 2018] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Tue Apr 3 10:07:28 CST 2018] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Tue Apr 3 10:07:28 CST 2018] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Apr 3 10:07:28 CST 2018] ACME_VERSION='2'
[Tue Apr 3 10:07:28 CST 2018] Le_NextRenewTime
[Tue Apr 3 10:07:28 CST 2018] _on_before_issue
[Tue Apr 3 10:07:28 CST 2018] _chk_main_domain='home160.com'
[Tue Apr 3 10:07:28 CST 2018] _chk_alt_domains='.home160.com'
[Tue Apr 3 10:07:28 CST 2018] Le_LocalAddress
[Tue Apr 3 10:07:28 CST 2018] d='home160.com'
[Tue Apr 3 10:07:28 CST 2018] Check for domain='home160.com'
[Tue Apr 3 10:07:28 CST 2018] _currentRoot='dns_ali'
[Tue Apr 3 10:07:28 CST 2018] d='.home160.com'
[Tue Apr 3 10:07:28 CST 2018] Check for domain='.home160.com'
[Tue Apr 3 10:07:28 CST 2018] _currentRoot='dns_ali'
[Tue Apr 3 10:07:28 CST 2018] d
[Tue Apr 3 10:07:28 CST 2018] _saved_account_key_hash is not changed, skip register account.
[Tue Apr 3 10:07:28 CST 2018] Read key length:
[Tue Apr 3 10:07:28 CST 2018] _createcsr
[Tue Apr 3 10:07:28 CST 2018] Multi domain='DNS:home160.com,DNS:.home160.com'
[Tue Apr 3 10:07:29 CST 2018] Getting domain auth token for each domain
[Tue Apr 3 10:07:29 CST 2018] d='.home160.com'
[Tue Apr 3 10:07:29 CST 2018] d
[Tue Apr 3 10:07:29 CST 2018] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Apr 3 10:07:29 CST 2018] payload='{"identifiers": [{"type":"dns","value":"home160.com"},{"type":"dns","value":".home160.com"}]}'
[Tue Apr 3 10:07:29 CST 2018] RSA key
[Tue Apr 3 10:07:29 CST 2018] HEAD
[Tue Apr 3 10:07:29 CST 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Apr 3 10:07:29 CST 2018] _CURL='curl -L --silent --dump-header /home/xia/.acme.sh/http.header -g '
[Tue Apr 3 10:07:29 CST 2018] _ret='0'
[Tue Apr 3 10:07:29 CST 2018] POST
[Tue Apr 3 10:07:29 CST 2018] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Apr 3 10:07:29 CST 2018] _CURL='curl -L --silent --dump-header /home/xia/.acme.sh/http.header -g '
[Tue Apr 3 10:07:30 CST 2018] _ret='0'
[Tue Apr 3 10:07:30 CST 2018] code='400'
[Tue Apr 3 10:07:30 CST 2018] Le_OrderFinalize
[Tue Apr 3 10:07:30 CST 2018] Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:malformed","detail":"Malformed account ID in KeyID header","status": 400}
[Tue Apr 3 10:07:30 CST 2018] pid

**Comment by Neilpang** [comment]
先把这个文件给我看一下:

```sh
cat    ~/.acme.sh/ca/acme-v02.api.letsencrypt.org/ca.conf
```
然后再把它删掉, 再试就好了.

```sh
rm   -f   ~/.acme.sh/ca/acme-v02.api.letsencrypt.org/ca.conf
```


还有, 同一个帖子不用发两份, 多发只会增加我的负担, 并不会帮助问题快速解决.

**Comment by xiagw** [comment]
显示的是 另一个 xxx.com 域名，因为我之前先注册过另一个域名（同一个.acme.sh）
不是home这个域名
删掉后再重新执行就好了。
