### ISSUE TITLE
求助，报错Can not init api

### ISSUE THREAD

**Issue by hjl19911127** [Neilpang/acme.sh#1486]
如图所示，为啥报Can not init api.，求助一下
![image](https://user-images.githubusercontent.com/9312114/38304787-2ad1d2fe-383d-11e8-8b7f-245920ecaa5c.png)

**Comment by hjl19911127** [comment]
卡住了

**Comment by Neilpang** [comment]
国内的垃圾主机都是这样,  多试几次.
