### ISSUE TITLE
Hook after every cron run

### ISSUE THREAD

**Issue by wizonesolutions** [Neilpang/acme.sh#1487]
We want to send a ping to Dead Man's Snitch every day when the `--cron` runs just to make sure that the script is alive. It seems like `--pre-hook` and `--post-hook` only work if a renewal will be attempted. What is the best way to have something run every time?

**Comment by FernandoMiguel** [comment]
daily is a bit excessive and might make you hit api limits

**Comment by wizonesolutions** [comment]
I don't want to renew every day. I just want to take an action after cron
has run. Conceptually, a post-cron hook.

Maybe we can just grep the log or something though in a separate cron job.

**Comment by FernandoMiguel** [comment]
i guess you can fire another sh inline with the cron

**Comment by FernandoMiguel** [comment]
15 3 * * * acme.sh --cron && alert.sh

**Comment by wizonesolutions** [comment]
Well, acme.sh sets up the cron though...

**Comment by FernandoMiguel** [comment]
on install

**Comment by wizonesolutions** [comment]
Is it possible to specify a custom cron command, though? Though I guess I
could have my own anyway since it will always skip not ready certificates.

**Comment by FernandoMiguel** [comment]
what do you mean?
acme.sh installs a cron.... it becomes a system or user cron
it doesnt change it ever again.

you can change it, update it, delete it.... it's on your system

**Comment by wizonesolutions** [comment]
I manage it with Ansible, but that is a good idea. I should be able to
figure something out. Thanks!

**Comment by wizonesolutions** [comment]
Ah. `--install` has `--nocron`. I could pass that and then set up my own cron. Going to try that.

**Comment by wizonesolutions** [comment]
That worked out.

**Comment by FernandoMiguel** [comment]
great to hear
