### ISSUE TITLE
 --dns dns-cf 错误

### ISSUE THREAD

**Issue by HuanMeng0** [Neilpang/acme.sh#149]
sh acme.sh--issue  -d n.huanmeng.party --dns dns-cf -d s01.n.huanmeng.party -d up.n.huanmeng.party -d l0.n.huanmeng.party
执行错误：
[Sat Apr 16 12:20:40 UTC 2016] Skip register account key
[Sat Apr 16 12:20:40 UTC 2016] Creating csr
[Sat Apr 16 12:20:40 UTC 2016] Multi domain='DNS:s01.n.huanmeng.party,DNS:up.n.huanmeng.party,DNS:l0.n.huanmeng.party'
[Sat Apr 16 12:20:40 UTC 2016] Verify each domain
[Sat Apr 16 12:20:40 UTC 2016] Getting webroot for domain='n.huanmeng.party'
[Sat Apr 16 12:20:40 UTC 2016] Getting token for domain='n.huanmeng.party'
[Sat Apr 16 12:20:42 UTC 2016] Getting webroot for domain='s01.n.huanmeng.party'
[Sat Apr 16 12:20:42 UTC 2016] Getting token for domain='s01.n.huanmeng.party'
[Sat Apr 16 12:20:44 UTC 2016] Getting webroot for domain='up.n.huanmeng.party'
[Sat Apr 16 12:20:44 UTC 2016] Getting token for domain='up.n.huanmeng.party'
[Sat Apr 16 12:20:45 UTC 2016] Getting webroot for domain='l0.n.huanmeng.party'
[Sat Apr 16 12:20:46 UTC 2016] Getting token for domain='l0.n.huanmeng.party'
[Sat Apr 16 12:20:47 UTC 2016] Found domain api file: /root/.acme.sh/dnsapi/dns-cf.sh
/root/.acme.sh/dnsapi/dns-cf.sh: line 78: `dns-cf-add': not a valid identifier

**Comment by Neilpang** [comment]
你是什么系统?

**Comment by HuanMeng0** [comment]
CentOS6.7 Final

**Comment by Neilpang** [comment]
加上 `--debug` 试试

**Comment by HuanMeng0** [comment]
[Sat Apr 16 12:45:51 UTC 2016] /root/.acme.sh/n.huanmeng.party/n.huanmeng.party.conf:1:Le_Domain=n.huanmeng.party
[Sat Apr 16 12:45:51 UTC 2016] /root/.acme.sh/n.huanmeng.party/n.huanmeng.party.conf:2:Le_Alt=no
[Sat Apr 16 12:45:51 UTC 2016] /root/.acme.sh/n.huanmeng.party/n.huanmeng.party.conf:3:Le_Webroot=dns-cf
[Sat Apr 16 12:45:51 UTC 2016] /root/.acme.sh/n.huanmeng.party/n.huanmeng.party.conf:4:Le_Keylength=no
[Sat Apr 16 12:45:51 UTC 2016] /root/.acme.sh/n.huanmeng.party/n.huanmeng.party.conf:5:Le_RealCertPath="no"
[Sat Apr 16 12:45:51 UTC 2016] /root/.acme.sh/n.huanmeng.party/n.huanmeng.party.conf:6:Le_RealCACertPath="no"
[Sat Apr 16 12:45:51 UTC 2016] /root/.acme.sh/n.huanmeng.party/n.huanmeng.party.conf:7:Le_RealKeyPath="no"
[Sat Apr 16 12:45:51 UTC 2016] /root/.acme.sh/n.huanmeng.party/n.huanmeng.party.conf:8:Le_ReloadCmd="no"
[Sat Apr 16 12:45:51 UTC 2016] /root/.acme.sh/n.huanmeng.party/n.huanmeng.party.conf:9:Le_RealFullChainPath="no"
[Sat Apr 16 12:45:51 UTC 2016] RSA key
[Sat Apr 16 12:45:52 UTC 2016] Skip register account key
[Sat Apr 16 12:45:52 UTC 2016] Creating csr
[Sat Apr 16 12:45:52 UTC 2016] Single domain='n.huanmeng.party'
[Sat Apr 16 12:45:52 UTC 2016] Verify each domain
[Sat Apr 16 12:45:52 UTC 2016] Getting webroot for domain='n.huanmeng.party'
[Sat Apr 16 12:45:52 UTC 2016] _w='dns-cf'
[Sat Apr 16 12:45:52 UTC 2016] _currentRoot='dns-cf'
[Sat Apr 16 12:45:52 UTC 2016] Getting token for domain='n.huanmeng.party'
[Sat Apr 16 12:45:52 UTC 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Sat Apr 16 12:45:52 UTC 2016] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "n.huanmeng.party"}}'
[Sat Apr 16 12:45:52 UTC 2016] RSA key
[Sat Apr 16 12:45:53 UTC 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Sat Apr 16 12:45:53 UTC 2016] nonce='RvcaAZzdGQKuYmIh9IEl_6vM-WEHp-jESvgp8aL9OBA'
[Sat Apr 16 12:45:54 UTC 2016] code='201'
[Sat Apr 16 12:45:54 UTC 2016] entry='{"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/ekTDCpdUwuTB                              i1W_AsL-ZDx6KneQzXme2J_Rl2F81SU/51488295","token":"8K0Dt--bu-PCYlYKnhrIgKV9ki1U0zWVgzvXxiE-oXY"'
[Sat Apr 16 12:45:54 UTC 2016] token='8K0Dt--bu-PCYlYKnhrIgKV9ki1U0zWVgzvXxiE-oXY'
[Sat Apr 16 12:45:54 UTC 2016] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/ekTDCpdUwuTBi1W_AsL-ZDx6KneQzXme2J_Rl2F81SU/51488295'
[Sat Apr 16 12:45:54 UTC 2016] keyauthorization='8K0Dt--bu-PCYlYKnhrIgKV9ki1U0zWVgzvXxiE-oXY.hNRQfyPc4Ew9wOQ79AxvuPEanFwoMs2nmUt1L-azZm4'
[Sat Apr 16 12:45:54 UTC 2016] dvlist='n.huanmeng.party#8K0Dt--bu-PCYlYKnhrIgKV9ki1U0zWVgzvXxiE-oXY.hNRQfyPc4Ew9wOQ79AxvuPEanFwoMs2nmUt1L-azZm4#h                              ttps://acme-v01.api.letsencrypt.org/acme/challenge/ekTDCpdUwuTBi1W_AsL-ZDx6KneQzXme2J_Rl2F81SU/51488295#dns-01#dns-cf'
[Sat Apr 16 12:45:54 UTC 2016] txtdomain='_acme-challenge.n.huanmeng.party'
[Sat Apr 16 12:45:54 UTC 2016] txt='abuR0gawaBUGN-YtpUrcWOMfZdLvBs7G-5BfaIwihk0'
[Sat Apr 16 12:45:54 UTC 2016] d_api='/root/.acme.sh/dnsapi/dns-cf.sh'
[Sat Apr 16 12:45:54 UTC 2016] Found domain api file: /root/.acme.sh/dnsapi/dns-cf.sh
/root/.acme.sh/dnsapi/dns-cf.sh: line 78: `dns-cf-add': not a valid identifier
[Sat Apr 16 12:45:54 UTC 2016] pid

**Comment by HuanMeng0** [comment]
问题解决，应该用acme.sh 而不是 sh acme.sh

**Comment by Neilpang** [comment]
@heldchen 

如果方便的话, 你再试试 `sh` 的版本,   现在应该可以了.

**Comment by heldchen** [comment]
from what i can gather from google translate, you probably meant to notify @HuanMeng0 :)

**Comment by Neilpang** [comment]
@heldchen 

Yes and sorry.
