### ISSUE TITLE
Combine wildcard with Le_Alt?

### ISSUE THREAD

**Issue by litemotiv** [Neilpang/acme.sh#1502]
I was just wondering if it's possible to combine wildcard domains with Alt domains in one conf file? I currently have a few sites with multiple Alt domains that originate from different DNS providers, testing them with the http-method works fine. How would this work using the dns-method for the wildcard domain? Hypothethical situation:

```
Le_Domain='*.foo.net' // dns provider #1
Le_Alt='bar.net' // dns provider #2
```

**Comment by FernandoMiguel** [comment]
i dont think that currently acme.sh supports that.
i've seen a similar ticket

**Comment by Neilpang** [comment]
Yes,
you can specify different dns provider for each domain:
https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert#3-multiple-domains-san-mode--hybrid-mode

**Comment by litemotiv** [comment]
Works like a charm Neilpang, thanks and apologies for not reading the wiki better.
