### ISSUE TITLE
Problem with solusvm

### ISSUE THREAD

**Issue by jimmy-rich** [Neilpang/acme.sh#1507]
Hello,

I have a problem with solusvm install

Doc: https://github.com/Neilpang/acme.sh/wiki/Deploy-ssl-to-SolusVM

1 Worked:  sh acme.sh --issue -d vps.mydomaine.com \ -w /usr/local/solusvm/www/.verification 

2 Error: sh acme.sh --installcert -d vps.mydomaine.com \ --keypath /usr/local/svmstack/nginx/ssl/ssl.key \
--fullchainpath /usr/local/svmstack/nginx/ssl/ssl.crt \
--reloadcmd "service svmstack-nginx restart; \
/usr/local/svmstack/sshwebsocket/quit; \
/usr/local/svmstack/sshwebsocket/port_check; \
cd /usr/local/svmstack/nginx/ssl && cat ssl.key ssl.crt > ssl.pem"

Error: [mar. avril 10 14:59:26 CEST 2018] Unknown parameter :  --keypath

Thanks you !

**Comment by jimmy-rich** [comment]
Solved.

**Comment by FernandoMiguel** [comment]
what was the issue?

**Comment by jimmy-rich** [comment]
http://centosquestions.com/setup-solusvm-with-lets-encrypt-free-ssl-certificate/
