### ISSUE TITLE
Verify error:DNS problem: query timed out looking up A for ...

### ISSUE THREAD

**Issue by zwl1619** [Neilpang/acme.sh#151]
I am using `cloudxns`  as DNS,the issue is as follow: 
```
[root@i001 ~]# acme.sh --issue -d www.aa.com -w /var/www/www.aa.com
[Sat Apr 16 21:08:04 CST 2016] Creating account key
[Sat Apr 16 21:08:04 CST 2016] Use default length 2048
[Sat Apr 16 21:08:04 CST 2016] Registering account
[Sat Apr 16 21:08:10 CST 2016] Registered
[Sat Apr 16 21:08:10 CST 2016] Creating domain key
[Sat Apr 16 21:08:10 CST 2016] Use length 2048
[Sat Apr 16 21:08:11 CST 2016] Creating csr
[Sat Apr 16 21:08:11 CST 2016] Single domain='www.aa.com'
[Sat Apr 16 21:08:11 CST 2016] Verify each domain
[Sat Apr 16 21:08:11 CST 2016] Getting webroot for domain='www.aa.com'
[Sat Apr 16 21:08:11 CST 2016] Getting token for domain='www.aa.com'
[Sat Apr 16 21:08:14 CST 2016] Verifying:www.aa.com
[Sat Apr 16 21:08:27 CST 2016] Pending
[Sat Apr 16 21:08:33 CST 2016] Pending
[Sat Apr 16 21:08:39 CST 2016] Pending
[Sat Apr 16 21:08:46 CST 2016] Pending
[Sat Apr 16 21:08:52 CST 2016] www.aa.com:Verify error:DNS problem: query timed out looking up A for www.aa.com
```

**Comment by Neilpang** [comment]
I suggest  you use cloudxns api.

https://github.com/Neilpang/acme.sh/tree/master/dnsapi

**Comment by zwl1619** [comment]
@Neilpang     
l find the reason, 
I can access my domain name on local windows via VPN,
and if I close VPN,it's unaccessible,
and my aliyun server doesn't have VPN,
Are there other ways to settle the issue except VPN?

**Comment by Neilpang** [comment]
因为你的域名解析没有生效, 所以, letsencrypt 的服务器无法解析.  有可能是 8.8.8.8  无法解析国内的nameserver.

这个我们没有任何办法.

**Comment by zwl1619** [comment]
是这样，应该cloudxns的DNS生效了的：   

先用阿里云也就是万网的dns，不翻墙，可以访问，但听说国外支持不好，所以换成cloudxns的DNS，刚开始无论如何都不能访问，我也认为没有生效，等过了48小时仍然不能访问，可是就在刚才，偶然在打开vpn的情况下访问，居然是能访问的，然后再关掉和打开vpn分别测试，确实是这样，那么，这种情况有什么办法么？

**Comment by Neilpang** [comment]
@zwl1619 
结果怎么样？   这两天忙着做sh 没时间回复。

请更新到最新的代码。

如果是本地windows (cygwin)， 关掉windows防火墙试试。

测试服务器的连通性：
···
echo "hello world"  | nc -l 80
···
或者：
···
echo "hello world"  | nc -l  -p 80
···

然后用浏览器访问：  http://www.aa.com

**Comment by zwl1619** [comment]
@Neilpang
域名解析我换回了阿里云，cloudxns不好用，访问不了。接着，根据这篇讨论，https://community.letsencrypt.org/t/invalid-response-for-acme-challenge/12529/2   
有个名字叫kelunik的哥们说不要重定向，所以我把nginx配置文件中的
```
#location ^~ /.well-known/acme-challenge/ {
         #   alias /var/www/challenges/;
         #   try_files $uri =404;
        #}
```
注释掉了，然后就成功了！！      
      
然后有2个问题咨询一下楼主：      
1、在/root/.acme.sh/www.aa.com文件夹中，`acme.sh`生成了5个证书和key的相关文件，如下：
```
ca.cer
fullchain.cer
www.aa.com.cer
www.aa.com.csr
www.aa.com.key
```
根据这篇文章https://imququ.com/post/my-nginx-conf.html，有6项是与证书、key相关的内容，摘录如下：
```
ssl_ct_static_scts              /home/jerry/www/scts;
ssl_certificate                    /home/jerry/www/ssl/chained.pem;
ssl_certificate_key             /home/jerry/www/ssl/domain.key;
ssl_dhparam                       /home/jerry/www/ssl/dhparams.pem;
ssl_session_ticket_key      /home/jerry/www/ssl/session_ticket.key;
ssl_trusted_certificate        /home/jerry/www/ssl/full_chained.pem;
```
**问题：**
两部分内容对比，貌似都对不上，应该怎么填写呢？
   
2、这篇文章https://imququ.com/post/letsencrypt-certificate.html 中说，`~/www/challenges/`文件夹用于存放验证文件，“这个验证服务以后更新证书还要用到，建议一直保留”，那么，现在我把它注释掉了，没有这个文件夹，这个验证文件放到什么地方的呢？

**Comment by Neilpang** [comment]
首先, 
```
#location ^~ /.well-known/acme-challenge/ {
#   alias /var/www/challenges/;
#   try_files $uri =404;
#}
```

这一段本来就不是必须的.  但是因为有的nginx 服务器默认配置只显示白名单的后缀名文件,  而 acme 要求的验证文件名根本就没有后缀, 所有就被禁止访问了.
加上这一段的目的就是要开放访问.  所以如果不加以可以那就不加了.



>> 1、这篇文章https://imququ.com/post/letsencrypt-certificate.html 中说，~/www/challenges/文件夹用>> 于存放验证文件，“这个验证服务以后更新证书还要用到，建议一直保留”，那么，在上面，我把重定>> 向注释掉了，没有使用challenges这个文件夹了，这个验证文件放到什么地方的呢？

  既然你成功了, 就不要在意这个文件夹.   acme 会自动handle所有的case.  它会在需要验证的时候, 自动在 网站根目录下创建:
```
 /var/www/.well-known/acme-challenge/
```
用完之后立即自动删除, 不留痕迹.



2.  如果是nginx 服务器 请使用下面三个文件:
```

www.aa.com.cer
www.aa.com.key
fullchain.cer
```
对应这三个:

```
ssl_certificate                    /home/jerry/www/ssl/chained.pem;
ssl_certificate_key             /home/jerry/www/ssl/domain.key;
ssl_trusted_certificate        /home/jerry/www/ssl/full_chained.pem;
```

其他的不管.
