### ISSUE TITLE
Need help on dns

### ISSUE THREAD

**Issue by umardraz** [Neilpang/acme.sh#1512]
Hello I am trying to request certificate with dns method and getting this error

> [Fri Apr 13 04:57:29 UTC 2018] Add txt record error.
> [Fri Apr 13 04:57:29 UTC 2018] null
> [Fri Apr 13 04:57:29 UTC 2018] Error add txt for domain:_acme-challenge.umardraz.com
> [Fri Apr 13 04:57:29 UTC 2018] Please add '--debug' or '--log' to check more details.
> [Fri Apr 13 04:57:29 UTC 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
> 

If I check my godaddy dns there is a TXT entry is created, don't know why aceme.sh is giving null error. Would you please help me how to resolve this issue.

**Comment by martgras** [comment]
Did you follow the steps for godaddy from https://github.com/Neilpang/acme.sh/blob/master/dnsapi/README.md?https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

If it continues to fail use -debug 2 and may check the instructions from https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by ferranbonas** [comment]
Same problem here.
The TXT record is added correctly, but acme.sh response is:
[Fri Apr 13 12:14:05 CEST 2018] Add txt record error.
[Fri Apr 13 12:14:05 CEST 2018] null
[Fri Apr 13 12:14:05 CEST 2018] Error add txt for domain:_acme-challenge.uc.ltmcdn.com
[Fri Apr 13 12:14:05 CEST 2018] pid
[Fri Apr 13 12:14:05 CEST 2018] _clearupdns
[Fri Apr 13 12:14:05 CEST 2018] Dns not added, skip.
[Fri Apr 13 12:14:05 CEST 2018] _on_issue_err

**Comment by umardraz** [comment]
Absolutely correct, There is something going wrong either with Godaddy or acme.sh

**Comment by Neilpang** [comment]
godaddy changed its api.
fixed, please try with the latest code.

**Comment by mloweris** [comment]
If you had a failure using version that had busted Godaddy API interaction (as I had a few) you will continue to get failures, until you go to godaddy and delete the txt record for the cert you were trying to create.  
It should work after that.
