### ISSUE TITLE
貌似shell语法有兼容性问题

### ISSUE THREAD

**Issue by goxofy** [Neilpang/acme.sh#152]
我用/bin/bash运行脚本正常，但是用/bin/sh运行脚本报错。

/root/acme.sh/acme.sh: 26: /root/acme.sh/acme.sh: [[: not found
/root/acme.sh/acme.sh: 2264: /root/acme.sh/acme.sh: [[: not found
/root/acme.sh/acme.sh: 2270: /root/acme.sh/acme.sh: [[: not found

**Comment by Neilpang** [comment]
sorry,  reverted ,  please try again.

**Comment by goxofy** [comment]
OK!
