### ISSUE TITLE
如何在现有证书的基础上增加新的域名？

### ISSUE THREAD

**Issue by AZmake** [Neilpang/acme.sh#1521]
我为2个域名成功申请了SSL证书
服务器A：
`abc.com`
`www.abc.com`

服务器B：
`a1.abc.com`

因为我希望不同的域名指向不同的服务器，不同的服务器有不同的SSL证书，所以没有使用通配符，

现在服务器A下新增一个域名`a2.abc.com`,我希望`a2.abc.com`同样支持SSL
服务器A：
`abc.com`
`www.abc.com`
`a2.abc.com`

问题：我如何新增域名？需要删除现有证书，然后重新申请？

**Comment by junmaqiang** [comment]
肯定是删除之前的,再重新申请

**Comment by AZmake** [comment]
解决问题思路肯定是这样。但是如果这个数量比较大的话那我不得写脚本自动化？有没有在同一台web服务器下自动扩展SSL证书的域名的更能？

**Comment by Neilpang** [comment]
具体要看你的认证方式.

当然, 最简单的就是删了重新申请.

如果你的域名很多的话,  acme.sh  支持逗号分隔的模式.

```sh
acme.sh  --issue  -d   a.com,b.com,c.com,d.com
```
这与写4个 `-d` 参数事等效了.

逗号分隔的模式可以大幅降低你自动化脚本的难度.
