### ISSUE TITLE
CWP7 AutoSSL .acme.sh

### ISSUE THREAD

**Issue by Snorlak** [Neilpang/acme.sh#1525]
Hello,

Upon installing CWP7 and running AutoSSL I receive the following error.

AutoSSL installation failed!
[Mon Apr 16 07:11:38 EDT 2018] Installing from online archive.
[Mon Apr 16 07:11:38 EDT 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz

AutoSSL Issue Failed!sh: /root/.acme.sh/acme.sh: No such file or directory
[Mon Apr 16 07:11:40 EDT 2018] Installing from online archive.
[Mon Apr 16 07:11:40 EDT 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz

AutoSSL Issue Failed!sh: /root/.acme.sh/acme.sh: No such file or directory

https://i.imgur.com/UcaQjis.png

Furthermore upon trying to install .acme.sh

[root@server ~]# cd acme.sh
-bash: cd: acme.sh: No such file or directory
[root@server ~]# curl https://get.acme.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705  100   705    0     0    758      0 --:--:-- --:--:-- --:--:--   758
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  163k  100  163k    0     0   285k      0 --:--:-- --:--:-- --:--:--  286k
[Mon Apr 16 07:15:36 EDT 2018] Installing from online archive.
[Mon Apr 16 07:15:36 EDT 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Mon Apr 16 07:15:37 EDT 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Mon Apr 16 07:15:37 EDT 2018] Download error.

CURLE_SSL_CONNECT_ERROR (35)
A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others.

Any ideas would be greatly appreciated :)
Cheers.

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/issues/1439

**Comment by Snorlak** [comment]
Thank you.
I found that last night fixed the issue.
