### ISSUE TITLE
What is eligible to backup to ensure crash recovering when having a lot of cert ?

### ISSUE THREAD

**Issue by tristanbes** [Neilpang/acme.sh#1526]
Hello,

Considering we're going to use this tool to generate a lot of certificates (1000+), i'm wondering:

What files are eligible to backup ? 
  - Is backuping the `certhome` directory enough to restore from a full failure machine crash (to continue renew certificates using acme.sh after a recovery ?)
  - Can we use the certificates stored under `certhome` to redeploy them to the webserver in case of the webserver crashes and all the installed certificates are lost ? Or the installed certificates (let's say on nginx) should/must be backup too ?

Thanks.

**Comment by Neilpang** [comment]
>> Is backuping the certhome directory enough to restore from 
`certhome` only contains your certs/keys files.  you should backup the `config-home`,  which contains not only the `certhome`, but also the account configs: account key and others.

**Comment by Neilpang** [comment]
see also:  https://github.com/Neilpang/acme.sh/wiki/How-to-install#4-advanced-installation

**Comment by tristanbes** [comment]
So backuping `config-home` and `certhome` is enough to restore, redeploy & renew certificates ?

Thanks @Neilpang

**Comment by tristanbes** [comment]
(I customized it, so in my case it's not.)

Thanks !
