### ISSUE TITLE
Unknown parameter : --renew-hook="myscript.sh"

### ISSUE THREAD

**Issue by alexandre1985** [Neilpang/acme.sh#1533]
I'm trying to run this command:
`acme.sh --issue -d minho.win -d '*.minho.win' --dns dns_dynu --renew-hook="/usr/local/bin/hitch-renew-hook" --post-hook="service hitch reload"`
but I get this error:

> Unknown parameter : --renew-hook=/usr/local/bin/hitch-renew-hook

**Comment by alexandre1985** [comment]
solved

**Comment by Karthickarumugam** [comment]
How it was solved? I am trying same, but i am not sure whether it will work or not during renewal.
