### ISSUE TITLE
oathtool not present in docker image

### ISSUE THREAD

**Issue by Linus9000** [Neilpang/acme.sh#1541]
I'm trying to use inwx DNS API while running acme.sh in docker. I have 2FA enabled, so creating the record fails. The log states:

[Fri Apr 20 06:15:49 GMT 2018] Please install oathtool to use 2 Factor Authentication.

Would including oathtool in the official image be possible?

**Comment by FernandoMiguel** [comment]
an alternative is to link the bin folder into the docker container

personally, a simple docker with FROM and and ADD is super simple to do.

**Comment by Linus9000** [comment]
Of course it's simple, but it's only one step. How to efficiently do this for multiple servers? Of course I might setup GitHub and Docker Hub so I can regularly create the modded image (well, I hope so, never done that), but should everyone who wants to use this functionality have to do this? The point of this is not that I with my two servers can easily solve this, I know how to do that. I'm talking about potential use for others who might save hours themselves to set this up (because of internal repo only, no CI available or whatever). 

Just as I said, I'd be happy if it will be implemented (maybe it was an oversight even, 2FA support for at least INWX isn't that old and maybe it didn't come up yet). I'm fine with it whatever happens :)

**Comment by FernandoMiguel** [comment]
well, in automation, MFA doesnt work :)
there is no way for machines to fill in those.

so you should use API tokens instead

**Comment by Neilpang** [comment]
1.  the docker image is based on busybox, if it's easy to install oathtool without making image size too large,  I'm ok.
2.  Please make sure oathtool can work, especially for auto renewal.

please send a PR.

Thanks.

**Comment by maxemann96** [comment]
I think this can be closed because of #2182 ?
