### ISSUE TITLE
How to upgrade acme.sh if installed as Docker daemon?

### ISSUE THREAD

**Issue by pennybuster** [Neilpang/acme.sh#1556]
Hi there. I'm new to Docker concept.
Can you explain how to upgrade acme.sh without data loss if installed as Docker daemon?
What happens with the cron jobs inside such a container?
Thanks a lot!

**Comment by alexlii1971** [comment]
Our server is in china, and we are using Aliyun.

Is it possible to support wildcard ssl ? 

Does it support dns API?

Alex

**Comment by FernandoMiguel** [comment]
@pennybuster you should have mounted the volume into your host so no data is lost

if you didnt, then do a `docker cp¨ back to the host of home account

**Comment by pennybuster** [comment]
Thank you Fernando. I'm going to read more about Docker management...
