### ISSUE TITLE
dnsapi/dns_nsupdate.sh breaks after PR #1490 merge

### ISSUE THREAD

**Issue by jim-p** [Neilpang/acme.sh#1560]
PR #1490 changed the nsupdate key data format such that it's no longer valid on a current version of nsupdate from BIND. Affects at least FreeBSD platforms using bind-tools 9.12 but most likely anyone using a recent nsupdate.

The syntax change doesn't appear to be valid even on older versions of nsupdate from bind.

In the key data, the server name must be specified as:
`server servername [port]`

PR #1490 effectively changed it to:
`server servername -p port`

Using `-p` there is not valid. You can pass `-p` to nsupdate as a command parameter, but `-p` does not belong in the key data.

**Comment by Neilpang** [comment]
sorry, can you please fix it ?

**Comment by jim-p** [comment]
Yes I can work up a PR later today if I can find a few spare moments, otherwise it might be early next week, I'm really short on time today.

**Comment by jim-p** [comment]
For some reason when I updated it didn't pull in the two commits after the one that added `-p`. Checking again today in dev and master that's gone, so it's really OK now. Sorry for the noise.
