### ISSUE TITLE
How can I get .pem or .crt

### ISSUE THREAD

**Issue by feiyu0** [Neilpang/acme.sh#157]
The default Certificate is cer ,and how can I get .pem or .crt?

**Comment by heldchen** [comment]
it's exactly the same format.

**Comment by Neilpang** [comment]
@heldchen 

Yes,   just rename  `domain.com.cer`  to `domain.com.crt`  or `domain.com.pem`.  They are same.

**Comment by gesinn-it** [comment]
I don't think this is correct. The pem file may contain both, the cert and the key. See also: http://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file

```
> openssl rsa -check -in /etc/ssl/private/domain.com/domain.com.cer
unable to load Private Key
8544:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:650:Expecting: ANY PRIVATE KEY
```

After `cat domain.key domain.cer >> domain.pem` you will get:

```
> openssl rsa -check -in /etc/ssl/private/domain.com/domain.com.pem
RSA key ok
writing RSA key
-----BEGIN RSA PRIVATE KEY-----
ASdsfdfdf/TPdv1ALA3Z58N...
```

E.g. Courier IMAP SSL requires pem files with both, cert and key.

**Comment by Neilpang** [comment]
@gesinn-it 

Yes,  All the files are there,  you can use them in any form.  We can not provide all the forms for everyone.
You can just concat the files and use them.
