### ISSUE TITLE
Feature request: Set cert name to be used in local housekeeping (directories, commands)

### ISSUE THREAD

**Issue by ecsumed** [Neilpang/acme.sh#1570]
Given multiple domains, the certs are stored in a directory specified by the first domain. 

For example, if I have:
`-d *.example.com -d another.com -d example.com `

The certs are stored in: `/root/.acme.sh/*.example.com`
And renewals than have to be of the form: `acme.sh --renew -d *.example.com`

It would be great to have something like `--cert-name=<string>` that is used for local housekeeping and will not show up on the cert.

Certs stored in: `/root/.acme.sh/<string>`
Renewals: `acme.sh --renew --cert_name <string>`

This will help create a clean directory structure and won't create a new cert directory every time you update your domains since we'll have more control over which certificate we want to modify.

Inspiration from certbot's `cert-name` functionality. https://certbot.eff.org/docs/using.html#changing-a-certificate-s-domains

The closest function I've found for this is 
`  --cert-home                       Specifies the home dir to save all the certs, only valid for '--install' command.
`
but this is not _per_ directory. Also it's not usable in other commands like revoke, renew, etc.

**Comment by Neilpang** [comment]
>> This will help create a clean directory structure and won't create a new cert directory every time you update your domains since we'll have more control over which certificate we want to modify.

If you don't change the first `-d ` domain name,  it will not create new cert dir.

I don't want to add a cert-name.   It's simple enough for now.

**Comment by randohinn** [comment]
Chiming in, this would be good to have
