### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by Tntdruid** [Neilpang/acme.sh#1578]
How do i use  https://github.com/Neilpang/acme.sh/blob/master/deploy/unifi.sh when making a new cert?

No info on the site about the deploy scrips
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by dwatrous** [comment]
There is a readme in https://github.com/Neilpang/acme.sh/tree/master/deploy that explains how to use the deploy scripts. In most cases you are required to first issue the certificate and then export some environment variables and run --deploy. You also specify a --deploy-hook that says which script to use. In your case that will be "unifi".

If you search in the script for "DEPLOY_UNIFI_" you'll see that there are three or so env vars expected.

**Comment by Tntdruid** [comment]
@dwatrous Thanks :)

There should be a small post on the wiki about that
