### ISSUE TITLE
error 400 in dns manual mode

### ISSUE THREAD

**Issue by Ruebezahl11** [Neilpang/acme.sh#1596]
Steps to reproduce
trying to renew cert:
--renew suggests to do a new --issue; I did so, then - after new TXT record had propagated, I did
a --renew. Error message is "Unable to update challenge :: The challenge is not pending."
Previous error is http error 400
------------------

Debug log
-----------------
'[Mo 14. Mai 09:04:59 CEST 2018] Lets find script dir.
[Mo 14. Mai 09:04:59 CEST 2018] _SCRIPT_='/home/wolfgang/.acme.sh/acme.sh'
[Mo 14. Mai 09:04:59 CEST 2018] _script='/home/wolfgang/.acme.sh/acme.sh'
[Mo 14. Mai 09:04:59 CEST 2018] _script_home='/home/wolfgang/.acme.sh'
[Mo 14. Mai 09:04:59 CEST 2018] Using config home:/home/wolfgang/.acme.sh
[Mo 14. Mai 09:04:59 CEST 2018] LE_WORKING_DIR='/home/wolfgang/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.7.9
[Mo 14. Mai 09:04:59 CEST 2018] Using config home:/home/wolfgang/.acme.sh
[Mo 14. Mai 09:04:59 CEST 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Mo 14. Mai 09:04:59 CEST 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Mo 14. Mai 09:04:59 CEST 2018] DOMAIN_PATH='/home/wolfgang/.acme.sh/mail.maas-noten.de'
[Mo 14. Mai 09:04:59 CEST 2018] Renew: 'mail.maas-noten.de'
[Mo 14. Mai 09:04:59 CEST 2018] Le_API='https://acme-v01.api.letsencrypt.org/directory'
[Mo 14. Mai 09:04:59 CEST 2018] Using config home:/home/wolfgang/.acme.sh
[Mo 14. Mai 09:04:59 CEST 2018] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Mo 14. Mai 09:04:59 CEST 2018] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Mo 14. Mai 09:04:59 CEST 2018] _main_domain='mail.maas-noten.de'
[Mo 14. Mai 09:04:59 CEST 2018] _alt_domains='no'
[Mo 14. Mai 09:04:59 CEST 2018] 'dns' contains 'dns'
[Mo 14. Mai 09:04:59 CEST 2018] Using ACME_DIRECTORY: https://acme-v01.api.letsencrypt.org/directory
[Mo 14. Mai 09:04:59 CEST 2018] _init api for server: https://acme-v01.api.letsencrypt.org/directory
[Mo 14. Mai 09:04:59 CEST 2018] GET
[Mo 14. Mai 09:04:59 CEST 2018] url='https://acme-v01.api.letsencrypt.org/directory'
[Mo 14. Mai 09:04:59 CEST 2018] timeout=
[Mo 14. Mai 09:04:59 CEST 2018] _CURL='curl -L --silent --dump-header /home/wolfgang/.acme.sh/http.header  --trace-ascii /tmp/tmp.VKI1oyebYb  -g '
[Mo 14. Mai 09:05:00 CEST 2018] ret='0'
[Mo 14. Mai 09:05:00 CEST 2018] response='{
  "Su9_InuKrWs": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}'
[Mo 14. Mai 09:05:00 CEST 2018] ACME_KEY_CHANGE='https://acme-v01.api.letsencrypt.org/acme/key-change'
[Mo 14. Mai 09:05:00 CEST 2018] ACME_NEW_AUTHZ='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Mo 14. Mai 09:05:00 CEST 2018] ACME_NEW_ORDER='https://acme-v01.api.letsencrypt.org/acme/new-cert'
[Mo 14. Mai 09:05:00 CEST 2018] ACME_NEW_ACCOUNT='https://acme-v01.api.letsencrypt.org/acme/new-reg'
[Mo 14. Mai 09:05:00 CEST 2018] ACME_REVOKE_CERT='https://acme-v01.api.letsencrypt.org/acme/revoke-cert'
[Mo 14. Mai 09:05:00 CEST 2018] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Mo 14. Mai 09:05:00 CEST 2018] ACME_NEW_NONCE
[Mo 14. Mai 09:05:00 CEST 2018] ACME_VERSION
[Mo 14. Mai 09:05:00 CEST 2018] Le_NextRenewTime='1523516037'
[Mo 14. Mai 09:05:00 CEST 2018] _on_before_issue
[Mo 14. Mai 09:05:00 CEST 2018] _chk_main_domain='mail.maas-noten.de'
[Mo 14. Mai 09:05:00 CEST 2018] _chk_alt_domains
[Mo 14. Mai 09:05:00 CEST 2018] 'dns' does not contain 'no'
[Mo 14. Mai 09:05:00 CEST 2018] Le_LocalAddress
[Mo 14. Mai 09:05:00 CEST 2018] d='mail.maas-noten.de'
[Mo 14. Mai 09:05:00 CEST 2018] Check for domain='mail.maas-noten.de'
[Mo 14. Mai 09:05:00 CEST 2018] _currentRoot='dns'
[Mo 14. Mai 09:05:00 CEST 2018] d
[Mo 14. Mai 09:05:00 CEST 2018] 'dns' does not contain 'apache'
[Mo 14. Mai 09:05:00 CEST 2018] _saved_account_key_hash='dlzhUdSn2hTh18HJLN1LUpx2luSz0AAA6NfdHszyXLU='
[Mo 14. Mai 09:05:00 CEST 2018] _saved_account_key_hash is not changed, skip register account.
[Mo 14. Mai 09:05:00 CEST 2018] Read key length:
[Mo 14. Mai 09:05:00 CEST 2018] _createcsr
[Mo 14. Mai 09:05:00 CEST 2018] domain='mail.maas-noten.de'
[Mo 14. Mai 09:05:00 CEST 2018] domainlist
[Mo 14. Mai 09:05:00 CEST 2018] csrkey='/home/wolfgang/.acme.sh/mail.maas-noten.de/mail.maas-noten.de.key'
[Mo 14. Mai 09:05:00 CEST 2018] csr='/home/wolfgang/.acme.sh/mail.maas-noten.de/mail.maas-noten.de.csr'
[Mo 14. Mai 09:05:00 CEST 2018] csrconf='/home/wolfgang/.acme.sh/mail.maas-noten.de/mail.maas-noten.de.csr.conf'
[Mo 14. Mai 09:05:00 CEST 2018] Single domain='mail.maas-noten.de'
[Mo 14. Mai 09:05:00 CEST 2018] _is_idn_d='mail.maas-noten.de'
[Mo 14. Mai 09:05:00 CEST 2018] _idn_temp
[Mo 14. Mai 09:05:00 CEST 2018] _csr_cn='mail.maas-noten.de'
[Mo 14. Mai 09:05:00 CEST 2018] Getting domain auth token for each domain
[Mo 14. Mai 09:05:00 CEST 2018] ok, let's start to verify
[Mo 14. Mai 09:05:00 CEST 2018] Verifying:mail.maas-noten.de
[Mo 14. Mai 09:05:00 CEST 2018] d='mail.maas-noten.de'
[Mo 14. Mai 09:05:00 CEST 2018] keyauthorization='PW2gUhxeZe4IVA_6OXITgwQWREloHYhSKvxb2a65kIc.3z5PwGCXJuVn4XTf4qyIs2B4znQVA4MjePa10PwOGyo'
[Mo 14. Mai 09:05:00 CEST 2018] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/aadOOjRx9g_wv3omLRRMfC4i1dIagpVJTzLTTp7Vfsg/4592577040'
[Mo 14. Mai 09:05:00 CEST 2018] _currentRoot='dns'
[Mo 14. Mai 09:05:00 CEST 2018] tigger domain validation.
[Mo 14. Mai 09:05:00 CEST 2018] _t_url='https://acme-v01.api.letsencrypt.org/acme/challenge/aadOOjRx9g_wv3omLRRMfC4i1dIagpVJTzLTTp7Vfsg/4592577040'
[Mo 14. Mai 09:05:00 CEST 2018] _t_key_authz='PW2gUhxeZe4IVA_6OXITgwQWREloHYhSKvxb2a65kIc.3z5PwGCXJuVn4XTf4qyIs2B4znQVA4MjePa10PwOGyo'
[Mo 14. Mai 09:05:00 CEST 2018] url='https://acme-v01.api.letsencrypt.org/acme/challenge/aadOOjRx9g_wv3omLRRMfC4i1dIagpVJTzLTTp7Vfsg/4592577040'
[Mo 14. Mai 09:05:00 CEST 2018] payload='{"resource": "challenge", "keyAuthorization": "PW2gUhxeZe4IVA_6OXITgwQWREloHYhSKvxb2a65kIc.3z5PwGCXJuVn4XTf4qyIs2B4znQVA4MjePa10PwOGyo"}'
[Mo 14. Mai 09:05:00 CEST 2018] RSA key
[Mo 14. Mai 09:05:00 CEST 2018] Get nonce. ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Mo 14. Mai 09:05:00 CEST 2018] GET
[Mo 14. Mai 09:05:00 CEST 2018] url='https://acme-v01.api.letsencrypt.org/directory'
[Mo 14. Mai 09:05:00 CEST 2018] timeout=
[Mo 14. Mai 09:05:00 CEST 2018] _CURL='curl -L --silent --dump-header /home/wolfgang/.acme.sh/http.header  --trace-ascii /tmp/tmp.Gw0yENrv6V  -g '
[Mo 14. Mai 09:05:01 CEST 2018] ret='0'
[Mo 14. Mai 09:05:01 CEST 2018] _headers='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 658
Replay-Nonce: NONyZaspv2Xn65QJw49HuOecddprF7XZ4D-sZAuF60o
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 14 May 2018 07:05:01 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 14 May 2018 07:05:01 GMT
Connection: keep-alive
^M'
[Mo 14. Mai 09:05:01 CEST 2018] _CACHED_NONCE='NONyZaspv2Xn65QJw49HuOecddprF7XZ4D-sZAuF60o'
[Mo 14. Mai 09:05:01 CEST 2018] nonce='NONyZaspv2Xn65QJw49HuOecddprF7XZ4D-sZAuF60o'
[Mo 14. Mai 09:05:01 CEST 2018] POST
[Mo 14. Mai 09:05:01 CEST 2018] _post_url='https://acme-v01.api.letsencrypt.org/acme/challenge/aadOOjRx9g_wv3omLRRMfC4i1dIagpVJTzLTTp7Vfsg/4592577040'
[Mo 14. Mai 09:05:01 CEST 2018] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "mCplyyHgk1CRzn9AXptKmONRa-WJ69-fYpGzXf9blArjaXOigUKW2PuoPVpxDwcrhWxsfWpnSGrlvLzWsxWXegUpRHTKWrjWyavGOjHkHGYbcGeRe3pknpdAoEOqhmQqUK7Kh2_B1ecOQavZTzu6YsS2eWjvpsJfwpbeNPA_4-kzFLRjuiXqG54ZRmh8ZISfmmCOqSg5XINXIV8rFfcV4r8wLPIOSD4bdnBmmhiqTDjap8W1x9d6Fb4pPHrGEESWQ7R59Ir7pmLv7Y_GY7Yv5NiyLHxGr1uK-zybmwOsCc8tt0Zp1N8nTpaxeeb3i9loRLAh176Ppt_dz-Jwob0iSw"}}, "protected": "eyJub25jZSI6ICJOT055WmFzcHYyWG42NVFKdzQ5SHVPZWNkZHByRjdYWjRELXNaQXVGNjBvIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAxLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbGVuZ2UvYWFkT09qUng5Z193djNvbUxSUk1mQzRpMWRJYWdwVkpUekxUVHA3VmZzZy80NTkyNTc3MDQwIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAibUNwbHl5SGdrMUNSem45QVhwdEttT05SYS1XSjY5LWZZcEd6WGY5YmxBcmphWE9pZ1VLVzJQdW9QVnB4RHdjcmhXeHNmV3BuU0dybHZMeldzeFdYZWdVcFJIVEtXcmpXeWF2R09qSGtIR1liY0dlUmUzcGtucGRBb0VPcWhtUXFVSzdLaDJfQjFlY09RYXZaVHp1NllzUzJlV2p2cHNKZndwYmVOUEFfNC1rekZMUmp1aVhxRzU0WlJtaDhaSVNmbW1DT3FTZzVYSU5YSVY4ckZmY1Y0cjh3TFBJT1NENGJkbkJtbWhpcVREamFwOFcxeDlkNkZiNHBQSHJHRUVTV1E3UjU5SXI3cG1MdjdZX0dZN1l2NU5peUxIeEdyMXVLLXp5Ym13T3NDYzh0dDBacDFOOG5UcGF4ZWViM2k5bG9STEFoMTc2UHB0X2R6LUp3b2IwaVN3In19", "payload": "eyJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLCAia2V5QXV0aG9yaXphdGlvbiI6ICJQVzJnVWh4ZVplNElWQV82T1hJVGd3UVdSRWxvSFloU0t2eGIyYTY1a0ljLjN6NVB3R0NYSnVWbjRYVGY0cXlJczJCNHpuUVZBNE1qZVBhMTBQd09HeW8ifQ", "signature": "X0l3Q7oxMCaHq0Uvwq0wCjHcI5TiS4QHm-Ous5VJ_agDJes7NkCaL1hnAwHoHOc4ZFf7_MtgPUd8hg2q_oxJs7NmrKlyQPaCLYNCQSgEHGPqPrk-SRw5d5ylZJp0lveovOTSlfhoE7VgfCPPXDTTVFd4_WtnrGyd0TpHMOgrxxKzzBBF0qxCAAe003A600ZHGiOm0VjfemCVRIWk_AWXAzxa_x28_Bc9SatDcHeH1cR_dLogvzsq8ftDPOIlw6nwdJb3a9z4aV641rpenzVdx7GFTA5cNVj89AtQFIVihZpyiqoBMyyW36UFcpT62fSmI3oWDcTcbB5uRN-lpbeAyw"}'
[Mo 14. Mai 09:05:01 CEST 2018] _postContentType
[Mo 14. Mai 09:05:01 CEST 2018] _CURL='curl -L --silent --dump-header /home/wolfgang/.acme.sh/http.header  --trace-ascii /tmp/tmp.kEyoGYmIFv  -g '
[Mo 14. Mai 09:05:02 CEST 2018] _ret='0'
[Mo 14. Mai 09:05:02 CEST 2018] original='{
  "type": "urn:acme:error:malformed",
  "detail": "Unable to update challenge :: The challenge is not pending.",
  "status": 400
}'
[Mo 14. Mai 09:05:02 CEST 2018] responseHeaders='HTTP/1.1 100 Continue
Expires: Mon, 14 May 2018 07:05:01 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/problem+json
Content-Length: 132
Boulder-Requester: 28878953
Replay-Nonce: tMgQ8882m3p_OP8itSOOAgBHFFk3yfRP3f2zvg44JaE
Expires: Mon, 14 May 2018 07:05:02 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 14 May 2018 07:05:02 GMT
Connection: close
^M'
[Mo 14. Mai 09:05:02 CEST 2018] response='{"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}'
[Mo 14. Mai 09:05:02 CEST 2018] code='400'
[Mo 14. Mai 09:05:02 CEST 2018] mail.maas-noten.de:Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}
[Mo 14. Mai 09:05:02 CEST 2018] Skip for removelevel:
[Mo 14. Mai 09:05:02 CEST 2018] pid
[Mo 14. Mai 09:05:02 CEST 2018] No need to restore nginx, skip.
[Mo 14. Mai 09:05:02 CEST 2018] _clearupdns
[Mo 14. Mai 09:05:02 CEST 2018] skip dns.
[Mo 14. Mai 09:05:02 CEST 2018] _on_issue_err
[Mo 14. Mai 09:05:02 CEST 2018] Please check log file for more details: /home/wolfgang/.acme.sh/acme.sh.log
[Mo 14. Mai 09:05:02 CEST 2018] _chk_vlist='mail.maas-noten.de#PW2gUhxeZe4IVA_6OXITgwQWREloHYhSKvxb2a65kIc.3z5PwGCXJuVn4XTf4qyIs2B4znQVA4MjePa10PwOGyo#https://acme-v01.api.letsencrypt.org/acme/challenge/aadOOjRx9g_wv3omLRRMfC4i1dIagpVJTzLTTp7Vfsg/4592577040#dns-01#dns,'
[Mo 14. Mai 09:05:02 CEST 2018] start to deactivate authz
[Mo 14. Mai 09:05:02 CEST 2018] tigger domain validation.
[Mo 14. Mai 09:05:02 CEST 2018] _t_url='https://acme-v01.api.letsencrypt.org/acme/challenge/aadOOjRx9g_wv3omLRRMfC4i1dIagpVJTzLTTp7Vfsg/4592577040'
[Mo 14. Mai 09:05:02 CEST 2018] _t_key_authz='PW2gUhxeZe4IVA_6OXITgwQWREloHYhSKvxb2a65kIc.3z5PwGCXJuVn4XTf4qyIs2B4znQVA4MjePa10PwOGyo'
[Mo 14. Mai 09:05:02 CEST 2018] url='https://acme-v01.api.letsencrypt.org/acme/challenge/aadOOjRx9g_wv3omLRRMfC4i1dIagpVJTzLTTp7Vfsg/4592577040'
[Mo 14. Mai 09:05:02 CEST 2018] payload='{"resource": "challenge", "keyAuthorization": "PW2gUhxeZe4IVA_6OXITgwQWREloHYhSKvxb2a65kIc.3z5PwGCXJuVn4XTf4qyIs2B4znQVA4MjePa10PwOGyo"}'
[Mo 14. Mai 09:05:02 CEST 2018] Use cached jwk for file: /home/wolfgang/.acme.sh/ca/acme-v01.api.letsencrypt.org/account.key
[Mo 14. Mai 09:05:02 CEST 2018] Use _CACHED_NONCE='tMgQ8882m3p_OP8itSOOAgBHFFk3yfRP3f2zvg44JaE'
[Mo 14. Mai 09:05:02 CEST 2018] nonce='tMgQ8882m3p_OP8itSOOAgBHFFk3yfRP3f2zvg44JaE'
[Mo 14. Mai 09:05:02 CEST 2018] POST
[Mo 14. Mai 09:05:02 CEST 2018] _post_url='https://acme-v01.api.letsencrypt.org/acme/challenge/aadOOjRx9g_wv3omLRRMfC4i1dIagpVJTzLTTp7Vfsg/4592577040'
[Mo 14. Mai 09:05:02 CEST 2018] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "mCplyyHgk1CRzn9AXptKmONRa-WJ69-fYpGzXf9blArjaXOigUKW2PuoPVpxDwcrhWxsfWpnSGrlvLzWsxWXegUpRHTKWrjWyavGOjHkHGYbcGeRe3pknpdAoEOqhmQqUK7Kh2_B1ecOQavZTzu6YsS2eWjvpsJfwpbeNPA_4-kzFLRjuiXqG54ZRmh8ZISfmmCOqSg5XINXIV8rFfcV4r8wLPIOSD4bdnBmmhiqTDjap8W1x9d6Fb4pPHrGEESWQ7R59Ir7pmLv7Y_GY7Yv5NiyLHxGr1uK-zybmwOsCc8tt0Zp1N8nTpaxeeb3i9loRLAh176Ppt_dz-Jwob0iSw"}}, "protected": "eyJub25jZSI6ICJ0TWdRODg4Mm0zcF9PUDhpdFNPT0FnQkhGRmszeWZSUDNmMnp2ZzQ0SmFFIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAxLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbGVuZ2UvYWFkT09qUng5Z193djNvbUxSUk1mQzRpMWRJYWdwVkpUekxUVHA3VmZzZy80NTkyNTc3MDQwIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAibUNwbHl5SGdrMUNSem45QVhwdEttT05SYS1XSjY5LWZZcEd6WGY5YmxBcmphWE9pZ1VLVzJQdW9QVnB4RHdjcmhXeHNmV3BuU0dybHZMeldzeFdYZWdVcFJIVEtXcmpXeWF2R09qSGtIR1liY0dlUmUzcGtucGRBb0VPcWhtUXFVSzdLaDJfQjFlY09RYXZaVHp1NllzUzJlV2p2cHNKZndwYmVOUEFfNC1rekZMUmp1aVhxRzU0WlJtaDhaSVNmbW1DT3FTZzVYSU5YSVY4ckZmY1Y0cjh3TFBJT1NENGJkbkJtbWhpcVREamFwOFcxeDlkNkZiNHBQSHJHRUVTV1E3UjU5SXI3cG1MdjdZX0dZN1l2NU5peUxIeEdyMXVLLXp5Ym13T3NDYzh0dDBacDFOOG5UcGF4ZWViM2k5bG9STEFoMTc2UHB0X2R6LUp3b2IwaVN3In19", "payload": "eyJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLCAia2V5QXV0aG9yaXphdGlvbiI6ICJQVzJnVWh4ZVplNElWQV82T1hJVGd3UVdSRWxvSFloU0t2eGIyYTY1a0ljLjN6NVB3R0NYSnVWbjRYVGY0cXlJczJCNHpuUVZBNE1qZVBhMTBQd09HeW8ifQ", "signature": "NSCR3n5PoG5tYVQy0zMm71E1e45eGW5xMns4dhwdsgcc3hu9W--wgVwb6xEUi4kXNMMereakk-2aB0Oa7xoJj_7JR3zxbbzCALjGlNqa3pyfL3PJLfMerCOsnaty5SaVVT7R5Ad35n1XAMJkHkNJrzaqepwiKywETQTlVqo1KpsF4icbk_20M-iP1iKVHKsxeoO6M48b6AjFYyYxdeTpTE_XXOT4Hl-eccojMYxapncQ_wWsv9jBycpnwWfNBZhdVgAVjEh0R6XU2fcLzsDHKwh5va0zj7q6zHoVfD7Yv-s2PiHNnvOIoOZZ4YY180LfVVjdOuGUB3SXSG0BKPuGSA"}'
[Mo 14. Mai 09:05:02 CEST 2018] _postContentType
[Mo 14. Mai 09:05:02 CEST 2018] _CURL='curl -L --silent --dump-header /home/wolfgang/.acme.sh/http.header  --trace-ascii /tmp/tmp.KiUkQ9ERVQ  -g '
[Mo 14. Mai 09:05:03 CEST 2018] _ret='0'
[Mo 14. Mai 09:05:03 CEST 2018] original='{
  "type": "urn:acme:error:malformed",
  "detail": "Unable to update challenge :: The challenge is not pending.",
  "status": 400
}'
[Mo 14. Mai 09:05:03 CEST 2018] responseHeaders='HTTP/1.1 100 Continue
Expires: Mon, 14 May 2018 07:05:02 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/problem+json
Content-Length: 132
Boulder-Requester: 28878953
Replay-Nonce: l5Ygg5J3mQR9zuLEraV3xyaHhHS_Bk3cM6EskMUDQT4
Expires: Mon, 14 May 2018 07:05:03 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 14 May 2018 07:05:03 GMT
Connection: close
^M'
[Mo 14. Mai 09:05:03 CEST 2018] response='{"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}'
[Mo 14. Mai 09:05:03 CEST 2018] code='400'
[Mo 14. Mai 09:05:03 CEST 2018] 'dns' contains 'dns'
[Mo 14. Mai 09:05:03 CEST 2018] The dns manual mode can not renew automatically, you must issue it again manually. You'd better use the other modes instead.
[Mo 14. Mai 09:05:03 CEST 2018] socat doesn't exists.
[Mo 14. Mai 09:05:03 CEST 2018] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.1k 8 Jan 2015
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:

One thing that looks strange: the script is sending json but uses a application/x-www-form-urlencoded content type

**Comment by Ruebezahl11** [comment]
I found a simple solution: I just deleted the domain folder and then started with --issue again. This time, the v2 api was used. Here, --renew worked as expected.

**Comment by AlanCapital** [comment]
> I found a simple solution: I just deleted the domain folder and then started with --issue again. This time, the v2 api was used. Here, --renew worked as expected.
Yes delete domain folder worked for me too ) thanks
