### ISSUE TITLE
Quotes or special characters in reload command

### ISSUE THREAD

**Issue by coreyworrell** [Neilpang/acme.sh#1599]
Steps to reproduce
------------------
Set `--reloadcmd` or `Le_ReloadCmd=` to something that includes characters with special bash meaning, or that has quotes

`Le_ReloadCmd='ENV_VAR=test>exa$mpl /var/script.sh'`
of course does not work.

`Le_ReloadCmd='ENV_VAR='"'test>exa$mpl'"' /var/script.sh'`
does work once, but then it overwrites the `.conf` file without the extra quotes like so:

`Le_ReloadCmd='ENV_VAR='test>exa$mpl' /var/script.sh'`
which will not work as it is basically the same as first example above.

#336 addressed this for other options, but since `LeReloadCmd` runs as a command itself, it doesn't cover this case. Base64 encoding/decoding is an option for certain use cases, but seems like an extra step that should not be necessary.

**Comment by mgollo** [comment]
I stumbled over this today after I had added ReloadCmd with a pipe symbol to one of my configs. After I had recovered my original config from my backups, I did some testing with the LE staging API.
Here is my config (I added the ReloadCmd after the initial certificate creation as this was what I did with my original certificate as well; e-mail address was a working one of course):
    Le_Domain='test.gollo.at'
    Le_Alt='*.test.gollo.at'
    Le_Webroot='dns_schoko'
    Le_PreHook=''
    Le_PostHook=''
    Le_RenewHook=''
    Le_API='https://acme-staging-v02.api.letsencrypt.org/directory'
    Le_Keylength=''
    Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/8350662/24295703'
    Le_DNSSleep='60'
    Le_LinkCert='https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa5ebcff82a9390caa0736b3b97b7b425878'
    Le_CertCreateTime='1551079394'
    Le_CertCreateTimeStr='Mon Feb 25 07:23:14 UTC 2019'
    Le_NextRenewTimeStr='Fri Apr 26 07:23:14 UTC 2019'
    Le_NextRenewTime='1556176994'
    Le_ReloadCmd='chmod 640 /etc/ssl/acme.sh/private/*; rsync -essh -aquz ~/.acme.sh/test.gollo.at/ 192.168.1.10:~/ssl/; echo "bla" | mail -s "test" test@example.org'

After running  
    acme.sh --renew -d test.gollo.at --force
the config file only contained the line
    Le_RealFullChainPath=''

**Comment by Neilpang** [comment]
@mgollo   Do not write complex commends in `--reloadcmd`.  you can write all your commands in a single shell file,  and call it in `--reloadcmd`

**Comment by mgollo** [comment]
That's exactly how I solved it. I was just too lazy before and unaware of this issue.
