### ISSUE TITLE
Renewing in manuel mode - where is the TXT-File?

### ISSUE THREAD

**Issue by Irv007** [Neilpang/acme.sh#1609]
Hello,

I'm a beginner in the area of SSL-Certificates.
I use acme.sh in manuel mode.

My browser Chrome says, my connection to my website is not secure since May, 10.
Before that, it was secure.
https://www.ssllabs.com/ says, the the certificate expired on May, 10.

If i say, "acme.sh --renew -d xbuch.eu", the log is: 
[Sat May 19 08:11:49 CEST 2018] Renew: 'xbuch.eu'
[Sat May 19 08:11:49 CEST 2018] Skip, Next renewal time is: Wed Jul 18 05:59:52 UTC 2018
[Sat May 19 08:11:49 CEST 2018] Add '--force' to force to renew.

If I say, " acme.sh --force --renew -d xbuch.eu", the log is:

[Sat May 19 08:17:04 CEST 2018] Renew: 'xbuch.eu'
[Sat May 19 08:17:04 CEST 2018] It seems that you are using dns manual mode. Read this link first: https://github.com/Neilpang/acme.sh/wiki/dns-manual-mode

After several attempts, I had deleted acme.sh.log in order to not be confused by old log information.

My questions:

- Using the force-option, did I now get a new TXT-record, that I have to put in my external DNS-Management-System?
- Where do I find the TXT-value?
- Is this forum the right place for this kind of questions?

regards, Irv

uname -a: Linux ip-172-31-19-142 4.4.0-1054-aws #63-Ubuntu SMP Wed Mar 28 19:42:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by FernandoMiguel** [comment]
please dont use manual dns mode.
it's meant for testing not for user and production usage.
the all principle of let's encrypt is automation.

so consider using a DNS provider that just works, or HTTP01 method

**Comment by Irv007** [comment]
ok, thank you.

Additonally, I have used the flag "--debug 2"-flag.

now, the actual problem is clear:

Sign failed: "detail":"Error creating new cert :: too many certificates already issued for exact set of domains: xbuch.eu: see https://letsencrypt.org/docs/rate-limits/"
