### ISSUE TITLE
Cygwin Standalone Verify Error

### ISSUE THREAD

**Issue by emelsk** [Neilpang/acme.sh#161]
Did anyone succeed in getting a cert using acme.sh **in standalone mode** on Cygwin? Here's my debug test session after trying (and failing) it for real first: [acme.sh.cygwin.standalone.debug.txt](https://github.com/Neilpang/acme.sh/files/225832/acme.sh.cygwin.standalone.debug.txt)

It appears as if nc was complaining about the way it was called first, then there's a message on missing (?) -i support in sed - can't tell if either of the two is really relevant - before the script ultimately spits out error `<fqdn>:Verify error:Could not connect to http://<fqdn>/.well-known/acme-challenge/<snip>`

Reaching the target on port 80 from the internet should not be an issue - had Skype sitting on that port originally, but the script complained about it in the very first attempt, in very early stage of its execution.

**Comment by heldchen** [comment]
this is the real problem: `nc: getaddrinfo: Servname not supported for ai_socktype`

**Comment by Neilpang** [comment]
fixed.  f321c3c7ea7513870cdaa5a757eb67b356e47ac1
please try again:

**Comment by Neilpang** [comment]
@emelsk  @heldchen 

I just tried again in my Windows7 vm in `--standalone` mode.  It' working without any problem.

**Comment by Neilpang** [comment]
@emelsk 

To check your issue.  please open cygwin:
```
echo  "hello world" | nc -l 80
```

Then use your browser to visit :  http://yourdomain.com

you should see 'hello world'

**Comment by emelsk** [comment]
@Neilpang Thank you very much. I pulled the updates, reinstalled the client, fiddled around with your netcat line locally first (`echo "hello world" | nc -l 0.0.0.0 80` turned out to be slightly better as the original version, otherwise nc would keep listening on `lo` interface instead of `lan` where I was expecting it to listen during local tests), discovered missing firewall rule allowing inbound port 80 connections (this is of course NATed machine running Cygwin) afterwards and then it all worked like charm. Thanks again!
