### ISSUE TITLE
 acme.sh: command not found

### ISSUE THREAD

**Issue by luochenzhimu** [Neilpang/acme.sh#1610]
安装完成后运行提示，是什么问题？
acme.sh: command not found

**Comment by luochenzhimu** [comment]
root@VM-72-48-ubuntu:/home/ubuntu# curl https://get.acme.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705  100   705    0     0   1965      0 --:--:-- --:--:-- --:--:--  1963
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  164k  100  164k    0     0  61461      0  0:00:02  0:00:02 --:--:-- 61442
[Sat May 19 19:55:30 CST 2018] Installing from online archive.
[Sat May 19 19:55:30 CST 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Sat May 19 19:55:34 CST 2018] Extracting master.tar.gz
[Sat May 19 19:55:34 CST 2018] It is recommended to install socat first.
[Sat May 19 19:55:34 CST 2018] We use socat for standalone server if you use standalone mode.
[Sat May 19 19:55:34 CST 2018] If you don't use standalone mode, just ignore this warning.
[Sat May 19 19:55:34 CST 2018] Installing to /root/.acme.sh
[Sat May 19 19:55:34 CST 2018] Installed to /root/.acme.sh/acme.sh
[Sat May 19 19:55:34 CST 2018] Installing alias to '/root/.bashrc'
[Sat May 19 19:55:34 CST 2018] OK, Close and reopen your terminal to start using acme.sh
[Sat May 19 19:55:34 CST 2018] Installing cron job
[Sat May 19 19:55:34 CST 2018] Good, bash is found, so change the shebang to use bash as preferred.
[Sat May 19 19:55:34 CST 2018] OK
[Sat May 19 19:55:34 CST 2018] Install success!

ubuntu@VM-72-48-ubuntu:~$ acme.sh --issue -d *.luochenzhimu.com --apache
acme.sh: command not found
ubuntu@VM-72-48-ubuntu:~$ cd /home/ubuntu/.acme.sh
ubuntu@VM-72-48-ubuntu:~/.acme.sh$ acme.sh --issue -d *.luochenzhimu.com --apache
acme.sh: command not found
ubuntu@VM-72-48-ubuntu:~/.acme.sh$
ubuntu@VM-72-48-ubuntu:~/.acme.sh$ acme.sh --list
acme.sh: command not found
ubuntu@VM-72-48-ubuntu:~/.acme.sh$ chmod +x acme.sh
ubuntu@VM-72-48-ubuntu:~/.acme.sh$ acme.sh --list
acme.sh: command not found
ubuntu@VM-72-48-ubuntu:~/.acme.sh$ sudo su
root@VM-72-48-ubuntu:/home/ubuntu/.acme.sh# acme.sh --list
acme.sh: command not found

**Comment by MAGICCC** [comment]
You need to open a new terminal 
>OK, Close and reopen your terminal to start using acme.sh

**Comment by luochenzhimu** [comment]
已解决，必须关闭安装acme.sh的终端，重新打开一个终端以使acme.sh命令生效
After the installation, you must close the current terminal and reopen it to make the alias take effect.

安装的终端继续执行的话需要写成 ~/.acme.sh/acme.sh形式，建议新建终端

**Comment by fresh-a** [comment]
我安装完成之后在install success后也报这个错 请问是安装之后新开一个终端就可以进行下一步的配置了吗
