### ISSUE TITLE
Uninstall acme.sh如何卸载acme.sh？直接删除acme.sh报错

### ISSUE THREAD

**Issue by luochenzhimu** [Neilpang/acme.sh#1612]
Uninstall acme.sh
直接删除acme.sh后登录终端命令行报错
-bash: /home/ubuntu/.acme.sh/acme.sh.env: No such file or directory

**Comment by luochenzhimu** [comment]
解决了，重新安装acme.sh
然后
`acme.sh --uninstall`

**Comment by truebit** [comment]
`vi /root/.profile` 然后删掉`/home/ubuntu/.acme.sh/acme.sh.env` 所在的行就好了

**Comment by Neilpang** [comment]
解决办法就是 重新安装一次, 然后执行 `acme.sh --uninstall`
然后再删除 `~/.acme.sh/` 目录.
