### ISSUE TITLE
Failed to connect to get.acme.sh

### ISSUE THREAD

**Issue by betaxab** [Neilpang/acme.sh#1617]
Steps to reproduce
------------------
`curl  https://get.acme.sh | sh`

Debug log
-----------------

```
curl: (7) Failed to connect to get.acme.sh port 443: Connection refused
```

Maybe get.acme.sh website have a problem. It rejected all connections.

**Comment by Neilpang** [comment]
fixed,  try again please.

**Comment by patgg** [comment]
same problem with wget or upgrade . 

For upgrade the acme application it fails (same reason) : 

_

> acme.sh --upgrade --auto-upgrade
> [mardi 22 mai 2018, 12:12:35 (UTC+0200)] Installing from online archive.
> [mardi 22 mai 2018, 12:12:35 (UTC+0200)] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
> [mardi 22 mai 2018, 12:12:35 (UTC+0200)] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
> [mardi 22 mai 2018, 12:12:35 (UTC+0200)] Download error.
> [mardi 22 mai 2018, 12:12:35 (UTC+0200)] Upgrade failed!

_


For WGET, i can't get : ERREUR : le nom commun du certificat ▒www.github.com▒ ne concorde pas avec le nom de l'h▒te demand▒ ▒raw.githubusercontent.com▒.
It seems that there's a problem beetween github.com et raw.githubusercontent.com : 

```

>  wget --no-check-certificate https://github.com/Neilpang/acme.sh/archive/master.zip
> --2018-05-22 12:13:17--  https://github.com/Neilpang/acme.sh/archive/master.zip
> R▒solution de github.com... 192.30.253.112, 192.30.253.113
> Connexion vers github.com|192.30.253.112|:443...connect▒.
> OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
> Incapable d'▒tablir une connexion SSL.

```

**Comment by herrold** [comment]
I encountered this issue from an older maximum TLS suite distribution, and had to fall back to a 'http' URL, to remove the older crypto suite issue.  I also saved into a local file first, inspected the code, and only then ran it

**Comment by Neilpang** [comment]
@urbels  fixed, try again please.

**Comment by krwu** [comment]
Happening again right now:

```bash
$ curl https://get.acme.sh
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to get.acme.sh:443
```

**Comment by MuYunyun** [comment]
> Happening again right now:
> 
> ```shell
> $ curl https://get.acme.sh
> curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to get.acme.sh:443
> ```

please help, same as the solution.
