### ISSUE TITLE
add a symlink to old .le folder to preserve configuration from webservers

### ISSUE THREAD

**Issue by Richard87** [Neilpang/acme.sh#162]
Hi!

After upgrading to new acme.sh script, I had to update the configuration in my webserver.... But there was no notice that I needed to, or that it would become a problem... the upgrade script should create a symlink aswell as moving the folder.

**Comment by Neilpang** [comment]
Hi @Richard87 
Sorry for the trouble, but it's not suggest to directly use the certs in the `.le` folder.  
You should use the `reloadcmd`  to copy the certs to your real folder and us them there.

**Comment by Neilpang** [comment]
Hi @Richard87 .

If you call :
```
acme.sh  --install
```

It will first detect whether you have `le` installed, if found, it will convert le to acme.sh automatically.
