### ISSUE TITLE
请问 DNS API Dev 这个脚本如何测试

### ISSUE THREAD

**Issue by hldh214** [Neilpang/acme.sh#1621]
比方说我写好了 `dns_qcloud.sh`, 我想单独测试这一个脚本是否能成功发请求加 record
而不涉及其他的模块比如不调用 letsencrypt 这边的 api
如果是直接执行 `./dns_qcloud.sh` 的话使不上 `acme.sh` 里的函数比如 `_hash()` 这类
谢谢~

**Comment by Neilpang** [comment]
1 首先建议你还是直接用 letsencrypt 的  测试 api 调试.  只需要加上 `acme.sh --test  --issue  -d xxxx  --dns dns_xxxx`.  这种简单直接. 而且不会有限额.

2 其次.  如果你真的想单独调试的话.  可以先用 `source` 命令, 把 acme.sh 文件导入到当前的 shell 中. 然后再把你自己的 dns_qcloud.sh 导入到当前shell 就可以直接调用里面的函数了.
但是注意的是, 每次你修改晚 dns_qcloud.sh  都要重新导入:
```sh
source  acme.sh

source  dns_qcloud.sh

dns_qcloud_add   mydomain.com   "this is txt record value."
```
