### ISSUE TITLE
How to use acme?

### ISSUE THREAD

**Issue by rualexy** [Neilpang/acme.sh#1622]
How do you do!
I have a letsencrypt certificates generated certbot(linux server). But i reinstall server, where it do. How can i use acme to get/renew my cert on new installed server.

Thanx

**Comment by MAGICCC** [comment]
You may read https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert

**Comment by rualexy** [comment]
I have already issued a certificate *.mysyte.com earlier. Should I change the TXT on my DNS server?

**Comment by MAGICCC** [comment]
Yes you may change the TXT record for a new cert

**Comment by FernandoMiguel** [comment]
no, you dont do the DNS yourself.
you use the API to do it for you when it renews.

what DNS provider are you using?

**Comment by rualexy** [comment]
>what DNS provider are you using?
imena.ua

**Comment by rualexy** [comment]
I don't want get a new cert. Early i get certs for my site: mysite.com *.mysite.com. When i run:
  acme.sh --issue -d mysite.com -d '*.mysite.com' --apache
i get error "Error, can not get domain token entry *.mysite.com. The supported validation types are: dns-01 , but you specified: http-01"
When i run:
acme.sh --issue -d mysite.com -d '*.mysite.com' --apache --dns
i get error "It seems that you are using dns manual mode. Read this link first: https://git........". It try to use some "dns plugin". But i'am get exist cert, not new. What command is true for me?

**Comment by FernandoMiguel** [comment]
you cant use apache with wildcard issuing.
only DNS API

**Comment by FernandoMiguel** [comment]
you need to use a DNS provider that has a supported API with acme.sh
go over the list of available options.
if your provider is not there, either provide a PR to include it or use the alias method

**Comment by Neilpang** [comment]
@FernandoMiguel 

Yes,  but if the dns provider is not supported yet by acme.sh.  you can try dns alias mode:
https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode

**Comment by Neilpang** [comment]
follow the steps in the readme. 
https://github.com/Neilpang/acme.sh
