### ISSUE TITLE
problem with getting cert for subdomain while domain has no zone

### ISSUE THREAD

**Issue by naox** [Neilpang/acme.sh#1626]
acme.sh is unable to to get cert for sub.example.com if example.com has  has no records (or zone itself) on its dns servers (while sub.example.com does)

[Sun May 27 23:41:09 CEST 2018] sub.example.com:Verify error:DNS problem: SERVFAIL looking up CAA for example.com

**Comment by FernandoMiguel** [comment]
my understanding of DNS Zones RFC, is that you **have** to have an apex zone
or do you know something i dont?

**Comment by naox** [comment]
Maybe in RFC's perfect world
dziennik.smerf24.pl looks up to an IP and works while smerf24.pl has no zone. acme.sh blocks attempt of getting letsencrypt cert for dziennik.smerf24.pl. I don't know however what would letsencrypt do when could not lookup CAA on smerf24.pl

**Comment by naox** [comment]
looking at the code I see that error is actualy comming from letsencrypt servers, so yeah...
