### ISSUE TITLE
三级域名OK，四级域名提示证书无授信

### ISSUE THREAD

**Issue by xiagw** [Neilpang/acme.sh#1632]
已经生成*.domain.com 的泛域名证书，
xxx.domain.com 一切都正常，
yy.xx.domain.com 则浏览器提示不安全证书。
难道是 issue 时 要多加 一个 参数 -d *.*.domain.com 吗？
求解

**Comment by lf-zbw** [comment]
泛域名证书只能保护某一级子域名，yy.xx.domain.com需要加`-d *.xx.domain.com`，如果加`-d *.*.domain.com`会报错`Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:malformed","detail":"Error creating new order :: DNS name had more than one wildcard","status": 400}`。

**Comment by FernandoMiguel** [comment]
You can't create two level wildcard. Is not permitted in the rfc

**Comment by xiagw** [comment]
thks everyone.
