### ISSUE TITLE
在群晖5.1上阿里ali报SignatureNonceUsed错

### ISSUE THREAD

**Issue by zyjia** [Neilpang/acme.sh#1639]
{"Recommend":"https://error-center.aliyun.com/status/search?Keyword=SignatureNonceUsed&source=PopGw","Message":"Specified signature nonce was used already.","RequestId":"B2EA4DDC-2E06-471E-8784-6C33AD871AAF","HostId":"alidns.aliyuncs.com","Code":"SignatureNonceUsed"}
阿里的解释是SignatureNonce 重复。每次请求的 SignatureNonce 在 15 分钟内不能重复。

看了一下记录确实在极短的时间内申请了两次，在群晖其他版本如6.0.2/6.1.6上正常的。
并且在相同的机器上cloudflare没有问题。
[Wed May 30 16:49:06 CST 2018] First detect the root zone
[Wed May 30 16:49:07 CST 2018] GET
[Wed May 30 16:49:07 CST 2018] url='https://alidns.aliyuncs.com/?AccessKeyId=iKjJIyGQSLS6pmyh&Action=DescribeDomainRecords&DomainName=zyjia.tk&Format=json&SignatureMethod=HMAC-SHA1&SignatureNonce=1527670146%N&SignatureVersion=1.0&Timestamp=2018-05-30T08%3A49%3A06Z&Version=2015-01-09&Signature=K15WtNVlVh9vOVUtzaTuZLHWYWE%3D'
[Wed May 30 16:49:07 CST 2018] timeout=3000
[Wed May 30 16:49:07 CST 2018] _CURL='curl -L --silent --dump-header /usr/local/share/acme.sh/http.header  -g  --connect-timeout 3000'
[Wed May 30 16:49:07 CST 2018] ret='0'
[Wed May 30 16:49:08 CST 2018] GET
[Wed May 30 16:49:08 CST 2018] url='https://alidns.aliyuncs.com/?AccessKeyId=iKjJIyGQSLS6pmyh&Action=DescribeDomainRecords&DomainName=tk&Format=json&SignatureMethod=HMAC-SHA1&SignatureNonce=1527670147%N&SignatureVersion=1.0&Timestamp=2018-05-30T08%3A49%3A07Z&Version=2015-01-09&Signature=%2FVlEKbYqtYtj%2BDLHLMTh1vwBow8%3D'
[Wed May 30 16:49:08 CST 2018] timeout=3000
[Wed May 30 16:49:08 CST 2018] _CURL='curl -L --silent --dump-header /usr/local/share/acme.sh/http.header  -g  --connect-timeout 3000'
[Wed May 30 16:49:08 CST 2018] ret='0'

**Comment by herirong** [comment]
最后怎么解决的？碰到同样的问题

**Comment by Neilpang** [comment]
使用 别的 api 
或者用 dns alis 模式:  https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode

由于 群晖上的 openssl 过于简陋,  ali 的签名算法有 bug
