### ISSUE TITLE
can't issue wildcard cert using * anymore : Unknown parameter :

### ISSUE THREAD

**Issue by samnyan** [Neilpang/acme.sh#1651]
Steps to reproduce
------------------
I try to issue a wildcard cert by using this command:
`acme.sh --issue -d domain.com -d *.domain.com --dns dns_cf`

But it shows  Unknown parameter : example.domain.com
The example.domain.com is one of domain I have issued before.
Now how can I delete the old config to issue a new cert?
I tried uninstall acme.sh , and the acme.sh remove command but have no difference.

Is there any config files in other location?

Debug log
-----------------

Using --debug show the same error without any log.

**Comment by samnyan** [comment]
Never mind.
I have to add quotes to that domain.
I'm using zsh 🌚

**Comment by killday** [comment]
Hi @samnyan How exacly did you solce this?
