### ISSUE TITLE
Create new order error. Le_OrderFinalize not found

### ISSUE THREAD

**Issue by MatthewSteeples** [Neilpang/acme.sh#1657]
Steps to reproduce
------------------
```
./acme.sh --debug 2 --renew -d ledgerscope.com --dns dns_me
```

I created this certificate in March, and if I do a `./acme.sh list` it appears in there. I have exported my API keys for DNSMadeEasy and they're set up correctly. The error that I'm getting is:

`Create new order error. Le_OrderFinalize not found. {"type":"urn:ietf:params:acme:error:malformed","detail":"Invalid Content-Type header on POST. Content-Type must be \"application/jose+json\"","status": 415}`

I get the same error if I try and issue a new certificate, and also whether I leave off the --dns option or keep it on. I've attached the .tmp trace file referenced in the debug log. If anything else would be helpful please let me know. I've got a bit of experience with LE (I wrote the DNSME implementation for the ACMESharp module - https://github.com/ebekker/ACMESharp/pull/254) so I'd like to think I've tried everything obvious, but can't guarantee it!
[acme.log](https://github.com/Neilpang/acme.sh/files/2076927/acme.log)
[diag.log](https://github.com/Neilpang/acme.sh/files/2076928/diag.log)

**Comment by Neilpang** [comment]
upgrade to latest acme.sh v2.7.9 and try again.

**Comment by MatthewSteeples** [comment]
@Neilpang That's great thanks. I'd done a ./acme.sh --upgrade so thought I was on the latest version already, but I'd forgotten that I'd cloned the git repo to set this up, so it hadn't actually updated the software!
