### ISSUE TITLE
Update the Godaddy Api Key/Secret in account.conf

### ISSUE THREAD

**Issue by phreakfer44** [Neilpang/acme.sh#1658]
Hello! I write this message because I had to update Godaddy's Api Key. To do this, I entered:
https://developer.godaddy.com/keys/
Then, I removed the key I had already created and created a new PRODUCTION key.
After this I tried updating via SSH:
```
export GD_Key = "****"
export GD_Secret = "****"
```
But when I check the `account.conf` file I see that it did NOT update the values
In `SAVED_GD_Key` there is the old key and in `SAVED_GD_Secret` there is the old secret as well.
This is why I understand that the values were never updated, but I don´t understand why.
1) How can I make it work for me?
2) Can I edit the account.conf file directly?

Sorry for my english

**Comment by baoang** [comment]
editing the account.conf will work. my experience.

actually, I didn't try the export command.

**Comment by phreakfer44** [comment]
Thanks very much. I will try it!!

De: baoang
Enviado: domingo, 10 de junio 02:52
Asunto: Re: [Neilpang/acme.sh] Update the Godaddy Api Key/Secret in account.conf (#1658)
Para: Neilpang/acme.sh
Cc: Fernando Rodrigo, Author


editing the account.conf will work. my experience.
actually, I didn't try the export command.

**Comment by Neilpang** [comment]
>> How can I make it work for me?

As you expected, another export should be working;
```sh
export GD_Key="sdfsafdsfdsfsdf"
export GD_Secret="adfsdfsdf"
```
There is not space key before or after the equal sign "=" above.

>> Can I edit the account.conf file directly?

Yes.

**Comment by phreakfer44** [comment]
Thanks very much @Neilpang
