### ISSUE TITLE
Fish shell

### ISSUE THREAD

**Issue by agarzon** [Neilpang/acme.sh#166]
Whoever is using fish shell needs to add manually the environment variables because the installer is not intended for that shell.

Add into file **~/.config/fish/config.fish**
```bash
set -gx LE_WORKING_DIR "/root/.acme.sh"
function acme.sh
        /root/.acme.sh/acme.sh
end
```

Note that you need to replace the path for your own.!

**Comment by Neilpang** [comment]
what is fish shell?

**Comment by agarzon** [comment]
https://fishshell.com/ a powerful alternative to bash.

**Comment by Neilpang** [comment]
thanks.

**Comment by the-solipsist** [comment]
Just in case someone comes across this and faces a problem, @agarzon has accidentally left out the `$argv` variable from the function.  It should be:
```
set -gx LE_WORKING_DIR "/root/.acme.sh"
function acme.sh
        /root/.acme.sh/acme.sh $argv;
end
```
(Substitute the directory you want for `/root/.acme.sh`.  The default is `$HOME/.acme.sh/`)
