### ISSUE TITLE
port 80 is unavailable

### ISSUE THREAD

**Issue by helllkz** [Neilpang/acme.sh#1660]
For home use, port 80 is blocked by ISP, so the domain can't be verified and get this message.

xxx.xxx:Verify error:Fetching http://xxx.xxx/.well-known/acme-challenge/w08TPxFlNjuJf6SDn3aT8FLcVJOuYSigIUxk1RNk8-4: Timeout during connect (likely firewall problem)

I have tried specify a port by httpport=50080 which is nginx used and accessible from internet, but it still get the same error message.
acme.sh  --issue  -d example.com  -w /home/wwwroot --httpport 50080
acme.sh  --issue  -d example.com  -w /home/wwwroot --standalone --httpport 50080

Can I specify the port which is used to verifying?

**Comment by t4thfavor** [comment]
I have the same issue on the current version. I am able to open port 80, so this corrects the problem. The tutorial should be updated to reflect the need to open Port 80.

**Comment by hulkyhawk** [comment]
@t4thfavor  i encountered the same issure how to open the port
