### ISSUE TITLE
Documentation clarity

### ISSUE THREAD

**Issue by LTIOfficial** [Neilpang/acme.sh#1665]
Thanks a ton for your work on this, folks!

I hate to admit this, but I'm having trouble working out what I'm supposed to use for my domain in the --install command shown below, as I just issued a cert for both my primary domain, and the wildcard version of it, e.g. 
```acme.sh --force --issue --dns dns_gd -d domain.com -d *.domain.com.```

Should the command below use my domain with or without the '*', or maybe both should be listed?  Neither [documentation](https://github.com/Neilpang/acme.sh#3-install-the-cert-to-apachenginx-etc) [location](https://github.com/Neilpang/acme.sh/wiki/Deploy-ssl-certs-to-apache-server#12-run-acmesh) is clear about this, but it does warn to make sure we get it right because the info will be used during renewals (so I really want to get it right!).

```
acme.sh --install-cert -d online.domain.com \
--cert-file /etc/apache2/2.2/ssl/online.domain.com-cert.pem \
--key-file /etc/apache2/2.2/ssl/online.domain.com-key.pem \
--fullchain-file /etc/apache2/2.2/ssl/letsencrypt.pem \
--reloadcmd "systemctl restart httpd"
```

Note that in Centos 7, `systemctl restart httpd` performs a graceful restart of apache.      ;)

**Comment by Neilpang** [comment]
You should use the FIRST   `-d domain.com`.
