### ISSUE TITLE
Issuing certificate using webroot fails due to .htacess redirects

### ISSUE THREAD

**Issue by santerikannisto** [Neilpang/acme.sh#1666]
If there is a redirect in .htaccess, for example redirecting all traffic from http to https or adding www. to urls, issuing certificate may fail with redirects. To prevent this, acme.sh should add to .htaccess the following:

After
`RewriteEngine on`
The following would prevent redirecting cert auth request
`RewriteRule ^.well-known/ - [L,NC]`

This will prevent redirect failing the cert check.

**Comment by Neilpang** [comment]
letsencrypt should work well with redirecting.  there should be no problems.
please make sure.

And, it doesn't make any sense to write  apache specific code.  apache is not the only webserver in the world.

**Comment by santerikannisto** [comment]
I have had the issue with apache only. No idea about other webservers. You might want to have it documented at some point as I am pretty sure I am not the only one having those errors.

**Comment by Neilpang** [comment]
@santerikannisto 

there should be no problems with redirecting.   Letsencrypt CA can follow any redirecting.
