### ISSUE TITLE
How to issue a delete curl command

### ISSUE THREAD

**Issue by m-boone** [Neilpang/acme.sh#1671]
Hi,

I'm currently in the process of creating a dns provider for Leaseweb. It's almost finished. The last step requires a DELETE method to be sent to their server and I could not find how to do that with acme.sh provided functions. Could you add this function (or maybe as a parameter of the get function)?

http://developer.leaseweb.com/api-docs/domains_v2.html#delete-domainsexamplecomresourceRecordSetsexamplecomA

**Comment by baoang** [comment]
```
  count=$(printf "%s\n" "$response" | _egrep_o "\"count\":[^,]*" | cut -d : -f 2)
  _debug count "$count"
  if [ "$count" = "0" ]; then
    _info "Don't need to remove."
  else
    record_id=$(printf "%s\n" "$response" | _egrep_o "\"id\":\"[^\"]*\"" | cut -d : -f 2 | tr -d \" | head -n 1)
    _debug "record_id" "$record_id"
    if [ -z "$record_id" ]; then
      _err "Can not get record id to remove."
      return 1
    fi
    if ! _cf_rest DELETE "zones/$_domain_id/dns_records/$record_id"; then
      _err "Delete record error."
      return 1
    fi
    _contains "$response" '"success":true'
  fi
```
This is what part of CloudFlare's scripts look like. There is a `DELETE`.

So, my guess is, that function is provided by  Leaseweb API?

**Comment by m-boone** [comment]
Hi baoang,

Thank you for providing the code snippit! dns_cloudfare uses the dns_cloudfare _cf_rest() function which calls the acme.sh _post() method where you can indicate the http method. The _post() method only indicates [POST|PUT]  as valid parameters in it's comment but as CloudFare works okay I'll see if I can do the same.

Cheers.

**Comment by m-boone** [comment]
That worked. Thank you baoang.
