### ISSUE TITLE
Error with OVH Api 

### ISSUE THREAD

**Issue by Yfksw65** [Neilpang/acme.sh#1678]
root@vps:~/.acme.sh# ./acme.sh  --issue -d 'domain.fr' -d '*.domain.fr'  --dns dns_ovh --test --log
[Fri Jun 15 16:49:27 CEST 2018] Using stage ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Jun 15 16:49:28 CEST 2018] Multi domain='DNS:domain.fr,DNS:*.domain.fr'
[Fri Jun 15 16:49:28 CEST 2018] Getting domain auth token for each domain
[Fri Jun 15 16:49:29 CEST 2018] Getting webroot for domain='domain.fr'
[Fri Jun 15 16:49:29 CEST 2018] Getting webroot for domain='*.domain.fr'
[Fri Jun 15 16:49:30 CEST 2018] Found domain api file: /root/.acme.sh/dnsapi/dns_ovh.sh
[Fri Jun 15 16:49:30 CEST 2018] Using OVH endpoint: ovh-eu
[Fri Jun 15 16:49:30 CEST 2018] Checking authentication
[Fri Jun 15 16:49:30 CEST 2018] Consumer key is ok.
[Fri Jun 15 16:49:30 CEST 2018] Adding record
[Fri Jun 15 16:49:30 CEST 2018] Add txt record error.
[Fri Jun 15 16:49:30 CEST 2018] Error add txt for domain:_acme-challenge.domain.fr
[Fri Jun 15 16:49:30 CEST 2018] Please check log file for more details: /root/.acme.sh/acme.sh.log

**Comment by MAGICCC** [comment]
Post the log?

**Comment by Neilpang** [comment]
@Yfksw65   please paste the log with `--debug 2`

**Comment by Yfksw65** [comment]
I have resolved this problem with recreating an app on : https://eu.api.ovh.com/createApp/

It's ok now 

thank you
