### ISSUE TITLE
Webroot verify error

### ISSUE THREAD

**Issue by H4ndl3** [Neilpang/acme.sh#168]
I don't know what's wrong but the webroot authentication method isn't working for me. I try to get a cert for my domain by running
` acme.sh --issue -d domain.com -d www.domain.com -w /usr/local/www/challenges` and get the following output:
```
[Sun Apr 24 00:45:24 CEST 2016] Skip register account key
[Sun Apr 24 00:45:24 CEST 2016] Creating csr
[Sun Apr 24 00:45:24 CEST 2016] Multi domain='DNS:www.domain.com'
[Sun Apr 24 00:45:24 CEST 2016] Verify each domain
[Sun Apr 24 00:45:24 CEST 2016] Getting webroot for domain='domain.com'
[Sun Apr 24 00:45:24 CEST 2016] Getting token for domain='domain.com'
[Sun Apr 24 00:45:27 CEST 2016] Getting webroot for domain='www.domain.com'
[Sun Apr 24 00:45:27 CEST 2016] Getting token for domain='www.domain.com'
[Sun Apr 24 00:45:30 CEST 2016] Verifying:domain.com
[Sun Apr 24 00:45:38 CEST 2016] domain.com:Verify error:Invalid response from http://domain.com/.well-known/acme-challenge/xxxxxxxxxxxxxx [123.123.123.123]: 404
```
`/usr/local/www/challenges` is a separate folder I created for serving the acme-challenges. My nginx config includes the following snippet to catch the acme requests:
```
location ^~ /.well-known/acme-challenge/ {
	default_type "text/plain";
	root /usr/local/www/challenges;
}

location = /.well-known/acme-challenge/ {
	try_files $uri =404;
}
```
I confirmed that it is working by creating the text file `/usr/local/www/challenges/.well-known/acme-challenge/ping.txt` and visiting `http://domain.com/.well-known/acme-challenge/ping.txt`. The content of the file was then correctly displayed.

I'm using FreeBSD 10.3-RELEASE.

**Comment by Neilpang** [comment]
`-w`  specifies the  web root folder,   not the challenge root folder.

For example, if you use `-w   /home/www`, then the challenge will be placed at :
```
/home/www/.well-known/acme-challenge/
```

Please remove  ` root /usr/local/www/challenges;` and use the correct web root as `-w`.

**Comment by H4ndl3** [comment]
I removed the line `root /usr/local/www/challenges;` from the nginx snippet and used the correct web root for the domain with `-w /usr/local/www/domain.com`. I tested the config again by opening `http://domain.com/.well-known/acme-challenge/ping.txt` which works, however the problem is still the same:`Verify error:Invalid response`. Access rights of `/usr/local/www/domain.com` are `755`. No folder  `.well-known/acme-challenge` is being created in `/usr/local/www/domain.com`, is it created and deleted while running the script or is that wrong behavior?

**Comment by Neilpang** [comment]
Yes,  the folder will be remove on success or on error.

Please try again with `--debug  2`

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by H4ndl3** [comment]
I think I found the problem: 
```
[Sun Apr 24 12:07:12 CEST 2016] _currentRoot='/usr/local/www/domain.com'
[Sun Apr 24 12:07:12 CEST 2016] wellknown_path='/usr/local/www/domain.com/.well-known/acme-challenge'
[Sun Apr 24 12:07:12 CEST 2016] writing token:-n xxxxxxxxxxxxxxxx to /usr/local/www/domain.com/.well-known/acme-challenge/-n xxxxxxxxxxxxxxxx
```
```
root@localhost:/usr/local/www/domain.com # cd .well-known/acme-challenge/ ; ls
-n xxxxxxxxxxxxxxxx
```
It seems that the challenge is written to the folder with a leading `-n` and a space after that, followed by the actual challenge.
I guess that my original config should work too when this bug is fixed.

**Comment by Neilpang** [comment]
fixed  ac0a1661f3c3f14fde76d41000734a3cb4bc5acf

Please uninstall and re-install again.

**Comment by H4ndl3** [comment]
Thanks for the fast fix! :+1: Now it's working with my original command and config too.

**Comment by vladkras** [comment]
my problem was solved by adding
```
        location ~ /.well-known/acme-challenge {
            allow all;
        }
```
to /etc/nginx/conf.d/mydomain.com
