### ISSUE TITLE
Problem with wildcard domain and manual dns update mode

### ISSUE THREAD

**Issue by ygator** [Neilpang/acme.sh#1684]
I have been using this for 8 or so sub-domains and wanted to switch to a wildcard instead.  Looking around I see the command would be:
`acme.sh --issue --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please -d domain.com -d *.domain.com `
However, when I did this the manual TXT records it wanted me to add were both the same: _acme-challenge.domain.com
So I figured the command was wrong so I tried again without the -d domain.com
However, I find out that the *.domain.com does not cover domain.com.
So it looks like there might be an issue with manual dns and wild cards.  Either that or I don't know what I am doing.

Thanks

**Comment by ygator** [comment]
I ended up running it again and it gave me only one TXT this time to add.  However, it said it did not match and I double checked that it was correct.  So I ran it one more time and it gave me a single TXT to add again and this time everything worked as it was suppose to.  I'll close this issue in a day or so in case anyone else has seen this behavior.

**Comment by FernandoMiguel** [comment]
Please don't use DNS01 in manual mode. 
It's there for debug purposes. 
With let's encrypt, we want automation all the time, and manual mode will not renew the cert for you. 
Try to find a DNS provider with a supported API. 

that said, per RFC a wildcard does not include the naked domain, so you always need both. 
The validation token is usually the same for both records
