### ISSUE TITLE
How soon before a cert is renewable via cron check?

### ISSUE THREAD

**Issue by sergeifilippov** [Neilpang/acme.sh#1685]
When running acme.sh in cron mode, how soon before a renewal is triggered?

Is it 30 days before cert expiry or some other number.

I could not see it in the docs.

**Comment by FernandoMiguel** [comment]
by default the cron will check every week, if i'm not mistaken.
by day 60 it will try to renew it if it can

**Comment by sergeifilippov** [comment]
Thanks @FernandoMiguel.

**Comment by Neilpang** [comment]
@FernandoMiguel 
The default cronjob checks the certs every day.
And yes, the cert will be renewed at the 60th day.
