### ISSUE TITLE
非 root 用户的 cron 任务问题

### ISSUE THREAD

**Issue by xinx1n** [Neilpang/acme.sh#1688]
当安装用户为非 root 用户，而 nginx 存放 证书的目录需要 sudo 才能拷贝进去，
acme.sh 自动生成的 cron 任务却没有 sudo，需要 crontab -e 去更改任务才能保证更新，
是否应该 acme.sh 自己生成任务时自己添加 sudo

**Comment by Neilpang** [comment]
sudo 并非 unix 标准.  很多系统上也没有.
正确的做法是 尽量不要使用需要sudo 的命令.  如果无法避免, 应该通过设置,让这个命令或者文件 不在需要 sudo 权限.

比如这里说到的: https://ruby-china.org/topics/31983
