### ISSUE TITLE
Messed up webroot of Webserver - what to do?

### ISSUE THREAD

**Issue by peter-schaefer** [Neilpang/acme.sh#1695]
I had to change the webroot of my webserver from /www/old to /www/new. The configuration for the webserver is under /etc/webserver/Includes

Now acme.sh always gets the wrong webroot.

How can I change the configuration for the certificate to use the new webroot?

Sorry if it is a dumb question, but I am stuck.

best regards

**Comment by FernandoMiguel** [comment]
have you reloaded your nginx service?

**Comment by peter-schaefer** [comment]
It's an apache and i reloaded it, after changing the webroot, so it's  up and running.

**Comment by Neilpang** [comment]
you can issue a new cert with the same domain name and the new webroot.

**Comment by peter-schaefer** [comment]
simple as that?

Ok, I am on a FreeBSD 11 system, so using apache there is /usr/local/www/apache24/data as the default webroot, but I use a virtual host under /usr/local/www/vhost-default.
/usr/local/www/apache24/data is owned by  root:wheel
/usr/local/www/vhost-default is owned by  vhost-user:vhost-group

Running acme.sh as root or as acme, I can't use -w /usr/local/www/vhost-default as none of them can write the token under /usr/local/www/vhost-default/.well-known, even if I put acme in groups, that can write. I can write directly with su/sudo under the webroot, but runnijg acme.sh can't.
acme.sh can write -w /usr/local/www/apache24/data/.well-known and i can put a link to .../vhost-default/.well-known so that getting a new certificate is possible.

**Comment by peter-schaefer** [comment]
Now I want to renew by crojob and I am using:
/usr/local/sbin/acme.sh --cron --home /var/db/acme/.acme.sh --reloadcmd "service apache24 reload"
but it doesn't use "service apache24 reload" instead it goes for "Run reload cmd: service apache24 force reload"
                                                                        
Which gives me:
/usr/local/etc/rc.d/apache24: extra argument ignored                     
Usage: /usr/local/etc/rc.d/apache24 [fast|force|one|quiet](start|stop|restart|rcvar|enabled|describe|extracommands|reload|graceful|gracefulstop|config

but can't reload the server.

Why is that?

**Comment by Neilpang** [comment]
forcereload was removed in the new apache version.
you can use reload instead.
