### ISSUE TITLE
为什么生成的证书里面颁布给的域名是sni224088.cloudflaressl.com

### ISSUE THREAD

**Issue by figo930** [Neilpang/acme.sh#1696]
使用者可选名字里面好多
DNS Name=sni224088.cloudflaressl.com
DNS Name=*.466wyzcnet.cf
DNS Name=*.au-tv.com
DNS Name=*.ayyubi.ga
DNS Name=*.barcelonaprivatetours.org
DNS Name=*.bellydancingbyannette.com
DNS Name=*.btenutrition.com
DNS Name=*.cleantr8ck.com
DNS Name=*.cpwynuytkl.ml
DNS Name=*.eurekadj.com
DNS Name=*.events-portugal.com
DNS Name=*.fatimaprivatetours.com
DNS Name=*.glenlakeartistsgallery.com
DNS Name=*.help-file.info
DNS Name=*.hotmoza.tv
DNS Name=*.humboldtconnects.com
DNS Name=*.ignahces.cf
DNS Name=*.iniblogsaya.info
DNS Name=*.knutsonjewelers.net
DNS Name=*.lisbon-tours.net
DNS Name=*.lisboncruiseport.com
DNS Name=*.lisbonguide.org
DNS Name=*.luivednss.tk
DNS Name=*.n2brews.com
DNS Name=*.nursaylatur.ga
DNS Name=*.pvowwowss.ga
DNS Name=*.rickyrosss.gq
DNS Name=*.ru-tv.com
DNS Name=*.shoretours.org
DNS Name=*.sintra-lisbon-tourguide.com
DNS Name=*.sintra-magik.com
DNS Name=*.tqifrols.cf
DNS Name=*.travel-blogger.net
DNS Name=*.travel-lisbon.com
DNS Name=*.trentbthompson.com
DNS Name=*.tw-tv.net
DNS Name=*.xxxtuboitaliano.webcam
DNS Name=466wyzcnet.cf
DNS Name=ailingyi.com
DNS Name=au-tv.com
DNS Name=ayyubi.ga
DNS Name=barcelonaprivatetours.org
DNS Name=bellydancingbyannette.com
DNS Name=btenutrition.com
DNS Name=cleantr8ck.com
DNS Name=cpwynuytkl.ml
DNS Name=eurekadj.com
DNS Name=events-portugal.com
DNS Name=fatimaprivatetours.com
DNS Name=glenlakeartistsgallery.com
DNS Name=help-file.info
DNS Name=hotmoza.tv
DNS Name=humboldtconnects.com
DNS Name=ignahces.cf
DNS Name=iniblogsaya.info
DNS Name=knutsonjewelers.net
DNS Name=lisbon-tours.net
DNS Name=lisboncruiseport.com
DNS Name=lisbonguide.org
DNS Name=luivednss.tk
DNS Name=n2brews.com
DNS Name=nursaylatur.ga
DNS Name=pvowwowss.ga
DNS Name=rickyrosss.gq
DNS Name=ru-tv.com
DNS Name=shoretours.org
DNS Name=sintra-lisbon-tourguide.com
DNS Name=sintra-magik.com
DNS Name=tqifrols.cf
DNS Name=travel-blogger.net
DNS Name=travel-lisbon.com
DNS Name=trentbthompson.com
DNS Name=tw-tv.net
DNS Name=xxxtuboitaliano.webcam

**Comment by Neilpang** [comment]
你这是  cloudflare 的免费证书,  再后台关掉 cf 的代理.
