### ISSUE TITLE
How to check if Cron will do what its supposed?

### ISSUE THREAD

**Issue by tilllt** [Neilpang/acme.sh#1699]
Hey,

i successfully installed acme.sh, issued letsencrypt certificates and installed them to their appropriate locations, nginx likes them, so everything looks good. While i totally appreciate that acme.sh takes care of creating a cronjob etc, i'd really like to check if its working as supposed to. do i just execute the same command added as a cron job and see what happens or is there a better way?

cheers.

**Comment by FernandoMiguel** [comment]
acme.sh --cron --force

**Comment by Neilpang** [comment]
>> do i just execute the same command added as a cron job and see what happens or is there a better way?

Yes,  you can run the cron command  tomorrow or later.

```sh
acme.sh --cron --force
```

**Comment by FernandoMiguel** [comment]
AH!

**Comment by tilllt** [comment]
Thanks guys!
