### ISSUE TITLE
.photos的域名不支持

### ISSUE THREAD

**Issue by uuair** [Neilpang/acme.sh#1701]
acme.sh  --installcert  -d  www.12345.photos
显示：
Domain is not valid:'www.12345.photos'

**Comment by FernandoMiguel** [comment]
https://dnssec-debugger.verisignlabs.com/12345.photos
> Zone photos (2001:dcd:1::7) returns NXDOMAIN for 12345.photos

**Comment by Neilpang** [comment]
为啥不读一下中文说明? 
https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E

你不先生成一个证书, 光 install 个啥?
