### ISSUE TITLE
建议把安装目录移动到 /etc/

### ISSUE THREAD

**Issue by gclove** [Neilpang/acme.sh#1707]
在 selinux 下，nginx 用户无法读取 /root/.acme.sh 目录的内容

**Comment by Neilpang** [comment]
就没打算让你读这下面的文件.  为什么不读一遍中文说明呢 ?
https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E

用 `--install-cert` 把 证书文件拷贝到 nginx 能读的位置.
