### ISSUE TITLE
Missing .acme.sh/deploy/ directory

### ISSUE THREAD

**Issue by gl-Hub** [Neilpang/acme.sh#1711]
Hello, 

I’ve installed Acme.sh using

```
curl -LO https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh
chmod +x acme.sh
./acme.sh --install –nocron
```

but I see that the **~/.acme.sh/deploy/** directory with its content was not created.

Any explanation?

PS: I need the **~/.acme.sh/deploy/cpanel_uapi.sh** to add this line

`export DEPLOY_CPANEL_USER=12345678`

and deploy a certificate with cPanel uapi.

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/How-to-install
