### ISSUE TITLE
DNS manual verification duplicate TXT records

### ISSUE THREAD

**Issue by ShepardEG** [Neilpang/acme.sh#1719]
Steps to reproduce
------------------
I want to create wildcard to my domain and his subdomains, but acme want add two different txt records with same name. Domains names was changed by me, sorry. 
Log
-----------------
[Mon Jul  9 12:25:35 MSK 2018] Multi domain='DNS:test.stopping-me.trigger.life,DNS:*.test.stopping-me.trigger.life'
[Mon Jul  9 12:25:35 MSK 2018] Getting domain auth token for each domain
[Mon Jul  9 12:25:37 MSK 2018] Getting webroot for domain='test.stopping-me.trigger.life'
[Mon Jul  9 12:25:37 MSK 2018] Getting webroot for domain='*.test.stopping-me.trigger.life'
[Mon Jul  9 12:25:37 MSK 2018] Add the following TXT record:
[Mon Jul  9 12:25:37 MSK 2018] Domain: '_acme-challenge.test.stopping-me.trigger.life'
[Mon Jul  9 12:25:37 MSK 2018] TXT value: 'CKjBC0ex-Zpg_Z47vqV8kPmmapiDh_f-7-dxGfZHn00'
[Mon Jul  9 12:25:37 MSK 2018] Please be aware that you prepend _acme-challenge. before your domain
[Mon Jul  9 12:25:37 MSK 2018] so the resulting subdomain will be: _acme-challenge.test.stopping-me.trigger.life
[Mon Jul  9 12:25:37 MSK 2018] Add the following TXT record:
[Mon Jul  9 12:25:37 MSK 2018] Domain: '_acme-challenge.test.stopping-me.trigger.life'
[Mon Jul  9 12:25:37 MSK 2018] TXT value: '6riVyZIM_hPFL5TX76lZisyVXcF96Mlw3eEMoYOGh5Y'
[Mon Jul  9 12:25:37 MSK 2018] Please be aware that you prepend _acme-challenge. before your domain
[Mon Jul  9 12:25:37 MSK 2018] so the resulting subdomain will be: _acme-challenge.ssr.test.stopping-me.trigger.life
[Mon Jul  9 12:25:37 MSK 2018] Please add the TXT records to the domains, and re-run with --renew.
[Mon Jul  9 12:25:37 MSK 2018] Please add '--debug' or '--log' to check more details.
[Mon Jul  9 12:25:37 MSK 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

```
./acme.sh --issue --dns -d test.stopping-me.trigger.life  -d *.test.stopping-me.trigger.life  --yes-I-know-dns-manual-mode-enough-go-ahead-please

```

**Comment by initit** [comment]
Hi,

please have a Look at [https://github.com/Neilpang/acme.sh/issues/1261](https://github.com/Neilpang/acme.sh/issues/1261)
Requesting wildcard certificates requires two TXT Records.

**Comment by ShepardEG** [comment]
Close it, my fault. I was think txt names need to be with one name and not same.
