### ISSUE TITLE
feature: please keep cert dir and filename compatibility with certbot

### ISSUE THREAD

**Issue by wowcut** [Neilpang/acme.sh#1724]
There are many different tools and scripts that are working with certbot, also admins will have some custom scripts that are expecting certbot directory structure and file naming. 

It would be really helpful and much easier to replace existing tools and workflows with acme.sh, if you would keep the domain directories and cert files created compatible with the way certbot does it. Please make the directories and filenames exactly like certbot, do not reinvent the wheel. Meta and config info that is needed for acme.sh should go in a different directory. 

Thanks!

**Comment by Neilpang** [comment]
sorry,  it's never our goal to keep compatibility  with certbot.
If you have problem with the file content ,  let's fix it for you case by case.
