### ISSUE TITLE
Update usage info for secp521r1

### ISSUE THREAD

**Issue by finlandiaG** [Neilpang/acme.sh#173]
Now that EC secp521r1 is supported, please update the usage info accordingly, ie. change

--keylength, -k [2048]            Specifies the domain key length: 2048, 3072, 4096, 8192 or ec-256, ec-384.

to 

--keylength, -k [2048]            Specifies the domain key length: 2048, 3072, 4096, 8192 or ec-256, ec-384, ec-521.

**Comment by Neilpang** [comment]
```
Invalid key in certificate request :: ECDSA curve P-521 not allowed
```
