### ISSUE TITLE
cant update dns on yandex.dns

### ISSUE THREAD

**Issue by spions** [Neilpang/acme.sh#1739]
Yandex started migration service DNS on "pdd" from "connect".
From the console I shows error "migrated_to_connect".

```
[Wed Jul 18 17:51:45 MSK 2018] _post_url='https://pddimp.yandex.ru/api2/admin/dns/add'
[Wed Jul 18 17:51:45 MSK 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed Jul 18 17:51:46 MSK 2018] _ret='0'
[Wed Jul 18 17:51:46 MSK 2018] Result: {"domain": "domain.ru", "success": "error", "error": "migrated_to_connect"}
[Wed Jul 18 17:51:46 MSK 2018] Sleep 120 seconds for the txt records to take effect
```

**Comment by dmitrykorobeynikov** [comment]
Does anyone know where I can find documentation for Yandex.Connect API for needed functions?

**Comment by aburuss** [comment]
Alas, the "Домены" section does not contain api for editing records:

https://tech.yandex.ru/connect/directory/api/about-docpage/

**Comment by ODware** [comment]
As I can see, DELETE method exists in api (link above)

**Comment by nstepa** [comment]
This is not an issue anymore: yandex.Connect supports old API.
