### ISSUE TITLE
No longer able to run under root with nginx

### ISSUE THREAD

**Issue by 4lun** [Neilpang/acme.sh#174]
No longer able to run under root in combination with nginx (running under `www-data`) on Ubuntu.

Cause is the recently added umask which restricts read permissions to just the owner, `.well-known` will  now return a 403 error: https://github.com/Neilpang/acme.sh/commit/bfdf1f482e0b012f0be88f271d1fe1fe37947ec1

Example of how I usually run it:
`acme.sh --issue -d example.org -w /var/www/example.org/public`

**Comment by heldchen** [comment]
also fails for me now due to the recent umask changes. this probably should be a configurable option.

**Comment by Neilpang** [comment]
@heldchen 

fixed  762978f8d8a7fcc7308e4b8c6e5b1cf3747014e6

**Comment by heldchen** [comment]
thanks alot!
