### ISSUE TITLE
installcert

### ISSUE THREAD

**Issue by liuxyon** [Neilpang/acme.sh#175]
这个命令是怎么用的？ 如何安装在IIS8.5上?

$ acme.sh --installcert -d AutoDiscover.god.org
[2016年04月27日 11:28:18] Run Le_ReloadCmd: no
/home/yon/.acme.sh/acme.sh:行1623: no: 未找到命令

**Comment by guigeng** [comment]
我用nginx来做反向代理，后端是IIS。可以实现https
