### ISSUE TITLE
DNS Manual mode - get TEXT record value

### ISSUE THREAD

**Issue by Marcin666** [Neilpang/acme.sh#1767]
Hello,
Is there a proper way of getting RAW TXT value for DNS manual mode challenge?

What is have to do - no DNS API, old machine needs to be automated. I can use sed to replace TXT record in zone file and hit NameD restart but need to get this value from acme.sh to pass it further.

Checked options in acme.sh but TXT value is nowhere to be extracted normally.

Any clues?

**Comment by Neilpang** [comment]
You can use a custom dns api:
https://github.com/Neilpang/acme.sh/tree/master/dnsapi#use-custom-api

**Comment by ehprivacy** [comment]
You can also grab the TXT record from the sdtout output of acme.sh in dns manual mode.  (I'm having to do this for automation, as my dns API requires client certificates which the current dns api framework doesn't seem to support).  

My script:
` acme.sh --staging --issue $acme_domain_list --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please 2>&1 | grep -A1 "Domain: '" | cut -d"'" -f2 | sed 's/--//g'`
