### ISSUE TITLE
Question related to multiple domains and API

### ISSUE THREAD

**Issue by pedrom34** [Neilpang/acme.sh#1774]
Hi,
I'm sorry to create an issue for a question, but I'm a bit lost... I'm using acme.sh with OVH API for a wildcard domain. I then use the cert in Nginx.
  
I want to add another wildcard domain for DuckDNS. How am I supposed to do that?
  
```shell
acme.sh --issue --dns dns_ovh -d *.domain.ovh -d domain.ovh  --issue --dns dns_duckdns -d mydomain.duckdns.org -d *.mydomain.duckdns.org
```
  
or
  
```shell
acme.sh --issue --dns dns_ovh -d *.domain.ovh -d domain.ovh --dns dns_duckdns -d mydomain.duckdns.org -d *.mydomain.duckdns.org
```
  
or else
  
```shell
acme.sh --issue --dns dns_ovh -d *.domain.ovh -d domain.ovh && acme.sh --issue --dns dns_duckdns -d mydomain.duckdns.org -d *.mydomain.duckdns.org
```
?  
  
Same question for issuing the cert for nginx... Should I do:
```shell
acme.sh --install-cert -d *.domain.ovh -d domain.ovh -d *.mydomain.duckdns.org -d mydomain.duckdns.org \
--key-file       /opt/etc/nginx/cert.key  \
--fullchain-file /opt/etc/nginx/cert.crt \
--reloadcmd     "nginx -s reload"
```
  
or
  
```shell
acme.sh --install-cert -d *.domain.ovh -d domain.ovh \
--key-file       /opt/etc/nginx/ovhcert.key  \
--fullchain-file /opt/etc/nginx/ovhcert.crt \
--reloadcmd     "nginx -s reload"

&&

acme.sh --install-cert -d *.mydomain.duckdns.org -d mydomain.duckdns.org \
--key-file       /opt/etc/nginx/duckcert.key  \
--fullchain-file /opt/etc/nginx/duckcert.crt \
--reloadcmd     "nginx -s reload"
```

**Comment by baoang** [comment]
没猜错意思的话，是说如何在一条命令中同时申请或处理两个DNS验证方式的域名？
我当初是先申请了一个证书，后来又有一个新域名，再走了一次命令申请了新域名的证书。
不过我猜，&&或可以用&吧。

不知道acme.sh如何能够从几个域名中增加、删除或暂停其中某个或某几个域名的证书更新。

**Comment by laszlof** [comment]
According to google translate, they said that you should probably use 2 commands to reissue the certs. I dont think you can specific multiple providers with 1 command.

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert#3-multiple-domains-san-mode--hybrid-mode

**Comment by pedrom34** [comment]
Thanks!
