### ISSUE TITLE
Feature request: auto detect challenge domain alias

### ISSUE THREAD

**Issue by gzm55** [Neilpang/acme.sh#1784]
Hi,

If not called with --{challenge,domain}-alias parameter, can we auto detect the real challenge domain by some dig commands, such as `dig @1.1.1.1 cert-domain CNAME`. By enable the DNSSEC and DNS-over-TLS, we can have the trusted results and link.

**Comment by Neilpang** [comment]
自动检测太复杂.
主要原因是跨平台的 dig 工具不好统一.  这样会增加 acme.sh 的依赖项.

如果你知道要用 alias, 你就显式的调用 alias 就好了.
