### ISSUE TITLE
Google CloudDNS Integration

### ISSUE THREAD

**Issue by Gunni** [Neilpang/acme.sh#180]
CloudDNS is a cheap DNS hosting solution with a 100% uptime SLA and provided by Google.

https://cloud.google.com/dns/api/v1/

**Comment by Neilpang** [comment]
Is it free?

**Comment by Gunni** [comment]
Free, no, cheap, yes https://cloud.google.com/dns/pricing

**Comment by vaivars** [comment]
Its also free if you use the google domains service

**Comment by paulchabotca** [comment]
This would be a great addition. I use the dns for my own sites (3, very little traffic) every 6 months or so I need to pay them 80 cents or so... I have a client with a few hundred domains and its not much more expensive. I will take a stab at adding this option to the code today.

**Comment by thejaswip** [comment]
I would think the best way to use this would be to build the wrapper around the google's gcloud tool rather than implement the API access to google cloud dns

**Comment by Gunni** [comment]
Abandoning ticket.
