### ISSUE TITLE
代码取得时间跟证书记录的时间有差异

### ISSUE THREAD

**Issue by linux0x5c** [Neilpang/acme.sh#1803]
[root@pinpoint-zookeeper-1 file.echemi.com]# openssl x509 -in file.echemi.com.cer  -startdate -noout
notBefore=Aug 15 08:48:40 2018 GMT
[root@pinpoint-zookeeper-1 file.echemi.com]# grep "Le_CertCreateTime" file.echemi.com.conf 
Le_CertCreateTime='1534326521'
Le_CertCreateTimeStr='Wed Aug 15 09:48:41 UTC 2018'

有时候差一秒，有时候不差，这是什么原因？

**Comment by Neilpang** [comment]
这个时间并非 是 startdate .

只是证书生成的时间.
