### ISSUE TITLE
i use cloudflare dns on ubuntu/nginx server. how do i know when the renewal takes place?

### ISSUE THREAD

**Issue by simkimsia** [Neilpang/acme.sh#1809]
i successfully issue using the dns mode for cloudflare and install on nginx.

the SSL cert works perfectly.

How do I know when the auto renewal takes place? and how long is the typical renewal period?

**Comment by Neilpang** [comment]
```sh
acme.sh  --list
```

**Comment by simkimsia** [comment]
Thanks @Neilpang
