### ISSUE TITLE
Is install cert included in the crontab?

### ISSUE THREAD

**Issue by EdanPyx** [Neilpang/acme.sh#181]
I used acme.sh as root so my web server is unable to access the cert location, so I had to use --installcert.

Does the --installcert command save the settings in the crontab? There should be documentation saying whether or not it does.

**Comment by Neilpang** [comment]
yes,  if the `--installcert`  is success.  all the settings are saved.  So, when the cert is renewed, it will be automatically installed.  You don't need to care about it again.

**Comment by EdanPyx** [comment]
Ok thanks. You should say that in the documentation though.

How does this work when you have multiple certs like a.com b.com? Do you need to run installcert twice and do they both get saved?
