### ISSUE TITLE
I ran install-cert twice for the same domain. How do I clean up?

### ISSUE THREAD

**Issue by simkimsia** [Neilpang/acme.sh#1815]
when I type `acme.sh --list` I get

```
Main_Domain   KeyLength  SAN_Domains     Created                       Renew
reconpdf.com  ""         *.reconpdf.com  Tue Aug 21 06:15:57 UTC 2018  Sat Oct 20 06:15:57 UTC 2018
reconpdf.com  "ec-384"   *.reconpdf.com  Tue Aug 21 12:40:28 UTC 2018  Sat Oct 20 12:40:28 UTC 2018
```

When i installed, I had two folders  under `~/.acme.sh`

`reconpdf.com` which contains the original cert that was not using `ecc`
`reconpdf.com_ecc` which contains the cert that's using `ecc`

So how do I need to undo/remove the RSA cert issue and installation? I want to use the one that's using the ecc cert. 

Thank you

**Comment by FernandoMiguel** [comment]
they are different certs.
one is RSA and the the other EC

**Comment by simkimsia** [comment]
I understand that they are different. So how do I undo/remove the RSA cert?

**Comment by simkimsia** [comment]
Oh I see. Thanks
