### ISSUE TITLE
working directory not remembered

### ISSUE THREAD

**Issue by alnixon** [Neilpang/acme.sh#182]
I don't know why the current approach isn't working for me but after installing to a custom working directory this isn't remembered.

I managed to work around this by effectively changing the acme.sh.env to pass in the directory
e.g.

_setopt "$_envfile" "alias $PROJECT_ENTRY" "=" "\"$LE_WORKING_DIR/$PROJECT_ENTRY --home $LE_WORKING_DIR \"

**Comment by Neilpang** [comment]
fixed    1786a5e55a4cd2e96aee56ccd1a4a568c4356f83
