### ISSUE TITLE
acme.sh with dns_pdns does not update serial

### ISSUE THREAD

**Issue by jahlives** [Neilpang/acme.sh#1825]
Pretty sure the root cause for this issue is somewhere in pdns. Problem is that although `dns_pdns` did insert the challenge records into my pdns, the serial number was not updated, therefore my slaves did not see any update which finally let acme.sh fail as the records could not be found on my public dns servers. 

I setup the [SOA-EDIT](https://doc.powerdns.com/authoritative/domainmetadata.html#soa-edit-api) of pdns and manually inserted records (directly to the mysql db) do increment the SOA serial properly. Just via API, as acme.sh does, the serial was never updated. After some tests I found that ```pdnsutil increase-serial MYDOMAIN``` does increase the serial as expected.

So to solve the "issue" on my side I just added ```pdnsutil increase-serial $root``` to the `notify_slaves()` in `dnsapi/dns_pdns.sh` After that it worked like charm

**Comment by jahlives** [comment]
Just as update: the pdnsutil call is not necessary if one configures SOA-EDIT correctly :-) SOA-EDIT knows API updates and normal DNSUPDATE. So both have to be set per domain in `domainmetadata` table in order for automatically changes of SOA serials:
```
insert into domainmetadata (domain_id,kind,content) values(id, 'SOA-EDIT-DNSUPDATE','INCEPTION-INCREMENT');
insert into domainmetadata (domain_id,kind,content) values(id, 'SOA-EDIT-API','INCEPTION-INCREMENT')
```

**Comment by gnanet** [comment]
If ALL such meta rows are missing this 2liner helps quickly:

```
INSERT INTO `domainmetadata` (domain_id,kind,content) SELECT id as domain_id, 'SOA-EDIT-DNSUPDATE' as kind, 'INCEPTION-INCREMENT' as content FROM `domains`;
INSERT INTO `domainmetadata` (domain_id,kind,content) SELECT id as domain_id, 'SOA-EDIT-API' as kind, 'INCEPTION-INCREMENT' as content FROM `domains`;

```
