### ISSUE TITLE
Persist _reloadcmd for cron

### ISSUE THREAD

**Issue by alnixon** [Neilpang/acme.sh#183]
From what I can tell the cron job will not know about any reload cmd previously used.
It would be great to persist this in the same way as _useragent; perhaps as part of the install.

**Comment by Neilpang** [comment]
I just tried again.  the reloadcmd is working as expected for cron.
It's persisted in the domain conf file:  `~/.amce.sh/domain.com/domain.com.conf`.
Please  retry and make sure.

**Comment by alnixon** [comment]
I'm all set now, thanks.  I hadn't passed it as part of the issue.
If I get chance I'll contribute to the readme.md to help avoid others making my mistake.

**Comment by Neilpang** [comment]
Sorry,
The `reloadcmd` is only valid for `issue` or `installcert` call.
