### ISSUE TITLE
Wrong error code after "Verify error:Invalid response"

### ISSUE THREAD

**Issue by washek** [Neilpang/acme.sh#185]
Hi,

acme.sh returns code "0" (which I interpret as "ok" or "without error") even if there is error during validation:

[Mon May  9 16:37:02 CEST 2016] Skip register account key
[Mon May  9 16:37:02 CEST 2016] Creating csr
[Mon May  9 16:37:02 CEST 2016] Single domain='x.cz'
[Mon May  9 16:37:02 CEST 2016] Verify each domain
[Mon May  9 16:37:02 CEST 2016] Getting webroot for domain='x.cz'
[Mon May  9 16:37:02 CEST 2016] Getting token for domain='x.cz'
[Mon May  9 16:37:04 CEST 2016] Verifying:x.cz
[Mon May  9 16:37:11 CEST 2016] x.cz:Verify error:Invalid response from http://x.cz/.well-known/acme-challenge/FWlHzXal8g7Wtz5fBlNz9RVJ79Io0ATqe0e0qmMkj4s [1.2.3.46]: 404
[.acme.sh]# echo $?
0

I believe that this is a bug and it would be great if you can fix it. Thanks!

**Comment by Neilpang** [comment]
fixed :  d3595686f6df3ec4de63718e7c1c2df9efcf3dca

Please retry.

**Comment by washek** [comment]
Now it's working as expected. Thanks for a quick fix!
