### ISSUE TITLE
Question: Do the --remove, --install-cert and --renew commands expect all domains listed or just the first / main one?

### ISSUE THREAD

**Issue by nickjj** [Neilpang/acme.sh#1856]
Hi,

Example: let's say you `--issue`'d a certificate with `-d example.com -d www.example.com -d hello.example.com` which will produce `~/acme.sh/example.com`.

When it comes to `--remove`, `--install-cert` and `--renew` do I need to pass in:

`-d example.com -d www.example.com -d hello.example.com`
or just`-d example.com`?

I couldn't find this in the documentation.

Also (sorry for the multi-topic issue but it is semi-related) when it comes to `--force`, is this meant to only be applied to (`--issue` and `--renew`) OR (`--install-cert` and `--renew`) OR (`--renew`)? I saw in a previous closed issue that this one only expects you to pass in `-d example.com` (instead of the all of the domains).

**Comment by baoang** [comment]
When you issue the cert, your config will be recorded into the conf file. When you renew or install the cert, the config will automatically be extracted from the conf file.

**Comment by nickjj** [comment]
@baoang thanks, so you're saying for renew and install I just need to pass in -d example.com (not even things like --dns)? What about remove?

**Comment by baoang** [comment]
Hi, @nickjj 

In my situation, *renew* and *install* are automatically executed via crond, which is set when you install acme.sh and issue certs for the first time.

You will find in your conf file, say mydomain.tld.conf, a bunch of commands relevant to cert installation. Here you'll see several lines like this:
```
...
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath='/path/to/mydomain.tld.key'
Le_RealFullChainPath='/path/to/fullchain.cer'
Le_ReloadCmd='service nginx restart'
```
Also, you can locate spots from acme.sh.log where certs were renewed.

From these sections, you'll see once issuing is complete and successful, renewing and installing are not a problem. You don't have to worry about it. No need to pass variables or adjust scripts or something. Acme.sh will do almost everything for you.

**Comment by nickjj** [comment]
Thanks.
