### ISSUE TITLE
Cant issue an Cert "Is a directory"

### ISSUE THREAD

**Issue by ReptoxX** [Neilpang/acme.sh#186]
I can´t issue a cert.
I always get this message..

`acme.sh --issue --apache -d xxx.de`

> /root/.acme.sh/acme.sh: line 1367: /home/.acme/: Is a directory
> wget: missing URL
> Usage: wget [OPTION]... [URL]...
> Try `wget --help' for more options.

Thanks for any help
ReptoxX

**Comment by Neilpang** [comment]
what is you os?

**Comment by Neilpang** [comment]
Please add  "--debug 2",  and paste the log here

**Comment by ReptoxX** [comment]
This Server is running Debian 7.
Is there a log file or do i need to copy this?

**Comment by Neilpang** [comment]
no log file.  just copy.

**Comment by ReptoxX** [comment]
Okay, btw. this could be an improvement.

[log.txt](https://github.com/Neilpang/acme.sh/files/263287/log.txt)

**Comment by Neilpang** [comment]
Please try again with the latest code.

**Comment by ReptoxX** [comment]
Okay i tried, now i get "Error, can not get domain token"

**Comment by Neilpang** [comment]
what is your wget version?

Is it possible for you to install curl ?

**Comment by ReptoxX** [comment]
the newest, i checked for updates before i open an issue.
No problem: with curl i get this error

> new-authz error: {"type":"urn:acme:error:unauthorized","detail":"No registration exists matching provided key","status":403}

**Comment by Neilpang** [comment]
please uninstall and remove "~/.acme.sh" folder.  Then install and try again with curl.

**Comment by ReptoxX** [comment]
Okay now it works!
Thank You, you helped me 3 times now, you are amazing.

**Comment by Neilpang** [comment]
You are welcome.  And I reproduced your issue on my debian 7 vm with wget.  I'm fixing it.

Thanks.

**Comment by ReptoxX** [comment]
Thanks. I believe you fix it fast, i trust in you :)

**Comment by Neilpang** [comment]
It seems that wget on debin 7 is  `Wget 1.13.4`, which doesn't support "--method"  parameter.
I'm fixing it now.

**Comment by Neilpang** [comment]
fixed  8fb9a709b0d4b2627888bf55a8809faed24bc84c

debian 7 with wget is working now.

**Comment by ReptoxX** [comment]
You are the best. 
Nice that i can help you finding errors :)
