### ISSUE TITLE
Cloudflare: Error in deploying certificate

### ISSUE THREAD

**Issue by JonnyTech** [Neilpang/acme.sh#1865]
Running a 123-reg.co.uk site but using Cloudflare's free DNS service, produces the following error in red when trying to deploy: **Error in deploying certificate**

Here are full logs for both issue and deploy (using the staging interface because somehow I managed to trip a rate limiter):

```
logs removed
```

Please can someone offer any assistance?

**Comment by frebib** [comment]
You're using the testing server to issue the certificate and deployment is failing because it isn't a valid CA, as it should

**Comment by JonnyTech** [comment]
Thanks for confirming, I suspected as much but was unable to test. I shall wait for the rate-limiting period to pass before trying again.
