### ISSUE TITLE
Restricted permissions for certificate directories

### ISSUE THREAD

**Issue by spack971** [Neilpang/acme.sh#1868]
Issue
-----

When issuing a new certificate `acme.sh` will create a new directory in `${CERT_HOME}` to host all files needed to manage this domain certificates.

However, this folder is also containing the certificate's private key. With the folder being created with the system's `umask` value, the private key can potentially be ex-filtrated on a shared system.

```console
$ umask
022
$ ls -ld .acme.sh/example.com
drwxr-xr-x. 2 user user 203 1 jan 00:00 .acme.sh/example.com
```

The certificate folder MUST be only accessible to the user in order to prevent extraction of the certificate.

Expected result
---------------

`acme.sh` should ignore the system's `umask` and set certificate folder permissions only to allow user access. 

```console
$ umask
022
$ ls -ld .acme.sh/example.com
drwx------. 2 user user 203 1 jan 00:00 .acme.sh/example.com
```

**Comment by Neilpang** [comment]
```sh
root@ctl:~# ls -la ~ | grep .acme.sh
drwx------  9 root root  4096 Oct 30 08:59 .acme.sh

```

The `.acme.sh` home folder is `700`, nobody else can read your key.

**Comment by FernandoMiguel** [comment]
this change broke my docker-compose... i used to run it with user:nobody but now need root :(

**Comment by Neilpang** [comment]
@FernandoMiguel 
please use `--install-cert` or `--deploy-hook` to `copy` the cert/key out of the default home folder.  Then it uses the default umask `022`.

Otherwise, you can `chmod` on the default home folder, or another domain folder,  acme.sh will not change the permission you set.

**Comment by FernandoMiguel** [comment]
@Neilpang i tried that... but docker volumes mess that a bit...
anyway, for now, it works. but i was caught off guard and broke the environment for a bunch of my devs between friday and monday

**Comment by Neilpang** [comment]
@FernandoMiguel  I'm sorry about that.

**Comment by spack971** [comment]
I was referring to a behaviour like the OpenSSH project. `ssh` will refuse to run if any file it manages are not properly restricted:

```
$ ls -ld .ssh
drwx------. .ssh
$ ls -l .ssh
-rw-------. config
-rw-------. id_rsa
-rw-r--r--. known_hosts
-rw-r--r--. id_rsa.pub
```
