### ISSUE TITLE
dnspod.com保存token识别问题

### ISSUE THREAD

**Issue by rickly** [Neilpang/acme.sh#1869]
由于dnspod.com目前获得"user_token"格式如： "730060,e1a8a$f14dc5dcbafd83680b3d2a553c4d553d"
填入
export DPI_Id="730060"
export DPI_Key="e1a8a$f14dc5dcbafd83680b3d2a553c4d553d"
运行脚本之后识别会丢弃"$"符号及"$"符号后一位数，上述例子中的token会被脚本识别为：
730060,e1a8a14dc5dcbafd83680b3d2a553c4d553d而导致错误，请修复一下脚本谢谢

**Comment by Neilpang** [comment]
这跟 脚本没关系,  用单引号就好了.
```
export DPI_Key='e1a8a$f14dc5dcbafd83680b3d2a553c4d553d'
```
