### ISSUE TITLE
how to update acme.sh

### ISSUE THREAD

**Issue by guigeng** [Neilpang/acme.sh#187]
必须先uninstall，然后再install一遍才行吗？
还是有命令可以直接更新acme.sh？

**Comment by Neilpang** [comment]
直接覆盖安装就可以。  稍后可能会添加一个 命令 upgrade

**Comment by guigeng** [comment]
谢谢您的回复。
我的nginx是部署成反向代理，配置是这样：
server {
    listen 80;
    server_name erp.domain.com ekp.domain.com;
    location /.well-known/acme-challenge/ {
        alias /etc/nginx/html/challenges/;
        try_files $uri =404;
    }
    location / {
        return 301 https://$server_name$request_uri;
    }
}
然后运行
acme.sh --issue -d erp.domain.com -d ekp.domain.com -w /etc/nginx/html/challenges/
报错：
chown: missing operand after ‘/.well-known’
Try 'chown --help' for more information.
不知道问题是出在哪里。

**Comment by Neilpang** [comment]
路径不对。 

参考这个配置。
```
location ^~ /.well-known/acme-challenge/ {
   default_type "text/plain";
   root /etc/nginx/html;
} 

location = /.well-known/acme-challenge/ {
    try_files $uri =404;
} #acme


```

然后：

```
acme --issue -d ....   -w  /etc/nginx/html
```

**Comment by guigeng** [comment]
thanks very much!

**Comment by guigeng** [comment]
看acme.sh命令的参数说明
--certpath /path/to/real/cert/file  After issue/renew, the cert will be copied to this path.
--keypath /path/to/real/key/file  After issue/renew, the key will be copied to this path.
--capath /path/to/real/ca/file    After issue/renew, the intermediate cert will be copied to this path.
--fullchainpath /path/to/fullchain/file After issue/renew, the fullchain cert will be copied to this path.

我可以在证书生成的时候，将所需的证书放置在所指定的位置是不是这个意思？

默认的位置是~/.acme.sh/domain.com/
ca.cer 
domain.com.cer  
domain.com.conf 
domain.com.csr
domain.com.key
domain.com.ssl.conf
fullchain.cer
我放在nginx配置文件里面的只有fullchain.cer和domain.com.key
那么其他文件是什么作用？

在安装的时候，自动在crontab里面增加：
0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
这个指令，每天夜里自动进行更新所有证书，那么如果我把上面的那些参数添加进来
0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" --certpath "/etc/nginx/ssl/" --keypath  "/etc/nginx/ssl/" --capath  "/etc/nginx/ssl/" --fullchainpath  "/etc/nginx/ssl/" --reloadcmd "systemctl reload nginx" >/dev/null
这样修改的话，那么我是否需要使用这些参数，重新issue新的证书？

谢谢！

**Comment by Neilpang** [comment]
>> 我可以在证书生成的时候，将所需的证书放置在所指定的位置是不是这个意思？

如果指定了这几个参数，  在成功创建证书或者 renew 证书之后， 会自动把证书拷贝的其指定的位置。


>> 那么其他文件是什么作用？
其他的文件没有作用，  为的是别的服务器，不光是nginx。  你需要什么就指定什么，别的不管。


>> 这样修改的话，那么我是否需要使用这些参数，重新issue新的证书？

不要手动修改 crontab 配置。   你刚才指定的所有参数都会自动被记录下来。  80天之后， 系统会自动用记录下来的参数再次重复你刚刚的过程来renew证书。   所有过程不需要人工干预。 它自己会处理。
