### ISSUE TITLE
升级失败

### ISSUE THREAD

**Issue by chaihongjun** [Neilpang/acme.sh#1877]
#1439 
通过这里手动下载包并解压安装成功了，然后测试upgrade报错（和安装一样）

> Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35

所以该怎么处理？  Centos 6.5

**Comment by zikezi** [comment]
我也有这样的问题，请问怎么解决？

**Comment by Neilpang** [comment]
[Tue Dec 4 08:58:24 CST 2018] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
