### ISSUE TITLE
Error add txt for domain 阿里云api是否不支持子账号RAM

### ISSUE THREAD

**Issue by hjfeng1988** [Neilpang/acme.sh#1894]
使用阿里云Api，主账号AK颁发成功，使用子账号RAM提示Error add txt for domain
是否不支持阿里云子账号AK

**Comment by hjfeng1988** [comment]
子账号添加错策略，需要的是"管理云解析(DNS)的权限"，而不是"管理域名的服务权限"

**Comment by telami** [comment]
Thanksssssssss

**Comment by ludengji** [comment]
感谢👍
