### ISSUE TITLE
 Domain is not valid:'*.techtag.com' when apply wildcard cert with  --install-cert

### ISSUE THREAD

**Issue by gitbobo** [Neilpang/acme.sh#1897]
Steps to reproduce
------------------

[Fri Oct 26 08:51:50 UTC 2018] Lets find script dir.
[Fri Oct 26 08:51:50 UTC 2018] _SCRIPT_='/root/.acme.sh/acme.sh'
[Fri Oct 26 08:51:50 UTC 2018] _script='/root/.acme.sh/acme.sh'
[Fri Oct 26 08:51:50 UTC 2018] _script_home='/root/.acme.sh'
[Fri Oct 26 08:51:50 UTC 2018] Using config home:/root/.acme.sh
[Fri Oct 26 08:51:50 UTC 2018] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.0
[Fri Oct 26 08:51:50 UTC 2018] Using config home:/root/.acme.sh
[Fri Oct 26 08:51:50 UTC 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Fri Oct 26 08:51:50 UTC 2018] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Fri Oct 26 08:51:50 UTC 2018] DOMAIN_PATH='/root/.acme.sh/*.techtag.com'
[Fri Oct 26 08:51:50 UTC 2018] Domain is not valid:'*.techtag.com'

-----------------

```
 ~/.acme.sh/acme.sh --install-cert -d *.techtag.com -d techtag.com --dns dns_dp --key-file /etc/pki/dovecot/private/_.techtag.com.key --fullchain-file /etc/pki/dovecot/certs/fullchain.cer --debug 2
```

**Comment by Neilpang** [comment]
duplicate with https://github.com/Neilpang/acme.sh/issues/1905
