### ISSUE TITLE
Install (create config, etc) when already in target directory

### ISSUE THREAD

**Issue by HostedDinner** [Neilpang/acme.sh#190]
It would be good, if there would be an option to call --install without trying to copy the files into the target directory.
I downloaded the files and put them into `~/.acme.sh/` and executed `~/.acme.sh/acme.sh --install`.
The problem is, that neither the default config, nor the cronjob was installed, because the script could not copy the script to the target (same name..., surprise) and aborted. When this happens, the installer should not abort, rather continue.

**Comment by Neilpang** [comment]
No,  please  do not  install in the target directory.
Or,  you can just use online install, which can work in any directory:
```
curl  https://get.acme.sh | sh
``

**Comment by HostedDinner** [comment]
That does not make sense...
Why should I download it, copy it to another directory and afterwards delete the downloaded files?
Normal: Download it to the right directory, no copy/moving involved -> Profit.

**Comment by Neilpang** [comment]
You don't need to download,  just install online:  
```
curl  https://get.acme.sh | sh
```

If you already download it in the  `~/.acme.sh/` dir, you don't need to call  `--install`  command at all.
It's just working there.
