### ISSUE TITLE
can not get domain token $d

### ISSUE THREAD

**Issue by Rikairchy** [Neilpang/acme.sh#191]
Trying acme.sh on a new box. I get an error stating that the domain token cannot be found.

I'm using Cloudlfare's DNS (API key and email configured) on Fedora 23 using a non-root account. 

I have uninstalled the acme.sh script and removed the ~/.acme.sh directory. Here is the output when running the command:

<code>[znc@fedora` ~]$ acme.sh --dns dns_cf --issue -d znc.rikairchy.net  </code>
<code>[Fri May 20 23:07:03 EDT 2016] Skip register account key  </code>
<code>[Fri May 20 23:07:03 EDT 2016] Creating csr  </code>
<code>[Fri May 20 23:07:03 EDT 2016] Single domain='znc.rikairchy.net'  </code>
<code>[Fri May 20 23:07:03 EDT 2016] Verify each domain  </code>
<code>[Fri May 20 23:07:03 EDT 2016] Getting webroot for domain='znc.rikairchy.net'  </code>
<code>[Fri May 20 23:07:03 EDT 2016] Getting token for domain='znc.rikairchy.net'  </code>
<code>[Fri May 20 23:07:04 EDT 2016] Error, can not get domain token znc.rikairchy.net  </code>
<code>[znc@fedora ~]$ which acme.sh  </code>
<code>alias acme.sh='/home/znc/.acme.sh/acme.sh'  </code>
<code>        ~/.acme.sh/acme.sh </code>

**Comment by epheph** [comment]
I just ran into this issue. It seems like the json responses have changed and are now being pretty-printed, completely destroying the grep'ing logic used to extract the variables. I fixed a few, but there's some large issues now, like some same-line pattern matching for values that are now on separate lines.

**Comment by Rikairchy** [comment]
Main reason I love this script is the Cloudflare integration. I have about 60 or so total subdomains that I use through a few certs. It's a bit of a pain to update each TXT record each time.

**Comment by zoc** [comment]
Yeah, same issue for me. I also chose this script for the Cloudflare integration. For now I only have one certificate in production but I was expecting to be able to request a few ones this morning.

I think that jq might be the solution, even if it is adding a dependency on another external tool. Anyway there are already dependencies, like netcat and curl (but I have to admit that they are more "standard" tools).

**Comment by Neilpang** [comment]
Yes, the  response from let's encrypt is formated. I'm fixing it now.

**Comment by Rikairchy** [comment]
@Neilpang You're awesome. Anything we can do to help?

**Comment by Neilpang** [comment]
No, thanks.  just wait a few minutes.

**Comment by Neilpang** [comment]
fixed  at  2ee5d873db78930925e1f60bf21aead9c7f9c65e

Please try again.

**Comment by zoc** [comment]
Seems to be OK for me, thank you so much !

**Comment by ElectronicWar** [comment]
v2.2.5 works for me again, thanks a lot!

**Comment by epheph** [comment]
Confirmed 2ee5d87 fixed the issue (for now!)

**Comment by petervanderwal** [comment]
Related to this issue:
lines 1489 & 1490 should be
`    response="$(echo $response | _dbase64 "multiline" | tr -d "\r\n" )"
    _err "Sign failed: $(echo "$response" | grep -o  '"detail" *: *"[^"]*"')"
`

**Comment by Neilpang** [comment]
@petervanderwal    fixed :  eae290992f2a087afd34c7d86331d99709e23455
