### ISSUE TITLE
FreeDNS更新出错(FreeDNS failed to add TXT record as FreeDNS requested security code)

### ISSUE THREAD

**Issue by redraiderj** [Neilpang/acme.sh#1911]
Domain是dendrobium.ignorelist.com，FREEDNS_User和FREEDNS_Password已指定，debug输出如下：

begin installing acme.sh tool...
[Tue Nov  6 11:26:21 CST 2018] It is recommended to install socat first.
[Tue Nov  6 11:26:21 CST 2018] We use socat for standalone server if you use standalone mode.
[Tue Nov  6 11:26:21 CST 2018] If you don't use standalone mode, just ignore this warning.
[Tue Nov  6 11:26:21 CST 2018] Installing to /volume3/syno-acme/acme.sh
[Tue Nov  6 11:26:21 CST 2018] Installed to /volume3/syno-acme/acme.sh/acme.sh
[Tue Nov  6 11:26:22 CST 2018] Installing alias to '/root/.profile'
[Tue Nov  6 11:26:22 CST 2018] OK, Close and reopen your terminal to start using acme.sh
[Tue Nov  6 11:26:22 CST 2018] Good, bash is found, so change the shebang to use bash as preferred.
[Tue Nov  6 11:26:22 CST 2018] OK
done installAcme
begin generateCrt
begin updating default cert by acme.sh tool
[Tue Nov  6 11:26:23 CST 2018] Single domain='*.dendrobium.ignorelist.com'
[Tue Nov  6 11:26:23 CST 2018] Getting domain auth token for each domain
[Tue Nov  6 11:26:25 CST 2018] Getting webroot for domain='*.dendrobium.ignorelist.com'
[Tue Nov  6 11:26:25 CST 2018] Found domain api file: /volume3/syno-acme/acme.sh/dnsapi/dns_freedns.sh
[Tue Nov  6 11:26:25 CST 2018] Add TXT record using FreeDNS
[Tue Nov  6 11:26:29 CST 2018] FreeDNS failed to add TXT record for _acme-challenge.dendrobium as FreeDNS requested security code
[Tue Nov  6 11:26:29 CST 2018] Note that you cannot use automatic DNS validation for FreeDNS public domains
[Tue Nov  6 11:26:29 CST 2018] Error add txt for domain:_acme-challenge.dendrobium.ignorelist.com
[Tue Nov  6 11:26:29 CST 2018] Please add '--debug' or '--log' to check more details.
[Tue Nov  6 11:26:29 CST 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Tue Nov  6 11:26:30 CST 2018] Installing cert to:/usr/syno/etc/certificate/_archive/DASRiV/cert.pem
cat: /volume3/syno-acme/acme.sh/*.dendrobium.ignorelist.com/*.dendrobium.ignorelist.com.cer: No such file or directory
[Tue Nov  6 11:26:30 CST 2018] Installing key to:/usr/syno/etc/certificate/_archive/DASRiV/privkey.pem
[Tue Nov  6 11:26:30 CST 2018] Installing full chain to:/usr/syno/etc/certificate/_archive/DASRiV/fullchain.pem
cat: /volume3/syno-acme/acme.sh/*.dendrobium.ignorelist.com/fullchain.cer: No such file or directory
./cert-up.sh: line 54: cd: /volume3/syno-acme/temp/acme.sh-2.7.8: No such file or directory
done generateCrt

**Comment by dkerr64** [comment]
Is the domain you are trying to use a free public domain?  If so then you cannot generate certificates for those.  This is a known documented restriction (see statement in the your log) and cannot be fixed because FreeDNS requires the security check.

**Comment by dkerr64** [comment]
@redraiderj can you please confirm whether you were using a free domain or one you owned.  This is important to know if there is a bug here or not.  Thanks

**Comment by redraiderj** [comment]
I'm using a free domain, so I think it's not a bug here.
