### ISSUE TITLE
How to migrate acme.sh to another computer G

### ISSUE THREAD

**Issue by pcouderc12** [Neilpang/acme.sh#1913]
It is not an issue, but a user question.

I am migrating my server. How do I migrate too my acme "script" so that it works on the new server ?

**Comment by FernandoMiguel** [comment]
Just install acme.sh and issue a new cert. 
Make sure the crown is running. 
That's it

**Comment by pcouderc12** [comment]
Fine, thank you!

**Comment by atesin** [comment]
i backuped all my server's filesystem, formatted, installed everything from scratch (centos 7->8), reinstall services and recover conf and data files

i want to recover my running acme.sh with all data, certs, tasks, account id, etc., without doing a fresh installation dropping everything done before

so sorry but i found the answer by @FernandoMiguel pretty simplistic and not enough for my needs

**Comment by FernandoMiguel** [comment]
@atesin acme.sh contains all its config files in a folder.
If you have a backup of acme.sh previous installation, you can restore that
You will need to reinstall the cron obviously

**Comment by atesin** [comment]
what a good to know it!

and naturally i think we can also restore aliases in ~/.bashrc ... i would like to know what should i restore in addition

actually i would like to know the procedure the script does the first time it runs for installation, to replicate myself manually (or the most part at least)

what is the instalation procedure the script does?, thanks in advance

**Comment by Neilpang** [comment]
The installation does't 2 things.
1.  copy the script to your `~/.acme.sh/` folder.
2. setup a cronjob for renewal.

So you can just install acme.sh on the new machine. and then copy the files from the previous machine to the new machine.

**Comment by atesin** [comment]
thank you @Neilpang for your response... i should add, in next runs by it also reads/writes configurations (and logs if enabled) in `~/.acme.sh/`

what i did and worked for me:

- copied my `<backup>/<home_dir>/.acme.sh` folder to `<home_dir>/`
- copied my old crontab as appear from `<backup>/var/spool/cron/<user>`, with `crontab -e`
- copied my old certs dir from `<backup>/<certs_dir>`, as shows in `<.acme.sh>/account.conf`
- ran `acme.sh` once to check installation and auto update (i had auto update and logs enabled)

as a side note, as showed in the logs, it seems acme.sh update downloads and installs the script everytime, regardless the version is newer or not, i will add another ticket

thanks for your support and happy new year
