### ISSUE TITLE
where does acme save the args of --installcert command?

### ISSUE THREAD

**Issue by ilaipi** [Neilpang/acme.sh#1915]
not a bug thanks.

[中文说明-3. copy/安装 证书](https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E#3-copy%E5%AE%89%E8%A3%85-%E8%AF%81%E4%B9%A6)

> 值得注意的是, 这里指定的所有参数都会被自动记录下来, 并在将来证书自动更新以后, 被再次自动调用.

I wonder where they are saved. Because I want to know what it actually saved, especially how many domains it saved. thanks.

**Comment by Conduitry** [comment]
They're saved in `~/.acme.sh/example.com/example.com.conf`.

**Comment by ilaipi** [comment]
@Conduitry Thanks. If one renew failed, will it affect others?

**Comment by Neilpang** [comment]
不会,   每个证书的 renew 都互不影响.

**Comment by ilaipi** [comment]
@Neilpang 谢谢。再问一个问题，一次--issue指定多个域名，生成一个证书，是多个域名共用一个证书吗？
