### ISSUE TITLE
importing  existing domains/certs in to acme.

### ISSUE THREAD

**Issue by Ressy66** [Neilpang/acme.sh#1922]
Not exactly an issue, but google and wiki doesn't yield results...

I use acme.sh successfully to manage several domains certs.

I have one machine with half a dozen or so LE certs that were issued by other means, manually or Crypt::LE. (they were the very first domains we used since we had trouble with acme.sh and TLS errors - all resolved ages ago now, at present that machine has to check via another bash script for renewals as well as acme.sh cron, so I'm trying to work out how to import those existing and current certs to acme.sh so it can manage all of my certs, has anyone any references to how to do this successfully?

**Comment by FernandoMiguel** [comment]
Unless you really need to keep those private keys, don't worry about importing them.
Just issue new certs

**Comment by Ressy66** [comment]
Thanks for suggestion, I just recreated them all overwriting previous, all is now good :)
Can now remove the other scripting and let acme.sh take care of everything

Closing issue...
