### ISSUE TITLE
求中文文档，英文能看懂，但是看着累啊

### ISSUE THREAD

**Issue by fengzhao** [Neilpang/acme.sh#1923]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

中文啊，大佬

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E

**Comment by fengzhao** [comment]
中文文档的详细程度，要比英文差太多了吧。

**Comment by Neilpang** [comment]
@fengzhao  https://github.com/Neilpang/acme.sh/wiki/Blogs-and-tutorials
