### ISSUE TITLE
Skip domains specified in a certificate no longer point at system

### ISSUE THREAD

**Issue by petrikoz** [Neilpang/acme.sh#1928]
Renew with cron doesn't work for me if some domains specified in a certificate no longer point at system.
In certbot I can use `--allow-subset-of-names` option.
How I can skip this domains with acme.sh?

**Comment by Neilpang** [comment]
please issue a new cert instead.  it will overwrite the previous one.

**Comment by petrikoz** [comment]
Yes, I did this. But if I have many domains in one cert I should know which of them are gone.
Because if it still stay in my command I can't complete issue. Also renew.

My pain in this case:

1. I issued cert with multiple domains.
2. Some domains are gone.
3. Renew is broken!

After step 3 I should manually check which domains are gone.
Can I skip manually check which domains missed on my server?

**Comment by FernandoMiguel** [comment]
what do you mean with 
>  I should manually check which domains are gone.

only you know what domains you want certs for.

**Comment by petrikoz** [comment]
@FernandoMiguel you're right. But sometimes I change the DNS for some domains of an existing cert: to test a new server, to transfer any projects to a server elsewhere, etc. If I forget to issue a new cert without these domains, my renewal will be broken. And the cert will expire.

**Comment by FernandoMiguel** [comment]
Well, if you change DNS, then you should immediately issue new certs to account for that change.
If you use DNS API the risk might be less than webroot validation

**Comment by petrikoz** [comment]
Issue via DNS API is cool. But my provider doesn't support this way.
So, I'll just care more about domains in my certs.

**Comment by FernandoMiguel** [comment]
You can always change to a provider that supports it or use alias support from acme.sh

You can also issue your certs with smaller number of domains in the SAN, preventing it from failing
