### ISSUE TITLE
ECC wildcard domain with manual DNS  failing to be issued

### ISSUE THREAD

**Issue by hadaob** [Neilpang/acme.sh#1935]
Hi Guys,

Just installed ACME (v2.8.0) when trying to get a wildcard domain with manual DNS (I know, its just for testing, no production) I was getting a error that the cert was not issued after the initial --issue to get the TXT records, after checking the debug looks the "DOMAIN_PATH=" for the --renew is looking on another path (not adding the _ecc), only after manually renaming the folder and issues again a new --renew it went Ok.

The steps below:

`$ ./acme.sh --issue -d *.redir.hiddendomain.com --ecc --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please  --debug`

[Mon Nov 26 21:31:04 UTC 2018] d='*.redir.hiddendomain.com'
[Mon Nov 26 21:31:04 UTC 2018] _d_alias
[Mon Nov 26 21:31:04 UTC 2018] txtdomain='_acme-challenge.redir.hiddendomain.com'
[Mon Nov 26 21:31:04 UTC 2018] txt='yMtDvZhSySjTTlAbUQYpi8GTWYYaL5snmDQiOQFFkG8'
[Mon Nov 26 21:31:04 UTC 2018] d_api
[Mon Nov 26 21:31:04 UTC 2018] Add the following TXT record:
[Mon Nov 26 21:31:04 UTC 2018] Domain: '_acme-challenge.redir.hiddendomain.com'
[Mon Nov 26 21:31:04 UTC 2018] TXT value: 'yMtDvZhSySjTTlAbUQYpi8GTWYYaL5snmDQiOQFFkG8'
[Mon Nov 26 21:31:04 UTC 2018] Please be aware that you prepend _acme-challenge. before your domain
[Mon Nov 26 21:31:04 UTC 2018] so the resulting subdomain will be: _acme-challenge.redir.hiddendomain.com
[Mon Nov 26 21:31:04 UTC 2018] Dns record not added yet, so, save to /home/ec2-user/.acme.sh/*.redir.hiddendomain.com/*.redir.hiddendomain.com.conf and exit.
[Mon Nov 26 21:31:04 UTC 2018] Please add the TXT records to the domains, and re-run with --renew.
[Mon Nov 26 21:31:04 UTC 2018] pid

Went to DNS and added the TXT records and then:

`$ ./acme.sh --renew -d *.redir.hiddendomain.com --ecc --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please --debug`

[Mon Nov 26 21:33:43 UTC 2018] Using config home:/home/ec2-user/.acme.sh
https://github.com/Neilpang/acme.sh
v2.8.0
[Mon Nov 26 21:33:43 UTC 2018] Using config home:/home/ec2-user/.acme.sh
[Mon Nov 26 21:33:43 UTC 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Nov 26 21:33:43 UTC 2018] DOMAIN_PATH='/home/ec2-user/.acme.sh/*.redir.hiddendomain.com_ecc'
[Mon Nov 26 21:33:43 UTC 2018] Renew: '*.redir.hiddendomain.com'
[Mon Nov 26 21:33:43 UTC 2018] '*.redir.hiddendomain.com' is not a issued domain, skip.

Checked the path and indeed didn't exist, renamed to have the _ecc.

`$ mv \*.redir.hiddendomain.com/ \*.redir.hiddendomain.com_ecc/`

`$ ./acme.sh --renew -d *.redir.hiddendomain.com --ecc --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please --debug`

[Mon Nov 26 21:37:32 UTC 2018] Lets find script dir.
[Mon Nov 26 21:37:32 UTC 2018] _SCRIPT_='./acme.sh'
[Mon Nov 26 21:37:32 UTC 2018] _script='/home/ec2-user/acme.sh'
[Mon Nov 26 21:37:32 UTC 2018] _script_home='/home/ec2-user'
[Mon Nov 26 21:37:32 UTC 2018] Using default home:/home/ec2-user/.acme.sh
[Mon Nov 26 21:37:32 UTC 2018] Using config home:/home/ec2-user/.acme.sh
https://github.com/Neilpang/acme.sh
v2.8.0
[Mon Nov 26 21:37:32 UTC 2018] Using config home:/home/ec2-user/.acme.sh
[Mon Nov 26 21:37:32 UTC 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Nov 26 21:37:32 UTC 2018] DOMAIN_PATH='/home/ec2-user/.acme.sh/*.redir.hiddendomain.com_ecc'
[Mon Nov 26 21:37:32 UTC 2018] Renew: '*.redir.hiddendomain.com'
[Mon Nov 26 21:37:32 UTC 2018] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Mon Nov 26 21:37:32 UTC 2018] Using config home:/home/ec2-user/.acme.sh
[Mon Nov 26 21:37:32 UTC 2018] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Nov 26 21:37:32 UTC 2018] _main_domain='*.redir.hiddendomain.com'
[Mon Nov 26 21:37:32 UTC 2018] _alt_domains='no'
[Mon Nov 26 21:37:32 UTC 2018] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Mon Nov 26 21:37:32 UTC 2018] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Nov 26 21:37:32 UTC 2018] GET
[Mon Nov 26 21:37:32 UTC 2018] url='https://acme-v02.api.letsencrypt.org/directory'
[Mon Nov 26 21:37:32 UTC 2018] timeout=
[Mon Nov 26 21:37:32 UTC 2018] _CURL='curl -L --silent --dump-header /home/ec2-user/.acme.sh/http.header  -g '
[Mon Nov 26 21:37:33 UTC 2018] ret='0'
[Mon Nov 26 21:37:33 UTC 2018] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mon Nov 26 21:37:33 UTC 2018] ACME_NEW_AUTHZ
....... 
removed to reduce output
......
[Mon Nov 26 21:37:36 UTC 2018] Success
[Mon Nov 26 21:37:36 UTC 2018] pid
[Mon Nov 26 21:37:36 UTC 2018] Skip for removelevel:
[Mon Nov 26 21:37:36 UTC 2018] pid
[Mon Nov 26 21:37:36 UTC 2018] No need to restore nginx, skip.
[Mon Nov 26 21:37:36 UTC 2018] _clearupdns
[Mon Nov 26 21:37:36 UTC 2018] skip dns.
[Mon Nov 26 21:37:36 UTC 2018] Verify finished, start to sign.

And voila, certificate issued with success.

Thank you in advance and great job making the ACME client.

**Comment by Neilpang** [comment]
```sh
./acme.sh --issue -d  '*.redir.hiddendomain.com'   -k  ec-256  ....
```


```sh
./acme.sh --renew -d  '*.redir.hiddendomain.com'   --ecc
```
