### ISSUE TITLE
err_cert_authority_invalid

### ISSUE THREAD

**Issue by muhammad-naderi** [Neilpang/acme.sh#1953]
Hi, 
first of all thanks for the nice work.
I'm using acme.sh on a centos 6 machine with apache web server
I issue the certificate using `acme.sh  --issue -d shygunsys.net  -d '*.shygunsys.net'  --dns dns_cf` successfully and use it in apache with this conf

```
SSLCertificateFile  /root/.acme.sh/shygunsys.net/shygunsys.net.cer
SSLCertificateKeyFile  /root/.acme.sh/shygunsys.net/shygunsys.net.key
SSLCertificateChainFile /root/.acme.sh/shygunsys.net/fullchain.cer
SSLCACertificateFile /root/.acme.sh/shygunsys.net/fullchain.cer
SSLCACertificatePath /root/.acme.sh/shygunsys.net/
```

everything works fine on pc, and new android devices, except for Old androids, I get 
`err_cert_authority_invalid`

checking on [SSLabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=wordpressapi.shygunsys.net&hideResults=on) gives error on `chain issues Incorrect order, Extra certs` and on digicert.com displays a broken link from server certificate to intermediate certificate.
using other bots for windows server I am getting a correct certificate, so I think problem should be with my apache conf.

Am I doing something wrong?

also I think this [issue](https://github.com/Neilpang/acme.sh/issues/801) somehow is related to my problem, unfortunately I do not know any chinese, so please forgive me if this issue is kind of duplicate

**Comment by FernandoMiguel** [comment]
Your 4th line is duplicated

**Comment by FernandoMiguel** [comment]
According to this 
https://letsencrypt.org/docs/certificate-compatibility/

Let's encrypt is not supported by 
Android < v2.3.6

**Comment by muhammad-naderi** [comment]
> According to this
> https://letsencrypt.org/docs/certificate-compatibility/
> 
> Let's encrypt is not supported by
> Android < v2.3.6

the android I'm checking on is 4.2.2, and as I mentioned certificates on out windows servers (from letsencrypt) work perfectly fine 



> Your 4th line is duplicated

I commented that line out, still same problem

**Comment by muhammad-naderi** [comment]
digging more in [SSlabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=www.shygunsys.net) I noticed that the chain is incomplete in `Certificate #2: RSA 2048 bits (SHA256withRSA) part` the second certificate in Paths is marked as `Extra Download` may be that is the problem ?

![certificate](https://user-images.githubusercontent.com/8791318/49696548-4a154280-fbc0-11e8-991a-4a9f10731827.png)

**Comment by FernandoMiguel** [comment]
you already providing full chain
`SSLCACertificateFile /root/.acme.sh/shygunsys.net/fullchain.cer`

**Comment by muhammad-naderi** [comment]
> I run testssl.sh against your domain
> you seem to be serving two certs.
> one for SNI and one without SNI support
> ![image](https://user-images.githubusercontent.com/168366/49696636-c0a44700-fba4-11e8-93ac-14057244a073.png)

well you were right, problem was that apache was reading ca from someplace else, creating symlink from that file to acme.sh output solved the problem
