### ISSUE TITLE
Change .well-know path

### ISSUE THREAD

**Issue by beli3ver** [Neilpang/acme.sh#1954]
Hello,

is it possible to change the well know path?
Something like that
--well-known /etc/acme/well-known

Thanks

**Comment by Neilpang** [comment]
which method do you use?  webroot mode or standalone mode ?

**Comment by beli3ver** [comment]
Standalone

Am December 16, 2018 1:00:53 PM UTC schrieb neil <notifications@github.com>:
>which method do you use?  webroot mode or standalone mode ?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Neilpang/acme.sh/issues/1954#issuecomment-447641541

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Neilpang** [comment]
you can try 'ACME_DIR'

```sh
mkdir /tmp/acme
export ACME_DIR="/tmp/acme"

acme.sh  --issue -d test.com  --standalone
```
