### ISSUE TITLE
Fabio load balancer + Vault

### ISSUE THREAD

**Issue by pashinin** [Neilpang/acme.sh#1956]
When using Fabio load balancer it wants to have a specific structure of records in Vault.
Fabio docs: https://fabiolb.net/feature/certificate-stores/#vault

We need to write in Vault this way:

```
vault write <PREFIX>/www.domain.com cert=@cert.pem key=@key.pem
```

I suggest using this write command when (for example) "Fabio" env variable is set to "1" instead of usual 4 write commands in vault_cli.sh.

**Comment by pashinin** [comment]
https://github.com/Neilpang/acme.sh/pull/1957

**Comment by Neilpang** [comment]
is this compatible ?

**Comment by pashinin** [comment]
Well, if "FABIO" env variable is not set it runs exactly same commands as it run before. I didn't change them.
