### ISSUE TITLE
Cloudflare (dns_cf) is using the wrong domain id.

### ISSUE THREAD

**Issue by asjmcguire** [Neilpang/acme.sh#1959]
Trying to renew nptohc.co.uk, CloudFlare returns 4 domains (bordersweather.co.uk, iiccp.co.uk, nptohc.co.uk,stops.org) for my account when the zones REST endpoint is hit. The script is using the returned id for the first domain (bordersweather.co.uk), and therefore updating the TXT record for bordersweather instead of nptohc. The script of course fails later because the TXT record for nptohc.co.uk does not exist - since it added it to the wrong domain.

**Comment by Incrementing** [comment]
+1
It's adding the record to one of my .co.uk domains, not the .io I specified.

**Comment by asjmcguire** [comment]
> +1
> It's adding the record to one of my .co.uk domains, not the .io I specified.

When you visit https://dash.cloudflare.com and click on the drop down "Select Website" is the site it is adding the TXT file to - also the first one listed, like me?

**Comment by Neilpang** [comment]
@asjmcguire  sorry, it was an issue imported yesterday,  https://github.com/Neilpang/acme.sh/issues/1941.

I will fix it soon.

**Comment by asjmcguire** [comment]
Thanks @Neilpang , I suspected it was probably a recent change, as it's been working brilliantly in the past. I have manually grabbed the challenge from the bordersweather domain and pasted it in to the nptohc domain before the 120 second countdown timer ran out, which has at least allowed me to renew the domain. Happy to test for you though when the fix is ready.

**Comment by harrytang** [comment]
Hi, same here, cannot get ssl for my new domain. Hope this will fix soon :)

**Comment by Neilpang** [comment]
Hi all.
It's fixed, please try with the latest code.

```sh
acme.sh --upgrade
``

**Comment by asjmcguire** [comment]
Thanks. Confirmed fixed.
