### ISSUE TITLE
DNS-01 not getting new tokens

### ISSUE THREAD

**Issue by serker1** [Neilpang/acme.sh#196]
Already have a cert for a domain/subdomain that verified and worked just fine last week.  This morning, attempting to create a new domain gives me "error, cannot get domain token blah.com".  This of course means I'm not getting the tokens to throw into DNS.  Attempted a bogus name on the existing "working" domain, and got the same error.  The appropriate privacy markouts are below (domain changed to protect the innocent, account name, nonce, etc...)

[Thu May 26 07:35:30 CDT 2016] /root/.acme.sh/bogus.blah.com/bogus.blah.com.conf:1:Le_Domain="bogus.blah.com"
[Thu May 26 07:35:30 CDT 2016] /root/.acme.sh/bogus.blah.com/bogus.blah.com.conf:2:Le_Alt="no"
[Thu May 26 07:35:30 CDT 2016] /root/.acme.sh/bogus.blah.com/bogus.blah.com.conf:3:Le_Webroot="dns"
[Thu May 26 07:35:30 CDT 2016] /root/.acme.sh/bogus.blah.com/bogus.blah.com.conf:4:Le_Keylength="no"
[Thu May 26 07:35:30 CDT 2016] 'dns' does not contain 'no'
[Thu May 26 07:35:30 CDT 2016] 'dns' does not contain 'apache'
[Thu May 26 07:35:30 CDT 2016] RSA key
[Thu May 26 07:35:30 CDT 2016] uselet='1'
[Thu May 26 07:35:30 CDT 2016] _URGLY_PRINTF
[Thu May 26 07:35:30 CDT 2016] uselet='1'
[Thu May 26 07:35:30 CDT 2016] _URGLY_PRINTF
[Thu May 26 07:35:31 CDT 2016] Skip register account key
[Thu May 26 07:35:31 CDT 2016] Creating domain key
[Thu May 26 07:35:31 CDT 2016] Use length 2048
[Thu May 26 07:35:31 CDT 2016] Creating csr
[Thu May 26 07:35:31 CDT 2016] Single domain='bogus.blah.com'
[Thu May 26 07:35:31 CDT 2016] Verify each domain
[Thu May 26 07:35:31 CDT 2016] Getting webroot for domain='bogus.blah.com'
[Thu May 26 07:35:31 CDT 2016] _w='dns'
[Thu May 26 07:35:31 CDT 2016] _currentRoot='dns'
[Thu May 26 07:35:31 CDT 2016] Getting token for domain='bogus.blah.com'
[Thu May 26 07:35:31 CDT 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Thu May 26 07:35:31 CDT 2016] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "bogus.blah.com"}}'
[Thu May 26 07:35:31 CDT 2016] RSA key
[Thu May 26 07:35:31 CDT 2016] uselet='1'
[Thu May 26 07:35:31 CDT 2016] _URGLY_PRINTF
[Thu May 26 07:35:31 CDT 2016] uselet='1'
[Thu May 26 07:35:31 CDT 2016] _URGLY_PRINTF
[Thu May 26 07:35:31 CDT 2016] GET
[Thu May 26 07:35:31 CDT 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Thu May 26 07:35:33 CDT 2016] nonce='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
[Thu May 26 07:35:33 CDT 2016] POST
[Thu May 26 07:35:33 CDT 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Thu May 26 07:35:35 CDT 2016] code='201'
[Thu May 26 07:35:35 CDT 2016] entry
[Thu May 26 07:35:35 CDT 2016] Error, can not get domain token bogus.blah.com
[Thu May 26 07:35:35 CDT 2016] pid

Can't tell if this is related to the new API changes at letsencrypt...but a renew of an existing cert is giving me the expected "can't renew for three months" (or something like that).  The code="201" is a little cryptic for me...so I can't tell if it's an outright denial, or, something in the script that can't read the token.  Pardon my stupidity if this on my end.

**Comment by Neilpang** [comment]
Please upgrade to latest version.

**Comment by serker1** [comment]
Sorry...that's the first thing I did.  The errors above are from the newest (3days old).

**Comment by Neilpang** [comment]
Which dns do you use?  cloudflare?
I just tried with cloudflare dns, it works for me.

please check your acme.sh version:
```
acme.sh  -v

```


Please add `--debug 2`  to get more detail info.

And what is your OS can curl version.

**Comment by Neilpang** [comment]
It seems that there is something wrong with cloudflare dns.   I have no time now to check more.
I will fix it tomorrow.

Thanks.

**Comment by Neilpang** [comment]
I just tried again on two of my servers, one with curl, the other one with wget.
They are working now.

I think it was a temp error on either letsencrypt side of on cloudflare side yesterday.

Please try again.

**Comment by serker1** [comment]
My apologies, my weekend was overwhelmed with spontaneous W10 upgrades at clients.  I've just gotten back to the issue.

acme.sh 2.2.4
gentoo
curl 7.45.0

You mention cloudflare, but that isn't what I'm using.  Previously, I'd simply --issue --dns -d domain, and it would print out what I am supposed to manually enter into the various DNS's for the client.  (_acme-challenge.bogus.domain.com. 1 TXT 'code') Now, I'm just getting the "error, token" previously described.

Without adding a bunch of compromising information...I'm wondering if I'm GETTING the token, but without '--debug 2' I'm not "seeing" the token anymore. (Like that printout routine of "put the following tokens Into your DNS" has disappeared or isn't being called anymore.  (Is the token line below, that I've retyped containing "microsoft", the very token I should be putting in DNS?)

If those are the tokens, and I'm just simply not getting the printout I'm used to, no harm/no foul---I'll debug to get them and enter them into the DNS.  I just fear that somehow these tokens aren't the answers, but somehow the question. Partial printout below.  If you need more, I'll have to doctor the output tremendously...

(BTW, thank you for the --debug 2...considerably more data)

Please confirm...

Content-Length: 1007
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Replay-Nonce: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Wed, 01 Jun 2016 11:24:26 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 01 Jun 2016 11:24:26 GMT
Connection: keep-alive
'
[Wed Jun  1 06:23:06 CDT 2016] response='{
  "identifier": {
    "type": "dns",
    "value": "bogus.domain.com"
  },
  "status": "pending",
  "expires": "2016-06-08T11:24:26.542363545Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/104532012",
      "token": "H3EgB5uA5Z77czklYMICROSOFTdeqCF5vjFt709utBg"
    },
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/104532013",
      "token": "2QAuQTIUV1WYZySkIUHi9WindowsuShDwxaefgVKRdRY"
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/104532014",
      "token": "TuarNKhu4t5A_3vMPbagjDisapain7DXZhZ5IWqUNwg"
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      2
    ],
    [
      1
    ]
  ]
}'
[Wed Jun  1 06:23:06 CDT 2016] code='201'
[Wed Jun  1 06:23:06 CDT 2016] entry
[Wed Jun  1 06:23:06 CDT 2016] Error, can not get domain token bogus.domain.com
[Wed Jun  1 06:23:06 CDT 2016] pid

**Comment by Neilpang** [comment]
Please install the latest code and try again.

**Comment by serker1** [comment]
That did it.  Thank you so much.  Worked like a charm.

Just FYI, no need to respond to this part.

Didn't use the debug on this round "--issue --dns", and the text changed a little.  Following the regular dns instructions, I simply inserted the proper DNS strings, then did a "--renew" like the readme suggests.  But the text of the output hit me with a feeling that retrying the regular "--issue --dns" might work.  As I recall (wasn't willing to try), it generates a new token every time you reissue--I know it's a little text blurb, but it might be something to consider (that the output's wording is a little vague).

Thanks again!
