### ISSUE TITLE
请问生成时是否能指定证书的有效期。

### ISSUE THREAD

**Issue by baiyuchina** [Neilpang/acme.sh#1964]
感谢作者的工具，请问生成时是否能指定证书的有效期，或者脚本中再哪调试能修改证书最大有效期。

**Comment by baoang** [comment]
最大有效期就是三个月，作者是两个月一续。

**Comment by ariable** [comment]
https://letsencrypt.org/docs/faq/
What is the lifetime for Let’s Encrypt certificates? For how long are they valid?

Our certificates are valid for 90 days. You can read about why here.

There is no way to adjust this, there are no exceptions. We recommend automatically renewing your certificates every 60 days.

**Comment by Neilpang** [comment]
不能.
