### ISSUE TITLE
Can't obtain wildcard cert using CF DNS API mode

### ISSUE THREAD

**Issue by blagoeres** [Neilpang/acme.sh#1966]
This is what I used to install `acme.sh`:

```
sudo mkdir /etc/letsencrypt
git clone https://github.com/Neilpang/acme.sh.git
cd acme.sh
sudo ./acme.sh --install \
--home /etc/letsencrypt \
--accountemail your_email@example.com
```

Then, I used this command to obtain wildcard cert from LE:

```
export CF_Key="MY_CF_API_KEY_HERE"
export CF_Email="my_cf_email@sss.com"
sudo /etc/letsencrypt/acme.sh --issue --dns dns_cf --home /etc/letsencrypt -d example.com -d *.example.com --keylength 2048
```

And I get this error:

```
[Fri Dec 14 01:59:07 CET 2018] You didn't specify a cloudflare api key and email yet.
[Fri Dec 14 01:59:07 CET 2018] Please create the key and try again.
[Fri Dec 14 01:59:07 CET 2018] Error add txt for domain:_acme-challenge.example.com
[Fri Dec 14 01:59:07 CET 2018] Please add '--debug' or '--log' to check more details.
[Fri Dec 14 01:59:07 CET 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

It says: "You didn't specify a cloudflare api key and email yet." but I specified them as you can see. Where is the problem in here ?

I also noticed, if I manually add API key and email into `/etc/letsencrypt/account.conf` I can obtain certs normally.

**Comment by chandave** [comment]
sudo is removing your previously defined CF_ environment variables.

Try running:

sudo -E /etc/letsencrypt/acme.sh --issue --dns dns_cf --home /etc/letsencrypt -d example.com -d *.example.com --keylength 2048

after exporting all your CF_ environment variables.

**Comment by blagoeres** [comment]
@chandave Yes you are right. I changed the way I install `acme.sh`, leaving everything to defaults, so that I don't need to use `sudo`. After obtaining certs, I just created symlink to `/etc/letsencrypt` from `~/.acme.sh/example.com` and everything works ok. Thank you for giving me a hint. I totally forget how bash shell works.
