### ISSUE TITLE
possible to issue cert using existing private key/csr pair ?

### ISSUE THREAD

**Issue by centminmod** [Neilpang/acme.sh#197]
Official letsencrypt client supports it so wondering if acme.sh does ?

For HPKP purporses I'd need to create a backup primary key/csr pair and generate pins for them too. So on renewal, I'd need to use that backup primary key/csr if necessary. From how acme.sh does it renews use the same private key/csr, so shouldn't be a problem until i need to switch it out for backup key/csr usage.

If acme.sh can use existing private key/csr pair, then you could add a new flag for `--hpkp` so that on new issues with the new flag, you could create a 2nd set of backup private key/csr pair in a subdirectory along with the usual issue routine

**Comment by Neilpang** [comment]
If you save your specified private key to the  domain dir,  it will be used to create csr and issue the cert.

So I can not get  what `--hpkp` is used for.   I'm not familiar with HPKP now.

**Comment by centminmod** [comment]
i see so is it supported to specify a private key at a certain path too ? with a different name for the private key ? so you specify the a different named private key in domain directory ?

HTTP Public Key Pinning http://centminmod.com/http-public-key-pinning.html and one way is it requires you to have a backup primary key and hash pin both existing primary key's SPKI as well as backup - though you can pin against the intermediates or root too but not as secure.

More info at https://scotthelme.co.uk/guidance-on-setting-up-hpkp/ and example of ECDSA cert and HPKP setup for it https://scotthelme.co.uk/ecdsa-certificates/

**Comment by Neilpang** [comment]
fixed  https://github.com/Neilpang/acme.sh/issues/212
