### ISSUE TITLE
multiple certs with namesilo (lexicon)

### ISSUE THREAD

**Issue by bilogic** [Neilpang/acme.sh#1982]
Hi,

I need separate certs for my domains, but due to namesilo DNS propagation, each DNS record creation requires a 15 minute delay. 

Is there anyway to execute part 1 (creation of the SRV TXT) for all these certs, do a 15-20 minute delay and then execute part 2 to request for the actual cert? Something like the manual DNS mode, but have the DNS record be automated.

Thank you.

**Comment by Neilpang** [comment]
use `--dnssleep`

https://github.com/Neilpang/acme.sh/wiki/dnsapi#35-use-namesilocom-api

**Comment by bilogic** [comment]
1. I re-explained the problem better here https://github.com/acmesh-official/acme.sh/issues/6732

> use `--dnssleep`
2. I suppose in your context, could we add a `--dnsterminate`?

```
# the commands here do not wait, instead each terminates immediately after creating the DNS records

acme.sh --issue -d domain1.com -d '*.domain1.com' --dns dns_namesilo --dnsterminate
acme.sh --issue -d domain2.com -d '*.domain2.com' --dns dns_namesilo --dnsterminate
acme.sh --issue -d domain3.com -d '*.domain3.com' --dns dns_namesilo --dnsterminate
acme.sh --issue -d domain4.com -d '*.domain4.com' --dns dns_namesilo --dnsterminate

# we sleep for a total of 900 seconds instead of 3600 seconds (900 x 4 domains)
sleep 900

acme.sh --issue -d domain1.com -d '*.domain1.com' --dns dns_namesilo
acme.sh --issue -d domain2.com -d '*.domain2.com' --dns dns_namesilo
acme.sh --issue -d domain3.com -d '*.domain3.com' --dns dns_namesilo
acme.sh --issue -d domain4.com -d '*.domain4.com' --dns dns_namesilo
```
