### ISSUE TITLE
Installing acme.sh to /root

### ISSUE THREAD

**Issue by blaja** [Neilpang/acme.sh#1998]
Is it ok to install acme.sh to /root ? What is the best practice when it comes to installing and using this script ? Should I use sudo when running it or just be root is fine ? Thanks.

**Comment by Neilpang** [comment]
yes,  it's recommended to installed in `/root`.   but do not use `sudo`.  just `su` to root and install then.

**Comment by blaja** [comment]
Thanks.

**Comment by gxgani** [comment]
> yes, it's recommended to installed in `/root`. but do not use `sudo`. just `su` to root and install then.

Unable to generate a certificate on debian 10 (su'd root)
```
root@server:~# acme.sh --issue --dns dns_cf -d "domain.com" -d "www.domain.com"
It seems that you are using sudo, please read this link first:
https://github.com/Neilpang/acme.sh/wiki/sudo
```
