### ISSUE TITLE
hiding certificate's content output at issue time ?

### ISSUE THREAD

**Issue by centminmod** [Neilpang/acme.sh#200]
When you issue a new certificate, part of the output is the actual contents of the ssl cert itself. Can this be hidden via a flag of some kind already built into acme.sh ? i.e. less verbose mode ?

FYI, I've decided to dump my existing official letsencrypt client integration code and do a total rewrite using your acme.sh client as the sole tool in my acmetool.sh wrapper addon https://community.centminmod.com/posts/31505/ :)  Helps that acme.sh is written in bash shell scripting that I can follow too :+1:

**Comment by Neilpang** [comment]
I saw your post.  Your acmetool.sh is cool.

If the output cert really matters you, I can define a new flag for you to hide the output cert.

what do you think ?

**Comment by centminmod** [comment]
That would be great maybe a quite mode flag that you can later extend to other existing verbose default outputs too

**Comment by Neilpang** [comment]
@centminmod 

Would you like a `--quite`  or `-q`  flag,  which works without any output.

**Comment by centminmod** [comment]
`--quite` seems to fit into existing syntax better :)

**Comment by Neilpang** [comment]
With this `--quite`  flag,  you will get no output at all.
Is that what you want ?

**Comment by centminmod** [comment]
was thinking just the cert contents output at https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L1485 as it's something end users wouldn't really have use for seeing specifically

**Comment by Neilpang** [comment]
Shell script client for startssl.com free certificate.

Hi @centminmod , would like to have a try ?

**Comment by centminmod** [comment]
@Neilpang nice startencrypt ! will give it a whirl when i have time. thanks for heads up!
