### ISSUE TITLE
TLS-ALPN-01 support uses obsolete id-pe-acmeIdentifier OID

### ISSUE THREAD

**Issue by cpu** [Neilpang/acme.sh#2005]
:wave: Hi folks,

I was happy to see `acme.sh` added support for the TLS-ALPN-01 challenge type in https://github.com/Neilpang/acme.sh/pull/1981 Very cool! I know this will be helpful for a number of users.

I noticed however that you're using the obsolete/incorrect `id-pe-acmeIdentifier` OID (`1.3.6.1.5.5.7.1.30.1`) that was specified in [draft-ietf-acme-tls-alpn-01](https://tools.ietf.org/html/draft-ietf-acme-tls-alpn-01):
https://github.com/Neilpang/acme.sh/blob/f99ca918db8e4587ec1437c6815a32a8de49c42f/acme.sh#L1093

That value was in conflict with another IANA assignment and the most-current TLS-ALPN-01 draft ([draft-ietf-tls-alpn-05](https://tools.ietf.org/html/draft-ietf-acme-tls-alpn-05)) updated the OID to `1.3.6.1.5.5.7.1.31`. See [Section 5.1](https://tools.ietf.org/html/draft-ietf-acme-tls-alpn-05#section-5.1).

Let's Encrypt/Boulder presently [allow TLS-ALPN-01 validation for either OID](https://github.com/letsencrypt/boulder/blob/9afa0f7f1967fd4b8c63f4a100a2795461b36609/va/va.go#L801) but we will be removing support for the obsolete OID at an unspecified future date. The sooner you're using the new OID the better :-)

You can test that you're using the correct OID by performing a TLS-ALPN-01 challenge against a [Pebble](https://github.com/letsencrypt/pebble) ACME server running with the `-strict` argument. This implementation will reject the obsolete OID.

Thanks again!

**Comment by Neilpang** [comment]
Thank you so much.
it fixed now.

**Comment by cpu** [comment]
@Neilpang Thanks for the ultra-quick fix! :clinking_glasses:
