### ISSUE TITLE
It is not possible to issue letsencrypt certificate if 80 port is redirected to 443 in existing apache server in Debian 6 Squeeze

### ISSUE THREAD

**Issue by kobruleht** [Neilpang/acme.sh#2008]
In Debian 6 Squeeze with Apache server  port 80 is redirected to 443 and port 443 is used by Apache server itself.
So webroot mode cannot used and using only apache or alpn modes is possible.
However both return errors.

Steps to reproduce:

Run commands 

>  ./acme.sh  --issue  -d www.mytestsite.com  --alpn --tlsport 8443
> ./acme.sh  --issue --apache  -d www.mytestsite.com

Certificate is not issued. Log file contains errors:

**Comment by Neilpang** [comment]
if 443 port is used by apache, you can not use alpn mode.

you can use webroot mode.

**Comment by kobruleht** [comment]
In Mono ASP.NET application, access from web to directories starting with . is disabled. So .well-known directory causes error and webroot mode cannot used.
 How to use directory name with does not start with . in webroot mode ?

Posted also in 
https://github.com/Neilpang/acme.sh/issues/1954
