### ISSUE TITLE
Windows cgywin生成证书后installcert命令无法reloadcmd

### ISSUE THREAD

**Issue by ElysionK** [Neilpang/acme.sh#2013]
$ acme.sh --install-cert -d XXX.com -d *.XXX.com --key-file E:\XXX-cert.pem --fullchain-file E:\XXX-full-chain.pem --reloadcmd "service apache2 force-reload"
[2019年01月 8日  9:57:03] Installing key to:E:\XXX-cert.pem
[2019年01月 8日  9:57:04] Installing full chain to:E:\XXX-full-chain.pem
[2019年01月 8日  9:57:04] Run reload cmd: service apache2 force-reload
/home/Administrator/.acme.sh/acme.sh:行4761: service: 未找到命令
[2019年01月 8日  9:57:04] Reload error for :

生成证书之后从内部路径copy证书到自建路径, 用的apache转发, 根据文档使用的 service apache2 force-reload出现上述错误, 是不是因为apache在windows上, cgywin的unix上根本没有apache ? 还是别的原因

**Comment by ElysionK** [comment]
> 

> $ acme.sh --install-cert -d XXX.com -d *.XXX.com --key-file E:\XXX-cert.pem --fullchain-file E:\XXX-full-chain.pem --reloadcmd "service apache2 force-reload"
> [2019年01月 8日 9:57:03] Installing key to:E:\XXX-cert.pem
> [2019年01月 8日 9:57:04] Installing full chain to:E:\XXX-full-chain.pem
> [2019年01月 8日 9:57:04] Run reload cmd: service apache2 force-reload
> /home/Administrator/.acme.sh/acme.sh:行4761: service: 未找到命令
> [2019年01月 8日 9:57:04] Reload error for :
> 
> 生成证书之后从内部路径copy证书到自建路径, 用的apache转发, 根据文档使用的 service apache2 force-reload出现上述错误, 是不是因为apache在windows上, cgywin的unix上根本没有apache ? 还是别的原因

--------------------------------------------------------------------------------------------------
在wiki找到了cgywin crontab的原因和解决方式,不是太明白, 下载了cygrunsrv之后就执行cron-config就行了吗, 不需要别的脚本了吗,

**Comment by Neilpang** [comment]
现在的版本, 已经不再需要 cron 了.   会使用Windows 自带的 schduler

https://github.com/Neilpang/acme.sh/wiki#4-how-to-run-on-windows-with-cygwin-or-git-bash
