### ISSUE TITLE
 Could not resolve host: get.acme.sh; Unknown error

### ISSUE THREAD

**Issue by wangjia2016** [Neilpang/acme.sh#2014]
Steps to reproduce
------------------

Debug log
-----------------
curl https://get.acme.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0curl: (6) Could not resolve host: get.acme.sh; Unknown error

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
多试几次
