### ISSUE TITLE
如何生成后缀为PEM的证书？

### ISSUE THREAD

**Issue by snoopy83101** [Neilpang/acme.sh#2018]
/root/.acme.sh/*.fengwotuan.com/*.fengwotuan.com.cer
/root/.acme.sh/*.fengwotuan.com/*.fengwotuan.com.key
/root/.acme.sh/*.fengwotuan.com/ca.cer
/root/.acme.sh/*.fengwotuan.com/fullchain.cer

生成成功之后，文件夹里只有这四个。 没有pem的，国内的CDN厂商都要求PEM。
我能否不用自己想办法转换，就让他有pem的证书文件呢？

**Comment by Neilpang** [comment]
cer === PEM

**Comment by cnryb** [comment]
在这儿记录一下，送给有需要的人。
证书内容( PEM格式 )：$ vi domain.cer
证书私钥( PEM格式 )：$ vi domain.key
