### ISSUE TITLE
dnsalias mode not working

### ISSUE THREAD

**Issue by mrizzato** [Neilpang/acme.sh#2024]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode

**Comment by mrizzato** [comment]
Ok, point taken, --domain-alias should be my option.

I have had success (no errors, certificate issued) with the following script:

#!/bin/bash

export CERT_FOLDER="$(find /usr/syno/etc/certificate/_archive/ -maxdepth 1 -mindepth 1 -type d)"
# Make sure $CERT_FOLDER is only one name. Else you have to manually specify the folder.
export CERT_DOMAIN="mydomain.com"
export CERT_DOMAIN_2="www.mydomain.com"
export CERT_DNS="dns_dyn"
/usr/local/share/acme.sh/acme.sh --force --issue -d "$CERT_DOMAIN" --dns "$CERT_DNS$" --domain-alias "$CERT_DOMAIN_2" --certpath "$CERT_FOLDER/cert.pem" --keypath "$CERT_FOLDER/privkey.pem" --fullchainpath "$CERT_FOLDER/fullchain.pem" --capath "$CERT_FOLDER/chain.pem" --reloadcmd "/usr/syno/sbin/synoservicectl --reload nginx" --dnssleep 20

But when accessing my website using domain "www.mydomain.com", I get told by the browser that the certificate is only valid for "mydomain.com". Apparently the --domain-alias oprion has had no effect.

**Comment by FernandoMiguel** [comment]
Very careful with the --force option
You should be using --test until you are comfortable it works

**Comment by mrizzato** [comment]
It works: I did run all the necessary tests and I can get my certificate without problems.
The only issue I have is that I cannot have a certificate that is valid for my main domain and its alias.
Probably I don't properly understand the usage of aliases wit acme.sh.
