### ISSUE TITLE
生成证书之后，还能怎样修改 reloadcmd 的命令?

### ISSUE THREAD

**Issue by xtremforce** [Neilpang/acme.sh#2029]
最初生成证书时 --reloadcmd 里的命令写错了，现在想要修改有什么正确的方法呢？

1、直接修改 ~/.acme.sh/xxx.com/xxx.com.conf 里面的 Le_ReloadCmd='xxxxxx' 是否有效？
2、这个命令是否在 cron 自动renew时会用到？

**Comment by Neilpang** [comment]
1.  可以
2. 会.


建议你用 `--install-cert  -d  example.com  --reloadcmd xxxx`  来修改.
