### ISSUE TITLE
issuing buypass cert not successful, telling me 'Unknown parameter'

### ISSUE THREAD

**Issue by baoang** [Neilpang/acme.sh#2030]
As per the instructions [here](https://github.com/Neilpang/acme.sh/wiki/BuyPass.com-CA) at https://github.com/Neilpang/acme.sh/wiki/BuyPass.com-CA , I tried to issue a BuyPass cert.
```
acme.sh --version
https://github.com/Neilpang/acme.sh
v2.8.0
```
## Step one
`acme.sh --server https://api.buypass.com/acme/directory --register-account  --accountemail my@personal.email`
with the output
```
[Sun Jan 13 09:50:58 EST 2019] Registering account
[Sun Jan 13 09:51:00 EST 2019] Registered
[Sun Jan 13 09:51:00 EST 2019] ACCOUNT_THUMBPRINT='balabala...'
```
It was completed.
## Step two
`acme.sh --server https://api.buypass.com/acme/directory --issue -d mydomain.tld -d pan.mydomain.tld --days 177`
with the output
`Please specify at least one validation method: '--webroot', '--standalone', '--apache', '--nginx' or '--dns' etc.`
Since I set my domain at CloudFlare, and follow the steps of previous LE cert application procedures, I modified the script as this
`acme.sh --dns dns_cf https://api.buypass.com/acme/directory --issue -d mydomain.tld -d pan.mydomain.tld --days 177`
which produced this output
`[Sun Jan 13 10:07:44 EST 2019] Unknown parameter : https://api.buypass.com/acme/directory`

PS, I also tried
``acme.sh --dns dns_cf https://api.buypass.com/acme/directory --issue -d mydomain.tld -d pan.mydomain.tld --days 177` --debug 2`
but cannot find anything new appending the _acme.sh.log_ file.

So, in order to get the buypass free cert, shall I change the para --server to --nginx?
I did the register job successfully with *--server* instead of *--nginx*, and if I have to or prefer the dns mode, how can I bypass/avoid the *unknown parameter* issue?

**Comment by Neilpang** [comment]
```
acme.sh --dns dns_cf   --server  https://api.buypass.com/acme/directory --issue -d mydomain.tld -d ....
```

**Comment by baoang** [comment]
Thank you, @Neilpang 
I tried your script above, but failed with the following output.

```
[Mon Jan 14 06:45:13 EST 2019] Verify finished, start to sign.
[Mon Jan 14 06:45:13 EST 2019] i='2'
[Mon Jan 14 06:45:13 EST 2019] j='16'
[Mon Jan 14 06:45:13 EST 2019] url='https://api.buypass.com/acme/new-cert'
[Mon Jan 14 06:45:13 EST 2019] payload='{"resource": "new-cert", "csr": "MIIblablabla...}'
[Mon Jan 14 06:45:14 EST 2019] POST
[Mon Jan 14 06:45:14 EST 2019] _post_url='https://api.buypass.com/acme/new-cert'
[Mon Jan 14 06:45:14 EST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mon Jan 14 06:45:15 EST 2019] _ret='0'
[Mon Jan 14 06:45:15 EST 2019] code='400'
[Mon Jan 14 06:45:15 EST 2019] Le_LinkCert
[Mon Jan 14 06:45:15 EST 2019] Sign failed: "detail":"Requested combination of domains is not allowed"
[Mon Jan 14 06:45:15 EST 2019] _on_issue_err
[Mon Jan 14 06:45:15 EST 2019] Please check log file for more details: /root/.acme.sh/acme.sh.log
```

**Comment by Neilpang** [comment]
you can only include 2 domain in one buypass cert:
```sh
example.com
www.example.com
```

or 
```
pan.example.com
www.pan.example.com
```
