### ISSUE TITLE
Unable to update challenge

### ISSUE THREAD

**Issue by coswind** [Neilpang/acme.sh#204]
重新添加了子域名，在renew --force时产生下面的错误

Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: Response does not complete challenge","status": 400}

**Comment by Neilpang** [comment]
添加了子域名后， 不要用 `--renew`
直接用 ·`--issue`

**Comment by coswind** [comment]
--issue 会提示retry 无限循环了

**Comment by coswind** [comment]
另外我是使用dns模式

**Comment by Neilpang** [comment]
这可能是一个 bug。   你现在把 `~/.acme.sh/domain.com`  这个目录删掉，从头再来issue 一次。

哪家的dns， 为什么不用 dns api 模式。

**Comment by coswind** [comment]
马云家的，不行我在用dns api试试

**Comment by coswind** [comment]
已经可以了，仍然是dns模式，
步骤是删除目录，issue一次，修改txt记录，在renew一次，成功

**Comment by purldator** [comment]
Greetings.  I just received this same error @coswind reported when attempting to update the dns challenge (nogtk Ubuntu Xenial + Nginx).

````
acme.sh --renew -d weavewordswith.us -d www.weavewordswith.us -d chat.weavewordswith.us -d discuss.weavewordswith.us
[Sun Jun 12 18:18:15 EDT 2016] Skip register account key
[Sun Jun 12 18:18:15 EDT 2016] Creating csr
[Sun Jun 12 18:18:15 EDT 2016] CSR exists, skip
[Sun Jun 12 18:18:15 EDT 2016] Verify each domain
[Sun Jun 12 18:18:15 EDT 2016] Verifying:weavewordswith.us
[Sun Jun 12 18:18:16 EDT 2016] weavewordswith.us:Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: Response does not complete challenge","status": 400}
[Sun Jun 12 18:18:16 EDT 2016] Skip for removelevel:
````

txt fields are properly set in dns.

I attempted to translate @coswind's last responses that I surmise are the answers to fix this error.  I know Let's Encrypt changed their dns api, but that does not apply to me: I installed acme.sh yesterday.

Something about removing a directory?

Any help appreciated.

**Comment by Neilpang** [comment]
Hi,
In in the first log of yours,  you can see only the domain `chat.weavewordswith.us` is verified failed.

In this case, you can not run `--renew` again,  since the tokens for  the other domains are already expired. when you run with `--renew` again, it tries to verify the others too, so, it fails in the second time.

In this case,  please remove the `weavewordswith.us` folder in `~/acme.sh/`  again.
And start with `--issue`,   then wait for all the txt records to take effect, then  run with `--renew`.

I know that the `--renew` can be run once seems wired here in your case, but I may fix it more graceful later.

**Comment by Neilpang** [comment]
@purldator

**Comment by purldator** [comment]
Thank you for the response, @Neilpang .  I tried using lexicon for the dns api.  I am thinking the dns propagation was a problem (time between --issue and --renew) and thought automating the process with my dns provider (namesilo) may help.  I installed lexicon and fetched my namesilo api key.  

That *seemed* to work, but 60 seconds was not enough time:

````
[Sun Jun 12 21:05:01 EDT 2016] Sleep 60 seconds for the txt records to take effect
[Sun Jun 12 21:06:01 EDT 2016] Verifying:weavewordswith.us
[Sun Jun 12 21:06:08 EDT 2016] weavewordswith.us:Verify error:DNS problem: NXDOMAIN looking up TXT for _acme-challenge.weavewordswith.us
[Sun Jun 12 21:06:08 EDT 2016] Skip for removelevel:
````

I did not realize --renew reads a domain's --issue method from corresponding folder (ie, ~/.acme.sh/weavewordswith.us).

So, when reentering --renew, the dns txt records for the tokens were duplicated by name, but had different txt token values.

````
[Sun Jun 12 21:08:09 EDT 2016] Sleep 60 seconds for the txt records to take effect
[Sun Jun 12 21:09:09 EDT 2016] Verifying:weavewordswith.us
[Sun Jun 12 21:09:16 EDT 2016] weavewordswith.us:Verify error:Correct value not found for DNS challenge
[Sun Jun 12 21:09:16 EDT 2016] Skip for removelevel:
````

I have deleted all dns records related to the _acme-challenge tokens, removed ~/.acme.sh, reset my terminal and cleared my cron tab.  That way, I am starting over.  

When do tokens expire?  I think I have a problem with token expiration vs dns propagation.

**Comment by Neilpang** [comment]
fixed 0e38c60da35620059ca3aa99a0982276260fc3c4

I just added a new param:   `--dnssleep`  to specify the sleeping time.

Sleep 120 seconds:

``
acme.sh --issue  .......    --dns  ....    --dnssleep  120`
``

**Comment by purldator** [comment]
Thank you, @Neilpang!  I shall use that new flag tomorrow once dns straightens out from cleaning out all those txt dns records.

**Comment by purldator** [comment]
````
 acme.sh --issue -d weavewordswith.us --dns dns_lexicon -d www.weavewordswith.us -d chat.weavewordswith.us -d discuss.weavewordswith.us --dnssleep 960
[Mon Jun 13 13:25:26 EDT 2016] Creating account key
[Mon Jun 13 13:25:26 EDT 2016] Use default length 2048
[Mon Jun 13 13:25:27 EDT 2016] Registering account
[Mon Jun 13 13:25:29 EDT 2016] Registered
[Mon Jun 13 13:25:29 EDT 2016] Creating domain key
[Mon Jun 13 13:25:29 EDT 2016] Use length 2048
[Mon Jun 13 13:25:29 EDT 2016] Creating csr
[Mon Jun 13 13:25:29 EDT 2016] Multi domain='DNS:www.weavewordswith.us,DNS:chat.weavewordswith.us,DNS:discuss.weavewordswith.us'
[Mon Jun 13 13:25:29 EDT 2016] Verify each domain
[Mon Jun 13 13:25:29 EDT 2016] Getting webroot for domain='weavewordswith.us'
[Mon Jun 13 13:25:29 EDT 2016] Getting token for domain='weavewordswith.us'
[Mon Jun 13 13:25:30 EDT 2016] Getting webroot for domain='www.weavewordswith.us'
[Mon Jun 13 13:25:30 EDT 2016] Getting token for domain='www.weavewordswith.us'
[Mon Jun 13 13:25:32 EDT 2016] Getting webroot for domain='chat.weavewordswith.us'
[Mon Jun 13 13:25:32 EDT 2016] Getting token for domain='chat.weavewordswith.us'
[Mon Jun 13 13:25:34 EDT 2016] Getting webroot for domain='discuss.weavewordswith.us'
[Mon Jun 13 13:25:34 EDT 2016] Getting token for domain='discuss.weavewordswith.us'
[Mon Jun 13 13:25:36 EDT 2016] Found domain api file: /home/yautweh/.acme.sh/dnsapi/dns_lexicon.sh
Namespace(action='create', auth_token=None, content='****', domain='weavewordswith.us', identifier=None, name='_acme-challenge.weavewordswith.us.', priority=None, provider_name='namesilo', ttl=None, type='TXT')
No handlers could be found for logger "tldextract"
create_record: True
[Mon Jun 13 13:25:38 EDT 2016] Found domain api file: /home/yautweh/.acme.sh/dnsapi/dns_lexicon.sh
Namespace(action='create', auth_token=None, content='****', domain='www.weavewordswith.us', identifier=None, name='_acme-challenge.www.weavewordswith.us.', priority=None, provider_name='namesilo', ttl=None, type='TXT')
No handlers could be found for logger "tldextract"
create_record: True
[Mon Jun 13 13:25:40 EDT 2016] Found domain api file: /home/yautweh/.acme.sh/dnsapi/dns_lexicon.sh
Namespace(action='create', auth_token=None, content='****', domain='chat.weavewordswith.us', identifier=None, name='_acme-challenge.chat.weavewordswith.us.', priority=None, provider_name='namesilo', ttl=None, type='TXT')
No handlers could be found for logger "tldextract"
create_record: True
[Mon Jun 13 13:25:43 EDT 2016] Found domain api file: /home/yautweh/.acme.sh/dnsapi/dns_lexicon.sh
Namespace(action='create', auth_token=None, content='****', domain='discuss.weavewordswith.us', identifier=None, name='_acme-challenge.discuss.weavewordswith.us.', priority=None, provider_name='namesilo', ttl=None, type='TXT')
No handlers could be found for logger "tldextract"
create_record: True
[Mon Jun 13 13:25:45 EDT 2016] Sleep 960 seconds for the txt records to take effect
[Mon Jun 13 13:41:45 EDT 2016] Verifying:weavewordswith.us
[Mon Jun 13 13:41:52 EDT 2016] Success
[Mon Jun 13 13:41:52 EDT 2016] Skip for removelevel:
[Mon Jun 13 13:41:52 EDT 2016] Verifying:www.weavewordswith.us
[Mon Jun 13 13:41:59 EDT 2016] Success
[Mon Jun 13 13:41:59 EDT 2016] Skip for removelevel:
[Mon Jun 13 13:41:59 EDT 2016] Verifying:chat.weavewordswith.us
[Mon Jun 13 13:42:07 EDT 2016] Success
[Mon Jun 13 13:42:07 EDT 2016] Skip for removelevel:
[Mon Jun 13 13:42:07 EDT 2016] Verifying:discuss.weavewordswith.us
[Mon Jun 13 13:42:14 EDT 2016] Success
[Mon Jun 13 13:42:14 EDT 2016] Skip for removelevel:
[Mon Jun 13 13:42:14 EDT 2016] Verify finished, start to sign.
[Mon Jun 13 13:42:16 EDT 2016] Cert success.
````

**Success!**  Thank you for adding `--dnssleep` option, @Neilpang. 🙏

**Comment by Neilpang** [comment]
Hi,   @purldator 

Can you please edit this page: https://github.com/Neilpang/acme.sh/wiki/How-to-use-lexicon-dns-api ?


And append your usage of namesilo api to that page, so that it can help more people.

Thanks.

**Comment by purldator** [comment]
@Neilpang; I have made the requested edits.

**Comment by Neilpang** [comment]
@purldator 
Cool.  Thank you a lot.
