### ISSUE TITLE
TLS-SNI-01 validation is reaching end-of-life and will stop working on **February 13th, 2019.**

### ISSUE THREAD

**Issue by hacknlove** [Neilpang/acme.sh#2041]
¿Is this affecting acme.sh?

In that case, is there some patch coming soon? or should we get our certificates with other means?

**Comment by FernandoMiguel** [comment]
TLS 01 has been suspended many months ago, and only remain working for existing certs.
You need to reissue with ALPN

**Comment by Neilpang** [comment]
please use other methods to issue your cert.  the  tls-sni method will not work soon.

**Comment by hacknlove** [comment]
how do i get to know what certificates has been issued with TLS01?

should i reissue all my certificates to be sure?

**Comment by FernandoMiguel** [comment]
no harm done in re-issuing

**Comment by Neilpang** [comment]
@FernandoMiguel 

I think @hacknlove  is talking about this:  https://community.letsencrypt.org/t/february-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209


The tls-sni will be totally removed recently.

**Comment by FernandoMiguel** [comment]
Yeah, I read that post too.
I think sni users are being notified via email

**Comment by samweisgamdschie** [comment]
Hi, where can I find account information? I cant remember creating an account for any of my acme.sh installation. In acme.sh there is no option for showing account information. Also `acme.sh --info` only shows some basic information about issued certificates.

`acme.sh --issue -d dom.org -d www.dom.org -w /path/dom.org/ --keylength ec-384`

This way I issued all my certificates. Maybe you can tell me if I have to change something?! Thanks in advance.

**Comment by FernandoMiguel** [comment]
> Hi, where can I find account information? I cant remember creating an account for any of my acme.sh installation. In acme.sh there is no option for showing account information. Also `acme.sh --info` only shows some basic information about issued certificates.
> 
> `acme.sh --issue -d dom.org -d www.dom.org -w /path/dom.org/ --keylength ec-384`
> 
> This way I issued all my certificates. Maybe you can tell me if I have to change something?! Thanks in advance.

you are using webroot method, nothing to do with this ticket validation method.
