### ISSUE TITLE
cloudxns限制最多10条txt导致域名校验失败

### ISSUE THREAD

**Issue by evilkong** [Neilpang/acme.sh#2045]
今天上去手动更新了一下acme.sh版本，然后顺道renew一下证书，然后悲催了。
有一个域名一直dns校验失败。折腾了半天。才发现是因为txt数量问题。

原因：
由于cloudxns限制最多10条txt记录，而使用domain-alias模式下，一个域名占用两个-d，test.com 和 *.test.com 。那么，问题来了：6个域名一起一张证书的话，导致一次性产生12条txt记录，而cx最多只能10条，更多的会无法添加，然后会导致dns核验一直失败。

也尝试过使用 challenge-alias 貌似无果。

求教解决方法，谢谢！

**Comment by Neilpang** [comment]
domain-alias   可以多指定几个 alias

https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode
