### ISSUE TITLE
Issue with acme + restarting MySQL

### ISSUE THREAD

**Issue by qcybb** [Neilpang/acme.sh#2049]
I'm using acme v2.7.9 + MySQL v5.6 on FreeBSD v11.2

The installer added the following line to end of .cshrc file
`source "/root/.acme.sh/acme.sh.csh"`

In doing so, it causes this issue when restarting MySQL

> $ sudo /usr/local/etc/rc.d/mysql-server restart
> Stopping mysql.
> /root/.acme.sh/acme.sh.csh: Permission denied.
> Waiting for PIDS: 61398.
> Starting mysql.
> /root/.acme.sh/acme.sh.csh: Permission denied.
> $

Commenting out the "source" line fixes this issue.

Any ideas how to properly fix this issue?

**Comment by Berzerker** [comment]
Is the .cshrc file for your user and not root? You may be running the restart command with sudo, but any subsequent commands run in the background might be running under your regular user, which doesn’t have permissions into the ‘/root’ home folder.

**Comment by qcybb** [comment]
I managed to solve the issue by deleting everything the installer did and then installed it via the FreeBSD ports system. The version in the ports system created a special "acme" user/group and stores everything in a different folder. 

Everything is running just fine now, so I'll go ahead and close the issue.
