### ISSUE TITLE
想申请泛域名证书，用http的方式申请以便可以自动更新，能实现吗？

### ISSUE THREAD

**Issue by adrianzhang** [Neilpang/acme.sh#2050]
看了很多教程帮助。
要么是泛域名证书用DNS方式申请
要么是用http方式申请证书以便可以自动更新。
就没有找到申请泛域名证书还可以自动更新的方式。

**Comment by adrianzhang** [comment]
> 1. 泛域名 只能通过 dns 方式申请。
> 2. 使用 dns api 方式， 默认就算是可以自动更新的。

抱歉，刚刚更新了acme.sh，目前在系统里配置的是zsh，`source .bashrc`后`acme -renew -d domain.com`成功执行。
之前不成功大概有两个原因：
1) 老版本acme，zsh
2) 没有insert certificates to nginx location.

现在证明，使用同样的cloudflare配置，DNS方式申请以及手动更新泛域名证书成功。

**Comment by AgainCrazyCode** [comment]
DNS方式不太方便，HTTP方式，域名太多也麻烦。暂时没发现十全十美的
