### ISSUE TITLE
不能自动续期，请教该如何处理

### ISSUE THREAD

**Issue by EurekaChen** [Neilpang/acme.sh#2062]
**具体调试输出如下：**

ubuntu@eureka_ubuntu_16044_tencent:~/.acme.sh$ **./acme.sh --cron --debug 2**
[Sun Jan 27 11:38:19 CST 2019] Lets find script dir.
[Sun Jan 27 11:38:19 CST 2019] _SCRIPT_='./acme.sh'
[Sun Jan 27 11:38:19 CST 2019] _script='/home/ubuntu/.acme.sh/acme.sh'
[Sun Jan 27 11:38:19 CST 2019] _script_home='/home/ubuntu/.acme.sh'
[Sun Jan 27 11:38:19 CST 2019] Using config home:/home/ubuntu/.acme.sh
[Sun Jan 27 11:38:19 CST 2019] LE_WORKING_DIR='/home/ubuntu/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.0
[Sun Jan 27 11:38:19 CST 2019] Using config home:/home/ubuntu/.acme.sh
[Sun Jan 27 11:38:19 CST 2019] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:19 CST 2019] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Jan 27 11:38:19 CST 2019] ===Starting cron===
[Sun Jan 27 11:38:19 CST 2019] Using config home:/home/ubuntu/.acme.sh
[Sun Jan 27 11:38:19 CST 2019] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:19 CST 2019] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Jan 27 11:38:19 CST 2019] _stopRenewOnError
[Sun Jan 27 11:38:19 CST 2019] di='/home/ubuntu/.acme.sh/echain.top/'
[Sun Jan 27 11:38:19 CST 2019] d='echain.top'
[Sun Jan 27 11:38:19 CST 2019] Using config home:/home/ubuntu/.acme.sh
[Sun Jan 27 11:38:19 CST 2019] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:19 CST 2019] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Jan 27 11:38:19 CST 2019] DOMAIN_PATH='/home/ubuntu/.acme.sh/echain.top'
[Sun Jan 27 11:38:19 CST 2019] Renew: 'echain.top'
[Sun Jan 27 11:38:19 CST 2019] Le_API='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:19 CST 2019] Using config home:/home/ubuntu/.acme.sh
[Sun Jan 27 11:38:19 CST 2019] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:19 CST 2019] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Jan 27 11:38:19 CST 2019] Skip, Next renewal time is: Mon Mar 11 02:36:31 UTC 2019
[Sun Jan 27 11:38:19 CST 2019] Add '--force' to force to renew.
[Sun Jan 27 11:38:19 CST 2019] Return code: 2
[Sun Jan 27 11:38:19 CST 2019] Skipped echain.top
[Sun Jan 27 11:38:19 CST 2019] di='/home/ubuntu/.acme.sh/eeblog.net/'
[Sun Jan 27 11:38:19 CST 2019] d='eeblog.net'
[Sun Jan 27 11:38:19 CST 2019] Using config home:/home/ubuntu/.acme.sh
[Sun Jan 27 11:38:19 CST 2019] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:19 CST 2019] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Jan 27 11:38:19 CST 2019] DOMAIN_PATH='/home/ubuntu/.acme.sh/eeblog.net'
[Sun Jan 27 11:38:19 CST 2019] Renew: 'eeblog.net'
[Sun Jan 27 11:38:19 CST 2019] Le_API='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:19 CST 2019] Using config home:/home/ubuntu/.acme.sh
[Sun Jan 27 11:38:19 CST 2019] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:19 CST 2019] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Jan 27 11:38:19 CST 2019] _main_domain='eeblog.net'
[Sun Jan 27 11:38:19 CST 2019] _alt_domains='no'
[Sun Jan 27 11:38:19 CST 2019] 'nginx:' does not contain 'dns'
[Sun Jan 27 11:38:19 CST 2019] Using ACME_DIRECTORY: https://acme-v01.api.letsencrypt.org/directory
[Sun Jan 27 11:38:19 CST 2019] _init api for server: https://acme-v01.api.letsencrypt.org/directory
[Sun Jan 27 11:38:19 CST 2019] GET
[Sun Jan 27 11:38:19 CST 2019] url='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:19 CST 2019] timeout=
[Sun Jan 27 11:38:19 CST 2019] _CURL='curl -L --silent --dump-header /home/ubuntu/.acme.sh/http.header  --trace-ascii /tmp/tmp.xCgw1Jpd5j  -g '
[Sun Jan 27 11:38:20 CST 2019] ret='0'
[Sun Jan 27 11:38:20 CST 2019] response='{
  "YbE8H3-MYpM": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}'
[Sun Jan 27 11:38:20 CST 2019] ACME_KEY_CHANGE='https://acme-v01.api.letsencrypt.org/acme/key-change'
[Sun Jan 27 11:38:20 CST 2019] ACME_NEW_AUTHZ='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Sun Jan 27 11:38:20 CST 2019] ACME_NEW_ORDER='https://acme-v01.api.letsencrypt.org/acme/new-cert'
[Sun Jan 27 11:38:20 CST 2019] ACME_NEW_ACCOUNT='https://acme-v01.api.letsencrypt.org/acme/new-reg'
[Sun Jan 27 11:38:20 CST 2019] ACME_REVOKE_CERT='https://acme-v01.api.letsencrypt.org/acme/revoke-cert'
[Sun Jan 27 11:38:20 CST 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Sun Jan 27 11:38:20 CST 2019] ACME_NEW_NONCE
[Sun Jan 27 11:38:20 CST 2019] ACME_VERSION
[Sun Jan 27 11:38:20 CST 2019] Le_NextRenewTime='1545712543'
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.conf: Permission denied
./acme.sh: line 1972: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.conf: Permission denied
./acme.sh: line 1972: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.conf: Permission denied
[Sun Jan 27 11:38:20 CST 2019] _on_before_issue
[Sun Jan 27 11:38:20 CST 2019] _chk_main_domain='eeblog.net'
[Sun Jan 27 11:38:20 CST 2019] _chk_alt_domains
[Sun Jan 27 11:38:20 CST 2019] 'nginx:' does not contain 'no'
[Sun Jan 27 11:38:20 CST 2019] Le_LocalAddress
[Sun Jan 27 11:38:20 CST 2019] d='eeblog.net'
[Sun Jan 27 11:38:20 CST 2019] Check for domain='eeblog.net'
[Sun Jan 27 11:38:20 CST 2019] _currentRoot='nginx:'
[Sun Jan 27 11:38:20 CST 2019] d
[Sun Jan 27 11:38:20 CST 2019] 'nginx:' does not contain 'apache'
[Sun Jan 27 11:38:20 CST 2019] _saved_account_key_hash='6ik5eAgB8iM9FxOwpNxdwuy/NZooyjY57t0ih/JLrOI='
[Sun Jan 27 11:38:20 CST 2019] _saved_account_key_hash is not changed, skip register account.
[Sun Jan 27 11:38:20 CST 2019] Read key length:
[Sun Jan 27 11:38:20 CST 2019] _createcsr
[Sun Jan 27 11:38:20 CST 2019] domain='eeblog.net'
[Sun Jan 27 11:38:20 CST 2019] domainlist
[Sun Jan 27 11:38:20 CST 2019] csrkey='/home/ubuntu/.acme.sh/eeblog.net/eeblog.net.key'
[Sun Jan 27 11:38:20 CST 2019] csr='/home/ubuntu/.acme.sh/eeblog.net/eeblog.net.csr'
[Sun Jan 27 11:38:20 CST 2019] csrconf='/home/ubuntu/.acme.sh/eeblog.net/eeblog.net.csr.conf'
./acme.sh: line 1065: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.csr.conf: Permission denied
[Sun Jan 27 11:38:20 CST 2019] Single domain='eeblog.net'
./acme.sh: line 1072: /home/ubuntu/.acme.sh/eeblog.net/eeblog.net.csr.conf: Permission denied
[Sun Jan 27 11:38:20 CST 2019] _is_idn_d='eeblog.net'
[Sun Jan 27 11:38:20 CST 2019] _idn_temp
[Sun Jan 27 11:38:20 CST 2019] _csr_cn='eeblog.net'
/home/ubuntu/.acme.sh/eeblog.net/eeblog.net.csr: Permission denied
139941466560152:error:0200100D:system library:fopen:Permission denied:bss_file.c:398:fopen('/home/ubuntu/.acme.sh/eeblog.net/eeblog.net.csr','w')
139941466560152:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
[Sun Jan 27 11:38:20 CST 2019] Create CSR error.
[Sun Jan 27 11:38:20 CST 2019] pid
[Sun Jan 27 11:38:20 CST 2019] No need to restore nginx, skip.
[Sun Jan 27 11:38:20 CST 2019] _clearupdns
[Sun Jan 27 11:38:20 CST 2019] dnsadded
[Sun Jan 27 11:38:20 CST 2019] vlist
[Sun Jan 27 11:38:20 CST 2019] skip dns.
[Sun Jan 27 11:38:20 CST 2019] _on_issue_err
[Sun Jan 27 11:38:20 CST 2019] Please check log file for more details: /home/ubuntu/.acme.sh/acme.sh.log
[Sun Jan 27 11:38:20 CST 2019] _chk_vlist
[Sun Jan 27 11:38:20 CST 2019] 'nginx:' does not contain 'dns'
[Sun Jan 27 11:38:20 CST 2019] socat doesn't exists.
[Sun Jan 27 11:38:20 CST 2019] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.2g  1 Mar 2016
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.10.3 (Ubuntu)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-stream --with-stream_ssl_module --with-mail --with-mail_ssl_module --with-threads
socat:
[Sun Jan 27 11:38:20 CST 2019] Return code: 1
[Sun Jan 27 11:38:20 CST 2019] Error renew eeblog.net.
[Sun Jan 27 11:38:20 CST 2019] di='/home/ubuntu/.acme.sh/eeeeee.org/'
[Sun Jan 27 11:38:20 CST 2019] d='eeeeee.org'
[Sun Jan 27 11:38:20 CST 2019] Using config home:/home/ubuntu/.acme.sh
[Sun Jan 27 11:38:20 CST 2019] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:20 CST 2019] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Jan 27 11:38:20 CST 2019] DOMAIN_PATH='/home/ubuntu/.acme.sh/eeeeee.org'
[Sun Jan 27 11:38:20 CST 2019] Renew: 'eeeeee.org'
[Sun Jan 27 11:38:20 CST 2019] Le_API='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:20 CST 2019] Using config home:/home/ubuntu/.acme.sh
[Sun Jan 27 11:38:20 CST 2019] ACME_DIRECTORY='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:20 CST 2019] _ACME_SERVER_HOST='acme-v01.api.letsencrypt.org'
[Sun Jan 27 11:38:20 CST 2019] _main_domain='eeeeee.org'
[Sun Jan 27 11:38:20 CST 2019] _alt_domains='no'
[Sun Jan 27 11:38:20 CST 2019] 'nginx:' does not contain 'dns'
[Sun Jan 27 11:38:20 CST 2019] Using ACME_DIRECTORY: https://acme-v01.api.letsencrypt.org/directory
[Sun Jan 27 11:38:20 CST 2019] _init api for server: https://acme-v01.api.letsencrypt.org/directory
[Sun Jan 27 11:38:20 CST 2019] GET
[Sun Jan 27 11:38:20 CST 2019] url='https://acme-v01.api.letsencrypt.org/directory'
[Sun Jan 27 11:38:20 CST 2019] timeout=
[Sun Jan 27 11:38:20 CST 2019] _CURL='curl -L --silent --dump-header /home/ubuntu/.acme.sh/http.header  --trace-ascii /tmp/tmp.2ymEa2zEnL  -g '
[Sun Jan 27 11:38:20 CST 2019] ret='0'
[Sun Jan 27 11:38:20 CST 2019] response='{
  "0dO1ODfFrfI": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}'
[Sun Jan 27 11:38:20 CST 2019] ACME_KEY_CHANGE='https://acme-v01.api.letsencrypt.org/acme/key-change'
[Sun Jan 27 11:38:20 CST 2019] ACME_NEW_AUTHZ='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Sun Jan 27 11:38:20 CST 2019] ACME_NEW_ORDER='https://acme-v01.api.letsencrypt.org/acme/new-cert'
[Sun Jan 27 11:38:20 CST 2019] ACME_NEW_ACCOUNT='https://acme-v01.api.letsencrypt.org/acme/new-reg'
[Sun Jan 27 11:38:20 CST 2019] ACME_REVOKE_CERT='https://acme-v01.api.letsencrypt.org/acme/revoke-cert'
[Sun Jan 27 11:38:20 CST 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Sun Jan 27 11:38:20 CST 2019] ACME_NEW_NONCE
[Sun Jan 27 11:38:20 CST 2019] ACME_VERSION
[Sun Jan 27 11:38:20 CST 2019] Le_NextRenewTime='1545697902'
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.conf: Permission denied
./acme.sh: line 1972: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.conf: Permission denied
./acme.sh: line 1972: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.conf: Permission denied
./acme.sh: line 1937: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.conf: Permission denied
[Sun Jan 27 11:38:20 CST 2019] _on_before_issue
[Sun Jan 27 11:38:20 CST 2019] _chk_main_domain='eeeeee.org'
[Sun Jan 27 11:38:20 CST 2019] _chk_alt_domains
[Sun Jan 27 11:38:20 CST 2019] 'nginx:' does not contain 'no'
[Sun Jan 27 11:38:20 CST 2019] Le_LocalAddress
[Sun Jan 27 11:38:20 CST 2019] d='eeeeee.org'
[Sun Jan 27 11:38:20 CST 2019] Check for domain='eeeeee.org'
[Sun Jan 27 11:38:20 CST 2019] _currentRoot='nginx:'
[Sun Jan 27 11:38:20 CST 2019] d
[Sun Jan 27 11:38:20 CST 2019] 'nginx:' does not contain 'apache'
[Sun Jan 27 11:38:20 CST 2019] _saved_account_key_hash='6ik5eAgB8iM9FxOwpNxdwuy/NZooyjY57t0ih/JLrOI='
[Sun Jan 27 11:38:20 CST 2019] _saved_account_key_hash is not changed, skip register account.
[Sun Jan 27 11:38:20 CST 2019] Read key length:
[Sun Jan 27 11:38:20 CST 2019] _createcsr
[Sun Jan 27 11:38:20 CST 2019] domain='eeeeee.org'
[Sun Jan 27 11:38:20 CST 2019] domainlist
[Sun Jan 27 11:38:20 CST 2019] csrkey='/home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.key'
[Sun Jan 27 11:38:20 CST 2019] csr='/home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.csr'
[Sun Jan 27 11:38:20 CST 2019] csrconf='/home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.csr.conf'
./acme.sh: line 1065: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.csr.conf: Permission denied
[Sun Jan 27 11:38:20 CST 2019] Single domain='eeeeee.org'
./acme.sh: line 1072: /home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.csr.conf: Permission denied
[Sun Jan 27 11:38:20 CST 2019] _is_idn_d='eeeeee.org'
[Sun Jan 27 11:38:20 CST 2019] _idn_temp
[Sun Jan 27 11:38:20 CST 2019] _csr_cn='eeeeee.org'
/home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.csr: Permission denied
140140822144664:error:0200100D:system library:fopen:Permission denied:bss_file.c:398:fopen('/home/ubuntu/.acme.sh/eeeeee.org/eeeeee.org.csr','w')
140140822144664:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
[Sun Jan 27 11:38:21 CST 2019] Create CSR error.
[Sun Jan 27 11:38:21 CST 2019] pid
[Sun Jan 27 11:38:21 CST 2019] No need to restore nginx, skip.
[Sun Jan 27 11:38:21 CST 2019] _clearupdns
[Sun Jan 27 11:38:21 CST 2019] dnsadded
[Sun Jan 27 11:38:21 CST 2019] vlist
[Sun Jan 27 11:38:21 CST 2019] skip dns.
[Sun Jan 27 11:38:21 CST 2019] _on_issue_err
[Sun Jan 27 11:38:21 CST 2019] Please check log file for more details: /home/ubuntu/.acme.sh/acme.sh.log
[Sun Jan 27 11:38:21 CST 2019] _chk_vlist
[Sun Jan 27 11:38:21 CST 2019] 'nginx:' does not contain 'dns'
[Sun Jan 27 11:38:21 CST 2019] socat doesn't exists.
[Sun Jan 27 11:38:21 CST 2019] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.2g  1 Mar 2016
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.10.3 (Ubuntu)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-stream --with-stream_ssl_module --with-mail --with-mail_ssl_module --with-threads
socat:
[Sun Jan 27 11:38:21 CST 2019] Return code: 1
[Sun Jan 27 11:38:21 CST 2019] Error renew eeeeee.org.
[Sun Jan 27 11:38:21 CST 2019] di='/home/ubuntu/.acme.sh/eureka.name/'
[Sun Jan 27 11:38:21 CST 2019] d='eureka.name'
…… 因接下去内容还有较多，故省略

**Comment by EurekaChen** [comment]
另外，在使用https后，把原来http的配置已经取消了，是不是也不能更新，加上sudo后运行crontab中的内容，会有如下提示：
 Renew: 'eeblog.net'
[Sun Jan 27 11:55:16 CST 2019] Single domain='eeblog.net'
[Sun Jan 27 11:55:16 CST 2019] Getting domain auth token for each domain
[Sun Jan 27 11:55:16 CST 2019] Getting webroot for domain='eeblog.net'
[Sun Jan 27 11:55:16 CST 2019] Getting new-authz for domain='eeblog.net'
[Sun Jan 27 11:55:17 CST 2019] The new-authz request is ok.
[Sun Jan 27 11:55:18 CST 2019] Verifying: eeblog.net
[Sun Jan 27 11:55:18 CST 2019] Nginx mode for domain:eeblog.net
[Sun Jan 27 11:55:18 CST 2019] Found conf file: /etc/nginx/sites-enabled/eeblog.net
[Sun Jan 27 11:55:18 CST 2019] Backup /etc/nginx/sites-enabled/eeblog.net to /home/ubuntu/.acme.sh/eeblog.net/backup/eeblog.net.nginx.conf
[Sun Jan 27 11:55:18 CST 2019] Check the nginx conf before setting up.
[Sun Jan 27 11:55:18 CST 2019] OK, Set up nginx config file
[Sun Jan 27 11:55:18 CST 2019] nginx conf is done, let's check it again.
[Sun Jan 27 11:55:18 CST 2019] Reload nginx
[Sun Jan 27 11:55:23 CST 2019] eeblog.net:Verify error:Invalid response from http://eeblog.net/.well-known/acme-challenge/q5Hi8kVe01GNTigiuuE-duN0opUBTmT8gCYRbCnLuZo [150.109.54.155]: 404
[Sun Jan 27 11:55:23 CST 2019] Restoring from /home/ubuntu/.acme.sh/eeblog.net/backup/eeblog.net.nginx.conf to /etc/nginx/sites-enabled/eeblog.net
[Sun Jan 27 11:55:23 CST 2019] Reload nginx
[Sun Jan 27 11:55:23 CST 2019] Please check log file for more details: /home/ubuntu/.acme.sh/acme.sh.log
[Sun Jan 27 11:55:24 CST 2019] Error renew eeblog.net.

**Comment by Neilpang** [comment]
你这是权限问题.   绝对不要用 `sudo acme.sh -- ....`,  除非你知道你在做什么.
因为你在sudo 时能完成的操作,   不能再自动renew 时完成.  自动的 cron 时不带sudo 的.

建议卸载 acme.sh,  然后在root下重新安装,并设置一遍.
```sh
acme.sh --uninstall

```

```sh
sudo su
curl https://get.acme.sh | sh
bash
acme.sh --issue -d xxxx   --nginx ....
```


另外, 我个人建议使用 webroot mode

**Comment by EurekaChen** [comment]
非常感谢及时的回复！我也是因为没有找到恰当的方法运行，所以一旦遇到Permission问题时，我就会使用sudo来解决。所以我基本上都是这样：sudo ./acme.sh 运行的。
我一般不用root登录，所以当时安装时也没有使用root，.一切看上去都还正常。只是现在crontab时遇到了权限问题，因为有好几个站，所以也不想重新操作一遍。我想是不是给crontab加上权限就能解决这个问题？
