### ISSUE TITLE
I can't even ping _acme-challenge.example.com(无法访问_acme-challenge.example.com)

### ISSUE THREAD

**Issue by Jaggle** [Neilpang/acme.sh#2065]
无法ping通`_acme-challenge.example.com`，但是在我本地的osx上是可以的，而服务器（centos 7)却不行，使用curl命令也无法访问，我想是因为`_acme-change`的前缀`_`导致了服务器触发了什么限制吗？

正在使用dns alias mode,错误信息如下：

```
example.com:Verify error:No TXT record found at _acme-challenge.example.com
```

抱歉我认为这不是acme.sh的错误，因此不贴debug信息了，只想问一下服务器为什么无法访问 `_acme-challenge.example.com`呢？

另外：我设置了其他非`_`开头的cname解析，比如`acme.example.com`，服务器上却可以正常ping通和访问。

**Comment by Jaggle** [comment]
```
dig _acme-change.example.com
```

可以正常返回解析信息，但是curl却不行，奇怪

**Comment by Neilpang** [comment]
不要什么东西都用 ping 来解决.  解析成功跟ping 时完全不沾边的事情.

https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

**Comment by Jaggle** [comment]
解析应当是成功的，毕竟我本地是可以正常ping和curl，服务器无法ping和curl，但是dig命令返回的信息似乎非常OK(敏感信息已打码)：

```
➔ dig _acme-challenge.example.com

; <<>> DiG 9.9.4-RedHat-9.9.4-72.el7 <<>> _acme-challenge.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44373
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_acme-challenge.example.com.	IN	A

;; ANSWER SECTION:
_acme-challenge.example.com. 600 IN	CNAME	www.validation-only.com.
www.validation-only.com.		600	IN	A	x.x.x.x

;; Query time: 3 msec
;; SERVER: 100.100.2.138#53(100.100.2.138)
;; WHEN: Mon Jan 28 22:15:50 CST 2019
;; MSG SIZE  rcvd: 102
```

以下是curl错误：

```
➔ curl  http://_acme-change.example.com
curl: (6) Could not resolve host: _acme-change.example.com; Name or service not known
```

回复这么快，非常感谢！

**Comment by Jaggle** [comment]
折腾一下，终于好了，原来我的cname解析是这样的：

```
_acme-challenge.importran-domain.com -> validation-only.com
```

之前我用dns alias mode是成功的，这次可能是因为在某个论坛（好像是le自家的）看到有人说validation-only.com不需要`_acme-challenge`前缀，所以我就没加，正确的cname解析为：

```
_acme-challenge.importran-domain.com -> _acme-challenge.validation-only.com
```

---

域名"_"前缀应该是允许的，但是RFC相关文档说不支持，curl和ping是完全遵守该文档的，dig是用的自己的dns解析，因此才会出现上面的乌龙。

最后还是感谢大佬创造了acme.sh。
