### ISSUE TITLE
一直报错，，返回码500

### ISSUE THREAD

**Issue by coeus-lei** [Neilpang/acme.sh#2067]
126 [Wed Jan 30 19:04:52 CST 2019] checking
127 [Wed Jan 30 19:04:52 CST 2019] GET
128 [Wed Jan 30 19:04:52 CST 2019] url='https://acme.freessl.cn/acme/challenge/lhLL10bDZuHRBOB8p-FbZZbBTGTZrht7y-o79HjK3q4/1725'
129 [Wed Jan 30 19:04:53 CST 2019] timeout=
130 [Wed Jan 30 19:04:53 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
131 [Wed Jan 30 19:04:53 CST 2019] ret='0'
132 [Wed Jan 30 19:04:53 CST 2019] Pending
133 [Wed Jan 30 19:04:53 CST 2019] sleep 2 secs to verify
134 [Wed Jan 30 19:04:55 CST 2019] checking
135 [Wed Jan 30 19:04:55 CST 2019] GET
136 [Wed Jan 30 19:04:55 CST 2019] url='https://acme.freessl.cn/acme/challenge/lhLL10bDZuHRBOB8p-FbZZbBTGTZrht7y-o79HjK3q4/1725'
137 [Wed Jan 30 19:04:55 CST 2019] timeout=
138 [Wed Jan 30 19:04:55 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
139 [Wed Jan 30 19:04:57 CST 2019] ret='0'
140 [Wed Jan 30 19:04:57 CST 2019] ^[[1;31;32mSuccess^[[0m
141 [Wed Jan 30 19:04:57 CST 2019] pid
142 [Wed Jan 30 19:04:57 CST 2019] Verify finished, start to sign.
143 [Wed Jan 30 19:04:57 CST 2019] i='2'
144 [Wed Jan 30 19:04:57 CST 2019] j='15'
145 [Wed Jan 30 19:04:57 CST 2019] url='https://acme.freessl.cn/acme/finalize/145/Ev2OGYyc37acc'
146 [Wed Jan 30 19:04:57 CST 2019] payload='{}'
147 [Wed Jan 30 19:04:57 CST 2019] POST
148 [Wed Jan 30 19:04:57 CST 2019] _post_url='https://acme.freessl.cn/acme/finalize/145/EvOGYycacc'
149 [Wed Jan 30 19:04:57 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
150 [Wed Jan 30 19:05:04 CST 2019] _ret='0'
151 [Wed Jan 30 19:05:04 CST 2019] code='500'
152 [Wed Jan 30 19:05:04 CST 2019] pid
153 [Wed Jan 30 19:05:04 CST 2019] No need to restore nginx, skip.
154 [Wed Jan 30 19:05:04 CST 2019] _clearupdns
155 [Wed Jan 30 19:05:04 CST 2019] skip dns.
156 [Wed Jan 30 19:05:04 CST 2019] Sign failed, code is not 200.
157 [Wed Jan 30 19:05:04 CST 2019] {"type":"urn:ietf:params:acme:error:serverInternal","detail":"Error finalizing order","status": 500}
158 [Wed Jan 30 19:05:04 CST 2019] _on_issue_err
159 [Wed Jan 30 19:05:04 CST 2019] Please check log file for more details: /root/.acme.sh/acme.sh.log

**Comment by Neilpang** [comment]
这个 `https://acme.freessl.cn/`  是什么 鬼 ?

**Comment by coeus-lei** [comment]
我也不知道啊 0..0！！！第一次搞这个！我连成功没有都不知道，，生成的证书居然是csr后缀的，，，我做nginx的啊，不应该是pem后缀的吗？？？

**Comment by coeus-lei** [comment]
那么，如果我要给正在运行的nginx所绑定的域名做证书签发，需要先停止nginx吗？还有我生成的证书格式不是pem后缀的，，，而是一个key和一个csr文件

**Comment by coeus-lei** [comment]
我签发出来的只有一个.csr和.key后缀的文件，，，没有.pem结尾的证书文件

**Comment by Neilpang** [comment]
@citolo  
你之前用 acme.sh 成功过吗?
你现在用的 acme.sh 是多少版本?  之前用的是那个版本 ?

```
acme.sh  --version
```

**Comment by citolo** [comment]
@Neilpang 我用的acme.sh也是2.8.0，我用这个版本和freessl的后台已经验证成功上百个域名了，不过我发现有出问题的网站似乎是因为我原本放网站的文件夹有大写的英文字母，所以第一次验证没成功，后来改小写之后，也无法验证成功，我有在/root/.acme.sh的文件夹中把同一个域名名称的文件夹删掉再重新验证，但还是不行，还是出现一样的错误，就是最后要写入PEM档时会出错，我想大概是case sensitive的问题，不过我也不知道要怎么解决，现在还尝试各种方法。

**Comment by li3p** [comment]
今天在阿里云的服务器上也遇到一样的问题，V2.8.4的版本。
