### ISSUE TITLE
[improvement] Cronjob time randomization

### ISSUE THREAD

**Issue by kobuki** [Neilpang/acme.sh#208]
acme.sh is working great. However the way the default cronjob gets installed is probably suboptimal. It always puts itself at midnight, which might cause unnecessary stress on the Let's Encrypt services at that time. Of course, this assumes a sizable user base has installed acme.sh and left the renewal cronjob entry intact (if they even care and are aware of it), but still might worth some consideration adding a simple randomization function to the timing.

**Comment by heldchen** [comment]
well, not all users are in the same timezone, so it's already distributed a bit.

randomization would certainly make things distributed better, but even then IMO it should be up to the user to manually select a time that fits best into his dev ops.

**Comment by kobuki** [comment]
Yes, it uses midnight in each time zone, effectively dividing the slot to about 24th of the total install base, and that's already a little more than an order of magnitude -- it all depends on the number of total installations. I "randomize" my half dozen of installations (so far) by hand. It might not hurt, regardless. It depends on the LE EULA, I guess...

**Comment by Neilpang** [comment]
There are 2 points:

1.  yes,  not everybody are in the same timezone.

2.  acme.sh doesn't connect to letsencrypt server everyday,  just connect if necessary, for example:  every 80 days  by default.


So, I don't think it's necessary.

**Comment by kobuki** [comment]
Right, then it checks renewal conditions based on info in the cert itself, I guess. Closing. Thanks for the easy script!
