### ISSUE TITLE
【疑问】关于自动续期的问题

### ISSUE THREAD

**Issue by xiebruce** [Neilpang/acme.sh#2097]
第一步：我执行以下语句，正常获取到了证书：
```
acme.sh --issue --dns dns_ali -d xiebruce.top -d '*.xiebruce.top'
```

第二步：上边虽然获取到了证书，但并不能直接使用，于是我用以下命令拷贝到nginx目录下，最后自动执行`reloadcmd`重载nginx配置，一切正常：
```
acme.sh --install-cert -d 'xiebruce.top' \
--key-file       /usr/local/openresty/nginx/letsencrypt/private.pem  \
--fullchain-file /usr/local/openresty/nginx/letsencrypt/fullchain.pem \
--reloadcmd     "nginx -s reload"
```

自动renew，无非就是添加定时任务，定时任务自动一天执行一次，但是我不太理解的是，你的定时任务是这样的，感觉有点看不懂啊，定时任务不是应该执行renew语句么？
```
0 0 * * * "/home/user/.acme.sh"/acme.sh --cron --home "/home/user/.acme.sh" > /dev/null
```
比如，我写成这样，是否可以？
```
0 0 * * *"/home/user/.acme.sh"/acme.sh --renew -d xiebruce.top > /dev/null
```

如果用以下renew语句，我试了一下，一切正常，开始我以为renew只会renew证书，但实际上我发现它也会执行install(即上边的第二步，所以也会重载nginx配置)，如果我把它添加到定时任务，那岂不是每天都会reload一次nginx？
```
acme.sh --renew -d xiebruce.top --force
```

**我的另一个理解：** 以下这句，它会自动在每天的0点执行renew操作以及install操作(即上边的第一步和第二步)，完全不需要我自己操心是吗？
```
0 0 * * * "/home/user/.acme.sh"/acme.sh --cron --home "/home/user/.acme.sh" > /dev/null
```

但即使这样，我还有几个问题：
1、自动renew是有--force的吗？它会在快过期的时候才真正renew，还是每天都强制更新一次(即使原来那个证书我只用了一天)，也就是它的等效操作是怎样的？
2、我的nginx是否会每天都reload一次？
3、双引号为什么加到这里：`"/home/user/.acme.sh"/acme.sh`，为什么不是这样`"/home/user/.acme.sh/acme.sh"`，或者干脆直接不用双引号也行吧，对cron不是很熟悉，还忘别笑话这是低级问题😂？
4、如果我多台机都运行同一个网站，那我是分别获取还是其中一台获取了然后同步到其他？

最后，感谢提供这么方便的工具！！

**Comment by Neilpang** [comment]
少年, 你的问题真多.

其实很简单: `cron == renewAll`
你有多个证书,  我不可能为你的每一个证书添加一个  cronjob 吧.  所以就写了一个总的.

只有在renew 成功以后, 才会reload.  否则不是傻吗

多个机器运行同一个网站, 如果用 webroot 模式,  并且你只在一台机器上运行 acme.sh, 就会有 验证问题.
因为你 无法确定 验证服务器会访问你哪一个后端.  当然也是有办法解决的. 比如对验证目录 进行重定向.
这些网上教程都有.
多个服务器建议用dns api 模式,  既可以每个服务器都运行,  也可以一个运行,然后同步到所有服务器.

**Comment by Neilpang** [comment]
至于引号的问题, 是为了防止路径中有空格.    最开始时, 貌似发现有的平台如果全部引号引起来会有问题, 所有就改成只引路径了.   我记不太清了. 后来就懒得改了.

**Comment by xiebruce** [comment]
@Neilpang 🤣不好意思啊，打扰你过情人节了。

我现在发现，执行一下`acme.sh --cron`我就明白了，那用`--home`指定`acme.sh`的home目录也是可以不用的吧？如果我默认的话？

另外，虽然我获取证书或强制renew证书成功，但我之前用`certbot`方式在阿里云添加的`_acme-challenge`值竟然一直不变，不过邮件却收到了修改的通知，并且里面的`_acme-challenge`值并不是我显式添加的值，感觉用接口的方式更新`_acme-challenge`值，并不会显式的显示出来，既然这样，那我删除了`_acme-challenge`应该没事吧？
