### ISSUE TITLE
Should this library be moved to an organization?

### ISSUE THREAD

**Issue by jhabdas** [Neilpang/acme.sh#2109]
I'm curious if this library is popular enough it should be transferred to an organization to make it look more more less "official", e.g. "github.com/acme/acme.sh". I image GitHub would help you secure a username/org title that's not in strong use given the star count here.

**Comment by Neilpang** [comment]
I don't mind if it's project or an organization.  It's never a must for a project being looked more "official" to be converted to an organization.

Here is a good example:  https://github.com/torvalds/linux

For now there is only one maintainer for acme.sh,   if in future it's necessary to have more developers,  it can be converted to an organization then.

Thanks.

**Comment by jhabdas** [comment]
Thanks for chiming in. I'd keep this under your username and orgs can be a <del>huge bitch</del><ins>more trouble than their worth</ins>. I think the real reason I asked is because of the capital N in your name TBH. GH is weird about name changes and how it does redirects though so I guess you're stuck with a funky URL.

**Comment by Neilpang** [comment]
@jhabdas 

Yes,  I tried to rename my name, but failed.

**Comment by jhabdas** [comment]
That bastards! I'm sorry for bringing this up then. Please accept my sincerest apologies.

**Comment by Neilpang** [comment]
@jhabdas   Never mind,  it's ok.  :)
