### ISSUE TITLE
关于服务端替换的问题

### ISSUE THREAD

**Issue by coeus-lei** [Neilpang/acme.sh#2115]
如果，我再一台服务器上面使用acme生成了证书，但是后续，我想更换一台服务器重新生成该域名的证书，需要撤销原来的证书吗？怎么撤销呢

**Comment by baoang** [comment]
你不用撤，你直接再申请就成了呗，不用换服务器就能重新再申请，就是证书时间不一样。

**Comment by coeus-lei** [comment]
那服务器挂掉了，需要更换的情况怎么办？

**Comment by coeus-lei** [comment]
麻蛋鸭！这个速率限制好麻烦！！

**Comment by baoang** [comment]
> 
> 
> 那服务器挂掉了，需要更换的情况怎么办？

那你当然得有备份。比如我就会下载一份证书到硬盘上，或者你在不同的服务器上再装一个acme.sh，这台挂了，你启用另一台的acme.sh

**Comment by coeus-lei** [comment]
速率限制，怎么避免？主域名的限制还是存在，7天五次

**Comment by coeus-lei** [comment]
好像有个后台可以解除存在等待的验证。。。麻蛋啊就看不懂了
