### ISSUE TITLE
FreeDNS can be updated without scraping web site

### ISSUE THREAD

**Issue by deutrino** [Neilpang/acme.sh#2121]
Hello, the documentation states that acme.sh relies on logging in to freedns.afraid.org because there is no API. However, I checked the FreeDNS FAQ and there is now a way to update TXT records that doesn't require storing the account password on disk. Pasted from http://freedns.afraid.org/faq/#17 below.

> **Question: (FAQ item 17)**
> How can I update my TXT record automatically?
> **Answer:**
> Here's one such way to achieve this:
> ```curl -b "dns_cookie=XXXXXXXXXX" -d "type=TXT" -d  "subdomain=_acme-challenge" -d "domain_id=0000" -d "data_id=0000" -d  "address=%22some_text%22"  https://freedns.afraid.org/subdomain/save.php?step=2```
> You can get the data_id by clicking 'subdomains' -> 'edit' on the entry.
> You can get the dns_cookie by analyzing the saved cookie in your browser while logged in.

**Comment by deutrino** [comment]
(Guess I should clarify that it would be nice to be able to just paste in the mentioned pieces of data somewhere, rather than having to use a username and password the first time.)

**Comment by Neilpang** [comment]
we already used the cookies.
