### ISSUE TITLE
Can't run with sudo or as root

### ISSUE THREAD

**Issue by Mikeb30** [Neilpang/acme.sh#2124]
I have a ghost blog installation and acme.sh came with it (tied with nginx,) tried issuing commands and it doesn't work with sudo (sudo: acme.sh: command not found) or if running as root (bash: acme.sh: command not found.) As well as if I run any command without sudo or root it just states permission denied.

How do I get this to work?

**Comment by Neilpang** [comment]
do not run as sudo.
you can either:
1. run as current user
2. Or `sudo su`, switch to root, and run acme.sh there.


Never never use sudo to run acme.sh

**Comment by JuanDMeGon** [comment]
Hello,

Would be nice if you can explain, as it is not clear for me and probably many other, why using `sudo` is not good but doing it directly after `sudo su` is right?

Some times we want to install certs of even renew or issue certs in "protected" locations, like `/var/www` or the Nginx folder (to install certs, for example `/etc/nginx/certs`).
So after we cannot use `sudo`, we will be forced to install acme.sh to the root user and/or to provide permissions to that "protected" locations to the specific user who installed acme.sh.

Can you bring us a guide to how is the correct/secure way to handle this so? Would be nice if you can add this to the [Wiki](https://github.com/Neilpang/acme.sh/wiki/sudo) which is a little vague right now.

Thank you so much in advance.

**Comment by pzillmann** [comment]
What's wrong with `sudo -s` or `sudo -i` - there is not much difference to `su`?

**Comment by Neilpang** [comment]
@pzillmann 

Imagine in the cronjob,  there is no `sudo -s` or `sudo -i` at all.  If you were the cron worker,  how can you accomplish the task of `renew(issue)` ?

The core conception here is that:  If something you can do in your command line, it we reuse it in the cronjob.  So, there should not be any sudo, because,  there is nobody in the cronjob  to input your passwrod for you.
