### ISSUE TITLE
关于证书的续签问题

### ISSUE THREAD

**Issue by coeus-lei** [Neilpang/acme.sh#2125]
证书续签是如何实现的，如果证书过期时间是90天，那么是在第90天证书过期的时候才续签的吗？
那过期和续签这个中间的时间，证书就是不可用的，网站不是就访问不了了吗？

**Comment by gclove** [comment]
你这问题比较傻 ...

https://github.com/Neilpang/acme.sh/blob/master/README.md#2-just-issue-a-cert

> The certs will be renewed automatically every 60 days.
