### ISSUE TITLE
Add support for Google DNS resolver

### ISSUE THREAD

**Issue by kberzinch** [Neilpang/acme.sh#2130]
[Google offers a DNS-over-HTTPS service](https://developers.google.com/speed/public-dns/docs/dns-over-https) much like Cloudflare. It uses the same schema as Cloudflare [per their documentation](https://developers.cloudflare.com/1.1.1.1/dns-over-https/json-format/). Please add a runtime parameter to select which resolver is used.

I ran into an issue where Cloudflare was returning empty responses to the server where I was trying to install the certificate. Running the same cURL command from my local machine received the expected result. I was able to find the Cloudflare resolver URL in the code and replace it with the Google URL, which solved my issue, but it would be nice to be able to do this with a command line parameter much like wget/curl.

**Comment by kberzinch** [comment]
I see the Google resolver was considered as an option in #2015, but I don't see why it was not added to the code.

**Comment by Neilpang** [comment]
@kberzich

Google public doesn't have an api to purge the dns cache.

The google api requires captcha .

Cloudflare  purge api doesn't require captcha

**Comment by kberzinch** [comment]
Hmm okay.

**Comment by KiritoStudio** [comment]
@Neilpang Did you mean there is no plan to support domain.google.com support? If so, I will change the DNS service provider.

**Comment by kberzinch** [comment]
This was regarding the recursive public resolver, not the authoritative name servers.
