### ISSUE TITLE
installcert bug cause cert not auto renew 

### ISSUE THREAD

**Issue by zgfh** [Neilpang/acme.sh#2134]
Steps to reproduce
```
/root/.acme.sh/acme.sh --installcert -d www.daozzg.com --key-file /opt/vps_config/nginx/ssl/www.daozzg.com/privkey.pem --fullchain-file /opt/vps_config/nginx/ssl/www.daozzg.com/fullchain.pem --reloadcmd ' docker ps|grep vpsconfig_nginx_1 &&docker exec  vpsconfig_nginx_1 service nginx force-reload ||echo update_nginx_fail'
```
 it look like sed should check  '|'：
https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L1958
It make config of /root/.acme.sh/www.daozzg.com/www.daozzg.com.conf empty,and can not list and renew

Debug log
-----------------
```
/root/.acme.sh/acme.sh --installcert -d www.daozzg.com --key-file /opt/vps_config/nginx/ssl/www.daozzg.com/privkey.pem --fullchain-file /opt/vps_config/nginx/ssl/www.daozzg.com/fullchain.pem --reloadcmd ' docker ps|grep vpsconfig_nginx_1 &&docker exec  vpsconfig_nginx_1 service nginx force-reload ||echo update_nginx_fail'

```
+ sed 's|^Le_ReloadCmd=.*$|Le_ReloadCmd='\'' docker ps|grep vpsconfig_nginx_1 \&\&docker exec  vpsconfig_nginx_1 service nginx force-reload ||echo update_nginx_fail'\''|'
sed: -e expression #1, char 47: unknown option to `s'
```

**Comment by Neilpang** [comment]
ok,  I will fix it later.

**Comment by Neilpang** [comment]
fixed, please try again.
