### ISSUE TITLE
The --apache mode doesn't work with the Apache httpd official docker image

### ISSUE THREAD

**Issue by zyberit** [Neilpang/acme.sh#214]
I'm trying to integrate acme.sh with the official Apache httpd docker image (https://hub.docker.com/_/httpd/).
I run **/root/.acme.sh/acme.sh --issue --apache -d $HOSTNAME** at container startup but
I get "_Sorry, apache config error, please contact me._" after a few lines of acme.sh execution.

If I comment out the line "#Include conf/extra/httpd-ssl.conf" in httpd.conf, the certificate issuing process works, but SSL is then not enabled in the server and the key and certs are not copied in place.

Issuing using --standalone and copying key and issued certificate to /usr/local/apache2/conf/ works.

**Comment by Neilpang** [comment]
There is something wrong in the default `/usr/local/apache2/conf/extra/httpd-ssl.conf`.

With a fresh new httpd container,  just uncomment the line: ` "#Include conf/extra/httpd-ssl.conf"`

Then :

···
apachectl  -k restart
···

you will see the error:

```
root@a3fe042a5ff0:/usr/local/apache2/conf# apachectl -k  restart
AH00526: Syntax error on line 52 of /usr/local/apache2/conf/extra/httpd-ssl.conf:
Invalid command 'SSLCipherSuite', perhaps misspelled or defined by a module not included in the server configuration

```

Please fix this error first, and make sure the `restart` command can work in this moment.

**Comment by zyberit** [comment]
The error is because the SSL-module is not load by default so the line
`LoadModule ssl_module modules/mod_ssl.so`
also needs to be uncommented in httpd.conf as well as the line
`LoadModule socache_shmcb_module modules/mod_socache_shmcb.so`
This is missing in the documentation.

When I run 
` /root/.acme.sh/acme.sh --issue --apache -d $HOSTNAME`
I get the output
```
[Wed Jun 15 05:17:36 UTC 2016] JFYI, Config file /usr/local/apache2/conf/httpd.conf is backuped to /root/.acme.sh/httpd.conf
[Wed Jun 15 05:17:36 UTC 2016] In case there is an error that can not be restored automatically, you may try restore it yourself.
[Wed Jun 15 05:17:36 UTC 2016] The backup file will be deleted on sucess, just forget it.
[Wed Jun 15 05:17:36 UTC 2016] Sorry, apache config error, please contact me.
[Wed Jun 15 05:17:36 UTC 2016] set up apache error. Report error to me.
```

**Comment by Neilpang** [comment]
After making those change.

```
root@e3908ed46546:/usr/local/apache2/conf# apachectl -k restart
AH00526: Syntax error on line 144 of /usr/local/apache2/conf/extra/httpd-ssl.conf:
SSLCertificateFile: file '/usr/local/apache2/conf/server.crt' does not exist or is empty

```

**Comment by Neilpang** [comment]
Please try the latest code.  I just fixed the error messge for you.

**Comment by zyberit** [comment]
Ahhh, so I need to configure the server with a dummy key and cert first in order to be able to issue new certificates when using the --apache mode.

**Comment by Neilpang** [comment]
@zyberit 

No,  you don't need dummy cert.

Do not uncomment this line when you issue your first cert:
```
"#Include conf/extra/httpd-ssl.conf"
```

After your first cert, you can use it as the server.crt.

**Comment by Neilpang** [comment]
please update the latest code again.  I just fixed the error message again.

**Comment by Neilpang** [comment]
You can also write script to uncomment the line in the `--reloadcmd`  parameter.

**Comment by Neilpang** [comment]
@zyberit 
 another option for you.
When you first run your container,  the apache server is not running,  so you can issue the first cert with `--standalone` mode.

Then setup it it with "--installcert" command.

Then start your apache server.

Then you can use `--apache` mode to issue cert in future.

**Comment by zyberit** [comment]
Thanks!  :)
