### ISSUE TITLE
2.8.1版本renew证书错误

### ISSUE THREAD

**Issue by denggaomou** [Neilpang/acme.sh#2141]
版本 2.8.1
证书renew显示正常，但是实际证书没有更新，检查了下脚本，发现issue方法新增了
 while [ -z "$Le_LinkCert" ] && [ "$_link_cert_retry" -lt "$_MAX_CERT_RETRY" ]; do
      if _contains "$response" "\"status\":\"valid\""; then
        _debug "Order status is valid."
        Le_LinkCert="$(echo "$response" | tr -d '\r\n' | _egrep_o '"certificate" *: *"[^"]*"' | cut -d '"' -f 4)"
但是renew的时候会先. "$DOMAIN_CONF",这时候后 while就不会生效，导致Le_LinkCert变量不会更新，还是会下载上一个版本的证书文件，renew之后虽然一切显示成功，然而证书还是老的

**Comment by Neilpang** [comment]
能不能给一个完整的 log

···
--debug   2
···

**Comment by denggaomou** [comment]
我的域名被我测试的已经被limit了...

**Comment by Neilpang** [comment]
修好了, 试一下
