### ISSUE TITLE
acme.sh: command not found

### ISSUE THREAD

**Issue by philliplurge** [Neilpang/acme.sh#2149]
I Need Realy help..

i have installed acme.sh with "curl https://get.acme.sh | sh" and have restarted my server .. 
but the terminal says command not fount when i use acme.sh to issue a cert..

my OS ist Ubuntu 16.04 with MSSQL 2017

Please help me ...

**Comment by Neilpang** [comment]
please install again, and show me the output:

```
curl https://get.acme.sh | sh
```

**Comment by philliplurge** [comment]
root@srv02:~# acme.sh -h
acme.sh: command not found
root@srv02:~# curl https://get.acme.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705  100   705    0     0   2123      0 --:--:-- --:--:-- --:--:--  2117
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  171k  100  171k    0     0  2479k      0 --:--:-- --:--:-- --:--:-- 2479k
[Sat Mar  9 21:39:39 UTC 2019] Installing from online archive.
[Sat Mar  9 21:39:39 UTC 2019] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Sat Mar  9 21:39:40 UTC 2019] Extracting master.tar.gz
[Sat Mar  9 21:39:40 UTC 2019] Installing to /root/.acme.sh
[Sat Mar  9 21:39:40 UTC 2019] Installed to /root/.acme.sh/acme.sh
[Sat Mar  9 21:39:40 UTC 2019] Installing alias to '/root/.bashrc'
[Sat Mar  9 21:39:40 UTC 2019] OK, Close and reopen your terminal to start using acme.sh
[Sat Mar  9 21:39:40 UTC 2019] Installing cron job
10 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Sat Mar  9 21:39:40 UTC 2019] Good, bash is found, so change the shebang to use bash as preferred.
[Sat Mar  9 21:39:41 UTC 2019] OK
[Sat Mar  9 21:39:41 UTC 2019] Install success!
root@srv02:~#


This is the Output.. on a Fresh installed Ubuntu 18.04

**Comment by Neilpang** [comment]
```sh
source  ~/.bashrc

acme.sh --help
```

**Comment by jerrychong25** [comment]
> ```shell
> source  ~/.bashrc
> 
> acme.sh --help
> ```

Thank you for solution!
