### ISSUE TITLE
Question on LE_PreHook - No an issue

### ISSUE THREAD

**Issue by mvbenz** [Neilpang/acme.sh#2150]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

I was looking for a way to get the script to restart apache after an update. I know I can do it with a cron job but I found in the documentation to use _Le_RenewHook_ but when I went into the config file for one of my domains I see an entry already filled in (see below). What do these mean?

**Le_PreHook='__ACME_BASE64__START___ACME_BASE64__END_'
Le_PostHook='__ACME_BASE64__START___ACME_BASE64__END_'
Le_RenewHook='__ACME_BASE64__START___ACME_BASE64__END_'**

I am running the bitnami LAMP stack with a few wordpress sites on AWS so the command to restart apache is:

**sudo /opt/bitnami/ctlscript.sh restart apache**

Would I replace Le_RenewHook as follows?

**Le_RenewHook='sudo /opt/bitnami/ctlscript.sh restart apache'**

**Comment by Neilpang** [comment]
you should not edit the conf file.
please use command line options:
https://github.com/Neilpang/acme.sh/wiki/Using-'--pre-hook',-'--post-hook',-'--renew-hook'-and-'--reload-cmd'

**Comment by ProBackup-nl** [comment]
@Neilpang 
I don't want to renew the already existing certificate, therefore I can't run `acme.sh --renew -d ...` neither `--issue` neither `--cron`.

I just want to edit/modify the configuration for the next run: add an additional (custom) deploy command.

When I should not edit the conf file, how to add a `post-hook` as an after though to an existing profile?

**Comment by ProBackup-nl** [comment]
I can answer my own question now. Just issue a deploy command, that deploy hook will be added to the .conf file. Example:
`
# acme.sh --deploy -d ftp.example.com --deploy-hook remotemacos
# grep Deploy /opt/home/admin/.acme.sh/ftp.example.com/ftp.example.com.conf
Le_DeployHook='remotemacos,'
`

**Comment by Neilpang** [comment]
@ProBackup-nl 

Correct.
