### ISSUE TITLE
请教一下自动续签有钩子吗？

### ISSUE THREAD

**Issue by zpzhoudev** [Neilpang/acme.sh#2153]
nginx装在docker里了，证书更新完了需要重启容器，请教下有什么机制可以在更新证书后自动重启呢？比如加个钩子，让用户配置一条命令，证书更新后自动执行？

**Comment by Neilpang** [comment]
请仔细阅读 说明: 
https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E

还有 wiki  https://github.com/Neilpang/acme.sh/wiki/Using-'--pre-hook',-'--post-hook',-'--renew-hook'-and-'--reload-cmd'

**Comment by zpzhoudev** [comment]
谢谢
