### ISSUE TITLE
dns_hostingde ENDPOINT not read from config file

### ISSUE THREAD

**Issue by afaenger** [Neilpang/acme.sh#2156]
Steps to reproduce
------------------
Invoking acme.sh from cron job without specifying HOSTINGDE_ENDPOINT doesn't work and throws an error
"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"

The Problem is that $HOSTINGDE_ENDPOINT is not read from the config file, whereas $HOSTINGDE_APIKEY is read.

Workaround: add the following line to the beginning of _hostingde_apiKey()

```
HOSTINGDE_ENDPOINT="${HOSTINGDE_ENDPOINT:-$(_readaccountconf_mutable HOSTINGDE_ENDPOINT)}"
```

Debug log
-----------------

```
[Mon Mar  4 01:45:03 CET 2019] You haven't specified hosting.de API key or endpoint yet.
[Mon Mar  4 01:45:03 CET 2019] Please create your key and try again.
```

**Comment by membero** [comment]
Hello,

I have created a PR for this. Please report issues here: https://github.com/Neilpang/acme.sh/issues/2058

Thanks!
