### ISSUE TITLE
Document exit codes

### ISSUE THREAD

**Issue by tinproject** [Neilpang/acme.sh#216]
I'm trying to automate certificate issue with ansible and acme.sh checking exit codes. Also I've notice that the exit codes of `--renewAll` and `--cron` return the exit code of the last certificate checked, there is no posible to detect if some certificate was renewed according to the exit code.

**Comment by Neilpang** [comment]
fixed:  cc179731135b42cad3f0d8d43e5d4f9a69ccef03


if there is any error in the renewall,  the cron command will return the error code.

**Comment by tinproject** [comment]
@Neilpang, thank you for your quick response. I was reviewing the code and the only case I see that one couldn't know if a cert is renewed, to do some action (reload server for example), is when a cert is renewed and other, after, fails with an error. I don't know if this corner case worth the detection.

**Comment by Neilpang** [comment]
I don't quite understand what you mean here.
But if you want to know the status of each cert renewal,  you can do it yourself with `--list` or `--list  --listraw` commands.

For example:

This will output all the certs and status.  will formated.

```
acme.sh   --list
root@adm:~# acme.sh  --list
Main_Domain        SAN_Domains     Created                       Renew
xxxxxxxxxxx.net    no              Thu Jun 16 07:12:53 UTC 2016  Sun Sep  4 07:12:53 UTC 2016
xxxxxxxxxx.com       no              Tue May 31 22:23:14 UTC 2016  Fri Aug 19 22:23:14 UTC 2016
xxxxx.xxxxxx.com   no              Thu May 26 05:59:35 UTC 2016  Sun Aug 14 05:59:35 UTC 2016
xxxxx.xxxxx.net  no              Fri May 27 00:00:51 UTC 2016  Mon Aug 15 00:00:51 UTC 2016
xxxxxx.xxxx.com    no              Mon May 30 19:29:43 UTC 2016  Thu Aug 18 19:29:43 UTC 2016
xxxxx.xxxx.net   no              Sun May  8 16:33:34 UTC 2016  Wed Jul 27 16:33:34 UTC 2016
xxxxxxx.com       no              Wed May 18 21:44:02 UTC 2016  Sat Aug  6 21:44:02 UTC 2016
xxxx.com         www.xxxxx.com  Wed Jun  8 18:58:14 UTC 2016  Sat Aug 27 18:58:14 UTC 2016

```

You can also list them as raw data, which is good for your command line process

```
acme.sh  --list  --listraw
```


After you list all the certs,  you can call `--renew  -d  domain.com ` by yourself.

Please let me know if this is ok for you.

Thanks.

**Comment by tinproject** [comment]
Sorry for late response. I was meaning the case when running `--renewAll`, with the domains tryed to renew in order, then for example: `xxxxxxxxxxx.com` will be renewed, and `xxxxxxx.com` later will fail, all others will be skipped. In this case the return code will be the error of the operation that leads to a failed renew, so in this case its not possible to know, with the error code, if some certificates were renewed or not.

For me i'ts ok the current level of detail. Thank you very much.
