### ISSUE TITLE
关于域名中包含特殊字符，不能order

### ISSUE THREAD

**Issue by coeus-lei** [Neilpang/acme.sh#2162]
[root@izj6cbkmagj0t1phj0dc1jz ~]# acme.sh --issue -d log_server.22970.vip --webroot /data/wwwroot/log_server.22970.vip/ --debug 2
[Thu Mar 14 20:11:28 CST 2019] Lets find script dir.
[Thu Mar 14 20:11:28 CST 2019] _SCRIPT_='/root/.acme.sh/acme.sh'
[Thu Mar 14 20:11:28 CST 2019] _script='/root/.acme.sh/acme.sh'
[Thu Mar 14 20:11:28 CST 2019] _script_home='/root/.acme.sh'
[Thu Mar 14 20:11:28 CST 2019] Using config home:/root/.acme.sh
[Thu Mar 14 20:11:28 CST 2019] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.1
[Thu Mar 14 20:11:28 CST 2019] _main_domain='log_server.22970.vip'
[Thu Mar 14 20:11:28 CST 2019] _alt_domains='no'
[Thu Mar 14 20:11:28 CST 2019] Using config home:/root/.acme.sh
[Thu Mar 14 20:11:28 CST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Mar 14 20:11:28 CST 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Thu Mar 14 20:11:28 CST 2019] DOMAIN_PATH='/root/mycerts/log_server.22970.vip'
[Thu Mar 14 20:11:28 CST 2019] '/data/wwwroot/log_server.22970.vip/' does not contain 'dns'
[Thu Mar 14 20:11:28 CST 2019] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Thu Mar 14 20:11:28 CST 2019] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Thu Mar 14 20:11:28 CST 2019] GET
[Thu Mar 14 20:11:28 CST 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Thu Mar 14 20:11:28 CST 2019] timeout=
[Thu Mar 14 20:11:28 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.f6Fb32mxbR  -g '
[Thu Mar 14 20:11:29 CST 2019] ret='0'
[Thu Mar 14 20:11:29 CST 2019] response='{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "yLjkSHSYDiU": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}'
[Thu Mar 14 20:11:29 CST 2019] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Thu Mar 14 20:11:29 CST 2019] ACME_NEW_AUTHZ
[Thu Mar 14 20:11:29 CST 2019] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Mar 14 20:11:29 CST 2019] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Thu Mar 14 20:11:29 CST 2019] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Thu Mar 14 20:11:29 CST 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Thu Mar 14 20:11:29 CST 2019] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Mar 14 20:11:29 CST 2019] ACME_VERSION='2'
[Thu Mar 14 20:11:29 CST 2019] Le_NextRenewTime
[Thu Mar 14 20:11:29 CST 2019] _on_before_issue
[Thu Mar 14 20:11:29 CST 2019] _chk_main_domain='log_server.22970.vip'
[Thu Mar 14 20:11:29 CST 2019] _chk_alt_domains
[Thu Mar 14 20:11:29 CST 2019] '/data/wwwroot/log_server.22970.vip/' does not contain 'no'
[Thu Mar 14 20:11:29 CST 2019] Le_LocalAddress
[Thu Mar 14 20:11:29 CST 2019] d='log_server.22970.vip'
[Thu Mar 14 20:11:29 CST 2019] Check for domain='log_server.22970.vip'
[Thu Mar 14 20:11:29 CST 2019] _currentRoot='/data/wwwroot/log_server.22970.vip/'
[Thu Mar 14 20:11:29 CST 2019] d
[Thu Mar 14 20:11:29 CST 2019] '/data/wwwroot/log_server.22970.vip/' does not contain 'apache'
[Thu Mar 14 20:11:29 CST 2019] _saved_account_key_hash='2H4DW5FQ30G2tP+VvrWRk6yJYVjkxD6kGtbsAii4rqE='
[Thu Mar 14 20:11:29 CST 2019] _saved_account_key_hash is not changed, skip register account.
[Thu Mar 14 20:11:29 CST 2019] Read key length:
[Thu Mar 14 20:11:29 CST 2019] _createcsr
[Thu Mar 14 20:11:29 CST 2019] domain='log_server.22970.vip'
[Thu Mar 14 20:11:29 CST 2019] domainlist
[Thu Mar 14 20:11:29 CST 2019] csrkey='/root/mycerts/log_server.22970.vip/log_server.22970.vip.key'
[Thu Mar 14 20:11:29 CST 2019] csr='/root/mycerts/log_server.22970.vip/log_server.22970.vip.csr'
[Thu Mar 14 20:11:29 CST 2019] csrconf='/root/mycerts/log_server.22970.vip/log_server.22970.vip.csr.conf'
[Thu Mar 14 20:11:29 CST 2019] Single domain='log_server.22970.vip'
[Thu Mar 14 20:11:29 CST 2019] _is_idn_d='log_server.22970.vip'
[Thu Mar 14 20:11:29 CST 2019] _idn_temp='_'
[Thu Mar 14 20:11:29 CST 2019] _csr_cn='log_server.22970.vip'
[Thu Mar 14 20:11:29 CST 2019] Getting domain auth token for each domain
[Thu Mar 14 20:11:29 CST 2019] d
[Thu Mar 14 20:11:29 CST 2019] _identifiers='{"type":"dns","value":"log_server.22970.vip"}'
[Thu Mar 14 20:11:29 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Mar 14 20:11:29 CST 2019] payload='{"identifiers": [{"type":"dns","value":"log_server.22970.vip"}]}'
[Thu Mar 14 20:11:29 CST 2019] RSA key
[Thu Mar 14 20:11:29 CST 2019] Get nonce with HEAD. ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Mar 14 20:11:29 CST 2019] HEAD
[Thu Mar 14 20:11:29 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Mar 14 20:11:29 CST 2019] body
[Thu Mar 14 20:11:29 CST 2019] _postContentType='application/jose+json'
[Thu Mar 14 20:11:29 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.H1ZScF0yZL  -g '
[Thu Mar 14 20:11:30 CST 2019] _ret='0'
[Thu Mar 14 20:11:30 CST 2019] _headers='HTTP/1.1 200 OK
Server: nginx
Link: <https://acme-v02.api.letsencrypt.org/index>;rel="index"
Replay-Nonce: az33_EosZ9aOZC3nggD2pljve43M6bq55SKUoipEfr0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Content-Length: 0
Expires: Thu, 14 Mar 2019 12:11:30 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 14 Mar 2019 12:11:30 GMT
Connection: keep-alive
'
[Thu Mar 14 20:11:30 CST 2019] _CACHED_NONCE='az33_EosZ9aOZC3nggD2pljve43M6bq55SKUoipEfr0'
[Thu Mar 14 20:11:30 CST 2019] nonce='az33_EosZ9aOZC3nggD2pljve43M6bq55SKUoipEfr0'
[Thu Mar 14 20:11:30 CST 2019] POST
[Thu Mar 14 20:11:30 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Mar 14 20:11:30 CST 2019] body='{"protected": "eyJub25jZSI6ICJhejMzX0Vvc1o5YU9aQzNuZ2dEMnBsanZlNDNNNmJxNTVTS1VvaXBFZnIwIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIiLCAiYWxnIjogIlJTMjU2IiwgImtpZCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hY2N0LzUzMjc1MzkyIn0", "payload": "eyJpZGVudGlmaWVycyI6IFt7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6ImxvZ19zZXJ2ZXIuMjI5NzAudmlwIn1dfQ", "signature": "UawuhFILm5lO7rLWyN2YWx1EpIAMzS_jVKQDi2ohGAny7iOWcK0W6oWUKhAuXvVT1yghapt50PaXan8xghLJ-eqRhFSVD4L6su7bAbxiRMbY0TIrOt9gAJfGvkn2UqtpRzuta1jeyG6Jw-T5p236qrJRV0c2yLpoCJNUzyp9N7ASFuh-QBjF11t7iB5rvA6kEsU1AUerTuQpfxXPsDEVyOi7uSCpL5Gczs-uka60OkLemd_mrK57m7nyaKQew5j08t3InJgsnXcBqmPmupni_R_wLlynaSC6Dy-ymL9KwDZ_RJF4JBxB4Z-d2aDwrlYUp1UQlFEF8-SRngTu4QxWTA"}'
[Thu Mar 14 20:11:30 CST 2019] _postContentType='application/jose+json'
[Thu Mar 14 20:11:30 CST 2019] Http already initialized.
[Thu Mar 14 20:11:30 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.H1ZScF0yZL  -g '
[Thu Mar 14 20:11:30 CST 2019] _ret='0'
[Thu Mar 14 20:11:30 CST 2019] responseHeaders='HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/problem+json
Content-Length: 142
Boulder-Requester: 53275392
Link: <https://acme-v02.api.letsencrypt.org/index>;rel="index"
Replay-Nonce: XUZvqlfxuSkbaSnQXS01NfkfjrRvzw1DHSuq5C7Hgi8
Expires: Thu, 14 Mar 2019 12:11:30 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 14 Mar 2019 12:11:30 GMT
Connection: close
'
[Thu Mar 14 20:11:30 CST 2019] code='400'
[Thu Mar 14 20:11:30 CST 2019] original='{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error creating new order :: Invalid character in DNS name",
  "status": 400
}'
[Thu Mar 14 20:11:30 CST 2019] response='{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error creating new order :: Invalid character in DNS name",
  "status": 400
}'
[Thu Mar 14 20:11:30 CST 2019] Le_OrderFinalize
[Thu Mar 14 20:11:30 CST 2019] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error creating new order :: Invalid character in DNS name",
  "status": 400
}
[Thu Mar 14 20:11:30 CST 2019] pid
[Thu Mar 14 20:11:30 CST 2019] No need to restore nginx, skip.
[Thu Mar 14 20:11:30 CST 2019] _clearupdns
[Thu Mar 14 20:11:30 CST 2019] dns_entries
[Thu Mar 14 20:11:30 CST 2019] skip dns.
[Thu Mar 14 20:11:30 CST 2019] _on_issue_err
[Thu Mar 14 20:11:30 CST 2019] Please add '--debug' or '--log' to check more details.
[Thu Mar 14 20:11:30 CST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Thu Mar 14 20:11:30 CST 2019] _chk_vlist
[Thu Mar 14 20:11:30 CST 2019] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2k-fips  26 Jan 2017
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.14.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --user=nginx --group=nginx --prefix=/usr/local/nginx --sbin-path=/usr/sbin/nginx --conf-path=/usr/local/nginx/nginx.conf --http-log-path=/var/log/nginx/logs/access.log --error-log-path=/var/log/nginx//logs/error.log --http-client-body-temp-path=/usr/local/nginx/client_body --http-proxy-temp-path=/usr/local/nginx/proxy --http-fastcgi-temp-path=/usr/local/nginx/fastcgi --http-uwsgi-temp-path=/usr/local/nginx/uwsgi --http-scgi-temp-path=/usr/local/nginx/scgi --modules-path=/usr/local/nginx/modules --pid-path=/usr/local/nginx/logs/nginx.pid --lock-path=/usr/local/nginx/lock/subsys/nginx --with-file-aio --with-http_auth_request_module --with-http_ssl_module --with-http_v2_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_realip_module --with-http_perl_module=dynamic --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-debug
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
Usage:
socat [options] <bi-address> <bi-address>
   options:
      -V     print version and feature information to stdout, and exit
      -h|-?  print a help text describing command line options and addresses
      -hh    like -h, plus a list of all common address option names
      -hhh   like -hh, plus a list of all available address option names
      -d     increase verbosity (use up to 4 times; 2 are recommended)
      -D     analyze file descriptors before loop
      -ly[facility]  log to syslog, using facility (default is daemon)
      -lf<logfile>   log to file
      -ls            log to stderr (default if no other log)
      -lm[facility]  mixed log mode (stderr during initialization, then syslog)
      -lp<progname>  set the program name used for logging
      -lu            use microseconds for logging timestamps
      -lh            add hostname to log messages
      -v     verbose data traffic, text
      -x     verbose data traffic, hexadecimal
      -b<size_t>     set data buffer size (8192)
      -s     sloppy (continue on error)
      -t<timeout>    wait seconds before closing second channel
      -T<timeout>    total inactivity timeout in seconds
      -u     unidirectional mode (left to right)
      -U     unidirectional mode (right to left)
      -g     do not check option groups
      -L <lockfile>  try to obtain lock, or fail
      -W <lockfile>  try to obtain lock, or wait
      -4     prefer IPv4 if version is not explicitly specified
      -6     prefer IPv6 if version is not explicitly specified
   bi-address:
      pipe[,<opts>]	groups=FD,FIFO
      <single-address>!!<single-address>
      <single-address>
   single-address:
      <address-head>[,<opts>]
   address-head:
      abstract-client:<filename>	groups=FD,SOCKET,RETRY,UNIX
      abstract-connect:<filename>	groups=FD,SOCKET,RETRY,UNIX
      abstract-listen:<filename>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,UNIX
      abstract-recv:<filename>	groups=FD,SOCKET,RETRY,UNIX
      abstract-recvfrom:<filename>	groups=FD,SOCKET,CHILD,RETRY,UNIX
      abstract-sendto:<filename>	groups=FD,SOCKET,RETRY,UNIX
      create:<filename>	groups=FD,REG,NAMED
      exec:<command-line>	groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      fd:<num>	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      gopen:<filename>	groups=FD,FIFO,CHR,BLK,REG,SOCKET,NAMED,OPEN,TERMIOS,UNIX
      interface:<interface>	groups=FD,SOCKET
      ip-datagram:<host>:<protocol>	groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recv:<protocol>	groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recvfrom:<protocol>	groups=FD,SOCKET,CHILD,RANGE,IP4,IP6
      ip-sendto:<host>:<protocol>	groups=FD,SOCKET,IP4,IP6
      ip4-datagram:<host>:<protocol>	groups=FD,SOCKET,RANGE,IP4
      ip4-recv:<protocol>	groups=FD,SOCKET,RANGE,IP4
      ip4-recvfrom:<protocol>	groups=FD,SOCKET,CHILD,RANGE,IP4
      ip4-sendto:<host>:<protocol>	groups=FD,SOCKET,IP4
      ip6-datagram:<host>:<protocol>	groups=FD,SOCKET,RANGE,IP6
      ip6-recv:<protocol>	groups=FD,SOCKET,RANGE,IP6
      ip6-recvfrom:<protocol>	groups=FD,SOCKET,CHILD,RANGE,IP6
      ip6-sendto:<host>:<protocol>	groups=FD,SOCKET,IP6
      open:<filename>	groups=FD,FIFO,CHR,BLK,REG,NAMED,OPEN,TERMIOS
      openssl:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,OPENSSL
      openssl-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP,OPENSSL
      pipe:<filename>	groups=FD,FIFO,NAMED,OPEN
      proxy:<proxy-server>:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,HTTP
      pty	groups=FD,NAMED,TERMIOS,PTY
      readline	groups=FD,READLINE,TERMIOS
      sctp-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,SCTP
      sctp-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,SCTP
      sctp4-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,SCTP
      sctp4-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,SCTP
      sctp6-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP6,SCTP
      sctp6-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,SCTP
      socket-connect:<domain>:<protocol>:<remote-address>	groups=FD,SOCKET,CHILD,RETRY
      socket-datagram:<domain>:<type>:<protocol>:<remote-address>	groups=FD,SOCKET,RANGE
      socket-listen:<domain>:<protocol>:<local-address>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE
      socket-recv:<domain>:<type>:<protocol>:<local-address>	groups=FD,SOCKET,RANGE
      socket-recvfrom:<domain>:<type>:<protocol>:<local-address>	groups=FD,SOCKET,CHILD,RANGE
      socket-sendto:<domain>:<type>:<protocol>:<remote-address>	groups=FD,SOCKET
      socks4:<socks-server>:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      socks4a:<socks-server>:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      stderr	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdin	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdio	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdout	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      system:<shell-command>	groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      tcp-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP
      tcp-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP
      tcp4-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,TCP
      tcp4-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,TCP
      tcp6-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP6,TCP
      tcp6-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,TCP
      tun[:<ip-addr>/<bits>]	groups=FD,CHR,NAMED,OPEN,INTERFACE
      udp-connect:<host>:<port>	groups=FD,SOCKET,IP4,IP6,UDP
      udp-datagram:<host>:<port>	groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,IP6,UDP
      udp-recv:<port>	groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-recvfrom:<port>	groups=FD,SOCKET,CHILD,RANGE,IP4,IP6,UDP
      udp-sendto:<host>:<port>	groups=FD,SOCKET,IP4,IP6,UDP
      udp4-connect:<host>:<port>	groups=FD,SOCKET,IP4,UDP
      udp4-datagram:<remote-address>:<port>	groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,UDP
      udp4-recv:<port>	groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-recvfrom:<host>:<port>	groups=FD,SOCKET,CHILD,RANGE,IP4,UDP
      udp4-sendto:<host>:<port>	groups=FD,SOCKET,IP4,UDP
      udp6-connect:<host>:<port>	groups=FD,SOCKET,IP6,UDP
      udp6-datagram:<host>:<port>	groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP6,UDP
      udp6-recv:<port>	groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-recvfrom:<port>	groups=FD,SOCKET,CHILD,RANGE,IP6,UDP
      udp6-sendto:<host>:<port>	groups=FD,SOCKET,IP6,UDP
      unix-client:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-connect:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-listen:<filename>	groups=FD,SOCKET,NAMED,LISTEN,CHILD,RETRY,UNIX
      unix-recv:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-recvfrom:<filename>	groups=FD,SOCKET,NAMED,CHILD,RETRY,UNIX
      unix-sendto:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX

**Comment by Neilpang** [comment]
```
[Thu Mar 14 20:11:30 CST 2019] original='{
"type": "urn:ietf:params:acme:error:malformed",
"detail": "Error creating new order :: Invalid character in DNS name",
"status": 400
}'
```

不用下划线很难吗

**Comment by coeus-lei** [comment]
但是，我使用--standalone 又可以使用下划线啊，老大！！！

**Comment by Neilpang** [comment]
你先弄一个成功的看看

**Comment by coeus-lei** [comment]
已经成功了

**Comment by coeus-lei** [comment]
好吧！我错了，，去也是没有成功

**Comment by coeus-lei** [comment]
也就是说acme本来就不支持特殊字符，，是吧
？

**Comment by coeus-lei** [comment]
大佬！！1给我确定一下答案啊。不然我心里面没底啊！！！

**Comment by Neilpang** [comment]
学会自己搜索答案:
https://www.google.com/search?q=domain+underscore&pws=0&gl=us&gws_rd=cr

**Comment by coeus-lei** [comment]
明白的！只是有些时候，有些关键点，需要点拨一下！多谢了！0..0！

**Comment by Neilpang** [comment]
探索未知的世界其实比直接知道答案更快乐。 加油。

**Comment by coeus-lei** [comment]
明白
