### ISSUE TITLE
cronjob: parameters?

### ISSUE THREAD

**Issue by heikoh81** [Neilpang/acme.sh#2165]
Hi,

I'm new to acme.sh (migarting from certbot).
After installing my first certificate, I'm wondering where the automatically generated cronjob setting
`54 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null`
is getting the parameters from?
How does the cronjob know to use dns authentication?
And how does it know where to copy the newly acquired certificates to?
And what post-renewal commands to run?

I couldn't find any hints in the documentation.

After installing, I executed the following commands:
`acme.sh --issue --dns dns_netcup -d domain.de`

`acme.sh --install-cert -d domain.de \
--cert-file      /etc/apache2/ssl/domain.de/cert.pem  \
--key-file       /etc/apache2/ssl/domain.de/key.pem  \
--fullchain-file /etc/apache2/ssl/domain.de/fullchain.pem \
--reloadcmd     "service apache2 force-reload" \
--renew-hook "/usr/local/bin/certbot_postrenewal_acme.sh"`

Greetings,
Heiko

**Comment by Neilpang** [comment]
```sh
cat  ~/.acme.sh/account.conf

cat ~/.acme.sh/[domain]/[domain].conf
```

**Comment by heikoh81** [comment]
I just completed 1 success full cert retrieval with both commands above.
This is the content of account.conf.
Should the commands above be saved here?

`
LOG_FILE="/root/.acme.sh/acme.sh.log"
LOG_LEVEL=1

#AUTO_UPGRADE="1"

#NO_TIMESTAMP=1

    
export NC_Apikey="SECRET"
export NC_Apipw="SECRET"
export NC_CID="SECRET"
SAVED_NC_Apikey='SECRET'
SAVED_NC_Apipw='SECRET'
SAVED_NC_CID='SECRET'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
`

The only thing I manually added was:
export NC_Apikey="SECRET"
export NC_Apipw="SECRET"
export NC_CID="SECRET"
I also enabled logging.
Everything was there before or was added automatically.

**Comment by Neilpang** [comment]
No,   you should not edit the conf file by your hands.  acme.sh will maintain the values automatically.

I just show them to you to tell you where the parameters are saved.

**Comment by heikoh81** [comment]
Ok, but where would I enter my Netcup DNS API credentials then correctly?
I suggest to add this to the documentation that account.conf should not be edited manually.
So, is everything fine and the cronjob should run fine doing DNS acquisition?

**Comment by Neilpang** [comment]
>> where would I enter my Netcup DNS API credentials then correctly

just enter it in your commandline.

**Comment by heikoh81** [comment]
The wiki does not describe how to do that.

It says:

> export NC_Apikey="<Apikey>"
export NC_Apipw="<Apipassword>"
export NC_CID="<Customernumber>"

and then

> acme.sh --issue --dns dns_netcup -d example.com -d www.example.com

How do I call the export functions?
Like this?
`acme.sh export NC_Apikey="<Apikey>"`

**Comment by virgilwashere** [comment]
> How do I call the export functions?
> Like this?
> `acme.sh export NC_Apikey="<Apikey>"`

This would be the syntax you are looking for:
`acme.sh NC_Apikey="<Apikey>" ...`

**Comment by heyheyhello** [comment]
I'm experiencing same issue. Where should I put the `export` fields? They do not persist in ~/.acme.sh...

My cert is now expired (my fault for not setting up notifications; I hoped acme would work).

```
cat /etc/cron.d/acme-https-certs
# HTTPS certificates via 1984.is DNS nameserver
0 1 * * *      hey    "/home/hey/.acme.sh"/acme.sh --cron --home "/hey/.acme.sh" >> /var/cron/acme-https-certs 2>&1
```

I see this in cron logs:

```
[Tue 15 Mar 2022 01:00:43 AM PDT] Add TXT record using 1984Hosting
[Tue 15 Mar 2022 01:00:43 AM PDT] You haven't specified 1984Hosting username or password yet.
[Tue 15 Mar 2022 01:00:43 AM PDT] Please export as One984HOSTING_Username / One984HOSTING_Password and try again.
[Tue 15 Mar 2022 01:00:43 AM PDT] 1984Hosting login failed for user . Check /hey/.acme.sh/http.header file
[Tue 15 Mar 2022 01:00:43 AM PDT] Error add txt for domain:_acme-challenge.hey.ca
[Tue 15 Mar 2022 01:00:43 AM PDT] Please add '--debug' or '--log' to check more details.
[Tue 15 Mar 2022 01:00:43 AM PDT] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Tue 15 Mar 2022 01:00:50 AM PDT] Error renew hey.ca.
[Tue 15 Mar 2022 01:00:50 AM PDT] ===End cron===
```

I used `export One984HOSTING_Username=...` when first doing setup, but now the values are nowhere to be found in .acme.sh/ folder...

Grep shows only the `SAVED_One984HOSTING_SESSIONID_COOKIE` and `SAVED_One984HOSTING_CSRFTOKEN_COOKIE`...

<details>
<summary>Full grep of ~/acme.sh/</summary>

```
hey@server ~/$ cd .acme.sh 
hey@server ~/.acme.sh$ grep -r One984HOSTING .
./account.conf:SAVED_One984HOSTING_SESSIONID_COOKIE='sessionid=9kw12iewho0g2[...]'
./account.conf:SAVED_One984HOSTING_CSRFTOKEN_COOKIE='csrftoken=ofDQiZ1Z9FDB7G[...]'
./dnsapi/dns_1984hosting.sh:#  One984HOSTING_Username=username
./dnsapi/dns_1984hosting.sh:#  One984HOSTING_Password=password
./dnsapi/dns_1984hosting.sh:    _err "1984Hosting login failed for user $One984HOSTING_Username. Check $HTTP_HEADER file"
./dnsapi/dns_1984hosting.sh:    _err "1984Hosting login failed for user $One984HOSTING_Username. Check $HTTP_HEADER file"
./dnsapi/dns_1984hosting.sh:  _debug "Login to 1984Hosting as user $One984HOSTING_Username"
./dnsapi/dns_1984hosting.sh:  username=$(printf '%s' "$One984HOSTING_Username" | _url_encode)
./dnsapi/dns_1984hosting.sh:  password=$(printf '%s' "$One984HOSTING_Password" | _url_encode)
./dnsapi/dns_1984hosting.sh:    One984HOSTING_SESSIONID_COOKIE="$(grep -i '^set-cookie:' "$HTTP_HEADER" | _egrep_o 'sessionid=[^;]*;' | tr -d ';')"
./dnsapi/dns_1984hosting.sh:    One984HOSTING_CSRFTOKEN_COOKIE="$(grep -i '^set-cookie:' "$HTTP_HEADER" | _egrep_o 'csrftoken=[^;]*;' | tr -d ';')"
./dnsapi/dns_1984hosting.sh:    export One984HOSTING_SESSIONID_COOKIE
./dnsapi/dns_1984hosting.sh:    export One984HOSTING_CSRFTOKEN_COOKIE
./dnsapi/dns_1984hosting.sh:    _saveaccountconf_mutable One984HOSTING_SESSIONID_COOKIE "$One984HOSTING_SESSIONID_COOKIE"
./dnsapi/dns_1984hosting.sh:    _saveaccountconf_mutable One984HOSTING_CSRFTOKEN_COOKIE "$One984HOSTING_CSRFTOKEN_COOKIE"
./dnsapi/dns_1984hosting.sh:  if [ -z "$One984HOSTING_Username" ] || [ -z "$One984HOSTING_Password" ]; then
./dnsapi/dns_1984hosting.sh:    One984HOSTING_Username=""
./dnsapi/dns_1984hosting.sh:    One984HOSTING_Password=""
./dnsapi/dns_1984hosting.sh:    _err "Please export as One984HOSTING_Username / One984HOSTING_Password and try again."
./dnsapi/dns_1984hosting.sh:  One984HOSTING_SESSIONID_COOKIE="${One984HOSTING_SESSIONID_COOKIE:-$(_readaccountconf_mutable One984HOSTING_SESSIONID_COOKIE)}"
./dnsapi/dns_1984hosting.sh:  One984HOSTING_CSRFTOKEN_COOKIE="${One984HOSTING_CSRFTOKEN_COOKIE:-$(_readaccountconf_mutable One984HOSTING_CSRFTOKEN_COOKIE)}"
./dnsapi/dns_1984hosting.sh:  if [ -z "$One984HOSTING_SESSIONID_COOKIE" ] || [ -z "$One984HOSTING_CSRFTOKEN_COOKIE" ]; then
./dnsapi/dns_1984hosting.sh:  One984HOSTING_SESSIONID_COOKIE=""
./dnsapi/dns_1984hosting.sh:  One984HOSTING_CSRFTOKEN_COOKIE=""
./dnsapi/dns_1984hosting.sh:  _saveaccountconf_mutable One984HOSTING_SESSIONID_COOKIE "$One984HOSTING_SESSIONID_COOKIE"
./dnsapi/dns_1984hosting.sh:  _saveaccountconf_mutable One984HOSTING_CSRFTOKEN_COOKIE "$One984HOSTING_CSRFTOKEN_COOKIE"
./dnsapi/dns_1984hosting.sh:  export _H1="Cookie: $One984HOSTING_CSRFTOKEN_COOKIE;$One984HOSTING_SESSIONID_COOKIE"
./dnsapi/dns_1984hosting.sh:  export _H1="Cookie: $One984HOSTING_CSRFTOKEN_COOKIE;$One984HOSTING_SESSIONID_COOKIE"
./dnsapi/dns_1984hosting.sh:  csrf_header="$(echo "$One984HOSTING_CSRFTOKEN_COOKIE" | _egrep_o "=[^=][0-9a-zA-Z]*" | tr -d "=")"
./dnsapi/dns_1984hosting.sh:  export _H1="Cookie: $One984HOSTING_CSRFTOKEN_COOKIE;$One984HOSTING_SESSIONID_COOKIE"
hey@server ~/.acme.sh$
```

</details>

I see the issue is closed - where should I store the `export One984HOSTING_Username=...` and password fields?

**Comment by iuliandita** [comment]
The `export` command sets your API info as environment variables for the current, logged on session.

Try this in your terminal:
```
$ export MY_VAR="value"
```
You can now use the variable named MY_VAR in your session:
```
$ echo $MY_VAR
value
```

If you have the DNS API vars set up, `acme.sh` should pick them up and use them to connect to your DNS provider.
On issuing, it updates the `.acme.sh/account.conf` file and adds these lines:
```
SAVED_NC_Apikey='...'
SAVED_NC_Apipw='...'
SAVED_NC_CID='...'
```
It also puts other domain relevant information in the `.acme.sh/domain.com/domain.com.conf` file.
Both of these conf files are automatically updated by `acme.sh`, so you don't need to touch them. They are being used by the cron job too.



PS: Alternatively, you can also set the environment variables in `/etc/environment`, and they will be available on every reconnect, like so (without the export command):
```
NC_Apikey=""
NC_Apipw=""
NC_CID=""
````
