### ISSUE TITLE
webservice wrapper

### ISSUE THREAD

**Issue by vixns** [Neilpang/acme.sh#2169]
FYI I just published https://github.com/vixns/acme.sh.ws
It's a very simple webservice wrapper for acme.sh
We are using it on production with docker or mesos for months, it just works.

We are open to contributions, PR are welcome.

You may want to reference this tool somewhere in the readme or the wiki.

**Comment by Neilpang** [comment]
happy to hear that you are using acme.sh.

would you like to explain more about your project ?

I didn't get your point.

Thanks.

**Comment by vixns** [comment]
acme.sh is really helpful, thank you to maintain it.
My point is to be able to issue certificates without granting console access to users or for applications running on isolated environments.
Using a command line interface in these cases does not fit.
Having a simple http rest interface is friendlier with our services oriented environments.

**Comment by Neilpang** [comment]
Ok, understood.

It's an adapter from acme.sh to REST api.
