### ISSUE TITLE
 Sign error, can not get order link location header

### ISSUE THREAD

**Issue by san360** [Neilpang/acme.sh#2179]
[Wed Mar 20 05:07:39 EDT 2019] _post_url='https://aaaaa.aaaa.aaaa.com:8443/ACME-server/order/LGNdBqurQk9OpSJgJNqN0                                                            gAAAWmaWxgI/finalize'
[Wed Mar 20 05:07:39 EDT 2019] body='{"protected": "eyJub25jZSI6ICJOY3ZiTDZmdGdUcS00cnhaS29oNHB3QUFBV21hV3luaiIsICJ1cmwiOiAiaHR                                                            0cHM6Ly9ucmNoYnMtc2x0NDA0Ny5uaWJyLm5vdmFydGlzLm5ldDo4NDQzL0FDTUUtc2VydmVyL29yZGVyL0xHTmRCcXVyUWs5T3BTSmdKTnFOMGdBQUFXbWFXeGdJL2                                                            ZpbmFsaXplIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cDovL25yY2hicy1zbHQ0MDQ3Lm5pYnIubm92YXJ0aXMubmV0OjgwODAvQUNNRS1zZXJ2ZXIvYWNjb                                                            3VudC9lUXFxblVtczBWVHVPcUxyNW85Q0hRQUFBV21hUE9UbiJ9", "payload": "eyJjc3IiOiAiTUlJQ3V6Q0NBYU1DQVFBd0t6RXBNQ2NHQTFVRUF3d2dibkoxY                                                            zJOaExYTnNaRFF4TURVdWJtbGljaTV1YjNaaGNuUnBjeTV1WlhRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNpUHFia3dyLWNBVGtn                                                            YnBnLXNYcEQzb05GOVNuaVVfM0xmRWhVd3JvNDJjT1hUMmRFTUdNcktVSWpRWFNQeVpSMGlRcTgybE91ZzA2Y2dKT2NsYzMzQTVGU1lwZFdiNFhlYURSZ3J3N1lndTd                                                            LZWYzODZwNHhDcWU2T2p2SGEzdVlRbUloMFNFVWZNSGVzSWJWcFI2RVZ3ZnVHOExrVmF1OWtZaVdYdTVMMFhpRG14Qmd0OUNpVE5nRjRrRGowUXRIeEpUSVM5OGFOTW                                                            hHSHdaRWhoSHZwVVVNWnBxX3VZMDZpMTJObmtWMVgwanRQY3N5ZVBmSXVEeU15bGlJSlY1dDdwbVNUcU9lc28zTzJuakpfX3pjalF1bDNkT2VSZFpoQ0xDUlNuRmwyd                                                            2RyNHVZWVBwNmVhajZwTElvLUJ0aXFqZHZWZS1uZ3BSdWVxdXh6b0t2UEFnTUJBQUdnU3pCSkJna3Foa2lHOXcwQkNRNHhQREE2TUFzR0ExVWREd1FFQXdJRjREQXJC                                                            Z05WSFJFRUpEQWlnaUJ1Y25WelkyRXRjMnhrTkRFd05TNXVhV0p5TG01dmRtRnlkR2x6TG01bGREQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEZzBKUHp2QUNFeWR                                                            aZmxPb3lQUlNQTG5CbmQ1SUdGV29rRzlzenViQTc5X29tbjVWZG5BcGlhaXZjVWpGaHBkN1dsNVduZHl0RDRxd1JUcnktNDYwWkxSNW5yclpfQ2hFYmhEa1VjcGxMck                                                            ozMzVuYlJVOElHRWxJRTFhU2toTVk2bWhlRTdfOFRmazN1M05QVHltcV9adk13b1hEODRSRmlxbzVxTERTcERzcUwwVlVxd1hyb1NDWldKbFpSa3lkclRxelJndUE4Q                                                            llnSlcwSGJPSkY5V0pNUUFmdTF1SHNGdTlzc0pBN1dndEpucVY4YllkNkwzOTcyd2JEaEIydDZ1UHp6cEgzWEVTeEw5VWhyQWVwWGpVX19uUlZyY3pHSlI2cHdMb3RG                                                            cHNzQXZ6Z2hpeHlHZUtxQk1hU2pkSDgxcFlyMmpoTzYwN0hCdE9CTzYxNVEifQ", "signature": "OEGGt5wtpVFHFuATihh_uOTE9Ec65Zxmzr0yL9v5ixdcSvuM                                                            vpHGcQoUa9DItGTVwbe9STaP1nJPAy9fXu7zq8b_5QIRuNxK3naqBiBo1kQ4f3uk3HLWEk6osI4loeGyec0tBo4LQCmj0SRlSetiv_-660vnXbSt5LWU98DbE-p_lre                                                            1KDSyvvkZPC0Ig-Wf_p9t1LfeUYrqJt5nFuYJAxjKGf51Q819DFgmEsTsI7ob0W_jbNr_8jf4_EmFqx-ZoBo7DLj1u1dNJP9K0YNNVYoMT9gLW0q_ohIDL-MXXr9ouc                                                            5WFPE6SZYpsThNHPor7P4rH5HRolSAA0dyDecX0Q"}'
[Wed Mar 20 05:07:39 EDT 2019] _postContentType='application/jose+json'
[Wed Mar 20 05:07:39 EDT 2019] Http already initialized.
[Wed Mar 20 05:07:39 EDT 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.EjkxByh                                                            aJM  -g '
[Wed Mar 20 05:07:43 EDT 2019] _ret='0'
[Wed Mar 20 05:07:43 EDT 2019] responseHeaders='HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Replay-Nonce: ehtHQFAuC2mr4cCzFpgMKQAAAWmaWy1T
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 20 Mar 2019 09:07:43 GMT
Server: App Server
'
[Wed Mar 20 05:07:43 EDT 2019] code='200'
[Wed Mar 20 05:07:43 EDT 2019] original='{"status":"valid","expires":"2019-03-21T09:07:35.049Z","identifiers":[{"type":"dns","v                                                            alue":"nrusca-sld4105.nibr.novartis.net"}],"authorizations":["https://aaaaa.aaaa.aaaa.com:8443/ACME-server/authz/k                                                            G27ChsaMhcttpu8swdr4AAAAWmaWxgT"],"finalize":"https://aaaaa.aaaa.aaaa.com:8443/ACME-server/order/LGNdBqurQk9OpSJgJ                                                            NqN0gAAAWmaWxgI/finalize","certificate":"https://aaaaa.aaaa.aaaa.com:8443/ACME-server/cert/SWsPkXUWOGA4jW_rfEwQTgA                                                            AAWmaWzcw"}'
[Wed Mar 20 05:07:43 EDT 2019] response='{"status":"valid","expires":"2019-03-21T09:07:35.049Z","identifiers":[{"type":"dns","v                                                            alue":"nrusca-sld4105.nibr.novartis.net"}],"authorizations":["https://aaaaa.aaaa.aaaa.com:8443/ACME-server/authz/k                                                            G27ChsaMhcttpu8swdr4AAAAWmaWxgT"],"finalize":"https://aaaaa.aaaa.aaaa.com:8443/ACME-server/order/LGNdBqurQk9OpSJgJ                                                            NqN0gAAAWmaWxgI/finalize","certificate":"https://aaaaa.aaaa.aaaa.com:8443/ACME-server/cert/SWsPkXUWOGA4jW_rfEwQTgA                                                            AAWmaWzcw"}'

[Wed Mar 20 05:07:43 EDT 2019] Sign error, can not get order link location header
[Wed Mar 20 05:07:43 EDT 2019] responseHeaders='HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Replay-Nonce: ehtHQFAuC2mr4cCzFpgMKQAAAWmaWy1T
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 20 Mar 2019 09:07:43 GMT
Server: App Server
'
[Wed Mar 20 05:07:43 EDT 2019] _on_issue_err
[Wed Mar 20 05:07:43 EDT 2019] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Wed Mar 20 05:07:43 EDT 2019] _chk_vlist
[Wed Mar 20 05:07:43 EDT 2019] openssl exists=0
[Wed Mar 20 05:07:43 EDT 2019] nginx exists=1
[Wed Mar 20 05:07:43 EDT 2019] socat exists=1
[Wed Mar 20 05:07:43 EDT 2019] socat doesn't exists.
[Wed Mar 20 05:07:43 EDT 2019] Diagnosis versions:
openssl:openssl

**Comment by Neilpang** [comment]
can you give the full log with `--debug 2` ?

**Comment by Neilpang** [comment]
please with the latest dev branch:
```sh
acme.sh --upgrade -b dev
```

It will be working.

Thanks.
