### ISSUE TITLE
Can not connect to https://acme-v01.api.letsencrypt.org/directory to get nonce.

### ISSUE THREAD

**Issue by GiacomoK** [Neilpang/acme.sh#218]
Hi,
I am using this script on qnap nas to get a ssl certificate.
This is what I do:

./acme.sh --issue -d mydomain.com -w /share/homes/admin/acme

but I get the error as subject. Am I doing something wrong?

Thanks.

**Comment by Neilpang** [comment]
add  `--debug 2` , and paste the output here.

See how to debug :　https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by Neilpang** [comment]
I guess your  qnap is ipv6 enabled ?

**Comment by Neilpang** [comment]
See these lines:
```
[Mon Jun 20 12:10:38 CEST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Mon Jun 20 12:10:38 CEST 2016] curl exists=0
[Mon Jun 20 12:10:38 CEST 2016] CURL='curl -L --silent --trace-ascii /share/homes/admin/.acme.sh/curl.dump '
[Mon Jun 20 12:10:39 CEST 2016] ret='60'
[Mon Jun 20 12:10:39 CEST 2016] Can not connect to https://acme-v01.api.letsencrypt.org/directory to get nonce.
```

It seems that the `curl` returns error code `60`.

https://curl.haxx.se/libcurl/c/libcurl-errors.html

Which means your device doesn't trust  the ssl certificate of `https://acme-v01.api.letsencrypt.org/directory`

So, the connection is failed.

Is it possible for you to update your cert store in the device ?

**Comment by GiacomoK** [comment]
I will try, even if I guess I am not able to :(

**Comment by Neilpang** [comment]
Don't worry. 　　I  just made a fix for you :  13d7cae9e22db91654af94526330d82701ecaa48

You can now add `--insecure` to ignore the certificate error:

Please install the latest version, and try:

```
acme.sh  --issue  --insecure  .......
```

**Comment by GiacomoK** [comment]
First of all, thank you so much, you are very gentle.
Anyway I got another error:

egrep: invalid option -- o

My qnap linux version does not support that option on grep command.
Thanks anyway, I am starting to think to buy a cheap ssl certificate.

p.s. just to know, why your script create .acme.sh/ directory? is it the normal behaviour?

**Comment by Neilpang** [comment]
Please give me your egrep version:
```
egrep --version
```

And :
```
egrep  --help
```

**Comment by Neilpang** [comment]
try:
```
 grep --version

```

**Comment by GiacomoK** [comment]
grep: unrecognized option `--version'

**Comment by Neilpang** [comment]
Hi  @GiacomoK ,

 I have a new project that can issue free cert from startssl.com.

https://github.com/Neilpang/startapi.sh


It's much simpler, so, I guess it should work for you.

**Comment by tsaavik** [comment]
had same problem as OP, used new --insecure switch.
I have gnu grep, not busybox, so everything worked after adding the switch. :)

So anyone else with the problem, upgrade to at least 2.3.2 and add --insecure
