### ISSUE TITLE
Hooks should be allowed to be specified during install 

### ISSUE THREAD

**Issue by miken32** [Neilpang/acme.sh#2181]
The _--pre-hook_ and _--post-hook_ options are ignored when they are used with the **install** command. Since these hooks are run automatically with the **renew** and **cron** commands, I think the natural assumption is that they will behave the same as the _--reloadcmd_ option. But instead they must be specified with the **issue** command.

As an aside, I don't see any need to have hooks on the **issue** command at all, since the hook commands could simply be run by the user or script before and after. That is, it's the same to do `prehook_command && acme.sh --issue ... && posthook_command` instead of `acme.sh --issue --pre-hook prehook_command --post-host posthook_command ...`

**Comment by Neilpang** [comment]
hooks are per certificate,  not per installation.

each cert may require different hooks.

**Comment by miken32** [comment]
Yes, and so is _--reloadcmd_, according to my understanding. I'm not sure how that makes it untenable to add the option of specifying hooks during install.

**Comment by Neilpang** [comment]
@miken32 
It doesn't make any sense to set a hook during installation.   hook for what ?
