### ISSUE TITLE
install-cert key file ownership

### ISSUE THREAD

**Issue by xtremforce** [Neilpang/acme.sh#2184]
1、用 root 身份运行的 acme.sh --install-cert 的证书怎样修改 owner 为其他用户？

2、如果我手动执行 chown 了，但日后自动续期的话，证书会重新变回 root 的吗？

**Comment by Neilpang** [comment]
>> 2、如果我手动执行 chown 了，但日后自动续期的话，证书会重新变回 root 的吗？

不会
