### ISSUE TITLE
Support notifications like email in cron job

### ISSUE THREAD

**Issue by Neilpang** [Neilpang/acme.sh#2186]
In current cronjob, there is no notifications.
Maybe we can support notificattions: like email, in cronjob.
Everyday, the users will get a notification.

**Comment by centminmod** [comment]
if it's totally optional and end user configurable, sure :)

**Comment by Neilpang** [comment]
@centminmod   yes,  it will be configurable, as always.

**Comment by Neilpang** [comment]
@centminmod 

I just checked in a new branch 'notify':  https://github.com/Neilpang/acme.sh/tree/notify

There are 2 notification methods supported for now: mailgun and sendgrid.

please see the usage:

https://github.com/Neilpang/acme.sh/wiki/notify

**Comment by Neilpang** [comment]
supported
https://github.com/Neilpang/acme.sh/wiki/notify
