### ISSUE TITLE
directory nonexistent error when updating existing cert on synology

### ISSUE THREAD

**Issue by powerdude** [Neilpang/acme.sh#2187]
Steps to reproduce
------------------
 docker exec acme.sh --issue -d "$CERT_DOMAIN" --dns "$CERT_DNS"       --cert-file /usr/syno/etc/certificate/system/default/cert.pem       --key-file /usr/syno/etc/certificate/system/default/privkey.pem       --fullchain-file /usr/syno/etc/certificate/system/default/fullchain.pem       --reloadcmd "/usr/syno/sbin/synoservicectl --reload nginx" --dnssleep 20          
   
Debug log
-----------------
```
acme.sh  --issue .....   --debug 2
```

[Fri Mar 22 13:27:41 EDT 2019] Your cert is in  /acme.sh/XXXXXXXX.XXXXXXXX/XXXXXXXX.XXX.cer
[Fri Mar 22 13:27:41 EDT 2019] Your cert key is in  /acme.sh/XXXXXXXX.XXX/XXXXXXXX.XXX.key
[Fri Mar 22 13:27:41 EDT 2019] The intermediate CA cert is in  /acme.sh/XXXXXXXX.XXX/ca.cer
[Fri Mar 22 13:27:41 EDT 2019] And the full chain certs is there:  /acme.sh/XXXXXXXX.XXX/fullchain.cer
[Fri Mar 22 13:27:41 EDT 2019] Installing cert to:/usr/syno/etc/certificate/system/default/cert.pem
/root/.acme.sh/acme.sh: line 4883: can't create /usr/syno/etc/certificate/system/default/cert.pem: nonexistent directory

the directory is there and the original certs are still there.

**Comment by florid2** [comment]
seems like you are running acme.sh inside a docker. 
if you haven't mapped volume, obviously the directory is not there within that container.
