### ISSUE TITLE
Attempt to install on old release

### ISSUE THREAD

**Issue by mdabney918** [Neilpang/acme.sh#2188]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

We have an OpenSUSE 11.4 server.  Due to the business critical nature of the server, it was never , ever updated.  We are in the process of rewriting.  In the meantime, we've updated our call manager and a custom program that we use to identify customer information doesn't work now, as it needs a security certificate.  I was able to install using curl.  No errors on the initial install.   When I attempted to install, the error was acme.sh command not found.   I attempted to run both from the home directory and from Root using sudo.  Same command not found.  I found a previous instance online and it said to restart terminal.  Same issue.  I also saw where you requested the user reinstall and send you the screen.  The install failed, but directed me to a webpage, where I couldn't find anything relevant to the error.  

"?????@IC-WEB-SUSE:/> sudo curl https://get.acme.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705  100   705    0     0   6271      0 --:--:-- --:--:-- --:--:--  9276
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify faile                                                                              d
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option."

The "--insecure" option gets me this:
" % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705  100   705    0     0    138      0  0:00:05  0:00:05 --:--:--  9155"

I exited the terminal, reentered, issued the command sudo acme.sh --issue -d mydomain.com -w /home/wwwroot/mydomain.com.  Same issue acme.sh: command not found. 

Can you assist?

**Comment by Neilpang** [comment]
do not use `sudo`
acme.sh is install for the current user.

**Comment by mdabney918** [comment]
Reran the install received this, “curl https://get.acme.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705  100   705    0     0   6944      0 --:--:-- --:--:-- --:--:--  9038
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify faile                                                                              d
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
the -k (or --insecure) option.
mdabney@IC-WEB-SUSE:~> cd ./acme.sh”

Ran the install
“mdabney@IC-WEB-SUSE:/acme.sh> ./acme.sh --install
[Mon Mar 25 09:36:18 EDT 2019] Installing to /home/mdabney/.acme.sh
[Mon Mar 25 09:36:18 EDT 2019] Installed to /home/mdabney/.acme.sh/acme.sh
[Mon Mar 25 09:36:18 EDT 2019] No profile is found, you will need to go into /home/mdabney/.acme.sh to use acme.sh
[Mon Mar 25 09:36:18 EDT 2019] Installing cron job
37 0 * * * "/home/mdabney/.acme.sh"/acme.sh --cron --home "/home/mdabney/.acme.sh" > /dev/null
[Mon Mar 25 09:36:18 EDT 2019] Good, bash is found, so change the shebang to use bash as preferred.
[Mon Mar 25 09:36:18 EDT 2019] OK
mdabney@IC-WEB-SUSE:/acme.sh<mailto:mdabney@IC-WEB-SUSE:/acme.sh>>”

Switched directory as it says.  I received the same error  “-bash:  acme.sh:  command not found.  I ran it  both as sudo and as my user
mdabney@IC-WEB-SUSE:~/.acme.sh> acme.sh --issue -d sstire.com -w /home/wwwroot/sstire.com
-bash: acme.sh: command not found

mdabney@IC-WEB-SUSE:~/.acme.sh> sudo acme.sh --issue -d sstire.com -w /home/wwwroot/sstire.com
mdabney's password:
sudo: acme.sh: command not found

Sorry to be a pest and thank you for the help.

Regards.

[name2]
[sns_tire_logo_small]
Michelle E. Dabney, MBA-ITM / Director, Information Technology
mdabney@sstire.com<mailto:mdabney@sstire.com>
S&S Tire / BestOne Tire and Service Centers
Office: 859-233-3157 x10617/Direct: 859-519-1413 / Mobile: 859-227-9509 /Fax: 859-519-1419
1475 Jingle Bell Lane Lexington, KY 40509
http://www.sstire.com<http://www.sstire.com/>
[LinkedIn] <https://www.linkedin.com/in/michelledabney> [NAPW-logo-horiz-RGB-low]

**Comment by mdabney918** [comment]
Thanks.  I never got it to work.  We gave up.






Regards,

[1558349616461_signature.jpg]


[S&S Tire]<http://www.sstire.com/>

Michelle E. Dabney / Director, Information Technology, MBA-ITM, CAPM
mdabney@sstire.com<mailto:mdabney@sstire.com>

S&S Tire
Office: 859-233-3157 x10617/Direct: 859-519-1413 / Mobile: 859-227-9509 /Fax: 859-519-1419
1475 Jingle Bell LaneLexington, KY 40509
http://www.sstire.com<http://www.sstire.com/>

[LinkedIn] <https://www.linkedin.com/in/michelledabney>


________________________________
