### ISSUE TITLE
ECC Private Key truncated by acme.sh when called with invalid --keylength

### ISSUE THREAD

**Issue by felixbuenemann** [Neilpang/acme.sh#2192]
acme.sh version 46fbd7f1e1fc355c34c76b6457e6a6959b5a387b (March 15th) truncated the private key of my ecc certificate.

I had both a RSA-2048 and an ECC-384 cert installed.

I then tried to replace the RSA-2048 cert with a RSA-4096 cert, but used the wrong syntax for `--keylength` (`rsa-4096` instead of `4096`):

```bash
$ acme.sh --issue --nginx -d example.org --keylength rsa-4096 --force
[Sat Mar 23 17:46:35 UTC 2019] Creating domain key
[Sat Mar 23 17:46:35 UTC 2019] Create key error.
[Sat Mar 23 17:46:35 UTC 2019] Single domain='example.org'
unable to load Private Key
140327701480512:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
[Sat Mar 23 17:46:35 UTC 2019] Create CSR error.
[Sat Mar 23 17:46:35 UTC 2019] Please add '--debug' or '--log' to check more details.
[Sat Mar 23 17:46:35 UTC 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

This caused acme.sh to overwrite my current *ecc* private key in `~/.acme.sh/example.org_ecc/example.org.key`.

**Comment by updater1234** [comment]
you can try acme.sh --issue --nginx -d example.org -k 4096 --force
