### ISSUE TITLE
Renewed certificate but website still showing expired certificate

### ISSUE THREAD

**Issue by WeeHong** [Neilpang/acme.sh#2193]
Steps to reproduce
------------------
I run `acme.sh --renew -d dev.wispri.com --webroot /var/www/wispri-dev --force` and it shows renew successful message.

When I tried to troubleshoot the issue, I go to letsencrypt folder, I found the certifcation is actually pointing to `/etc/letsencrypt/live/`.

Then I change the path to `/root/.acme.sh/`, yet it the browser still showing not verified.

Debug log
-----------------

```
acme.sh --renew -d dev.wispri.com --webroot /var/www/wispri-dev --force

[Sun Mar 24 12:24:18 +08 2019] Your cert is in  /root/.acme.sh/dev.wispri.com/dev.wispri.com.cer
[Sun Mar 24 12:24:18 +08 2019] Your cert key is in  /root/.acme.sh/dev.wispri.com/dev.wispri.com.key
[Sun Mar 24 12:24:18 +08 2019] The intermediate CA cert is in  /root/.acme.sh/dev.wispri.com/ca.cer
[Sun Mar 24 12:24:18 +08 2019] And the full chain certs is there:  /root/.acme.sh/dev.wispri.com/fullchain.cer
```

**Comment by florid2** [comment]
You just renewed the certificate itself. You also need to install certs to the web service directories. And reload the web service.

**Comment by vadhack** [comment]
Please someone can explain me how can install  those certs in a nodejs server?

**Comment by vadhack** [comment]
how and what exactly shoud convert to .pem format?
