### ISSUE TITLE
NAS install - Documentation update suggestions

### ISSUE THREAD

**Issue by dolphinkite** [Neilpang/acme.sh#2194]
Hello,

I'm using this script for the first time, looking at having a signed certificate on my Synology NAS that has port 80 blocked by my ISP.

Reading the wiki page here (https://github.com/Neilpang/acme.sh/wiki/Synology-NAS-Guide) I found a few things that could be improved:
1- the link to the CloudFare API key isn't valid anymore
2- Which key should I enter? On CloudFare, I see a Global API key and an Origin CA key. Which one should be used?

**Comment by florid2** [comment]
1. I updated the link
2. Global API key
