### ISSUE TITLE
acme.sh should have a presence on a Git forge with IPv6

### ISSUE THREAD

**Issue by awilfox** [Neilpang/acme.sh#2200]
Steps to reproduce
------------------
`git clone https://github.com/Neilpang/acme.sh.git`

Debug log
-----------------
```
awilcox on annwyn ~ $ git clone https://github.com/Neilpang/acme.sh.git
Cloning into 'acme.sh'...
fatal: unable to access 'https://github.com/Neilpang/acme.sh.git/': Couldn't connect to server
```

This server [only has IPv6 connection, it doesn't have IPv4](https://catfox.life/2019/03/31/github-and-ipv6-three-years-later/).  I wanted to try `acme.sh` for myself, but I don't trust `curl | sh`, and I can't clone the Git repository.  Any way to put a mirror of the Git repository on something like Savannah or BitBucket or a private server that has IPv6 connectivity?

**Comment by FernandoMiguel** [comment]
https://github.com/isaacs/github/issues/354#thread-subscription-status
