### ISSUE TITLE
Option to not check cloudflare for when DNS records are updated

### ISSUE THREAD

**Issue by scj643** [Neilpang/acme.sh#2204]
When using the latest version I noticed that it's checking cloudflare for the txt records. In some locations this isn't possible and should have an option to disable

**Comment by Neilpang** [comment]
you can specify `--densleep 200` options to disable the default cloudlfare checks.
It means to sleep/wait for 200 seconds before the txt record can propagate.

**Comment by scj643** [comment]
Ok thanks
