### ISSUE TITLE
Auto renewal broken: integer expression expected

### ISSUE THREAD

**Issue by fboender** [Neilpang/acme.sh#2208]
Automatic renewal randomly broke for a few of my certs. acme.sh fails with the following output for each cert:

    root @ zoltar /etc/acme $ /etc/acme/acme.sh --cron --home "/etc/acme" --renew-hook "/etc/init.d/nginx reload"
    [Sat Apr  6 09:14:16 CEST 2019] ===Starting cron===
    [Sat Apr  6 09:14:16 CEST 2019] Renew: 'build.electricmonk.nl'
    /etc/acme/acme.sh: line 3636: [: "1554418842": integer expression expected
    [Sat Apr  6 09:14:17 CEST 2019] Run pre hook:'""'
    /etc/acme/acme.sh: line 3053: : command not found
    [Sat Apr  6 09:14:17 CEST 2019] Error when run pre hook.
    [Sat Apr  6 09:14:17 CEST 2019] _on_before_issue.
    [Sat Apr  6 09:14:17 CEST 2019] Error renew build.electricmonk.nl.

I'm using v2.8.1:

    $ /etc/acme/acme.sh --version
    https://github.com/Neilpang/acme.sh
    v2.8.1

Debug output:

    $ /etc/acme/acme.sh --debug 2 --cron --home "/etc/acme" --renew-hook "/etc/init.d/nginx reload"
    [Sat Apr  6 09:17:09 CEST 2019] Lets find script dir.
    [Sat Apr  6 09:17:09 CEST 2019] _SCRIPT_='/etc/acme/acme.sh'
    [Sat Apr  6 09:17:09 CEST 2019] _script='/etc/acme/acme.sh'
    [Sat Apr  6 09:17:09 CEST 2019] _script_home='/etc/acme'
    [Sat Apr  6 09:17:09 CEST 2019] Using config home:/etc/acme
    [Sat Apr  6 09:17:09 CEST 2019] LE_WORKING_DIR='/etc/acme'
    https://github.com/Neilpang/acme.sh
    v2.8.1
    [Sat Apr  6 09:17:09 CEST 2019] Using config home:/etc/acme
    [Sat Apr  6 09:17:09 CEST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
    [Sat Apr  6 09:17:09 CEST 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
    [Sat Apr  6 09:17:09 CEST 2019] ===Starting cron===
    [Sat Apr  6 09:17:09 CEST 2019] Using config home:/etc/acme
    [Sat Apr  6 09:17:09 CEST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
    [Sat Apr  6 09:17:09 CEST 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
    [Sat Apr  6 09:17:09 CEST 2019] _stopRenewOnError
    [Sat Apr  6 09:17:09 CEST 2019] di='/etc/acme/build.electricmonk.nl/'
    [Sat Apr  6 09:17:09 CEST 2019] d='build.electricmonk.nl'
    [Sat Apr  6 09:17:09 CEST 2019] Using config home:/etc/acme
    [Sat Apr  6 09:17:09 CEST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
    [Sat Apr  6 09:17:09 CEST 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
    [Sat Apr  6 09:17:09 CEST 2019] DOMAIN_PATH='/etc/acme/build.electricmonk.nl'
    [Sat Apr  6 09:17:09 CEST 2019] Renew: 'build.electricmonk.nl'
    [Sat Apr  6 09:17:09 CEST 2019] Le_API
    [Sat Apr  6 09:17:09 CEST 2019] _main_domain='build.electricmonk.nl'
    [Sat Apr  6 09:17:09 CEST 2019] _alt_domains='no'
    [Sat Apr  6 09:17:09 CEST 2019] '/var/www/build.electricmonk.nl/htdocs/' does not contain 'dns'
    [Sat Apr  6 09:17:09 CEST 2019] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
    [Sat Apr  6 09:17:09 CEST 2019] _init api for server: https://acme-v02.api.letsencrypt.org/directory
    [Sat Apr  6 09:17:09 CEST 2019] GET
    [Sat Apr  6 09:17:09 CEST 2019] url='https://acme-v02.api.letsencrypt.org/directory'
    [Sat Apr  6 09:17:09 CEST 2019] timeout=
    [Sat Apr  6 09:17:09 CEST 2019] _CURL='curl -L --silent --dump-header /etc/acme/http.header  --trace-ascii /tmp/tmp.Y7CwH6z52f  -g '
    [Sat Apr  6 09:17:10 CEST 2019] ret='0'
    [Sat Apr  6 09:17:10 CEST 2019] response='{
      "7Rv1rTRHP5Y": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
      "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
      "meta": {
        "caaIdentities": [
          "letsencrypt.org"
        ],
        "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
        "website": "https://letsencrypt.org"
      },
      "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
      "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
      "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
      "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
    }'
    [Sat Apr  6 09:17:10 CEST 2019] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
    [Sat Apr  6 09:17:10 CEST 2019] ACME_NEW_AUTHZ
    [Sat Apr  6 09:17:10 CEST 2019] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
    [Sat Apr  6 09:17:10 CEST 2019] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
    [Sat Apr  6 09:17:10 CEST 2019] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
    [Sat Apr  6 09:17:10 CEST 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
    [Sat Apr  6 09:17:10 CEST 2019] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
    [Sat Apr  6 09:17:10 CEST 2019] ACME_VERSION='2'
    [Sat Apr  6 09:17:10 CEST 2019] Le_NextRenewTime='"1554418842"'
    /etc/acme/acme.sh: line 3636: [: "1554418842": integer expression expected
    [Sat Apr  6 09:17:10 CEST 2019] _on_before_issue
    [Sat Apr  6 09:17:10 CEST 2019] _chk_main_domain='build.electricmonk.nl'
    [Sat Apr  6 09:17:10 CEST 2019] _chk_alt_domains
    [Sat Apr  6 09:17:10 CEST 2019] Run pre hook:'""'
    /etc/acme/acme.sh: line 3053: : command not found
    [Sat Apr  6 09:17:10 CEST 2019] Error when run pre hook.
    [Sat Apr  6 09:17:10 CEST 2019] _on_before_issue.
    [Sat Apr  6 09:17:10 CEST 2019] Return code: 1
    [Sat Apr  6 09:17:10 CEST 2019] Error renew build.electricmonk.nl.

I've tried with both `https://github.com/Neilpang/acme.sh/archive/master.tar.gz` and `https://github.com/Neilpang/acme.sh/archive/dev.tar.gz`, with the same results.

I'm not aware of any changes to my system that could have caused this problem, unless acme.sh automatically upgrades itself.

**Comment by fboender** [comment]
Contents of the configuration file for that cert:

    root @ zoltar /etc/acme $ cat /etc/acme/build.electricmonk.nl/build.electricmonk.nl.conf 
    Le_Domain='build.electricmonk.nl'
    Le_Alt='no'
    Le_Webroot='/var/www/build.electricmonk.nl/htdocs/'
    Le_PreHook='__ACME_BASE64__START_IiI=__ACME_BASE64__END_'
    Le_PostHook='__ACME_BASE64__START_IiI=__ACME_BASE64__END_'
    Le_RenewHook='__ACME_BASE64__START_IiI=__ACME_BASE64__END_'


    Le_Keylength=""
    Le_LinkCert="https://acme-v01.api.letsencrypt.org/acme/cert/REMOVED"
    Le_LinkIssuer="https://acme-v01.api.letsencrypt.org/acme/issuer-cert"
    Le_CertCreateTime="1549321242"
    Le_CertCreateTimeStr="Mon Feb  4 23:00:42 UTC 2019"
    Le_NextRenewTimeStr="Fri Apr  5 23:00:42 UTC 2019"
    Le_NextRenewTime="1554418842"

**Comment by fboender** [comment]
It seems somehow the configuration files have been corrupted. I've never manually touched these (didn't even know they existed), so I have no idea how that would have happened.

    Le_PreHook='__ACME_BASE64__START_IiI=__ACME_BASE64__END_'

This basically decodes the string `IiI=` using openssl, resulting in two double-quotes:

    echo 'IiI=' | openssl base64 -d 
    ""

Changing these lines to:

    Le_PreHook='__ACME_BASE64__START___ACME_BASE64__END_'
    Le_PostHook='__ACME_BASE64__START___ACME_BASE64__END_'
    Le_RenewHook='__ACME_BASE64__START___ACME_BASE64__END_'

And removing the double quotes around the Le_NextRenewTime value, like so:

    Le_NextRenewTime=1554418842

Fixes the problem, and renewal now works for that cert:

    [Sat Apr  6 09:49:40 CEST 2019] Your cert is in  /etc/acme/build.electricmonk.nl/build.electricmonk.nl.cer 
    [Sat Apr  6 09:49:40 CEST 2019] Your cert key is in  /etc/acme/build.electricmonk.nl/build.electricmonk.nl.key 
    [Sat Apr  6 09:49:40 CEST 2019] v2 chain.
    [Sat Apr  6 09:49:40 CEST 2019] The intermediate CA cert is in  /etc/acme/build.electricmonk.nl/ca.cer 
    [Sat Apr  6 09:49:40 CEST 2019] And the full chain certs is there:  /etc/acme/build.electricmonk.nl/fullchain.cer 
    [Sat Apr  6 09:49:40 CEST 2019] _on_issue_success

**Comment by Neilpang** [comment]
It seems like a recent bug, I will fix it soon.

**Comment by fboender** [comment]
Thanks for the quick fix Neil!
