### ISSUE TITLE
域名更换了 DNS 服务器后，直接修改 acme.sh 里的配置可以吗？

### ISSUE THREAD

**Issue by xtremforce** [Neilpang/acme.sh#2211]
最近几个域名从 DNSPod 更换到 CloudXNS，想问下直接修改配置是否可以继续正常自动续期？

1、修改 ~/.acme.sh/account.conf，添加正确的 SAVED_CX_Key 以及 SAVED_CX_Secret
2、修改每个域名的 ~/.acme.sh/域名/域名.conf，将 Le_Webroot='dns_dp' 改成 dns_cx

然后这样是否就可以了？

**Comment by Neilpang** [comment]
可以, 但是不建议你直接修改conf 文件. 这个文件可能会变.

正确的做法是,  重新 issue 一个 证书.
