### ISSUE TITLE
acme.sh no longer working with DNS-01 and nsupdate

### ISSUE THREAD

**Issue by JamesB7** [Neilpang/acme.sh#2212]
Hello,

I am now getting

Challenge error: {"type":"urn:ietf:params:acme:error:badNonce","detail":"JWS has an invalid anti-replay nonce: \"...\"","status": 400}

I thought it might be one server running an old Ubuntu version, so I tried adding on the same domains to another server I have. I get this same error. So it appears that for whatever reason, acme.sh can no longer verify domains with DNS-01. Any idea?

(This is not related to IPv6. It is disabled on both servers now, as someone had suggested that. No change.)

Thanks!

James

**Comment by mnordhoff** [comment]
See also https://community.letsencrypt.org/t/challenge-error-jws-has-an-invalid-anit-replay-nonce-status-400/90765

**Comment by Neilpang** [comment]
@mnordhoff  Thanks.


@JamesB7  please give me full log with `--debug 2`

```
acme.sh --cron --debug 2
```

For badNonce errror, acme.sh will retry for 5 times, so I need to know your full log.

Thanks.

**Comment by JamesB7** [comment]
I was running 2.7.9 and get.sh had been retrieving into the wrong directory instead of upgrading.
