### ISSUE TITLE
Create new order error. Le_OrderFinalize not found

### ISSUE THREAD

**Issue by woshizhugeng** [Neilpang/acme.sh#2213]
[root@VM_0_8_centos dnsapi]# acme.sh --issue -d mucool.me -d *.mucool.me --dns dns_gd --debug
[Wed Apr 10 09:59:06 CST 2019] Lets find script dir.
[Wed Apr 10 09:59:06 CST 2019] _SCRIPT_='/root/.acme.sh/acme.sh'
[Wed Apr 10 09:59:06 CST 2019] _script='/root/.acme.sh/acme.sh'
[Wed Apr 10 09:59:06 CST 2019] _script_home='/root/.acme.sh'
[Wed Apr 10 09:59:06 CST 2019] Using config home:/root/.acme.sh
https://github.com/Neilpang/acme.sh
v2.8.1
[Wed Apr 10 09:59:06 CST 2019] _main_domain='mucool.me'
[Wed Apr 10 09:59:06 CST 2019] _alt_domains='*.mucool.me'
[Wed Apr 10 09:59:06 CST 2019] Using config home:/root/.acme.sh
[Wed Apr 10 09:59:06 CST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Wed Apr 10 09:59:06 CST 2019] DOMAIN_PATH='/root/.acme.sh/mucool.me'
[Wed Apr 10 09:59:06 CST 2019] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Wed Apr 10 09:59:06 CST 2019] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Wed Apr 10 09:59:06 CST 2019] GET
[Wed Apr 10 09:59:06 CST 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Wed Apr 10 09:59:06 CST 2019] timeout=
[Wed Apr 10 09:59:06 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed Apr 10 09:59:07 CST 2019] ret='0'
[Wed Apr 10 09:59:07 CST 2019] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Wed Apr 10 09:59:07 CST 2019] ACME_NEW_AUTHZ
[Wed Apr 10 09:59:07 CST 2019] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Apr 10 09:59:07 CST 2019] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Wed Apr 10 09:59:07 CST 2019] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Wed Apr 10 09:59:07 CST 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Wed Apr 10 09:59:07 CST 2019] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Wed Apr 10 09:59:07 CST 2019] ACME_VERSION='2'
[Wed Apr 10 09:59:07 CST 2019] Le_NextRenewTime
[Wed Apr 10 09:59:07 CST 2019] _on_before_issue
[Wed Apr 10 09:59:07 CST 2019] _chk_main_domain='mucool.me'
[Wed Apr 10 09:59:07 CST 2019] _chk_alt_domains='*.mucool.me'
[Wed Apr 10 09:59:07 CST 2019] Le_LocalAddress
[Wed Apr 10 09:59:07 CST 2019] d='mucool.me'
[Wed Apr 10 09:59:07 CST 2019] Check for domain='mucool.me'
[Wed Apr 10 09:59:07 CST 2019] _currentRoot='dns_gd'
[Wed Apr 10 09:59:07 CST 2019] d='*.mucool.me'
[Wed Apr 10 09:59:07 CST 2019] Check for domain='*.mucool.me'
[Wed Apr 10 09:59:07 CST 2019] _currentRoot='dns_gd'
[Wed Apr 10 09:59:07 CST 2019] d
[Wed Apr 10 09:59:07 CST 2019] _saved_account_key_hash is not changed, skip register account.
[Wed Apr 10 09:59:07 CST 2019] Read key length:
[Wed Apr 10 09:59:07 CST 2019] _createcsr
[Wed Apr 10 09:59:07 CST 2019] Multi domain='DNS:mucool.me,DNS:*.mucool.me'
[Wed Apr 10 09:59:07 CST 2019] Getting domain auth token for each domain
[Wed Apr 10 09:59:07 CST 2019] d='*.mucool.me'
[Wed Apr 10 09:59:07 CST 2019] d
[Wed Apr 10 09:59:07 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Apr 10 09:59:07 CST 2019] payload='{"identifiers": [{"type":"dns","value":"mucool.me"},{"type":"dns","value":"*.mucool.me"}]}'
[Wed Apr 10 09:59:07 CST 2019] RSA key
[Wed Apr 10 09:59:07 CST 2019] HEAD
[Wed Apr 10 09:59:07 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Wed Apr 10 09:59:07 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed Apr 10 09:59:07 CST 2019] _ret='0'
[Wed Apr 10 09:59:07 CST 2019] POST
[Wed Apr 10 09:59:07 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Apr 10 09:59:07 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed Apr 10 09:59:08 CST 2019] _ret='0'
[Wed Apr 10 09:59:08 CST 2019] code='429'
[Wed Apr 10 09:59:08 CST 2019] Le_LinkOrder
[Wed Apr 10 09:59:08 CST 2019] Le_OrderFinalize
[Wed Apr 10 09:59:08 CST 2019] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Wed Apr 10 09:59:08 CST 2019] pid
[Wed Apr 10 09:59:08 CST 2019] No need to restore nginx, skip.
[Wed Apr 10 09:59:08 CST 2019] _clearupdns
[Wed Apr 10 09:59:08 CST 2019] dns_entries
[Wed Apr 10 09:59:08 CST 2019] skip dns.
[Wed Apr 10 09:59:08 CST 2019] _on_issue_err
[Wed Apr 10 09:59:08 CST 2019] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Wed Apr 10 09:59:08 CST 2019] socat doesn't exists.
[Wed Apr 10 09:59:08 CST 2019] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2k-fips  26 Jan 2017
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.14.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -pie'
socat:

**Comment by FernandoMiguel** [comment]
[Wed Apr 10 09:59:08 CST 2019] Create new order error. Le_OrderFinalize not found. {
"type": "urn:ietf:params:acme:error:rateLimited",
"detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
"status": 429

Sounds like you generated too many certs

**Comment by woshizhugeng** [comment]
> [Wed Apr 10 09:59:08 CST 2019] Create new order error. Le_OrderFinalize not found. {
> "type": "urn:ietf:params:acme:error:rateLimited",
> "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
> "status": 429
> 
> Sounds like you generated too many certs

It seems to be like this, what  should i do? i do not understand.
I used Ali before，but --renew failed, then i use godaddy still failed.

**Comment by FernandoMiguel** [comment]
Check that url.
It will explain api limits. 
There's not much to do other than wait for it to be over. 
Then you can issue or renew a new cert. 

If you are doing experiments, please use the staging server that has far higher limits, using --test flag

**Comment by woshizhugeng** [comment]
> Check that url.
> It will explain api limits.
> There's not much to do other than wait for it to be over.
> Then you can issue or renew a new cert.
> 
> If you are doing experiments, please use the staging server that has far higher limits, using --test flag

Thank you very much!
