### ISSUE TITLE
error on alpine linux

### ISSUE THREAD

**Issue by debiansid** [Neilpang/acme.sh#2216]
Steps to reproduce
------------------
```
./acme.sh --issue -d yes.test.com -d *.test.com --dns dns_he --certhome /etc/haproxy/certs --ca-path /etc/ssl/certs --debug 2
```

Debug log
-----------------

```
Fri Apr 12 16:29:04 CST 2019] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error creating new order :: Domain name \"yes.test.com\" is redundant with a wildcard domain in the same request. Remove one or the other from the certificate request.",
  "status":}
```

**Comment by cpu** [comment]
@debiansid You can solve your problem by removing the `-d yes.test.com` domain and leaving just `-d *.test.com`. E.g.:
```
./acme.sh --issue -d '*.test.com' --dns dns_he --certhome /etc/haproxy/certs --ca-path /etc/ssl/certs --debug 2
```

The `yes.test.com` domain is covered by `*.test.com` and Let's Encrypt doesn't let you have overlapping subjects in one certificate.

You may want `-d test.com -d '*.test.com'` if you need to use the certificate for `https://test.com`.
