### ISSUE TITLE
Fails when invoked non-interactively

### ISSUE THREAD

**Issue by inflatador** [Neilpang/acme.sh#2223]
When invoked non-interactively (like via a bash script), acme.sh doesn't seem to be able to create its config directories. API call works, but private key/etc aren't saved anywhere. Note that I am running this script as root.

Steps to reproduce
------------------
Put the following command into a bash script:

./acme.sh --debug --issue --dns -d $domain  --accountemail $email --yes-I-know-dns-manual-mode-enough-go-ahead-please 2>&1 | tee /tmp/results 

Debug log
-----------------
[Thu Apr 18 16:43:41 UTC 2019] Lets find script dir.
[Thu Apr 18 16:43:41 UTC 2019] _SCRIPT_='./acme.sh'
[Thu Apr 18 16:43:41 UTC 2019] _script='/root/acme.sh/acme.sh'
[Thu Apr 18 16:43:41 UTC 2019] _script_home='/root/acme.sh'
[Thu Apr 18 16:43:41 UTC 2019] Using default home:/.acme.sh
[Thu Apr 18 16:43:41 UTC 2019] Using config home:/.acme.sh
touch: cannot touch ‘/.acme.sh/account.conf’: No such file or directory
grep: /.acme.sh/account.conf: No such file or directory
grep: /.acme.sh/account.conf: No such file or directory
./acme.sh: line 1968: /.acme.sh/account.conf: No such file or directory
grep: /.acme.sh/account.conf: No such file or directory
https://github.com/Neilpang/acme.sh
v2.8.1

Full debug at http://paste.openstack.org/show/749492/

**Comment by inflatador** [comment]
Upon further review, it looks like the root cause is that the "issue" command creates the files in /.acme.sh/ instead of ~/.acme.sh . The "renew" command expects the files to be in ~/.acme.sh and claims the files aren't there.

**Comment by inflatador** [comment]
I was able to work around this by copying the dir created at /.acme.sh/ to ~/.acme.sh/' . Moving does not work, as running the script through bash -x shows the the script sometimes looks for files in one place, and sometimes in the other. Symlink is probably a better way to workaround.

**Comment by Neilpang** [comment]
acme.sh finds files from your `$HOME` dir.  It seems that in some cases your `$HOME` is not defined.
Anyway,  you can always use `--home` parameter to specify the home for acme.sh.

```
acme.sh --home  /root/.acme.sh   --issue  -d example.com .....

acme.sh --home  /root/.acme.sh   --renew  -d example.com

acme.sh --home  /root/.acme.sh   --cron
```
