### ISSUE TITLE
Unable to override NSUPDATE_SERVER 

### ISSUE THREAD

**Issue by scifibob** [Neilpang/acme.sh#2225]
acme.sh stores the NSUPDATE_SERVER variable in account.conf, and I'm unable to override it.
I don't know how, but I have 4 diffent local dns servers, and the script always manage to choose the one that is unable to do dynamic updates, and store it in the accont file.
I would think that overriding the variable "NSUPDATE_SERVER" would do it, but it does not work.
I have tried to uninstall acme.sh an installed it again, but then it selects the wrong server even before I start.

**Comment by scifibob** [comment]
I have tried manually to update account.conf, but it seems that the main script updates it somehow, and with the wrong ip.

**Comment by scifibob** [comment]
Even write protecting account.conf didn't work. Obviously, the script are doing some weird things.

**Comment by vestacp** [comment]
the NSUPDATE_SERVER  value can be overwritten now.
everytime you use `export NSUPDATE_SERVER=xxxxxxxxx `,  it will save in the account.conf.

So, only the last NSUPDATE_SERVER is saved, thus, only the last sever's cert can be renewed automatically.

We planned to support  multiple servers in future.   see this bug: https://github.com/Neilpang/acme.sh/issues/2055

**Comment by Neilpang** [comment]
the NSUPDATE_SERVER value can be overwritten now.
everytime you use export NSUPDATE_SERVER=xxxxxxxxx , it will save in the account.conf.

So, only the last NSUPDATE_SERVER is saved, thus, only the last sever's cert can be renewed automatically.

We planned to support multiple servers in future. see this bug: https://github.com/Neilpang/acme.sh/issues/2055
