### ISSUE TITLE
How can we use this on windows server 2012?

### ISSUE THREAD

**Issue by MonsterMMORPG** [Neilpang/acme.sh#223]
I would like to use this software on windows server 2012 with letsencrypt

ty

**Comment by Neilpang** [comment]
wiki:
https://github.com/Neilpang/acme.sh/wiki#4-how-to-run-on-windows-with-cygwin

**Comment by Neilpang** [comment]
Hi @MonsterMMORPG 
I have a new project that can issue free cert from startssl.com.

https://github.com/Neilpang/startapi.sh

It's much simpler, so, I guess it should work for you.
