### ISSUE TITLE
Create a Debian package for acme.sh

### ISSUE THREAD

**Issue by mdbraber** [Neilpang/acme.sh#2262]
I've create [acme.sh-debian](https://github.com/mdbraber/acme.sh-debian) for anyone who'd like to create a Debian package from `acme.sh`. Obviously `acme.sh` already has a very good installer - but if you'd like to package `acme.sh` with your own config files / settings or use unattended-upgrades - this might help.

Please submit any questions or issues to the original repository at https://github.com/mdbraber/acme.sh-debian

**Comment by kapouer** [comment]
Hi,
https://tracker.debian.org/pkg/acme.sh
is in debian/testing, so if no unsolvable bug arise, it will go in next debian 13 release.
