### ISSUE TITLE
How to add new domains to a cert?

### ISSUE THREAD

**Issue by alexanderisora** [Neilpang/acme.sh#2266]
Hello! I regularly add new domains to my service. I need to provide an SSL cert for each new one.

Imagine I have a cert with a couple of existing clients. Like this:

`acme.sh --issue --dns -d *.my-own-site.com -d client1.com -d client2.com --yes-I-know-dns-manual-mode-enough-go-ahead-please`

Now I need to add a new `client3.com` domain to the cert. How do I do it? Will `client1.com` and `client2.com` need to update their `_acme-challenge.*` DNS records?

Thanks for the answers in advance. I love you.

**Comment by FernandoMiguel** [comment]
you just issue a new one with all the certs.
and the next renewal will take that in consideration

super easy

if the DNS validation is more than 48h, you will need new records.

**Comment by alexanderisora** [comment]
> you just issue a new one with all the certs.
> and the next renewal will take that in consideration
> 
> super easy
> 
> if the DNS validation is more than 48h, you will need new records.

Thanks @FernandoMiguel  👍 
Does that also mean also that if I renew a certificate in 3 months I will not have to pass the DNS verification process for existing domains?

**Comment by FernandoMiguel** [comment]
At renewal, you need new DNS records for all domains you wish to renew
