### ISSUE TITLE
DNS name does not have enough labels

### ISSUE THREAD

**Issue by MarcusWolschon** [Neilpang/acme.sh#227]
Same as #116 but happening with the latest Version 2.0.2 of the le.sh script.
<pre>
./le.sh --renew -d kleinbetrieb.biz  --debug
[Wed Jun 29 18:19:35 CEST 2016] /root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf:1:Le_Domain=kleinbetrieb.biz
[Wed Jun 29 18:19:35 CEST 2016] /root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf:2:Le_Alt=ec-384
[Wed Jun 29 18:19:35 CEST 2016] /root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf:3:Le_Webroot=/home/domains/kleinbetrieb.biz/htdocs
[Wed Jun 29 18:19:35 CEST 2016] /root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf:4:Le_Keylength=
[Wed Jun 29 18:19:35 CEST 2016] /root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf:5:Le_RealCertPath=""
[Wed Jun 29 18:19:35 CEST 2016] /root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf:6:Le_RealCACertPath=""
[Wed Jun 29 18:19:35 CEST 2016] /root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf:7:Le_RealKeyPath=""
[Wed Jun 29 18:19:35 CEST 2016] /root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf:8:Le_ReloadCmd=""
[Wed Jun 29 18:19:35 CEST 2016] /root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf:17:Le_RealFullChainPath=""
[Wed Jun 29 18:19:35 CEST 2016] Creating account key
[Wed Jun 29 18:19:35 CEST 2016] Use default length 2048
[Wed Jun 29 18:19:35 CEST 2016] Account key exists, skip
[Wed Jun 29 18:19:35 CEST 2016] RSA key
[Wed Jun 29 18:19:35 CEST 2016] Skip register account key
[Wed Jun 29 18:19:35 CEST 2016] Creating domain key
[Wed Jun 29 18:19:35 CEST 2016] Use length 2048
[Wed Jun 29 18:19:35 CEST 2016] Domain key exists, skip
[Wed Jun 29 18:19:35 CEST 2016] Creating csr
[Wed Jun 29 18:19:35 CEST 2016] CSR exists, skip
[Wed Jun 29 18:19:35 CEST 2016] Verify each domain
[Wed Jun 29 18:19:35 CEST 2016] Getting webroot for domain='kleinbetrieb.biz'
[Wed Jun 29 18:19:35 CEST 2016] _w='/home/domains/kleinbetrieb.biz/htdocs'
[Wed Jun 29 18:19:35 CEST 2016] _currentRoot='/home/domains/kleinbetrieb.biz/htdocs'
[Wed Jun 29 18:19:35 CEST 2016] Getting token for domain='kleinbetrieb.biz'
[Wed Jun 29 18:19:35 CEST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Wed Jun 29 18:19:35 CEST 2016] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "kleinbetrieb.biz"}}'
[Wed Jun 29 18:19:35 CEST 2016] RSA key
[Wed Jun 29 18:19:36 CEST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Wed Jun 29 18:19:36 CEST 2016] nonce='xxxxxxxxxxxxx'
[Wed Jun 29 18:19:37 CEST 2016] code='201'
[Wed Jun 29 18:19:37 CEST 2016] entry
[Wed Jun 29 18:19:37 CEST 2016] token
[Wed Jun 29 18:19:37 CEST 2016] uri
[Wed Jun 29 18:19:37 CEST 2016] keyauthorization='xxxxxxxxxxxxx'
[Wed Jun 29 18:19:37 CEST 2016] dvlist='kleinbetrieb.biz#xxxxxxxxxxxxxxxxxxx##http-01#/home/domains/kleinbetrieb.biz/htdocs'
[Wed Jun 29 18:19:37 CEST 2016] Getting webroot for domain='ec-384'
[Wed Jun 29 18:19:37 CEST 2016] _w='/home/domains/kleinbetrieb.biz/htdocs'
[Wed Jun 29 18:19:37 CEST 2016] _currentRoot='/home/domains/kleinbetrieb.biz/htdocs'
[Wed Jun 29 18:19:37 CEST 2016] Getting token for domain='ec-384'
[Wed Jun 29 18:19:37 CEST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Wed Jun 29 18:19:37 CEST 2016] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "ec-384"}}'
[Wed Jun 29 18:19:37 CEST 2016] RSA key
[Wed Jun 29 18:19:37 CEST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Wed Jun 29 18:19:37 CEST 2016] nonce='xxxxxxxxxxxxxxxx'
[Wed Jun 29 18:19:38 CEST 2016] code='400'
[Wed Jun 29 18:19:38 CEST 2016] new-authz error: {
  "type": "urn:acme:error:malformed",
  "detail": "Error creating new authz :: DNS name does not have enough labels",
  "status": 400
}
[Wed Jun 29 18:19:38 CEST 2016] pid
</pre>

/root/.le/kleinbetrieb.biz/kleinbetrieb.biz.conf contains:

<pre>
Le_Domain=kleinbetrieb.biz
Le_Alt=ec-384
Le_Webroot=/home/domains/kleinbetrieb.biz/htdocs
Le_Keylength=
Le_RealCertPath=""
Le_RealCACertPath=""
Le_RealKeyPath=""
Le_ReloadCmd=""
Le_LinkCert=https://acme-v01.api.letsencrypt.org/acme/cert/xxxxxxxxxxxxx
Le_Vlist=""
Le_LinkIssuer=https://acme-v01.api.letsencrypt.org/acme/issuer-cert
Le_CertCreateTime=1459395264
Le_CertCreateTimeStr="Thu Mar 31 03:34:24 UTC 2016"
Le_RenewalDays=80
Le_NextRenewTime=1466307264
Le_NextRenewTimeStr="Sun Jun 19 03:34:24 UTC 2016"
Le_RealFullChainPath=""
</pre>

The current LetsEncrypt certificate for this domain is already expired because le.sh obviously failed to renew it.

**Comment by MarcusWolschon** [comment]
found it:
Le_Alt=ec-384
should have been
Le_Alt=www.kleinbetrieb.biz

Judging by Google, this is a very common mistake made by users when creating a certificate.
It should check for the string "ec-384" as subject-alt-name and warn the user.

I still can't renew and the entire domain is still offline because now this domain still shows issue  #228 
"./le.sh: line 1232: /...../htdocs/.well-known/acme-challenge/: Is a directory"

**Comment by Neilpang** [comment]
So,  why not upgrade to the latest code ?  

```
le.sh  uninstall

curl https://get.acme.sh | sh

```

Then, you need to issue the cert again:

https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert

**Comment by MarcusWolschon** [comment]
The issue is:
"It should check for the string "ec-384" as subject-alt-name and warn the admin with a HELPFUL message."
Does it do that yet? If not, then why upgrade as the issue is not resolved.

**Comment by Neilpang** [comment]
it was fixed long long ago.
