### ISSUE TITLE
dnsapi: netcup: Error while parsing sessionid on BSD

### ISSUE THREAD

**Issue by devNan0** [Neilpang/acme.sh#2279]
Steps to reproduce
------------------ 
When using the dns_netcup api on BSD (OPNSense in my case) `acme.sh --issue --dns dns_netcup -d example.domain.tld --dnssleep 600`
I got this error:
```
{"serverrequestid":"","clientrequestid":"","action":"updateDnsRecords","status":"error","statuscode":4006,"shortmessage":"Api key in invalid format","longmessage":"The API Key is not in a valid format.","responsedata":""}
```

Found Bug
-----------------

After some debugging I found the bug and wrote a Hotfix
`sed` works different on Linux then BSD

On BSD `sed` throws this error: `sed: 1: "s/\"\}\}//g": RE error: parentheses not balanced`

So I changed this line
https://github.com/Neilpang/acme.sh/blob/57fc5d28a9aa8f4942e78a2843009aa4cc05b2ab/dnsapi/dns_netcup.sh#L120
to
`sid=$(_getfield "$tmp" "8" | sed s/\"responsedata\":\{\"apisessionid\":\"//g | sed -E 's/\"\}\}//g') `

I tested it on FreeBSD (OPNSense) and Debian 9.
I dont know if there ist a better solution for this or if my fix breaks something on other OS

**Comment by Neilpang** [comment]
The `sed -E` option is not portable to all the platforms.
Can we find another way to fix it?
For exmaple:  using `cut`, `sed` and `tr` instead.

**Comment by devNan0** [comment]
I found two solutions without the `sed -E` option.
Both tested on FreeBSD/OPNSense and Debian 9.

Solution 1:
```
sid=$(_getfield "$tmp" "8" | sed s/\"responsedata\":\{\"apisessionid\":\"//g | sed s/\"\}\}//g)
```

Solution 2:
```
sid=$(_getfield "$tmp" "8" | sed s/\"responsedata\":\{\"apisessionid\":\"//g | tr -d '"}}')
```

**Comment by Neilpang** [comment]
please show me the value of `$tmp`.

**Comment by devNan0** [comment]
`$tmp` is the JSON response from the netcup API after the method 'login' and looks like
```
{"serverrequestid":"YYYYYYYYYYYYYYYYYYYYYYYYYYYY","clientrequestid":"","action":"login","status":"success","statuscode":2000,"shortmessage":"Login successful","longmessage":"Session has been created successful.","responsedata":{"apisessionid":"XXXXXXXXXXXXXXXXXXXXXXXX"}}
```

AFAIK the goal is to get the value of `apisessionid` into `$sid`

**Comment by Neilpang** [comment]
try this one:

```sh
sid=$(echo "$tmp" | tr '{}' '\n\n' | grep apisessionid | cut -d : -f 2)

```

If this works for you,  please send a PR

Thanks

**Comment by devNan0** [comment]
Your line returns the apisessionid with `"` like `"XXXXXXXXXXXXXXXXX"`

but this line would work
```
sid=$(echo "$tmp" | tr '{}' '\n\n' | grep apisessionid | cut -d '"' -f 4)
```

Again testet on FreeBSD and Debain 9.

Is this good enough to make a PR?

**Comment by Neilpang** [comment]
yes, go ahead.
