### ISSUE TITLE
./le.sh: line 1232: /..../htdocs/.well-known/acme-challenge/: Is a directory

### ISSUE THREAD

**Issue by MarcusWolschon** [Neilpang/acme.sh#228]
le.sh version 2.0.2

<pre>
./le.sh renew DOMAIN.info
[Wed Jun 29 18:31:46 CEST 2016] Creating account key
[Wed Jun 29 18:31:46 CEST 2016] Account key exists, skip
[Wed Jun 29 18:31:47 CEST 2016] Skip register account key
[Wed Jun 29 18:31:47 CEST 2016] Creating domain key
[Wed Jun 29 18:31:47 CEST 2016] Use length 384
[Wed Jun 29 18:31:47 CEST 2016] Using ec name: secp384r1
[Wed Jun 29 18:31:47 CEST 2016] Domain key exists, skip
[Wed Jun 29 18:31:47 CEST 2016] Creating csr
[Wed Jun 29 18:31:47 CEST 2016] CSR exists, skip
[Wed Jun 29 18:31:47 CEST 2016] Verify each domain
[Wed Jun 29 18:31:47 CEST 2016] Getting webroot for domain='DOMAIN.info'
[Wed Jun 29 18:31:47 CEST 2016] Getting token for domain='DOMAIN.info'
[Wed Jun 29 18:31:49 CEST 2016] Getting webroot for domain='www.DOMAIN.info'
[Wed Jun 29 18:31:49 CEST 2016] Getting token for domain='www.DOMAIN.info'
[Wed Jun 29 18:31:50 CEST 2016] Verifying:DOMAIN.info
./le.sh: line 1232: /...../htdocs/.well-known/acme-challenge/: Is a directory
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[Wed Jun 29 18:31:56 CEST 2016] DOMAIN.info:Verify error:
</pre>

**Comment by MarcusWolschon** [comment]
"--debug" shows:

[Wed Jun 29 18:51:48 CEST 2016] _currentRoot='/home/domains/DOMAIN.biz/htdocs'
[Wed Jun 29 18:51:48 CEST 2016] wellknown_path='/home/domains/DOMAIN.biz/htdocs/.well-known/acme-challenge'
[Wed Jun 29 18:51:48 CEST 2016] writing token: to /home/domains/DOMAIN.biz/htdocs/.well-known/acme-challenge/

Aparently there is a "/" at the end of acme-challange where there should be none.

**Comment by MarcusWolschon** [comment]
egrep -zo '{[^{]*"type"[ ]*:[ ]*"$vtype"[^}]*'
seems to do the trick.
-z replaces \n with \0 and the additional [ ]* allows for spaces between "type": and "http-01" 


entry="$(printf $response | egrep -zo  '\{[^{]*"type"[ ]*:[ ]*"'$vtype'"[^}]*')"
      _debug entry "$entry"
<pre>
      token="$(printf "$entry" | egrep -o '"token"[ ]*:[ ]*"[^"]*' | cut -d : -f 2 | tr -d '"')"
      _debug token $token

      uri="$(printf "$entry" | egrep -o '"uri"[ ]*:[ ]*"[^"]*'| cut -d : -f 2,3 | tr -d '"' )"
      _debug uri $uri
</pre>

**Comment by MarcusWolschon** [comment]
After this fix it still installed the certificate in the wrong place.
/root/.le/DOMAIN/DOMAIN.conf clearly says
Le_RealCertPath="/etc/ssl/certs/letsencrypt_DOMAIN.biz.cert"

but the certificate was happily installed in
/root/.le/DOMAIN.biz/DOMAIN.biz.cer

**Comment by Neilpang** [comment]
Please upgrade:
```
le.sh  uninstall

curl https://get.acme.sh | sh

```

**Comment by MarcusWolschon** [comment]
I did just upgrade before running it and confirmed that the script said it was version 2.0.2,
the latest release (https://github.com/Neilpang/acme.sh/releases)

**Comment by Neilpang** [comment]
If you call `le.sh  uninstall`, it will uninstall, and remove 'le.sh'.

And after you run `curl https://get.acme.sh | sh`.

you will install `acme.sh` instead of `le.sh`.

you must call `acme.sh` instead of `le.sh`

you should install from https://get.acme.sh  anytime.

it will install the latest code.

As for the label `2.0.2`, it's just a label.

**Comment by MarcusWolschon** [comment]
This will not solve the issue.
https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L1444
you still have the same bug in there.

I suggest a proper JSON parser to get around these ugly grep-lines that make way too many assumptions to be robust enough against minor (and perfectly legal) changes to be used for production code.

e.g. this one (in bash)
https://github.com/dominictarr/JSON.sh

**Comment by Neilpang** [comment]
I just tried with  one of my domain in webroot mode.  it works.

Please try again with acme.sh
```
acme.sh   --issue  -d .....  -w ...    --debug 2
```

Paste the log here.

**Comment by MarcusWolschon** [comment]
--issue? The problem is with --renew.

I didn't know it has multiple debug levels. That detail should be documented in --help

**Comment by Neilpang** [comment]
I knew it was with `--renew`

Can you try `--issue` first ?

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
