### ISSUE TITLE
Test mode does not re-verify each time it is run

### ISSUE THREAD

**Issue by jradxl** [Neilpang/acme.sh#2280]
Sorry if I've not understood how acme.sh works or there is an option to force a re-verify.
v2.8.2

If I run with ./acme.sh --test --force .... multiple times, then i see the log message
[Wed 22 May 12:51:23 BST 2019] xxxxx.dyndns.org is already verified, skip http-01.
[Wed 22 May 12:51:23 BST 2019] www.xxxxx.dyndns.org is already verified, skip http-01.
[Wed 22 May 12:51:23 BST 2019] ldap.xxxxx.dyndns.org is already verified, skip http-01.

Since I am trying to find out whether my setup is working correctly, this inability to re-verify each time misleads me into thinking all is OK.
I can circumvent this by each time adding a fake sub-domain, thus causing the new verify and thus I see if the verify step is working OK.

If acme.sh upgrades itself, then it issues a new verify step for all domains, so is there a way to force acme.sh to re-verify on each run.

Thanks

**Comment by Neilpang** [comment]
The verified status is cached on the letsencrypt server end,  not in acme.sh.
you can revoke the verified status first.

```sh
acme.sh --test  --deactivate  -d  xxxxx.dyndns.org  -d www.xxxxx.dyndns.org  -d ldap.xxxxx.dyndns.org
```

**Comment by Neilpang** [comment]
Hi,  @cpu

I remember that not long ago, the letsencrypt staging server disabled the caching for the domain challenge status.  And I ever confirmed that it was working as expected, that:  I need to verify the domain every time.
But recently, I also noticed that the staging has changed.  The domain challenge status is cached again.

do you have any idea ?

Thanks.

**Comment by Neilpang** [comment]
@cpu  it will be very appreciated if you haven any time on this.

Thanks.

**Comment by cpu** [comment]
Hi @Neilpang, apologies I missed your earlier @'s.

Yes, we had temporarily turned off valid authorization reuse in staging for a period and it has since been re-enabled.

One idea to reliably avoid any state reuse in the staging environment for a client test mode is to create a new ACME account per-test. The staging rate limits for account creation are very generous.

Hope that helps!

**Comment by Neilpang** [comment]
@cpu   Thanks.
