### ISSUE TITLE
Handle processing state

### ISSUE THREAD

**Issue by andreasschulze** [Neilpang/acme.sh#2286]
We're using acme.sh (master) and our own ACME-Server.

According to https://tools.ietf.org/html/rfc8555#section-7.1.6 there is a state "processing"
This state is not handled by acme.sh. I'll provide our fix as pull request later

**Comment by Neilpang** [comment]
@andreasschulze   which version are you using?

https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L4390

**Comment by andreasschulze** [comment]
Oh, maybe I used the master branch I checked out a week ago.

this is my solution, by the way: https://github.com/andreasschulze/acme.sh/commit/93740c997c5ea74fe198c37223bba13e4e777b36

I'll try today's master branch version and report results...

**Comment by andreasschulze** [comment]
the version I used did contain https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L4390
so my patch is stil lrequired here.

**Comment by Neilpang** [comment]
please send the PR first.
Thanks.

**Comment by andreasschulze** [comment]
https://github.com/Neilpang/acme.sh/pull/2288
