### ISSUE TITLE
Howto add parameter to curl / force HTTP/1.1

### ISSUE THREAD

**Issue by andreasschulze** [Neilpang/acme.sh#2287]
The ACME Server we use has an open issue handling HTTP/2 requests generated by [curl 7.52.1-5+deb9u9](https://packages.debian.org/stretch/curl).

The current workaround is to uninstall curl and install wget but on the long tail that break other things here.

There is a [commandline option '--http1.1'](https://curl.haxx.se/docs/manpage.html#--http11) to force curl to use this specific protocol.

I would like to somehow add this option to all curl invocations. Is this possible?

**Comment by Neilpang** [comment]
you can install both curl and wget on your machine.
we have an option `--use-wget` to force to use wget.

If you ever used `--use-wget` once,   all your requests will use wget automatically in future.
