### ISSUE TITLE
Inconsistent invocation for creating and renewing ECC

### ISSUE THREAD

**Issue by dilyanpalauzov** [Neilpang/acme.sh#2290]
An RSA certificate is created with `acme.sh --issue -d domailn -w webroot ` and renewed with `acme.sh --renew -d domain --force`.

An ECC certificate is created with `acme.sh --issue -d domail -w webroot --key-length ec-256` and renewed with `acme.sh --renew -d domailn --force --ecc`.

This is not consistent.  Either EC creation and renewal must accepts `--ecc` or both must accept `--key-length ec-256`.

For what purpose does the inconsistency exist.

**Comment by Neilpang** [comment]
it's designed for easy-to-use.
when you issue a cert,  both `ec` and `256` are necessary.
but when you renew the cert, only `--ecc` is necessary.

**Comment by dilyanpalauzov** [comment]
Ease of use is, when on renewal only --renew has to be added.  What happens it there are two different ECC for the domain issued and on renewal only one of them is supposed to be refreshed.  How does the system know what is meant?

**Comment by Neilpang** [comment]
>> What happens it there are two different ECC for the domain issued 

There can be only one ecc cert existing.  The new cert will replace the existing ecc cert.
