### ISSUE TITLE
FreeBSD ACME.SH CRON

### ISSUE THREAD

**Issue by AngelVillaG** [Neilpang/acme.sh#230]
Hi,

Thank you for you great work...

I have a problem with FreeBSD 10.2 RELEASE with acme.sh 2.2.9

If i run the command

Just issue a cert:
# /storage/acme.sh --issue --domain my.domain.com --force --webroot /usr/local/www/apache24/data --home /storage/letsencrypt > /tmp/acme.sh.log

Work correctly

Just renew a cert:
# /storage/acme.sh --renew --domain my.domain.com --force --webroot /usr/local/www/apache24/data --home /storage/letsencrypt > /tmp/acme.sh.log

Renewal correctly

But if i try renewal from crome with this line

00      01      01      *       *       root    /storage/acme.sh --renew --domain my.domain.com --force --webroot /usr/local/www/apache24/data --home /storage/letsencrypt > /tmp/acme.sh.log

The renewal fail

I receive a mail with this 

Cron <root@dc> /storage/acme.sh --renew --domain my.domain.com --force --webroot /usr/local/www/apache24/data --home /storage/letsencrypt > /tmp/acme.sh.log

[Fri Jul  1 19:35:03 COT 2016] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 127
[Fri Jul  1 19:35:03 COT 2016] Can not post to https://acme-v01.api.letsencrypt.org/acme/new-authz.
[Fri Jul  1 19:35:03 COT 2016] Can not get domain token.

The log have this 

# cat /tmp/acme.sh.log
[Fri Jul  1 19:35:00 COT 2016] Renew: my.domain.com
[Fri Jul  1 19:35:01 COT 2016] Skip register account key
[Fri Jul  1 19:35:01 COT 2016] Creating csr
[Fri Jul  1 19:35:01 COT 2016] Single domain='my.domain.com'
[Fri Jul  1 19:35:01 COT 2016] Verify each domain
[Fri Jul  1 19:35:01 COT 2016] Getting webroot for domain='my.domain.com'
[Fri Jul  1 19:35:01 COT 2016] Getting token for domain='my.domain.com'

Please note that i write 'my.domain.com' but y use a valid domain!

I think the problem comes from crom curl or wget paths because no know...

# which curl
/usr/local/bin/curl

Sorry, English isn't not my native language.

**Comment by AngelVillaG** [comment]
Sorry, some text pasted with html y try change later in a computer (i use a phone) and some words bad (is cron not crome)

**Comment by Neilpang** [comment]
Hi @AngelVillaG 

1.  It is not recommended to use your own cronjob,  the default cronjob can handle the renew for you.  It will check if the certificate needs to be renewed,  it only renew the cert if needed.

2. Your cronjob is like:
```
00 01 01 * *  
```
The cronjob is too less frequent ,  That is dangerous.  Sometimes, the renewal may fail, due to the network issue or the error form let's encrypt server.  Then you have only 2 opportunities to renew.

3.  If you want to renew the cert every 30 days.  Please use `--days 30` argument when you issue the cert:
```
acme.sh  --renew  --days 30    ...............
```
Then the cert will be renew automatically every 30 days.

4. If you want the cron job log,  you should do like this:
```
00 01 01 * * root /storage/acme.sh  --cron --home ...............    >/tmp/acme.sh.log 2>&1
```
Maybe, I will add a new parameter `--logfile /tmp/acme.log` soon.  


5. Yes, from your info above, it seems that the curl was not found.

You should run:
```
acme.sh  --cron  --force
```

or 
```
acme.sh  --cron  --force  --debug 2
```

Give me more debug info.

And please paste the account.conf file here:
```
cat  $LE_WORKING_DIR/account.conf
```

**Comment by AngelVillaG** [comment]
Hi,

Thank you for you attention

The new cron is (later adjust you recommendation of
--cron and --days 30 ):

36	23	01	*	*	root	/storage/acme.sh --renew --domain samdom.telemedellin.tv --force --debug 2 --webroot /usr/local/www/apache24/data --home /storage/letsencrypt >/tmp/acme.sh.log 2>&1

The output of $LE_WORKING_DIR/account.conf

# cat  /storage/letsencrypt/account.conf
ACCOUNT_KEY_HASH="<I DELETED THIS IRRELEVANT INFORMATION>"
USER_PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin"

The output of cat /tmp/acme.sh.log

http://pastebin.com/X8JyW838

Thanks

**Comment by AngelVillaG** [comment]
ACCOUNT_KEY_HASH="I DELETE THIS IRRELEVANT INFORMATION"

**Comment by Neilpang** [comment]
It seems that curl was not found in the cron job.
I just updated new debug message.

Please try the latest code.  and paste the log.

**Comment by Neilpang** [comment]
I tried with my freebsd vm. the cronjob works good.

In the cronjob, your should use `--cron`  instead of `--renew`

```
36 23 01 * * root /storage/acme.sh --cron  ...........
```

**Comment by AngelVillaG** [comment]
Download the new code
root@dc:~ # fetch -o /storage/acme.sh https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh
/storage/acme.sh                              100% of   72 kB  407 kBps 00m00s

Allow execution
root@dc:~ # chmod +x /storage/acme.sh                                        
Check version number 
root@dc:~ # cat /storage/acme.sh | grep VER=                                 VER=2.3.0

Clean de log
root@dc:~ # cat /dev/null >/tmp/acme.sh.log

New task 
root@dc:~ # edit /etc/crontab

55    08    02    *    *    root    /storage/acme.sh --cron --domain samdom.telemedellin.tv --force --debug 2 --webroot /usr/local/www/apache24/data --home /storage/letsencrypt >/tmp/acme.sh.log 2>&1

View the log
root@dc:~ # cat /tmp/acme.sh.log

http://pastebin.com/XegXywu7

root@dc:~ # /usr/local/etc/rc.d/apache24 graceful
Performing sanity check on apache24 configuration:
Syntax OK
Performing a graceful restart

Please view the site with the new certs here
https://samdom.telemedellin.tv/icinga/
guest / guest

You new script acme.sh work great! :-)

What is you recommendation for the correct cron task?

Maybe...

# Every Monday 01:00am check if left less than 30 days renewal
00    01    *    *    1    root    /storage/acme.sh --cron  --days 30 --domain samdom.telemedellin.tv --debug 2 --webroot /usr/local/www/apache24/data --home /storage/letsencrypt >/tmp/acme.sh.log 2>&1

# Every Monday 01:30am reload Apache with the renewal certs
30    01    *    *    1    root /usr/local/etc/rc.d/apache24 graceful

Please confirm if you think this is correct or you write the good, i no like make errors and is useful for others...

So many thanks again, you are amazing!

PD:
I promise write a complete tutorial in my blog for all at http://angelcontents.blogspot.com

**Comment by Neilpang** [comment]
I would suggest you  download/git clone the whole project,  and then call  `--install` command.

```
./acme.sh  --install  --home  /storage
```

It will install the cron job for you.  you don't need to add your own cron job.

**Comment by AngelVillaG** [comment]
Understand, perfect :-)

Thanks.

I close the thread...

Have a good day!
