### ISSUE TITLE
Ovh dns api script bug

### ISSUE THREAD

**Issue by adrienyhuel** [Neilpang/acme.sh#2300]
Hello,

I found some inconsistent typo in dns_ovh.sh.

1/
At line 82, you write "OVH_AK="${OVH_AK:-$(_readaccountconf_mutable OVH_AK)}"", so it means AK is stored as mutable "SAVED_OVH_AK" property.
But, at line 93 you write "if [ "$OVH_AK" != "$(_readaccountconf OVH_AK)" ]; then", so you read "OVH_AK" property, then the condition will always be true.
-> line 93 should be _readaccountconf_mutable

2/
At line 112, you write "OVH_CK="${OVH_CK:-$(_readaccountconf_mutable OVH_CK)}"".
So you read CK as "SAVED_OVH_CK" property.
But at line 236, you write "_saveaccountconf OVH_CK "$OVH_CK"", so you save it as "OVH_CK".
-> line 236 should be _saveaccountconf_mutable
And at line 95 and 127, you write "_clearaccountconf OVH_CK", so you clear "OVH_CK".
-> lines 95 and 127 should be _clearaccountconf_mutable

**Comment by Neilpang** [comment]
is there any bugs you saw ?

**Comment by adrienyhuel** [comment]
@Neilpang 
I think it's a bug since the OVH AK and CK are sometimes read/saved/cleared as "mutable" (so "SAVED_XXX"), and sometimes normal properties (no "XXX").

eg : in _ovh_authentication you saved OVH_CK with : _saveaccountconf OVH_CK "$OVH_CK".
So in conf file there is OVH_CK=XXX
But in main method, you read it fom conf file with : _readaccountconf_mutable OVH_CK.
So it reads "SAVED_OVH_CK", which is never written.

**Comment by Neilpang** [comment]
CK is processed differently from AK or AS.

OVH_CK  was never saved as `SAVED_OVH_CK ` yet.

it can be a bug, but it's not as you mentioned.

if you can reproduce the bug, show me the steps.

Thanks.

**Comment by adrienyhuel** [comment]
OK, so let's try something :
1/ export OVH_AK, OVH_AS as env vars, and obtain certs with acme.sh
2/ Now, in conf file you have SAVED_OVH_AK, SAVED_OVH_AS, OVH_CK
3/ Now renew certs, without exporting env vars (as those ar now saved in conf file).
4/ Now in conf file, you have a new OVH_CK, so it means the script obtain a new CK each time, even if it was saved before.

**Comment by Neilpang** [comment]
I don't think so.
I just tried on my machine, it works good.

please double check on your machine first.

It's not possible to create a new OVH_CK without user interactive.

The user is required to authenticate the CK on the webpage.

**Comment by adrienyhuel** [comment]
I just tried on my machine : 

1/ account.conf without AK, AS, or CK
2/ export OVH_AK, OVH_AS
3/ run acme.sh
4/ OVH consumer key is empty, Let's get one, Please open this link to do authentication
5/ in account.conf I have : 
SAVED_OVH_AK='XXX'
SAVED_OVH_AS='XXX'
OVH_CK='XXXX'
6/ exit and relog into linux account (because acme.sh can save some things in env vars)
7/ run acme.sh
8/ OVH consumer key is empty, Let's get one, Please open this link to do authentication
9/ in account.conf I have : 
SAVED_OVH_AK='XXX'
SAVED_OVH_AS='XXX'
OVH_CK='YYYY' -> A new value

**Comment by adrienyhuel** [comment]
Did you exit and relog into linux ?
Because if I do not exit, and relaunch, all is OK and CK doesn't change.

**Comment by Neilpang** [comment]
Yes,  but I don't need to re-authenticate in your step 8

>> 8/ OVH consumer key is empty, Let's get one, Please open this link to do authentication

**Comment by adrienyhuel** [comment]
OK, I did not reproduced my test, I don't know what happened...
Now it works properly if I have 1 certificate to create.

But, If I have multiple certificates to create, on first it create a CK asks to validate it. Then it try to generate second cert, use CK to OVH, get an error (because it is not validated yet), and erase CK from account.cf.

Then you can't use it with 2 certificates, unless you provide manually an already validated CK.

**Comment by adrienyhuel** [comment]
Another problem I found : 
If you try to change your AK and AS with exporting env vars and run acme.sh, it still uses old CK and run into an error.

It's because : 
1/ Line 93 : if [ "$OVH_AK" != "$(_readaccountconf OVH_AK)" ]; then _clearaccountconf OVH_CK
-> _readaccountconf OVH_AK doesn't find "OVH_AK" in account.conf (there is SAVED_OVH_AK), and due to evals in this function, when the key is not found in conf file, it echoes the content of the env var ($OVH_AK).
-> So the OVH_CK is not cleared.

2/ Line 112 : OVH_CK="${OVH_CK:-$(_readaccountconf_mutable OVH_CK)}"
-> The OVH_CK variable is still set, then the script doesn't try to get a new one.
-> Maybe you should unset OVH_CK var after clearing it in conf file in point 1/

**Comment by Neilpang** [comment]
show me the logs with `--debug 2`

**Comment by adrienyhuel** [comment]
- I had SAVED_OVH_AK, SAVED_OVH_AS and OVH_CK in account.conf
- I created an new OVH app, get the AK and AS
- export OVH_AK='new ovh ak'
- export OVH_AS='nex ovh as'
- "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" --force --test --domain adrien60.ovh --debug 2
 - Then errors : '{"errorCode":"NOT_CREDENTIAL","httpCode":"403 Forbidden","message":"This credential does not exist"}'
- In account.conf, SAVED_OVH_AK and SAVED_OVH_AS changed, but there is still old OVH_CK
Please see log attached.
[acme.sh.log](https://github.com/Neilpang/acme.sh/files/3303509/acme.sh.log)

**Comment by Neilpang** [comment]
fixe, please try again,  it seems that  OVH changed its api response.
