### ISSUE TITLE
Bugs，手动模式同时增加根域名和通配符域名时，会产生两条记录，但其实是同样的地址。

### ISSUE THREAD

**Issue by jobbr88** [Neilpang/acme.sh#2306]
手动模式同时增加根域名和通配符域名时，会产生两条记录，但其实是同样的地址，导致无法选择到底要增加哪一条txt。
日志如下：

[Mon Jun  3 02:05:26 CST 2019] Creating domain key
[Mon Jun  3 02:05:26 CST 2019] The domain key is here: /home/work/.acme.sh/hnydmq.com/hnydmq.com.key
[Mon Jun  3 02:05:26 CST 2019] Multi domain='DNS:hnydmq.com,DNS:*.hnydmq.com'
[Mon Jun  3 02:05:26 CST 2019] Getting domain auth token for each domain
[Mon Jun  3 02:05:29 CST 2019] Getting webroot for domain='xxx.com'
[Mon Jun  3 02:05:29 CST 2019] Getting webroot for domain='*.xxx.com'
[Mon Jun  3 02:05:29 CST 2019] Add the following TXT record:
[Mon Jun  3 02:05:29 CST 2019] Domain: '_acme-challenge.xxx.com'
[Mon Jun  3 02:05:29 CST 2019] TXT value: 'xxxx'
[Mon Jun  3 02:05:29 CST 2019] Please be aware that you prepend _acme-challenge. before your domain
[Mon Jun  3 02:05:29 CST 2019] so the resulting subdomain will be: _acme-challenge.hnydmq.com
[Mon Jun  3 02:05:29 CST 2019] Add the following TXT record:
[Mon Jun  3 02:05:29 CST 2019] Domain: '_acme-challenge.xxx.com'
[Mon Jun  3 02:05:29 CST 2019] TXT value: 'xxx'
[Mon Jun  3 02:05:29 CST 2019] Please be aware that you prepend _acme-challenge. before your domain
[Mon Jun  3 02:05:29 CST 2019] so the resulting subdomain will be: _acme-challenge.hnydmq.com
[Mon Jun  3 02:05:29 CST 2019] Please add the TXT records to the domains, and re-run with --renew.
[Mon Jun  3 02:05:29 CST 2019] Please add '--debug' or '--log' to check more details.
[Mon Jun  3 02:05:29 CST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by idler8** [comment]
我也有这个疑问，*不包含@

**Comment by Neilpang** [comment]
所以, 为什么不两个都添加进去呢

**Comment by jobbr88** [comment]
> 所以, 为什么不两个都添加进去呢

非常感谢，已经搞定了。
我之前还以为TXT记录只能增加一条。

谢谢。
