### ISSUE TITLE
Dalao, Could you add support of Freenom?

### ISSUE THREAD

**Issue by xiebruce** [Neilpang/acme.sh#2310]
Hope you can add support of Freenom, thank you!

**Comment by Neilpang** [comment]
你先找一下官方文档, 看看支不支持 api 再说啊.

**Comment by xiebruce** [comment]
@Neilpang 我发现有这个玩意 [Freenom-dns-updater](https://github.com/maxisoft/Freenom-dns-updater)，所以应该是可以的吧？不过我现在可以不用freenom了，谢谢大佬！

**Comment by Neilpang** [comment]
貌似不支持 txt

反正是免费的, 你可以使用 cloudflare api

**Comment by xiebruce** [comment]
嗯嗯，话说，在哪个网站申请证书有什么区别吗？是域名在哪个网站就去哪个网站申请对吗？

**Comment by Neilpang** [comment]
没区别.

准确的说是,  域名在哪里解析,就在哪申请.

**Comment by xiebruce** [comment]
好的，谢谢大佬！

**Comment by kukudemajia** [comment]
> 貌似不支持 txt
> 
> 反正是免费的, 你可以使用 cloudflare api
大佬，freenom可以白撸还是蛮多人用的，支持txt的哦
