### ISSUE TITLE
how to change renewal date

### ISSUE THREAD

**Issue by nerijus** [Neilpang/acme.sh#2311]
I accidentally added "--days 14" to --issue command, so acme.sh put Le_RenewalDays='14' in domain.conf file. I changed it to Le_RenewalDays='60', but when I issue ./acme.sh --list, I still get:
```
Main_Domain                  KeyLength  SAN_Domains             Created                       Renew
domain.com                   "ec-384"   *.domain.com            Tue Jun  4 00:18:07 UTC 2019  Tue Jun 18 00:18:07 UTC 2019
```
it still shows renewal date as Jun 18, i.e. after 14 days. Will it actually renew on Jun 18 or after 60 days?

**Comment by Neilpang** [comment]
Yes,  it will be renewed on Jun 18, but the next renew will be 60 days after.

**Comment by nerijus** [comment]
So if I want to change renewal date, I have to change Le_NextRenewTimeStr and Le_NextRenewTime manually?

**Comment by Neilpang** [comment]
do not edit the conf file manually. 
the correct way is to `--issue` a new one with `--days`
