### ISSUE TITLE
The deploy hook docker is not found.

### ISSUE THREAD

**Issue by shiny** [Neilpang/acme.sh#2312]
I'm trying to run acme.sh following the wiki: https://github.com/Neilpang/acme.sh/wiki/deploy-to-docker-containers
But get stuck in deploy, 

```sh
[Tue Jun  4 13:43:27 UTC 2019] The deploy hook docker is not found.
```

The docker deploy script does not exists in the neilpang/acme.sh image, but exists in  neilpang/acme.sh:docker
Should we switch to acme.sh:docker or wait for an update of the image ?

**Comment by Neilpang** [comment]
please use acme.sh:docker  for now.

it will be merged to master soon.

Thanks.

**Comment by shiny** [comment]
> please use acme.sh:docker for now.
> 
> it will be merged to master soon.
> 
> Thanks.

Oh great, thank you for answering.
