### ISSUE TITLE
多个域名dns api 使用多个不同的key

### ISSUE THREAD

**Issue by xiagw** [Neilpang/acme.sh#2314]
你好，
我有多个 域名，而且每个域名处在不同的dns运营商，
请问 能否修改一下功能，可以存储多个 dns api 的用户/密码？
我注意到当前是存储在 公共的 account.conf 里面？
而不是存储 dns api user/pass 到各个不同的域名子目录下面去，
当前这样似乎 我只能用一个 dns api 账号/密码

**Comment by Neilpang** [comment]
不同的 dns api  可以共存.

但是 同一个 dns api 只能保存一个 key

**Comment by xiagw** [comment]
有可能分开保存 并 复用吗？这样可以 多key 共存，也符合数据保存的理念。

**Comment by xiagw** [comment]
注意到有 dns alias 的方式，但是那个 使用起来还是不太便利。

**Comment by Neilpang** [comment]
后面可能会支持,  看我的时间了.
先用 alias 代替吧.
