### ISSUE TITLE
Support for TNAuthList profile

### ISSUE THREAD

**Issue by grindsa** [Neilpang/acme.sh#2315]
Hi,

Are there any plans to include the support for [TNAuthList profile](https://tools.ietf.org/html/draft-ietf-acme-authority-token-tnauthlist-03) into acme.sh?

BR GrindSA

**Comment by Neilpang** [comment]
Is there any server support it ?

**Comment by grindsa** [comment]
Not that I am aware of but I am expecting it to come up soon. I am thinking to include the support into [my project](https://github.com/grindsa/acme2certifier) but i am looking for a client for testing. So somehow a chicken and egg problem :-)

**Comment by Neilpang** [comment]
cool.  but I would prefer to wait for the official letsencrypt server support it first.

**Comment by grindsa** [comment]
Understood. I am not sure if Letsencrypt will ever support this as its a Telco specific thing. All I found this [this treat from 2 years back](https://community.letsencrypt.org/t/regarding-tl-authorization-list-extention/29369) supporting my statement. Anyway thanks for your answers. I was just curious if there are plans on your side to get it in.
