### ISSUE TITLE
Need help renewing certificates

### ISSUE THREAD

**Issue by DragonOsman** [Neilpang/acme.sh#2316]
My Let's Encrypt certificate expired, so I tried to renew it by running `./acme.sh --renew -d https://dragonosman.dynu.net:5501/` on WSL.  The domain name here is a subdomain name from dynu.com.  Running this command gave me this output: 
```
./acme.sh --renew -d https://dragonosman.dynu.net:5501/
[Sun Jun  9 15:39:47 STD 2019] Renew: 'https://dragonosman.dynu.net:5501/'
[Sun Jun  9 15:39:47 STD 2019] 'https://dragonosman.dynu.net:5501/' is not a issued domain, skip.
```
I'm using Windows 10 Home, version 10.0.17763.503.  Acme.sh version is 2.8.1.  What I'm hosting at the domain name (on my own computer) is a web application I made with the backend code written C++; I used the version of Boost.Beast that comes with Boost version 1.70.0, written as `Boost.Beast/248" in the `BOOST_BEAST_VERSION_STRING` macro value.  

How can I fix this and successfully renew my certificate?

**Comment by DragonOsman** [comment]
I tried using `dragonosman.dynu.net` as the domain as well, but had a similar error (the same as before, except with `dragonosman.dynu.net` as the domain name).

**Comment by Neilpang** [comment]
```
./acme.sh --renew -d   dragonosman.dynu.net
```
