### ISSUE TITLE
No action from mail notification

### ISSUE THREAD

**Issue by jahlives** [Neilpang/acme.sh#2318]
I try to use the notification `mail` on my server running a Centos7. I got the latest devel version to verify if there is a difference between release and devel. 
If I run the following command the notify-level of 3 should always generate a mail, even the renew is skipped
```
"/work/.acme.sh"/acme.sh --set-notify --notify-hook mail --notify-level 3 --notify-mode 1 --auto-upgrade 0 --debug --cron --home "/work/.acme.sh"
```
Prior to the command I use ```export``` to set the necessary variables for the mail command and the values can be seen in account.conf
I set auto-upgrade to 0 just to ensure that --cron does not download latest release again ;-)
According to the output from the command above 
```
[Mon Jun 10 13:43:38 UTC 2019] mail send success.
[Mon Jun 10 13:43:38 UTC 2019] mail Success
```
mail should have been sent.
But if I tcpdump on that box for smtp connections outbound I cannot see one smtp paket leaving the box. Outbound connection from that box work, especially smtp. ```mail``` command is installed and can be found

I'm a bit clueless why acme.sh says it sent the notification but tcpdump proves it wrong

**Comment by Neilpang** [comment]
don't use `--set-notify`  and `--cron` at the same time.
They are 2 different commands.   You can only specify one command a time.

**Comment by jahlives** [comment]
@Neilpang 
thanks for the hint.
But does this mean that --cron can not send notifications? I removed the notify stuff from my command and only fired the --cron. Still says message is sent
```
$ "/work/.acme.sh"/acme.sh --debug --cron --auto-upgrade 0 --home "/work/.acme.sh
[...]
[Mon Jun 10 14:23:55 UTC 2019] Add '--force' to force to renew.
[Mon Jun 10 14:23:55 UTC 2019] Found /work/.acme.sh/notify/mail.sh
[Mon Jun 10 14:23:55 UTC 2019] _subject='Renew MYDOMAIN skipped'
[Mon Jun 10 14:23:55 UTC 2019] _content='Good, the cert next renewal time is Fri Aug  9 09:57:08 UTC 2019.'
[Mon Jun 10 14:23:55 UTC 2019] _statusCode='2'
[Mon Jun 10 14:23:56 UTC 2019] mail send success.
[Mon Jun 10 14:23:56 UTC 2019] mail Success
[Mon Jun 10 14:23:56 UTC 2019] Return code: 2
```
but still tcpdump does not show any outgoing smtp connection
