### ISSUE TITLE
acme.sh fails to create multiple certs

### ISSUE THREAD

**Issue by johann-schmidt** [Neilpang/acme.sh#2326]
Steps to reproduce
------------------
I have six name-based hosts served from my home on an ubuntu 18.04 server using apache 2.4.29. I use Dynu's ddns service. All hosts are accessible on :80. I can create text records on all domains. I previously used acme.sh 2.8.2 (and dns_dynu.sh) to successfully issue a cert for one domain which became accessible on :443. I have write permissions to www doc root /var/www. I have root shell access. I do not use a control panel to manage my sites.

I want certs for all my domains, not sure if a wildcard cert is the way to go. At any rate, I fired this command:
$ acme.sh --issue --debug --force --log-level 2 --server https://acme-staging.api.letsencrypt.org/directory --dns dns_dynu -d mvopd.mywire.org -d blog.mvopd.mywire.org -d cal.mvopd.mywire.org -d cirrus.mvopd.mywire.org -d game01.mvopd.mywire.org -d gen01.mvopd.mywire.org -w /var/www

...and the process failed, logging failures during dns_dynu.sh processing (first reported failure on line 655 in the attached level 2 log). I also ran the above command without the "-w /var/www" as suggested elsewhere with no improvement.

Debug log (with --log-level 2)
-----------------
[js_06_12_19_multiple_cert_failure_acme.sh.log](https://github.com/Neilpang/acme.sh/files/3282322/js_06_12_19_multiple_cert_failure_acme.sh.log)

**Comment by FernandoMiguel** [comment]
You need to choose between DNS and webroot.
Both at the same time can be confusing

Also don't use force unless you know what you are doing..
There's no need to specify LE server, just pass --staging if you want to issue a testing cert
