### ISSUE TITLE
Doesn't support CloudFlare CA key

### ISSUE THREAD

**Issue by h4x3rotab** [Neilpang/acme.sh#2328]
acme.sh can run `--dns dns_cf` with the CF global key without problem but doesn't work with the CA key.

Steps to reproduce
------------------
1. Get the CA Key from my CloudFlare profile (in the format of "v1.0-xxxx-xxxxx")
2. Run the issue command with CF_Email and CF_Key environment variables
3. Got error `invalid domain` and `{"code":6103,"message":"Invalid format for X-Auth-Key header"}`

**Comment by Neilpang** [comment]
what is CA key ?

**Comment by h4x3rotab** [comment]
![image](https://user-images.githubusercontent.com/1343470/59922471-6b09fa80-9463-11e9-83d9-eb54891c000d.png)

As shown in the screenshot, the "Origin CA" key is a special key for ACME validation only.

**Comment by Neilpang** [comment]
where did you find the keyword `ACME` there ?

The Origin CA is not for API.

**Comment by h4x3rotab** [comment]
On the screenshot it says that the "Origin CA Key" is for generating the certificates without giving out the permission to the API to read / write full CF settings. I might be wrong, but what I see is that it's designed for the certification issue validation purpose without compromise of the security.

So disappointed. There's no ACME but this is not a good attitude for the supporters of the project.
