### ISSUE TITLE
DNS mode issue

### ISSUE THREAD

**Issue by enjoyzqq** [Neilpang/acme.sh#233]
Add the following txt record:
Domain:_acme-challenge.aa.com
Txt value:9ihDbjYfTExAYeDs4DBUeuTo18KBzwvTEjUnSwd32-c

Add the following txt record:
Domain:_acme-challenge.www.aa.com
Txt value:9ihDbjxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Please add those txt records to the domains. Waiting for the dns to take effect.
上述 txt records 具体应该被加在哪啊？

**Comment by Neilpang** [comment]
要看你的域名在哪家注册的或者在哪家解析的.

要去添加解析记录.

谷歌搜索,  如果添加域名 txt 解析记录.

**Comment by enjoyzqq** [comment]
谢谢，解决了
