### ISSUE TITLE
the --list command line options output

### ISSUE THREAD

**Issue by pnelsonsr** [Neilpang/acme.sh#2334]
Steps to reproduce
------------------
acme.sh --list

Debug log
-----------------
No debug needed...

the output of the list command lists the Created and Renew dates and times.  I'm not sure if this is a problem but I have noticed it so I thought I would a least ask so I may understand.  So currently I have 2 wild-card domains and it shows something like 

```
Created                          Renew
Fri 31 May 2019 07:48:44 AM UTC  Tue 30 Jul 2019 07:48:44 AM UTC
```

for them (the domains are not important here) so I've been setting my upgrade process based of that Renew date.  However, I was looking at the certs in the web pages and it says something a bit different (which I may add and now that I think of it... seems to match more closely with what I remember happening) which looks like this:

Valid from 4/1/2019 to 6/30/2019

So I ask what is the date I should renew...  Like I said I'd generally do 30 days or so prior to the Renew date listed in the acme.sh --list output.  But should I focus on what the certs say from the webpage (valid from...)?

And why the difference?

BTW I have to do this all manually because we have many services with many different types of certs...

**Comment by Neilpang** [comment]
The cert is valid for 90 days, but acme.sh renews the cert at 60 days.

**Comment by pnelsonsr** [comment]
Which probably makes sense seeing it says renew.  I might be nice to have it report expire, but I got it thanks for replying.
