### ISSUE TITLE
Failing to add TXT and looping

### ISSUE THREAD

**Issue by JeffCleverley** [Neilpang/acme.sh#2335]
Using in a script, using dns api

On occassion it fails to add a record, then just keeps trying forever and stalling the script.

I need to be able to error out after n attempts.

Anyway to do this with Acme, or do I need to work externally?

**Comment by Neilpang** [comment]
use `--dnssleep  300`,   it will wait for 300 seconds at most before the records propagate.  
by default, acme.sh  keeps trying for about 20 minutes.   Anyway, It is not forever.
