### ISSUE TITLE
unary operator expected error with pull request 2339 - NOTIFY_LEVEL not set?

### ISSUE THREAD

**Issue by bguscott** [Neilpang/acme.sh#2341]
Steps to reproduce
------------------
After the latest commit ~7 hours ago I started receiving the following error in my scheduled cron job on my proxmox hypervisor (running the latest patches):
```
/root/.acme.sh/acme.sh: line 4786: [: 3: unary operator expected
```

The line 4786 in question:
```
  if [ "$ACME_IN_CRON" ] && [ $_error_level -le $NOTIFY_LEVEL ]; then
```

Exploring further with `set -x` the following variables are being compared:
```
+ '[' 3 -le ']'
/root/.acme.sh/acme.sh: line 4786: [: 3: unary operator expected
```
Setting `echo $NOTIFY_LEVEL` right before that `if` statement, it looks like `$NOTIFY_LEVEL` isn't set to anything yet.

```
 4786   echo $NOTIFY_LEVEL
 4787   if [ "$ACME_IN_CRON" ] && [ $_error_level -le $NOTIFY_LEVEL ]; then
```
And the output:
```
[Fri Jun 14 18:06:40 MDT 2019] Skipped xxxxxxxx.net

/root/.acme.sh/acme.sh: line 4787: [: 3: unary operator expected
[Fri Jun 14 18:06:40 MDT 2019] ===End cron===
```

**Comment by Neilpang** [comment]
thank you.

fixed now.

**Comment by bguscott** [comment]
Works as expected now. Thank you!!

**Comment by Neilpang** [comment]
@bguscott   sorry about that.
