### ISSUE TITLE
Account key is not found 

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#2343]
=> ERROR [2/3] RUN acme.sh --update-account --accountemail "it.operations@REDACTED" --debug 2                                                                                                                                  0.7s
------
 > [2/3] RUN acme.sh --update-account --accountemail "it.operations@REDACTED" --debug 2:
#5 0.443 [Mon Jun 17 13:03:24 UTC 2019] Lets find script dir.
#5 0.444 [Mon Jun 17 13:03:24 UTC 2019] _SCRIPT_='/usr/local/bin/acme.sh'
#5 0.447 [Mon Jun 17 13:03:24 UTC 2019] _script='/root/.acme.sh/acme.sh'
#5 0.449 [Mon Jun 17 13:03:24 UTC 2019] _script_home='/root/.acme.sh'
#5 0.450 [Mon Jun 17 13:03:24 UTC 2019] Using default home:/root/.acme.sh
#5 0.451 [Mon Jun 17 13:03:24 UTC 2019] Using config home:/acme.sh
#5 0.465 https://github.com/Neilpang/acme.sh
#5 0.465 v2.8.2
#5 0.465 [Mon Jun 17 13:03:24 UTC 2019] LE_WORKING_DIR='/root/.acme.sh'
#5 0.466 [Mon Jun 17 13:03:24 UTC 2019] Using config home:/acme.sh
#5 0.467 [Mon Jun 17 13:03:24 UTC 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
#5 0.470 [Mon Jun 17 13:03:24 UTC 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
#5 0.472 [Mon Jun 17 13:03:24 UTC 2019] Account key is not found at: /acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
------
executor failed running [/bin/sh -c acme.sh --update-account --accountemail "it.operations@REDACTED" --debug 2]: exit code: 1

**Comment by Neilpang** [comment]
Is the config home correct ?

>>[Mon Jun 17 13:03:24 UTC 2019] Using config home:/acme.sh

**Comment by FernandoMiguel** [comment]
@Neilpang it's a blank docker
so yeah , i store the config there

**Comment by Neilpang** [comment]
I don't think it's a bug.   
the user should call `--register-account` first.

what do you think ?

**Comment by FernandoMiguel** [comment]
if that works better, great.
have had this on my notes and docker for a year, and was the 1st time it failed.
Apparently the CA key is no longer there and only made available after issuing .
i'll test register

**Comment by FernandoMiguel** [comment]
@Neilpang this is acme.sh docker
i'm just issuesing new certs

**Comment by FernandoMiguel** [comment]
even on an AWS EC2, that never had acme.sh, 
i installed via curl, and the CA wasnt there

**Comment by Neilpang** [comment]
can this issue be closed ?
