### ISSUE TITLE
dns由阿里云转向cloudflare了但每天还是收到阿里云_acme-challenge已删除的邮件

### ISSUE THREAD

**Issue by xiebruce** [Neilpang/acme.sh#2345]
acme.sh获取证书后，向crontab添加了以下定时任务，就是每天0点9分运行一次更新呗？
```
9 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
```

但我很好奇定时任务里的这个命令并没有指定dns_api用哪个，那就是用之前获取域名时的那个了呗？请问大佬这个值是往哪存了？account.conf？看起来也不像啊，只是存个账号而已。

因为我现在每天晚上收到阿里云的这个邮件：
![image](https://user-images.githubusercontent.com/13575500/59677789-43b1f400-91fd-11e9-9a9e-4e127ab31156.png)
这是不是代表我的acme.sh还是有请求阿里云？不然我为什么会收到这邮件呢？我要怎么删除它请求阿里云续期？因为我现在是用的cloudflare呀。

**Comment by Neilpang** [comment]
```sh
acme.sh --remove  -d exmaple.com
```
