### ISSUE TITLE
提交证书申请时一直报SignatureDoesNotMatch，确认Aliyun API key无误

### ISSUE THREAD

**Issue by hyzsfl** [Neilpang/acme.sh#2349]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

![image](https://user-images.githubusercontent.com/4577825/59804204-34779700-9320-11e9-8446-a667c4c37346.png)

**Comment by Neilpang** [comment]
在路由器上 ?  路由器上有bug
请使用 其他 api 吧

或者请安装下列命令之一:  `od`, `hexdump` 或者 `xxd`

如果你不知道我在说什么,  请直接使用 dnspod api 吧.

**Comment by hyzsfl** [comment]
好的，谢谢，那我去用dnspod api吧
