### ISSUE TITLE
Apache 2.x: how to skip writing over httpd.conf

### ISSUE THREAD

**Issue by gaia** [Neilpang/acme.sh#235]
I would like to just have acme.sh issue/renew certs but I don't want it to change httpd.conf. Is this possible? I'd rather do this manually*.

Additionally (this might be in a FAQ, apologies in advance if I didn't look carefully enough), can I customize the path and filenames the cert/key/ca are created under (so they go directly into the proper dir with the proper names).

*unlikely I will need to since all the vhosts that need SSL are already using SSL, though not letsencrypt, hence the need to issue - it seems that I cannot renew a letsencrypt cert unless it has been issued by acme.sh.

**Comment by Neilpang** [comment]
Hi @gaia 

1.  Yes, we never really change the httpd.conf.  After issuing the cert, the httpd.conf will be restored as before.  There is not a single byte changed in any of your conf file.

2.  After you issue the cert, please use `--installcert` command to copy the cert to your real cert file.
https://github.com/Neilpang/acme.sh#install-issued-cert-to-apachenginx-etc

**Comment by gaia** [comment]
Thanks Neil. My server uses ssl.ca, ssl.cer and ssl.key. Can I customize the filenames too?

**Comment by Neilpang** [comment]
please use `--installcert` command to copy the cert to your real cert file.
https://github.com/Neilpang/acme.sh#install-issued-cert-to-apachenginx-etc

You can specify any file name to copy to.

Also we have a `--reloadcmd`, which will be called after the cert is issued/renewed.

You may write a `myreload.sh` script, and do anything you like in it.

```
acme.sh --issue  ..........    --reloadcmd  "/home/myreload.sh"
```
In the `myreload.sh`, you can do copy/rename/reload ...etc , anything you like.

**Comment by gaia** [comment]
Thnak you, Neil!
