### ISSUE TITLE
dns dns_dp Error add txt for domain

### ISSUE THREAD

**Issue by cditqq** [Neilpang/acme.sh#2355]
使用  --dns dns_dp 进行泛域名 *.xxxx.com 解析时，失败。
错误信息如下：
Error add txt for domain:_acme-challenge.xxxx.com

接口返回错误为：
 response='{"status":{"code":"10002","message":"The login token ID is invalid","created_at":"2019-06-25 18:13:13"}}'

**Comment by Neilpang** [comment]
The login token ID is invalid

**Comment by cditqq** [comment]
> The login token ID is invalid

Sorry， the error message is copied incorrectly。 The correct content is as follows。

response='{"status":{"code":"26","message":"Record line invalid","created_at":"2019-06-26 08:51:03"}}'

Thank you for your reply.
