### ISSUE TITLE
Get to authz error

### ISSUE THREAD

**Issue by Zewwy** [Neilpang/acme.sh#2356]
Copy of issue #1365

You get the following error in the following situations:

Steps to reproduce
------------------

Create any CSR with a wildcard * or any capitol letter in the Common name/SAN.
Then attempt to issue/renew, watch log file with "tail -f /var/log/acme.sh.log"

I'm not proving an logs, as the steps to reproduce are insanely easy.

Work Around
-----------------

Don't use wildcards as SNI is supported with HAProxy Plugin.
ensure to use all lowercase letters in Common name and SAN.

I feel this issue is due to linux being case sensitive more than anything, but that simply a hunch.

**Comment by Neilpang** [comment]
I tried for my domain, it works well.
please paste your log with `--debug 2`,  so that we can help you.

Thanks.

**Comment by Zewwy** [comment]
It works for you with capitols letters in your Common and and SAN?

seriously, if I have to reproduce this error at home cause I can't share my corporate info, I'm gonna be rather annoyed. but whatever it takes man.

**Comment by Zewwy** [comment]
Well it appears to have worked in my tests at home...

well there goes this ticket... I'm not sure why I was getting it when I did the same ting at work, and the only difference between my attempts was a uppercase, both times.. so weird.

**Comment by eric-xgu** [comment]
l have the same question，which is log
[Tue Jul 23 16:33:13 CST 2019] get to authz error.
[Tue Jul 23 16:33:13 CST 2019] _authorizations_map='hnwmall.com,{"identifier":{"type":"dns","value":"hnwmall.com"},"status":"pending","expires":"2019-07-30T07:47:56Z","challenges":[{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/yqdx93qrpEGejrTX_JhIIv8Pvjyw4VXhUutHf3WH2w0/18623237082","token":"jEwpKOPTVzcYdAl51MToHyX9OUx-gLALQJanifLPtiQ"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/yqdx93qrpEGejrTX_JhIIv8Pvjyw4VXhUutHf3WH2w0/18623237083","token":"WViKav8HF6obcDQSKqoa7QUOgvC40RrScqWCKJnPUxE"},{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/yqdx93qrpEGejrTX_JhIIv8Pvjyw4VXhUutHf3WH2w0/18623237084","token":"QeuJCsmxSgcnpT6EW8QRuQndqzrpfv0vi2pt3aw_dQg"}]}
*.hnwmall.com,{"identifier":{"type":"dns","value":"hnwmall.com"},"status":"pending","expires":"2019-07-30T07:47:56Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/WQIGrTQJZwpVkdFPUqjsXq7xnR-yvzMHTssiOk7HWRw/18623237081","token":"RZS30jMvIi6aUs0Qty9S17ETHKfsLQbNro_13ST55Ug"}],"wildcard": true}
*.api.hnwmall.com,{"identifier":{"type":"dns","value":"api.hnwmall.com"},"status":"pending","expires":"2019-07-30T07:47:56Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/bMmS9atxXP-UIN87R24w9IVgPnji7WwhP1MRjMKKmJ4/18623237080","token":"BIDKVX0VnhN2VqqVqEaLs76xbg40FRvOqxXt40RfxhQ"}],"wildcard": true}
'
[Tue Jul 23 16:33:13 CST 2019] Please add '--debug' or '--log' to check more details.
[Tue Jul 23 16:33:13 CST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by Zewwy** [comment]
Create a new issue, this ones been closed. I thought i was having an issue related to a Captol being used in the Common name or SAN of the cert request, which was not proven after further testing. Check any firewalls you may have between the internet and your OPNsense server/ACME script if present.

________________________________

**Comment by JimPyeCSS** [comment]
I think Case Sensitivity does come into the picture somewhere.  I have just started to see an issue where the command line used to generate the cert is using upper case characters.  I was failing when it tries to parse the authorizations_map to extract the domains and there parameters.

If I change the line (approx 7038 in v 2.8.4) from:
        response="$(echo "$_authorizations_map" | grep "^$(_idn "$d")," | sed "s/$d,//")"
to
        response="$(echo "$_authorizations_map" | grep -i "^$(_idn "$d")," | sed "s/$d,//i")"

Making the grep command and the sed command case insensitive and it now works.
However, in my case it gets to the point after the pause to allow DNS changes to be committed (dns_azure being used) and the script then wanting, to for some reason, purge Cloudflare DNS which we do not allow access to.  See my Ticket #2517 which seems to work when not running in interactive shell, but works when run via cron ???
