### ISSUE TITLE
add the -- OCSP option, ssllabs prompts "Supported, OCSP response not stapled"

### ISSUE THREAD

**Issue by mpv945** [Neilpang/acme.sh#2357]
Execute "acme.sh -- issue-d example.com-d*.example.com -- DNS dns_cf -- dnssleep 30 -- ocsp"

Firefox browser is not accessible, prompting "MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING"

No problem with other mainstream browsers!

How to set up certificates for adding - OCSP?

**Comment by andreasschulze** [comment]
--ocsp let a certificate have a property:
"if a TLS client connect to a TLS server pesenting this certificate, the TLS client must expect the server also deliver uptodate OCSP data as part of the TLS handshake"

Mozilla browser as TLS client behave that way. So you must configure you TLS server to satisfy that requirement, you must setup OCSP stapling.

**Comment by pille** [comment]
@mpv945, you need to fetch your OCSP proof and bundle it with your certificate regularly (more often than you renew the cert. currently only mozilla seems to be strict about it being missing/expired.

**Comment by Neilpang** [comment]
you must configure your server to fetch ocsp proof and send it back to the client.
