### ISSUE TITLE
The domain '*.betestar888.com' is not a cert name

### ISSUE THREAD

**Issue by maxadd** [Neilpang/acme.sh#2363]
不支持泛域名证书么？或许不应该这么写？

```sh
[root@nginx www]# acme.sh -v
https://github.com/Neilpang/acme.sh
v2.8.2

[root@nginx www]# acme.sh --issue --dns dns_gd -d '*.betestar888.com' --installcert --key-file /etc/nginx/cret/betestar888.com.key --fullchain-file /etc/nginx/cret/betestar888.com.crt --reloadcmd "nginx -s reload" --debug 2
[Sat Jun 29 03:39:00 UTC 2019] Lets find script dir.
[Sat Jun 29 03:39:00 UTC 2019] _SCRIPT_='/root/.acme.sh/acme.sh'
[Sat Jun 29 03:39:00 UTC 2019] _script='/root/.acme.sh/acme.sh'
[Sat Jun 29 03:39:00 UTC 2019] _script_home='/root/.acme.sh'
[Sat Jun 29 03:39:00 UTC 2019] Using config home:/root/.acme.sh
[Sat Jun 29 03:39:00 UTC 2019] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.2
[Sat Jun 29 03:39:00 UTC 2019] Using config home:/root/.acme.sh
[Sat Jun 29 03:39:00 UTC 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sat Jun 29 03:39:00 UTC 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Sat Jun 29 03:39:00 UTC 2019] DOMAIN_PATH='/root/.acme.sh/*.betestar888.com'
[Sat Jun 29 03:39:00 UTC 2019] The domain '*.betestar888.com' is not a cert name. You must use the cert name to specify the cert to install.
[Sat Jun 29 03:39:00 UTC 2019] Can not find path:'/root/.acme.sh/*.betestar888.com'
```

**Comment by Rikairchy** [comment]
you will need to issue a cert for the base domain as well as the wildcard. Try 

`acme.sh --issue --dns dns_gd -d betestar888.com --dns dns_gd *.betestar888.com --installcert --key-file /etc/nginx/cret/betestar888.com.key --fullchain-file /etc/nginx/cret/betestar888.com.crt --reloadcmd "nginx -s reload" --debug 2`

Also, the install command has a directory called `cret` - is that the name of the directory or a mistype?

**Comment by maxadd** [comment]
Yes, sorry, it should be `cert`.

However, I use the command you gave to output the following error. This is somewhat difficult to understand. Is it that the operation is not completed after I complete the installation?

```sh
[root@nginx ~]# acme.sh --issue --dns dns_gd -d betestar888.com --dns dns_gd -d *.betestar888.com --installcert --key-file /etc/nginx/cert/betestar888.com.key --fullchain-file /etc/nginx/cert/betestar888.com.crt --reloadcmd "nginx -s reload" --debug 2
[Mon Jul  1 03:14:02 UTC 2019] Lets find script dir.
[Mon Jul  1 03:14:02 UTC 2019] _SCRIPT_='/root/.acme.sh/acme.sh'
[Mon Jul  1 03:14:02 UTC 2019] _script='/root/.acme.sh/acme.sh'
[Mon Jul  1 03:14:02 UTC 2019] _script_home='/root/.acme.sh'
[Mon Jul  1 03:14:02 UTC 2019] Using config home:/root/.acme.sh
[Mon Jul  1 03:14:02 UTC 2019] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.2
[Mon Jul  1 03:14:02 UTC 2019] Using config home:/root/.acme.sh
[Mon Jul  1 03:14:02 UTC 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  1 03:14:02 UTC 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mon Jul  1 03:14:02 UTC 2019] DOMAIN_PATH='/root/.acme.sh/betestar888.com'
[Mon Jul  1 03:14:02 UTC 2019] The domain 'betestar888.com' is not a cert name. You must use the cert name to specify the cert to install.
[Mon Jul  1 03:14:02 UTC 2019] Can not find path:'/root/.acme.sh/betestar888.com'
```

**Comment by Rikairchy** [comment]
Can you do an `ls /root/.acme.sh/` for me?

**Comment by maxadd** [comment]
```sh
[root@nginx ~]# ll -A /root/.acme.sh/
total 208
-rw-r--r--. 1 root root     96 Jul  1 02:06 account.conf
-rwxr-xr-x. 1 root root 189233 Jul  1 02:06 acme.sh
-rw-r--r--. 1 root root     78 Jul  1 02:06 acme.sh.csh
-rw-r--r--. 1 root root     78 Jul  1 02:06 acme.sh.env
drwxr-xr-x. 2 root root   4096 Jul  1 02:06 deploy
drwxr-xr-x. 2 root root   4096 Jul  1 02:06 dnsapi
drwxr-xr-x. 2 root root    122 Jul  1 02:06 notify
```

**Comment by Rikairchy** [comment]
Is the output in https://github.com/Neilpang/acme.sh/issues/2363#issuecomment-507102522 the full output? If not, can you provide it? I do not believe the cert was issued

**Comment by maxadd** [comment]
yes, it is full

**Comment by Rikairchy** [comment]
Can you create the `/root/.acme.sh/betestar888.com` directory manually, and
then issue the cert?

**Comment by maxadd** [comment]
...

```sh
[root@nginx ~]# mkdir /root/.acme.sh/betestar888.com
[root@nginx ~]# acme.sh --issue --dns dns_gd -d betestar888.com --dns dns_gd -d *.betestar888.com --installcert --key-file /etc/nginx/cert/betestar888.com.key --fullchain-file /etc/nginx/cert/betestar888.com.crt --reloadcmd "nginx -s reload" --debug 2
[Mon Jul  1 04:40:01 UTC 2019] Lets find script dir.
[Mon Jul  1 04:40:01 UTC 2019] _SCRIPT_='/root/.acme.sh/acme.sh'
[Mon Jul  1 04:40:01 UTC 2019] _script='/root/.acme.sh/acme.sh'
[Mon Jul  1 04:40:01 UTC 2019] _script_home='/root/.acme.sh'
[Mon Jul  1 04:40:01 UTC 2019] Using config home:/root/.acme.sh
[Mon Jul  1 04:40:01 UTC 2019] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.2
[Mon Jul  1 04:40:01 UTC 2019] Using config home:/root/.acme.sh
[Mon Jul  1 04:40:01 UTC 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jul  1 04:40:01 UTC 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mon Jul  1 04:40:01 UTC 2019] DOMAIN_PATH='/root/.acme.sh/betestar888.com'
[Mon Jul  1 04:40:01 UTC 2019] Installing key to:/etc/nginx/cert/betestar888.com.key
cat: /root/.acme.sh/betestar888.com/betestar888.com.key: No such file or directory
```

**Comment by Neilpang** [comment]
`--issue`  和 `--install-cert` 是两个独立的命令, 不能混用.

仔细阅读说明:

https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E

**Comment by nicbou** [comment]
@Neilpang, what is the solution to your problem? You closed the ticket without much information. It's not helpful for people with the same problem.

**Comment by matsuro-hadouken** [comment]
@nicbou When you receive certificat, message will report something like this:

`Your cert is in: /eth/some/path/acme.sh/certificates` and this is where received certificates stored.

For absolutely unknown reason, cert installer looking for certs at `$HOME/.acme.sh/domain_name` and this is why we are getting this error.

I'm not sure if this related to ZeroSSL default _( again )_ or maybe new version of the script.

I also noticed, actual cert folder previously `domain.name` _( Let's Encrypt )_ and now by using ZeroSSL _( or maybe related to new script version )_ folder name is `domein.name_ecc`.

However, to fix this issue need to add path flag and provide absolute path to certificates folder like this:
```bash
acme.sh --install-cert -d <domain.name> --cert-home </whatever/path/to/acme.sh/certificates> \
...
```

**Comment by nicbou** [comment]
I found the solution, but it's very specific to my setup. I'll post the fix in case it might help.

I run acme.sh inside docker. The SSL certificates are saved in a docker volume. However, the files acme.sh generates under `/root/.acme.sh` were destroyed when I rebuilt the docker image. The solution was to create a volume for /root/acme.sh.

```yaml
volumes:
      - "ssl_certs:/etc/ssl-certs"
      - "acme_sh:/root/.acme.sh"
      # ...
```

**Comment by ugate** [comment]
@matsuro-hadouken you are right.

Even if `acme.sh` generates new certs in `.acme.sh/example.com_ecc`, the installation will try to use an old `.acme.sh/example.com` instead.

The only way I found to circumvent this issue is to `mkdir .acme.sh/example.com_old && mv .acme.sh/example.com .acme.sh/example.com_old`. Then reissue the installation. This seems to forces `.acme.sh` to use the correct ECC directory.
