### ISSUE TITLE
dnsapi: namecheap : Error while parsing sessionid on BSD

### ISSUE THREAD

**Issue by Piping** [Neilpang/acme.sh#2371]
Steps to reproduce
------------------
Same output as https://github.com/Neilpang/acme.sh/issues/2279#issuecomment-494835929 mentioned.

But it is for namecheap.sh

Debug log
-----------------

```
[Tue Jul 2 01:06:36 UTC 2019] Found domain api file: /usr/local/pkg/acme/dnsapi/dns_namecheap.sh
sed: 1: "s/.*\((http|https)://.* ...": RE error: parentheses not balanced
[Tue Jul 2 01:06:38 UTC 2019] error API Key is invalid or API access has not been enabled
```

**Comment by Neilpang** [comment]
so, why not paste your log with `--debug 2` ?

**Comment by Piping** [comment]
@Neilpang Hi, The package is bundled with `pfSense` Firewall as `acme` package. It is kind of difficult to issue the debug or test command.

The output is from the web GUI of pfSense.

**Comment by honzahommer** [comment]
@Neilpang https://github.com/opnsense/plugins/pull/1350

**Comment by Piping** [comment]
@honzahommer Thanks! The fix works well.
update script line 167 as `addr=$(echo "$NAMECHEAP_SOURCEIP" | _egrep_o '(http|https):\/\/.*')` for future pfsense users.
