### ISSUE TITLE
Support xinnet domain api?

### ISSUE THREAD

**Issue by ajeecai** [Neilpang/acme.sh#2372]
Hi, thanks for your great work. Is there any plan for supporting http://www.xinnet.com/ ? 
I have searched the issues and wiki and found it is not there.

Thanks

**Comment by Neilpang** [comment]
下次报需求之前, 麻烦把 api 文档找出来,  节约我的时间.

刚看了一下, 貌似只有 代理上可以访问 api

**Comment by ajeecai** [comment]
FYI, 
http://agent.xinnet.com/Modules/downloads/api/xinnet-domain-api.pdf
