### ISSUE TITLE
Change Settings

### ISSUE THREAD

**Issue by Nosxxx** [Neilpang/acme.sh#238]
Is there an way to change the settings for CloudFlare DNS via command?

**Comment by Neilpang** [comment]
If you want to control all the settings vi commandline, you should try this:
https://github.com/AnalogJ/lexicon

**Comment by Nosxxx** [comment]
I mean, i would like to change the CF_Key and CF_Email of your script. Is there a way to do that via commandline?

**Comment by Neilpang** [comment]
@Nosxxx 

There are 2 options,  you can use eithet one of them:

1. Edit the config file:  `~/.acme.sh/account.conf`

2. Every time you use a new cf_key/cf_email,   the new value will replace the old ones automatically.
For example:
```
export CF_Key="this is my new cf key"

export CF_Email="this is my new cf email@xxx.com"

acme.sh --issue ........    --dns  dns_cf
```
