### ISSUE TITLE
是否有支持京东云DNS API的计划？

### ISSUE THREAD

**Issue by realpg** [Neilpang/acme.sh#2380]
CLOUDXNS即将于7.16停止全部免费用户

现在国内大型DNS服务中，仅有CloudXNS、阿里云和京东云支持CAA记录

其中CloudXNS将于2019.7.16停止全部非VIP用户使用

阿里云只有针对每个域名付费才可以使用CAA记录

对非付费用户支持CAA记录的仅剩京东云一家了

想要CAA记录，就没法直接用acme.sh

所以希望能增加jdcloud dns支持

PS 之所以提feature request 的issue，实在是对自己写出可靠的shell脚本不具备信心。如果本项目是采用常见语言开发的，早就拎键盘自己干了。无奈做回伸手党。感觉API跟阿里云的类似

参考资料
京东云OPENAPI DNS解析部分

https://docs.jdcloud.com/cn/jd-cloud-dns/api/introduction

https://docs.jdcloud.com/cn/jd-cloud-dns/api/overview

**Comment by Neilpang** [comment]
这个免费用户可以直接使用吗?
1. 实名认证?
2. 外部域名可以使用, 还是必须在jd 注册 ?
3. 免费?  还是需要在jd 购买别的服务 ?
4. 如果作为一个从没使用过 jd 的用户, 我的成本是什么?

看起来不难, 我主要关心的是开发和使用的 综合成本问题.

谢谢.

**Comment by realpg** [comment]
您好，感谢关注

我正在洲际航班上使用手机回复，可能排版包括语序组织都不太好，敬请见谅，因为手机没法方便的随心所欲复制粘贴进行后期排版，想到啥包括之前我二次开发过遇到的坑都说一下

1. 目前完全免费，不要求使用他的云服务，也不要求他那里注册的域名。国内厂商不好预期未来，暂时是这样的

2. 本人是京东老用户，京东用户已经实名，直接用京东账户登录就能用，不了解其他用户是否要求实名才能用，没有测试条件，请其他朋友补充

3. 遇到的坑之一：京东账户首次登录，拉取的账户手机号是10年前我首次在京东输入手机号时候的号码。(我的京东号比较早注册了快15年了)，现在京东实名绑定，账号安全手机，直接登录手机，银行卡绑定的都不是这个十年前的号码，不知道他京东云这边是从哪里读出来的这个数据

4. API开发遇到的坑，经常有比如要涉及的域名API是云服务地域无关的，也要求你带上地域，这时候最好带北方北京就是默认那个，带其他的可能有莫名其妙问题，而且要记住这个点，啊不一定哪天他们研发发现这个是多余的就删了改API不通知(有过先例)

5. CAA记录，TXT记录曾经双引号的处理有些问题不知道修复没有

**Comment by Neilpang** [comment]
好的,  我这两天就看看.

**Comment by Neilpang** [comment]
这东西的 签名算法基本上是照 aws 搬过来的.  复杂的要死.

还在调试.

**Comment by realpg** [comment]
辛苦。主要是这个项目完全用的shell脚本写的，实在爱莫能助，个人懂shell脚本，能读明白，能写超级简单的，复杂的就完蛋了，也没有写出复杂shell脚本的先例

要是运维常用的golang python 甚至perl 拎键盘就干了

**Comment by Neilpang** [comment]
@realpg  已经再 dev branch 了.
有时间试一下.  这里是用法:
https://github.com/Neilpang/acme.sh/wiki/dnsapi#83-use-jdcloudcom-dns-api-to-automatically-issue-cert

**Comment by realpg** [comment]
@Neilpang 
既然没法做开发，测试这种蓝领工作我们帮忙干。马上开工

**Comment by realpg** [comment]
@Neilpang

已经进行初步测试，各种能想到的场景工作正常

----

提一个不算是问题的点，就算是建议吧

添加的acme txt记录的TTL是120秒，我没查看是代码写死的还是不指定京东云默认给了120秒

如果是手动指定的，建议TTL再长一点。目前看到的京东云解析的免费限制就有TTL限制，但是我没仔细测，1分钟的TTL不让免费用户使用，那是没测出来允许免费用户使用的最小TTL是多少

因为国内云厂商的节操，不排除以后更严格限制免费用户的最小TTL值的可能性，那样以后又会某天大家提issue，然后再改长。现在京东云默认建议TTL是10分钟（600秒）

我实际参与过DNS类项目，一般来说，TTL设置的小于5分钟（300秒），对于普通小规模非死站的网站，就会对DNS造成略大的压力了，感觉做成300能规避一些未来可能存在的风险

**Comment by Neilpang** [comment]
因为我测出来最小是 120,  所以就用了.
已经改成 300了.

已经 merge 到 master了.
