### ISSUE TITLE
www.dns.com的没有吗? 求添加

### ISSUE THREAD

**Issue by 201821134066** [Neilpang/acme.sh#2387]
www.dns.com的没有吗? 求添加

**Comment by Neilpang** [comment]
这家 文档不好读.  又没有sdk

你有例子吗

**Comment by 201821134066** [comment]
> 这家文档不好读。又没有SDK
> 
> 你有例子吗

https://www.dns.com/supports/601.html 这个是API接口使用说明

**Comment by Neilpang** [comment]
这个地址没有有用信息, 里面的 demo 都打不开.

**Comment by 201821134066** [comment]
> 这个地址没有有用信息, 里面的 demo 都打不开.

好吧, 谢谢回复. 还是老是用cf 😄
