### ISSUE TITLE
Nginx not restarting after certificate renewal

### ISSUE THREAD

**Issue by kafan1986** [Neilpang/acme.sh#2394]
I am using the below command for certification renewal and nginx restart post certification renewal. But it did not work.

`acme.sh --install-cert -d xyz.com --key-file /home/ubuntu/nginxssl/xyz_key.pem --fullchain-file /home/ubuntu/nginxssl/xyz_cert.pem --reloadcmd "service nginx force-reload"`

When I run **service nginx force-reload**  command then it asks me password but in the above setup command I can not see any password parameter.

I can also restart nginx normally through **sudo systemctl restart nginx**

Upon manually restarting nginx the site worked fine. What am I missing?

**Comment by Neilpang** [comment]
restart/reload nginx without sudo:

https://stackoverflow.com/questions/3011067/restart-nginx-without-sudo
