### ISSUE TITLE
Use setcap instead of root

### ISSUE THREAD

**Issue by avierr** [Neilpang/acme.sh#2396]
At the moment, you need root access if you aren't using DNS method
The certs generated under root aren't readable by other non-root programs.

You need to do some manual stuff of copying over the certs and applying right permissions and becomes even more complex with auto-renew. (any right methods to solve this will also be appreciated)

The setcap method used here is a much more nicer alternative https://go-acme.github.io/lego/usage/cli/

and probably we should use it?

**Comment by Neilpang** [comment]
>> The certs generated under root aren't readable by other non-root programs.

Not really.

We have 2 ways to copy the cert/key files out of root home folder:
1.  Using `--key-file/--cert-file/--reload-cmd` approach
2.  Using `--deploy`  hooks.

In either of the ways, we will copy the files to the target positions when renewal,   AND, the file permissions will not be changed in renewal.  Only the file content is replaced.

`setcap` is not portable for all the platforms we supported, such as:  BSD, Solaris, and Windows/Cygwin.

We don't want to make things complicated.

**Comment by neilpang** [comment]
please add a new wiki page, I can link it in the readme.
