### ISSUE TITLE
是否能支持华为云的api

### ISSUE THREAD

**Issue by SoyMeng** [Neilpang/acme.sh#2402]
接口文档：
https://support.huaweicloud.com/api-dns/zh-cn_topic_0132421999.html

**Comment by Neilpang** [comment]
麻烦多一些信息. 
1. 这个服务是免费的吗?
2. 必须使用 华为购买的域名吗?
3. 在第三方买的域名可以用吗 ?
4. 需要实名认证吗, 需要手持吗?
5. 我从没用过 华为云的 服务, 对于我来说, 使用的成本是什么, 包括时间成本, 和金钱.

我没多少时间研究,  希望能多一些信息节约我的时间.
谢谢

**Comment by SoyMeng** [comment]
@Neilpang 

1. 服务是免费的
2. 看资料应该是不需要的，不过我没有进行过确认
3. 域名应该是可以使用第三方的，参考资料https://support.huaweicloud.com/qs-dns/zh-cn_topic_0035467699.html
4. 需要实名认证，有三种方式，银行卡，手机，上传身份证照片（这个方式是需要手持的）
5. 使用上应该基本与阿里云类似

**Comment by unmec** [comment]
刚刚将一个域名迁移至华为云，可以补充以下信息：

1. 服务是免费的
2. 不一定需要在华为云购买域名
3. 在第三方购买的域名可以使用
4. 需要实名认证，个人实名认证需要手持证件照
5. 如果需要此项目添加对其支持，主要是参与者的时间成本

**Comment by Neilpang** [comment]
谢谢各位.

本人抵制手持, 所以不打算支持.

建议用 dns alias 模式替换.
https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode

如果确实想用华为,  你可以设置好账号和域名, 然后给付费做开发.
