### ISSUE TITLE
A problem with non-root users.

### ISSUE THREAD

**Issue by siaimes** [Neilpang/acme.sh#2406]
If my nginx and acme.sh are configured with different non-root users, such as nginx and acme. Then how to ensure that the user nginx can access the certificate generated by the user acme, and the user acme can also correctly update the certificate without encountering the permission problem. Can you give me a more specific solution? Thank you.

**Comment by Neilpang** [comment]
use `--install-cert`  to copy the cert/key to a specified location.

Then use `chmod` to add read permissions on the cert/key  files to the nginx user.

Done.

Next time when the cert is renewed,  the file content will be updated, but  the files permissions will be kept.

**Comment by siaimes** [comment]
Thank you!
