### ISSUE TITLE
Possible to timeout the script retries, if failing to add records

### ISSUE THREAD

**Issue by JeffCleverley** [Neilpang/acme.sh#2408]
Dns api method just keeps trying, under certain circumstances and hanging a parent script. When api key is okay, but error at provider. It just loops trying to add records. 

Is there a way to set a timeout?

**Comment by Neilpang** [comment]
show me the output with `--debug 2`

We have 20 minutes timeout.

**Comment by JeffCleverley** [comment]
Ahhh the twenty minutes would seem like an in infinite loop within our scripts.

Is there anyway to reduce or manage that timeout?

**Comment by Neilpang** [comment]
```
--dnssleep  200
```
