### ISSUE TITLE
 Error renew ssl Invalid response from “domain"更新ssl失败，提示无效响应

### ISSUE THREAD

**Issue by zzhjiyin** [Neilpang/acme.sh#2412]
Steps to reproduce
------------------
Due to the vps shut down last month, I missed the acme.sh auto ssl renewal  .Now I wanna manually update the ssl cert.I trid as below so many times. It always told me invalid response.
how can I figure out this problem.I appreaciate your help.
你好，打扰了。我想向你请教一个问题。由于我之前的vps关闭了导致acme.sh的自动续期无法正常进行，现在证书过期了，我想手动更新它，但是他提示了以下的错误，我已经更新到最新的版本了，并且也试过了`acme.sh --cron --debug`
OS：centos6.9 
Debug log
-----------------
[root@69 ~]# acme.sh --cron --debug
[Tue Jul 30 19:14:51 CST 2019] Lets find script dir.
[Tue Jul 30 19:14:51 CST 2019] _SCRIPT_='/usr/local/acme.sh/acme.sh'
[Tue Jul 30 19:14:51 CST 2019] _script='/usr/local/acme.sh/acme.sh'
[Tue Jul 30 19:14:51 CST 2019] _script_home='/usr/local/acme.sh'
[Tue Jul 30 19:14:51 CST 2019] Using config home:/usr/local/acme.sh
https://github.com/Neilpang/acme.sh
v2.8.1
[Tue Jul 30 19:14:51 CST 2019] Using config home:/usr/local/acme.sh
[Tue Jul 30 19:14:51 CST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jul 30 19:14:51 CST 2019] ===Starting cron===
[Tue Jul 30 19:14:51 CST 2019] Using config home:/usr/local/acme.sh
[Tue Jul 30 19:14:51 CST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jul 30 19:14:51 CST 2019] _stopRenewOnError
[Tue Jul 30 19:14:51 CST 2019] di='/usr/local/nginx/conf/ssl/zzhjiyin.tk/'
[Tue Jul 30 19:14:51 CST 2019] d='zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] Using config home:/usr/local/acme.sh
[Tue Jul 30 19:14:51 CST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jul 30 19:14:51 CST 2019] DOMAIN_PATH='/usr/local/nginx/conf/ssl/zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] Renew: 'zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] Le_API
[Tue Jul 30 19:14:51 CST 2019] _main_domain='zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] _alt_domains='www.zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Tue Jul 30 19:14:51 CST 2019] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Tue Jul 30 19:14:51 CST 2019] GET
[Tue Jul 30 19:14:51 CST 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jul 30 19:14:51 CST 2019] timeout=
[Tue Jul 30 19:14:51 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:14:51 CST 2019] ret='0'
[Tue Jul 30 19:14:51 CST 2019] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Tue Jul 30 19:14:51 CST 2019] ACME_NEW_AUTHZ
[Tue Jul 30 19:14:51 CST 2019] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Jul 30 19:14:51 CST 2019] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Tue Jul 30 19:14:51 CST 2019] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Tue Jul 30 19:14:51 CST 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Tue Jul 30 19:14:51 CST 2019] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Jul 30 19:14:51 CST 2019] ACME_VERSION='2'
[Tue Jul 30 19:14:51 CST 2019] Le_NextRenewTime='1561552592'
[Tue Jul 30 19:14:51 CST 2019] _on_before_issue
[Tue Jul 30 19:14:51 CST 2019] _chk_main_domain='zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] _chk_alt_domains='www.zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] Le_LocalAddress
[Tue Jul 30 19:14:51 CST 2019] d='zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] Check for domain='zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] _currentRoot='/home/wwwroot/zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] d='www.zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] Check for domain='www.zzhjiyin.tk'
[Tue Jul 30 19:14:51 CST 2019] _currentRoot='/home/wwwroot/zzhjiyin.tk'
[Tue Jul 30 19:14:52 CST 2019] d
[Tue Jul 30 19:14:52 CST 2019] _saved_account_key_hash is not changed, skip register account.
[Tue Jul 30 19:14:52 CST 2019] Read key length:
[Tue Jul 30 19:14:52 CST 2019] _createcsr
[Tue Jul 30 19:14:52 CST 2019] Multi domain='DNS:zzhjiyin.tk,DNS:www.zzhjiyin.tk'
[Tue Jul 30 19:14:52 CST 2019] Getting domain auth token for each domain
[Tue Jul 30 19:14:52 CST 2019] d='www.zzhjiyin.tk'
[Tue Jul 30 19:14:52 CST 2019] d
[Tue Jul 30 19:14:52 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Jul 30 19:14:52 CST 2019] payload='{"identifiers": [{"type":"dns","value":"zzhjiyin.tk"},{"type":"dns","value":"www.zzhjiyin.tk"}]}'
[Tue Jul 30 19:14:52 CST 2019] RSA key
[Tue Jul 30 19:14:52 CST 2019] HEAD
[Tue Jul 30 19:14:52 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Jul 30 19:14:52 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:14:52 CST 2019] _ret='0'
[Tue Jul 30 19:14:52 CST 2019] POST
[Tue Jul 30 19:14:52 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Jul 30 19:14:52 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:14:52 CST 2019] _ret='0'
[Tue Jul 30 19:14:52 CST 2019] code='201'
[Tue Jul 30 19:14:52 CST 2019] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/56039778/806763650'
[Tue Jul 30 19:14:52 CST 2019] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/56039778/806763650'
[Tue Jul 30 19:14:52 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/authz/p0HPof4il0ynVzBlienObmX_uKMZr8htUalUdfQcM20'
[Tue Jul 30 19:14:52 CST 2019] payload
[Tue Jul 30 19:14:52 CST 2019] POST
[Tue Jul 30 19:14:52 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz/p0HPof4il0ynVzBlienObmX_uKMZr8htUalUdfQcM20'
[Tue Jul 30 19:14:52 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:14:53 CST 2019] _ret='0'
[Tue Jul 30 19:14:53 CST 2019] code='200'
[Tue Jul 30 19:14:53 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/authz/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg'
[Tue Jul 30 19:14:53 CST 2019] payload
[Tue Jul 30 19:14:53 CST 2019] POST
[Tue Jul 30 19:14:53 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg'
[Tue Jul 30 19:14:53 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:14:53 CST 2019] _ret='0'
[Tue Jul 30 19:14:53 CST 2019] code='200'
[Tue Jul 30 19:14:53 CST 2019] d='zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] Getting webroot for domain='zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] _w='/home/wwwroot/zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] _currentRoot='/home/wwwroot/zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073","token":"y08Lv5F2_0vfNtPnu2RtRF7Ln8h0_9bpomspVnwFODc"'
[Tue Jul 30 19:14:53 CST 2019] token='y08Lv5F2_0vfNtPnu2RtRF7Ln8h0_9bpomspVnwFODc'
[Tue Jul 30 19:14:53 CST 2019] uri='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:14:53 CST 2019] keyauthorization='y08Lv5F2_0vfNtPnu2RtRF7Ln8h0_9bpomspVnwFODc.Ng1AgIV1F-2Lov7ngyY05kTyCS6PaadiSn0bbzkWjH8'
[Tue Jul 30 19:14:53 CST 2019] dvlist='zzhjiyin.tk#y08Lv5F2_0vfNtPnu2RtRF7Ln8h0_9bpomspVnwFODc.Ng1AgIV1F-2Lov7ngyY05kTyCS6PaadiSn0bbzkWjH8#https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073#http-01#/home/wwwroot/zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] d='www.zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] Getting webroot for domain='www.zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] _w='/home/wwwroot/zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] _currentRoot='/home/wwwroot/zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/p0HPof4il0ynVzBlienObmX_uKMZr8htUalUdfQcM20/18913396070","token":"5rob4Lcnfv6HInXxZ9dn4OMxc635RVlmL7XFmAfms7A"'
[Tue Jul 30 19:14:53 CST 2019] token='5rob4Lcnfv6HInXxZ9dn4OMxc635RVlmL7XFmAfms7A'
[Tue Jul 30 19:14:53 CST 2019] uri='https://acme-v02.api.letsencrypt.org/acme/challenge/p0HPof4il0ynVzBlienObmX_uKMZr8htUalUdfQcM20/18913396070'
[Tue Jul 30 19:14:53 CST 2019] keyauthorization='5rob4Lcnfv6HInXxZ9dn4OMxc635RVlmL7XFmAfms7A.Ng1AgIV1F-2Lov7ngyY05kTyCS6PaadiSn0bbzkWjH8'
[Tue Jul 30 19:14:53 CST 2019] dvlist='www.zzhjiyin.tk#5rob4Lcnfv6HInXxZ9dn4OMxc635RVlmL7XFmAfms7A.Ng1AgIV1F-2Lov7ngyY05kTyCS6PaadiSn0bbzkWjH8#https://acme-v02.api.letsencrypt.org/acme/challenge/p0HPof4il0ynVzBlienObmX_uKMZr8htUalUdfQcM20/18913396070#http-01#/home/wwwroot/zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] d
[Tue Jul 30 19:14:53 CST 2019] vlist='zzhjiyin.tk#y08Lv5F2_0vfNtPnu2RtRF7Ln8h0_9bpomspVnwFODc.Ng1AgIV1F-2Lov7ngyY05kTyCS6PaadiSn0bbzkWjH8#https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073#http-01#/home/wwwroot/zzhjiyin.tk,www.zzhjiyin.tk#5rob4Lcnfv6HInXxZ9dn4OMxc635RVlmL7XFmAfms7A.Ng1AgIV1F-2Lov7ngyY05kTyCS6PaadiSn0bbzkWjH8#https://acme-v02.api.letsencrypt.org/acme/challenge/p0HPof4il0ynVzBlienObmX_uKMZr8htUalUdfQcM20/18913396070#http-01#/home/wwwroot/zzhjiyin.tk,'
[Tue Jul 30 19:14:53 CST 2019] d='zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] d='www.zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] ok, let's start to verify
[Tue Jul 30 19:14:53 CST 2019] Verifying: zzhjiyin.tk
[Tue Jul 30 19:14:53 CST 2019] d='zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] keyauthorization='y08Lv5F2_0vfNtPnu2RtRF7Ln8h0_9bpomspVnwFODc.Ng1AgIV1F-2Lov7ngyY05kTyCS6PaadiSn0bbzkWjH8'
[Tue Jul 30 19:14:53 CST 2019] uri='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:14:53 CST 2019] _currentRoot='/home/wwwroot/zzhjiyin.tk'
[Tue Jul 30 19:14:53 CST 2019] wellknown_path='/home/wwwroot/zzhjiyin.tk/.well-known/acme-challenge'
[Tue Jul 30 19:14:53 CST 2019] writing token:y08Lv5F2_0vfNtPnu2RtRF7Ln8h0_9bpomspVnwFODc to /home/wwwroot/zzhjiyin.tk/.well-known/acme-challenge/y08Lv5F2_0vfNtPnu2RtRF7Ln8h0_9bpomspVnwFODc
[Tue Jul 30 19:14:53 CST 2019] Changing owner/group of .well-known to www:www
[Tue Jul 30 19:14:53 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:14:53 CST 2019] payload='{}'
[Tue Jul 30 19:14:53 CST 2019] POST
[Tue Jul 30 19:14:53 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:14:53 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:14:53 CST 2019] _ret='0'
[Tue Jul 30 19:14:53 CST 2019] code='200'
[Tue Jul 30 19:14:54 CST 2019] trigger validation code: 200
[Tue Jul 30 19:14:54 CST 2019] sleep 2 secs to verify
[Tue Jul 30 19:14:56 CST 2019] checking
[Tue Jul 30 19:14:56 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:14:56 CST 2019] payload
[Tue Jul 30 19:14:56 CST 2019] POST
[Tue Jul 30 19:14:56 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:14:56 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:14:56 CST 2019] _ret='0'
[Tue Jul 30 19:14:56 CST 2019] code='200'
[Tue Jul 30 19:14:56 CST 2019] Pending
[Tue Jul 30 19:14:56 CST 2019] sleep 2 secs to verify
[Tue Jul 30 19:14:58 CST 2019] checking
[Tue Jul 30 19:14:58 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:14:58 CST 2019] payload
[Tue Jul 30 19:14:58 CST 2019] POST
[Tue Jul 30 19:14:58 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:14:58 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:14:58 CST 2019] _ret='0'
[Tue Jul 30 19:14:58 CST 2019] code='200'
[Tue Jul 30 19:14:59 CST 2019] Pending
[Tue Jul 30 19:14:59 CST 2019] sleep 2 secs to verify
[Tue Jul 30 19:15:01 CST 2019] checking
[Tue Jul 30 19:15:01 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:01 CST 2019] payload
[Tue Jul 30 19:15:01 CST 2019] POST
[Tue Jul 30 19:15:01 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:01 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:15:01 CST 2019] _ret='0'
[Tue Jul 30 19:15:01 CST 2019] code='200'
[Tue Jul 30 19:15:01 CST 2019] Pending
[Tue Jul 30 19:15:01 CST 2019] sleep 2 secs to verify
[Tue Jul 30 19:15:03 CST 2019] checking
[Tue Jul 30 19:15:03 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:03 CST 2019] payload
[Tue Jul 30 19:15:03 CST 2019] POST
[Tue Jul 30 19:15:03 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:03 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:15:04 CST 2019] _ret='0'
[Tue Jul 30 19:15:04 CST 2019] code='200'
[Tue Jul 30 19:15:04 CST 2019] Pending
[Tue Jul 30 19:15:04 CST 2019] sleep 2 secs to verify
[Tue Jul 30 19:15:06 CST 2019] checking
[Tue Jul 30 19:15:06 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:06 CST 2019] payload
[Tue Jul 30 19:15:06 CST 2019] POST
[Tue Jul 30 19:15:06 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:06 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:15:06 CST 2019] _ret='0'
[Tue Jul 30 19:15:06 CST 2019] code='200'
[Tue Jul 30 19:15:06 CST 2019] Pending
[Tue Jul 30 19:15:06 CST 2019] sleep 2 secs to verify
[Tue Jul 30 19:15:08 CST 2019] checking
[Tue Jul 30 19:15:08 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:08 CST 2019] payload
[Tue Jul 30 19:15:08 CST 2019] POST
[Tue Jul 30 19:15:08 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:08 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:15:09 CST 2019] _ret='0'
[Tue Jul 30 19:15:09 CST 2019] code='200'
[Tue Jul 30 19:15:09 CST 2019] zzhjiyin.tk:Verify error:Invalid response from https://zzhjiyin.tk [69.171.72.246]: 
[Tue Jul 30 19:15:09 CST 2019] Debug: get token url.
[Tue Jul 30 19:15:09 CST 2019] GET
[Tue Jul 30 19:15:09 CST 2019] url='http://zzhjiyin.tk/.well-known/acme-challenge/y08Lv5F2_0vfNtPnu2RtRF7Ln8h0_9bpomspVnwFODc'
[Tue Jul 30 19:15:09 CST 2019] timeout=1
[Tue Jul 30 19:15:09 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g  --connect-timeout 1'
[Tue Jul 30 19:15:09 CST 2019] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60
[Tue Jul 30 19:15:09 CST 2019] ret='60'
[Tue Jul 30 19:15:09 CST 2019] Debugging, skip removing: /home/wwwroot/zzhjiyin.tk/.well-known
[Tue Jul 30 19:15:09 CST 2019] pid
[Tue Jul 30 19:15:09 CST 2019] No need to restore nginx, skip.
[Tue Jul 30 19:15:09 CST 2019] _clearupdns
[Tue Jul 30 19:15:09 CST 2019] dns_entries
[Tue Jul 30 19:15:09 CST 2019] skip dns.
[Tue Jul 30 19:15:09 CST 2019] _on_issue_err
[Tue Jul 30 19:15:09 CST 2019] Please check log file for more details: /usr/local/acme.sh/acme.sh.log
[Tue Jul 30 19:15:09 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:09 CST 2019] payload='{}'
[Tue Jul 30 19:15:09 CST 2019] POST
[Tue Jul 30 19:15:09 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/rqa0hYGSq9n8hflOZyljUA2loBWozSvQaG_xkD2yttg/18913396073'
[Tue Jul 30 19:15:09 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:15:09 CST 2019] _ret='0'
[Tue Jul 30 19:15:09 CST 2019] code='400'
[Tue Jul 30 19:15:09 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/p0HPof4il0ynVzBlienObmX_uKMZr8htUalUdfQcM20/18913396070'
[Tue Jul 30 19:15:09 CST 2019] payload='{}'
[Tue Jul 30 19:15:09 CST 2019] POST
[Tue Jul 30 19:15:09 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/p0HPof4il0ynVzBlienObmX_uKMZr8htUalUdfQcM20/18913396070'
[Tue Jul 30 19:15:09 CST 2019] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  -g '
[Tue Jul 30 19:15:10 CST 2019] _ret='0'
[Tue Jul 30 19:15:10 CST 2019] code='200'
[Tue Jul 30 19:15:10 CST 2019] socat doesn't exists.
[Tue Jul 30 19:15:10 CST 2019] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.1e-fips 11 Feb 2013
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.14.1
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) 
built with OpenSSL 1.0.2o  27 Mar 2018
TLS SNI support enabled
configure arguments: --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module --with-http_sub_module --with-stream --with-stream_ssl_module --with-openssl=/root/lnmp1.5/src/openssl-1.0.2o
socat:
[Tue Jul 30 19:15:10 CST 2019] Return code: 1
[Tue Jul 30 19:15:10 CST 2019] Error renew zzhjiyin.tk.
[Tue Jul 30 19:15:10 CST 2019] ===End cron===

```

acme.sh --cron --debug

**Comment by lcdtyph** [comment]
Install ```socat``` with your package manager.

**Comment by zzhjiyin** [comment]
I have figured out this problem.although the ssl cert has been inavailable,but the nginx set the rule that 80 port all point to 443, so the letencrypt fetched the web by 443 port,it caused the error directly,I cancelled the rule,try again the above code, it worked!
