### ISSUE TITLE
Certificate Issue Date question

### ISSUE THREAD

**Issue by lnwxav** [Neilpang/acme.sh#2415]
Due to my cyberpanel Let's Encrypt SSL problem (since 12 july), I use your acme to generate SSL and your acme can fix that problem. (Thank You :D ).

But I have 1 weirdthing. Look at this certificate it's valid from 12 June to 10 September. But as I said, I use your acme generate SSL on 12 july.

![cc (1)](https://user-images.githubusercontent.com/43088483/62048235-90461180-b236-11e9-9f00-e3b77dc9e5be.jpg)

My question is "why 12 june instead of 12 july"? Is it bug?

**Comment by Neilpang** [comment]
there is no cert generated at july 12 for your domain.
https://crt.sh/?q=greedisgoods.com
