### ISSUE TITLE
Failed to fetch acme-challenge using webroot mode for custom tls port

### ISSUE THREAD

**Issue by Linburger** [Neilpang/acme.sh#2418]
Steps to reproduce
------------------
in centos with apache server and all requests from port 80 will be redirected to 9443, when try to issue certificate using webroot mode. I find the request for fetching acme-challenge is redirected to 9443 but failed with "**Invalid port in redirect target, only ports 80 and 443 are supported, not 9443.**".
Does that mean we can only listen 80 and 443 when issue a certificate or is there something needed for this case
My Running commands:
```
acme.sh --issue -d mydomain.com -w /myWebRoot
```

**Comment by Neilpang** [comment]
use 80 or 443 only.
