### ISSUE TITLE
next renew time uses different time formats - renewals being missed

### ISSUE THREAD

**Issue by heldchen** [Neilpang/acme.sh#242]
on the same server, different certificates seem to use different time formats for their renewal timestamp:

domain1:
`[Thu Jul 21 21:00:02 CEST 2016] Skip, Next renewal time is: Mon Oct  3 19:00:22 UTC 2016`

domain2:
`[Thu Jul 21 21:00:02 CEST 2016] Skip, Next renewal time is: 2016-07-22 19:00:15 UTC`

the time format of domain1 is correctly recognised, while the format for domain2 is not. is that a leftover of a previous acme.sh version or a problem with the bash locale that needs to be addressed? when I manually force a renewal of domain2, the time format changes to what domain1 uses. about 30% of the certificates on that specific servers use the same format as domain2 tho...

**Comment by Neilpang** [comment]
It's just the old format left by previous version of acme.sh.

Don't worry, it's just a display string for human being.  it doesn't affect the actual renewal time.

When next the cert is renewed automatically, it will use the new format.

**Comment by heldchen** [comment]
actually it **does** affect the renewal time - for example domain2's renewal is long overdue and the certificate would have expired later today. we even had some expired certificates on other domains on this and other servers. I did manually renew then all now, so for me everything is fine now, but others might run into the same issue.

**Comment by Neilpang** [comment]
there is a small issue.
if the displayed renew time is `2016-07-22 19:00:15 UTC`,     the actual renewal time will be at `2016-07-23 0:0:0 (local time zone)`

So, if you wait more than 24 hours, it should be renewed.

**Comment by heldchen** [comment]
oh ok, I understand. thanks!
