### ISSUE TITLE
More granular renewal interval

### ISSUE THREAD

**Issue by mmalone** [Neilpang/acme.sh#2422]
Hi!

I'm working on ACME support for an internal certificate authority and I'm trying to document the best way to use `acme.sh` as a client. I'm running into an issue with renewals. By default, you renew certs after they're 60 days old. I found that you can override this with the `--days` flag, but our CA issues short-lived certs for only 24 hours by default! So obviously days are not a granular enough time unit for us. I tried passing something like `--days "0.75"` but, alas, command-line math is integral only. Any thoughts on a workaround or fix?

I also noticed that when you pass `--ca-bundle` it's persisted globally for all `acme.sh` operations. This was a little surprising. It means that if I get certs from both Let's Encrypt and an internal CA on one host, the internal CA root is also trusted for the Let's Encrypt request. Not a huge deal, but a little weird. Interesting it does work, probably by accident, because when you pass `--cacert` to `curl` it actually _adds_ to the list of trusted certs instead of replacing it. TIL.

**Comment by Neilpang** [comment]
our cronjob  is designed to run once a day.  so, the minimum interval is 1 day.
