### ISSUE TITLE
ggc.world:Verify error:Invalid response from https://ggc.world/.well-known/acme-challenge/fTYaRei8-Flt8p5SL3aCjpGdRCQzU9rR7_JTm3qDDpg 

### ISSUE THREAD

**Issue by marcoippolito** [Neilpang/acme.sh#2423]
In my Ubuntu 18.04.02 Server Edition I just installed acme.sh 

    marco@pc:~$ git clone https://github.com/Neilpang/acme.sh.git
    Cloning into 'acme.sh'...
    remote: Enumerating objects: 8, done.
    remote: Counting objects: 100% (8/8), done.
    remote: Compressing objects: 100% (6/6), done.
    remote: Total 9036 (delta 2), reused 4 (delta 2), pack-reused 9028
    Receiving objects: 100% (9036/9036), 3.55 MiB | 5.25 MiB/s, done.
    Resolving deltas: 100% (5255/5255), done.
    marco@pc:~$ cd acme.sh/

    marco@pc:~/acme.sh$ ./acme.sh --install  \
    > --home ~/myacme \
    > --config-home ~/myacme/data \
    > --cert-home  ~/mycerts \
    > --accountemail  "myemail@gmail.com" \
    > --accountkey  ~/myaccount.key \
    > --accountconf ~/myaccount.conf \
    > --useragent  "this is my client."
    [Sat Aug  3 19:43:49 CEST 2019] It is recommended to install socat first.
    [Sat Aug  3 19:43:49 CEST 2019] We use socat for standalone server if you use standalone 
    mode.
    [Sat Aug  3 19:43:49 CEST 2019] If you don't use standalone mode, just ignore this warning.
    [Sat Aug  3 19:43:49 CEST 2019] Installing to /home/marco/myacme
    [Sat Aug  3 19:43:49 CEST 2019] Installed to /home/marco/myacme/acme.sh
    [Sat Aug  3 19:43:49 CEST 2019] Installing alias to '/home/marco/.bashrc'
    [Sat Aug  3 19:43:49 CEST 2019] OK, Close and reopen your terminal to start using acme.sh
    [Sat Aug  3 19:43:49 CEST 2019] Installing cron job
    no crontab for marco
    no crontab for marco
    [Sat Aug  3 19:43:49 CEST 2019] Good, bash is found, so change the shebang to use bash as  
    preferred.
    [Sat Aug  3 19:43:49 CEST 2019] OK

Following the indications here: https://www.cyberciti.biz/faq/how-to-configure-nginx-with-free-lets-encrypt-ssl-certificate-on-debian-or-ubuntu-linux/

I tried to issue certificates:

    marco@pc:~/acme.sh$ sudo ./acme.sh --issue -w /home/wwwroot/ggc.world -d ggc.world -d 
    www.ggc.world -k 4096 --debug 2
 
But it outputs this error message:

    ggc.world:Verify error:Invalid response from https://ggc.world/.well-known/acme-challenge/EuJ-
      IUyrP9Tv0Fr49ZgeivU-Hhe4RV-V5XPw1X8IHMs [109.116.173.122]: 

I included the complete debug log:
[certsIssueDebugOutput.txt](https://github.com/Neilpang/acme.sh/files/3464263/certsIssueDebugOutput.txt)

    marco@pc:~$ curl -IkL -m20 http://ggc.world
    HTTP/1.1 301 Moved Permanently
    Server: nginx/1.14.0 (Ubuntu)
    Date: Sat, 03 Aug 2019 18:24:16 GMT
    Content-Type: text/html
    Content-Length: 194
    Connection: keep-alive
    Location: https://ggc.world/
    Strict-Transport-Security: max-age=31536000

    HTTP/2 200 
    server: nginx/1.14.0 (Ubuntu)
    date: Sat, 03 Aug 2019 18:24:16 GMT
    content-type: text/html; charset=UTF-8
    content-length: 2438
    x-powered-by: Express
    accept-ranges: bytes
    etag: W/"986-Blz4escee3Zs+0l962PhNYFx224"
    strict-transport-security: max-age=31536000

After adding --force as parameter of issuing command:

    marco@pc:~/acme.sh$ sudo ./acme.sh --issue -w /home/wwwroot/ggc.world -d ggc.world -d 
    www.ggc.world -k 4096 --force --debug 2

    [Sat Aug  3 21:55:29 CEST 2019] Use length 4096
    [Sat Aug  3 21:55:29 CEST 2019] Using RSA: 4096
    [Sat Aug  3 21:55:29 CEST 2019] The domain key is here: /home/marco/.acme.sh/ggc.world
    /ggc.world.key
    [Sat Aug  3 21:55:29 CEST 2019] _createcsr
    [Sat Aug  3 21:55:29 CEST 2019] domain='ggc.world'
    [Sat Aug  3 21:55:29 CEST 2019] domainlist='www.ggc.world'
    [Sat Aug  3 21:55:29 CEST 2019] csrkey='/home/marco/.acme.sh/ggc.world/ggc.world.key'
    [Sat Aug  3 21:55:29 CEST 2019] csr='/home/marco/.acme.sh/ggc.world/ggc.world.csr'
    [Sat Aug  3 21:55:29 CEST 2019] csrconf='/home/marco/.acme.sh/ggc.world/ggc.world.csr.conf'

Error output:

    [Sat Aug  3 21:55:30 CEST 2019] response='{
      "type": "urn:ietf:params:acme:error:rateLimited",
      "detail": "Error creating new order :: too many failed authorizations recently: see   
      https://letsencrypt.org/docs/rate-limits/",
      "status": 429
    }'
    [Sat Aug  3 21:55:30 CEST 2019] Le_LinkOrder
    [Sat Aug  3 21:55:30 CEST 2019] Le_OrderFinalize

    [Sat Aug  3 21:55:30 CEST 2019] Create new order error. Le_OrderFinalize not found. {
      "type": "urn:ietf:params:acme:error:rateLimited",
      "detail": "Error creating new order :: too many failed authorizations recently: see  
    https://letsencrypt.org/docs/rate-limits/",
      "status": 429

The complete debug log is here: 
[certsIssueDebugOutput-2.txt](https://github.com/Neilpang/acme.sh/files/3464275/certsIssueDebugOutput-2.txt)

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by Neilpang** [comment]
Don't use sudo

**Comment by marcoippolito** [comment]
Thanks @Neilpang . I discovered that I had to use root. Solved: https://community.letsencrypt.org/t/acme-sh-how-to-set-the-automatic-certiicates-renewal-ubuntu-18-04-02-server-edition/99586
