### ISSUE TITLE
证书没有正常更新

### ISSUE THREAD

**Issue by xinyei** [Neilpang/acme.sh#2428]
2019/4/11 申请的证书 ：acme.sh  --issue mydomain.me   --standalone --httpport  8080 -k 3072
今天发现证书已经过期25天了，我尝试手动执行renew，但是返回了错误
[ec2-user@ip-172-30-2-50 ~]$ sudo ~/.acme.sh/acme.sh --renew -d mydomain.me --force
[Mon Aug  5 07:22:08 UTC 2019] Renew: 'mydomain.me'
[Mon Aug  5 07:22:08 UTC 2019] 'mydomain.me' is not a issued domain, skip.
之前申请完证书是有测试过手动更新的，是能够正常更新的。
请问为什么我的域名会变成了未发布状态？

**Comment by Neilpang** [comment]
不要用 sudo
