### ISSUE TITLE
没有crontab 会自动更新吗?

### ISSUE THREAD

**Issue by warriorBrian** [Neilpang/acme.sh#2435]
我按wiki成功颁发了证书，但是我输入`crontab -l`，返回 no crontab for root
我想问下，他会自动续订么，wiki上说60天会自动续订，但是我没看到crontab任务。
![image](https://user-images.githubusercontent.com/28696399/62817492-5a742780-bb6a-11e9-9911-722a80ba4ad8.png)

**Comment by Neilpang** [comment]
1. 首先, 标题可以改一下, 开宗明义:   没有crontab 会自动更新吗?   没有人愿意看到类似: 关于xxxx 的疑问.  之类的标题.   点进来看需要时间.
2. 其次:  请详细描述你的问题. 比如, 你根据哪个wiki 页面做的, 是在主机还是在docker 里面.  笼统的说, 别人没时间来猜.  你不会得到任何有用的帮助.
3. 第三, 不要发私人邮件来问问题. 不提供免费的邮件支持. 你不会得到任何回复.

**Comment by warriorBrian** [comment]
@Neilpang

**Comment by warriorBrian** [comment]
@Neilpang 
1. 我根据这个： [wiki](https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E) 来进行操作。
2. 我执行了 `acme.sh -d demo.aaa.com --nginx`
3. 然后执行了 `acme.sh  --installcert  -d  <domain>.com   \
        --key-file   /etc/nginx/ssl/<domain>.key \
        --fullchain-file /etc/nginx/ssl/fullchain.cer \
        --reloadcmd  "service nginx force-reload"`
4. 最后执行了 `acme.sh --upgrade --auto-grade`

5. 我发现了`crontab -l`没有任何任务。环境`Centos7`,阿里云ECS服务器。服务器内部执行，没有任何虚拟容器承载。

然后，按照你口中的开宗明义：没有crontab 会自动更新吗?

**Comment by Neilpang** [comment]
如果你的 `crontab -l` 中确实没有的话, 可以执行:

```
acme.sh  --install-cronjob
```

它会帮你安装 cronjob.

如果有了, 就可以了.

另外, 你还可以设置一个通知功能, 这样你每天晚上都能收到通知:
https://github.com/Neilpang/acme.sh/wiki/notify

**Comment by warriorBrian** [comment]
@Neilpang 非常感谢。
