### ISSUE TITLE
feature request: recognized "--days" parameter for "--renew" and "--renewAll"

### ISSUE THREAD

**Issue by heldchen** [Neilpang/acme.sh#244]
currently, the "days" value used during "issue" is stored in the domain.conf along with the next renewall timestamp/date. there seems currently no way to automatically adjusting this values.

I'm trying to lower the renewall days from the initial 80 to 70 to avoid getting the "Let's Encrypt certificate expiration notice" email notifications. I was hoping I could just use the `--days` parameter with -`-renew` resp. `--renewAll` to have the values adjusted when the certificates are due to renew, but acme.sh keeps using the initial 80 days as stored in the domain conf.

it would be nice to have the following:
- `--renew` and `--renewAll` recognise the `--days` parameter
- (optionally) if the passed `--days` value is different from what is stored in the domain conf recalculate the `Le_NextRenewTime` and `Le_NextRenewTimeStr` values

**Comment by Neilpang** [comment]
hmmmm...
Let me think about it.

**Comment by heldchen** [comment]
awesome, thanks!
