### ISSUE TITLE
通过(--standalone)方式安装证书 - 【续签】

### ISSUE THREAD

**Issue by weishengbin** [Neilpang/acme.sh#2449]
安装证书使用--standalone方式，需要先关闭服务器上的80端口，保证其不被占用，那么有一个问题是，安装完成之后，服务器会启动80端口的服务（如nginx），后期续签时80端口是被占用着的，这有影响吗？是否会影响证书的续签？

**Comment by Neilpang** [comment]
如果你的80 端口被占用了,  不建议使用 standalone 模式.   替换成webroot 模式 或着 dns api 模式, 或者 nginx 模式.

如果你非要使用standalone 模式,   可以用 `--pre-hook` 和 `--post-hook`

```sh
acme.sh  --issue -d xxxxxx   ...   --pre-hook "service nginx stop"  --post-hook  "service nginx start"
```
