### ISSUE TITLE
wiki/Options-and-Params — formatting 

### ISSUE THREAD

**Issue by dilyanpalauzov** [Neilpang/acme.sh#2451]
At https://github.com/Neilpang/acme.sh/wiki/Options-and-Params “--nocron Only valid for '--install' command, which means: do not install the default cron job. In this case, the certs will not be renewed automatically. --noprofile Only valid for '--install' command, which means: do not install aliases to user profile. --ecc Specifies to use the ECC cert. Valid for '--installcert', '--renew', '--revoke', '--toPkcs' and '--createCSR'” are supposed to be on three lines, but it is one.

**Comment by FernandoMiguel** [comment]
@dilyanpalauzov it's a wiki.
Feel free to edit it
