### ISSUE TITLE
Is netcat or socat required?

### ISSUE THREAD

**Issue by dilyanpalauzov** [Neilpang/acme.sh#2454]
Per https://github.com/Neilpang/acme.sh/wiki/Install-preparations netcat on the system where `acme.sh` is running must support the `-4` and `-6` options.  But I do not see in the source code, where `nc` or `netcat` is involved.  In particular, `acme.sh:2161:  _NC="socat"` indicates, that `socat` is required, and `netcat` is not used.

**Comment by Neilpang** [comment]
the wiki page is updated.
Thanks.
