### ISSUE TITLE
Get two TXT records it wants me to add be neither works

### ISSUE THREAD

**Issue by ygator** [Neilpang/acme.sh#2456]
Same issue as #1684
It seems that manual DNS is still broke or the command I am using is incorrect.
This happens every 3 months when I go to renew.  So far I have been able to keep running the commands until I receive only one TXT record.  However, this time I ran into a rate limit and have to wait an hour to try again.

Last time I reported the issue the only reply back was to not use manual dns mode.  Which is not help since it is the only mode I can use.

Is my command correct or is this a bug?
What does --dns dns_cf do?

Thanks

./acme.sh --issue --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please -d domain.com -d '*.domain.com'
Multi domain='DNS:domain.com,DNS:*.domain.com'
Getting domain auth token for each domain
Getting webroot for domain='domain.com'
Getting webroot for domain='*.domain.com'
Add the following TXT record:
Domain: '_acme-challenge.domain.com'
TXT value: 'hkokwt943mgm'rgojkhkjtorhmktrwktrjktrjykjkr'
Please be aware that you prepend _acme-challenge.before your domain
so the resulting subdomain will be: _acme-challenge.domain.com
Add the following TXT record:
Domain: '_acme-challenge.domain.com'
TXT value: 'okowthotrkotr50whrwthrthkwrkgkrtkl3lgkrtkor'
Please be aware that you prepend _acme-challenge.before your domain
so the resulting subdomain will be: _acme-challenge.domain.com
Please add the TXT records to the domains, and re-run with --renew.
Please add '--debug' or '--log' to check more details.
See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by kshji** [comment]
Same question. I'll say that link not give answer for this Multi domain version problem. TXT record twice. That is not problem but checking not loop TXT records for same host.

**Comment by Neilpang** [comment]
Strictly follow the steps here:

https://github.com/Neilpang/acme.sh/wiki/DNS-manual-mode

**Comment by ygator** [comment]
Neil,

I just tried to renew and got 2 TXT records back again.  Here it is fully documented.

> $ ./acme.sh --renew -d example.com --yes-I-know-dns-manual-mode-enough-go-ahead-please
Renew: 'example.com'
Multi domain='DNS:example.com,DNS:*.example.com'
Getting domain auth token for each domain
Getting webroot for domain='example.com'
Getting webroot for domain='*.example.com'
Add the following TXT record:
Domain: '_acme-challenge.example.com'
TXT value: 'ysWnd1uaPhDFrGEAc0UPNBYonC_fMNb5KJ_etEQT_Xc'
Please be aware that you prepend _acme-challenge. before your domain
so the resulting subdomain will be: _acme-challenge.example.com
Add the following TXT record:
Domain: '_acme-challenge.example.com'
TXT value: 'OCg1PLwNBQV7QRK-OEVUbZx0w7HEn89SdI4LgvbEris'
Please be aware that you prepend _acme-challenge. before your domain
so the resulting subdomain will be: _acme-challenge.example.com
Please add the TXT records to the domains, and re-run with --renew.
Please add '--debug' or '--log' to check more details.
See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
The dns manual mode can not renew automatically, you must issue it again manually. You'd better use the other modes instead.

 Can only enter one TXT since they are the same and put in the first one.  Got back TXT is invalid.

> $ ./acme.sh --renew -d example.com --yes-I-know-dns-manual-mode-enough-go-ahead-please
Renew: 'example.com'
Multi domain='DNS:example.com,DNS:*.example.com'
Getting domain auth token for each domain
Verifying: example.com
Success
Verifying: *.example.com
*.example.com:Verify error:Incorrect TXT record
Please add '--debug' or '--log' to check more details.
See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
The dns manual mode can not renew automatically, you must issue it again manually. You'd better use the other modes instead.

Went ahead and switched to the second TXT.

> $ ./acme.sh --renew -d example.com --yes-I-know-dns-manual-mode-enough-go-ahead-please
Renew: 'example.com'
Multi domain='DNS:example.com,DNS:*.example.com'
Getting domain auth token for each domain
Getting webroot for domain='example.com'
Getting webroot for domain='*.example.com'
Add the following TXT record:
Domain: '_acme-challenge.example.com'
TXT value: '1nFkAsxxisATSGguwAAqOs4XDaTSBUVmhImV_MJAHrS'
Please be aware that you prepend _acme-challenge. before your domain
so the resulting subdomain will be: _acme-challenge.example.com
Please add the TXT records to the domains, and re-run with --renew.
Please add '--debug' or '--log' to check more details.
See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
The dns manual mode can not renew automatically, you must issue it again manually. You'd better use the other modes instead.

It gave yet another TXT so I entered that one and did a renew again.

> $ ./acme.sh --renew -d example.com --yes-I-know-dns-manual-mode-enough-go-ahead-please
Renew: 'example.com'
Multi domain='DNS:example.com,DNS:*.example.com'
Getting domain auth token for each domain
example.com is already verified, skip dns-01.
Verifying: *.example.com
Success
Verify finished, start to sign.
Lets finalize the order, Le_OrderFinalize: https://acme-v02.api.letsencrypt.org/acme/finalize/36878460/1459764441
Download cert, Le_LinkCert: https://acme-v02.api.letsencrypt.org/acme/cert/04679786c21b06da541e086bc495e77b2c62
Cert success.
-----BEGIN CERTIFICATE-----

Finally success.  The renew command I am using is the "exact" one given in the link you gave.
