### ISSUE TITLE
crontab entry for acme.sh

### ISSUE THREAD

**Issue by b-a-t** [Neilpang/acme.sh#246]
I've added crontab entry to `acme.sh` via `acme.sh --install` and been a bit surprised by the generated line:

    0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null

Those quotes around `"/root/.acme.sh"` look a bit abigious... They shouldn't really hurt, but I'd rather expect `"/root/.acme.sh/acme.sh"` if any.

 Also, LetsEncrypt recommends to invoke renewal script twice a day at least and at a random time frame...

**Comment by Neilpang** [comment]
1. for  the quotes,  it was designed like that.   It may cause problems when quote fully.
2. Where did you find "LetsEncrypt recommends to invoke renewal script twice a day"  ?

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/issues/208

**Comment by helix** [comment]
@Neilpang wrote:
> for the quotes, it was designed like that. It may cause problems when quote fully.

Just out of curiosity, can you explain what kind of problems may occur when the script path is full quoted ?
