### ISSUE TITLE
after testing a domain with --staging acme.sh does not revert to non-staging mode

### ISSUE THREAD

**Issue by hxx-fetch** [Neilpang/acme.sh#2463]
To debug some connection issues I was using --renew with --staging to overcome
the renew-rate-limiting of the letsencrypt servers.

After the issues were resolved I was trying to --renew the certificate for production,
(with out --staging) but I still got testing-certficates until I manually changed the 
Le_API-entry  in the .conf file of the  domain 

Thanx
hxx

**Comment by FernandoMiguel** [comment]
You need to issue a new one and use --force

**Comment by FernandoMiguel** [comment]
Don't edit config files manually

**Comment by hxx-fetch** [comment]
> You need to issue a new one and use --force
Thanks, will use this the next time I run into this.
