### ISSUE TITLE
A机申请了证书，A机挂了，在B机上renew证书可以吗？

### ISSUE THREAD

**Issue by AgainCrazyCode** [Neilpang/acme.sh#2467]
你好
A机大概申请了60个域名证书，单域名形式。很不幸的是，A机在几天前挂了，一切申请证书的原始数据都没有了，请问在B机中新环境renew证书操作可以直接用吗？还是需要原始数据的？

**Comment by baoang** [comment]
原始数据全没了就不行了吧，因为你申请时的诸如：

- ca目录及其下的账号及key数据
- domain.tld (60个)目录及其下的账号及key数据
- account.conf 文件
全没有了，只能重新申请，续是续不起来了。

**Comment by Neilpang** [comment]
不需要renew,  直接重新申请即可.
