### ISSUE TITLE
你好 ，奇怪问题，acme.sh不能解析到域名。因为域名中有两层CNAME，是不是不支持多IP域名？加--test成功，不加失败

### ISSUE THREAD

**Issue by 0CrazyGuy9** [Neilpang/acme.sh#2473]
acme 你好

xxxx.com指向了我的CNAME，CNAME中使用了多层CNAME，然后才到几个IP地址。

dig 出来是没错，输入网址也可以正常访问。

为了隐私，xxxx.com代表我的域名，在WAN是可以正常访问,+++++是隐藏过的IP

 /root/.acme.sh/acme.sh -v
https://github.com/Neilpang/acme.sh
v2.8.3

dig xxxx.com

; <<>> DiG 9.9.4-RedHat-9.9.4-74.el7_6.2 <<>> xxxx.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19905
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;xxxx.com.                 IN      A

;; ANSWER SECTION:
xxxx.com.          599     IN      CNAME   xxxx.com.yyyy.com.
xxxx.com.yyyy.com. 599 IN   CNAME   all.yyy.com.
node1.xm.cdn.com.  599     IN      A       111.223.++++
node1.xm.cdn.com.  599     IN      A       111.223++++
node1.xm.cdn.com.  599     IN      A       43.240++++

;; Query time: 134 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Sep 10 00:16:18 CST 2019
;; MSG SIZE  rcvd: 156

---------------------------------------------------------------------------------------------------

但就是创建证书的时候提示：
[Mon Sep  9 19:43:08 CST 2019] Single domain='xxxx.com'
[Mon Sep  9 19:43:08 CST 2019] Getting domain auth token for each domain
[Mon Sep  9 19:43:09 CST 2019] Getting webroot for domain='xxxx.com'
[Mon Sep  9 19:43:09 CST 2019] Verifying: xxxx.com
[Mon Sep  9 19:43:13 CST 2019] Pending
[Mon Sep  9 19:43:15 CST 2019] Pending
xxxx.com:Verify error:No valid IP addresses found for xxxx.com

详细日志都这样显示
 {"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:dns","detail":"No valid IP addresses found for xxxx.com","status": 400},"url":"https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/7910388/JbmjJQ","token":"If39iIyB9pJLShjA2YyCxq9feJ6UmT8SSNU3ULuyFRk"}

[Mon Sep  9 22:10:40 CST 2019] _clearupdns
[Mon Sep  9 22:10:40 CST 2019] dns_entries
[Mon Sep  9 22:10:40 CST 2019] skip dns.
[Mon Sep  9 22:10:40 CST 2019] _on_issue_err

请问怎么办？我这都是5个IP以上的CNAME

---------------------------------------------------------------------------------------------------

还有就是
当我用测试模式 ， 加 --test 参数的时候，能验证生成证书

但去掉--test，就不同结果了
/root/.acme.sh/acme.sh --issue -d xxxx.com --webroot /tmp/wwwroot --key-file /tmp/xxxx.com.key --cert-file /tmp/xxxx.com.cert --fullchain-file /tmp/xxxx.com.crt --force --log

[Wed Sep 11 19:34:57 CST 2019] xxxx.com:Verify error:No valid IP addresses found for xxxx.com
[Wed Sep 11 19:34:57 CST 2019] Please check log file for more details: /root/.acme.sh/acme.sh.log

同样的域名，加--test可以，不加--test就不可以。请问这是怎么回事？加上--test就成功了
/root/.acme.sh/acme.sh --issue -d xxxx.com --webroot /tmp/wwwroot --key-file /tmp/xxxx.com.key --cert-file /tmp/xxxx.com.cert --fullchain-file /tmp/xxxx.com.crt --force --log --test

[Wed Sep 11 19:36:46 CST 2019] Your cert is in /root/.acme.sh/xxxx.com/xxxx.com.cer
[Wed Sep 11 19:36:46 CST 2019] Your cert key is in /root/.acme.sh/xxxx.com/xxxx.com.key
[Wed Sep 11 19:36:46 CST 2019] The intermediate CA cert is in /root/.acme.sh/xxxx.com/ca.cer
[Wed Sep 11 19:36:46 CST 2019] And the full chain certs is there: /root/.acme.sh/xxxx.com/fullchain.cer
[Wed Sep 11 19:36:46 CST 2019] Installing cert to:/tmp/cert/xxxx.com.cert
[Wed Sep 11 19:36:46 CST 2019] Installing key to:/tmp/cert/xxxx.com.key
[Wed Sep 11 19:36:46 CST 2019] Installing full chain to:/tmp/cert/xxxx.com.crt

请问这是为什么呢？DNS检测出现问题吗？还是不支持5个IP以上的指向?

acme 大神帮帮我吧

**Comment by AgainCrazyCode** [comment]
域名 指向 CNAME  CNAME再指向CNAME，有4个IP以上的

**Comment by AgainCrazyCode** [comment]
感觉测试发现，太多IP是不行的。比如3个IP以上……

**Comment by 0CrazyGuy9** [comment]
把CNAME指向的IP减少了，减到只指向2个，正常验证到证书……

**Comment by 0CrazyGuy9** [comment]
还有就是
当我用测试模式 ， 加 --test 参数的时候，能验证生成证书

但去掉--test，就不同结果了

[Wed Sep 11 19:34:57 CST 2019] xxxx.com:Verify error:No valid IP addresses found for xxxx.com
[Wed Sep 11 19:34:57 CST 2019] Please check log file for more details: /root/.acme.sh/acme.sh.log

**Comment by Neilpang** [comment]
多ip 的, 使用 dns 方式吧.
web 方式我不是一两句话给你解释清楚的.

**Comment by 0CrazyGuy9** [comment]
你好
多IP的，有时候域名的管理权限不在我手，还有其他办法吗？
