### ISSUE TITLE
 求教：如果重启了服务器，自动更新的任务是否需要手动启动呢？

### ISSUE THREAD

**Issue by flftfqwxf** [Neilpang/acme.sh#2475]
求教：
问题1：
如果重启了服务器，自动更新的任务是否需要手动启动呢？
问题2：
自动更新是根据，此命令的内容来执行的么：

acme.sh  --installcert  -d  <domain>.com   \
        --key-file   /etc/nginx/ssl/<domain>.key \
        --fullchain-file /etc/nginx/ssl/fullchain.cer \
        --reloadcmd  "service nginx force-reload"

**Comment by Neilpang** [comment]
文档里面明确说明的问题, 为什么还要再问一遍.
https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E

**Comment by flftfqwxf** [comment]
@Neilpang 谢谢，文档看过了，只是不太确认你那个表达理解是不是一致，你那个文档有些表述意思不是非常明确，中英文的文档内容有一些不一致，也没有提，如果重启了，是否也会自动运行定时任务

**Comment by lovelyelfpop** [comment]
`crontab -l` 可以查看所有定时任务，可以看到有 acme.sh 的定时任务

**Comment by flftfqwxf** [comment]
@lovelyelfpop 我知道可以看，我的意思是重启后会不会自动添加这个定时任务，我线上的服务也不会没事去重启着去试

**Comment by lovelyelfpop** [comment]
@flftfqwxf 定时任务当然只会添加一次，多次添加不就多个定时任务了
