### ISSUE TITLE
--standalone --httpport weirdness (or simple user)

### ISSUE THREAD

**Issue by Stubblet** [Neilpang/acme.sh#2476]
I am trying to issue a cert:

./acme.sh --issue --config-home /var/etc/acme-client --staging  --cert-home '/var/etc/acme-client/home/'  -d mydomain --standalone --httpport 9999 --force --debug 2

Acme seems to setup properly:

[Tue Sep 10 10:33:01 BST 2019] Le_HTTPPort='9999'
[Tue Sep 10 10:33:01 BST 2019] Le_Listen_V4
[Tue Sep 10 10:33:01 BST 2019] Le_Listen_V6
[Tue Sep 10 10:33:01 BST 2019] _content_len='      87'
[Tue Sep 10 10:33:01 BST 2019] _NC='socat -d -d -v TCP-LISTEN:9999,crlf,reuseaddr,fork'
2019/09/10 10:33:01 socat[92977] N listening on LEN=16 AF=2 0.0.0.0:9999

But the callback looks wrong:

[Tue Sep 10 10:33:15 BST 2019] original='{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:connection",
    "detail": "Fetching http://mydomain/well-known/acme-challenge/ry52Yu8....: Timeout during connect (likely firewall problem)",
    "status": 400
  },

The firewall is configured for the port.

What am i doing wrong ?

A.

**Comment by Neilpang** [comment]
you can not use `--httpport 9999`

remove it or use `80` port
