### ISSUE TITLE
sudo -s

### ISSUE THREAD

**Issue by simolev** [Neilpang/acme.sh#2478]
Debug log
-----------------
It seems that if a user became root with `sudo su`, then they are allowed to run `acme.sh`.  
Not so if they employed `sudo -s` or `sudo -i`.

Steps to reproduce
------------------

`sudo -s`
`git clone https://github.com/Neilpang/acme.sh.git /root/.acme.sh`
`vi /root/.acme.sh/account.conf`
```
SAVED_HE_Username='user'
SAVED_HE_Password='******'
ACCOUNT_EMAIL='user@domain.com'
```
`/root/.acme.sh/acme.sh --home /root/.acme.sh --issue --dns dns_he --keylength ec-256 -d my.domain.com`

Debug log
-----------------

```
/root/.acme.sh/acme.sh --home /root/.acme.sh --issue --dns dns_he --keylength ec-256 -d my.domain.com --debug 2
It seems that you are using sudo, please read this link first:
https://github.com/Neilpang/acme.sh/wiki/sudo
```

Possible solution
-----------------
in acme.sh, replace line 6244:
`     if [ "$SUDO_COMMAND" = "/bin/su" ]; then`
with:
`    if [ "$SUDO_COMMAND" = "/bin/su" ] || [ "$SUDO_COMMAND" = "/bin/bash" ]; then`

**Comment by Neilpang** [comment]
fine
