### ISSUE TITLE
crontab command fails with non-standard --cert-home??

### ISSUE THREAD

**Issue by chgaertner** [Neilpang/acme.sh#2491]
Hi!

The automatic installation (curl https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh | INSTALLONLINE=1 sh) adds a command like this to the crontab:
**"/home/pi/.acme.sh"/acme.sh --cron --home "/home/pi/.acme.sh"**

When I issue a certificate with the _--cert-home /home/pi/cert_ option, the certificate is stored in the location specified. The crontab command shown above cannot find the certificate in its default folder and therefore it cannot check if it is due for renewal. I have to manually modify the crontab command:
**"/home/pi/.acme.sh"/acme.sh --cron --home "/home/pi/.acme.sh" --cert-home "/home/pi/cert"**

Even if i use the custom installation command and specify an alternate certificate store during installation (**./acme.sh --install --cert-home /home/pi/cert**), the command in the crontab does not include the _--cert-home_ part.

I know that I can easily modify the crontab command but I am using acme.sh inside docker containers and therefore I would have to change the crontab after every build.

Am I missing anything or is there a workaround for that problem?

Thank you and best regards,
Christian

**Comment by Neilpang** [comment]
please uninstall it first.   the cronjob will be removed.

close and reopen your terminal.

then install again.  

check your `crontab -l `
