### ISSUE TITLE
我的问题最简单，当地电信封杀了未备案域名的端口，--dns 验证成功后，无法正常访问

### ISSUE THREAD

**Issue by iamlion** [Neilpang/acme.sh#2492]
作者你好，就一个问题：

当地电信封杀了未备案域名的端口，我用 DNS 验证成功后，网站无法正常访问，但是在云服务器内网使用域名可以正常访问，是不是我对 https 配置和 nginx 配置理解不对，还有一点，我用charles连着访问正常，正常浏览器访问不行。

**Comment by Neilpang** [comment]
这与证书无关.
