### ISSUE TITLE
请问是否可以增加支持华为云的api接口

### ISSUE THREAD

**Issue by TesKO666** [Neilpang/acme.sh#2493]
现在的api接口以及很强大， 请问是否可以增加支持华为云的api呢？

**Comment by Neilpang** [comment]
这个问题之前已经有人问过了.
因为要手持,  不支持.

**Comment by xiaoyao9933** [comment]
不需要手持了，微信认证即可。现在没了cloudxns，免费自定义线路的只剩华为云了。
