### ISSUE TITLE
Subfolder 'dnsapi' is not copied with --install

### ISSUE THREAD

**Issue by chgaertner** [Neilpang/acme.sh#2495]
Hi!

If the online installation is performed, the subdirectory 'dnsapi' with all content is copied to the local machine.

If I do a manual install using **acme.sh --install** (to overcome the issue with the wrongly created crontab entry, see issue #2491), the dnsapi subfolder is not created an none of the dns plugins are installed.

BTW: Is there a way to do the online installation but have **NOT** added the cronjob??

Best regards,
Christian

**Comment by Neilpang** [comment]
>> the dnsapi subfolder is not created an none of the dns plugins are installed

No, it's not possible.   please give the debug log with `--debug`


>> BTW: Is there a way to do the online installation but have NOT added the cronjob??

You can install first, and then `crontab -e`  to remove the cronjob.

**Comment by chgaertner** [comment]
**1) Automatic installation**
curl https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh | INSTALLONLINE=1  sh
acme.sh is installed in ~/.acme.sh/ and the following files/folders are created:
- account.conf
- acme.sh
- acme.sh.env
- deploy
- dnsapi
- notify

**2) Manual installation**
curl https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh > acme.sh
chmod +x acme.sh
./acme.sh --install --debug --nocron --noprofile --home /home/pi/.acme.sh --cert-home /home/pi/cert
acme.sh is installed in ~/.acme.sh/ and only the following files/folders are created:
- account.conf
- acme.sh

[Mon 23 Sep 15:06:49 CEST 2019] Running cmd: install
[Mon 23 Sep 15:06:49 CEST 2019] Lets find script dir.
[Mon 23 Sep 15:06:49 CEST 2019] _SCRIPT_='./acme.sh'
[Mon 23 Sep 15:06:49 CEST 2019] _script='/home/pi/acme.sh'
[Mon 23 Sep 15:06:49 CEST 2019] _script_home='/home/pi'
[Mon 23 Sep 15:06:49 CEST 2019] Using config home:/home/pi/.acme.sh
[Mon 23 Sep 15:06:49 CEST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon 23 Sep 15:06:49 CEST 2019] Skip install cron job
[Mon 23 Sep 15:06:49 CEST 2019] It is recommended to install socat first.
[Mon 23 Sep 15:06:49 CEST 2019] We use socat for standalone server if you use standalone mode.
[Mon 23 Sep 15:06:49 CEST 2019] If you don't use standalone mode, just ignore this warning.
[Mon 23 Sep 15:06:49 CEST 2019] Installing to /home/pi/.acme.sh
[Mon 23 Sep 15:06:49 CEST 2019] Installed to /home/pi/.acme.sh/acme.sh
[Mon 23 Sep 15:06:49 CEST 2019] Using config home:/home/pi/.acme.sh
[Mon 23 Sep 15:06:49 CEST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon 23 Sep 15:06:49 CEST 2019] Good, bash is found, so change the shebang to use bash as preferred.
[Mon 23 Sep 15:06:49 CEST 2019] OK

**Comment by Neilpang** [comment]
please download the whole  tar.gz package, and install from there.

https://github.com/Neilpang/acme.sh/archive/master.tar.gz
