### ISSUE TITLE
Cert IPv6 only server

### ISSUE THREAD

**Issue by kiki78** [Neilpang/acme.sh#2497]
I don't know if it's a bug or if I misused acme.sh, but I never found howto record domain with IPv6 only.
I'm behind ISP box with only one IPv4.
Port 80 is already used by main server, so I need to cert secondary server with IPv6 only address.

Is it possible ?

Regards,

**Comment by Neilpang** [comment]
if you use the webroot mode,   no matter it's ipv4 or ipv6, as long as your website can be accessed.
if you use the dns mode,  no ip is needed.
