### ISSUE TITLE
Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 2

### ISSUE THREAD

**Issue by FenghenHome** [Neilpang/acme.sh#2503]
大佬您好
今天是要您的API签名域名，可是爆提示，还请看下是否是问题，是否需要重新签名域名，谢谢

[Tue Sep 24 20:51:27 CST 2019] RSA key
[Tue Sep 24 20:51:27 CST 2019] HEAD
[Tue Sep 24 20:51:27 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Sep 24 20:51:27 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Tue Sep 24 20:51:27 CST 2019] **Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 2**
[Tue Sep 24 20:51:27 CST 2019] _ret='2'
[Tue Sep 24 20:51:27 CST 2019] GET
[Tue Sep 24 20:51:27 CST 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Sep 24 20:51:27 CST 2019] timeout=
[Tue Sep 24 20:51:27 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Sep 24 20:51:28 CST 2019] ret='0'
[Tue Sep 24 20:51:28 CST 2019] POST
[Tue Sep 24 20:51:28 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Sep 24 20:51:28 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Tue Sep 24 20:51:29 CST 2019] _ret='0'
[Tue Sep 24 20:51:29 CST 2019] code='429'

**Comment by Neilpang** [comment]
更新到最新版再试

**Comment by Neilpang** [comment]
```
acme.sh  --upgrade
```

**Comment by FenghenHome** [comment]
一样问题，更新完不需要重启吧

**Comment by Neilpang** [comment]
把  log 贴出来
```
--debug  2
```

**Comment by FenghenHome** [comment]
[Tue Sep 24 21:32:38 CST 2019] RSA key
[Tue Sep 24 21:32:38 CST 2019] Get nonce with HEAD. ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Sep 24 21:32:38 CST 2019] HEAD
[Tue Sep 24 21:32:38 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Sep 24 21:32:38 CST 2019] body
[Tue Sep 24 21:32:38 CST 2019] _postContentType='application/jose+json'
[Tue Sep 24 21:32:38 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.sI7gQflMSi  -g  -I  '
[Tue Sep 24 21:32:38 CST 2019] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 2
[Tue Sep 24 21:32:38 CST 2019] Here is the curl dump log:
[Tue Sep 24 21:32:38 CST 2019] 
[Tue Sep 24 21:32:38 CST 2019] _ret='2'
[Tue Sep 24 21:32:38 CST 2019] Get nonce with GET. ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Sep 24 21:32:38 CST 2019] GET
[Tue Sep 24 21:32:38 CST 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Sep 24 21:32:38 CST 2019] timeout=
[Tue Sep 24 21:32:38 CST 2019] Http already initialized.
[Tue Sep 24 21:32:38 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.sI7gQflMSi  -g '
[Tue Sep 24 21:32:39 CST 2019] ret='0'
[Tue Sep 24 21:32:39 CST 2019] _headers='HTTP/1.1 200 OK
Server: nginx
Date: Tue, 24 Sep 2019 13:32:39 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Replay-Nonce: 00024MFsAi3ZQ88rfkvS1ovNVB1ZYj0ZQmtUfenHBRYuvSE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
'
[Tue Sep 24 21:32:39 CST 2019] _CACHED_NONCE='00024MFsAi3ZQ88rfkvS1ovNVB1ZYj0ZQmtUfenHBRYuvSE'
[Tue Sep 24 21:32:39 CST 2019] nonce='00024MFsAi3ZQ88rfkvS1ovNVB1ZYj0ZQmtUfenHBRYuvSE'
[Tue Sep 24 21:32:40 CST 2019] POST
[Tue Sep 24 21:32:40 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Sep 24 21:32:40 CST 2019] body='{"protected": "eyJub25jZSI6ICIwMDAyNE1Gc0FpM1pRODhyZmt2UzFvdk5WQjFaWWowWlFtdFVmZW5IQlJZdXZTRSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvbmV3LW9yZGVyIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC82NzE3OTA0NCJ9", "payload": "eyJpZGVudGlmaWVycyI6IFt7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6Im1vc3UueHl6In0seyJ0eXBlIjoiZG5zIiwidmFsdWUiOiIqLm1vc3UueHl6In1dfQ", "signature": "QDv6f-xPxzYcm2f-ZVzn5BqA1xyw-kGHWOBCUwXLa_Q4X5L5ifwe7GklKviDZ2uX1r6QWTzI2o_xw5t3IUllwOOQC4nLE86uzrz3goCjyASIMWD_sdNw93kfXTd4cPkBz4oDuxsWV3jO_cUrkGssOF5we0XkJ9_4BRKpn6cFxvuuYHiQVK4nCIv95wIUsqkWfL1MUNYZvyLFZdzRWN1NplYgCfTPB0HnkqJs3x1pBdZibzaGCah02mJ8lrmY5lbpVvBbp952G4bQChhzIenjxXaIYbxwLVVgay0_Wx2e0IhvTbEdMUNrqQXa2mnsM5a-Ioh8veo9t0VTSLitmIwjmg"}'
[Tue Sep 24 21:32:40 CST 2019] _postContentType='application/jose+json'
[Tue Sep 24 21:32:40 CST 2019] Http already initialized.
[Tue Sep 24 21:32:40 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.sI7gQflMSi  -g '
[Tue Sep 24 21:32:41 CST 2019] _ret='0'
[Tue Sep 24 21:32:41 CST 2019] responseHeaders='HTTP/1.1 429 Too Many Requests
Server: nginx
Date: Tue, 24 Sep 2019 13:32:41 GMT
Content-Type: application/problem+json
Content-Length: 244
Connection: keep-alive
Boulder-Requester: 67179044
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002JMis6Hf55Ao0ye75ogq-_D7uS8nRdGxdHAdgz5vYrcw
'
[Tue Sep 24 21:32:41 CST 2019] code='429'

**Comment by Neilpang** [comment]
更新之后, 再试试.

**Comment by yyjazsf** [comment]
`apt insyall libssl-dev  openssl  ` 就行了
