### ISSUE TITLE
Few accounts reg.ru for wildcard certificates

### ISSUE THREAD

**Issue by vitaly80** [Neilpang/acme.sh#2505]
Hello. I am using acme.sh and feel good, thanks! Great app!

I have a question:
I have many sites and many of them on one account reg.ru. I ask support of reg.ru and they give me permissions for use API from my IP-address. It is OK.

I type in shell

```
export REGRU_API_Username='myusername'
export REGRU_API_Password='mypassword'
```

And I get in file /root/.acme.sh/account.conf:

```
SAVED_REGRU_API_Username='myusername'
SAVED_REGRU_API_Password='mypassword'
```

Now, Question!

I have one-two sites, they DNS in other account reg.ru.

Can I customize username and password (from reg.ru) for some sites? I.e. in file conf:

/root/.acme.sh/site2.ru/site2.ru.conf 

And how?

that is, what should I do if I have several reg.ru accounts for different sites?

Sorry for my worst english(

**Comment by Neilpang** [comment]
create another  linux user, and install acme.sh there.
