### ISSUE TITLE
Clarify usage per-system vs. per-user

### ISSUE THREAD

**Issue by archiecobbs** [Neilpang/acme.sh#251]
I attempted to build an RPM of this script. This revealed several usage assumptions which are not necessarily valid.

In an attempt to be easy to use and user friendly, the script does things like install itself, upgrade itself, and modify its own files. Moreover it seems to be based on an assumption that each user is going to manually download and install their own copy under their home directory, etc.

This is not scalable into a deployable package via RPM, deb, etc. and is contrary to the way most packaged software is deployed, i.e., once per system, with separate storage locations for:
- System-wide executables and support files (`/usr/bin/xxx`, `/usr/share/xxx`)
- System-wide read/write state (`/var/lib/xxx`)
- System-wide configuration state (`/etc/xxx`)
- Per-user read/write state (`~/.xxx`)
- Per-user configuration state (`~/.xxx`)

Not sure what the best way to clean all this up is but it's worth some thought.

Perhaps one way to help would be to have a "master" configuration file that defines the locations for all of the config and state files. Then you could say `acme.sh -f myconfig.conf` to get the "universe" defined by `myconfig.conf`.

**Comment by Neilpang** [comment]
Let me think about it.

**Comment by ukoloff** [comment]
As I see, it's trivial task: just install single file `acme.sh` to PATH, eg /usr/bin.

Make sure curl is installed too.

Then acme.sh can be run by any user. It will automatically create `~/.acme.sh/` and use it. It is user-wide config (account.conf) and state.

No system-wide config/state exists.

**Comment by archiecobbs** [comment]
Sounds good to me.

**Comment by ukoloff** [comment]
I thought about two more things:

1. You can replace shebang line to `#!/bin.bash' in acme.sh. acme.sh --install  does so.

2. acme.sh --install creates ~/.acme.sh/account.conf file, so user can look in to see its format and parameters. You should instead provide some docs about them, eg ACCOUNT_EMAIL, STAGE and DEBUG. Or just put sample file into package.

**Comment by Neilpang** [comment]
@ukoloff 
You should not care about where the config file is, and what it is.

You should set the configs by commandline parameters. Do not edit the config file.

**Comment by ukoloff** [comment]
Well, what you said clearly makes sense.

In that case packaging acme.sh is very easy task.
