### ISSUE TITLE
Issue Wildcard certificates needs idn? Wildcard names not supported?

### ISSUE THREAD

**Issue by z0rti** [Neilpang/acme.sh#2511]
I'm trying to issue a wildcard cert:
`acme.sh  --issue -d example.com  -d '*.example.com'  --dns dns_cf`
i get an error:
`It seems that *.example.com is an IDN( Internationalized Domain Names), please install 'idn' command first.`
so i made a script that does just 
`echo '*.example.com'`
now i get this error
`new-authz error: {"type":"urn:acme:error:malformed","detail":"Error creating new authz :: Wildcard names not supported","status": 400}
`
```
$ acme.sh --version
https://github.com/Neilpang/acme.sh
v2.7.4

```

**Comment by vitaly80** [comment]
try
acme.sh --upgrade
