### ISSUE TITLE
Can not find nginx conf.   找不到Nginx配置

### ISSUE THREAD

**Issue by AngleBeats147753** [Neilpang/acme.sh#2516]
Steps to reproduce
------------------
acme.sh --issue  -d 52xiuyixiu.com --nginx --debug 2

nginx -t
输出：
   nginx: the configuration file /usr/local/nginx/conf/nginx.conf syntax is ok
   nginx: configuration file /usr/local/nginx/conf/nginx.conf test is successful

Debug log
-----------------

```
acme.sh --issue  -d 52xiuyixiu.com --nginx --debug 2
```
[Tue Oct  1 01:53:31 CST 2019] Lets find script dir.
[Tue Oct  1 01:53:31 CST 2019] _SCRIPT_='/root/.acme.sh/acme.sh'
[Tue Oct  1 01:53:31 CST 2019] _script='/root/.acme.sh/acme.sh'
[Tue Oct  1 01:53:31 CST 2019] _script_home='/root/.acme.sh'
[Tue Oct  1 01:53:31 CST 2019] Using config home:/root/.acme.sh
[Tue Oct  1 01:53:31 CST 2019] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.3
[Tue Oct  1 01:53:31 CST 2019] Running cmd: issue
[Tue Oct  1 01:53:31 CST 2019] _main_domain='52xiuyixiu.com'
[Tue Oct  1 01:53:31 CST 2019] _alt_domains='no'
[Tue Oct  1 01:53:31 CST 2019] Using config home:/root/.acme.sh
[Tue Oct  1 01:53:31 CST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Oct  1 01:53:31 CST 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Oct  1 01:53:31 CST 2019] DOMAIN_PATH='/root/.acme.sh/52xiuyixiu.com'
[Tue Oct  1 01:53:31 CST 2019] 'nginx:' does not contain 'dns'
[Tue Oct  1 01:53:31 CST 2019] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Tue Oct  1 01:53:31 CST 2019] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Tue Oct  1 01:53:31 CST 2019] GET
[Tue Oct  1 01:53:31 CST 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Oct  1 01:53:31 CST 2019] timeout=
[Tue Oct  1 01:53:31 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.bMJDVZ3JO2  -g '
[Tue Oct  1 01:53:33 CST 2019] ret='0'
[Tue Oct  1 01:53:33 CST 2019] response='{
  "iJJ9rUw6buQ": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Tue Oct  1 01:53:33 CST 2019] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Tue Oct  1 01:53:33 CST 2019] ACME_NEW_AUTHZ
[Tue Oct  1 01:53:33 CST 2019] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Oct  1 01:53:33 CST 2019] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Tue Oct  1 01:53:33 CST 2019] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Tue Oct  1 01:53:33 CST 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Tue Oct  1 01:53:33 CST 2019] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Oct  1 01:53:33 CST 2019] ACME_VERSION='2'
[Tue Oct  1 01:53:33 CST 2019] Le_NextRenewTime
[Tue Oct  1 01:53:33 CST 2019] _on_before_issue
[Tue Oct  1 01:53:33 CST 2019] _chk_main_domain='52xiuyixiu.com'
[Tue Oct  1 01:53:33 CST 2019] _chk_alt_domains
[Tue Oct  1 01:53:33 CST 2019] 'nginx:' does not contain 'no'
[Tue Oct  1 01:53:33 CST 2019] Le_LocalAddress
[Tue Oct  1 01:53:33 CST 2019] d='52xiuyixiu.com'
[Tue Oct  1 01:53:33 CST 2019] Check for domain='52xiuyixiu.com'
[Tue Oct  1 01:53:33 CST 2019] _currentRoot='nginx:'
[Tue Oct  1 01:53:33 CST 2019] d
[Tue Oct  1 01:53:33 CST 2019] 'nginx:' does not contain 'apache'
[Tue Oct  1 01:53:33 CST 2019] _saved_account_key_hash='v3SzYT86hrmqDC2Lfu7C2h6fj3UHjUXdw9NtXZNKbcg='
[Tue Oct  1 01:53:33 CST 2019] _saved_account_key_hash is not changed, skip register account.
[Tue Oct  1 01:53:33 CST 2019] Read key length:
[Tue Oct  1 01:53:33 CST 2019] _createcsr
[Tue Oct  1 01:53:33 CST 2019] domain='52xiuyixiu.com'
[Tue Oct  1 01:53:33 CST 2019] domainlist
[Tue Oct  1 01:53:33 CST 2019] csrkey='/root/.acme.sh/52xiuyixiu.com/52xiuyixiu.com.key'
[Tue Oct  1 01:53:33 CST 2019] csr='/root/.acme.sh/52xiuyixiu.com/52xiuyixiu.com.csr'
[Tue Oct  1 01:53:33 CST 2019] csrconf='/root/.acme.sh/52xiuyixiu.com/52xiuyixiu.com.csr.conf'
[Tue Oct  1 01:53:33 CST 2019] Single domain='52xiuyixiu.com'
[Tue Oct  1 01:53:33 CST 2019] _is_idn_d='52xiuyixiu.com'
[Tue Oct  1 01:53:33 CST 2019] _idn_temp
[Tue Oct  1 01:53:33 CST 2019] _is_idn_d='52xiuyixiu.com'
[Tue Oct  1 01:53:33 CST 2019] _idn_temp
[Tue Oct  1 01:53:33 CST 2019] _csr_cn='52xiuyixiu.com'
[Tue Oct  1 01:53:33 CST 2019] Getting domain auth token for each domain
[Tue Oct  1 01:53:33 CST 2019] _is_idn_d='52xiuyixiu.com'
[Tue Oct  1 01:53:33 CST 2019] _idn_temp
[Tue Oct  1 01:53:33 CST 2019] d
[Tue Oct  1 01:53:33 CST 2019] _identifiers='{"type":"dns","value":"52xiuyixiu.com"}'
[Tue Oct  1 01:53:33 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Oct  1 01:53:33 CST 2019] payload='{"identifiers": [{"type":"dns","value":"52xiuyixiu.com"}]}'
[Tue Oct  1 01:53:33 CST 2019] RSA key
[Tue Oct  1 01:53:33 CST 2019] Get nonce with HEAD. ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Oct  1 01:53:33 CST 2019] HEAD
[Tue Oct  1 01:53:33 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Oct  1 01:53:33 CST 2019] body
[Tue Oct  1 01:53:33 CST 2019] _postContentType='application/jose+json'
[Tue Oct  1 01:53:33 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.b6P19DpA1e  -g  -I  '
[Tue Oct  1 01:53:34 CST 2019] _ret='0'
[Tue Oct  1 01:53:34 CST 2019] _headers='HTTP/1.1 200 OK
Server: nginx
Date: Mon, 30 Sep 2019 17:53:34 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001vO6x-qqplicLuKzdMqWH7AmTDFU6V59z2MGEx5qHk4g
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
'
[Tue Oct  1 01:53:34 CST 2019] _CACHED_NONCE='0001vO6x-qqplicLuKzdMqWH7AmTDFU6V59z2MGEx5qHk4g'
[Tue Oct  1 01:53:34 CST 2019] nonce='0001vO6x-qqplicLuKzdMqWH7AmTDFU6V59z2MGEx5qHk4g'
[Tue Oct  1 01:53:34 CST 2019] POST
[Tue Oct  1 01:53:34 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Oct  1 01:53:34 CST 2019] body='{"protected": "eyJub25jZSI6ICIwMDAxdk82eC1xcXBsaWNMdUt6ZE1xV0g3QW1UREZVNlY1OXoyTUdFeDVxSGs0ZyIsICJ1cmwiOiAiaHR0cHM6Ly9hY
21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvbmV3LW9yZGVyIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC82Nz
kyNDYyMyJ9", "payload": "eyJpZGVudGlmaWVycyI6IFt7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6IjUyeGl1eWl4aXUuY29tIn1dfQ", "signature": "dCD6U9CjWodAMV95IpuqUKNfDPDLXH8eElvH4
RhDxdMbWqd5cuD-uLrGKQ-PkBjCXHzGVsm3HxAPd8F2jJCXkUXgegCu91Pg9z_gbchocOyWoXtbkUEryXdwdFJ3Zo_C8u3cJrcpoLUnzLXFa7gcRqEOfLahQ3serxzVMNc_wUTwuSaDrt3_KfROGFju6dWKtM
SzIqn0CvHK1vKKJBLM6RMosXlCrnECLMqaHXvr71QYtj5aRtFJq1Rn8xEGhTEWyTRlbBuph51DpvhVABf_QJNFCVK3gP1pQ6OjOp132hWLf_SvDWI1GVPjMzPMJ5Uf1jednqRk1mL968ZciXJx3A"}'
[Tue Oct  1 01:53:34 CST 2019] _postContentType='application/jose+json'
[Tue Oct  1 01:53:34 CST 2019] Http already initialized.
[Tue Oct  1 01:53:34 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.b6P19DpA1e  -g '
[Tue Oct  1 01:53:35 CST 2019] _ret='0'
[Tue Oct  1 01:53:35 CST 2019] responseHeaders='HTTP/1.1 201 Created
Server: nginx
Date: Mon, 30 Sep 2019 17:53:35 GMT
Content-Type: application/json
Content-Length: 343
Connection: keep-alive
Boulder-Requester: 67924623
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/67924623/1192060223
Replay-Nonce: 0001MCZ0b4EqMbfRsKkvqJ1lnIOA-LJn--DCV8x-1wmauuM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
'
[Tue Oct  1 01:53:35 CST 2019] code='201'
[Tue Oct  1 01:53:35 CST 2019] original='{
  "status": "pending",
  "expires": "2019-10-07T17:53:35.781811536Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "52xiuyixiu.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/572293242"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/67924623/1192060223"
}'
[Tue Oct  1 01:53:35 CST 2019] response='{"status":"pending","expires":"2019-10-07T17:53:35.781811536Z","identifiers":[{"type":"dns","value":"52xiuyixiu.com"
}],"authorizations":["https://acme-v02.api.letsencrypt.org/acme/authz-v3/572293242"],"finalize":"https://acme-v02.api.letsencrypt.org/acme/finalize/67924623/
1192060223"}'
[Tue Oct  1 01:53:35 CST 2019] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/67924623/1192060223'
[Tue Oct  1 01:53:35 CST 2019] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/67924623/1192060223'
[Tue Oct  1 01:53:35 CST 2019] _authorizations_seg='https://acme-v02.api.letsencrypt.org/acme/authz-v3/572293242'
[Tue Oct  1 01:53:35 CST 2019] _authz_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/572293242'
[Tue Oct  1 01:53:35 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/572293242'
[Tue Oct  1 01:53:35 CST 2019] payload
[Tue Oct  1 01:53:35 CST 2019] Use cached jwk for file: /root/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
[Tue Oct  1 01:53:35 CST 2019] Use _CACHED_NONCE='0001MCZ0b4EqMbfRsKkvqJ1lnIOA-LJn--DCV8x-1wmauuM'
[Tue Oct  1 01:53:35 CST 2019] nonce='0001MCZ0b4EqMbfRsKkvqJ1lnIOA-LJn--DCV8x-1wmauuM'
[Tue Oct  1 01:53:35 CST 2019] POST
[Tue Oct  1 01:53:35 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/572293242'
[Tue Oct  1 01:53:36 CST 2019] body='{"protected": "eyJub25jZSI6ICIwMDAxTUNaMGI0RXFNYmZSc0trdnFKMWxuSU9BLUxKbi0tRENWOHgtMXdtYXV1TSIsICJ1cmwiOiAiaHR0cHM6Ly9hY
21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYXV0aHotdjMvNTcyMjkzMjQyIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbW
UvYWNjdC82NzkyNDYyMyJ9", "payload": "", "signature": "BLiKcs5ThzeOclZtB9spiJAP71ZQsIJQuWjPyr6HYKKH34p9LQYtR1ZLNwoSC5rA7YrHWNnFmCI2RaEHLMNiwmE6ke69XzsTNq9TW1k
69tlWNcUzBpEvkzxbZ7oZkiu1HatWRSwkin4qt97G_DUDf0W44mL1jl955AQnwFMBJCvmYFb_4bGL0LcU6WXiDOHbQkCOw72sdW-7Xcj0bxZ-OpoQajcSjYzzW42NmMvodfh7KEbchnZod9O05pLxoxOq_Syo
EzJn1X83AKVG_wl7-a15i4NByFuwtzY_krQIk4JA5B2UbfAQRsK1uJZJKSzXGsYIGT91Khp8HY4Hd6Xjkg"}'
[Tue Oct  1 01:53:36 CST 2019] _postContentType='application/jose+json'
[Tue Oct  1 01:53:36 CST 2019] Http already initialized.
[Tue Oct  1 01:53:36 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.b6P19DpA1e  -g '
[Tue Oct  1 01:53:37 CST 2019] _ret='0'
[Tue Oct  1 01:53:37 CST 2019] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Date: Mon, 30 Sep 2019 17:53:36 GMT
Content-Type: application/json
Content-Length: 789
Connection: keep-alive
Boulder-Requester: 67924623
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001EPnlX_a97YMVLnFy2HvB-71XIGwxr-eNBtu_jk7d3uA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
'
[Tue Oct  1 01:53:37 CST 2019] code='200'
[Tue Oct  1 01:53:37 CST 2019] original='{
  "identifier": {
    "type": "dns",
    "value": "52xiuyixiu.com"
  },
  "status": "pending",
  "expires": "2019-10-07T17:53:35Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A",
      "token": "57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/uJUVew",
      "token": "57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/7jD_8Q",
      "token": "57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"
    }
  ]
}'
[Tue Oct  1 01:53:37 CST 2019] response='{"identifier":{"type":"dns","value":"52xiuyixiu.com"},"status":"pending","expires":"2019-10-07T17:53:35Z","challenge
s":[{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A","token":"57CfDwYAED1pzcJTMCZDEAaT66s3mdQ
egw4PhMBCAj4"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/uJUVew","token":"57CfDwYAED1pzcJTMCZDE
AaT66s3mdQegw4PhMBCAj4"},{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/7jD_8Q","token":"57CfDw
YAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"}]}'
[Tue Oct  1 01:53:37 CST 2019] response='{"identifier":{"type":"dns","value":"52xiuyixiu.com"},"status":"pending","expires":"2019-10-07T17:53:35Z","challenge
s":[{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A","token":"57CfDwYAED1pzcJTMCZDEAaT66s3mdQ
egw4PhMBCAj4"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/uJUVew","token":"57CfDwYAED1pzcJTMCZDE
AaT66s3mdQegw4PhMBCAj4"},{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/7jD_8Q","token":"57CfDw
YAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"}]}'
[Tue Oct  1 01:53:37 CST 2019] _d='52xiuyixiu.com'
[Tue Oct  1 01:53:37 CST 2019] _authorizations_map='52xiuyixiu.com,{"identifier":{"type":"dns","value":"52xiuyixiu.com"},"status":"pending","expires":"2019-1
0-07T17:53:35Z","challenges":[{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A","token":"57CfD
wYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/uJUVew","tok
en":"57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"},{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/5722932
42/7jD_8Q","token":"57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"}]}
'
[Tue Oct  1 01:53:37 CST 2019] d='52xiuyixiu.com'
[Tue Oct  1 01:53:37 CST 2019] Getting webroot for domain='52xiuyixiu.com'
[Tue Oct  1 01:53:37 CST 2019] _w='nginx:'
[Tue Oct  1 01:53:37 CST 2019] _currentRoot='nginx:'
[Tue Oct  1 01:53:37 CST 2019] _is_idn_d='52xiuyixiu.com'
[Tue Oct  1 01:53:37 CST 2019] _idn_temp
[Tue Oct  1 01:53:37 CST 2019] response='{"identifier":{"type":"dns","value":"52xiuyixiu.com"},"status":"pending","expires":"2019-10-07T17:53:35Z","challenge
s":[{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A","token":"57CfDwYAED1pzcJTMCZDEAaT66s3mdQ
egw4PhMBCAj4"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/uJUVew","token":"57CfDwYAED1pzcJTMCZDE
AaT66s3mdQegw4PhMBCAj4"},{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/7jD_8Q","token":"57CfDw
YAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"}]}'
[Tue Oct  1 01:53:37 CST 2019] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A","token"
:"57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"'
[Tue Oct  1 01:53:37 CST 2019] token='57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4'
[Tue Oct  1 01:53:37 CST 2019] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A'
[Tue Oct  1 01:53:37 CST 2019] keyauthorization='57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4.zpfuIzc--2HOPZYO9w6-llKdc38NfogKJzoqOOw3N3c'
[Tue Oct  1 01:53:37 CST 2019] dvlist='52xiuyixiu.com#57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4.zpfuIzc--2HOPZYO9w6-llKdc38NfogKJzoqOOw3N3c#https://acme-v0
2.api.letsencrypt.org/acme/chall-v3/572293242/geg67A#http-01#nginx:'
[Tue Oct  1 01:53:37 CST 2019] d
[Tue Oct  1 01:53:37 CST 2019] vlist='52xiuyixiu.com#57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4.zpfuIzc--2HOPZYO9w6-llKdc38NfogKJzoqOOw3N3c#https://acme-v02
.api.letsencrypt.org/acme/chall-v3/572293242/geg67A#http-01#nginx:,'
[Tue Oct  1 01:53:37 CST 2019] d='52xiuyixiu.com'
[Tue Oct  1 01:53:37 CST 2019] ok, let's start to verify
[Tue Oct  1 01:53:37 CST 2019] Verifying: 52xiuyixiu.com
[Tue Oct  1 01:53:37 CST 2019] d='52xiuyixiu.com'
[Tue Oct  1 01:53:37 CST 2019] keyauthorization='57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4.zpfuIzc--2HOPZYO9w6-llKdc38NfogKJzoqOOw3N3c'
[Tue Oct  1 01:53:37 CST 2019] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A'
[Tue Oct  1 01:53:37 CST 2019] _currentRoot='nginx:'
[Tue Oct  1 01:53:37 CST 2019] Nginx mode for domain:52xiuyixiu.com
[Tue Oct  1 01:53:37 CST 2019] _croot='nginx:'
[Tue Oct  1 01:53:37 CST 2019] _start_f
[Tue Oct  1 01:53:37 CST 2019] find start conf from nginx command
[Tue Oct  1 01:53:37 CST 2019] NGINX_CONF
[Tue Oct  1 01:53:37 CST 2019] NGINX_CONF
[Tue Oct  1 01:53:37 CST 2019] Can not find nginx conf.
[Tue Oct  1 01:53:37 CST 2019] pid
[Tue Oct  1 01:53:37 CST 2019] No need to restore nginx, skip.
[Tue Oct  1 01:53:37 CST 2019] _clearupdns
[Tue Oct  1 01:53:37 CST 2019] dns_entries
[Tue Oct  1 01:53:37 CST 2019] skip dns.
[Tue Oct  1 01:53:37 CST 2019] _on_issue_err
[Tue Oct  1 01:53:37 CST 2019] Please add '--debug' or '--log' to check more details.
[Tue Oct  1 01:53:37 CST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Tue Oct  1 01:53:37 CST 2019] _chk_vlist='52xiuyixiu.com#57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4.zpfuIzc--2HOPZYO9w6-llKdc38NfogKJzoqOOw3N3c#https://acm
e-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A#http-01#nginx:,'
[Tue Oct  1 01:53:37 CST 2019] start to deactivate authz
[Tue Oct  1 01:53:37 CST 2019] Trigger domain validation.
[Tue Oct  1 01:53:37 CST 2019] _t_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A'
[Tue Oct  1 01:53:37 CST 2019] _t_key_authz='57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4.zpfuIzc--2HOPZYO9w6-llKdc38NfogKJzoqOOw3N3c'
[Tue Oct  1 01:53:37 CST 2019] _t_vtype
[Tue Oct  1 01:53:37 CST 2019] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A'
[Tue Oct  1 01:53:37 CST 2019] payload='{}'
[Tue Oct  1 01:53:37 CST 2019] Use cached jwk for file: /root/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
[Tue Oct  1 01:53:37 CST 2019] Use _CACHED_NONCE='0001EPnlX_a97YMVLnFy2HvB-71XIGwxr-eNBtu_jk7d3uA'
[Tue Oct  1 01:53:37 CST 2019] nonce='0001EPnlX_a97YMVLnFy2HvB-71XIGwxr-eNBtu_jk7d3uA'
[Tue Oct  1 01:53:37 CST 2019] POST
[Tue Oct  1 01:53:37 CST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A'
[Tue Oct  1 01:53:37 CST 2019] body='{"protected": "eyJub25jZSI6ICIwMDAxRVBubFhfYTk3WU1WTG5GeTJIdkItNzFYSUd3eHItZU5CdHVfams3ZDN1QSIsICJ1cmwiOiAiaHR0cHM6Ly9hY
21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvY2hhbGwtdjMvNTcyMjkzMjQyL2dlZzY3QSIsICJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm
9yZy9hY21lL2FjY3QvNjc5MjQ2MjMifQ", "payload": "e30", "signature": "DiYDTiwYdGtVc6dIibe_5Y0DJw4OqI0x6DFc1DKDWjOuCAFzO2tApDPLNX84LNDY3ozHkK-xO31tFNzi0EldlMD9dx
kTgW2L-9H6kBDk3Jbl6ogPBrpg3RovvhK2TYchKJDWb0Ymz4qcTO4jYfrogk-GJJthoH-OkYPWwHeqzQ3HiUqZMCe4vld7-dguAIueJnm_dq2vVcQvxdLvfN3_1YBEt7RWJrbFdq84BAaXXLb3pBV4fB9QjJ5
KVQZGa0i6jjTEFSqzQDfAUZTyS3G65g_wvLuseaQCVLa1SIAD74PIT1IUXV2DU8_DCa7cAbkgwkyjW5cGgu6nfY5en6wbng"}'
[Tue Oct  1 01:53:37 CST 2019] _postContentType='application/jose+json'
[Tue Oct  1 01:53:37 CST 2019] Http already initialized.
[Tue Oct  1 01:53:37 CST 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.b6P19DpA1e  -g '
[Tue Oct  1 01:53:39 CST 2019] _ret='0'
[Tue Oct  1 01:53:39 CST 2019] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Date: Mon, 30 Sep 2019 17:53:38 GMT
Content-Type: application/json
Content-Length: 184
Connection: keep-alive
Boulder-Requester: 67924623
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Link: <https://acme-v02.api.letsencrypt.org/acme/authz-v3/572293242>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A
Replay-Nonce: 0002nS0WWN0pHjkjKJp-TZHe3Htyc_hxv6d_Lljkx-aiPPY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
'
[Tue Oct  1 01:53:39 CST 2019] code='200'
[Tue Oct  1 01:53:39 CST 2019] original='{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A",
  "token": "57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"
}'
[Tue Oct  1 01:53:39 CST 2019] response='{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/572293242/geg67A","to
ken":"57CfDwYAED1pzcJTMCZDEAaT66s3mdQegw4PhMBCAj4"}'
[Tue Oct  1 01:53:39 CST 2019] socat doesn't exists.
[Tue Oct  1 01:53:39 CST 2019] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2k-fips  26 Jan 2017
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.10.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
configure arguments:
socat:

**Comment by Neilpang** [comment]
nginx 模式可以指定 nginx conf 的位置:

https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert#8-nginx-mode
