### ISSUE TITLE
DNS entry cannot be veryfied.

### ISSUE THREAD

**Issue by AndreasTheDead** [Neilpang/acme.sh#2524]
[log.txt](https://github.com/Neilpang/acme.sh/files/3691070/log.txt)

Today i tryed this script for the first time and i run again this error, i have seen the other reports but every one endet with a wich for the debug 2 log.

The TXT hast the debug output. 

but first i want to say thank you for this programm.

After the upoodate the output is the same.

**Comment by Neilpang** [comment]
why is there `duckdns.org` in the response ?

```sh
[Fr 4. Okt 16:49:43 CEST 2019] response='{"Status": 0,"TC": false,"RD": true, "RA": true, "AD": false,"CD": false,"Question":[{"name": "_acme-challenge.[mydomain].de.", "type": 16}],"Answer":[{"name": "_acme-challenge.[mydomain].de.", "type": 5, "TTL": 9978, "data": "[mydomain].duckdns.org (a Cname entry)."},{"name": "[mydomain].duckdns.org (a Cname entry).", "type": 16, "TTL": 48, "data": "\"\""}]}'
[Fr 4. Okt 16:49:43 CEST 2019] _answers='"Answer":[
"name": "_acme-challenge.[mydomain].de.", "type": 5, "TTL": 9978, "data": "[mydomain].duckdns.org (a Cname entry)."
,
"name": "[mydomain].duckdns.org (a Cname entry).", "type": 16, "TTL": 48, "data": "\"\""
]'
```

check your domain settings, remove all the `_acme-challenge.[mydomain].de` records.

**Comment by AndreasTheDead** [comment]
The Duckdns entry is my * entry of the domain.

https://mxtoolbox.com/SuperTool.aspx?action=txt says there are only the both _acme-challenge. records.

that are my hole dns records.

![image](https://user-images.githubusercontent.com/16037934/66218871-5ed04300-e6ca-11e9-9e51-428d5af1e2b2.png)

**Comment by Neilpang** [comment]
remove the `*` entry.

There is a conflict between the CNAME and TXT record.

If a subdomain is CNAMEed to another domain,  the dns resolver will follow the CNAME to get txt record.
