### ISSUE TITLE
Fetch agreement dynamically

### ISSUE THREAD

**Issue by nihilus** [Neilpang/acme.sh#253]
Agreement should be fetched like this dynamically:
`curl -I ${DEFAULT_CA}/terms 2>/dev/null | grep "Location:" | awk '{print $2}' | tr -d '\r\n'`

**Comment by Neilpang** [comment]
HI, @nihilus 
Good catch.

According to the acme protocol:

https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#directory

The agreement should be : `${DEFAULT_CA}/terms` .

But it seems that, the current boulder doesn't follow the protocol at: https://acme-v01.api.letsencrypt.org/directory

Let's keep this issue open, and see what we can do in future.

Thanks.

**Comment by nihilus** [comment]
@Neilpang Please note that when using acme.sh in an embedded environment this kind of thing is crucial.

**Comment by Neilpang** [comment]
@nihilus  what do you mean by "crucial" ?

**Comment by nihilus** [comment]
@Neilpang That it will break end-users experience when trying to auto-magically renew the certificates on the routers. Hence they would need a firmware upgrade.

**Comment by Neilpang** [comment]
@nihilus   
Let me think about it.

**Comment by nihilus** [comment]
Thx! This is perfect since we going to release in a couple of weeks!
