### ISSUE TITLE
HTTP proxy mode

### ISSUE THREAD

**Issue by strarsis** [Neilpang/acme.sh#2535]
@Neilpang: Example scenario: On an IPv4 NAT, port 80 is forwarded to a networked device with limited customizability, e.g. a webcam (that supports HTTPS certificates).
acme.sh can't perform an automatic signing or renewal of a cert using the HTTP-01 validation method because the NAT forwards the port (and the HTTP-01 validation method forces the usage of the HTTP standard port 80) to the device and not a system that can run acme.sh, like a Raspberry Pi.

As a solution, acme.sh could be a very lightweight proxy between the device and the NAT, so the NAT can forward the port 80 to the acme.sh script that in turn proxies (just forwards everything non-ACME challenge related, like a dumb proxy) all requests to the networked device.
Now the HTTP-01 challenge can be performed by the ACME server in an automated way.
As an added bonus, the acme.sh script could even add HTTPS support to devices that don't support HTTPS / installing custom HTTPS certificates.

**Comment by Neilpang** [comment]
>> As a solution, acme.sh could be a very lightweight proxy between the device and the NAT,

No,  you can run a nginx proxy yourself.  Forward the ACME challenge to acme.sh, and forward all the other to your device.

Anyway, There are dns mode or dns alias mode, not only http-01 mode.

https://github.com/Neilpang/acme.sh/wiki/dnsapi
https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode
