### ISSUE TITLE
Report bugs to freedns dns api

### ISSUE THREAD

**Issue by master-nevi** [Neilpang/acme.sh#2536]
Add support for Synology routers while using [dnsapi/dns_freedns.sh](https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_freedns.sh). Synology router scripting stacks do not have a version of the "tr" command line utility that supports character class representation option i.e. the "[:space:]" :

`tr -d "[:space:]"` should be replaced with `tr -d "\r\n"` inside of [dnsapi/dns_freedns.sh](https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_freedns.sh) for better support across embedded linux systems and routers.

Existing good usage:
https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_freedns.sh#L161

Usages to replace:
https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_freedns.sh#L306
https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_freedns.sh#L352

Steps to reproduce
------------------
Use a Synology router to run acme.sh

Debug log
-----------------
The script silently fails and simply doesn't parse the freedns web page correctly.

**Comment by master-nevi** [comment]
I have addressed this issue myself in this pull request: https://github.com/Neilpang/acme.sh/pull/2537

**Comment by dkerr64** [comment]
This should be updated to also remove tabs and spaces as well, and maybe even vertical tabs and form feeds.  While things may be working just fine now, the subsequent greps and seds assume that spaces have been removed.  FreeDNS does not presently have spaces in places that the code is sensitive to, but if that changed in the future this would fail.  Hence if "[:space:]" won't work then I would replace with " \r\n\t\v\f" (note blank space within the string"
David

**Comment by dkerr64** [comment]
Correction to my previous comment.  You DO NEED to explicitly have a space character in the string as there ARE spaces that need to be removed for later greps to work.  I recommend reverting the pull request #2537 and replacing the tr string with " \r\n\t\v\f" (note blank space within the string)

**Comment by dkerr64** [comment]
@Neilpang please close this issue so that no one else adds bug reports relating to FreeDNS here.  Bug reports should be directed to issue #2305
Thanks
David
