### ISSUE TITLE
nonfunctional crontab

### ISSUE THREAD

**Issue by blau** [Neilpang/acme.sh#254]
First, thank you for this script. I use it on a Debian Jessie server. Installed and configured about 3 months ago via: 

    curl https://get.acme.sh | sh

It failed to renew the certificates. The crontab is broken because of doublequotes: 

    0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null

acme.sh.env is as follows:

    LE_WORKING_DIR="/root/.acme.sh"
    alias acme.sh="/root/.acme.sh/acme.sh"
    export LE_WORKING_DIR="/root/.acme.sh"

Reinstalling via curl reinserts the same broken crontab line.

**Comment by Neilpang** [comment]
Hi, @blau 

Here is my crontab:

```
0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
```

It's same with yours,  but it works for me.

Can you please run it manually:
```
root@adm:~# "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"
```

Tell me what is happening.

**Comment by blau** [comment]
It runs fine. Let me check if my crontab is actually executed by the system.

**Comment by blau** [comment]
The crontab for root is in place and gets executed at the planned times. 
If I put the default acme.sh line (with quotes) it works command line and from crontab. I modified it to log to a file:

    0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /var/log/acme.sh.log 2>&1

So my issue seems to be unrelated to your script, namely what happened on my system when in the last week a handful of certs expired, in different days, and none was renewed.

**Comment by Neilpang** [comment]
can you please run `--cron` now?

```
acme.sh  --cron
```

Please add `MAILTO=you@gmail.com`  to your crontab config.

Then if the cron jobs has error,  you will get email notified.

**Comment by blau** [comment]
[Thu Aug  4 15:54:20 CEST 2016] Renew: www.mydomain.net
    [Thu Aug  4 15:54:20 CEST 2016] Skip, Next renewal time is: Sun Oct 23 08:45:16 UTC 2016
    [Thu Aug  4 15:54:20 CEST 2016] Skipped www.mydomain.net

And so on.

**Comment by heldchen** [comment]
that looks ok - the certificate is valid for --days (default: 80) and will only be renewed when this date has been reached, in your case Sun Oct 23 08:45:16 UTC 2016

**Comment by blau** [comment]
Yes, of course. Thank you all for your time, I'll keep my logs monitored.
