### ISSUE TITLE
After renew certificate its not reflect on webpage.

### ISSUE THREAD

**Issue by pan-kaj** [Neilpang/acme.sh#2554]
I have a website. I renew a certificate using --force certificate has been created but not reflect on website.

I execute following command to create and renew the certificate.

./acme.sh --issue --dns dns_azure -d *.myaddressline.com
./acme.sh --install-cert --dns dns_azure -d *.myaddressline.com
./acme.sh --renew --dns dns_azure -d *.myaddressline.com --force

How it can reflect automatically. Or i have to upload certificate manually on server.

Thanks

**Comment by odili** [comment]
I have similar issue, but I noticed that after renew,  the message :
 `Your cert key is in  /root/.acme.sh/domain.com/domain.com.key 
`  
is displayed but the file in that directory is not overwritten; so the old expired file is still there. 
However, other files ; 
`[Tue Nov 19 22:24:35 WAT 2019] Your cert is in  /root/.acme.sh/domain.com/domain.com.cer  
[Tue Nov 19 22:24:35 WAT 2019] The intermediate CA cert is in  /root/.acme.sh/domain.com/ca.cer 
[Tue Nov 19 22:24:35 WAT 2019] And the full chain certs is there:  /root/.acme.sh/domain.com/fullchain.cer `
are properly overwritten.

Plz help. 
Many thanks

**Comment by Neilpang** [comment]
please use `acme.sh --install-cert` command, or `acme.sh --deploy` command.
