### ISSUE TITLE
Config gets overwritten, when requesting two certificates with same root domain

### ISSUE THREAD

**Issue by zuim** [Neilpang/acme.sh#2573]
When requesting two certificates, with the same root domain the first gets overwritten by the second.
Example:
First certificate for: example.com, *.example.com
Second certificate for: example.com, mail.example.com

Then the config of both certificates gets written to .acme.sh/example.com/ overwriting the first certificate. This configuration would be very useful, if certificates with different settings are needed for different services. 

I did not find any way to rename the .acme.sh/example.com folder, (like --cert-name in certbot). All path settings are for the output files, which does not help with this.

**Comment by Neilpang** [comment]
it's a limitation for now.
maybe in future we can support something like `--cert-name`.  but there is no ETA for that.

Thanks.

**Comment by zuim** [comment]
Thanks for the quick answer. Then I'll close this issue.

A workaround is to simply copy the .acme.sh folder to an alternate location, with appropiate home directory setting.
