### ISSUE TITLE
dnsapi broken: uses DoH only

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [Neilpang/acme.sh#2576]
For the "check lookup" ("Checking do.main.name for _acme-challenge.do.main.name"), acme.sh solely relies on two proprietary DoH providers for DNS lookups rather than just using the local resolver.

I can see how this could appear desirable. However, in my setup, this just breaks things.

There should be an option to use standard DNS resolving (i.e. UDP on port 53) instead.

I mitigated the issue by just skipping the "check lookup".

**Comment by Neilpang** [comment]
Using public DoH is just because that  letsencrypt CA is using public dns servers to validate.
To disable ns lool up,  you can use `--dnssleep 180`

```sh
acme.sh --issue -d xxxx  --dns dnsXXXX   --dnssleep  180
```
