### ISSUE TITLE
Two TXT returned for renew (reference previous issue)

### ISSUE THREAD

**Issue by ygator** [Neilpang/acme.sh#2578]
Neil,

I just tried to renew and got 2 TXT records back again.  Here it is fully documented.

> $ ./acme.sh --renew -d example.com --yes-I-know-dns-manual-mode-enough-go-ahead-please
Renew: 'example.com'
Multi domain='DNS:example.com,DNS:*.example.com'
Getting domain auth token for each domain
Getting webroot for domain='example.com'
Getting webroot for domain='*.example.com'
Add the following TXT record:
Domain: '_acme-challenge.example.com'
TXT value: 'ysWnd1uaPhDFrGEAc0UPNBYonC_fMNb5KJ_etEQT_Xc'
Please be aware that you prepend _acme-challenge. before your domain
so the resulting subdomain will be: _acme-challenge.example.com
Add the following TXT record:
Domain: '_acme-challenge.example.com'
TXT value: 'OCg1PLwNBQV7QRK-OEVUbZx0w7HEn89SdI4LgvbEris'
Please be aware that you prepend _acme-challenge. before your domain
so the resulting subdomain will be: _acme-challenge.example.com
Please add the TXT records to the domains, and re-run with --renew.
Please add '--debug' or '--log' to check more details.
See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
The dns manual mode can not renew automatically, you must issue it again manually. You'd better use the other modes instead.

 Can only enter one TXT since they are the same and put in the first one.  Got back TXT is invalid.

> $ ./acme.sh --renew -d example.com --yes-I-know-dns-manual-mode-enough-go-ahead-please
Renew: 'example.com'
Multi domain='DNS:example.com,DNS:*.example.com'
Getting domain auth token for each domain
Verifying: example.com
Success
Verifying: *.example.com
*.example.com:Verify error:Incorrect TXT record
Please add '--debug' or '--log' to check more details.
See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
The dns manual mode can not renew automatically, you must issue it again manually. You'd better use the other modes instead.

Went ahead and switched to the second TXT.

> $ ./acme.sh --renew -d example.com --yes-I-know-dns-manual-mode-enough-go-ahead-please
Renew: 'example.com'
Multi domain='DNS:example.com,DNS:*.example.com'
Getting domain auth token for each domain
Getting webroot for domain='example.com'
Getting webroot for domain='*.example.com'
Add the following TXT record:
Domain: '_acme-challenge.example.com'
TXT value: '1nFkAsxxisATSGguwAAqOs4XDaTSBUVmhImV_MJAHrS'
Please be aware that you prepend _acme-challenge. before your domain
so the resulting subdomain will be: _acme-challenge.example.com
Please add the TXT records to the domains, and re-run with --renew.
Please add '--debug' or '--log' to check more details.
See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
The dns manual mode can not renew automatically, you must issue it again manually. You'd better use the other modes instead.

It gave yet another TXT so I entered that one and did a renew again.

> $ ./acme.sh --renew -d example.com --yes-I-know-dns-manual-mode-enough-go-ahead-please
Renew: 'example.com'
Multi domain='DNS:example.com,DNS:*.example.com'
Getting domain auth token for each domain
example.com is already verified, skip dns-01.
Verifying: *.example.com
Success
Verify finished, start to sign.
Lets finalize the order, Le_OrderFinalize: https://acme-v02.api.letsencrypt.org/acme/finalize/36878460/1459764441
Download cert, Le_LinkCert: https://acme-v02.api.letsencrypt.org/acme/cert/04679786c21b06da541e086bc495e77b2c62
Cert success.
-----BEGIN CERTIFICATE-----

Finally success.  The renew command I am using is the "exact" one given in the link you gave.

_Originally posted by @ygator in https://github.com/Neilpang/acme.sh/issues/2456#issuecomment-551222941_

**Comment by Neilpang** [comment]
Just follow the wiki guide.  If there are 2 txt records,  please add 2 of them all.
