### ISSUE TITLE
Sign failed, finalize code is not 200. [Sun, Nov 17, 2019 15:45:14] {   "type": "urn:ietf:params:acme:error:serverInternal",   "detail": "Error finalizing order",   "status": 500 }

### ISSUE THREAD

**Issue by midy85** [Neilpang/acme.sh#2591]
Hi guys,

Previously I was able to create certificates without any issue. Now I'm getting this error:

Sign failed, finalize code is not 200.
[Sun, Nov 17, 2019 15:45:14] {
  "type": "urn:ietf:params:acme:error:serverInternal",
  "detail": "Error finalizing order",
  "status": 500
}

In debug log there's not shown anything else than these few lines above

acme.sh --issue --dns dns_dyn -d domain.name.eu  --cert-home /cygdrive/c/Resources/Cert/

any help will be appreciated

**Comment by MrBitBucket** [comment]
I am seeing the same error, but am using dynu dns and or simple webroot; have full debug if that's meaningful
```[Sun 17 Nov 15:51:02 GMT 2019] url='https://acme-v02.api.letsencrypt.org/acme/finalize/68463434/1535339037'
[Sun 17 Nov 15:51:02 GMT 2019] payload='{"csr": "MIICkzCCAXsCAQAw.........."}'
[Sun 17 Nov 15:51:02 GMT 2019] POST
[Sun 17 Nov 15:51:02 GMT 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/finalize/68463434/1535339037'
[Sun 17 Nov 15:51:02 GMT 2019] _CURL='curl -L --silent --dump-header /srv/nginx/etc_nginx/certs/acme.sh/data/http.header  -g '
[Sun 17 Nov 15:51:03 GMT 2019] _ret='0'
[Sun 17 Nov 15:51:03 GMT 2019] code='500'
[Sun 17 Nov 15:51:04 GMT 2019] Sign failed, finalize code is not 200.
[Sun 17 Nov 15:51:04 GMT 2019] {
  "type": "urn:ietf:params:acme:error:serverInternal",
  "detail": "Error finalizing order",
  "status": 500
}```

**Comment by Zocker1999NET** [comment]
Got the same error with a fresh install of `acme.sh` from `master`, I use simple webroot too.

**Comment by Zocker1999NET** [comment]
It seems this bug is not specific to acme.sh, see https://community.letsencrypt.org/t/error-finalizing-order/106501 or https://letsencrypt.status.io/

**Comment by midy85** [comment]
Guessing its issue on letsencrypt servers

**Comment by MrBitBucket** [comment]
yes see https://letsencrypt.status.io/

**Comment by midy85** [comment]
Again up and running
