### ISSUE TITLE
Register account staging server

### ISSUE THREAD

**Issue by scorpiorooster** [Neilpang/acme.sh#2595]
I keep ending up with fake certs.  How can I stop registering an account with the staging server?  

acme --debug --force --register-account --use-wget --ca-path /opt/etc/ssl/certs
[Mon Nov 18 12:41:47 MST 2019] Lets find script dir.
[Mon Nov 18 12:41:47 MST 2019] _SCRIPT_='/opt/bin/acme'
[Mon Nov 18 12:41:47 MST 2019] _script='/tmp/mnt/ew/entware/etc/acme/acme.sh'
[Mon Nov 18 12:41:47 MST 2019] _script_home='/tmp/mnt/ew/entware/etc/acme'
[Mon Nov 18 12:41:47 MST 2019] Using config home:/opt/etc/acme
https://github.com/Neilpang/acme.sh
v2.8.2
[Mon Nov 18 12:41:47 MST 2019] Using config home:/opt/etc/acme
[Mon Nov 18 12:41:47 MST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Nov 18 12:41:48 MST 2019] Using config home:/opt/etc/acme
[Mon Nov 18 12:41:48 MST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Nov 18 12:41:48 MST 2019] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Nov 18 12:41:48 MST 2019] Use default length 2048
[Mon Nov 18 12:41:48 MST 2019] length='2048'
[Mon Nov 18 12:41:48 MST 2019] Using config home:/opt/etc/acme
[Mon Nov 18 12:41:48 MST 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Nov 18 12:41:48 MST 2019] Use length 2048
[Mon Nov 18 12:41:48 MST 2019] Using RSA: 2048
[Mon Nov 18 12:41:55 MST 2019] Create account key ok.
[Mon Nov 18 12:41:55 MST 2019] RSA key
[Mon Nov 18 12:41:55 MST 2019] Registering account
[Mon Nov 18 12:41:55 MST 2019] url='https://acme-staging-v02.api.letsencrypt.org/acme/new-acct'
[Mon Nov 18 12:41:55 MST 2019] payload='{"termsOfServiceAgreed": true}'
[Mon Nov 18 12:41:55 MST 2019] HEAD
[Mon Nov 18 12:41:55 MST 2019] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Nov 18 12:41:55 MST 2019] _WGET='wget -q --ca-directory=/opt/etc/ssl/certs  --content-on-error '
[Mon Nov 18 12:41:56 MST 2019] No -i support in sed
[Mon Nov 18 12:41:56 MST 2019] _ret='0'
[Mon Nov 18 12:41:56 MST 2019] POST
[Mon Nov 18 12:41:56 MST 2019] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-acct'
[Mon Nov 18 12:41:56 MST 2019] _WGET='wget -q --ca-directory=/opt/etc/ssl/certs  --content-on-error '
[Mon Nov 18 12:41:56 MST 2019] No -i support in sed
[Mon Nov 18 12:41:56 MST 2019] _ret='0'
[Mon Nov 18 12:41:56 MST 2019] code='201'
[Mon Nov 18 12:41:57 MST 2019] Registered
[Mon Nov 18 12:41:57 MST 2019] _accUri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/11597773'
[Mon Nov 18 12:41:57 MST 2019] Calc CA_KEY_HASH='wj2EnVQ1vGri/Itp5+AMZbCxEvK0k7/yCiN/dkHL/w4='
[Mon Nov 18 12:41:57 MST 2019] ACCOUNT_THUMBPRINT='d-OPGD7V9ZpjuoCDJNlg7hYzm41jgHPJJfaS8KbikLI'

**Comment by FernandoMiguel** [comment]
Just issue a new one with force parameter

**Comment by scorpiorooster** [comment]
I am using --force
command:
acme --debug --force --register-account --use-wget --ca-path /opt/etc/ssl/certs

**Comment by FernandoMiguel** [comment]
I said issue, not register account
