### ISSUE TITLE
Having trouble issuing cert to subdomain - "invalid domain" error

### ISSUE THREAD

**Issue by samteezy** [Neilpang/acme.sh#2600]
Hi all,

I have used acme.sh in the past to issue a cert and a wildcard cert for my subdomain by following both the [wiki instructions](https://github.com/Neilpang/acme.sh/wiki/Synology-NAS-Guide) and some recommendations on [this blog post](https://bbrks.me/synology-nas-tips/#lecerts).

I am in the process of switching domains and am trying to replicate the same thing for the new root domain. However, I cannot seem to get the service to add the txt record in Cloudflare.

I have tried both using CF_TOKEN and CF_KEY, same result.

This is command I'm using:
`./acme.sh --issue -d "home.staylor.net" -d "*.home.staylor.net" --dns "dns_cf" --certpath "$CERT_PATH/cert.pem" --keypath "$CERT_PATH/privkey.pem" --fullchainpath "$CERT_PATH/fullchain.pem" --capath "$CERT_PATH/chain.pem" --reloadcmd "/usr/syno/sbin/synoservicectl --reload nginx" --dnssleep 20`

And here is the output - I took out a lot of the stuff in the middle that I thought may have sensitive info. There are no errors or issues I could identify in the removed section.
[Fri Nov 22 11:19:54 EST 2019] Running cmd: issue
[Fri Nov 22 11:19:54 EST 2019] _main_domain='home.staylor.net'
[Fri Nov 22 11:19:54 EST 2019] _alt_domains='*.home.staylor.net'
....
[Fri Nov 22 11:19:58 EST 2019] d='home.staylor.net'
[Fri Nov 22 11:19:58 EST 2019] _d_alias
[Fri Nov 22 11:19:58 EST 2019] txtdomain='_acme-challenge.home.staylor.net'
[Fri Nov 22 11:19:58 EST 2019] txt='l0k8i7WGeH6hJJu1df1Fi7Z3pCDla5jW7bF-c10Kkis'
[Fri Nov 22 11:19:58 EST 2019] d_api='/usr/local/share/acme.sh/dnsapi/dns_cf.sh'
[Fri Nov 22 11:19:58 EST 2019] Found domain api file: /usr/local/share/acme.sh/dnsapi/dns_cf.sh
[Fri Nov 22 11:19:58 EST 2019] Adding txt value: l0k8i7WGeH6hJJu1df1Fi7Z3pCDla5jW7bF-c10Kkis for domain:  _acme-challenge.home.staylor.net
[Fri Nov 22 11:19:58 EST 2019] First detect the root zone
[Fri Nov 22 11:19:58 EST 2019] h='_acme-challenge.home.staylor.net'
[Fri Nov 22 11:19:58 EST 2019] zones?name=_acme-challenge.home.staylor.net
[Fri Nov 22 11:19:58 EST 2019] GET
[Fri Nov 22 11:19:58 EST 2019] url='https://api.cloudflare.com/client/v4/zones?name=_acme-challenge.home.staylor.net'
[Fri Nov 22 11:19:58 EST 2019] timeout=
[Fri Nov 22 11:19:58 EST 2019] _CURL='curl -L --silent --dump-header /var/services/homes/sam/.acme.sh/http.header  -g '
[Fri Nov 22 11:19:59 EST 2019] ret='0'
[Fri Nov 22 11:19:59 EST 2019] h='home.staylor.net'
[Fri Nov 22 11:19:59 EST 2019] zones?name=home.staylor.net
[Fri Nov 22 11:19:59 EST 2019] GET
[Fri Nov 22 11:19:59 EST 2019] url='https://api.cloudflare.com/client/v4/zones?name=home.staylor.net'
[Fri Nov 22 11:19:59 EST 2019] timeout=
[Fri Nov 22 11:19:59 EST 2019] _CURL='curl -L --silent --dump-header /var/services/homes/sam/.acme.sh/http.header  -g '
[Fri Nov 22 11:19:59 EST 2019] ret='0'
[Fri Nov 22 11:19:59 EST 2019] h='staylor.net'
[Fri Nov 22 11:19:59 EST 2019] zones?name=staylor.net
[Fri Nov 22 11:19:59 EST 2019] GET
[Fri Nov 22 11:19:59 EST 2019] url='https://api.cloudflare.com/client/v4/zones?name=staylor.net'
[Fri Nov 22 11:19:59 EST 2019] timeout=
[Fri Nov 22 11:19:59 EST 2019] _CURL='curl -L --silent --dump-header /var/services/homes/sam/.acme.sh/http.header  -g '
[Fri Nov 22 11:20:00 EST 2019] ret='0'
[Fri Nov 22 11:20:00 EST 2019] h='net'
[Fri Nov 22 11:20:00 EST 2019] zones?name=net
[Fri Nov 22 11:20:00 EST 2019] GET
[Fri Nov 22 11:20:00 EST 2019] url='https://api.cloudflare.com/client/v4/zones?name=net'
[Fri Nov 22 11:20:00 EST 2019] timeout=
[Fri Nov 22 11:20:00 EST 2019] _CURL='curl -L --silent --dump-header /var/services/homes/sam/.acme.sh/http.header  -g '
[Fri Nov 22 11:20:00 EST 2019] ret='0'
[Fri Nov 22 11:20:00 EST 2019] h
**[Fri Nov 22 11:20:00 EST 2019] invalid domain
[Fri Nov 22 11:20:00 EST 2019] Error add txt for domain:_acme-challenge.home.staylor.net
[Fri Nov 22 11:20:00 EST 2019] _on_issue_err
[Fri Nov 22 11:20:00 EST 2019] Please check log file for more details: /var/services/homes/sam/.acme.sh/acme.sh.log**
[Fri Nov 22 11:20:00 EST 2019] url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/22675748/d6t30g'
[Fri Nov 22 11:20:00 EST 2019] payload='{}'
[Fri Nov 22 11:20:00 EST 2019] POST
[Fri Nov 22 11:20:00 EST 2019] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/22675748/d6t30g'
[Fri Nov 22 11:20:00 EST 2019] _CURL='curl -L --silent --dump-header /var/services/homes/sam/.acme.sh/http.header  -g '
[Fri Nov 22 11:20:01 EST 2019] _ret='0'
[Fri Nov 22 11:20:01 EST 2019] code='200'
[Fri Nov 22 11:20:01 EST 2019] url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/22675747/IxKEEA'
[Fri Nov 22 11:20:01 EST 2019] payload='{}'
[Fri Nov 22 11:20:01 EST 2019] POST
[Fri Nov 22 11:20:01 EST 2019] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/22675747/IxKEEA'
[Fri Nov 22 11:20:01 EST 2019] _CURL='curl -L --silent --dump-header /var/services/homes/sam/.acme.sh/http.header  -g '
[Fri Nov 22 11:20:01 EST 2019] _ret='0'
[Fri Nov 22 11:20:01 EST 2019] code='200'
[Fri Nov 22 11:20:01 EST 2019] pid
[Fri Nov 22 11:20:01 EST 2019] No need to restore nginx, skip.
[Fri Nov 22 11:20:01 EST 2019] _clearupdns
[Fri Nov 22 11:20:01 EST 2019] dns_entries
[Fri Nov 22 11:20:02 EST 2019] skip dns.

**Comment by cmsimike** [comment]
FWIW my wildcard let's encrypt requests are failing today:

[Fri Nov 22 08:02:49 PST 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Nov 22 08:02:49 PST 2019] _CURL='curl -L --silent --dump-header /var/etc/acme-client/home/http.header  -g '
[Fri Nov 22 08:02:49 PST 2019] _ret='0'
[Fri Nov 22 08:02:49 PST 2019] Could not get nonce, let's try again.
[Fri Nov 22 08:02:51 PST 2019] Le_OrderFinalize
[Fri Nov 22 08:02:51 PST 2019] Create new order error. Le_OrderFinalize not found. 

Not sure if it's related or not.

Looks like LE was having issues yesterday https://statusgator.com/services/lets-encrypt but obviously today is not yesterday. I haven't had a chance to confirm if LE works when not using this plugin works for anyone yet.

**Comment by samteezy** [comment]
Thanks @cmsimike. I'm not totally confident in this but it appears that my issue has to do with the creation of the txt record so it might be something on Cloudflare's side.

**Comment by cmsimike** [comment]
As an update - looks like the issue was just acme.sh needed an update on my side. Sorry to derail this @samteezy. I will remove my other comment.

**Comment by samteezy** [comment]
I figured mine out too. The issue was that I'd changed my email address associated with my Cloudflare account, and though I'd specified a new one in the environment variables, the old was still saved in ~./acme.sh/account.conf.

Changing that to my new email, worked.
