### ISSUE TITLE
feedback: acme.sh should use authoritative DNS instead of cloudflare

### ISSUE THREAD

**Issue by hdatma** [Neilpang/acme.sh#2612]
The verification fails with the following error:

` *.example.org:Verify error:DNS problem: NXDOMAIN looking up TXT for _acme-challenge.example.org`

I investigated a bit, using this ad-hoc one liner on a separate terminal:

`while :; do dig @[DNSSERVER] -tTXT +short _acme-challenge.example.org; done`

When "DNSSERVER" is the PUBLIC IP of the DOMAIN'S DNS (example.org), I see the new TXT record as soon as acme.sh updates its value into the DNS. So it works!

**However,** when "DNSSERVER" is the ISP's DNS, I see nothing. This is normal, because it takes time for non-authoritative DNSs to update their own copy.

This is how I am using the script:

`./acme.sh --debug --dnssleep 400 --use-wget --staging --force --issue -d "*.example.org" --dns dns_nsd`

I am using 400 because the TXT RR has a refresh of 300, so remote DNSs can pick it up before the verification, assuming they are up to it. This is how the zone is configured:

```
$ORIGIN _acme-challenge.example.org. ;
$TTL 300;
@ IN SOA acme-dns.example.org. _acme-challenge.example.org. ( 2019112702 1200 7200 604800 3600 )
@ IN NS  acme-dns.example.org.
#@ IN TXT "I'm not here"
```

The server is nsd, and it works well. The above zone has no slaves. 

It would be silly to pretend the swift uptake of TXT by all DNS databases of the world, so from my seat it is OK if the ISP's DNS test fails, for example. 

When acme.sh tests the TXT record, it uses "https://cloudflare-dns.com/dns-query". This test may fail, similarly to how the ISP test fails. 

Since the purpose of acme.sh is to serve letsencrypt, I think the DNS test should be done using letsencrypt's own DNS, or the domain's own authoritative DNS. Preferably the latter.

**Comment by Neilpang** [comment]
we need to dns over https (doh) here.
your authoritative DNS server always doens' support doh.

**Comment by hdatma** [comment]
It's a dog biting its own tail. To have DNS over HTTPS you need a certificate, don't you? To authenticate the DNS and its records you need DNSSEC with DANE.
