### ISSUE TITLE
docker and cron, how is it suppose to work ?

### ISSUE THREAD

**Issue by donnib** [Neilpang/acme.sh#2624]
Hi,
I am trying to have a docker container that sits and ocasionally checks for a renewal and if it renews it saves the certificates in a volume that i can access from other places. I thought installing the docker container and using --cron would start the container and check reneweal once in a while but i see it does something then exits so it's a one time deal. What is it that i am missing here ? Is it not like that i should use it ?

/donnib

**Comment by Neilpang** [comment]
if it runs in daemon mode,  the cron is handle automaically.
https://github.com/Neilpang/acme.sh/wiki/Run-acme.sh-in-docker#3-run-acmesh-as-a-docker-daemon
