### ISSUE TITLE
docker container...docker compose

### ISSUE THREAD

**Issue by awgcooper** [Neilpang/acme.sh#2627]
I'm not sure if it's okay to ask simple 'how-to' questions here but it looks like the best place to get the right answer so apologies if I shouldn't do this.

I'm looking to set up an acme.sh docker container which will issue certificates to other containers. I've been working through the following as well as reading previous posts:
https://github.com/Neilpang/acme.sh/wiki/deploy-to-docker-containers
https://github.com/Neilpang/acme.sh/wiki/Run-acme.sh-in-docker#3-run-acmesh-as-a-docker-daemon

My questions about the compose file (https://github.com/Neilpang/acme.sh/wiki/deploy-to-docker-containers#5-all-together-docker-compose-example) are:
1) if the container one to which one is deploying is managing multiple domains what is the best way to manage this? Should one replace the environment section with a .env file. If the answer is yes, what's the most efficient bash (substitution) syntax for the label lines when applied to multiple domains.
2) near the beginning of the compose file there is the label: sh.acme.autoload.domain=example.com
Would that be change to a list corresponding to the different domains such as:
sh.acme.autoload.domain=example1.com
sh.acme.autoload.domain=example2.com
sh.acme.autoload.domain=example3.com
etc
3) the './acmeout' volume: is that the full acme.sh package, all directories.
4) what's the correct cronjob to monitor for renewals - I'm guessing a single cronjob in the container. If so what is it and how does one ensure persistence? Basically is it just there and I don't have to think about it or is some intervention required.
5) Am I correct in saying the one bit of unavoidable manual intervention will be a docker exec command to deploy a certificate for a new domain. In order to do this would I first need to bring the container down, add a new domain in however specified by the answer to my questions 1) & 2) above, bring it back up and then run the command.
6) I use the DNS api method to generate certs. Like with standalone acme.sh which keeps a copy of the exported registrar env. variables, does the container do the same so as to facilitate renwals?
7) That leads to a wider (and my final!) question: does the renewal automatically use the same settings as the initial deployment (e.g. ec-384, wildcard etc) - again like the standalone .conf files in the certs directories.

A very big thank you if I'm able to get all of these answered!!

**Comment by FernandoMiguel** [comment]
For your use case look at traefik which will also issue LE certs for you and load balance your services.
Much easier than using acme.sh

**Comment by Only-explore** [comment]
请一次性解决问题，

**Comment by Neilpang** [comment]
You don't need to write such `sh.acme.autoload.domain=example1.com` variables to the docker-compose file.
Just define them every time you `exec` a command:
https://github.com/Neilpang/acme.sh/wiki/deploy-to-docker-containers#4-lets-deploy-the-cert-now

The variables will be recorded for every cert.  When the certs are renewed, they will be re-deployed one by one.

**Comment by awgcooper** [comment]
Of coure, totally makes sense.  Thank you.
