### ISSUE TITLE
部署七牛云的泛域名时候提示失败

### ISSUE THREAD

**Issue by juukee** [Neilpang/acme.sh#2630]
我使用容器部署docker，然后部署到七牛云的时候提示如下，七牛云平台证书已经上传成功，但是部署失败。
`docker exec acme.sh --deploy -d *.juukee.cn --deploy-hook qiniu`

[Thu Dec 12 16:02:54 UTC 2019] Error in updating domain httpsconf:
[Thu Dec 12 16:02:54 UTC 2019] {"code":612,"error":"no such domain"}

**Comment by zend** [comment]
`export QINIU_CDN_DOMAIN=YOUR.domain.juukee.cn`
