### ISSUE TITLE
Updating keylength doesn't work

### ISSUE THREAD

**Issue by z0rti** [Neilpang/acme.sh#2643]
I created a cert with --issue, forgot to specify --keylength so it is default 2048 
Now i tried to increase the size with '--renew --keylength 4096'
It didn't complain, but the resulting key is still 2048 bits long.
(Bug?/FeatureRequest)

**Comment by Neilpang** [comment]
no,  keylength is not working with renew

**Comment by z0rti** [comment]
Can it be a FeatureRequest then? Or is it not possible at all to change keylength?

**Comment by Neilpang** [comment]
of course, anything can be a feature request.
but it's not working this way for now.
