### ISSUE TITLE
Generate SSL key with apache and custom port failed

### ISSUE THREAD

**Issue by MrDini123** [Neilpang/acme.sh#265]
Hi!

I have a server with two apache webservers. My first webserver is listenning on port 80. It is for config webgui. And I want to install a cert to my second apache, which listens on port 8080. But when I try to generate a key, using `./acme.sh --issue --apache -d mydomain.com`, it says:

```
[snip]
Verify error:Could not connect to http://mydomain.com/.well-known[snip]
```

I tried to change the `-d mydomain.com` to `-d mydomain.com:8080`, but it said a dns error.

And one more thing! The second webserver is on 8080 port, but I have a port forward at the router from local 8080 to external 8086 port... So the webserver accessible from WAN via the 8086 port.

What Can I do?

Thanks a lot!

**Comment by Neilpang** [comment]
@MrDini123 

From the ACME protocol,  the CA server  only connects to your external port 80 or 443 to verify.

Any other port 8080 or 8086 will not work.

In you case, I guess all the external traffic on the external port 80 is forwarded to your first server,  So, you can only issue cert on the first server.

You can use a script to copy the cert from first server to secondary domain:

```
cat  /root/.acme.sh/myreload.sh

scp  "$CERT_PATH"   seconary-server:path/to/domain.cer
scp  "$CERT_KEY_PATH"  seconary-server:path/to/domain.key
scp  "$CERT_FULLCHAIN_PATH"    seconary-server:path/to/fullchain.cer

ssh seconary-server  "service   apache2  reload"

```

Then install the script:
```
acme.sh  --installcert   -d "seconary.domain.com"   --reloadcmd ".  /root/.acme.sh/myreload.sh "
```

Then, when the cert is renewed on the first server, it will be scp to the secondary server.



Another solution, you can use dns api mode to issue cert on any server.

**Comment by MrDini123** [comment]
Thanks for the answer!

Well, the first webserver, as I said, just for configuration. It is only available from local network. My second webserver is, which available from external places.

I think it would be nice to I Can specify a port where the acme look for the .well-know/... path. And not at the default http port (80)... From WAN, I haven't got anything at 80 port, I just have a webserver at 8086 and I Can't move it.

But when I copy this link from the output:

http://mydomain.com/.well-known/acme-challenge/<long hash>

And change the port to 8086 it works.

**Comment by Neilpang** [comment]
ACME  protocol only use 80/443.  no other port.

**Comment by MrDini123** [comment]
Ah, bad news...

And why this verify needed?

Is there any way to solve that?

**Comment by Neilpang** [comment]
>> And why this verify needed?

I don't know,  it's the protocol.   Although it is silly I think.


>> Is there any way to solve that?

You must forward the public external 80 port to your secondary apache server's port.


You can also use dns api mode,  which doesn't use any port.

**Comment by MrDini123** [comment]
Okay! Many thanks. And for this cool script too!

I will look for the acme feature request page and 'll open a ticket to add custom port support.

Sorry for my noobness, but what is dns api? And how Can I use that? I saw at the readme.md, but I Cannot understand how does it working...

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/tree/master/dnsapi

**Comment by MrDini123** [comment]
I saw that:

https://github.com/Neilpang/acme.sh/blob/master/dnsapi/README.md

But in my case, what I have to execute?

**Comment by Neilpang** [comment]
what is the dns server of your domain ?

**Comment by Neilpang** [comment]
BTW,  why not  forward your public 80 port to your secondary server ?

**Comment by MrDini123** [comment]
Because it is a home webdav server. I used a custom port to skip the ip scanning...

And I have domain at noip.com.

**Comment by Neilpang** [comment]
Is  noip.com  free ?

**Comment by MrDini123** [comment]
No. I have a free dynamic dns which is redirected to a bought domain. But I Can use the dynami dns if it is better.

**Comment by Neilpang** [comment]
what is your bought domain dns serve ?  Godaddy ?

**Comment by MrDini123** [comment]
Ahh, sorry, I checked the noip page and it is also a hostname, but it is paid and don't have .noip.org suffix, or .ddns.net, etc...

Nice question, I think it is noip's dns server.

**Comment by MrDini123** [comment]
But I will try to change the port to 80 and hope nobody tries to crack it.

**Comment by Neilpang** [comment]
I have a good solution for you.

On your router, forward  80 port to   9090 port for your secondary server.

Then use standalone mode:

```
acme.sh  --isssue --standalone  -d secondary.domain.com   --httpport  9090
```

**Comment by Neilpang** [comment]
@MrDini123

**Comment by MrDini123** [comment]
I tried the standalone mode, but alson saying:

```
[Fri Aug 19 15:12:41 CEST 2016] Standalone mode server
[Fri Aug 19 15:12:55 CEST 2016] mydomain.com:Verify error:Could not connect to http://mydomain.com/.well-known/acme-challenge/…
```

**Comment by Neilpang** [comment]
Is the public 80 port forwarded to your  internal  9090 port ?

**Comment by MrDini123** [comment]
No, I forwarded 9090 to ext 9090...

But I changed the public port to 80 and the apache plugin also works.

**Comment by Neilpang** [comment]
you just need to  forward the 80 port to 9090.
After the cert is issued,   the 9090 port will be free,  so that no one can scan your port.

**Comment by MrDini123** [comment]
Hi again!

As You said, the 443 port also supported by acme.

So I moved my webserver to port 443. But when I try to generate a key, it says verification error at http://mydomain.com/.well-known.... I tried to change the domain to https://mydomain.com, but it also gives me an error. What Can I do?

**Comment by Neilpang** [comment]
443 port is used only for `--tls` mode.

https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert

**Comment by MrDini123** [comment]
Okay, thanks. I was blind! ;)

And is it works with apache mode, or just with standalone?

**Comment by Neilpang** [comment]
No.
