### ISSUE TITLE
using cloudflare for DNS and execute acme.sh command for certificate，then resulting in an error.

### ISSUE THREAD

**Issue by zhang007z** [Neilpang/acme.sh#2663]
Cloudflare configuration is fine, with CF_Key and CF_Email ----------------------------------------------------------------------------
shell command :
acme.sh -- issue --dns dns_cf -d mydomain.com -d *.mydomain.com --debug 2
------------------------------------------------------------------------------------
resulting in an error: [Fri 1月305日:07:13 CST 2020] Zones? Name=tk & amp; account.id= mymail@mail.com [Fri 1月305日:07:13 CST 2020] GET [Fri 1月305日:07:13 CST 2020] url =' https://api.cloudflare.com/client/v4/zones? n ame = tk & amp; account.id = mymail@mail.com' [Fri 1月305日:07:13 CST 2020] time out = [Fri 1月305日:07:13 CST 2020] Httpareadyinitialized. [Fri 1月305日:07:13 CST 2020]_CURL='curl-L-Silent-dump-header/root/.acme .sh /http.header-Trace-ascii/tmp/tmp.MthAqYkmZj-g' [Fri 1月305日:07:13 CST 2020] Ret ='0' [Fri 1月305日:07:13 CST 2020] Response ='{& quot; success & quot; false,& quot; error & quot;[{& quot; code & quot;0,& quot; quot;m essage & quot;& quot; Actor' com.cloudflare.api.token.6294b824beefe29dfsdf4db3c4359d215e36c' requi res permission' com.cloudflare.api.account.zone.list' to listzones for' com.clo udflare.api.account.mymail@mail.com'& quot;],& quot; messages & quot;[],& quot;& quot; results & quot; null }' [Fri 1月305日:07:13 CST 2020] h **[Fri 1月305日:07:13 CST 2020] invalid domain** **[Fri 1月305日:07:13 CST 2020] Error add txt for domain:_acme- challenge.mydomain.com**
[Fri 1月305日:07:13 CST 2020]_on_issue_err [Fri 1月305日:07:13 CST 2020] Please check log file for more details:/root/.ac me.sh /acme.sh.log ---------------------------------------------------------------------------------

picture:
![ssl证书问题](https://user-images.githubusercontent.com/6176207/72077502-4f4c4000-3332-11ea-9aa0-cb4751edf313.jpg)

cloudflare DNS activation:
![cloudflare添加到域名](https://user-images.githubusercontent.com/6176207/72133740-2624c180-33bd-11ea-9acc-d61c8713f247.jpg)

main problem:
[Fri 1月3日 05:07:13 CST 2020] invalid domain
[Fri 1月3日 05:07:13 CST 2020] Error add txt for domain:_acme-challenge.mydomain.com
Looked at a lot of blog, found that they don't have the question of me, please ask me where is this problem?

**Comment by zhang007z** [comment]
i have solved this issue and generated the certificate via certbot tool, acme.sh still need to continue to improve.

**Comment by Neilpang** [comment]
错误信息很明显, 说你的 api 权限不够.
检查你的 api key 或者 token

**Comment by typoworx-de** [comment]
@Neilpang could you please answer in english to make english users understand how to resolte this?

I'm having the same issue here. I want to migrate from certbot to acme.sh using cloudflare API. But this results in the error given above.

Has there been any recent change in API Token/Key at cloudflare? I created a new API Token for "Acme.sh" with permissions  "Zone.Zone, Zone.DNS" and resources "All zones". I also have my global API-Key. I then entered these credentials into a shell-script:

```
#!/bin/bash
export CF_Account_ID="{CF Global API Key}"
export CF_Token="{CF API Token}"

acme.sh --issue --dns dns_cf $@
```
Which always results in:
```
invalid domain
Error add txt for domain:_acme-challenge.my-domain.de
```

Btw. isn't it possible to setup CF-API Credentials in myaccount.conf somehow?
