### ISSUE TITLE
Adding a subdomain to a certificate when HSTS preload is enabled 

### ISSUE THREAD

**Issue by phonon112358** [Neilpang/acme.sh#2668]
I am using acme.sh on Debian 10 with nginx. 
I issued a certificate for my domain and some subdomains (I can't use dns mode) and added the domain to the HSTS preload list.

Now, I want to add a further subdomain to the certificate. Firstly, I noticed that the http challenge is made against https:// (and not http://). Using the `--debug` mode, I found that there is a ssl problem regarding libcurl (same error message as in https://github.com/Neilpang/acme.sh/issues/994). Using `debug 2`, the problem seems to be that I haven't a certificate for the new subdomain. But that's exactly what I want to issue! 
Hence, I am in some circle: I want to issue a certificate but need a valid and trusted certificate to do this because my domain is on the HSTS preload list...

Do you have any idea what I can do?

**Comment by FernandoMiguel** [comment]
You have to issue a new cert using 
tls-alpn mode

**Comment by Neilpang** [comment]
It doesn't matter at all.
The letsencrypt validation server will ignore the https cert error for validation.

**Comment by phonon112358** [comment]
Ah... I found my failure! I forgot to enable the site/server in nginx! 
Everything works! 
Thanks and sorry!
