### ISSUE TITLE
moving servers - copying .acme/ directory contents ?

### ISSUE THREAD

**Issue by centminmod** [Neilpang/acme.sh#268]
If moving servers, would these steps be ok domain with acme.sh issued letsencrypt cert ?

1. on new server, install acme.sh so it's home would be i.e. /root/.acme.sh
2. on old server transfer site data along with the acme.sh installcert specified path saved letsencrypt ssl certificates

**Comment by heldchen** [comment]
you also need to copy the subdirectories in `/root/.acme.sh ` - those contain the real information about the certificates. the `installcert` path only contains the certificates without their acme.sh metadata.

**Comment by centminmod** [comment]
cheers yeach when i mean copy /root/.acme.sh i mean everything under it subdirectory wise

**Comment by Neilpang** [comment]
@centminmod   Yes,  Correct.

**Comment by centminmod** [comment]
cheers :)
