### ISSUE TITLE
--post-hook issue

### ISSUE THREAD

**Issue by qcybb** [Neilpang/acme.sh#2684]
The contents of --post-hook is never fired.

>  --post-hook : Command to be run after attempting to obtain/renew certificates. No matter the obtain/renew is success or failed.

`30 0 * * * /usr/local/sbin/acme.sh --cron --post-hook /var/db/acme/.acme.sh/acme-email.sh  --home /var/db/acme/.acme.sh`

When I test the file manually, I receive the email immediately.

**Comment by Neilpang** [comment]
`-post-hook`  is only used with `--issue` command.

don't edit the default `crontab`

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/Using-'--pre-hook',-'--post-hook',-'--renew-hook'-and-'--reload-cmd'
