### ISSUE TITLE
dns mode not able to distinguish between ec-256 vs 2048 cert

### ISSUE THREAD

**Issue by centminmod** [Neilpang/acme.sh#270]
if i used ec-256 first for

    acme.sh --issue --dns -d acme9.domain1.com -k ec-256

```
ls -lah /root/.acme.sh/| grep acme9
drwxr-xr-x   2 root root 4.0K Aug 22 21:09 acme9.domain1.com_ecc
```

but then switch to rsa 2048 cert, acme.sh still seems to register and check ecc cert private key/folder etc ?

    acme.sh --issue --dns -d acme9.domain1.com -k 2048

```
/root/.acme.sh/acme.sh --issue --dns -d acme9.domain1.com -k 2048
[Mon Aug 22 22:20:34 UTC 2016] The domain 'acme9.domain1.com' seems to be a ECC domain, please add '--ecc' parameter next time.
[Mon Aug 22 22:20:37 UTC 2016] Skip register account key
[Mon Aug 22 22:20:37 UTC 2016] Creating domain key
[Mon Aug 22 22:20:37 UTC 2016] Domain key exists, do you want to overwrite the key?
[Mon Aug 22 22:20:37 UTC 2016] Add '--force', and try again.
[Mon Aug 22 22:20:37 UTC 2016] Create domain key error.
```

shouldn't `--dns` mode check for ` /root/.acme.sh/acme9.domain1.com_ecc` and ` /root/.acme.sh/acme9.domain1.com` separately dependent on KEYLENGTH set to either ec-256 or 2048 ?

**Comment by Neilpang** [comment]
fixed.   It was my fault to add such logic to increase the compatibility.

**Comment by centminmod** [comment]
excellent thanks @Neilpang :+1:
