### ISSUE TITLE
Domain required for Account key creation?

### ISSUE THREAD

**Issue by theraser** [Neilpang/acme.sh#271]
Hi,

I just tried to use acme.sh to generate just an account key but it requires a domain. I'm not sure if I'm missing something but the given domain seems to be ignored completely (https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L521).
```
# ./acme.sh  --createAccountKey 
[Tue Aug 23 16:13:23 CEST 2016] Creating account key
Usage: acme.sh --createAccountKey -d domain.com [--accountkeylength 2048]
```
Is this by design or a bug?

Best Regards

**Comment by Neilpang** [comment]
fixed.
Sorry, it was a bug.  We used to use the domain in the createAccountKey function,  but later, it's removed.

**Comment by theraser** [comment]
Thanks, it is working now
