### ISSUE TITLE
OVH DNS Integration

### ISSUE THREAD

**Issue by Nosxxx** [Neilpang/acme.sh#272]
May you add support for the OVH API ?
https://api.ovh.com/

I would sponsor this integration.

**Comment by Neilpang** [comment]
Do you mean  using ovh domain api to issue cert ?

**Comment by Nosxxx** [comment]
I mean that issuing certs via dns work like cloudflare. 

I'm sorry for my bad english.

**Comment by Neilpang** [comment]
Ok. I see. 
I will take a look at their api tomorrow.

**Comment by Neilpang** [comment]
Hi, I just checked the ovh api.

But I can not find how to register a domain at ovh.com.

I also tried ove.ie,  but they request my Passport and ID.

Can you please tell me how to register domain there ?

**Comment by Nosxxx** [comment]
You have to buy a Domain there. https://www.ovh.ie/domains/
I can give you the money you need via paypaldonation.

**Comment by Neilpang** [comment]
Yes, I tried ovh.ie,  but but they request my Passport and ID.

Please create a temp account there and register a cheapest domain there.

Then send me your account and password to my email:  info@acme.sh

**Comment by Nosxxx** [comment]
Thanks, i will test it later.

**Comment by Neilpang** [comment]
@Nosxxx   have you tried ?

**Comment by Nosxxx** [comment]
I will try it soon.
I'm sorry, i have some personal problems.

**Comment by Nosxxx** [comment]
I have tested it, the OVH API works great. Thanks you.
