### ISSUE TITLE
Please add the TXT records to the domains, and retry again

### ISSUE THREAD

**Issue by wasas** [Neilpang/acme.sh#277]
系统, centos 6.8
openssl, 1.1.0
域名在 cloudxns.net (服务器在国外)
使用 dns 验证的方式, 报错退出 (Please add the TXT records to the domains, and retry again)

已更改 dnsapi/dns_cx.sh 里 CX_Key="*****" 和 CX_Secret="*****" (同时去除了这两行前的 # )

命令方式:
./acme.sh --issue --dns dns_cx -d xxx.com -d www.xxx.com -d web.xxx.com -d wap.xxx.com

麻烦你了, 谢谢...

**Comment by Neilpang** [comment]
你这应该是没有安装，所以找不到 dnscx 的实现代码 

请按照首页的规则安装    然后再按着这个说明 https://github.com/Neilpang/acme.sh/blob/master/dnsapi/README.md


严格按照使用说明服用，疗效更好 。  不要跳，不要冲进去改代码

**Comment by Neilpang** [comment]
@wasas 
刚刚修复了,  现在不需要安装可以直接使用啦:  f3e4cea34f2c5086aea000a6ba5d67425bbf26b7
