### ISSUE TITLE
--installcert without effect (and no output message) after --issue --dns

### ISSUE THREAD

**Issue by gravsten** [Neilpang/acme.sh#280]
I ran the following:
```
acme.sh --issue --dns dns_gd -d mydomain.com
acme.sh --installcert -d mydomain.com
```

The certs are properly issued, cron job add, and DNS TXT modified, although I have a doubt about the latter: the record name is `_acme-challenge`, not `_acme-challenge.mydomain.com` as the current IETF draft requires.

Anyway, the second command shows no output message whatsoever and my GoDaddy account's cPanel shows no additional certificate (I have a previously existing certificate already installed).

As far as I can tell, the new Let'sEncrypt cert was not properly installed, hence this bug report.

**Comment by gravsten** [comment]
For completion, I have uninstalled the previous certificate (from Comodo) and tried again `acme.sh --installcert -d mydomain.com`, but unfortunately, this didn't help.

This may be an issue of documention: it isn't explained if `--issue --dns dns_gd` (Automatic DNS API integration with GoDaddy) is exclusive of the plain `--issue` command.

**Comment by Neilpang** [comment]
@gravsten 

The `--installcert` is not able to know how is your nginx/apache conf file written.

If you are useing cpanel,  you should set the cert/key to your cpanel.

Then, you should know how your nginx/apache conf is written.

Let's assume it's like:

```
SSL_CERT = /etc/certs/mydomain.cer
SSL_KEY=/etc/certs/mydomain.key
```


Then you can use `--installcert` : 

```
acme.sh  --installcert  --certpath etc/certs/mydomain.cer  --keypath etc/certs/mydomain.key  --reloadcmd  "service apache reload"
```
