### ISSUE TITLE
Support  '--pre-hook', '--post-hook' and '--renew-hook'

### ISSUE THREAD

**Issue by Neilpang** [Neilpang/acme.sh#282]
Support  '--pre-hook', '--post-hook' and '--renew-hook'

When issue or renew certs:

https://certbot.eff.org/docs/using.html#command-line

**Comment by Neilpang** [comment]
fixed b0070f03af98cedd49dbf30e1ddd53f4a2849ed0.

**Comment by centminmod** [comment]
so these can run any ssh based commands ?

**Comment by Neilpang** [comment]
@centminmod 
Yes

**Comment by centminmod** [comment]
thanks !

**Comment by kantharia** [comment]
how to use these hooks ?
