### ISSUE TITLE
DNS API Config

### ISSUE THREAD

**Issue by Nosxxx** [Neilpang/acme.sh#283]
Hey, 
sometimes i have two diffrent accounts for Cloudflare API. 
May there is a chance to add additional API Credentials for the DNS APIs?

**Comment by Rikairchy** [comment]
I had the same question. I just duplicated the CF API file and renamed it dns_cf2 and called that instead of dns_cf

**Comment by Nosxxx** [comment]
I have done the same. 
But settings per Certificate would be a great feature.

**Comment by Neilpang** [comment]
here is an issue: 
https://github.com/Neilpang/acme.sh/issues/799
