### ISSUE TITLE
Whether to provide a parameter to turn off automatic updates certificate？

### ISSUE THREAD

**Issue by isbaseby** [Neilpang/acme.sh#284]
In many cases, a certificate is required after updating to do some work, and sometimes I have written the script better adapted to update the actual situation

The best situation should the user can choose whether to enable automatic updates acme.sh.

**Comment by Neilpang** [comment]
1.  You can remove the crontab task:
```
acme.sh  --uninstallcronjob
```
All the cert will not renewed automatically.

2. If you upgrade acme.sh by `--upgrade` command,  it will not create the cronjob again.

```
acme.sh  --upgrade
```

**Comment by isbaseby** [comment]
@Neilpang Thanks
