### ISSUE TITLE
proposal: use shfmt for all shell files

### ISSUE THREAD

**Issue by mvdan** [Neilpang/acme.sh#286]
I've recently written shfmt, the equivalent of gofmt for bash/shell programs. acme.sh is a pretty active project with lots of contributors, so I think it would benefit from its use.

More info: https://github.com/mvdan/sh

I can tag a release and/or upload binaries to github if that would make it easier to integrate in Travis.

I ran `shfmt -i 2 -l -w .` and these are the diffs. By default it indents with tabs, but it can use any number of spaces like I did there. For now, nothing else is configurable, and I hope to keep it that way.

`git diff` - https://clbin.com/OiuZZ
`git diff -w` - https://clbin.com/dgBOi

If you have any questions or issues, I'm happy to help.

**Comment by centminmod** [comment]
ooh nice this maybe useful to me too - lots of shell scripts/code in play for me too :)

**Comment by mvdan** [comment]
I just released the first version with binaries, in case that helps with testing or integration with CI:

https://github.com/mvdan/sh/releases/tag/v0.1.0

**Comment by mvdan** [comment]
Ping @Neilpang - I can provide a pull request if needed. Adding some CI like Travis would probably make sense to keep the format from breaking with pull requests.

**Comment by Neilpang** [comment]
@mvdan 

Thanks.  That would be great appreciated.

**Comment by mvdan** [comment]
@Neilpang I need you to enable Travis on the repo so that then I can add a `.travis.yml` file to keep the format consistent with pull requests.

**Comment by Neilpang** [comment]
@mvdan 

Travis is enabled.

Thanks.

**Comment by mvdan** [comment]
This is now in master.

**Comment by heldchen** [comment]
awesome, thanks!

**Comment by mvdan** [comment]
@Neilpang by the way, I just realised that you seem to restrict the repo to POSIX Shell and not Bash. You could add `-p` to the `shfmt` calls, this will restrict the parser to only accept POSIX. I just tried `shfmt -p -l -w -i 2 .` on master and it works just fine.

This will help with PRs as any bash features (arrays, `let`, etc) will be parse errors and make CI fail.

**Comment by Neilpang** [comment]
@mvdan 

Thanks. I will try.

**Comment by mvdan** [comment]
@Neilpang this got me to think about detecting `sh` versus `bash`, please give your input on https://github.com/mvdan/sh/issues/48. That could mean `-p` would be unnecessary in this scenario, as all the files are clearly sh and not bash.
