### ISSUE TITLE
Add an Option for OCSP-Must-Staple

### ISSUE THREAD

**Issue by biergaizi** [Neilpang/acme.sh#288]
An extension `OCSP-Must-Staple` is used to ensure that clients always check the certificate against OCSP, and found its way in Let's Encrypt and FireFox. 

Adding a `--ocsp-must-staple` is necessary, you may refer to https://github.com/lukas2511/dehydrated/commit/8e77ba5e02a4b76d3a76a2354f74c0b53ba4fec8 for the implementation.

Basically it is

    if ocsp {
        printf "\n1.3.6.1.5.5.7.1.24=DER:30:03:02:01:05" >> "${tmp_openssl_cnf}"
    }

**Comment by Neilpang** [comment]
https://community.letsencrypt.org/t/improving-revocation-will-lets-encrypt-support-ocsp-must-staple/4334/42

https://github.com/chromium/badssl.com/pull/115/commits/ba03d024d0ea9b6a739ab913708d6fd5e6dae83a

**Comment by itsallinyourhead** [comment]
I tried to get a certificate with DNS manual mode with an existing CSR. That CSR contains `1.3.6.1.5.5.7.1.24 = DER:30:03:02:01:05` but this line is removed in `~/.acme.sh/example.com_ecc/example.com.csr.conf`. So OCSP Must Staple does not work that way.
Even inserting that line into that file does not work, it is also removed after renewing the certificate.

Is there another way to get OCSP Must Staple working?

**Comment by idarlund** [comment]
Why is this feature request closed? I would really like to see ocsp must staple option in acme. cerbot already has this option; https://certbot.eff.org/docs/using.html#certbot-command-line-options

**Comment by Neilpang** [comment]
@idarlund 
It's already supported:   "--ocsp"

**Comment by idarlund** [comment]
afaik --ocsp will staple the certificate, but will it set the must-staple flag?

**Comment by biergaizi** [comment]
@idarlund Please read the issue carefully. GitHub says, **Neilpang closed this *in 0c9546c***, in other words, it has already implemented, as `--ocsp-must-staple`, its short abbreviation is `--ocsp`. I've been using it for two years and it worked without a hitch.
