### ISSUE TITLE
Does the everyday cron job take care of the --installcert functionality by default (copying over the files and reloading the webserver)?

### ISSUE THREAD

**Issue by djvdorp** [Neilpang/acme.sh#290]
First of all, I would like to thank you for your efforts on writing this shell script that allows me to use LetsEncrypt on low-end hardware, amazing work!

However, there is one thing that is not (completely) clear to me and that is why I am opening this issue to get this question answered (if possible):

I have installed your script (from web) as follows:
`curl https://get.acme.sh | sh`

This will do the three things you have mentioned in your `README.md`:

> 1. Create and copy `acme.sh` to your home dir (`$HOME`): `~/.acme.sh/`. All certs will be placed in this folder.
> 2. Create alias for: `acme.sh=~/.acme.sh/acme.sh`.
> 3. Create everyday cron job to check and renew the cert if needed.
> 
> Cron entry example:
> 
> `0 0 * * * "/home/user/.acme.sh"/acme.sh --cron --home "/home/user/.acme.sh" > /dev/null`
> 

My particular question is about the third item in this list.

I have also ran this command to install the issued cert to nginx:

```
acme.sh --installcert -d aa.com \
--certpath /path/to/certfile/in/nginx  \
--keypath  /path/to/keyfile/in/nginx  \
--capath   /path/to/ca/certfile/nginx   \
--fullchainpath path/to/fullchain/certfile/nginx \
--reloadcmd  "service nginx reload"
```

In your `README.md` you mention this about the `--installcert` functionality:

> The cert will be `renewed every 80 days by default` (which is configurable). Once the cert is renewed, the apache/nginx will be automatically reloaded by the command: `service apache2 reload` or `service nginx reload`.

However, how does this work? And how can I be sure this works?
Is the third item in the list above (the `everyday cron job to check and renew the cert if needed`) going to take care of this? And after running `--installcert` for one (or more) domain(s), where is this configuration stored so that `acme.sh` knows that his cron job should make sure to copy the files over (because I think that is what `--installcert` does) and then run `service nginx reload` for me?

**Comment by Neilpang** [comment]
yes,   acme.sh records all you do,  when the cert is renewed, `--installcert` will be run automatically.

see:
```
~/.acme.sh/domain.com/domain.conf
```

**Comment by djvdorp** [comment]
Hi @Neilpang,

Thank you for the prompt reply, I have found what I was looking for now.
I will describe it here in detail in case other people are looking for it later on, and then close the issue.

So I ran this to acquire a certificate:
```
$ acme.sh --issue -d domain.com --webroot /srv/www/domain.com
```

Then I ran this to install the issued cert to nginx:
```
$ acme.sh --installcert -d domain.com --certpath /etc/nginx/ssl/domain.com.cer --keypath /etc/nginx/ssl/domain.com.key --capath /etc/nginx/ssl/domain.com.ca.cer --fullchainpath /etc/nginx/ssl/domain.com.chain.cer --reloadcmd "sudo service nginx reload"
```

Which resulted in this record (like you described above):
```
$ cat .acme.sh/domain.com/domain.com.conf
Le_Domain="domain.com"
Le_Alt="no"
Le_Webroot="/srv/www/domain.com"
Le_PreHook=""
Le_PostHook=""
Le_RenewHook=""
Le_Keylength=""
Le_LinkCert="https://acme-v01.api.letsencrypt.org/acme/cert/XXX"
Le_LinkIssuer="https://acme-v01.api.letsencrypt.org/acme/issuer-cert"
Le_CertCreateTime="1474046801"
Le_CertCreateTimeStr="Fri Sep 16 17:26:41 UTC 2016"
Le_NextRenewTime="1480958801"
Le_NextRenewTimeStr="Mon Dec  5 17:26:41 UTC 2016"
Le_RealCertPath="/etc/nginx/ssl/domain.com.cer"
Le_RealCACertPath="/etc/nginx/ssl/domain.com.ca.cer"
Le_RealKeyPath="/etc/nginx/ssl/domain.com.key"
Le_ReloadCmd="sudo service nginx reload"
Le_RealFullChainPath="/etc/nginx/ssl/domain.com.chain.cer"
```

And I have ran this to test that all works well and that the cron job will install it again and reload nginx for me (hence the `--force` once):
```
"/home/www-data/.acme.sh"/acme.sh --cron --home "/home/www-data/.acme.sh" --force
```

**Comment by Neilpang** [comment]
@djvdorp  Yes, right.

But I have a question:

if you are log in as user "www-data",   does it belong to sudoer? 

I see your reloadcmd has  `sudo` in it .

**Comment by djvdorp** [comment]
@Neilpang Yes, the user `www-data` can do `sudo service nginx reload` without password, configured as follows (in file `/etc/sudoers`):

```
[..]
# Cmnd alias specification
# Nginx Commands
Cmnd_Alias NGINX_RELOAD  = /usr/sbin/service nginx reload

# No-Password Commands
www-data ALL=NOPASSWD: NGINX_RELOAD
[..]
```

I configured it this way because `www-data` runs the webserver for all domains configured, so in my head it makes sense to also let this user handle the SSL certificates and not do this as `root`.

**Comment by SimWhite** [comment]
Could someone explain what happens if I run `--installcert` for the same certificate more than one time with a different parameters of installation directory and services?

**Comment by Neilpang** [comment]
@SimWhite 

Only the latest parameters take effect.

**Comment by c33s** [comment]
would be good to have [this info](https://github.com/Neilpang/acme.sh/issues/290#issuecomment-247754410) directly in the readme.
