### ISSUE TITLE
Skip verification if the domain is already verified

### ISSUE THREAD

**Issue by msg7086** [Neilpang/acme.sh#294]
Sometimes when a domain cert is being renewed, the domain verification status is still valid. Might be better if it can just skip the verification and issue the cert right away.

I notice this when I'm trying to renew a domain cert whose DNS is not correctly configured, and still got the certificates (using same account key, of course). I dump the debug log and see this:

```
entry='{"type":"http-01","status":"valid","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/HfZ_***/238193***","token":"L_XR-***","keyAuthorization":"L_XR-***.WXsBIi-***
3e6Ut6FU3MNLXmPFC4IPgPpVEStIlpc","validationRecord":[{"url":"http://***.com/.well-known/acme-challenge/L_XR-***","hostname":"***.com","port":"80","addressesResolved":["96.26.97.4"],"addressUsed":"96.26.97.4"'
```

Compared to a new domain cert request:

```
entry='{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/EggzCq-****/269401577","token":"KG3dbyLR4o****"'
```

Should just check if entry['status'] is valid and skip the verification process.

**Comment by Neilpang** [comment]
@msg7086 
Yes, we already did that long long ago.

If you ever tried it, you should see the output like:
```
[Tue Sep 20 19:09:38 CST 2016] Getting webroot for domain='test.mydomain.com'
[Tue Sep 20 19:09:38 CST 2016] Getting token for domain='test.mydomain.com'
[Tue Sep 20 19:09:41 CST 2016] test.mydomain.com is already verified, skip.
[Tue Sep 20 19:09:41 CST 2016] test.mydomain.com is already verified, skip http-01.
[Tue Sep 20 19:09:41 CST 2016] test.mydomain.com is already verified, skip http-01.
[Tue Sep 20 19:09:41 CST 2016] Verify finished, start to sign.
[Tue Sep 20 19:09:45 CST 2016] Cert success.

```

**Comment by msg7086** [comment]
My bad. Updated acme.sh and it works as expected.

**Comment by Neilpang** [comment]
@msg7086   

https://community.letsencrypt.org/t/upcoming-change-valid-authz-reuse/16982
