### ISSUE TITLE
readlink: illegal option 

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#297]
$ ./acme.sh --staging  --issue  -d acmesh.imperialus.house  --dns dns_cf 
readlink: illegal option -- f
usage: readlink [-n] [file ...]

MacOS 10.12 sierra with latest home brew installed
https://github.com/Neilpang/acme.sh v2.5.5

**Comment by Neilpang** [comment]
@FernandoMiguel 

Paste the debug log:

https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by Neilpang** [comment]
@FernandoMiguel 

fixed, please upgrade and try again.

**Comment by FernandoMiguel** [comment]
fixed on the mac. will test synology and linux later
