### ISSUE TITLE
revoke fails

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#299]
$ ./acme.sh --revoke -d acmesh.imperialus.house --debug
[Thu 22 Sep 2016 10:52:03 BST] Lets guess script dir.
[Thu 22 Sep 2016 10:52:03 BST] _SCRIPT_='./acme.sh'
[Thu 22 Sep 2016 10:52:03 BST] _script
[Thu 22 Sep 2016 10:52:03 BST] _script_home='.'
[Thu 22 Sep 2016 10:52:03 BST] It seems tha acme.sh is already installed in /Users/Fernando/.acme.sh
https://github.com/Neilpang/acme.sh
v2.5.5
[Thu 22 Sep 2016 10:52:03 BST] DOMAIN_PATH='/Users/Fernando/.acme.sh/acmesh.imperialus.house'
[Thu 22 Sep 2016 10:52:04 BST] i='2'
[Thu 22 Sep 2016 10:52:04 BST] j='28'
[Thu 22 Sep 2016 10:52:04 BST] Try domain key first.
[Thu 22 Sep 2016 10:52:04 BST] url='https://acme-v01.api.letsencrypt.org/acme/revoke-cert'
[Thu 22 Sep 2016 10:52:04 BST] payload='{"resource": "revoke-cert", "certificate": "MIIE8zCCA9ugAwIBAgITAPqa9jPlF9-XXXX"}'
[Thu 22 Sep 2016 10:52:04 BST] RSA key
[Thu 22 Sep 2016 10:52:05 BST] GET
[Thu 22 Sep 2016 10:52:05 BST] url='https://acme-v01.api.letsencrypt.org/directory'
[Thu 22 Sep 2016 10:52:05 BST] timeout
[Thu 22 Sep 2016 10:52:05 BST] _CURL='curl -L --silent --dump-header /Users/Fernando/.acme.sh/http.header '
[Thu 22 Sep 2016 10:52:06 BST] ret='0'
[Thu 22 Sep 2016 10:52:06 BST] POST
[Thu 22 Sep 2016 10:52:06 BST] url='https://acme-v01.api.letsencrypt.org/acme/revoke-cert'
[Thu 22 Sep 2016 10:52:06 BST] _CURL='curl -L --silent --dump-header /Users/Fernando/.acme.sh/http.header '
[Thu 22 Sep 2016 10:52:07 BST] _ret='0'
[Thu 22 Sep 2016 10:52:07 BST] code='404'
[Thu 22 Sep 2016 10:52:07 BST] Revoke error by domain key.
[Thu 22 Sep 2016 10:52:07 BST] {"type":"urn:acme:error:malformed","detail":"No such certificate","status": 404}
[Thu 22 Sep 2016 10:52:07 BST] Then try account key.
[Thu 22 Sep 2016 10:52:07 BST] url='https://acme-v01.api.letsencrypt.org/acme/revoke-cert'
[Thu 22 Sep 2016 10:52:07 BST] payload='{"resource": "revoke-cert", "certificate": "MIIE8zCCA9ugAwIBAgITAPqa9jPlF9-XXXX"}'
[Thu 22 Sep 2016 10:52:07 BST] RSA key
[Thu 22 Sep 2016 10:52:09 BST] GET
[Thu 22 Sep 2016 10:52:09 BST] url='https://acme-v01.api.letsencrypt.org/directory'
[Thu 22 Sep 2016 10:52:09 BST] timeout
[Thu 22 Sep 2016 10:52:09 BST] _CURL='curl -L --silent --dump-header /Users/Fernando/.acme.sh/http.header '
[Thu 22 Sep 2016 10:52:09 BST] ret='0'
[Thu 22 Sep 2016 10:52:09 BST] POST
[Thu 22 Sep 2016 10:52:09 BST] url='https://acme-v01.api.letsencrypt.org/acme/revoke-cert'
[Thu 22 Sep 2016 10:52:09 BST] _CURL='curl -L --silent --dump-header /Users/Fernando/.acme.sh/http.header '
[Thu 22 Sep 2016 10:52:10 BST] _ret='0'
[Thu 22 Sep 2016 10:52:10 BST] code='404'
[Thu 22 Sep 2016 10:52:10 BST] Revoke error.
[Thu 22 Sep 2016 10:52:10 BST] {"type":"urn:acme:error:malformed","detail":"No such certificate","status": 404}

**Comment by vestacp** [comment]
@FernandoMiguel 

If the certificate is staging cert, you should invoke to staging cert:

```
acme.sh --revoke -d acmesh.imperialus.house --debug  --stage
```

**Comment by Neilpang** [comment]
did you use staging server ?

**Comment by FernandoMiguel** [comment]
oh right!

**Comment by FernandoMiguel** [comment]
good catch. using the *same* server works.

$ ./acme.sh --issue -d acmeshrevoke.imperialus.house --dns dns_cf 
[Thu 22 Sep 2016 11:24:48 BST] Registering account
[Thu 22 Sep 2016 11:24:51 BST] Already registered
[Thu 22 Sep 2016 11:24:51 BST] Creating domain key
[Thu 22 Sep 2016 11:24:51 BST] Single domain='acmeshrevoke.imperialus.house'
[Thu 22 Sep 2016 11:24:52 BST] Verify each domain
[Thu 22 Sep 2016 11:24:52 BST] Getting webroot for domain='acmeshrevoke.imperialus.house'
[Thu 22 Sep 2016 11:24:52 BST] Getting token for domain='acmeshrevoke.imperialus.house'
[Thu 22 Sep 2016 11:24:55 BST] Found domain api file: /Users/Fernando/.acme.sh/dnsapi/dns_cf.sh
[Thu 22 Sep 2016 11:24:57 BST] Adding record
[Thu 22 Sep 2016 11:24:57 BST] Added, sleeping 10 seconds
[Thu 22 Sep 2016 11:25:07 BST] Sleep 10 seconds for the txt records to take effect
[Thu 22 Sep 2016 11:25:17 BST] Verifying:acmeshrevoke.imperialus.house
[Thu 22 Sep 2016 11:25:26 BST] Success
[Thu 22 Sep 2016 11:25:26 BST] Verify finished, start to sign.
[Thu 22 Sep 2016 11:25:30 BST] Cert success.


$ ./acme.sh --revoke -d acmeshrevoke.imperialus.house 
[Thu 22 Sep 2016 11:25:39 BST] Try domain key first.
[Thu 22 Sep 2016 11:25:42 BST] Revoke success.
