### ISSUE TITLE
keep settings on upgrade

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#301]
everytime i upgrade the settings i do in account.conf and acme.sh get reset.
i always need to go enter the account email, dns timeout, etc.
cloudflare API keys are kept.

would it be possible for a better upgrade process to keep these (global) settings ?

**Comment by Neilpang** [comment]
It should be kept.

Please give debug log:

```
acme.sh  --upgrade  --debug 2
```

**Comment by FernandoMiguel** [comment]
$ ./acme.sh --upgrade  --debug 2
[Thu 22 Sep 2016 14:12:07 BST] Lets guess script dir.
[Thu 22 Sep 2016 14:12:07 BST] _SCRIPT_='./acme.sh'
[Thu 22 Sep 2016 14:12:07 BST] _script
[Thu 22 Sep 2016 14:12:07 BST] _script_home='.'
[Thu 22 Sep 2016 14:12:07 BST] It seems tha acme.sh is already installed in /Users/Fernando/.acme.sh
[Thu 22 Sep 2016 14:12:07 BST] 20:USER_AGENT=""
https://github.com/Neilpang/acme.sh
v2.5.5
[Thu 22 Sep 2016 14:12:07 BST] Installing from online archive.
[Thu 22 Sep 2016 14:12:07 BST] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Thu 22 Sep 2016 14:12:07 BST] GET
[Thu 22 Sep 2016 14:12:07 BST] url='https://github.com/Neilpang/acme.sh/archive/master.tar.gz'
[Thu 22 Sep 2016 14:12:07 BST] timeout
[Thu 22 Sep 2016 14:12:07 BST] _CURL='curl -L --silent --dump-header /Users/Fernando/.acme.sh/http.header  --trace-ascii /var/folders/m9/h_k1grsd7z3dsjcy2t5p79_w0000gn/T/tmp.omr0dqxy '
[Thu 22 Sep 2016 14:12:09 BST] ret='0'
[Thu 22 Sep 2016 14:12:09 BST] Extracting master.tar.gz
[Thu 22 Sep 2016 14:12:09 BST] Installing to /Users/Fernando/.acme.sh
[Thu 22 Sep 2016 14:12:09 BST] Installed to /Users/Fernando/.acme.sh/acme.sh
[Thu 22 Sep 2016 14:12:09 BST] OK, Close and reopen your terminal to start using acme.sh
[Thu 22 Sep 2016 14:12:09 BST] Good, bash is installed, change the shebang to use bash as prefered.
[Thu 22 Sep 2016 14:12:09 BST] OK
[Thu 22 Sep 2016 14:12:09 BST] Install success!
[Thu 22 Sep 2016 14:12:09 BST] Upgrade success!


`$ more acme.sh
#!/usr/bin/env bash

VER=2.5.5

PROJECT_NAME="acme.sh"

PROJECT_ENTRY="acme.sh"

PROJECT="https://github.com/Neilpang/$PROJECT_NAME"

DEFAULT_INSTALL_HOME="$HOME/.$PROJECT_NAME"
_SCRIPT_="$0"


DEFAULT_CA="https://acme-v01.api.letsencrypt.org"
DEFAULT_AGREEMENT="https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf"

DEFAULT_USER_AGENT="$PROJECT_ENTRY client v$VER : $PROJECT"
DEFAULT_ACCOUNT_EMAIL=""

STAGE_CA="https://acme-staging.api.letsencrypt.org"

VTYPE_HTTP="http-01"
VTYPE_DNS="dns-01"
VTYPE_TLS="tls-sni-01"
VTYPE_TLS2="tls-sni-02"

MAX_RENEW=80

DEFAULT_DNS_SLEEP=120
`

i had set the email and DNS sleep to 10 sec

**Comment by Neilpang** [comment]
It's a bug on Mac.

Do not use `./acme.sh --upgrade`

Use the alias `acme.sh  --upgrade`

**Comment by FernandoMiguel** [comment]
well, i cant, since acme.sh is not part of my $PATH

**Comment by FernandoMiguel** [comment]
this is at the bottom of my .bashrc

. "/Users/Fernando/.acme.sh/acme.sh.env"

**Comment by FernandoMiguel** [comment]
$ alias acme.sh="/Users/Fernando/.acme.sh/acme.sh"
fmMac:~ Fernando$ acme.sh --upgrade
[Thu 22 Sep 2016 14:25:01 BST] Installing from online archive.
[Thu 22 Sep 2016 14:25:01 BST] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Thu 22 Sep 2016 14:25:02 BST] Extracting master.tar.gz
[Thu 22 Sep 2016 14:25:02 BST] Installing to /Users/Fernando/.acme.sh
[Thu 22 Sep 2016 14:25:02 BST] Installed to /Users/Fernando/.acme.sh/acme.sh
[Thu 22 Sep 2016 14:25:02 BST] OK, Close and reopen your terminal to start using acme.sh
[Thu 22 Sep 2016 14:25:02 BST] Good, bash is installed, change the shebang to use bash as prefered.
[Thu 22 Sep 2016 14:25:02 BST] OK
[Thu 22 Sep 2016 14:25:02 BST] Install success!
[Thu 22 Sep 2016 14:25:03 BST] Upgrade success!


and it still replaced my changes done to acme.sh

**Comment by Neilpang** [comment]
Is the `/Users/Fernando/.acme.sh/account.conf`  reset ?

I don't understand which file is reset.  Please explain.

**Comment by FernandoMiguel** [comment]
yes, account.conf loses ACCOUNT_EMAIL= data
and acme.sh 
DEFAULT_ACCOUNT_EMAIL="XXX"
DEFAULT_DNS_SLEEP=10

**Comment by Neilpang** [comment]
@FernandoMiguel 

Never, never, never, never, never, never, never, never, never, never change anything in `acme.sh`,  it will get lost.

You can change in account.conf:
```
ACCOUNT_EMAIL=aaa
```

or you can also use `--accountemail`
```
acme.sh --issue .....     --accountemail my@my.com
```

If you want to change the dns sleep time, please use `--dnssleep`
Sleep 300 seconds:
```
acme.sh  --issue  -d mydomain.com   --dns  dns_cf   --dnssleep 300
```


Please uninstall and re-install the latest code and try again:

```
acme.sh  --uninstall
curl https://get.acme.sh | sh

source ~/.acme.sh/acme.sh.env

acme.sh --issue ........
```

**Comment by FernandoMiguel** [comment]
thank you for the instructions.
would it be possible to move all of this permanent settings to a config file?
would allow us to easily deploy to our servers and keep in our code repos.

**Comment by Neilpang** [comment]
@FernandoMiguel 
You can comment or uncomment any the options in the account.conf if you know it well.

Do not use the options that are not listed in the account.conf.
