### ISSUE TITLE
add an option to re-try in debug mode

### ISSUE THREAD

**Issue by centminmod** [Neilpang/acme.sh#304]
when acme.sh fails to issue a certificate due to various errors like dns, verification failures etc, would be nice if you could automatically re-try but with `--debug 2` flag enabled for the 2nd attempt ?

maybe a new flag like `--debug-retry` which triggers a re-try with `--debug 2` ?

**Comment by Neilpang** [comment]
@centminmod 
There is already some retry logic in the code.  you can search for "retry" keyword.

It should retry if there is fatal error in the process.

Anyway, Please give me give me more details, let me think about it.

**Comment by centminmod** [comment]
well currently if a user runs acme.sh issue and it fails, they have to run it again with `--debug 2`

the suggestion is to be able to auto re-run with  `--debug 2` enabled again.

**Comment by Neilpang** [comment]
@centminmod 
OK.
I'm added a `LOG_LEVEL` option,  which works together with the `LOG_FILE` option.

It can log the process.  if error happens,  the user can check the log file.

Is that ok?

**Comment by centminmod** [comment]
so that would log the same detailed verbose output as `--debug 2` ? if so that would be perfect :)

**Comment by Neilpang** [comment]
Fixed at:  a73c5b3355c6afb889363ca486db82c0946b1702

https://github.com/Neilpang/acme.sh/wiki/Enable-acme.sh-log

**Comment by centminmod** [comment]
the link to https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh might confuse users of my acmetool.sh wrapper that uses acme.sh as the method used to debug would slightly differ https://community.centminmod.com/posts/36908/

an option to disable the link to https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh or edit it ?

**Comment by centminmod** [comment]
seem to be getting an error if i set log-level ?

    /root/.acme.sh/acme.sh --staging --issue -d acme.domain.com -w /home/nginx/domains/acme.domain.com/public -k 2048 --useragent centminmod-centos7-acmesh-webroot --log /root/centminlogs/acmetool.sh-debug-log-260916-173926 --log-level 2
    /root/.acme.sh/acme.sh: line 136: [: --log-level: integer expression expected

**Comment by centminmod** [comment]
`bash -x` output segment from acme.sh issue run

```
+ '[' 8 -gt 0 ']'
+ case "${1}" in
+ _keylength=2048
+ '[' '' = no ']'
+ shift
+ shift 1
+ '[' 6 -gt 0 ']'
+ case "${1}" in
+ _useragent=centminmod-centos7-acmesh-webroot
+ USER_AGENT=centminmod-centos7-acmesh-webroot
+ shift
+ shift 1
+ '[' 4 -gt 0 ']'
+ case "${1}" in
+ _log=1
+ _logfile=/root/centminlogs/acmetool.sh-debug-log-260916-175936.log
+ '[' -z /root/centminlogs/acmetool.sh-debug-log-260916-175936.log ']'
+ _startswith /root/centminlogs/acmetool.sh-debug-log-260916-175936.log -
+ _str=/root/centminlogs/acmetool.sh-debug-log-260916-175936.log
+ _sub=-
+ echo /root/centminlogs/acmetool.sh-debug-log-260916-175936.log
+ grep '^-'
+ shift
+ LOG_FILE=/root/centminlogs/acmetool.sh-debug-log-260916-175936.log
+ '[' -z '' ']'
+ LOG_LEVEL=1
+ shift 1
+ '[' 2 -gt 0 ']'
+ case "${1}" in
+ _log_level=--log-level
+ LOG_LEVEL=--log-level
+ shift
+ shift 1
+ '[' 0 -gt 0 ']'
+ '[' issue '!=' install ']'
+ __initHome
+ '[' -z '' ']'
+ _exists readlink
+ cmd=readlink
+ '[' -z readlink ']'
+ type command
+ command -v readlink
+ ret=0
+ _debug3 'readlink exists=0'
+ '[' --log-level ']'
+ '[' --log-level -ge 3 ']'
/root/.acme.sh/acme.sh: line 136: [: --log-level: integer expression expected
+ '[' '' ']'
+ return 0
+ _exists dirname
+ cmd=dirname
+ '[' -z dirname ']'
+ type command
+ command -v dirname
+ ret=0
+ _debug3 'dirname exists=0'
+ '[' --log-level ']'
+ '[' --log-level -ge 3 ']'
/root/.acme.sh/acme.sh: line 136: [: --log-level: integer expression expected
+ '[' '' ']'
+ return 0
+ _debug 'Lets guess script dir.'
+ '[' -z --log-level ']'
+ '[' --log-level -ge 1 ']'
/root/.acme.sh/acme.sh: line 117: [: --log-level: integer expression expected
```

**Comment by Neilpang** [comment]
@centminmod 
Sorry, it was a typo.

**Comment by Neilpang** [comment]
@centminmod 

The default log level is: 1 
which logs same as the `--debug` detail.

you can set log level to: 2,

which logs same as `--debug 2`

**Comment by centminmod** [comment]
@Neilpang cheers looks to be working https://community.centminmod.com/posts/36941/ 👍
