### ISSUE TITLE
Cannot issue from a SAN csr file

### ISSUE THREAD

**Issue by dynos01** [Neilpang/acme.sh#306]
"Cannot read subject from csr"

**Comment by Neilpang** [comment]
@dynos01 
What command did you use?
Please add `--debug`  or `--log`

Give me your CSR.

**Comment by dynos01** [comment]
bash acme.sh --showcsr --csr ecc.csr --debug
[Thu Sep 29 13:44:44 CST 2016] Lets guess script dir.
[Thu Sep 29 13:44:44 CST 2016] _SCRIPT_='acme.sh'
[Thu Sep 29 13:44:44 CST 2016] _script='/usr/local/nginx/ssl/acme.sh'
[Thu Sep 29 13:44:44 CST 2016] _script_home='/usr/local/nginx/ssl'https://github.com/Neilpang/acme.shv2.6.0
[Thu Sep 29 13:44:44 CST 2016] Can not read subject from csr: ecc.csr

and the csr is:
-----BEGIN CERTIFICATE REQUEST-----MIIBiDCCAQ0CAQAwADB2MBAGByqGSM49AgEGBSuBBAAiA2IABJFQfuwdtRyrLBAVY/ATgjjGryRzHs5bdUXKEkCX0rhPxGrk7xseoP+IqMVnFLE2xSnyx+xuNtZWJ/139Un6jY9ITunUghTnkP+e983iPBvs6HHZF6X2+18NaynBCPxQsKCBjTCBigYJKoZIhvcNAQkOMX0wezB5BgNVHREEcjBwggZkeW4uaW2CCnd3dy5keW4uaW2CDXN0YXRpYy5keW4uaW2CC3Rlc3QuZHluLmltggtkeW5vczAxLmNvbYIPd3d3LmR5bm9zMDEuY29tgg1kZW5neWludW8ubmV0ghF3d3cuZGVuZ3lpbnVvLm5ldDAKBggqhkjOPQQDAgNpADBmAjEAipWlfBj24RiIlNanB0d77aCLUydumBibNQxc9+zKyutKT/Rit8xoz1s5ciiYpU9DAjEA7x/fb9c6a/dSYqrf1OPPh9gGUspLtcPTSYDV3Z6pE+FKlFLXsKd97xIOOgG54/Uc
-----END CERTIFICATE REQUEST-----

**Comment by dynos01** [comment]
Oops the github mobile was ruining my format...
If it doesn't work, try https://static.dyn.im/ecc.csr
Thank you a lot

**Comment by Neilpang** [comment]
Thanks, I see your csr now.
It doesn't have a subject field.   which tool did you use to generate such csr ?

**Comment by dynos01** [comment]
Using such a command:
openssl req -new -sha256 -key domain.key -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:yoursite.com,DNS:www.yoursite.com")) > domain.csr

**Comment by Neilpang** [comment]
OK, I will fix it.

**Comment by dynos01** [comment]
好的 谢谢作者（才发现原来是天朝人= =

**Comment by Neilpang** [comment]
不客气, 之前没考虑到这种空主题的情况.

**Comment by Neilpang** [comment]
一个小问题, 你为什么要自己手动生成csr 呢 ?

**Comment by Neilpang** [comment]
要用 ecdsa 类型的key吗.

https://github.com/Neilpang/acme.sh#9-issue-ecc-certificate

```
acme.sh --issue  ....   -k ec-256
```

**Comment by dynos01** [comment]
这是因为软件环境原因不能更换key，只能用现有的
