### ISSUE TITLE
DNS name does not have enough labels，how to solve it？

### ISSUE THREAD

**Issue by ccc1924** [Neilpang/acme.sh#312]
rt

**Comment by Neilpang** [comment]
麻烦问一下  rt 是什么意思？
发这样的无意义内容没有人能帮到你。

请参考这个说明：  https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E

和 debug 方法：  https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by ccc1924** [comment]
十分抱歉没写清楚，rt=如题。问题出在DNS上，已经解决
