### ISSUE TITLE
chrome提示申请到的证书不正确？如何解决

### ISSUE THREAD

**Issue by ccc1924** [Neilpang/acme.sh#313]
我通过dns方式成功申请到证书
然后执行
acme.sh  --installcert  -d  multimind.org   --keypath   /etc/nginx/ssl/multimind/multimind.key --certpath  /etc/nginx/ssl/multimind/multimind.cer --capath /etc/nginx/ssl/multimind/ca.cer --fullchainpath /etc/nginx/ssl/multimind/fullchain.cer --reloadcmd  "service nginx reload"

nginx ssl配置如下
    ssl on;
    ssl_certificate     /etc/nginx/ssl/multimind/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/multimind/multimind.key;
求帮助。

**Comment by Neilpang** [comment]
改成这样试试：
```
acme.sh --installcert -d multimind.org --keypath /etc/nginx/ssl/multimind/multimind.key --fullchainpath  /etc/nginx/ssl/multimind/multimind.cer  --reloadcmd "service nginx reload"
```

**Comment by Neilpang** [comment]
你的证书不对， 请仔细阅读chrome 给你的错误信息。

应该多添加一个域名
```
acme.sh --issue  -d multimind.org  -d  www.multimind.org  ......
```

**Comment by ccc1924** [comment]
生成了fullchain.cer ca.cer multimind.org.csr multimind.org.key,最终在nginx中有用到的有哪些？

**Comment by Neilpang** [comment]
两个：
```
--keypath /etc/nginx/ssl/multimind/multimind.key 
--fullchainpath  /etc/nginx/ssl/multimind/multimind.cer 
```

**Comment by ccc1924** [comment]
不知道为什么www.multimind.org一直申请不成功，用的是linode的dns，multimind.org申请成功。

**Comment by ccc1924** [comment]
这段脚本是不是在debian中测试过？我的系统是opensuse，使用时无法添加alias。

**Comment by Neilpang** [comment]
这是所有的测试列表：
https://github.com/Neilpang/acmetest

图片不准，因为有cdn 缓存。 看后面的字段 **passed**

**Comment by Neilpang** [comment]
有问题请贴出你的 debug log

https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

否则没办法帮你。

**Comment by ccc1924** [comment]
谢谢
