### ISSUE TITLE
GoDaddy shared hosting

### ISSUE THREAD

**Issue by Doxtra** [Neilpang/acme.sh#323]
Hi, is this a bug? I managed to get KEY and CSR but failed to return CRT - both on API and manual. I keep getting an "invalid domain" response.

## API

> myblog@a2plcpnl0241 [~]$ acme.sh --issue --dns dns_gd -d myblog.org --debug
[Sat Oct  8 05:18:56 MST 2016] Lets guess script dir.
[Sat Oct  8 05:18:56 MST 2016] _SCRIPT_='/home/myblog/.acme.sh/acme.sh'
[Sat Oct  8 05:18:56 MST 2016] _script='/home/myblog/.acme.sh/acme.sh'
[Sat Oct  8 05:18:56 MST 2016] _script_home='/home/myblog/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.6.0
[Sat Oct  8 05:18:56 MST 2016] Using api:
[Sat Oct  8 05:18:56 MST 2016] DOMAIN_PATH='/home/myblog/.acme.sh/myblog.org'
[Sat Oct  8 05:18:56 MST 2016] Le_NextRenewTime
[Sat Oct  8 05:18:56 MST 2016] _on_before_issue
[Sat Oct  8 05:18:56 MST 2016] RSA key
[Sat Oct  8 05:18:57 MST 2016] AGREEMENT
[Sat Oct  8 05:18:57 MST 2016] Registering account
[Sat Oct  8 05:18:57 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-reg'
[Sat Oct  8 05:18:57 MST 2016] payload='{"resource": "new-reg", "agreement": ""}'
[Sat Oct  8 05:18:57 MST 2016] RSA key
[Sat Oct  8 05:18:57 MST 2016] GET
[Sat Oct  8 05:18:57 MST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Sat Oct  8 05:18:57 MST 2016] timeout
[Sat Oct  8 05:18:57 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:18:58 MST 2016] ret='0'
[Sat Oct  8 05:18:58 MST 2016] POST
[Sat Oct  8 05:18:58 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-reg'
[Sat Oct  8 05:18:58 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:18:58 MST 2016] _ret='0'
[Sat Oct  8 05:18:58 MST 2016] code='409'
[Sat Oct  8 05:18:58 MST 2016] Already registered
[Sat Oct  8 05:18:58 MST 2016] _accUri='https://acme-v01.api.letsencrypt.org/acme/reg/2464286'
[Sat Oct  8 05:18:58 MST 2016] _tos
[Sat Oct  8 05:18:58 MST 2016] Use default tos: https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
[Sat Oct  8 05:18:58 MST 2016] AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf'
[Sat Oct  8 05:18:58 MST 2016] Update tos: https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
[Sat Oct  8 05:18:58 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/reg/2464286'
[Sat Oct  8 05:18:58 MST 2016] payload='{"resource": "reg", "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf"}'
[Sat Oct  8 05:18:58 MST 2016] RSA key
[Sat Oct  8 05:18:59 MST 2016] GET
[Sat Oct  8 05:18:59 MST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Sat Oct  8 05:18:59 MST 2016] timeout
[Sat Oct  8 05:18:59 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:18:59 MST 2016] ret='0'
[Sat Oct  8 05:18:59 MST 2016] POST
[Sat Oct  8 05:18:59 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/reg/2464286'
[Sat Oct  8 05:18:59 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:18:59 MST 2016] _ret='0'
[Sat Oct  8 05:18:59 MST 2016] code='202'
[Sat Oct  8 05:18:59 MST 2016] Update success.
[Sat Oct  8 05:18:59 MST 2016] Read key length:
[Sat Oct  8 05:18:59 MST 2016] _createcsr
[Sat Oct  8 05:18:59 MST 2016] Single domain='myblog.org'
[Sat Oct  8 05:18:59 MST 2016] Verify each domain
[Sat Oct  8 05:18:59 MST 2016] Getting webroot for domain='myblog.org'
[Sat Oct  8 05:18:59 MST 2016] _w='dns_gd'
[Sat Oct  8 05:18:59 MST 2016] _currentRoot='dns_gd'
[Sat Oct  8 05:18:59 MST 2016] Getting new-authz for domain='myblog.org'
[Sat Oct  8 05:18:59 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Sat Oct  8 05:18:59 MST 2016] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "myblog.org"}}'
[Sat Oct  8 05:18:59 MST 2016] RSA key
[Sat Oct  8 05:19:00 MST 2016] GET
[Sat Oct  8 05:19:00 MST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Sat Oct  8 05:19:00 MST 2016] timeout
[Sat Oct  8 05:19:00 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:19:00 MST 2016] ret='0'
[Sat Oct  8 05:19:00 MST 2016] POST
[Sat Oct  8 05:19:00 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Sat Oct  8 05:19:00 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:19:00 MST 2016] _ret='0'
[Sat Oct  8 05:19:01 MST 2016] code='201'
[Sat Oct  8 05:19:01 MST 2016] entry='"type":"dns-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/6tzAufGIi5Uh0BL8FTEyzZXHAuK2qhnVWCojyd95Fnw/286619383","token":"_UTSPvDco5_uEjClm7WUBA3YQ0c0cqkLPBX9SUnupbA"'
[Sat Oct  8 05:19:01 MST 2016] token='_UTSPvDco5_uEjClm7WUBA3YQ0c0cqkLPBX9SUnupbA'
[Sat Oct  8 05:19:01 MST 2016] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/6tzAufGIi5Uh0BL8FTEyzZXHAuK2qhnVWCojyd95Fnw/286619383'
[Sat Oct  8 05:19:01 MST 2016] keyauthorization='_UTSPvDco5_uEjClm7WUBA3YQ0c0cqkLPBX9SUnupbA.SqyDIFKJg_ZH54EvRimRtEO2PhHpSL0ibyJ2J6lpU7o'
[Sat Oct  8 05:19:01 MST 2016] dvlist='myblog.org#_UTSPvDco5_uEjClm7WUBA3YQ0c0cqkLPBX9SUnupbA.SqyDIFKJg_ZH54EvRimRtEO2PhHpSL0ibyJ2J6lpU7o#https://acme-v01.api.letsencrypt.org/acme/challenge/6tzAufGIi5Uh0BL8FTEyzZXHAuK2qhnVWCojyd95Fnw/286619383#dns-01#dns_gd'
[Sat Oct  8 05:19:01 MST 2016] txtdomain='_acme-challenge.myblog.org'
[Sat Oct  8 05:19:01 MST 2016] txt='oEcSD_Yzrcj5WgjQxENcSCL8dt1lIG7t0bgAGIkJGpA'
[Sat Oct  8 05:19:01 MST 2016] d_api='/home/myblog/.acme.sh/dnsapi/dns_gd.sh'
[Sat Oct  8 05:19:01 MST 2016] Found domain api file: /home/myblog/.acme.sh/dnsapi/dns_gd.sh
[Sat Oct  8 05:19:01 MST 2016] First detect the root zone
[Sat Oct  8 05:19:01 MST 2016] domains/myblog.org
[Sat Oct  8 05:19:01 MST 2016] GET
[Sat Oct  8 05:19:01 MST 2016] url='https://api.godaddy.com/v1/domains/myblog.org'
[Sat Oct  8 05:19:01 MST 2016] timeout
[Sat Oct  8 05:19:01 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:19:01 MST 2016] ret='0'
[Sat Oct  8 05:19:01 MST 2016] myblog.org not found
[Sat Oct  8 05:19:01 MST 2016] domains/org
[Sat Oct  8 05:19:01 MST 2016] GET
[Sat Oct  8 05:19:01 MST 2016] url='https://api.godaddy.com/v1/domains/org'
[Sat Oct  8 05:19:01 MST 2016] timeout
[Sat Oct  8 05:19:01 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:19:02 MST 2016] ret='0'
[Sat Oct  8 05:19:02 MST 2016] org not found
[Sat Oct  8 05:19:02 MST 2016] invalid domain
[Sat Oct  8 05:19:02 MST 2016] Error add txt for domain:_acme-challenge.myblog.org
[Sat Oct  8 05:19:02 MST 2016] pid
[Sat Oct  8 05:19:02 MST 2016] _on_issue_err
[Sat Oct  8 05:19:02 MST 2016] Please use add '--debug' or '--log' to check more details.
[Sat Oct  8 05:19:02 MST 2016] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

## MANUAL
> myblog@a2plcpnl0241
 [~]$ acme.sh --issue -d myblog.org -w /home/myblog/public-html --debug
[Sat Oct  8 05:37:09 MST 2016] Lets guess script dir.
[Sat Oct  8 05:37:09 MST 2016] _SCRIPT_='/home/myblog/.acme.sh/acme.sh'
[Sat Oct  8 05:37:09 MST 2016] _script='/home/myblog/.acme.sh/acme.sh'
[Sat Oct  8 05:37:09 MST 2016] _script_home='/home/myblog/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.6.0
[Sat Oct  8 05:37:09 MST 2016] Using api:
[Sat Oct  8 05:37:09 MST 2016] DOMAIN_PATH='/home/myblog/.acme.sh/myblog.org'
[Sat Oct  8 05:37:09 MST 2016] Le_NextRenewTime
[Sat Oct  8 05:37:09 MST 2016] _on_before_issue
[Sat Oct  8 05:37:09 MST 2016] RSA key
[Sat Oct  8 05:37:10 MST 2016] AGREEMENT
[Sat Oct  8 05:37:10 MST 2016] Registering account
[Sat Oct  8 05:37:10 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-reg'
[Sat Oct  8 05:37:10 MST 2016] payload='{"resource": "new-reg", "agreement": ""}'
[Sat Oct  8 05:37:10 MST 2016] RSA key
[Sat Oct  8 05:37:10 MST 2016] GET
[Sat Oct  8 05:37:10 MST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Sat Oct  8 05:37:10 MST 2016] timeout
[Sat Oct  8 05:37:10 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:37:11 MST 2016] ret='0'
[Sat Oct  8 05:37:11 MST 2016] POST
[Sat Oct  8 05:37:11 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-reg'
[Sat Oct  8 05:37:11 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:37:15 MST 2016] _ret='0'
[Sat Oct  8 05:37:15 MST 2016] code='409'
[Sat Oct  8 05:37:15 MST 2016] Already registered
[Sat Oct  8 05:37:15 MST 2016] _accUri='https://acme-v01.api.letsencrypt.org/acme/reg/2464286'
[Sat Oct  8 05:37:15 MST 2016] _tos
[Sat Oct  8 05:37:15 MST 2016] Use default tos: https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
[Sat Oct  8 05:37:15 MST 2016] AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf'
[Sat Oct  8 05:37:15 MST 2016] Update tos: https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
[Sat Oct  8 05:37:15 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/reg/2464286'
[Sat Oct  8 05:37:15 MST 2016] payload='{"resource": "reg", "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf"}'
[Sat Oct  8 05:37:15 MST 2016] RSA key
[Sat Oct  8 05:37:16 MST 2016] GET
[Sat Oct  8 05:37:16 MST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Sat Oct  8 05:37:16 MST 2016] timeout
[Sat Oct  8 05:37:16 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:37:16 MST 2016] ret='0'
[Sat Oct  8 05:37:16 MST 2016] POST
[Sat Oct  8 05:37:16 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/reg/2464286'
[Sat Oct  8 05:37:16 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:37:16 MST 2016] _ret='0'
[Sat Oct  8 05:37:16 MST 2016] code='202'
[Sat Oct  8 05:37:16 MST 2016] Update success.
[Sat Oct  8 05:37:16 MST 2016] Read key length:
[Sat Oct  8 05:37:16 MST 2016] _createcsr
[Sat Oct  8 05:37:16 MST 2016] Single domain='myblog.org'
[Sat Oct  8 05:37:16 MST 2016] Verify each domain
[Sat Oct  8 05:37:16 MST 2016] Getting webroot for domain='myblog.org'
[Sat Oct  8 05:37:16 MST 2016] _w='/home/myblog/public-html'
[Sat Oct  8 05:37:16 MST 2016] _currentRoot='/home/myblog/public-html'
[Sat Oct  8 05:37:16 MST 2016] Getting new-authz for domain='myblog.org'
[Sat Oct  8 05:37:16 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Sat Oct  8 05:37:16 MST 2016] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "myblog.org"}}'
[Sat Oct  8 05:37:16 MST 2016] RSA key
[Sat Oct  8 05:37:17 MST 2016] GET
[Sat Oct  8 05:37:17 MST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Sat Oct  8 05:37:17 MST 2016] timeout
[Sat Oct  8 05:37:17 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:37:17 MST 2016] ret='0'
[Sat Oct  8 05:37:17 MST 2016] POST
[Sat Oct  8 05:37:17 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Sat Oct  8 05:37:17 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:37:17 MST 2016] _ret='0'
[Sat Oct  8 05:37:17 MST 2016] code='201'
[Sat Oct  8 05:37:17 MST 2016] entry='"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/bJZM0YMq01jlnpaAtMghk5qeF5AWB0hj9VqSbvD020s/286631197","token":"8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI"'
[Sat Oct  8 05:37:17 MST 2016] token='8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI'
[Sat Oct  8 05:37:17 MST 2016] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/bJZM0YMq01jlnpaAtMghk5qeF5AWB0hj9VqSbvD020s/286631197'
[Sat Oct  8 05:37:17 MST 2016] keyauthorization='8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI.SqyDIFKJg_ZH54EvRimRtEO2PhHpSL0ibyJ2J6lpU7o'
[Sat Oct  8 05:37:17 MST 2016] dvlist='myblog.org#8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI.SqyDIFKJg_ZH54EvRimRtEO2PhHpSL0ibyJ2J6lpU7o#https://acme-v01.api.letsencrypt.org/acme/challenge/bJZM0YMq01jlnpaAtMghk5qeF5AWB0hj9VqSbvD020s/286631197#http-01#/home/myblog/public-html'
[Sat Oct  8 05:37:18 MST 2016] ok, let's start to verify
[Sat Oct  8 05:37:18 MST 2016] Verifying:myblog.org
[Sat Oct  8 05:37:18 MST 2016] d='myblog.org'
[Sat Oct  8 05:37:18 MST 2016] keyauthorization='8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI.SqyDIFKJg_ZH54EvRimRtEO2PhHpSL0ibyJ2J6lpU7o'
[Sat Oct  8 05:37:18 MST 2016] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/bJZM0YMq01jlnpaAtMghk5qeF5AWB0hj9VqSbvD020s/286631197'
[Sat Oct  8 05:37:18 MST 2016] _currentRoot='/home/myblog/public-html'
[Sat Oct  8 05:37:18 MST 2016] wellknown_path='/home/myblog/public-html/.well-known/acme-challenge'
[Sat Oct  8 05:37:18 MST 2016] writing token:8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI to /home/myblog/public-html/.well-known/acme-challenge/8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI
[Sat Oct  8 05:37:18 MST 2016] Changing owner/group of .well-known to myblog:myblog
[Sat Oct  8 05:37:18 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/bJZM0YMq01jlnpaAtMghk5qeF5AWB0hj9VqSbvD020s/286631197'
[Sat Oct  8 05:37:18 MST 2016] payload='{"resource": "challenge", "keyAuthorization": "8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI.SqyDIFKJg_ZH54EvRimRtEO2PhHpSL0ibyJ2J6lpU7o"}'
[Sat Oct  8 05:37:18 MST 2016] RSA key
[Sat Oct  8 05:37:18 MST 2016] GET
[Sat Oct  8 05:37:18 MST 2016] url='https://acme-v01.api.letsencrypt.org/directory'
[Sat Oct  8 05:37:18 MST 2016] timeout
[Sat Oct  8 05:37:18 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:37:18 MST 2016] ret='0'
[Sat Oct  8 05:37:18 MST 2016] POST
[Sat Oct  8 05:37:18 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/bJZM0YMq01jlnpaAtMghk5qeF5AWB0hj9VqSbvD020s/286631197'
[Sat Oct  8 05:37:18 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:37:19 MST 2016] _ret='0'
[Sat Oct  8 05:37:19 MST 2016] code='202'
[Sat Oct  8 05:37:19 MST 2016] sleep 5 secs to verify
[Sat Oct  8 05:37:24 MST 2016] checking
[Sat Oct  8 05:37:24 MST 2016] GET
[Sat Oct  8 05:37:24 MST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/bJZM0YMq01jlnpaAtMghk5qeF5AWB0hj9VqSbvD020s/286631197'
[Sat Oct  8 05:37:24 MST 2016] timeout
[Sat Oct  8 05:37:24 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
[Sat Oct  8 05:37:24 MST 2016] ret='0'
[Sat Oct  8 05:37:24 MST 2016] myblog.org:Verify error:
[Sat Oct  8 05:37:24 MST 2016] Debug: get token url.
[Sat Oct  8 05:37:24 MST 2016] GET
[Sat Oct  8 05:37:24 MST 2016] url='http://myblog.org/.well-known/acme-challenge/8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI'
[Sat Oct  8 05:37:24 MST 2016] timeout
[Sat Oct  8 05:37:24 MST 2016] _CURL='curl -L --silent --dump-header /home/myblog/.acme.sh/http.header '
<!DOCTYPE html>
<html class="no-js" lang="fr-FR" prefix="og: http://ogp.me/ns#"> ... ... ... </html>
[Sat Oct  8 05:37:25 MST 2016] ret='0'
[Sat Oct  8 05:37:25 MST 2016] Debugging, skip removing: /home/myblog/public-html/.well-known
[Sat Oct  8 05:37:25 MST 2016] pid
[Sat Oct  8 05:37:25 MST 2016] _on_issue_err
[Sat Oct  8 05:37:25 MST 2016] Please use add '--debug' or '--log' to check more details.
[Sat Oct  8 05:37:25 MST 2016] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by Neilpang** [comment]
NO, I don't think it's a bug.

what is your domain ?

if you want to use dns_gd api,  your domain must use the godaddy nameserver,  not the godaddy hosting.

If you use `-w ` mode,  it's NOT manual mode,  it is webroot mode.  Please open this url 'http://myblog.org/.well-known/acme-challenge/8eBMhB4LjDXZr_CGjb81v3qKMV3zKK995-i7F2fszHI'

what do you see there ?

**Comment by Doxtra** [comment]
The domain is doxtra.org

It seems the `acme-challenge` documents are not being created (in the `public-html` folder). I have checked permissions, manually created a `.well-known\acme-challenge` folder, deleted the .htaccess file...

They can however be created in root `home/doxtra` i.e.,

`acme.sh --issue -d myblog.org -w home/myblog/anything` works while
`acme.sh --issue -d myblog.org -w home/myblog/public_html`  does not... and
`acme.sh --issue --dns dns_gd myblog.org` does not either*.

*I accidentally used `dns-gd` and was able to get a TXT record but got "UnExpected error occured. Please try again. If this issue continues, contact support." when trying to update GoDaddy DNS record.

**Comment by Neilpang** [comment]
1. do not delete the `.htaccess`,  that is needed by your hosting, and it has nothing to do with acme protocol.

2. What is your webroot folder ?
https://ca.godaddy.com/help/what-is-my-websites-root-directory-9123

And please set the full path to `-w`, not a relative path.
```
acme.sh --issue -d .....  -w  /home/........
```


3. When you use `dns_gd` mode,  please make sure your api key and secret is Production key,  not a Testing key.
https://developer.godaddy.com/keys/
I just tried one of my domain with `dns_gd`, it works fine for me.

**Comment by Doxtra** [comment]
I've used the webroot mode with `/home/myblog/public_html` AND issued separate certificates for subdomains, each time pointing to a specific folder, i.e. `../public_html/subsite-a`, `../public_html/subsite-b`. So I ended up with more certificates but at least I had SSL working for the time-being.

As a note for GoDaddy users, once `key`, `csr` and `cer` files have been generated by acme.sh, you need to enter them manually in cPanel.

1. **Home** > **SSL/TLS** > **Certificate (CRT)** (Generate, view, upload, or delete SSL certificates.).
2. Copy/Paste the contents of your `cer` file (in `acme.sh` folder) into the "Upload a New Certificate" textbox.
3. Click on "Save certificate", then "Go back".
4. Now go to: **Install and Manage SSL for your site (HTTPS)** (Manage SSL sites.).
5. Under "Install an SSL website" select the required domain/subdomain.
6. Select "Autofill".
7. Enter the contents of the corresponding `key` file in the "Private Key (KEY)" tetbox.
8. Click on "Install certificate".
9. Enjoy your Let's Encrypt SSL thanks to @Neilpang !

Thanks heaps!

*Epilogue: The domain is handled by another registrar. That's why the DNS method won't work for me...

**Comment by Neilpang** [comment]
Glad to know it works for you.
Here is a script to install the cert automatically:
https://github.com/Neilpang/acme.sh/issues/285#issuecomment-245968876
