### ISSUE TITLE
private key file is world readable

### ISSUE THREAD

**Issue by focusaurus** [Neilpang/acme.sh#328]
Filesystem permissions on the private key file are `-rw-rw-r--`. I think it would be more secure to create this file as `-rw-rw----` or even `-r--------`.

**Comment by Neilpang** [comment]
@focusaurus   @warrenski

we had a discussion before:  https://github.com/Neilpang/acme.sh/issues/40


1.  The default install dir is in your home dir:  **~/.acme.sh/**

Nobody else can read your private key in your  home dir.

2. Please search for "chmod" in the source code.  You will find:
```bash
chmod 700 "$LE_WORKING_DIR"
```

Which means the Install dir is also changed to **700**,  nobody else can read the private key in the dir.


Is there any problem you faced ?

**Comment by focusaurus** [comment]
No, this is I guess acceptable. I think it's indirect and still feel `400` on the key reinforces it needs to be secret. Conveys to the sysadmin: "Don't send it to the tech support engineer doing a social engineering attack", etc. But if you have already discussed and are OK with how things are now, it's OK with me. Thanks.
