### ISSUE TITLE
--standalone does not work

### ISSUE THREAD

**Issue by casperklein** [Neilpang/acme.sh#329]
I tried acme.sh today with --standalone. That doesn't work for me.

I noticed, that tcp/80 is not opened by acme.sh. After changing

```_NC="$_NC -q 1 -l $ncaddr"``` 
to
```_NC="$_NC -q 1 -l -p $ncaddr"``` 

it works. Did I miss something or is it a bug?

Debian: 8.6

**Comment by Neilpang** [comment]
Give me the debug log: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

tell me you OS version.

**Comment by casperklein** [comment]
Last line of my post (it's Debian 8.6). I will post debug log when I am at home later.

Just wondering: Can you get nc to listen on any port without "-p" switch?

**Comment by casperklein** [comment]
[debug.txt](https://github.com/Neilpang/acme.sh/files/537299/debug.txt)

**Comment by Neilpang** [comment]
give me you nc version:
```
nc -h
```

**Comment by Neilpang** [comment]
fixed at:  c9febbdd876888e2b16c1b6b57f7658c63bea91e

You are using the default nc on debian.  it should be working now.

But it is recommended to use the `netcat-openbsd` instead.
```
sudo apt-get install netcat-openbsd
```

`netcat-openbsd`  supports more options, and is more modern .

Thanks.

**Comment by casperklein** [comment]
Thanks for fixing and the hint about netcat-openbsd. I didn't know, that there are other versions available.
