### ISSUE TITLE
don't add anything to zshrc without informing the user

### ISSUE THREAD

**Issue by LeSpocky** [Neilpang/acme.sh#332]
When installing 2.5.2 on zsh, I got the following output

```
alex@susan ~/src/acme.sh (git)-[tags/2.5.2] % ./acme.sh --install --accountemail post@lespocky.de
[Do 20. Okt 16:18:42 CEST 2016] Installing to /home/alex/.acme.sh
[Do 20. Okt 16:18:42 CEST 2016] Installed to /home/alex/.acme.sh/acme.sh
[Do 20. Okt 16:18:42 CEST 2016] OK, Close and reopen your terminal to start using acme.sh
[Do 20. Okt 16:18:42 CEST 2016] Installing cron job
no crontab for alex
no crontab for alex
[Do 20. Okt 16:18:42 CEST 2016] Good, bash is installed, change the shebang to use bash as prefered.
[Do 20. Okt 16:18:42 CEST 2016] OK
```

The changes made to my system as I could find out where these:

* created directory `~/.acme.sh` and copied things to it
* created a cronjob
* appended a line to my `~/.zshrc`

The first two things are more or less clear, although the install script could be even more clear about the cronjob. The last is not obvious at all. Log messages talk about bash, yes bash is installed, but it's not the shell I use. No word about zsh, but silently appending things to my `~/.zshrc` … and even wrong. See, this is the line appended:

```
. "/home/alex/.acme.sh/acme.sh.env"
```

This file contains:

```
export LE_WORKING_DIR="/home/alex/.acme.sh"
alias acme.sh="/home/alex/.acme.sh/acme.sh"
```

The first is setting an environment variable, which should go to `~/.zshenv` for zsh. The alias could go to `~/.zshrc` but if it goes unnoticed, people regulary overwriting their zshrc from another source would silently overwrite the changes made by acme.sh installer.

**Comment by Neilpang** [comment]
I just added more info.  9aa3be7f9f585ad25f40eed66483f82db0d433a1

If you don't like the alias.  you can uninstall the alias:
```
./acme.sh   _uninstallalias
```

**Comment by LeSpocky** [comment]
Fine, thank you. :-)

**Comment by CMCDragonkai** [comment]
Can this be placed on the README.md? Also can this be changed to a flag like --noalias just like --nocron during installation.

**Comment by Neilpang** [comment]
@msva  sure, I will add soon.

**Comment by Perflyst** [comment]
Any update on `--noalias`?
