### ISSUE TITLE
Message if anything was upgraded or not

### ISSUE THREAD

**Issue by noplanman** [Neilpang/acme.sh#337]
It would be great if the output of `acme.sh --upgrade` would say if anything was upgraded or not. As I'm using Ansible for server management, this would be very helpful.

Now I need to compare the output of `acme.sh --version` before and after the upgrade, which isn't soooo bad, but it would be nicer to just "know" if there was an update in 1 step.

What I imagine is something along the lines of:
`Upgrade success! (v2.6.0 -> v2.6.1)`
or if no upgrade available:
`Already up-to-date. (v2.6.1)`

**Comment by Neilpang** [comment]
There are always many fixes without increasing the version number.  We don't upgrade  according to the version number.

So, when you call `--upgrade`, it always download the latest code from github.

You don't need to know whether the version number is different or not.

**Comment by noplanman** [comment]
Hmm, ok. Is there any other way of knowing if something changed?

For Ansible it's important to know if anything actually changed.

**Comment by Neilpang** [comment]
Not yet.

Tell me more about your case.

**Comment by noplanman** [comment]
Do you know [Ansible](https://www.ansible.com/)?

Basically, it's a software to automate server installations. Whenever a task changes something in the system, Ansible tells you about it. Obviously this should only happen if something actually does change. So it needs something to be able to compare to (e.g. version numbers, or checking the output of a script).

So if `acme.sh --upgrade` doesn't actually change any files, this task shouldn't be marked as "changed".

I totally understand what you say, that it just gets the latest version and it's not important if something actually changes. But for my case I need it.

Doing it with `shasum` works well for the moment.

**Comment by Neilpang** [comment]
Cool, if you can compare the `shasum` of the source code, it will be good.

**Comment by noplanman** [comment]
Ok, will do it like that then 👍
