### ISSUE TITLE
post task for DNS API

### ISSUE THREAD

**Issue by noplanman** [Neilpang/acme.sh#338]
When using a custom DNS API, it would be nice if there was a cleanup task that could be defined.

In the same way that there is a function for [adding the TXT entry](https://github.com/Neilpang/acme.sh/blob/049be10406501f9f9d294cd18841818ff1e3d226/acme.sh#L2293), it would be great if there was one for cleanup.

Namely, to remove the TXT entry again after a successful verification.

Or does the renew always use the same TXT entry?

**Comment by Neilpang** [comment]
Yes,  it should be removed.

See https://github.com/Neilpang/acme.sh/issues/79

**Comment by noplanman** [comment]
Ok, so it's in the works, great! Will close here and check back on the other issue.

**Comment by Neilpang** [comment]
Yes, please subscribe to that bug,  it will get fixed soon.  For now, you can add the remove function in your api file.  when I fix that issue,  your function will be called.

**Comment by noplanman** [comment]
What will the function be named? `dnx_xyz_clearup`?

**Comment by Neilpang** [comment]
`dns_xxxx_rm`,  the name is not important.  you change then.

**Comment by noplanman** [comment]
Ok, I'll just wait till it's definite. Thanks!
