### ISSUE TITLE
Multiple (non)punycode IDN domain certificates

### ISSUE THREAD

**Issue by noplanman** [Neilpang/acme.sh#342]
When registering for an IDN, there are 2 ways of doing this:
- With the pretty name
- With the punycode name (`xn--xyz`)

This allows for 2 different different certificates, which are registered for the same domain (the punycode version).

So when renewing the certs, it will try to renew both "same ones".

Is this intentional or should this be changed?

Also, what is your view on having the `_is_idn` function also return true for punycode domains?

**Comment by Neilpang** [comment]
>> So when renewing the certs, it will try to renew both "same ones".

What do you mean by "same ones " ?

>> Also, what is your view on having the _is_idn function also return true for punycode domains?

To support the punycode domains.

**Comment by noplanman** [comment]
> What do you mean by "same ones " ?

In the `.acme.sh/` folder there are 2 separate entries, one for the nice name, one for the punycode version. (This is if you try to issue both versions)

Regarding the `_is_idn` function, for now it only returns `true` if the nice name looks internationalised. If the format is punycode, the function returns `false`, because punycode names consist of "normal" characters.
What I suggest is to return `true` for both cases.

**Comment by Neilpang** [comment]
>> In the .acme.sh/ folder there are 2 separate entries, one for the nice name, one for the punycode version. (This is if you try to issue both versions)

If you use punycode,  you are professional.  we don't need to compare and find if the domain is already issued.   You are on your own to do anything you want.


>>Regarding the _is_idn function, for now it only returns true if the 

No,   if the domain is already punycoded,  we don't need to encode it again.  This is what the "_is_idn" function is used for.   If the user already give us a  punycoded domain, it's ok. we can also work.
This can be more compatible when the `idn` tools is not available on the user's  system.

**Comment by noplanman** [comment]
> You are on your own to do anything you want.

Ok, I can live with that 😊 

> if the domain is already punycoded, we don't need to encode it again

What I'm using at the moment is `idn -a "${fulldomain}"`, which converts it either way, even if it is already.

>  This can be more compatible when the idn tools is not available on the user's system.

Absolutely, so I'll close here, thanks for the explanations!

**Comment by Neilpang** [comment]
@noplanman  yes, we can not strongly rely on the tool `idn`.  it may be not available on many systems.
