### ISSUE TITLE
Issue certficate very slow

### ISSUE THREAD

**Issue by guestisp** [Neilpang/acme.sh#344]
I'm trying to use acme.sh and replacing certbot (mainly because acme.sh doesn't have any dependances) but acme.sh is way slower than certbot.

I have to create a certificate with 45 domains on it and it taking 10 minutes. The same, with certbot require a couple of minutes

I've also saw this: https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L2557
sleeping 5 seconds for each certificate is really needed?

Is possible to speed up the signing process?

**Comment by guestisp** [comment]
Additionally, i'm getting this:
```
[Thu Oct 27 11:20:03 CEST 2016] new-authz error: <HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>An error occurred while processing your request.<p>Reference&#32;&#35;179&#46;f3ad90d5&#46;1477560003&#46;12b39e34</BODY></HTML>
```

many times. This never happened with certbot.

**Comment by guestisp** [comment]
The major slowdown seems to be here: https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L838

**Comment by Neilpang** [comment]
For the error, it is because that the letsencrypt CA sometimes can not process the request.
I saw the error before.
I just added retry logic to deal with the temp error.

**Comment by guestisp** [comment]
Cool, with this merge, I can remove my retry login (that was repeating the whole procedure from start)

**Comment by guestisp** [comment]
Anyway, the certificate issuing is still slower than cert-bot

**Comment by Neilpang** [comment]
@guestisp 
Please leave this issue open,  I fix the performance soon.

**Comment by Neilpang** [comment]
@guestisp 
fixed.  Please try again.

The issue time is reduced from more than 20 seconds to 8 seconds.

Thanks.

**Comment by guestisp** [comment]
trying right now. I don't have a comparison (i've not saved the issue time previously) but seems MUCH faster.

Yes, I confirm, is waaaaaaaaaaaay faster.

**Comment by warriorjacq9** [comment]
When I make a certificate for one domain, it says 'Processing, The CA is processing your order, please just wait (1/30)' and then the number keeps incrementing without it doing anything. It times out when it reaches 30.
