### ISSUE TITLE
acme.sh/acme.sh --install fails

### ISSUE THREAD

**Issue by gonzzor** [Neilpang/acme.sh#359]
According to the installation guide, `cd acme.sh` is needed after the initial clone and before `./acme.sh --install`. However, doing this in one step, i.e. `acme.sh/acme.sh --install` gives the following error

```
[Wed Nov  2 14:53:13 CET 2016] Installing to /root/.acme.sh
cp: cannot stat `acme.sh': No such file or directory
```
Not sure if there is a reason why this shouldn't work.

**Comment by Neilpang** [comment]
no,  you must `cd acme.sh`.    do not use `acme.sh/acme.sh --install`

And it's better to use online install:

```
curl https://get.acme.sh | sh
```

**Comment by gonzzor** [comment]
Yes, I noticed that, working fine now.

This was more to understand why `acme.sh/acme.sh --install` wasn't supported, any technical reason?

**Comment by Neilpang** [comment]
No technical reason.  Just designed.

**Comment by gonzzor** [comment]
Fair enough, feel free to close if you don't think it's worth fixing :)
