### ISSUE TITLE
cron job with --force doesn't work for domain issued with --test

### ISSUE THREAD

**Issue by gonzzor** [Neilpang/acme.sh#360]
Certificate is issued successfully with the following command (real domain redacted)
`acme.sh --issue --domain foo.example.net -w /var/www/acme --test`

Testing the cronjob created by `acme.sh --install`manually gives an error if `--test` isn't used.
`0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null`

```
"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" --force --log
```

Log is attached from the above run.
[acme.sh.log.txt](https://github.com/Neilpang/acme.sh/files/566787/acme.sh.log.txt)

**Comment by FernandoMiguel** [comment]
technically, you wouldnt want to renew a staging cert. 
my guess it will not even be there in 90 days.

**Comment by gonzzor** [comment]
@FernandoMiguel yes, it's probably not a very common use case beside testing that the setup is working, renewing a certificate is part of that.

It's not a real issue for me, but rather a "bug" I noticed while testing things.

**Comment by Neilpang** [comment]
@gonzzor  @FernandoMiguel 
Let me try.

**Comment by Neilpang** [comment]
@gonzzor  @FernandoMiguel 

I just tried with a total new vm,   then install acme.sh,  issue a cert , run cron with `--force`.  the cert is renewed sucessfully.


@gonzzor   can you please add the level 2 debug.

```
"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" --force  --debug 2 
```

**Comment by FernandoMiguel** [comment]
although i can see benefits from **testing** the cron, is this really something we want to leave in production ?
someone might create a test cert and 60 days cron will try to renew it.... i dont believe it should renew test certs!
maybe a debug flag we can pass for accepting the risk when testing it. but not on the regular cron command 

so, if you want cron to renew a test cert, you should **manually** pass --test to it :)

**Comment by gonzzor** [comment]
@FernandoMiguel Noticed that --cron doesn't accept --domain parameter. I have some real certificates that I don't want to force renew.

Reran the test as a regular user and it all worked as it should

So curious of why it fail when running as root, I moved the real domain folders away and reran the test with --debug 2, it failed. Attaching the log from that run.

[acme.sh.log.txt](https://github.com/Neilpang/acme.sh/files/566923/acme.sh.log.txt)

**Comment by gonzzor** [comment]
@FernandoMiguel What harm would it do to renew a test certificate?

Beside, acme.sh, use a domain specific .conf so that you shouldn't be able to get both a real and a test certificate at the same time, which would be a bad surprise 60 days in the future :). Unless of course you have different directories for acme.sh.

Sure, passing `--test` might be reasonable, failing without isn't very good though.

**Comment by Neilpang** [comment]
@gonzzor 

I just added more log.

Please upgrade and try again:

```
acme.sh --upgrade
```

**Comment by Neilpang** [comment]
@gonzzor 

It maybe a bug when we use wget,  for now, please install `curl` and try again.

Leave this issue open, I will fix it soon.

**Comment by gonzzor** [comment]
@Neilpang So I reran the test with the latest acme.sh but it failed, even with curl installed.

`"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" --force --log --debug 2`

See the attached log of the failures (first run is wget, second is curl).
[acme.sh.log.txt](https://github.com/Neilpang/acme.sh/files/567678/acme.sh.log.txt)

**Comment by Neilpang** [comment]
@gonzzor 

Please run :
```
acme.sh  --registeraccount

```

Then try again.

**Comment by gonzzor** [comment]
Did that, no change
```
# acme.sh --registeraccount
[Thu Nov  3 07:45:56 CET 2016] Registering account
[Thu Nov  3 07:45:58 CET 2016] Already registered
[Thu Nov  3 07:45:59 CET 2016] Update success.
```

Still fails with `new-authz error: {"type":"urn:acme:error:unauthorized","detail":"No registration exists matching provided key","status": 403}`

Can get details from log later if you need.

Tested again with `--test` and it worked.
