### ISSUE TITLE
Synology DS 1813+ and no crontab installed?

### ISSUE THREAD

**Issue by nexttoyou** [Neilpang/acme.sh#364]
Hi,

I was trying to install and run acme.sh following this guide:

https://github.com/Neilpang/acme.sh/wiki/Synology-NAS-Guide

Unfortunately, the install process fails from the beginning as the script is telling me that no crontab is installed:

```
[Thu Nov  3 17:13:05 CET 2016] Installing from online archive.
[Thu Nov  3 17:13:05 CET 2016] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Thu Nov  3 17:13:07 CET 2016] Extracting master.tar.gz
[Thu Nov  3 17:13:07 CET 2016] It is recommended to install crontab first. try to install 'cron, crontab, crontabs or vixie-cron'.
[Thu Nov  3 17:13:07 CET 2016] We need to set cron job to renew the certs automatically.
[Thu Nov  3 17:13:07 CET 2016] Otherwise, your certs will not be able to be renewed automatically.
[Thu Nov  3 17:13:07 CET 2016] Please add '--force' and try install again to go without crontab.
[Thu Nov  3 17:13:07 CET 2016] ./acme.sh --install --force
[Thu Nov  3 17:13:07 CET 2016] Pre-check failed, can not install.

```

Several of the programs installed on this system (DS 1813+/DSM 6.0.2-8451 Update 2) are using cron, so it seems that DSM 6.x is rendering the use of the crontab quite complicated. Any clues?

Many thanks!

**Comment by heldchen** [comment]
DSM does not have a regular crontab installed. use the `--force` parameter as outlined in the error message to get the script installed without creating crontab entries, then create a manual daily scheduled task in the DSM gui.

**Comment by FernandoMiguel** [comment]
I'm the author of the guide.
on my ds214play it worked ok. but feedback is welcome.
you can manually access cron via 
vi /etc/crontab

**Comment by nexttoyou** [comment]
Please accept my apologies in advance, but installing anything via SSH on the Synology is by far not my speciality. So if I enter "./acme.sh --install --force" after the above error message, the output is just this:

`-sh: ./acme.sh: No such file or directory`

The description/guide seemed to be simple but the reality (in my case at least) might be a bit more complicated …

Many thanks!

**Comment by FernandoMiguel** [comment]
In some cases, not all tools might be there, nor did i have access to test this in many devices... just my own NAS, really.

Try following part of my other guide for the RT1900ac, that is more limited than my NAS shell
https://github.com/Neilpang/acme.sh/wiki/Synology-RT1900ac-install-guide

in that example you will download the installer manually and then install without a cron

$ wget https://github.com/Neilpang/acme.sh/archive/master.tar.gz 
$ tar xvf master.tar.gz 
$ cd acme.sh-master/ 
$ ./acme.sh --install --nocron

you then have to create a cron manually

**Comment by heldchen** [comment]
if you're not feeling comfortable with SSH/bash scripts, maybe just use the built-in DSM LE support? https://www.synology.com/en-global/knowledgebase/DSM/help/DSM/AdminCenter/connection_certificate

**Comment by FernandoMiguel** [comment]
@heldchen i suspect his idea is the same as mine, to avoid opening ports to the world

**Comment by nexttoyou** [comment]
@heldchen:
Of course I would have used the included LE functionality, but the use of Cloudflare in my case is rendering it impossible. Nope, SSH is not making me uncomfortable (I’m working with NEXTSTEP/macOS since 1991), but I’m nevertheless far from experienced.

**Comment by nexttoyou** [comment]
@FernandoMiguel 

This is what happens next:

`./acme.sh --install --nocron
[Thu Nov  3 18:30:47 CET 2016] It is recommended to install nc first, try to install 'nc' or 'netcat'.
[Thu Nov  3 18:30:47 CET 2016] We use nc for standalone server if you use standalone mode.
[Thu Nov  3 18:30:47 CET 2016] If you don't use standalone mode, just ignore this warning.
[Thu Nov  3 18:30:47 CET 2016] Installing to /var/services/homes/david/.acme.sh
[Thu Nov  3 18:30:47 CET 2016] Installed to /var/services/homes/david/.acme.sh/acme.sh
[Thu Nov  3 18:30:47 CET 2016] No profile is found, you will need to go into /var/services/homes/david/.acme.sh to use acme.sh
[Thu Nov  3 18:30:47 CET 2016] Good, bash is found, so change the shebang to use bash as prefered.
[Thu Nov  3 18:30:47 CET 2016] OK`

Well, now "nc" seems to be missing …

**Comment by FernandoMiguel** [comment]
you could temporarily disable cloudflare protection .
I've seen a few reports of issues with it, but was never personally hit by them (both at home and hundreds of deploys at work).

do keep in mind that i have setup zero protections to this code, and system updates will break, delete, or make it difficult to execute.
so backup your keys

**Comment by FernandoMiguel** [comment]
@nexttoyou that's just a warning. you are good to go.

**Comment by nexttoyou** [comment]
Sigh, yes, I thought about disabling Cloudflare temporarily. But you know, an easy script seemed to be the better way. And even if the script result is not protected etc. it still seems to be more secure this way as opening the DS up to the whole world (the IPv4 is not dynamic).

**Comment by FernandoMiguel** [comment]
oh i agree with you.
why do you think i use this, wrote the guide and shared it with the world? :D 
let me know if it worked or if you need any help

**Comment by nexttoyou** [comment]
Well, then let's go on … I have opened the files "acme.sh" and "account.conf" with vi. In "acme.sh" I have only entered an existing email address like this:

`"DEFAULT_ACCOUNT_EMAIL="my@email.address"`

And then I saved the file. In "account.conf" I then have entered the Cloudflare account data and uncommented the respective places like this:

```
#dns api
#######################
#Cloudflare:
#api key
CF_Key="mysecretcloudflarekey"
#account email
CF_Email="my.cloudflare@email.address"
```

And then I saved the file. Correct so far?

**Comment by FernandoMiguel** [comment]
Don't change acme.sh as all changes will be lost on update 
You should have an email field on the account.conf

But yeah, that's all the setup required. 
Now you try issuing a new certificate with - - test 
Once you are comfortable with your testing, issue again without it. 
Make sure it replaced your system ones (my DSM paths in the guide) 
Add the crontab. 
Restart DSM (I saw a comment on the forums of a possible way of doing it) or restart the NAS. 
Your certificate should have been published. 

Keep in mind any OpenVPN certs won't be valid as the root ca changed.

**Comment by heldchen** [comment]
... and make sure you run the script as root, as the DSM default certification path is root-writeable only.

**Comment by nexttoyou** [comment]
@FernandoMiguel 
Ah, ok, so I do not change `acme.sh` (you might then update your HowTo at the Synology forum as you wrote `$ vi acme.sh account.conf` there).

@heldchen 
Will do.

But unfortunately, this now has to wait until tomorrow. Many many thanks for all your help!

**Comment by Neilpang** [comment]
Hi guys, @nexttoyou  @FernandoMiguel  @heldchen 

I have a few advices:

1.  You don't need to edit any conf file.  If you want to specify an account email.

```
./acme.sh --install  --force  --accountemail  "myle@example.com"
```

2. Yes, please do not change `acme.sh` file or `dns_cf.sh` file.  they will be overwritten when upgrading.

You should just pass all the arguments from command line parameters,  they will be saved automatically.

3. If you manually add cron job,  please pass the `--home` parameter.

```
/full/path/to/acme.sh  --cron   --home /full/path/to/.acme.sh  >/dev/null
```

**Comment by nexttoyou** [comment]
This is just to tell you that everything has been working as expected and the certificate has been issued flawlessly from LE. The Synology was using it correctly as the default certificate after the reboot but did not show it in the security settings GUI.

Could someone tell me now how the crontab entry on his Synology exactly looks like as I have to do the entry manually and the above example from Neilpang most probably does not work on my DS 1813+.

**Comment by FernandoMiguel** [comment]
vi /etc/crontab

add this with whatever your install path was (i would seriously advise it to be /volume1/@appstore/.acme.sh)

3 2 * * 2 root /root/.acme.sh/acme.sh --cron
