### ISSUE TITLE
Randomized hour/minute for cronjob instead of exactly midnight at install time

### ISSUE THREAD

**Issue by adminblogger** [Neilpang/acme.sh#371]
Hi,

this is mostly a suggestion to reduce load on Let's Encrypt infrastructure. At the moment each and every time you install acme.sh the cronjob entry added will run exactly at midnight.

This will result in **peak load on LE infrastructure** the more acme.sh is adopted. I'm aware that many people run their servers on local time so not all acme.sh installations will run the renew cronjob at the same time. but this only spreads the peak to 24 different peaks all at the full hour.

I suggest to use a random value for hour and minute at install time, so the cronjob from future acme.sh installations will be spread evenly over 24 hours instead of all running at midnight.

**Comment by heldchen** [comment]
this already has come up a few times, see for example #208 #246 #302 for the reasoning for the current behavior...

**Comment by Neilpang** [comment]
@heldchen 
let me think about it.

**Comment by heldchen** [comment]
personally, I'd like to see a randomization of the *minutes* only, not the hours. especially when you have advanced reload scripts, you do not want them to be run mid-day.  but then again, someone using an advanced setup will adjust the crontab entry to his preferences anyway.

**Comment by adminblogger** [comment]
You could spred the cronjob from 9pm to 3am at least for the default install. Sure, there are people who just tweak the line to adjust the time after acme.sh was installed.

But for the average joe it shouldn't matter if the script is running at 9:21pm or 2:49am.

Big hosting providers e.g. modify the cron.daily execution time in /etc/crontab in their install scripts because if not they all to mdadm software raid checks at the exact same time resulting in massive power peaks.

So I guess it would only be fair to spread the load at least a little bit.

**Comment by heldchen** [comment]
keep in mind that a certificate is only issued every x days, and when on a day multiple reissue happen they are serialized. thus it's not that big of a load at all.

**Comment by sjau** [comment]
@adminblogger 

9pm to 3am what timezone? If you're a hosting company you probably have clients from all over the world... so "your" midnight might be "someone else's" noon.

**Comment by abelbeck** [comment]
We had a special case where we handle ```--installcronjob``` and ```--uninstallcronjob``` outside of the acme.sh script.  We used this to set the minutes value of the cron entry:
```
# randomize minutes in the range of 4-56, 53 is a prime number
min=$(( RANDOM % 53 + 4 ))
```
The prime divisor seems to result in a fairly uniform distribution, not perfect but good enough.

It's simple, works with bash and (Busybox) ash, but sadly not all shells.

**Comment by bittorf** [comment]
sorry, $RANDOM is not portable. what you can do is something like:
`MINUTE_RANDOM=$(( $( hexdump -n 2 -e '/2 "%u"' /dev/urandom ) % 60 ))` - but is hexdump widely adopted and portable?

**Comment by dessant** [comment]
I've been randomizing minutes like this:
```
echo "$(shuf -i0-59 -n1) 0 * * *"
```

**Comment by Neilpang** [comment]
@dessant 

It's not that complex.

```
t=$(_time)
random_minute=$(_math $t % 60)
```

But do you guys think the random minute is really so important ?

**Comment by FernandoMiguel** [comment]
@Neilpang Yes.
I run many servers, most of them in the same region, with all of them in UTC (or some cases BST).
having all of them updating certs, writing to disk, reloading configs, hitting LE API servers, DNS requests, 
all at the same time, would be really bad practice

**Comment by sjau** [comment]
Another option would be to ask the user during installation (and provide an installation option to automate it)

**Comment by Neilpang** [comment]
OK,

This is what you guys want:

https://github.com/Neilpang/acme.sh/pull/547
