### ISSUE TITLE
Problem listing SAN certificates with maximum number of domains

### ISSUE THREAD

**Issue by warrenski** [Neilpang/acme.sh#378]
Using ``acme.sh`` I've successfully managed to issue several multi-domain certificates that contain the maximum number of names that Let's Encrypt allows on a single certificate (i.e. LE's limit is currently 100 names per certificate). No issues with that.

However, if I run the following command on CentOS 5:
```
acme.sh  --list
```
For each one of these certificates, the following output appears in the console before the row of headings is printed:
```
column: line too long
```

I believe this warning is from ``sed`` or one of the other text processing binaries that ``acme.sh`` calls?

Further to this, the lines of output for these certificates show signs of truncation. Lines of output for unrelated certificates are unaffected by this problem.

Unfortunately I'm unable to test this in newer CentOS 6/7 releases.

**Comment by Neilpang** [comment]
@warrenski 

It is because the command `column` on Centos5 is too old,  it only supports a small line of data.

**Comment by warrenski** [comment]
@Neilpang Sorry for the trouble, and thanks for confirming that it's the ``column`` command in CentOS versions < 6. Probably not worth working around this issue considering that [CentOS 5 is EOL from April 2017](https://wiki.centos.org/About/Product).

Please close this issue if you like.
