### ISSUE TITLE
安装时报错Unable to establish SSL connection.

### ISSUE THREAD

**Issue by xjdata** [Neilpang/acme.sh#380]
额。。。。我在某些特殊的地区，这里的网络管制比较严格。
Unable to establish SSL connection.

```
DEBUG=2
curl https://get.acme.sh | sh
```

```
wget https://github.com/Neilpang/acme.sh/archive/master.tar.gz
--2016-11-13 10:22:52--  https://github.com/Neilpang/acme.sh/archive/master.tar.gz
Resolving github.com (github.com)... 203.208.39.99, 203.208.39.104
Connecting to github.com (github.com)|203.208.39.99|:443... connected.
Unable to establish SSL connection.
```

貌似只能忽略ssl验证了。  或者我直接下载master分支内容 在执行  sh acme.sh 可以吗？

**Comment by Neilpang** [comment]
可以   你直接下载master  然后 执行  acme.sh --install

**Comment by xjdata** [comment]
嗯。。。。 哎。。。。。 我倒是看到源码安装方式了。

可是这样估计 更新acme 在我这种网络环境下基本不可能，  我看 oschina也有个acme，看作者名字应该是你了。。。但是那边最后更新是8月份的。不知道是否可以尽量2边做到同步， 我走国内的git源。也许还有希望， 不然的话，你更新了但是我这环境造成的没法更细， 最后证书失效，这就扯了。

最后，谢谢acme 真的非常方便。

**Comment by Neilpang** [comment]
你手动执行一次更新   acme.sh  -- upgrade  --auto-upgrade  -- insecure    之后就可以自动更新 并自动忽略证书了

**Comment by Neilpang** [comment]
那边也是我，只是很久没同步了，   等我有时间可以加个那边的镜像

**Comment by xjdata** [comment]
额。 可能我描述的不准确。   acme.sh -- upgrade --auto-upgrade -- insecure   这样确实可以更新acme自身等等。  我在我自己电脑/虚拟机上肯定可行， 因为我翻墙了。 

但是在服务器上，这个就不好说了。 PS，服务器没翻墙。 

实际使用肯定是 设置acme自己也自动更新，同时依靠acme进行证书的更新， 就是担心因为服务器没翻墙所以造成的更新出问题，或者无法更新acme自身，又因为LE规则变动等等情况。造成最后证书无法及时更新。。。


所以担心比较多了。  实在不行我就直接把sslocal弄服务器上去，这样估计最保险了。

关了。 主要都是我这边网络限制太死，其实根本不是acme的问题。 谢谢。

**Comment by Neilpang** [comment]
你在服务器上去试试，  如果你手动能成功， 自动就没问题
