### ISSUE TITLE
Bash & jq?

### ISSUE THREAD

**Issue by sjau** [Neilpang/acme.sh#390]
Hi there

I'm currently writing a dns plugin for the control panel I use and I have two question:

1. can bash be used or must it be posix?
2. can jq be used - that makes handling of json much simpler

**Comment by Neilpang** [comment]
@sjau 

1. yes,  we must run on Unix systems such as Solaris that doesn't have bash by default.
2. yes,  we must cross a large range of systems. Please think about using `_normalizeJson()` and `_egrep_o()` methods instead.

**Comment by sjau** [comment]
Thx, I'll have a look at that. I just thought bash or rather jq would simplify a lot of JSON. Thx for all the work this far.
