### ISSUE TITLE
env: bash: No such file or directory

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#394]
Got an update on my Synology Router which removed acme 

Was trying to issue new issue and got the following error

Triton> ./acme.sh --issue --post-hook kill -USR1 cat /run/httpd/httpd-sys.pid -d triton.imperialus.house --dns dns_cf --certpath /usr/syno/etc/ssl/ssl.crt/server.crt -keypath /us
r/syno/etc/ssl/ssl.key/server.key --fullchainpath /usr/syno/etc/ssl/ssl.intercrt/server-ca.crt --debug 2
**env: bash: No such file or directory**

Triton> head acme.sh 
#!/usr/bin/env bash

VER=2.6.5

any reason for forcing bash?

**Comment by Neilpang** [comment]
@FernandoMiguel 

Just for a better performance.

How did you get such error ?

**Comment by FernandoMiguel** [comment]
@Neilpang no bash in this system 
got ash and sh

**Comment by Neilpang** [comment]
@FernandoMiguel 

run
```
command -v bash

which bash
```

**Comment by FernandoMiguel** [comment]
Triton> command -v bash
-ash: command: not found

**Comment by Neilpang** [comment]
try:

```
which  bash
```

**Comment by FernandoMiguel** [comment]
that gets no reply.

**Comment by Neilpang** [comment]
@FernandoMiguel 

try:

```
which  bash && echo ok || echo bad
```

**Comment by FernandoMiguel** [comment]
Triton> which  bash && echo ok || echo bad
bad

**Comment by FernandoMiguel** [comment]
Triton> ll /bin/
drwxr-xr-x    2 root     root          4096 Jan  1  2016 .
drwxr-xr-x   24 root     root          4096 Jan  1  2016 ..
lrwxrwxrwx    1 root     root             7 Jan  1  2016 ash -> busybox
-rwxr-xr-x    1 root     root        429700 Oct 21 13:00 busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 cat -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 catv -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 chgrp -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 chmod -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 chown -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 cp -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 date -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 dd -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 df -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 dmesg -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 dnsdomainname -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 echo -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 egrep -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 false -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 fgrep -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 get_key_value -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 getopt -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 grep -> busybox
lrwxrwxrwx    1 root     root            15 Jan  1  2016 gunzip -> /usr/bin/gunzip
lrwxrwxrwx    1 root     root            13 Jan  1  2016 gzip -> /usr/bin/gzip
lrwxrwxrwx    1 root     root             7 Jan  1  2016 hostname -> busybox
-rwxr-xr-x    1 root     root        197876 Sep 19 02:16 ip
lrwxrwxrwx    1 root     root             7 Jan  1  2016 ipcalc -> busybox
-rwxr-xr-x    1 root     root        174048 Oct 21 13:01 jq
lrwxrwxrwx    1 root     root             7 Jan  1  2016 kill -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 killps -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 ln -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 login -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 ls -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 mkdir -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 mknod -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 more -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 mount -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 mv -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 netstat -> busybox
-rwxr-xr-x    1 root     root         98660 Oct 21 12:59 ntfs-3g
-rwxr-xr-x    1 root     root          6004 Oct 21 12:59 ntfs-3g.probe
lrwxrwxrwx    1 root     root             7 Jan  1  2016 pidof -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 ping -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 ping6 -> busybox
-rwxr-xr-x    1 root     root          4996 Oct 21 12:59 proxy
lrwxrwxrwx    1 root     root             7 Jan  1  2016 ps -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 pwd -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 rm -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 rmdir -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 run-parts -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 sed -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 sh -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 sleep -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 stat -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 stty -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 su -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 sync -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 synodd -> busybox
lrwxrwxrwx    1 root     root            12 Jan  1  2016 tar -> /usr/bin/tar
lrwxrwxrwx    1 root     root             7 Jan  1  2016 touch -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 true -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 umount -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 uname -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 usleep -> busybox
lrwxrwxrwx    1 root     root             7 Jan  1  2016 vi -> busybox
lrwxrwxrwx    1 root     root            13 Jan  1  2016 zcat -> /usr/bin/zcat

**Comment by Neilpang** [comment]
@FernandoMiguel 

try 

```
acme.sh  --upgrade  --debug 3
```

**Comment by FernandoMiguel** [comment]
Triton> pwd
/root
Triton> acme.sh  --upgrade  --debug 3
-ash: acme.sh: not found


this is after exiting and sshing again.

there's a /root/.profile

**Comment by FernandoMiguel** [comment]
Triton> cd .acme.sh/
Triton> ./acme.sh  --upgrade  --debug 3
[Wed Nov 16 15:56:13 GMT 2016] readlink exists=0
[Wed Nov 16 15:56:13 GMT 2016] dirname exists=0
[Wed Nov 16 15:56:13 GMT 2016] Lets find script dir.
[Wed Nov 16 15:56:13 GMT 2016] _SCRIPT_='./acme.sh'
[Wed Nov 16 15:56:13 GMT 2016] _script='/root/.acme.sh/acme.sh'
[Wed Nov 16 15:56:13 GMT 2016] _script_home='/root/.acme.sh'
[Wed Nov 16 15:56:13 GMT 2016] It seems that acme.sh is already installed in /root/.acme.sh
[Wed Nov 16 15:56:13 GMT 2016] OK
[Wed Nov 16 15:56:13 GMT 2016] 5:ACCOUNT_EMAIL='tritonssl@imperialus.house'
[Wed Nov 16 15:56:13 GMT 2016] OK
[Wed Nov 16 15:56:13 GMT 2016] 14:AUTO_UPGRADE='1'
[Wed Nov 16 15:56:13 GMT 2016] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.6.5
[Wed Nov 16 15:56:13 GMT 2016] Installing from online archive.
[Wed Nov 16 15:56:13 GMT 2016] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Wed Nov 16 15:56:13 GMT 2016] GET
[Wed Nov 16 15:56:13 GMT 2016] url='https://github.com/Neilpang/acme.sh/archive/master.tar.gz'
[Wed Nov 16 15:56:13 GMT 2016] timeout
[Wed Nov 16 15:56:13 GMT 2016] curl exists=0
[Wed Nov 16 15:56:13 GMT 2016] mktemp exists=0
[Wed Nov 16 15:56:13 GMT 2016] wget exists=0
[Wed Nov 16 15:56:13 GMT 2016] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/acme.shwefADf24sf.1479311773.tmp '
[Wed Nov 16 15:56:14 GMT 2016] ret='0'
[Wed Nov 16 15:56:14 GMT 2016] Extracting master.tar.gz
[Wed Nov 16 15:56:14 GMT 2016] Installing to /root/.acme.sh
[Wed Nov 16 15:56:14 GMT 2016] Installed to /root/.acme.sh/acme.sh
[Wed Nov 16 15:56:14 GMT 2016] Installing alias to '/root/.profile'
[Wed Nov 16 15:56:14 GMT 2016] OK, Close and reopen your terminal to start using acme.sh
[Wed Nov 16 15:56:14 GMT 2016] Good, bash is found, so change the shebang to use bash as prefered.
[Wed Nov 16 15:56:15 GMT 2016] OK
[Wed Nov 16 15:56:15 GMT 2016] Install success!
[Wed Nov 16 15:56:15 GMT 2016] Upgrade success!

**Comment by Neilpang** [comment]
@FernandoMiguel 

fixed 7575094cf34e6e218fbad9face68362360b2eedb.

Please re-install.

It was a bug imported by my recent fixes.

**Comment by FernandoMiguel** [comment]
Triton> tail -n1 ~/.profile 
. "/root/.acme.sh/acme.sh.env"

Triton> cat /root/.acme.sh/acme.sh.env
export LE_WORKING_DIR="/root/.acme.sh"
alias acme.sh="/root/.acme.sh/acme.sh"

**Comment by FernandoMiguel** [comment]
reinstall or upgrade ?

**Comment by Neilpang** [comment]
@FernandoMiguel 

either reinstall or upgrade is ok.

**Comment by FernandoMiguel** [comment]
Triton> head acme.sh
#!/usr/bin/env sh

closing
