### ISSUE TITLE
dns-01 question

### ISSUE THREAD

**Issue by sjau** [Neilpang/acme.sh#406]
Hi there

Just wondering, if you use the dns-01 challenge, how will it actually work (if you request a SAN cert):

Will it:

a) first add the txt record for each domain, then tell the LE server they can lookup the dns zone now, and after that remove the txt records?

or

b) first add txt record for domain a, reply to LE server to lookup for the challenge, then remove the txt record....  move to domain b, add txt record, fullfill the challenge, remove the txt record... move to domain c etc. ?

The question arises because when I add a txt record to ISPConfig I get the id of that according row back. So I can easily remove that record again with the same id. However, if first all domains get added and then all records deleted it's different.

Also, adding a txt record to a dns zone in ISPConfig takes a little while until the zone is written to file and bind reloaded. If I write a custom dns plugin, would I need to provide the sleep time between record adding and signalling that the challenge can be completed now?

**Comment by Neilpang** [comment]
@sjau 

We will add the txt records one by one first.

Then ask the Letsencrypt server to validate every domain.

After all the domains are verified we call "dns_xxxx_rm()" function to each domain to delete the txt reocrds.

"dns_xxxx_rm()" is not required, and it's not implemented for every api.  If you implement your api wrapper,  it's recommended to imlement "dns_xxxx_rm()".

**Comment by sjau** [comment]
What if you have multiple txt records like:

acme_test.domain.tld.  3600  TXT "aaaa"
acme_test.domain.tld.  3600  TXT "bbbb"

Won't that lead to problems with LE challenge?

**Comment by Neilpang** [comment]
@sjau 

No, it won't bring any problem.   For each sub domain, it's allowed to add multiple txt records.

**Comment by sjau** [comment]
and what about timeouts and stuff? ISPConfig has a cronjob that writes changes to the DB every minute or so... so between adding a TXT record and having it in the zone file there's up to a 1min delay. How does acme.sh handle such a delay?

**Comment by Neilpang** [comment]
@sjau 

Don't worry,  `acme.sh` knows the delay.  It will wait `180` seconds before asking Letsencrypt to validate.

`180` seconds is enough for most of the apis,  but if it's not enough,  the user can specify a custom value when calling your api:

```
acme.sh --issue  -d example.com  --dns  dns_yourapi   --dnssleep  300 # sleep 300 seconds.
```

**Comment by sjau** [comment]
ah nice :) thx

**Comment by sjau** [comment]
can be closed, made pull request meanwhile.
