### ISSUE TITLE
a possible bug regarding the  --standalone --httpport 34443

### ISSUE THREAD

**Issue by keekychen** [Neilpang/acme.sh#412]
Steps to reproduce
------------------
Openwrt 15.05.1, try to use --standalone --httpport 34443 to issue cert
and get 
[Mon Nov 21 17:40:23 CST 2016] <...omitted...>com:Verify error:Could not connect to <...omitted...>com
[Mon Nov 21 17:40:23 CST 2016] Error: Couldn't resolve host "34443"

regarding the token url $d, the output shows it has no port followed the url callback 
[Mon Nov 21 17:40:23 CST 2016] url='http://<...omitted...>.com/.well-known/acme-challenge/...omitted...'
should it be something with port because listen the 34443?
[Mon Nov 21 17:40:23 CST 2016] url='http://<...omitted...>.com**:34443**/.well-known/acme-challenge/...omitted...'

quick guess is because Openwrt already have 80 port in listen due to luci, could acme.sh wrong judge it has httpd server there using 80 port? refer   --debug 2 output below

Debug log
-----------------
[Mon Nov 21 17:40:12 CST 2016] Standalone mode server
[Mon Nov 21 17:40:12 CST 2016] ncaddr
[Mon Nov 21 17:40:12 CST 2016] startserver: 11448
[Mon Nov 21 17:40:12 CST 2016] Le_HTTPPort='34443'
[Mon Nov 21 17:40:12 CST 2016] Le_Listen_V4
[Mon Nov 21 17:40:12 CST 2016] Le_Listen_V6
[Mon Nov 21 17:40:12 CST 2016] _NC='nc -c -l '
[Mon Nov 21 17:40:13 CST 2016] serverproc='13206'
[Mon Nov 21 17:40:13 CST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/...omitted...'
[Mon Nov 21 17:40:13 CST 2016] payload='{"resource": "challenge", "keyAuthorization": "...omitted..."}'
[Mon Nov 21 17:40:14 CST 2016] POST
[Mon Nov 21 17:40:14 CST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/...omitted...'
[Mon Nov 21 17:40:14 CST 2016] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header '
[Mon Nov 21 17:40:16 CST 2016] _ret='0'
[Mon Nov 21 17:40:16 CST 2016] code='202'
[Mon Nov 21 17:40:16 CST 2016] sleep 2 secs to verify
[Mon Nov 21 17:40:18 CST 2016] checking
[Mon Nov 21 17:40:18 CST 2016] GET
[Mon Nov 21 17:40:18 CST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/...omitted...'
[Mon Nov 21 17:40:18 CST 2016] timeout
[Mon Nov 21 17:40:18 CST 2016] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header '
[Mon Nov 21 17:40:19 CST 2016] ret='0'
[Mon Nov 21 17:40:19 CST 2016] Pending
[Mon Nov 21 17:40:19 CST 2016] sleep 2 secs to verify
[Mon Nov 21 17:40:21 CST 2016] checking
[Mon Nov 21 17:40:21 CST 2016] GET
[Mon Nov 21 17:40:21 CST 2016] url='https://acme-v01.api.letsencrypt.org/acme/challenge/...omitted...'
[Mon Nov 21 17:40:22 CST 2016] timeout
[Mon Nov 21 17:40:22 CST 2016] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header '
[Mon Nov 21 17:40:23 CST 2016] ret='0'
[Mon Nov 21 17:40:23 CST 2016] ...omitted....com:Verify error:Could not connect to ...omitted...com
[Mon Nov 21 17:40:23 CST 2016] Debug: get token url.
[Mon Nov 21 17:40:23 CST 2016] GET
[Mon Nov 21 17:40:23 CST 2016] url='http://...omitted...com/.well-known/acme-challenge/...omitted...'
[Mon Nov 21 17:40:23 CST 2016] timeout='1'
[Mon Nov 21 17:40:23 CST 2016] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --connect-timeout 1'
[Mon Nov 21 17:40:23 CST 2016] ret='0'
[Mon Nov 21 17:40:23 CST 2016] Skip for removelevel:
[Mon Nov 21 17:40:23 CST 2016] pid='13206'
[Mon Nov 21 17:40:23 CST 2016] GET
[Mon Nov 21 17:40:23 CST 2016] url='http://localhost:34443'
[Mon Nov 21 17:40:23 CST 2016] timeout='1'
[Mon Nov 21 17:40:23 CST 2016] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --connect-timeout 1'
[Mon Nov 21 17:40:23 CST 2016] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 7
[Mon Nov 21 17:40:23 CST 2016] ret='7'
[Mon Nov 21 17:40:23 CST 2016] nc listen error.
[Mon Nov 21 17:40:23 CST 2016] _clearupdns
[Mon Nov 21 17:40:23 CST 2016] Error: Couldn't resolve host "34443"
[Mon Nov 21 17:40:23 CST 2016] Dns not added, skip.
[Mon Nov 21 17:40:23 CST 2016] _on_issue_err
[Mon Nov 21 17:40:24 CST 2016] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Mon Nov 21 17:40:24 CST 2016] Diagnosis versions:

```
acme.sh  --issue .....   --debug 2
```
Here is the debug 2 output

[Mon Nov 21 17:54:33 CST 2016] ret='0'
[Mon Nov 21 17:54:33 CST 2016] original='{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:connection",
    "detail": "Could not connect to <...omitted...>.com",
    "status": 400
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/<...omitted...>",
  "token": "<...omitted...>",
  "keyAuthorization": "ydx2KEafL<...omitted...>1XFB4TJILidg",
  "validationRecord": [
    {
      "url": "http://<...omitted...>.com/.well-known/acme-challenge/<...omitted...>",
      "hostname": "<...omitted...>.com",
      "port": "80",                               **<<-- this could possible wrong, could be 34443**
      "addressesResolved": [
        "1.x.x.1"                                    **<<- this is confirmed right**
      ],
      "addressUsed": "1.x.x.1"
    }
  ]
}'

**Comment by Neilpang** [comment]
@keekychen 

`httpport` is only used for behind a reverse proxy or load balancer.

In the acme protocol,  the Letencrypt CA server  MUST connect to  `http://domain:80`  to verify your domaain.

So, the public tcp port `80` or `443` is required.

Only if you public `80` port is routed to your internal `8443` port,  then you can use `httpport`.

**Comment by keekychen** [comment]
@Neilpang 

Thank you very much for your quick response.

As you may know already, some ISPs (you know which one i am taking about:-)) will block standard 80/443 port open to internet for links such as a home DSL, therefore to get a cert for those lines you may need to use other non-standard ports or DNS auth, that is a sad story because some DDNS provider do not support TXT records, practically, not support TXT records beginning with "_".

Any suggestion?

**Comment by Neilpang** [comment]
@keekychen 

yes,  dns auth is the only option for you.  As your DDNS provider doesn't allow `_`,  here is a workaround for you.   

For example,   `a.com`  is the real domain you want,  which is hosted on a DDNS provider that doesn't allow `_`. 

You must have another domain `b.com`,  that is hosted on a DNS/DDNS provider that allow `_` in the txt record.

In your DDNS provider, make a `CNAME` :
```
_acme-challenge.a.com   ->  _acme-challenge.b.com
```

Then run dns manual mode:

```
acme.sh  --issue   -d a.com   --dns
```

When the txt record value is displayed,  please add the txt record to `_acme-challenge.b.com`.

Then retry:

```
acme.sh  --renew  -d  a.com 
```

It should be working for you.

For now you can only use dns manual mode,   I will fix it to work automatically soon.
