### ISSUE TITLE
Installing crontab with logfile

### ISSUE THREAD

**Issue by wizonesolutions** [Neilpang/acme.sh#417]
Is it possible to install a crontab that redirects to a log file instead of `/dev/null`? I don't see an install option for this.

**Comment by Neilpang** [comment]
Yes,  you don't need to care about the `>/dev/null` in the cron job.  we have `--log` option.

You just need to install/upgrade with `--log` option.

This will turn on the logging in future, the default log file is: `~/.acme.sh/acme.sh.log`
```
acme.sh  --upgrade   --log
```

If you can also specify a custom log file:

```
acme.sh  --upgrade  --log   /path/to/my.log
```

We also have `--log-level`

```
acme.sh  --upgrade  --log     --log-level 2
```


The `--log` option can be used in any command, such as `--issue` , `--renew` etc, not only `--upgrade`.

**Comment by Neilpang** [comment]
@wizonesolutions 

Once the log is turn on, any operations/cron  will be logged.
