### ISSUE TITLE
_debug / _debug2

### ISSUE THREAD

**Issue by sjau** [Neilpang/acme.sh#422]
Hi there

What is the actual difference between _debug and _debug2?

**Comment by Neilpang** [comment]
No difference.  just different debug levels.

**Comment by sjau** [comment]
when should _debug2 be used?

**Comment by Neilpang** [comment]
_debug is only for some critical debug info.   Mostly, some simple debug info.

_debug is for most detailed debug info.

**Comment by sjau** [comment]
I see, thx.
