### ISSUE TITLE
Error in standalone mode on OpenWrt/LEDE

### ISSUE THREAD

**Issue by tohojo** [Neilpang/acme.sh#424]
I'm trying to debug an issue with acme.sh as packaged for OpenWrt/LEDE. The package runs acme.sh in standalone mode. The letsencrypt server says it can't connect, but it seems to connect just fine. Could someone here take a look at the log and try to make sense of it?

The issue is here: https://github.com/openwrt/packages/issues/3544

And the debug log in question is in this comment: https://github.com/openwrt/packages/issues/3544#issuecomment-263102574

**Comment by Neilpang** [comment]
@tohojo  I'm checking the log now.
