### ISSUE TITLE
Add NO_TIMESTAMP to mute the timestamp from the output

### ISSUE THREAD

**Issue by Neilpang** [Neilpang/acme.sh#426]
Add NO_TIMESTAMP to mute the timestamp from the output

The output for now is like:
```
[Tue Nov 29 00:07:58 CST 2016] Installing to /home/neil/.acme.sh
[Tue Nov 29 00:07:58 CST 2016] Installed to /home/neil/.acme.sh/acme.sh
[Tue Nov 29 00:07:59 CST 2016] Installing alias to '/home/neil/.bashrc'
[Tue Nov 29 00:07:59 CST 2016] OK, Close and reopen your .....
```

The timestamp prefix may be not necessary for some cases.  

Add NO_TIMESTAMP to mute the timestamp from the output

**Comment by Neilpang** [comment]
@tohojo   @centminmod 

Please check the latest code.

Thanks.

**Comment by tohojo** [comment]
Ah, that's useful, thanks! I'll update the openwrt package and drop the patch :)

**Comment by Neilpang** [comment]
@tohojo 
Yes,  if you need any other help from my end, Please feel free to let me know.
