### ISSUE TITLE
acme.sh is a Let's Encrypt client, not a Certbot client :)

### ISSUE THREAD

**Issue by pde** [Neilpang/acme.sh#429]
Currently, this project's description says:
` An ACME Shell script, a certbot client: acme.sh https://acme.sh `
Probably it should be:
` An ACME Shell script, a Let's Encrypt client: acme.sh https://acme.sh `

Both Certbot and acme.sh are clients that use the Let's Encrypt service.

**Comment by Neilpang** [comment]
fixed,  thanks.
