### ISSUE TITLE
acme.sh --upgrade, Download error.

### ISSUE THREAD

**Issue by xiagw** [Neilpang/acme.sh#446]
Steps to reproduce
------------------
$ acme.sh --upgrade
[Tue Dec  6 15:18:28 CST 2016] Installing from online archive.
[Tue Dec  6 15:18:28 CST 2016] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Tue Dec  6 15:18:34 CST 2016] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 51
[Tue Dec  6 15:18:34 CST 2016] Download error.
[Tue Dec  6 15:18:34 CST 2016] Upgrade failed!

try to visit : https://github.com/Neilpang/acme.sh/archive/master.tar.gz

get 404,

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
try again.

```
acme.sh  --upgrade
```
