### ISSUE TITLE
Import data from certbot

### ISSUE THREAD

**Issue by IzzySoft** [Neilpang/acme.sh#450]
Due to a fresh installation on one of my machines, I'm considering to switch from the "official" LE/certbot to acme.sh. Is it somehow possible to import/migrate data, such as registration and existing certs/configs – and if so, any advice on how to best approach this?

**Comment by Neilpang** [comment]
There is no options to import/migrate from the official certbot.

You don't need to re-use the registration and existing certs.

Just remove certbot and forget it.

**Comment by IzzySoft** [comment]
Sure, that's a possible approach (as long as I can use the same mail address, and don't get nagging mails for the "forgotten certificates" associated with the certbot registrations). Though it would be nice for taking over configurations, so one would simply have to "renew" what's already there. But maybe in most/many cases, creating everything anew would be less effort than migration. I was just wondering as some of the other projects offer such "migration", I simply might have missed something here.

Thanks for your fast response!

**Comment by Neilpang** [comment]
@IzzySoft 

Here are some install options for you:

https://github.com/Neilpang/acme.sh/wiki/How-to-install#4-advanced-installation

**Comment by IzzySoft** [comment]
@Neilpang yes, thanks, I've seen that already (and marked it). In fact, that's what I plan to use.

If any of those files (`myaccount.key`, `myaccount.conf`, certs in the cert directory specified) already exist, would they be "adopted"? And are account key plus config compatible with those from certbot? The certs themselves should be (as both solutions use openssl), but I never checked if they are recreated from the scratch on each run anyway.

**Comment by Neilpang** [comment]
@IzzySoft 

Sorry,  I don't know about certbot format.   Please do not mix them.

**Comment by IzzySoft** [comment]
@Neilpang fair enough, thanks a lot! May I suggest leaving this issue open a little longer, so someone with the knowledge might jump in one day and provide a solution? I'd bet I'm not the only one interested – though I might no longer be affected until that happens :sunglasses:

**Comment by IndianNestingDoll** [comment]
I don't see much benefit actually... you can just request new certs...

**Comment by IzzySoft** [comment]
OK, maybe I didn't dig into it deep enough. Thought there might be some consequences when changing the "master key". If there aren't any, the only interesting thing remaining would be the configs, if one had multiple certs created. But just for me, if there are no other consequences, doing those few certs again is no big issue. Thanks for your attention nevertheless!

**Comment by maddes-b** [comment]
Sorry for being late to the party, but I wrote as script to convert the LE account data from certbot to acme.sh:
https://github.com/maddes-b/linux-stuff/tree/main/acme.sh

**Comment by IzzySoft** [comment]
A bit late for me indeed – but others will certainly appreciate it, so thanks @maddes-b!
