### ISSUE TITLE
AWS DNS integration does not work with temporary access keys from IAM Roles

### ISSUE THREAD

**Issue by AntonTimiskov** [Neilpang/acme.sh#453]
Or simple: AWS DNS integration does not support AWS IAM Roles

Scenario:
I have and AWS Instance run under IAM Role with all required rights to Route53.
As `acme.sh` does not support aws iam roles yet, i have to extract access key from them:
```
ROLE=`curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/`
curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/$ROLE> /tmp/aws.keys
export AWS_ACCESS_KEY_ID=`cat /tmp/aws.keys | jq -j '.AccessKeyId'`
export AWS_SECRET_ACCESS_KEY=`cat /tmp/aws.keys | jq -j '.SecretAccessKey'`
export AWS_SESSION_TOKEN=`cat /tmp/aws.keys | jq -j '.Token'`
```
and then run the acme:
```
acme.sh --issue --dns dns_aws --debug -d <domain>
```
It fails with an error:
```
[Tue Dec  6 17:30:59 UTC 2016] Response error:<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidClientTokenId</Code><Message>The security token included in the request is invalid.</Message></Error><RequestId></RequestId></ErrorResponse>
[Tue Dec  6 17:30:59 UTC 2016] invalid domain
[Tue Dec  6 17:30:59 UTC 2016] Error add txt for domain:_acme-challenge.<domain>
```
As I see the [dns_aws](https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_aws.sh) does not take into account the `AWS_SESSION_TOKEN` environment variable that is required to process the call to Route53 under the IAM Role Access Keys.

Do you have a plan to support the AWS IAM Roles or fix the issue with `AWS_SESSION_TOKEN`?

**Comment by Neilpang** [comment]
what is `x-amz-security-token` ?

what is the relation between `x-amz-security-token` and `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY` ?

**Comment by AntonTimiskov** [comment]
`x-amz-security-token` is the required part of signing REST API calls for temporary credentials:
http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#UsingTemporarySecurityCredentials

When you are working under IAM Role, to do any Amazon call you should acquire the temporary amazon access keys.
```
ROLE=`curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/`
curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/$ROLE
```
As a result you will get these keys:
```
{
  "Code" : "Success",
  "LastUpdated" : "2016-12-07T11:32:53Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "...",
  "SecretAccessKey" : "...",
  "Token" : "...b64-token...",
  "Expiration" : "2016-12-07T18:01:04Z"
}
```
There are 3 part: Key ID, Key Secret and a Token. And it is the difference with the using of access keys (key id and secret) for an IAM User. Three of them are required to call API under temp keys.
For example, you have to setup them in this way to call `aws s3 ls <bucket>` command:
```
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_SESSION_TOKEN=
```
Otherwise it will return the same error `The security token included in the request is invalid.`.
See the guide about environment variables for AWS CLI for additional information:
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-config-files
It describes where `AWS_SESSION_TOKEN` came to the topic.

BTW, I replaced `bash` to `sh` back.

**Comment by Neilpang** [comment]
>> AWS_SESSION_TOKEN – session token. A session token is only required if you are using temporary security credentials.

It's temporary  token ?  how long will it be alive ?

I don't think AWS_SESSION_TOKEN  is a must,  do you ?

**Comment by AntonTimiskov** [comment]
It's a temporary token, as a temporary key id and temporary secret.
It's a must to work under these temporary credentials (for IAM Role).
As you can see from the example, all of them will expire in about 7 hours and after that can't be used.

**Comment by AntonTimiskov** [comment]
http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html

**Comment by Neilpang** [comment]
Sorry, I don't want to support such temporary  token.

Since, the cert must be renewed in 60 days, we must use permanent keys.

**Comment by FernandoMiguel** [comment]
the temporary token is obtain by querying ec2 metadata

**Comment by Neilpang** [comment]
@FernandoMiguel 

Yes, if the temp token can be obtained from the permanent key,  it doesn't make any sense for the users to specify a temp token from the command line like:
```
export AWS_SESSION_TOKEN="asdfsfdsfdsfsfd"
```

I think if it's a must to support temp token,   we must  obtain the temp token automatically.  But in the PR, I don't see such steps.

**Comment by Neilpang** [comment]
@FernandoMiguel

And I want to make things simple,  if permanent key is enough, it doesn't make any sense to use such temp tokens.

**Comment by FernandoMiguel** [comment]
it has to do with the way AWS deals with roles.
when an user assumes a role, they dont have any permanent keys for that resource, the role does.
and those tonkes get rotated every so often so incase a resource is compromised, the keys go out of rotation.

i havent implemented API calls via user assumed roles, so I cant speak on the matter too much, although I'm setting up IAM policies exactly for that purpose for work this sprint, so i'll know more about it soon.


I think @AntonTimiskov  can provide better feedback than me currently, and probably improve the PR to meet your requirement.

**Comment by AntonTimiskov** [comment]
@Neilpang I agree, that exposing temporary credentials (including the token) is not the good way as environment vars, and it does not make any sense to store them permanently. And It will not work if you schedule the cron job.
So, the feature should be "Support of AWS IAM Roles" (you have only support AWS IAM Users now).
But technically it's a right way to go:
get the temporary credentials from the aws metadata api, add the security header to aws calls, forget about the temp credentials until next time when it generates new one.

So, my plan will be to implement the feature for you in some future. It will check is it run under Role, and will not ask to specify access key id and secret explicitly when you are under role. And do all the job in that way i described.
Will it work for you, @Neilpang ?

**Comment by ksperling** [comment]
The simple way to do this would be to just use the aws cli instead of all that custom shell code to sign and perform the AWS api requests manually. That way all the various authentication methods, roles etc will be automatically supported in a future-proof way.

**Comment by mimmus** [comment]
What is the status of this issue?
Looking at code, it seems solved but I'm still getting:
```
[Tue Nov  2 12:32:23 UTC 2021] Response error:<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>AccessDenied</Code><Message>User: arn:aws:sts::970737678499:assumed-role/MyEC2SSMInstanceRole/i-06ece52330e0168cc is not authorized to perform: route53:ListHostedZones</Message></Error><RequestId>83ffad77-cfc8-4311-a447-7b51301a7a75</RequestId></ErrorResponse>
[Tue Nov  2 12:32:23 UTC 2021] invalid domain
[Tue Nov  2 12:32:25 UTC 2021] Error add txt for domain:_acme-challenge.acme.cervedgroup.com
```

**Comment by cidrbl0ck** [comment]
Same, And I'm attempting to use RolesAnywhere which for this is basically the same thing. Requiring the use of permanent IAM User keys is rather silly.
