### ISSUE TITLE
PKCS #12

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#459]
how can a PKCS #12 cert be issued with acme.sh ?

**Comment by Neilpang** [comment]
`pkcs12`   IS   `pfx`

see:  https://github.com/Neilpang/acme.sh/wiki#3-how-to-get-pkcs12pfx-format

**Comment by FernandoMiguel** [comment]
@Neilpang that documentations seems to be insufficient 

$ acme.sh --test  --toPkcs  -d plexpfx.imperialus.house 
[Fri  9 Dec 2016 12:35:23 GMT] Using stage api:https://acme-staging.api.letsencrypt.org
Error opening input file /Users/fernando/.acme.sh/plexpfx.imperialus.house/plexpfx.imperialus.house.cer
/Users/fernando/.acme.sh/plexpfx.imperialus.house/plexpfx.imperialus.house.cer: No such file or directory

**Comment by FernandoMiguel** [comment]
*after*..... one of these days i'll learn how to read

**Comment by FernandoMiguel** [comment]
will the pfx be issued once a cert is renewed?
or should i had this to the post hook?

**Comment by Neilpang** [comment]
@FernandoMiguel  
You must issue the cert first.

```
acme.sh --issue   -d  mydomain.com  ......
```

Then convert it to pkcs12 format:
```
acme.sh  --topkcs  -d mydomain.com   ......
```

Yes,  you must convert it in the `--post-hook` or `--renew-hook`.

It is suggest that,  you read a hook file `renew-hook.sh`.

You can do anything in that file.

Thanks.
