### ISSUE TITLE
指定非80端口报错

### ISSUE THREAD

**Issue by guigeng** [Neilpang/acme.sh#462]
acme.sh  --issue  -d d.com  --standalone --httpport 88
[Mon Dec 12 13:41:11 CST 2016] Standalone mode.
[Mon Dec 12 13:41:11 CST 2016] Single domain='d.com'
[Mon Dec 12 13:41:11 CST 2016] Getting domain auth token for each domain
[Mon Dec 12 13:41:11 CST 2016] Getting webroot for domain='d.com'
[Mon Dec 12 13:41:11 CST 2016] _w='no'
[Mon Dec 12 13:41:11 CST 2016] Getting new-authz for domain='d.com'
[Mon Dec 12 13:41:17 CST 2016] The new-authz request is ok.
[Mon Dec 12 13:41:17 CST 2016] Verifying:d.com
[Mon Dec 12 13:41:17 CST 2016] Standalone mode server
[Mon Dec 12 13:41:23 CST 2016] Pending
[Mon Dec 12 13:41:26 CST 2016] d.comVerify error:Could not connect to d.com
GET / HTTP/1.1
User-Agent: acme.sh/2.6.5 (https://github.com/Neilpang/acme.sh)
Host: localhost:88
Accept: */*

[Mon Dec 12 13:41:26 CST 2016] Please check log file for more details: /root/.acme.sh/acme.sh.log

使用certbot正常，但是没找到ec证书的选项
certbot certonly --standalone --preferred-challenges http-01 --http-01-port 88 -d d.com
这个命令就正常了。

**Comment by guigeng** [comment]
后来试了，又不行。有点搞不懂。

不明白问题出在哪里。

**Comment by Neilpang** [comment]
必须使用 80/443 端口.

除非你读懂了这段话:
https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert#2-standalone-mode

否则千万不要用 --httpport 88
