### ISSUE TITLE
dns_me not finding root zone

### ISSUE THREAD

**Issue by rosenbergj** [Neilpang/acme.sh#463]
Debug log
-----------------

```
./acme.sh --debug 2 --issue --dns dns_me -d jabber.solutionsforprogress.com

```
[snip]
[Mon Dec 12 11:58:51 EST 2016] d_api='/home/jrosenberg/working/letsencrypt-dns/acme.sh/dnsapi/dns_me.sh'
[Mon Dec 12 11:58:51 EST 2016] Found domain api file: /home/jrosenberg/working/letsencrypt-dns/acme.sh/dnsapi/dns_me.sh
[Mon Dec 12 11:58:51 EST 2016] 1:ME_Key='redacted'
[Mon Dec 12 11:58:51 EST 2016] 2:ME_Secret='redacted'
[Mon Dec 12 11:58:51 EST 2016] First detect the root zone
[Mon Dec 12 11:58:51 EST 2016] name?domainname=jabber.solutionsforprogress.com
[Mon Dec 12 11:58:51 EST 2016] GET
[Mon Dec 12 11:58:51 EST 2016] url='https://api.dnsmadeeasy.com/V2.0/dns/managed/name?domainname=jabber.solutionsforprogress.com'
[Mon Dec 12 11:58:51 EST 2016] timeout
[Mon Dec 12 11:58:51 EST 2016] _CURL='curl -L --silent --dump-header /home/jrosenberg/.acme.sh/http.header  --trace-ascii /tmp/tmp.O80Mov6lee '
[Mon Dec 12 11:58:51 EST 2016] ret='0'
[Mon Dec 12 11:58:51 EST 2016] response='{error: ["Request sent with date header too far out of sync.  Difference in times is -37706, header value is 1481561931000"]}'
[Mon Dec 12 11:58:51 EST 2016] name?domainname=solutionsforprogress.com
[Mon Dec 12 11:58:52 EST 2016] GET
[Mon Dec 12 11:58:52 EST 2016] url='https://api.dnsmadeeasy.com/V2.0/dns/managed/name?domainname=solutionsforprogress.com'
[Mon Dec 12 11:58:52 EST 2016] timeout
[Mon Dec 12 11:58:52 EST 2016] _CURL='curl -L --silent --dump-header /home/jrosenberg/.acme.sh/http.header  --trace-ascii /tmp/tmp.Cc6aZjKhHQ '
[Mon Dec 12 11:58:52 EST 2016] ret='0'
[Mon Dec 12 11:58:52 EST 2016] response='{error: ["Request sent with date header too far out of sync.  Difference in times is -37249, header value is 1481561931000"]}'
[Mon Dec 12 11:58:52 EST 2016] name?domainname=com
[Mon Dec 12 11:58:52 EST 2016] GET
[Mon Dec 12 11:58:52 EST 2016] url='https://api.dnsmadeeasy.com/V2.0/dns/managed/name?domainname=com'
[Mon Dec 12 11:58:52 EST 2016] timeout
[Mon Dec 12 11:58:52 EST 2016] _CURL='curl -L --silent --dump-header /home/jrosenberg/.acme.sh/http.header  --trace-ascii /tmp/tmp.Aa770EGJ6N '
[Mon Dec 12 11:58:52 EST 2016] ret='0'
[Mon Dec 12 11:58:52 EST 2016] response='{error: ["Request sent with date header too far out of sync.  Difference in times is -37800, header value is 1481561932000"]}'
[Mon Dec 12 11:58:52 EST 2016] invalid domain
[Mon Dec 12 11:58:52 EST 2016] Error add txt for domain:_acme-challenge.jabber.solutionsforprogress.com
[Mon Dec 12 11:58:52 EST 2016] pid
[Mon Dec 12 11:58:52 EST 2016] _clearupdns
[Mon Dec 12 11:58:52 EST 2016] Dns not added, skip.
[Mon Dec 12 11:58:52 EST 2016] _on_issue_err
[Mon Dec 12 11:58:52 EST 2016] Please check log file for more details: /home/jrosenberg/.acme.sh/acme.sh.log

**Comment by Neilpang** [comment]
your time is not correct.

Please make sure you time is right.

You can also try it on another server.

**Comment by rosenbergj** [comment]
You're right; I was less than a minute off but that was enough to cause the problem. Sorry for the bad issue.
