### ISSUE TITLE
add "shellcheck" for robust code ?

### ISSUE THREAD

**Issue by ka7** [Neilpang/acme.sh#467]
For fun let it run thru shellcheck [1] @ codeclimate.
Here the results. [2] ... sure, might contain lots of pedantic tips; 
(there is also github hook to automate that..)

1] https://github.com/koalaman/shellcheck
2] https://codeclimate.com/github/ka7/acme.sh/compare/with_shellcheck

**Comment by Neilpang** [comment]
we already used shellcheck in the CI.
