### ISSUE TITLE
certhome opt stopped working

### ISSUE THREAD

**Issue by pierreozoux** [Neilpang/acme.sh#469]
I use acme to automatically provision certs for my [haproxy setup](https://github.com/indiehosters/haproxy).

Here is how letsencrypt is installed: https://github.com/indiehosters/docker-letsencrypt/blob/master/Dockerfile
(certhome is specified [here](https://github.com/indiehosters/docker-letsencrypt/blob/master/Dockerfile#L16) )

If you `docker run -it --entrypoint=bash indiehosters/letsencrypt` and `cat /usr/bin/acme.sh`, you'll see no reference to `certhome`.
I guess this configuration should be saved here.

As a result, when I provision a new cert, it is saved in `/root/.acme.sh/$domain` which is not the expected behavior.

Let me know how can I help to solve this, and maybe add regression tests.
(I tried to look for the code, without much success.)

**Comment by Neilpang** [comment]
If you don't install `acme.sh` in the default home path,  then you should add the `--home` parameter with any command you use.  
for example
```
/usr/bin/acme.sh  --home /usr/bin/  --issue -d example.com .......
```

here should be an  `account.conf` file in the specified home path:  `/usr/bin/account.conf`

In this account.conf file,  it records the `--certhome` value.

**Comment by pierreozoux** [comment]
Thanks for your explanation.
I updated the wiki to reflect this: https://github.com/Neilpang/acme.sh/wiki/Options-and-Params/_compare/433c48427f67f2584830549a2e3b7742af341533...c310bf65fb4f9f10a0c00189bd6ce0d4480e0d40

Is it possible that it was working last week? (I'm sure it was, but well, maybe I missed something :) )

Please close the issue once you read it.

Thanks again and have a nice day!

Pierre

**Comment by Neilpang** [comment]
@pierreozoux 

Yes, it was working for a small period of time,  but I disabled it soon.

Thanks you.
