### ISSUE TITLE
reload nginx , https domain can't access

### ISSUE THREAD

**Issue by samhou1988** [Neilpang/acme.sh#470]
hi, 
when I use the shell script, I have something happened,

`./acme.sh --installcert -d happbibo.com --keypath /etc/nginx/ssl/happbibo.key --fullchainpath /etc/nginx/ssl/fullchain.cer --reloadcmd "nginx -s reload"`

`
    server_name  www.happbibo.com;

    ssl on;
    ssl_certificate /etc/nginx/ssl/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/happbibo.key;`

nginx -s reload

I can't access the website `https://www.happbibo.com/`

**Comment by Neilpang** [comment]
did you see any error when you use the `--installcmd` command ?

You can use `nginx -t`  to check where the error is.

Thanks.

**Comment by TerraX-net** [comment]
Do you use acme.sh as root or is your user in /etc/sudoers ? "sudo service nginx reload"
