### ISSUE TITLE
acme.sh can't verify domain because apache not accepting hyphens in verification URL path

### ISSUE THREAD

**Issue by oparviai** [Neilpang/acme.sh#472]
Hello. I have an issue that acme.sh fails the domain verification step because the local Apache doesn't agree to properly serve the acme.sh verification files.

The specific issue is that I have virtual WWW domain running on web hotel's Apache server, and Apache doesn't seem to accept hyphens in virtual domain name url paths: Accessing a WWW page works ok if the URL doesn't have hyphens. Otherwise identical attempt and access configuration with an URL having hyphens does not work.

Example: 
1. http://www.example.com/.wellknown/acmechallenge/test.html => this works ok
2. http://www.example.com/.well-known/acme-challenge/test.html => Apache rejects the request with Not Found (404) error. Chmod settings are identical to case (1).

Accordingly, if there's not specific reason to use hyphens in the acme challenge path names, could you remove hyphens from the URLS as they seem to cause problem.

Apache version is 2.4.23, running on Debian 4.6.3. server

acme.sh log:

[Sat Dec 17 13:11:35 EET 2016] www.[example].com:Verify error:Invalid response from http://www.[example].net/.well-known/acme-challenge/NRLvMdiDy8AV0lwnFGj7iQ8EU5YqEYxzs-Pg9VmaRLM [212.47.208.162]: 404

**Comment by Neilpang** [comment]
The hyphen is required by acme protocol.

Can you please provide your full command line and and debug log ?

**Comment by oparviai** [comment]
I see, if it's in the protocol then can't assumingly do much about this and I'll need to look some other solution for SSLs. Thanks for quick response, you can close this issue.
