### ISSUE TITLE
Problem with the "install" script and ERROR: certificate common name

### ISSUE THREAD

**Issue by ArfyFR** [Neilpang/acme.sh#476]
A problem with the certificate 'dedif.acme.sh' which does not match 'get.acme.sh' ?

Steps to reproduce
------------------
Get the installer by hand
wget -O -  https://get.acme.sh >> acmeinstall.sh

And inside the sh I also had to add `--no-check-certificate' on wget lines

Debug log
-----------------
--2016-12-19 17:41:57--  https://get.acme.sh/
Resolving get.acme.sh... 195.154.91.106
Connecting to get.acme.sh|195.154.91.106|:443... connected.
ERROR: certificate common name `dedif.acme.sh' doesn't match requested host name `get.acme.sh'.
To connect to get.acme.sh insecurely, use `--no-check-certificate'.

**Comment by Neilpang** [comment]
what is your wget version ?

Maybe it doesn't support SNI.

tell me your OS and wget version.

**Comment by Neilpang** [comment]
fixed,  I just updated the cert of get.acme.sh

**Comment by ArfyFR** [comment]
It is
GNU Wget 1.12 built on linux-gnu
Debian GNU/Linux 6.0.10

I'll try later, for the moment it have the same problem
```
wget -O - https://get.acme.sh >> acmeinstall.sh111
--2016-12-21 13:32:36--  https://get.acme.sh/
Resolving get.acme.sh... 195.154.91.106
Connecting to get.acme.sh|195.154.91.106|:443... connected.
ERROR: certificate common name `dedif.acme.sh' doesn't match requested host name `get.acme.sh'.
To connect to get.acme.sh insecurely, use `--no-check-certificate'.
```

**Comment by Neilpang** [comment]
That's the problem.
SNI support in wget is added in v1.14
https://stackoverflow.com/questions/36559821/wget-tls-sni-support-setting-server-name

**Comment by ArfyFR** [comment]
Ok, I'll ask the admins to update it thanks
