### ISSUE TITLE
Solaris 10 Install cron job failed

### ISSUE THREAD

**Issue by teschulz** [Neilpang/acme.sh#480]
Installing the cron job fails on Solaris10. The code in question is
    if _exists uname && uname -a | grep solaris >/dev/null; then
      crontab -l | {
        cat
        echo "0 0 * * * $lesh --cron --home \"$LE_WORKING_DIR\" > /dev/null"
      } | crontab --
    else

But on Solaris 10 uname -a returns:
SunOS seahorse 5.10 Generic_142910-17 i86pc i386 i86pc

Changing solaris to SunOS fixes the problem. Note that it is possible that later versions of Solaris
would return solaris.

**Comment by Neilpang** [comment]
This is our testing solaris machine returns:

```
root@solaris:~# uname -a
SunOS solaris 5.11 11.3 i86pc i386 i86pc

```


I will try to fix it soon.
