### ISSUE TITLE
Solaris 10 tar: z: unknown function modifier

### ISSUE THREAD

**Issue by teschulz** [Neilpang/acme.sh#481]
On Solaris 10, tar fails with tar: z: unknown function modifier. The code involved is:

    _info "Extracting $localname"
    tar xzf $localname

But Solaris 10 tar does not understand modifier 'z'. As I have the gnu utilities installed, I just
replaced tar with gtar. But perhaps a better fix would be to use gzcat piped into tar.

I don't know if the tar in later versions of Solaris understand 'z' or not.

**Comment by Neilpang** [comment]
The `z` options is also working on my solaris machine.

Anyway, I will try to fix it later.
