### ISSUE TITLE
Question: using the same LetsEncrypt account on multiple servers?

### ISSUE THREAD

**Issue by djvdorp** [Neilpang/acme.sh#483]
Let's say that I have used `acme.sh` to get a certificate for a specific server A, hosting my subdomain `monitoring.example.com`. Now I want to also get a certificate for server B, hosting my domain `www.example.com`. I tried to find this in the documentation/wiki but couldn't find it.

In my head it would make sense to use the same [LetsEncrypt account](https://letsencrypt.org/docs/account-id/) for that, but in the case of `acme.sh`, what files should I copy/scp over from server A to server B? And would that be something you recommend or not?

List of possibly relevant files:
- `~/.acme.sh/account.conf`
- `~/.acme.sh/account.json`
- `~/.acme.sh/account.key`

**Comment by Neilpang** [comment]
It's recommended not to copy account (private) key across servers.

You can just install acme.sh on serverA, then issue certs for serverA.
Then just install acme.sh on ServerB, and issue certs for serverB.

That's ok.

**Comment by djvdorp** [comment]
@Neilpang thank you for your quick reply! I just wanted to ask this, because in my head it made a lot of sense to have all the certs for an organisation in one account, but it seems that the concept of "accounts" in LetsEncrypt is different than accounts on other websites then. 

If I however would really want this, it is probably possible to copy accounts by copying over the above 3 files, correct? (I also need to know this so that I know if it is enough to back up these 3 files, together with the generated certs + keys, instead of the full acme.sh code and repository, in case of a reinstall for example)

**Comment by Neilpang** [comment]
yes,
Copy the 3 files to the same dir to serverB.

**Comment by djvdorp** [comment]
@Neilpang would that be the 3 files I meant in my original question:

- `~/.acme.sh/account.{conf,json,key}`

or

- `~/.acme.sh/ca/acme-v01.api.letsencrypt.org/account.{json,key}` (I think these are new?)

Because I think they are not identical, and I am unsure about which one fulfils which role?

**Comment by Neilpang** [comment]
The 3 files used to be in `~/.acme.sh/*`,  but now I moved them to `~/.acme.sh/ca/acme-v01.api.letsencrypt.org/`.

Please use the new location.

**Comment by djvdorp** [comment]
@Neilpang okay, because my `~/.acme.sh/ca/acme-v01.api.letsencrypt.org/` only has 2 out of the 3 files it seems (only `account.{json,key}` and `ca.conf` but not `account.conf`), hence me wondering.

**Comment by Neilpang** [comment]
yes,  `account.conf`  is still in the old location. 

Actually, you just need to copy  2 files: account.{key|json}
