### ISSUE TITLE
Restrict key files to user access

### ISSUE THREAD

**Issue by kaie** [Neilpang/acme.sh#488]
The account.key and domain.key files created by --issue are group readable and world readable.
I suggest, after you create any key file, run "chmod 600 file.key" on that filename, to restrict read access.

**Comment by Neilpang** [comment]
We have discussed that before.

The default home `.acme.sh` is in your home dir,  nobody else can read your home dir.

**Comment by sercxanto** [comment]
I noticed that after installing with "--installcert" the file copied to "--keypath" is world readable. Wouldn't it make sense to restrict the access after copying outside of home dir?

**Comment by Neilpang** [comment]
@sercxanto 

We don't use `cp` to copy the cert file.  we just write the key file content to the target path. This would not change the permissions of the target key file.

https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L3321
```
cat "$CERT_KEY_PATH" >"$Le_RealKeyPath"
```

**Comment by sercxanto** [comment]
Ah, OK. Understood.Thanks  :-)

I just created a PR for README.md to make the behaviour clear: https://github.com/Neilpang/acme.sh/pull/499

**Comment by elyscape** [comment]
@Nielpang
>We don't use `cp` to copy the cert file. we just write the key file content to the target path. This would not change the permissions of the target key file.

This is true, but we _do_ use `cp` [to make the backup][backup]. These calls should probably be modified to use `cp -p`, which preserves the file ownership and mode.

[backup]: https://github.com/Neilpang/acme.sh/blob/2.6.4/acme.sh#L3282

**Comment by Neilpang** [comment]
@elyscape   Good.
We used to use `cp -p`, but it was not supported on Proxmox.
Anyway, I will move the backup cert/key into the acme home dir soon.

Thanks.

**Comment by elyscape** [comment]
That's weird. `cp -p` is the POSIX standard. What version of `cp` is on Proxmox?
