### ISSUE TITLE
可以增加  给acme设置代理的功能吗？

### ISSUE THREAD

**Issue by xjdata** [Neilpang/acme.sh#489]
可以增加  给acme设置代理的功能吗？
比如 acme自身的自动更新，以及生成，更新证书时使用的代理。
谢谢

**Comment by Neilpang** [comment]
你可以在网上搜一下 curl 如何配置代理.

**Comment by xiagw** [comment]
$ curl --help |grep proxy
     --noproxy       List of hosts which do not use proxy
 -x, --proxy [PROTOCOL://]HOST[:PORT]  Use proxy on given port
     --proxy-anyauth  Pick "any" proxy authentication method (H)
     --proxy-basic   Use Basic authentication on the proxy (H)
     --proxy-digest  Use Digest authentication on the proxy (H)
     --proxy-negotiate  Use HTTP Negotiate (SPNEGO) authentication on the proxy (H)
     --proxy-ntlm    Use NTLM authentication on the proxy (H)
     --proxy-service-name NAME  SPNEGO proxy service name
 -U, --proxy-user USER[:PASSWORD]  Proxy user and password
     --proxy1.0 HOST[:PORT]  Use HTTP/1.0 proxy on given port
 -p, --proxytunnel   Operate through a HTTP proxy tunnel (using CONNECT)
     --socks4 HOST[:PORT]  SOCKS4 proxy on given host + port
     --socks4a HOST[:PORT]  SOCKS4a proxy on given host + port
     --socks5 HOST[:PORT]  SOCKS5 proxy on given host + port
     --socks5-hostname HOST[:PORT]  SOCKS5 proxy, pass host name to proxy
     --socks5-gssapi-service NAME  SOCKS5 proxy service name for GSS-API

**Comment by xjdata** [comment]
可是自动更新，以及生成，更新证书时   是acme自动的。 要修改acme.sh吗？ 给curl都加上代理配置？

**Comment by Neilpang** [comment]
可以修改 `.curlrc`  或者使用环境变量:
http://stackoverflow.com/a/7559129/7250439
https://stackoverflow.com/questions/9445489/linux-curl-command-with-proxy

**Comment by xjdata** [comment]
谢谢。
