### ISSUE TITLE
Add support for --user-agent flag

### ISSUE THREAD

**Issue by centminmod** [Neilpang/acme.sh#49]
Possible to add support for the official client's `--user-agent=` ?

**Comment by Neilpang** [comment]
Is there any use case that one must customize the user agent ?

**Comment by centminmod** [comment]
well i am looking at integrating your le client into my LEMP stack and it currently uses official le client and passes a user agent

so looking for an equivalent

**Comment by Neilpang** [comment]
I see.  But I wonder if there is a reason that you need to use a customized  user agent ?

**Comment by centminmod** [comment]
there's possibly user agent stats are tracked at LE side so they know where client and integrations are coming from via the user agent so would be nice to have that in place and supported

**Comment by Neilpang** [comment]
UserAgent supported   bbbdcb091adcf018891a60fe48a7e0a2e81d10f6

We have a new config in the `account.conf`
```
#USER_AGENT="le.sh client: https://github.com/Neilpang/le"
```

**Comment by Neilpang** [comment]
`--useragent` parameter is added.  635695ec84485f83781bf435b6f0009653430b7d

When `--install` command or `--issue` command,  you can specify `--useragent`.   The useragent will be saved in the account.conf.

Everytime you specify a new `--useragent`, the value will be updated.
