### ISSUE TITLE
Crontab not found when installing on synology 212j running DSM 5.2-5592

### ISSUE THREAD

**Issue by Compstuff** [Neilpang/acme.sh#490]
cron is on the synology and has other jobs running
curl https://get.acme.sh | sh 
installation error:
(also ran curl https://get.acme.sh | sh --force and got the same error)

It is recommended to install crontab first. try to install 'cron, crontab, crontabs or vixie-cron'.
We need to set cron job to renew the certs automatically.
Otherwise, your certs will not be able to be renewed automatically.
Please add '--force' and try install again to go without crontab.
./acme.sh --install --force
Pre-check failed, can not install.

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/Synology-NAS-Guide

**Comment by Neilpang** [comment]
```
export  FORCE=1
curl  https://get.acme.sh | sh

```
