### ISSUE TITLE
unclear csr format requirements

### ISSUE THREAD

**Issue by dbabits** [Neilpang/acme.sh#492]
My certificate is in .pem format( created by gogs, but it's probably not important):

```
pi@raspberrypi:~/bin/gogs $ cat cert.pem

-----BEGIN CERTIFICATE-----
MIIDHDCCAgSgAwIBAgIQAWBK/S37LfqTMleTJy8IJzANBgkqhkiG9w0BAQsFADAh
```

It's not clear what format is required for acme.sh:

```
1996195616:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: CERTIFICATE REQUEST
[Mon Dec 26 23:03:54 EST 2016] Can not read subject from csr: /home/pi/bin/gogs/cert.pem


```
I tried this conversion, but .crt wasn't accepted either.
```
/bin/gogs $ openssl x509 -outform der -in cert.pem -out cert.crt
```

Could you specify format and if possible conversion commands:

**Comment by Neilpang** [comment]
It's not a CSR:

```
-----BEGIN CERTIFICATE-----
```

It's a certificate.

Please give the correct csr file.

**Comment by dbabits** [comment]
Could you help out in the docs with this? I understand that perhaps it's common knowledge, but it would be very helpful if the docs at least pointed in the right direction.
There are multiple formats of keys, etc, and I have spent a lot of time trying.
Example:
```
pi@raspberrypi:~/bin/gogs $ openssl req -new -sha256 -inform PEM -key /home/pi/bin/gogs/cert.pem -out raspberrypi.csr
unable to load Private Key
1996240672:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: ANY PRIVATE KEY

```
This command works and provides output:
```
pi@raspberrypi:~/bin/gogs $ openssl x509 -text -inform PEM -in cert.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
......................
```

**Comment by Neilpang** [comment]
Your problem is not about the format, but about the correct file.

You are using a certificate file as a csr file.

Please use the correct file first.

**Comment by dbabits** [comment]
looks like I moved past this hurdle - thanks. Having a different issue, will open a separate one.
