### ISSUE TITLE
--days working properly ?

### ISSUE THREAD

**Issue by centminmod** [Neilpang/acme.sh#498]
Is this still correct, for quicker cron renewal tests i set --days to 21 instead of default 60

```
RENEWDAYS=21
./acme.sh --install --days $RENEWDAYS
```

then issued ssl cert

but cronjob isn't renewing after 21st day ?

```
"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"
[Wed Dec 28 21:19:27 UTC 2016] Renew: 'mysqlmymon.com'
[Wed Dec 28 21:19:27 UTC 2016] Skip, Next renewal time is: Fri Feb 10 00:00:21 UTC 2017
[Wed Dec 28 21:19:27 UTC 2016] Add '--force' to force to renew.
[Wed Dec 28 21:19:27 UTC 2016] Skipped mysqlmymon.com
```

my acme.sh wrapper for acmetool.sh checkdates output shows cert expiry days left etc
```
addons/acmetool.sh checkdates
----------------------------------------------
nginx installed
----------------------------------------------

/usr/local/nginx/conf/ssl/mysqlmymon.com/mysqlmymon.com-acme.cer
SHA1 Fingerprint=663D4311FCBFD214075E66EC7399CE6B8E9F0E55
certificate expires in 52 days on 19 Feb 2017

----------------------------------------------
acme.sh obtained
----------------------------------------------

/root/.acme.sh/mysqlmymon.com/mysqlmymon.com.cer
SHA1 Fingerprint=663D4311FCBFD214075E66EC7399CE6B8E9F0E55
[ below certifcate transparency link is only valid ~1hr after issuance ]
https://crt.sh/?sha1=663D4311FCBFD214075E66EC7399CE6B8E9F0E55
certificate expires in 52 days on 19 Feb 2017
```

where do i look to see what acme.sh is reading for the threshold of 21 or 60 days ?

**Comment by Neilpang** [comment]
Yes,  but `--days`  can not work with `--install` command.  it only works with `--issue` or `--renew`.

The renew days is recorded in the domain.conf,  not the account.conf.  So there must be a domain.

Yes, if you want to change the renew days globally,  you can manually edit account.conf, and `Le_RenewalDays` in it.

**Comment by centminmod** [comment]
Ah i see. Could of sworn i saw --days on install command at one time in the official documentation ? But thanks @Neilpang for clarification :)

would setting Le_RenewalDays in account.conf override the domain.conf renew days recorded ?

**Comment by Neilpang** [comment]
>> would setting Le_RenewalDays in account.conf override the domain.conf renew days recorded ?

Yes, I think so.

**Comment by centminmod** [comment]
Thanks @Neilpang for clarification :)

**Comment by Neilpang** [comment]
Can you please close this issue ?
