### ISSUE TITLE
readlink use still broken on Darwin

### ISSUE THREAD

**Issue by ahl** [Neilpang/acme.sh#505]
Steps to reproduce
------------------

LE_WORKING_DIR=./config acme.sh/acme.sh --test --issue --dns dns_aws -d foo.com

The command completes but it ignores the `dns_aws` component. Apple's `readlink` produces no output when invoked on a non-symlink; it's use in `_readlink` appears to be incorrect.

Let me know if you want a PR.

Debug log
-----------------

N/A

**Comment by ahl** [comment]
Also note that there's a use of `readlink -f` around line 4350:

```sh
      --ca-bundle)
        _ca_bundle="$(readlink -f "$2")"
        CA_BUNDLE="$_ca_bundle"
        shift
        ;;
```

**Comment by Neilpang** [comment]
Do you have any advice to implement the function `_readlink()` ?

**Comment by ahl** [comment]
Maybe something like this from http://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-osx:

```sh
realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}
```

If you don't actually need the canonical path, but you just want an absolute path you could change
`if _startswith "$_rf" "\./$PROJECT_ENTRY"; then`
to
`if ! _startswith "$_rf" "/"; then`
