### ISSUE TITLE
multiple deploy scripts?

### ISSUE THREAD

**Issue by msimerson** [Neilpang/acme.sh#508]
I have a cert(s) that needs to be deployed to several daemons: haproxy (HTTPS), dovecot (IMAPS), and haraka (SMTPS). I had already created a deployment script for haproxy so I created two more for dovecot and haraka before realizing that the automatic renewal and deployment doesn't work with more than one deployment script.

Possible solutions:
* create a "mail-server" deployment script that knows how to deploy to all three targets.
* a dummy deployment script that wraps the haproxy, dovecot, and haraka scripts
* --deploy haproxy --deploy dovecot --deploy haraka
    * which does something like:
    * for h in haproxy dovecot haraka do /root/.acme.sh/acme.sh --deploy -d mail.example.com --deploy-hook $h; done
* other?

Thoughts?

**Comment by Neilpang** [comment]
`a dummy deployment script that wraps the haproxy, dovecot, and haraka scripts`  should be a good choice for now.

I will add support for multiple  `--deploy-hook` for a single cert soon.

**Comment by msimerson** [comment]
Thanks!

On a related note, I'm considering how to automate the deployment for many domains while using just a few (apache, lighttpd, nginx) deployment scripts. Across a few httpd installs, the path to where to installs the certs will vary as will the restart command. It seems that storing a map of paths and commands (indexed by domain) in the deploy script could then choose the correct paths and restart command based on _cdomain.

Reasonable as well?

**Comment by msimerson** [comment]
The wrapper script, for anyone else that needs this feature before official support is available:

```sh
#!/usr/local/bin/bash

#domain keyfile certfile cafile fullchain
mailtoaster_deploy() {
	_cdomain="$1"
	_ckey="$2"
	_ccert="$3"
	_cca="$4"
	_cfullchain="$5"

	for _target in haraka haproxy dovecot
	do
		echo "deploying $_target"
		. "/root/.acme.sh/deploy/$_target"
		${_target}_deploy $* || return 2
	done

	return 0
}
```

Now when `--deploy mailtoaster` deploy script is run, the cert is installed for all 3 of the daemons that need it.
