### ISSUE TITLE
install do different path

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#510]
# acme.sh --installcert -d DOMAIN.uk --keypath /etc/ssl/private/DOMAIN.uk/DOMAIN.key.pem --fullchainpath /etc/ssl/private/DOMAIN.uk/DOMAIN.fullchain.pem --reloadcmd     "service nginx force-reload" --test
[Thu Jan  5 15:49:47 UTC 2017] Using stage api:https://acme-staging.api.letsencrypt.org
[Thu Jan  5 15:49:47 UTC 2017] Installing key to:/etc/ssl/private/DOMAIN.uk/DOMAIN.key.pem
cat: /root/.acme.sh/DOMAIN.uk/DOMAIN.key: No such file or directory
[Thu Jan  5 15:49:47 UTC 2017] Installing full chain to:/etc/ssl/private/DOMAIN.uk/DOMAIN.fullchain.pem
cat: /root/.acme.sh/DOMAIN.uk/fullchain.cer: No such file or directory

seems there's an issue with the cat command there

**Comment by Neilpang** [comment]
Is the cert a ECC cert ?

**Comment by FernandoMiguel** [comment]
No, regular RSA.
Something wasnt ok with the issue command.

using standalone seems to have worked
