### ISSUE TITLE
Add support for Debian without systemd?

### ISSUE THREAD

**Issue by ovizii** [Neilpang/acme.sh#516]
cron job:
`0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null`

results in a renewed certificate but error:

```
/root/.acme.sh/acme.sh: line 3337: systemctl: command not found
[Tue  3 Jan 00:02:31 CET 2017] Reload error for : domain.tld
[Tue  3 Jan 00:02:31 CET 2017] Error renew domain.tld, Go ahead to next one.
```

on Debian Jessie without systemd

**Comment by Neilpang** [comment]
`acme.sh` doesn't use  systemd.  Please check our parameter `--reloadcmd`,   you are using the systemctl to reload nginx/apache maybe.

**Comment by ovizii** [comment]
I'm sorry I didn't realize that. I might have used the wrong settings for that parameter when I initially issues that particular certificate. Where would I find and change that parameter?

As I said, I get that error from the cronjob and that parameter isn't used inside the cronjob.

**Comment by Neilpang** [comment]
```
/root/.acme.sh/domain.tld/domain.tld.conf
```

**Comment by ovizii** [comment]
THX!
