### ISSUE TITLE
Namecheap API implementation

### ISSUE THREAD

**Issue by isometriq** [Neilpang/acme.sh#527]
From what I see, Namecheap API is not in the supported list. That's what I need for my NAS.

Found this, but unsure if related to acme.sh
https://github.com/wdouglascampbell/letsencrypt_namecheap_dns_api_hook

I think it's for another script ..is there anything I can salvage there?
I'd like to implement it correctly then create a pull request.
Thx

**Comment by Neilpang** [comment]
@isometriq 

yes,  namecheap api is not complicated, but it's not available for all their users.  As when I tried to use it,  it has limit of the money spent in my account.

Please feel free to implement and send pr.

**Comment by isometriq** [comment]
oh you mean the API is not free ?

**Comment by Neilpang** [comment]
https://www.namecheap.com/support/api/intro.aspx

https://ap.www.namecheap.com/Profile/Tools/ApiAccess

>> We’re sorry, you have not met the criteria to qualify for API access. To qualify, you must have: Account balance of $50+, 20+ domains in your account, or purchases totaling $50+ within the last 2 years.
