### ISSUE TITLE
fullchain.cer versus chain.cer

### ISSUE THREAD

**Issue by IzzySoft** [Neilpang/acme.sh#531]
The original LetsEncrypt client also created a `chain.cer` in addition to the `fullchain.cer`. Would it make sense to have `acme.sh` do the same?

Background of my question: I still have several machines running Apache2.2, and had them set up using the `SSLCertificateChainFile chain.pem` file – while the `fullchain.pem` is used by postfix. I don't remember why I made this distinction, but am afraid I had a reason (if there should be none, I'd be glad to hear that ;). So I'd prefer keeping it that way for now.

Am I assuming correctly I could simply use the `ca.cer` as `chain.pem`?

**Comment by Neilpang** [comment]
I think `ca.cer` should work for you.
Please try first.

**Comment by IzzySoft** [comment]
Thanks for confirming! Will do so on the weekend (where I have time to react if anything gets weird) and report back. As postfix uses the fullchain, all that can go broke is the webmail on that machine :)

**Comment by Neilpang** [comment]
@IzzySoft 

How is going on ?

**Comment by IzzySoft** [comment]
I was waiting for your reply on the other issue (issue #537 – which popped up when I tried to implement the above), concerning passing parameters to the ReloadCmd. As you don't want us to edit the config manually, I didn't want to get into troubles reconfiguring that afterwards :)

Background: the certs need to be transferred to a different machine, which is not reachable at port 80 from the outside. So I'd need something like `--reloadcmd "sudo myscript.sh $ca $key $cert $fullchain"` to have an external script taking care to copy the certs over and restart the corresponding services once the certs are generated successfully. If there are no "place holders" for the parameters mentioned, I had to pick the certs directly – which again is something you strongly discourage from.

So once that issue is solved, I can see to tackle this one :)

**Comment by Neilpang** [comment]
how is going on?

**Comment by IzzySoft** [comment]
@Neilpang Sorry for the delay. Now finally I updated and played with it – and it works so far!

Hint: If the `--reloadcmd` needs a `sudo`, one should not forget to pass the environment. `--reloadcmd "sudo /path/to/script"` will not pass the variables (`$CERT_PATH` etc). If the reloadCmd must be invoked via `sudo`, it must rather include the `-E` parameter to have the environment passed along: `--reloadcmd "sudo -E /path/to/script"`. Took me a little to figure :)

Now I have to watch out for any side-effects concerning the `ca.cer`. None seen so far, though.

**Comment by Neilpang** [comment]
@IzzySoft 
You should not use `sudo` for the whole script.
Instead,  you should use `sudo` inside your script. Please only use `sudo` for the required command.


```sh
#myscript
...
...

sudo service apache2 restart


```

**Comment by IzzySoft** [comment]
Neil, if I call the entire script via `sudo`, I need exactly one entry in the `/etc/sudoers` for that (remember the script must run without user intervention, so it needs a password-less `sudo` here). If I do as you advice, I'd need a bunch of entries (or at least figure how to work with wildcards in `/etc/sudoers`).

Different people have different approaches. You should not force your own on everyone else ;) This is not Gnome :stuck_out_tongue_winking_eye: And besides, it's not just the Apache restart requiring a `sudo` here – it's copying the cert files, adjusting the ownership and permissions of the cert files, and dealing with other services (postfix, dovecot, …) as well. As I'm already not allowed to use the cert names directly ("you should not"), I hardly can setup a sudoer's rule for that. Makes stuff quite complicated.

So no, I won't add another complication. I'm happy that it works now. And I prefer simple constructs I still do understand in 3 years without guessing at how many places I've tweaked the system for it in a way unnatural to me, and without writing a book for documentation :) Sure, I could run the entire `acme.sh` as root and forget about the rest – but somehow I start wondering what then did you mean in the README by "DOES NOT require `root/sudoer` access"? How does it write the cert files (which are owned by `root:root`) and reload services without `root/sudoer` access?

Don't get me wrong, Neil, I'm not accusing (in fact, I'm very thankful for your script!). It's just that all your "you-should-nots" seem to make it much more complicated than it appeared initially (and I'm no newcomer to Linux, working with it already since the last century). For internals of your programming I must accept that (strange as it feels to me in some cases). But my general scripting I prefer to keep my style :innocent:

**Comment by Neilpang** [comment]
>> Neil, if I call the entire script via sudo, I need exactly one entry in the /etc/sudoers for that (remember the script must run without user intervention, so it needs a password-less sudo here). If I do as you advice, I'd need a bunch of entries (or at least figure how to work with wildcards in /etc/sudoers).

I don't think you need a bunch entries in the `/etc/sudoers`,  you just need set your self as non-password sudoer.

>> Different people have different approaches. You should not force your own on everyone else ;) This is not Gnome 😜 And besides, it's not just the Apache restart requiring a sudo here – it's copying the cert files, adjusting the ownership and permissions of the cert files, and dealing with other services (postfix, dovecot, …) as well. As I'm already not allowed to use the cert names directly ("you should not"), I hardly can setup a sudoer's rule for that. Makes stuff quite complicated.

Sorry, When I say "you should/should not do something",  I mean "I suggest you to do something".  It's just suggestions/recommendations.
What I mean is that:  when you write a script for the `--reloadcmd`,  you don't need to run the whole script as `root/sudoer`.   Usually, only a few operations need  `root` permission,  something like copying files, or restarting services.   So I think using `sudo` inside the script is safer and better.  

It's said that one should use `sudo` as little as possible.

Sorry, if it made you misunderstand me.

**Comment by IzzySoft** [comment]
> I don't think you need a bunch entries in the `/etc/sudoers`, you just need to set yourself as non-password sudoer.

Which IMHO defeats the purpose. In that case, I could simply run the entire process as root. If there's any user who can do everything as root by just prepending each command by "sudo", and never is asked for a password, I'd call that a security hole.

> It's said that one should use `sudo` as little as possible.

Exactly :stuck_out_tongue_winking_eye: Which is why I've split the "system stuff" off and put it in its own script. So even if someone manages to call it, no harm is done – as opposed to a "blank cheque" rewarded without limitations.

> Sorry, When I say "you should/should not do something", I mean "I suggest you to do something". It's just suggestions/recommendations.

Ah – in that case it's on me to apologize! Let's say then I respect your approach, but prefer mine? :flushed:

Again, Neil: thanks for all your help! Very much appreciated! And I prefer `acme.sh` 10 times over the bloated certbot with all its dependencies. I'll watch my two current installations a little more, and then will switch to `acme.sh` on my other installations as well, most likely in spring (when I've seen `acme.sh` having successfully renewed certs on the existing installations).

**Comment by Neilpang** [comment]
>> I'll watch my two current installations a little more, and then will switch to acme.sh on my other installations as well, most likely in spring (when I've seen acme.sh having successfully renewed certs on the existing installations).

Sure.
