### ISSUE TITLE
acme.sh should chmod keys to 400 in its "working" directory and install new keys as 400 too

### ISSUE THREAD

**Issue by blacklion** [Neilpang/acme.sh#532]
It will be better if acme.sh make all keys read-only-only-by-owner. Yes, its working directory is 700, but just in case.

Also, maybe install key for first time (if here is no target key file) with mode 400 and notify user IN BIG LETTERS to check owner, group and access rights

**Comment by bittorf** [comment]
can you please send a pullrequest with you changes?

**Comment by Neilpang** [comment]
It's too much for acme.sh to  deal with the owner, group and access.
