### ISSUE TITLE
config

### ISSUE THREAD

**Issue by IzzySoft** [Neilpang/acme.sh#537]
I've searched Wiki and issues as well, but obviously missed it: are the parameters of the config file documented somewhere? If not, it would be nice to have that in the wiki :)

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki

https://github.com/Neilpang/acme.sh/wiki/Options-and-Params

**Comment by IzzySoft** [comment]
Thanks, Neil (just now noticed the "6 more pages" I missed before). But those are the command line parameters. I was talking about the config file (`domain.com/domain.com.conf`). While some parameters correspond, others don't (or are spelled differently, so they are not easy to make out in the long list).

I've added a section to the wiki page you mentioned, you might wish to cross-check that (and maybe fill the gaps?)

**Comment by Neilpang** [comment]
Where is the page you added ?

Anyway, I want the users use the commandline parameters, instead of editing the config file.

The users should **NOT** know the config file.  The config file is intended for internal private use.

In future, we may have other features, something like saving the config info in to database, instead of config file.

Or, we may change the config file name or location.

So, please do not edit the config file.  just use the commandline parameters.

That was way I never wrote about the config file.

**Comment by IzzySoft** [comment]
I did not add a new page, just a section on the page you referred me to: https://github.com/Neilpang/acme.sh/wiki/Options-and-Params#configuration-file

And I disagree that one should not know about it. The warning is understood, yes. But there are situations where it's helpful and saves a couple of steps simply fixing things there. For example, changing the ReloadCmd or one of the hooks without executing them right away.

**Comment by Neilpang** [comment]
Thanks.

I just removed the changes.  The config file is not a recommended public interface for now.

The user should use command line parameters to change anything.  If you have requirements, I can add parameters for you.

**Comment by IzzySoft** [comment]
Understood. I currently have some issues with this approach ("don't touch the config, don't access the certs directly…). Some specific reasons:

1. I don't want to run the entire thing as root. So I cannot have `acme.sh` "distribute" the certs itself (no write access there, of course), but must handle that via an external script (run via `sudo` and registered with `/etc/sudoers`) – which copies the certs to their corresponding locations and, if successful, reloads the web server. For that, I must touch the certs myself. Sure, I could have `acme.sh` export them to a temporary place and have my script move them from there – but that I'd consider unnecessary overhead. I prefer to stay in control without making things more complicated than needed :)
2. I have to create certs for multiple machines behind the same (external) IP, and then distribute the generated certs to those machines. That's no longer local, so I need to touch the certs myself again to transfer them via SSH. Same way, once the transfer succeeded, I need to reload the remote servers via SSH.

Sure, parts of that could be done by `acme.sh` itself – even with "Mr. root" involved: so the ReloadCmd could be tought to hand the corresponding information as parameters (something like `--reloadcmd "sudo myscript.sh $ca $key $cert $fullchain"` – is that already possible, and I just missed that?). I didn't suggest that yet as things are already complex enough as they are – but if you prefer it that way… We might as well need a command to change/clear parameters of the config file. For example, if one initially had `acme.sh` distribute the keys and now decides doing that via an external script – how to reconfigure it without executing anything? Is there something like `acme.sh --reconfigure …`? I cannot find such a parameter in the wiki.

**Comment by IzzySoft** [comment]
Guess the closure is due to 25555b8 ? If I interprete that correctly, the ReloadCmd can find certificate files in the environment via `$CERT_PATH`, `$CERT_KEY_PATH`, `$CA_CERT_PATH` and `$CERT_FULLCHAIN_PATH` – each of them having the resp. full qualified file name?

**Comment by Neilpang** [comment]
@IzzySoft 
Yes,  it's full path.  you can read for the cert/key content.

**Comment by IzzySoft** [comment]
Thanks a lot! Then I'll see to update and give it a try ASAP.
