### ISSUE TITLE
Why is `root` recommended ?

### ISSUE THREAD

**Issue by davidandreoletti** [Neilpang/acme.sh#538]
This is not a bug report. The documentation states that`You don't have to be root then, although it is recommended.`. 

Why is `root` recommended ?

**Comment by bittorf** [comment]
why is this closed without waiting for an answer (or at least give it yourself/for others)?

**Comment by Neilpang** [comment]
@bittorf  I don't know, it's not closed by me.

**Comment by davidandreoletti** [comment]
It was opened by me, unfortunately Github seems not to allow deleting one's own issue.

I initially raised the question because recommending to use "root" (for most scenario) and using the option to automatically upgrade acme.sh on a regular basis (e.g. via a cron job) is potentially a highly dangerous setup from a security POV (when the server running acme.sh is holding all necessary data to copy, update the certificates proving one's ownership of a resources)

I do believe reasonable effort is taken to prevent malicious code (submitted as malicious pull request for example) from entering the source code, the possibility is still there.

I think recommending to use a non privileged user (e.g.: nobody) would have been more appropriate.

That being said, I supposed the author of the recommendation assumed people using acme.sh know what they doing. Hence the closed issue with any question.
