### ISSUE TITLE
Webroot renew attempts to use standalone mode

### ISSUE THREAD

**Issue by dessant** [Neilpang/acme.sh#544]
Tested with 2.6.4 and master.

```
bash-4.3# /usr/local/bin/acme.sh --home /web/tls/data --webroot /web/tls --force --renewAll --debug
[Tue Jan 17 12:07:46 UTC 2017] Lets find script dir.
[Tue Jan 17 12:07:46 UTC 2017] _SCRIPT_='/usr/local/bin/acme.sh'
[Tue Jan 17 12:07:46 UTC 2017] _script='/usr/local/bin/acme.sh'
[Tue Jan 17 12:07:46 UTC 2017] _script_home='/usr/local/bin'
https://github.com/Neilpang/acme.sh
v2.6.5
[Tue Jan 17 12:07:46 UTC 2017] _stopRenewOnError
[Tue Jan 17 12:07:46 UTC 2017] di='/web/tls/data/example.com/'
[Tue Jan 17 12:07:46 UTC 2017] d='example.com'
[Tue Jan 17 12:07:46 UTC 2017] DOMAIN_PATH='/web/tls/data/example.com'
[Tue Jan 17 12:07:46 UTC 2017] Renew: 'example.com'
[Tue Jan 17 12:07:46 UTC 2017] Using api: https://acme-v01.api.letsencrypt.org
[Tue Jan 17 12:07:46 UTC 2017] Le_NextRenewTime='1483611519'
[Tue Jan 17 12:07:46 UTC 2017] _on_before_issue
[Tue Jan 17 12:07:46 UTC 2017] Le_LocalAddress
[Tue Jan 17 12:07:46 UTC 2017] Check for domain='example.com'
[Tue Jan 17 12:07:46 UTC 2017] _currentRoot='no'
[Tue Jan 17 12:07:46 UTC 2017] Standalone mode.
[Tue Jan 17 12:07:46 UTC 2017] _checkport='80'
[Tue Jan 17 12:07:46 UTC 2017] _checkaddr
[Tue Jan 17 12:07:46 UTC 2017] Using: netstat
[Tue Jan 17 12:07:47 UTC 2017] tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      16/nginx: master pr
tcp        0      0 :::80                   :::*                    LISTEN      16/nginx: master pr
[Tue Jan 17 12:07:47 UTC 2017] tcp port 80 is already used by  master pr
80                   
[Tue Jan 17 12:07:47 UTC 2017] Please stop it first
[Tue Jan 17 12:07:47 UTC 2017] _on_before_issue.
[Tue Jan 17 12:07:47 UTC 2017] Return code: 1
[Tue Jan 17 12:07:47 UTC 2017] Error renew example.com, Go ahead to next one.
```

**Comment by Neilpang** [comment]
Do not use `--webroot /web/tls` option.

When you use `renew` or `renewall`, you don't need to specify anything.  `acme.sh` remembers all the info when you first issue the cert.

```bash
/usr/local/bin/acme.sh --home /web/tls/data  --force   --renewAll

```

**Comment by Neilpang** [comment]
Please check:

```sh
crontab -l
```

**Comment by Neilpang** [comment]
I guess you don't need to specify the `--home` too.

```sh
/usr/local/bin/acme.sh   --force   --renewAll

```

**Comment by dessant** [comment]
Thanks for the pointer, i've been passing --webroot every time on other servers without issues.

Unfortunately skipping --webroot gives the same error, and --home seems to be needed.

```
bash-4.3# crontab -l
# do daily/weekly/monthly maintenance
# min	hour	day	month	weekday	command
*/15	*	*	*	*	run-parts /etc/periodic/15min
0	*	*	*	*	run-parts /etc/periodic/hourly
0	2	*	*	*	run-parts /etc/periodic/daily
0	3	*	*	6	run-parts /etc/periodic/weekly
0	5	1	*	*	run-parts /etc/periodic/monthly

bash-4.3# /usr/local/bin/acme.sh --force --renewAll                     
bash-4.3# /usr/local/bin/acme.sh --renewAll        
bash-4.3# /usr/local/bin/acme.sh --renewAll --debug
[Tue Jan 17 13:16:41 UTC 2017] Lets find script dir.
[Tue Jan 17 13:16:41 UTC 2017] _SCRIPT_='/usr/local/bin/acme.sh'
[Tue Jan 17 13:16:41 UTC 2017] _script='/usr/local/bin/acme.sh'
[Tue Jan 17 13:16:41 UTC 2017] _script_home='/usr/local/bin'
[Tue Jan 17 13:16:41 UTC 2017] Using default home:/root/.acme.sh
https://github.com/Neilpang/acme.sh
v2.6.5
[Tue Jan 17 13:16:41 UTC 2017] _stopRenewOnError
[Tue Jan 17 13:16:41 UTC 2017] di='/root/.acme.sh/*.*/'
[Tue Jan 17 13:16:41 UTC 2017] Not directory, skip: /root/.acme.sh/*.*/
```

**Comment by dessant** [comment]
It's probably ok to pass --webroot too on further commands, because you might want to change the path without discarding the data saved in the home dir. Or you might want to move the home dir to a different location, with the data. Anyway, it does work on other servers, i'm not sure why it started to fail here.

**Comment by Neilpang** [comment]
you can pass `--home` to specify where `acme.sh` is installed to.

But never, never specify  `--webroot` on `renewall` command.

**Comment by dessant** [comment]
@Neilpang, ok. Though I don't see why this must be a rule, does it mean if the webroot path has to be changed for some reason, you'd have to edit the internal config file in the home folder?

Do you have some tips on how to debug why it tries to switch to standalone mode, regardless of --webroot being passed or not?

**Comment by Neilpang** [comment]
You can use `--debug`  or `--debug 2`
And paste the log here

**Comment by dessant** [comment]
Ok, i think I know why it happens, this is in example.com.conf:
```
Le_Webroot='no'
```

So the certs were created in standalone mode for the very first time, because nginx was not running, and renews ignore the new --webroot.

The solution would be to update `Le_Webroot` when `--webroot` is used with later commands.

**Comment by Neilpang** [comment]
cool.

Anytime you want to change the parameter,  please use `--issue` again.  All the parameters will be refreshed.

**Comment by dessant** [comment]
Thanks, but wouldn't that reissue the certificates instead of renewing them? I don't see why this limitation has to be imposed.

**Comment by dessant** [comment]
The same seems to be happening with `Le_ReloadCmd`, and the rest of the variables.

**Comment by dessant** [comment]
Though i see why you would not want to alter the config files on renews, alternatively it could just use the new command line value, when present, for the current command, without overwriting the config option on disk.

**Comment by Neilpang** [comment]
It could be a mess to change the config in renew/renwall.
I'd like to keep it simple.

**Comment by dessant** [comment]
You're right, it makes sense if the change would add too much complexity.
Thanks for this project btw, I've tested many of the most popular alternatives, and I believe this one is the best so far. ❤️
