### ISSUE TITLE
How to remove certificates?

### ISSUE THREAD

**Issue by NielsH** [Neilpang/acme.sh#551]
Hello,

What's the recommended way to remove certificates? I know that I can revoke them, but that does not remove the certs from --list - and I'm not sure if that will still trigger a reload when it was supposed to expire.
Preferably I'd like a clean way to remove a certificate that I no longer need. At the moment, I just remove the directory in the certs/ folder, but if it can be done through acme.sh itself that'd be great.

Thanks!

**Comment by Neilpang** [comment]
Yes,  remove the folder is enough for now.

I will add a new command `--remove` for you soon.

**Comment by Neilpang** [comment]
fixed now https://github.com/Neilpang/acme.sh/commit/78f0201dfafede2ef68a5776ab5f80a6d196d3af

**Comment by NielsH** [comment]
Thank you, @Neilpang !
