### ISSUE TITLE
Support for passing path to key / cert / fullchain / CA to reloadcmd/renew-hook

### ISSUE THREAD

**Issue by lucasRolff** [Neilpang/acme.sh#558]
Hi Neil,

I'm happily using acme.sh on a bunch of servers - but we store the certificates in a central location afterwards (currently encrypted MySQL) - since we deploy it to a list of servers - for this we have to update the entry in the database after a certificate has been issued

Would it be possible to (optionally) pass the path to the private key, certificate, CA, fullchain and csr to reloadcmd or renew-hook? Possibly if the --fullchainpath --certpath --keypath are set, using those instead

It would mean we could execute a script afterwards to do certain actions based on the certificate

For us e.g. we name our certificate based on an identifier we can match in the database - so we could grab the name from the certificate, look it up in the database, and replace based on this.

Or is there any smart way we can get this information (keypath and fullchainpath being most important for us)

**Comment by lucasRolff** [comment]
Ah, I see the renew-hook only works for renewals, and not --issue command it seems 😞 

Do you have any idea, how we can exec something both during a successful issue and renewal, for doing something else?

I could write a wrapper to use --deploy scripts, but that means I would have to rewrite the renewal as well, since I can't see how I would know the domain to run --deploy for, with the current automatic renew command in acme.sh

**Comment by Neilpang** [comment]
I have 2 advices:

1. I just fixed https://github.com/Neilpang/acme.sh/pull/559.
you can get the env variables to know the cert/key file path in your reload script.

2. `--post-hook` will be called for no matter `--issue` or `--renew`.

**Comment by lucasRolff** [comment]
> `--post-hook` will be called for no matter `--issue` or `--renew`.

Indeed - but it will also be called in case of failure - not sure if it would be an idea to have `--error-post-hook` and `--success-post-hook` - it would make it super flexible.

> you can get the env variables to know the cert/key file path in your reload script.

I'll work with `--reloadcmd` for now

I actually realize, since following is executed:

```
cd "$DOMAIN_PATH" && eval "$Le_ReloadCmd"
```

I could even source the `$domain`.conf file - and from there also get the variables such as `$Le_RealFullChainPath` and `$Le_RealKeyPath`

That means I should be able to get the name of the certificate as well to match in my DB

Thanks for the super quick feature Niel!

**Comment by Neilpang** [comment]
@lucasRolff 

Actually, if your `reloadcmd` is a shell script(not a executable),  you can read any `Le_RealFullChainPath` etc direct,  you don't need to source the conf file.

**Comment by lucasRolff** [comment]
Cool, I'll test that out to see if I can get that working

**Comment by lucasRolff** [comment]
So... For --reloadcmd you'd do something like:

```
acme.sh --reloadcmd "echo $Le_RealFullChainPath
// continue some other commands here" -d mydomain.com

Like as a block of code, instead of putting it inside a file?

**Comment by Neilpang** [comment]
If your reloadcmd is just on command, you can write it in the command line,
but if your need multiple commands,  you should write the commands in a script file.

**Comment by lucasRolff** [comment]
Sure, but if I do somehing like --reloadcmd "bash myscript.sh" - since the variables (e.g. `Le_RealFullChainPath`) isn't exported it won't be available in sub-shells which is what will happen if you do a `bash myscript.sh` - then it would have to be exported.

If I just do `bash myscript.sh` - doing `env` won't show the variables, and shouldn't be usable then

**Comment by Neilpang** [comment]
Do not use `--reloadcmd "bash myscript.sh" `.

Use `--reloadcmd "/path/to/myscript.sh" `

**Comment by hatifnatt** [comment]
Hello @Neilpang you suggest to use $Le_* variables in `--reloadcmd` (also I saw example [here](https://github.com/Neilpang/acme.sh/issues/261#issuecomment-239188317)) script but I can't get it working
My script: `/root/.acme.sh/haproxy-reload.sh`
```
echo "Le_Domain $Le_Domain"
echo "$CERT_FULLCHAIN_PATH" "$CERT_KEY_PATH" "/etc/haproxy/certs/${Le_Domain}.pem1"
```
Result:
```
[Ср мар 29 01:30:01 MSK 2017] Run reload cmd: /root/.acme.sh/haproxy-reload.sh
Le_Domain
/root/.acme.sh/sdev.dev.telemetron.ru/fullchain.cer /root/.acme.sh/sdev.dev.telemetron.ru/sdev.dev.telemetron.ru.key /etc/haproxy/certs/
.pem1
```
Looks like exported variables  $CERT_FULLCHAIN_PATH and $CERT_KEY_PATH are fine, but  $Le_Domain isn't available for external script. Am I doing something wrong?

**Comment by Neilpang** [comment]
@hatifnatt 
fixed https://github.com/Neilpang/acme.sh/pull/752
Please try again.  Please let me know if you have another problems.

**Comment by hatifnatt** [comment]
@Neilpang thank you, now it's working. But I'm just curious what about other Le_* variables, have they worked before some code changes?

**Comment by Neilpang** [comment]
@hatifnatt  It was never supported yet.
Sorry,  Please use `_readdomainconf()` function to get all the `Le_*` variables if you want.
```sh
mydomain=$(_readdomainconf Le_domain)
```

I will revert my last fix soon.

**Comment by hatifnatt** [comment]
@Neilpang sorry but I'm confused, how internal function like `_readdomainconf()` will be available in external script which will be launched with `--reloadcmd`? It's clear that `CERT_PATH, CERT_KEY_PATH, CA_CERT_PATH, CERT_FULLCHAIN_PATH` variables are exported and available for any external script. But I also need domain name which currently saved in `Le_Domain` variable in script and in conf file. Sure I can source conf file as **lucasRolff** mentioned above but may be you suggest better solution.
