### ISSUE TITLE
Open/Close firewall port

### ISSUE THREAD

**Issue by guestisp** [Neilpang/acme.sh#561]
Would be nice to add a flag (`--iptables` ?) to automatically open and close firewall port (80 or 443) when signing/renewing certificates.

This allow to use the standalone mode on servers without apache/nginx to serve a webroot, in example, on a mailserver.

acme.sh should open the required port just before the CA verification and then close it immediatly after.

**Comment by Neilpang** [comment]
It's too much overkilled.
You can use `--pre-hook` and `--post-hook` to open firewall port or close firewall port.

```
acme.sh  --issue -d example.com  --standalone  \
--pre-hook "sudo  iptables -I INPUT  -p tcp  --dport 80    -j ACCEPT"
--post-hook "sudo  iptables -D INPUT  -p tcp  --dport 80    -j ACCEPT"
```
