### ISSUE TITLE
renewal question with DNS method

### ISSUE THREAD

**Issue by JimDunphy** [Neilpang/acme.sh#562]
I am having a problem with the dns method.  When it comes time to renew, I am having to go through the validation steps again. Is that normal?

I created it initially with the following:

./acme.sh --issue --dns -d mail.example.com -d mail.example.org -d mail.example.net 

The first time it came up for renewal, I did:

./acme.sh --cron --home /home/XXX/.acme.sh

That resulted in having to go through the challenge again and adding new TXT records

Another 70+ days passed and I tried:

./acme.sh --renew -d mail.example.com -d mail.example.org -d mail.example.net 

And again, I went through the challenge and adding new TXT records.

What is the proper method to renew a CERT that was obtained via the dns method? I was hoping to find an automatic method so I didn't have to add the TXT records.

I was using version 2.6.2 and will try next with 2.6.6.

I guess for my 3rd time, I might try using the original challenge/verification TXT records that are currently commented out but this time specify the --dns with the --renew option such as this:

./acme.sh --dns --renew -d mail.example.com -d mail.example.org -d mail.example.net 

Any advice on how to accomplish an automatic renewal of the CERTS without having to go through the verification/challenge steps.

Thanks for great software!

**Comment by Neilpang** [comment]
Yes,  it's supposed to verify the domain each time you renew the cert.

For the the validation lasts valid for 60 days, the new acme.sh renews the cert every 59 days. Which means  can be renewed without validation again.

But do not rely on this.  Let's encrypt said that they will shorten this time later.

So, you should expect to validate your domain every time you issue/renew the cert.

It's suggest to use webroot mode or   dns api mode.

**Comment by JimDunphy** [comment]
Perfect. Thank you.

**Comment by Neilpang** [comment]
https://community.letsencrypt.org/t/404-expired-authorization/26038
