### ISSUE TITLE
stateless mode, command to output thumbprint

### ISSUE THREAD

**Issue by stephankn** [Neilpang/acme.sh#575]
This is a feature request.

I would like to use a stateless mode as this saves me from configuring a proxy redirect and firewall settings. It also sounds safer to skip opening additional ports if not needed.
Other acme clients support this already (like https://github.com/hlandau/acme)

Nginx would be statically configured to respond to the challenge. The account_thumbprint would need to be exportable by acme.sh

```
http {
  server {
    location ~ "^/\.well-known/acme-challenge/([-_a-zA-Z0-9]+)$" {
      default_type text/plain;
      return 200 "$1.ACCOUNT_THUMBPRINT";
    }
  }
}
```

The calculation of the thumbprint is already there, it would just need to be exported.
https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L2782

Additional implementation of a "stateless" mode also sounds not too difficult. Code should be similar to standalone, just skipping opening the webserver. 

Please consider adding support for it.

**Comment by Neilpang** [comment]
I don't quite understand the use case for this.
Can you please explain more ?

**Comment by stephankn** [comment]
Sure.

When you ask the letsencrypt server for a validation it will call a a specific URL or your server and expects a specific response.

eg it requests `/.well-known/acme-challenge/ABCDEF` and expects a specific return `ABCDEF.thumbprint`. Thumbprint is static for your account.

acme.sh creates this return in the sections pointed to above and serves it by opening a server listening on port 80.

Noticed that my link pointed to master, which make the line numbers to change. Sorry if this caused confusion. 
https://github.com/Neilpang/acme.sh/blob/dba26c3240efaa6cdd9c6f163f8294242c2bdbfd/acme.sh#L2827

The return `keyauthorization="$token.$thumbprint"` consists of a random string chosen by LE and a static thumbprint.

Instead of configuring nginx to forward a port and acme.sh opening a server this task could be done by nginx itself. The snippet above configures a responder to LE requests to answer the challenge with the right combination of token and thumbprint.

Advantage is that it makes opening a server port unneeded thus helping in setups where port 80 is not available and redirects cause extra work with firewall setups.

**Comment by Neilpang** [comment]
The `--stateless` mode is checked in.

I also wrote a doc: 
https://github.com/Neilpang/acme.sh/wiki/Stateless-Mode

Please take a look,  please feel free to comment on the doc.

Thanks.

**Comment by FernandoMiguel** [comment]
interesting technique
as good as DNS01

**Comment by stokito** [comment]
I'm very confused. I thought that the challenge file contains a nonce generated by the acme server and known only to the acme client. Otherwise anyone in the middle can see all tokens over the plain HTTP and issue a cert. So this should be allowed only by HTTPS.
The "stateless" is a security bug: why the challenge tokens are needed then? Just check that the thumbprint is present.

**Comment by stephankn** [comment]
@stokito It is always fine to double check that security functionality is really secure. Maybe you can suggest some additions to the documentation which is then explaining why an account thumbprint is no secret.

When creating a https certificate, it consists of a private key which is stored on your server an kept secret. And a corresponding public key.

Let's Encrypt is not certifying that you are who you claim you are. It only confirm that you have control over the http or dns at the address mentioned in Subject of certificate at the point in time when LE checks this.

If an attacker is able to take over DNS, then they can register their own account at LE and get a certificate. No need to have thumbprint. This is because identity is not verified. Your bank might use a different CA and use CAA records to prevent attackers from getting a false certificate.

If attacker has only thumbprint and no possession of your private key I doubt that anything harmful can be done with it. I am open to hear your specific concerns about a possible attack vector to discuss it.
