### ISSUE TITLE
Add logging to standard system syslog

### ISSUE THREAD

**Issue by dkerr64** [Neilpang/acme.sh#576]
Acme.sh should have the option of logging to syslog instead (or as well as) a stand alone log file.  It should use standard system _logger_ functions for this.  I need this because if an error occurs during certificate renew from cron job then it is very likely to go unnoticed.  If acme.sh logs to syslog then standard monitoring tools could detect it.

I am willing to do a pull request and implement this but want to solicit input on how best to do it.

Option 1...
add a --syslog [level] parameter.
[level] would be one of the standard syslog levels, e.g. debug, info, warning, error. It would default to error.

Option 2...
modify the current --log to special case the string "syslog" as the filename.  Instead of logging to a file it would instead log to system log file.  Modify the --log-level to accept standard syslog levels.

My preference would be option 1.

Thoughts?

David

**Comment by Neilpang** [comment]
yes, I agree with Option 1.
syslog and normal file log should work separately, but they should share the same log level.

so, 
```
--syslog
```
should be ok.

if syslog is enabled, the log message should be sent to syslog, as well as the file log(if enabled).

We should also save :`SYS_LOG=1` to the `account.conf` for future automatic use.

I'm open the change, if you have any more ideas.

Thanks.

**Comment by dkerr64** [comment]
I'll work on it and do a pull request once I have it working.

David

**Comment by dkerr64** [comment]
See my comments in pull request #577 

David

**Comment by Neilpang** [comment]
fixed  at  https://github.com/Neilpang/acme.sh/commit/e2edf2083384f6ceae71d89e569052b1ba3b827d
