### ISSUE TITLE
Unable to parse CSR (OpenSSL 1.1.0)

### ISSUE THREAD

**Issue by drake127** [Neilpang/acme.sh#578]
It seems that OpenSSL 1.1.0 breaks parsing of CSR. Everytime I try to do anything with CSR (e.g. --showcsr), acme.sh fails with error "Can not read subject from csr: request.pem".

I tracked down the issue to the function `_readSubjectFromCSR()` which calls `openssl req -subject`. In OpenSSL 1.0.1 it returns something like `subject=/CN=example.com` but OpenSSL 1.1.0 prints `subject=CN = example.com`. Notice spaces before and after second `=` and missing slash.

Steps to reproduce
------------------
Use e.g. Debian Stretch
`acme.sh --showcsr --csr request.pem`

**Comment by Neilpang** [comment]
Can you please give me an example request.pem ?

**Comment by drake127** [comment]
Quite good steps to reproduce the issue are following commands:
`openssl req -new -newkey rsa:2048 -nodes -sha256 -subj '/CN=example.com' 2>/dev/null`
`openssl req -noout -subject`

Resulting line with CN differs in OpenSSL versions:
1.0.1: `subject=/CN=example.com`
1.1.0: `subject=CN = example.com`

Example request.pem:
`-----BEGIN CERTIFICATE REQUEST-----`
`MIICWzCCAUMCAQAwFjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wggEiMA0GCSqGSIb3`
`DQEBAQUAA4IBDwAwggEKAoIBAQDU1uzfO7IHQgsiq66nPiaeBH8+aoh2CdfBF53p`
`w4fmT6eh+kItdlactGoNcI8PBb+hOZ/kH4QTZIK1tW4iyBP9LbEe1lVqp0ktxvZm`
`wjbT/O17163kxeGVaHwjPGbTTXKcP4XXnmnxuFynckECs80/Rf4bFgbo39DExpvN`
`aB3HibLq1qfpFg74E4UevP6lVpZLcS8l1MzG4mUIYQDmhSdxpXZbzec8pSgsGF2T`
`K2LyT5ke6D6Qy8D1DgBrIVEuobIKwBbfc4OrEeX6hN7jzXsJB70OrzZBJadZpTse`
`e/nguR5HXsru9EQ8OV0pONibT2Rl6oPKNn5RsXnapsU8VjTNAgMBAAGgADANBgkq`
`hkiG9w0BAQsFAAOCAQEAlh+b74xUu3ZYPEFfwTJM8wvwdQLaqIDN0qbSf7J+kqow`
`7vA66PPktEfFXRB1uZ2VbA+6C7VVRtysSlTKv0vBNtuDL84nPd3WGYospc3pMDJd`
`MjVyrfR2Yy61WMOQie9yvFDb2LCzvcmf8zrXFutUP3wd6DYX4o6yYFRKOXkY36k6`
`5OIcX9vwwet74Y6z1MdY9a694YYL7G6usgM2oNJRbwlEz/ztZ184Jhra+9G8n/Wj`
`GKdadIbQ9CiKd+7FbxaUnxw4f6qyId7SfICuQbrD0NgF4I8Bc8vbR8EuW5u4AAC9`
`o/y9brOHVDUJQEqrUSdpi+BtnwIB3xED+M5ZLTlzQA==`
`-----END CERTIFICATE REQUEST-----`
