### ISSUE TITLE
请问：路由器ac68u上安装阿里云+Let's Encrpt，该如何完成？

### ISSUE THREAD

**Issue by i-fengma** [Neilpang/acme.sh#579]
你好！首先，请原谅我的小白，有很多东西都不懂……请见谅！

我的问题是：在路由器ac68u上安装阿里云+Let's Encrpt。
我是从这篇文章：http://koolshare.cn/thread-79146-1-1.html （你可以看看这里，或者查看我的引用部分：我修改为阿里云+Let's Encrpt），到最后找到你。因为这篇文章有一些问题（它是DNSPod+Let's Encrpt），通过几天的尝试，始终不能运行成功。

> 1、因为Merlin只有sh，没有python、bash。所以必须基于sh完成。
wget https://github.com/Neilpang/acme.sh/archive/master.zip
unzip master.zip  
cd acme.sh-master
chmod a+x acme.sh
./acme.sh --install --home "/jffs/acme.sh"
cd /jffs/acme.sh/

>运行测试看看是否正常，如果没有错误表示ok了。
/jffs/acme.sh/acme.sh --home "/jffs/acme.sh"

>2、确定要是用DDNS类型，这里以阿里云为例
echo "Ali_Key='xxxx'" >>/jffs/acme.sh/account.conf
echo "Ali_Secret='xxxxx'" >>/jffs/acme.sh/account.conf

>3、开始申请证书
./acme.sh --home "/jffs/acme.sh" --issue --dns dns_ali -d example.com -d www.example.com -d asus.example.com
example.com 为自己的域名；asus.example.com，为准备访问后台的域名
如果配置没有错误，会生成/jffs/acme.sh/example.com 目录，而且该目录下会生成各种证书。

>4、配置ac68u
首先在界面开始SSL访问，并设置好端口，也可以使用nvram设置，不赘述这个过程
nvram set https_crt_save=1
nvram unset https_crt_file
./acme.sh --home "/jffs/acme.sh" --installcert -d example.com --keypath /etc/key.pem --fullchainpath /etc/cert.pem --reloadcmd "service restart_httpd"
这个命令务必执行，完成证书安装，并且保证证书被更新的时候会自动复制证书

>5、使用https访问吧。
https://asus.example.com:xxxx/

>6、设置crontab自动更新
Let's Encrpt证书3个月有效，使用crontab自动更新

>7、添加重启后crontab自动更新脚本（2.4更新）
echo -e "#!/bin/sh\n/usr/sbin/cru a 'LetsEncrpt' '0 0 * * * /jffs/acme.sh/acme.sh --cron --home /jffs/acme.sh > /dev/null '" >> /jffs/scripts/services-start
chmod 755 /jffs/scripts/services-start
这里放入init-start 也可以
注意：如果原先已经有services-start，请手工调整一下/jffs/scripts/services-start文件

>要点：使用--home指定脚本所在位置、acme.sh默认会安装到/home目录，重启消失。

所以，我想请问，该怎么运行呢（因为ac68u只有sh，没有python、bash。所以必须基于sh完成）？

**Comment by Neilpang** [comment]
这篇文章我之前看过, 没有问题.
我自己也用的 koolshare 的固件.

不用太客气, 直接说问题.
从你的帖子中, 我只能得到一个信息就是: 你遇到问题了.

但是,  遇到什么问题, 你在做什么, 做到哪一步, 有没有出错, 出错信息是什么 等等这些重要的信息只字未提.

我想帮也是无从下手啊.

能不能详细描述, 能不能给一个 debug 日志?


这是沟通技巧, 举个不恰当的例子,  你请别人来修车, 是不是要先告诉车辆的具体信息, 故障表现, 然后把引擎盖掀开, 等修车师傅来了, 直接就能在最短的时间内直达病患.  节约大家的时间, 提高沟通效率.

**Comment by i-fengma** [comment]
> 举个不恰当的例子, 你请别人来修车, 是不是要先告诉车辆的具体信息, 故障表现, 然后把引擎盖掀开, 等修车师傅来了, 直接就能在最短的时间内直达病患. 节约大家的时间, 提高沟通效率.

你举的例子很好。但是，用你的例子来回答，我不知道故障在哪儿，所以棘手、难办。

我再运行一次，努力找故障。

**Comment by i-fengma** [comment]
> 3、开始申请证书
./acme.sh --home "/jffs/acme.sh" --issue --dns dns_ali -d example.com -d www.example.com -d asus.example.com
example.com 为自己的域名；asus.example.com，为准备访问后台的域名
如果配置没有错误，会生成/jffs/acme.sh/example.com 目录，而且该目录下会生成各种证书。

运行到这里：
> admin@NETGEAR-8402:/jffs/acme.sh# ./acme.sh --home "/jffs/acme.sh" --issue --dns
 dns_ali -d xxxxx.win -d www.xxxxx.win
[Sun Feb  5 12:39:41 GMT 2017] Multi domain='DNS:www.xxxxx.win'
[Sun Feb  5 12:39:41 GMT 2017] Getting domain auth token for each domain
[Sun Feb  5 12:39:41 GMT 2017] Getting webroot for domain='xxxxx.win'
[Sun Feb  5 12:39:42 GMT 2017] _w='dns_ali'
[Sun Feb  5 12:39:42 GMT 2017] Getting new-authz for domain='ifilu.win'
[Sun Feb  5 12:39:55 GMT 2017] The new-authz request is ok.
[Sun Feb  5 12:39:56 GMT 2017] Getting webroot for domain='www.xxxxx.win'
[Sun Feb  5 12:39:56 GMT 2017] _w='dns_ali'
[Sun Feb  5 12:39:56 GMT 2017] Getting new-authz for domain='www.xxxxx.win'
[Sun Feb  5 12:39:58 GMT 2017] The new-authz request is ok.
[Sun Feb  5 12:39:59 GMT 2017] Found domain api file: /jffs/acme.sh/dnsapi/dns_a  li.sh
./acme.sh: line 1: od: not found
Usage: _hmac hashalg secret [outputhex]
./acme.sh: line 1: od: not found
Usage: _hmac hashalg secret [outputhex]
[Sun Feb  5 12:40:12 GMT 2017] Error add txt for domain:_acme-challenge.ifilu.wi  n
[Sun Feb  5 12:40:12 GMT 2017] Please add '--debug' or '--log' to check more det  ails.
[Sun Feb  5 12:40:12 GMT 2017] See: https://github.com/Neilpang/acme.sh/wiki/How  -to-debug-acme.sh

我是哪里有错呢？

**Comment by Neilpang** [comment]
这是最近引入的 一个 bug :
```
./acme.sh: line 1: od: not found
```

你的 固件 中 缺少 `od` 命令.

之前不依赖 `od` 但有别的问题,  后来用了 `od`.  你这又没有od.

如果可以,  建议你想办法安装od,  或者在koolshare 那边留言 要求增加 `od`.  这是最好的解决办法.

我这正在写一个兼容方案,  稍等.

**Comment by i-fengma** [comment]
1、如何安装 od 呢？

2、koolshare的反应实在太慢太慢，更新一个插件都要等很久（因为它的编写人员很多），所以……不能依靠它。

3、期待兼容方案！

**Comment by Neilpang** [comment]
1.  我也不知道

2. `od` 是 unix 上非常基础的 一个命令.  我测试的所有平台都有这个命令.  不知道为什么他们没有.

3. 已经修了,请得最新的code  再试.
https://github.com/Neilpang/acme.sh/pull/580/commits/9bdb799b412bf86cddbe62d630e94a023fcc532d

**Comment by i-fengma** [comment]
好，非常感谢！

**Comment by Neilpang** [comment]
建议你去那边报一个 issue,  希望他们能加入 od

**Comment by i-fengma** [comment]
哪里边报？
