### ISSUE TITLE
在群晖DS216j上尝试安装Let's Encrypt

### ISSUE THREAD

**Issue by i-fengma** [Neilpang/acme.sh#581]
路由不能用。于是在群晖DS216J上进行尝试。
(地址：https://forum.synology.com/enu/viewtopic.php?t=123003)：

> so we have to do it manually
$ wget https://github.com/Neilpang/acme.sh/arc ... ter.tar.gz
$ tar xvf master.tar.gz
$ cd acme.sh-master/
$ ./acme.sh --install --nocron --home /volume1/@appstore/acme.sh
log out and login to ssh again

> so install is done :)

> next,config
$ cd /volume1/@appstore/acme.sh
get your email, cloudflare account and API (https://www.cloudflare.com/a/account/my-account)
type this to the shell, replace with the values above
export Ali_Key="sdfsdfsdfljlbjkljlkjsdfoiwje"
export Ali_Secret="xxxx@sss.com"

> now to create your cert
$ ./acme.sh --issue --post-hook "/usr/syno/sbin/synoservicecfg --restart httpd-sys" --dns dns_ali --certpath /usr/syno/etc/ssl/ssl.crt/server.crt --keypath /usr/syno/etc/ssl/ssl.key/server.key --fullchainpath /usr/syno/etc/ssl/ssl.intercrt/server-ca.crt --config-home /volume1/@appstore/acme.sh/ --dnssleep 15 -d xxxxx.win 

> simple right?

> since there is no crontab, we need to manually add it to cron.
$ vi /etc/crontab 
and add something like
3 2 * * 2 root /root/.acme.sh/acme.sh --cron
:wq

> HTH
Last edited by BUGabundo on Thu Feb 02, 2017 1:49 pm, edited 3 times in total.

仔细检查了几次，为什么依然不行呢？没有报错阿……

**Comment by Neilpang** [comment]
不要把网页上的内容大段复制, 我看不明白.

为什么不把你自己的输出 复制过来呢?

**Comment by Neilpang** [comment]
请更新最新的code 再试试.
