### ISSUE TITLE
429 error as user but not as root

### ISSUE THREAD

**Issue by ConanMalone** [Neilpang/acme.sh#588]
Using the latest version of acme.sh, we are trying to renew a SAN certificate by running a script with

```
/home/user/.acme.sh/acme.sh --renew --standalone --httpport 8080 -k 4096 --force --debug 2 \
-d example1.ourdomain.uk                 \
-d example2.ourdomain.uk                 \
-d example3.ourdomain.uk                
```

when this script is run as root it works and a certificate is stored in /root/.acme.sh/ but when the same script is run as our acme user, it uses the home directory as /home/user/.acme.sh/ and it produces a 429 error

```
_CURL='curl -L --silent --dump-header /home/acme/.acme.sh/http.header  --trace-ascii /tmp/tmp.xidHrer8j '
[Mon  6 Feb 11:03:47 GMT 2017] _ret='0'
[Mon  6 Feb 11:03:47 GMT 2017] original='{
  "type": "urn:acme:error:rateLimited",
  "detail": "Error creating new authz :: Too many currently pending authorizations.",
  "status": 429
}'
[Mon  6 Feb 11:03:47 GMT 2017] responseHeaders='HTTP/1.1 100 Continue
Expires: Mon, 06 Feb 2017 11:03:46 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 429 Unknown
Server: nginx
Content-Type: application/problem+json
Content-Length: 145
Boulder-Request-Id: D7lOECdCoM15drqvSqL85eOGyDtkq5jzWttZW18B7tA
Boulder-Requester: 408761
Replay-Nonce: dscKjyA8nnYE7_4ZNOQ03k2SnxqJ0LWPOzKEHO-qbfE
Expires: Mon, 06 Feb 2017 11:03:47 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 06 Feb 2017 11:03:47 GMT
Connection: close
'
[Mon  6 Feb 11:03:47 GMT 2017] response='{"type":"urn:acme:error:rateLimited","detail":"Error creating new authz :: Too many currently pending authorizations.","status": 429}'
[Mon  6 Feb 11:03:47 GMT 2017] code='429'
[Mon  6 Feb 11:03:47 GMT 2017] The new-authz request is ok.
[Mon  6 Feb 11:03:47 GMT 2017] new-authz error: {"type":"urn:acme:error:rateLimited","detail":"Error creating new authz :: Too many currently pending authorizations.","status": 429}
[Mon  6 Feb 11:03:47 GMT 2017] pid
[Mon  6 Feb 11:03:47 GMT 2017] _clearupdns
[Mon  6 Feb 11:03:47 GMT 2017] Dns not added, skip.
[Mon  6 Feb 11:03:47 GMT 2017] _on_issue_err
```
Not sure if this is an issue with the acme script or if it is something on my end? If we have ran the script too many times and need to wait to renew our cert why would this not produce the same result for root?

**Comment by Neilpang** [comment]
1.  when you renew a cert,  you can just specify the cert name(the first domain name),  you don't need to specify any other parameters.
```
acme.sh --renew  -d example1.ourdomain.uk   --force
```

2. when you run as root,  it will use the account key in root user home: `/root/.acme.sh/*`,  when you run as normal user("userA" as an example.),  it uses the account key in the normal user: `/home/userA/.acme.sh/*`.   So they are two different accounts.   From the error message,  your normal user has exceed the limit.

**Comment by ConanMalone** [comment]
Should the script still continue to show the error:
```
Too many currently pending authorizations
```
when the ```--test``` option is applied?

**Comment by FernandoMiguel** [comment]
Test and production have different rate limits

**Comment by Neilpang** [comment]
The error message was not issued by acme.sh,  it was from the letsencrypt ca.

**Comment by ConanMalone** [comment]
Okay thanks will wait a week and renew certs.
