### ISSUE TITLE
AWS / Route53 DNS API Broken: hostedzone not set correctly

### ISSUE THREAD

**Issue by AllenJB** [Neilpang/acme.sh#593]
The AWS API appears to be broken on CentOS 7.3 by the "fix for Solaris" changes made on 2017-01-31 in commit https://github.com/Neilpang/acme.sh/commit/bb6326f4d423b9fe6b6677ffb058711724376fcb . The AWS API responds with a HTTP 505 "HTTP Version not supported" error. If I revert these changes it works as expected.

**Comment by Neilpang** [comment]
Please give me a `--debug 2` log.

**Comment by AllenJB** [comment]
Full debug log (redacted domain names and AWS keys): https://gist.github.com/AllenJB/25ecff21a411caea87d3fd133b9f44af

I compared the logs from a working version (the specified revision reverted) to a non-working version, and can see the hostedzone should contain one \<HostedZone> entry when working:

    hostedzone='<HostedZone><Id>/hostedzone/Z3EZDEH0OARE58</Id><Name>example.co.uk.</Name><CallerReference>A77EA3DA-563B-19F6-94B4-CF4D7781B093</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>232</ResourceRecordSetCount></HostedZone>'

But in the non-working version it contains many:

    hostedzone='<HostedZone><Id>/hostedzone/Z3EZDEH0OARE58</Id><Name>example.co.uk.</Name><CallerReference>A77EA3DA-563B-19F6-94B4-CF4D7781B093</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>232</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1Y3Z8B9GEHHIZ</Id><Name>example37.com.</Name><CallerReference>GTA-API-example37.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>14</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZFV8DGBX1QWKG</Id><Name>example38.com.</Name><CallerReference>52231C83-7BE8-C1C5-AA12-7BDE1EA3F6BB</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>6</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z22EKN4K1X1LVC</Id><Name>999.999.5.in-addr.arpa.</Name><CallerReference>EB25B0A0-A232-7874-9954-4468DDA0B531</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>2</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1MZMRIIJF6VE8</Id><Name>999.999.15.in-addr.arpa.</Name><CallerReference>CD058FB2-4505-1F16-BBE7-75C91FFC4BFC</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>9</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1OFM0HNEG0YNH</Id><Name>mi.example38.com.</Name><CallerReference>GTA-API-mi.example38.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>51</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z31C7IOPML703G</Id><Name>as.example38.com.</Name><CallerReference>GTA-API-as.example38.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>62</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1R735RC0JODQQ</Id><Name>ni.example38.com.</Name><CallerReference>GTA-API-ni.example38.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>56</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z23MHFHPNEXD62</Id><Name>mu.example38.com.</Name><CallerReference>GTA-API-mu.example38.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>63</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZOSWU6M9ALZ3J</Id><Name>example39.com.</Name><CallerReference>59F492A3-C439-A677-B0BC-0F2B97A29627</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>3</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZMOBNXCW4I6AH</Id><Name>999.999.16.in-addr.arpa.</Name><CallerReference>5EFFA406-FA1E-0328-80BB-9AA1F27DF438</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>5</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z27H6Y3TQCG5VN</Id><Name>999.999.17.in-addr.arpa.</Name><CallerReference>EF7BE3EF-F02A-9838-A8AF-D61EEF309526</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>5</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1FF7CLO9ZS9HH</Id><Name>m1.example32.com.</Name><CallerReference>GTA-API-m1.example32.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>13</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1RD72Z4RN91V8</Id><Name>nl1.example32.com.</Name><CallerReference>GTA-API-nl1.example32.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>13</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZV8ST6WQO2MQW</Id><Name>nl3.example32.com.</Name><CallerReference>GTA-API-nl3.example32.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>12</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1EMYBZTCNWP2D</Id><Name>nl2.example32.com.</Name><CallerReference>GTA-API-nl2.example32.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>14</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z2RWLA87UWHWBU</Id><Name>m3.example32.com.</Name><CallerReference>GTA-API-m3.example32.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>12</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1ZTZ6XVWGR6RK</Id><Name>m2.example32.com.</Name><CallerReference>GTA-API-m2.example32.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>14</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z2NH1G30AVRJSX</Id><Name>example40.com.</Name><CallerReference>9B771442-1D0C-49C1-8C99-B377CA6017A4</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>10</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1GL0N7W4BWO26</Id><Name>news.example22.com.</Name><CallerReference>GTA-API-news.example22.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>14</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z34R52FC8HM4FP</Id><Name>example41.co.uk.</Name><CallerReference>BB73BF9A-D4DA-5C75-AB74-02B5684F21D9</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>131</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z2LOKJJMZ3EIU7</Id><Name>example42.com.</Name><CallerReference>CD0FF7E3-3DC9-7A6F-9FEC-2089A238844B</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>7</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z3VMY1L7VIZ8KL</Id><Name>example43.com.</Name><CallerReference>E6418E39-737A-3FCF-84FA-5F2DE788E434</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>7</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z2ZDBOEF0FLZDA</Id><Name>example44.org.uk.</Name><CallerReference>B8A7FBD4-AFE5-5A93-9B75-0E4B8133C180</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>8</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z24BJM309W6YKL</Id><Name>example45.com.</Name><CallerReference>CC886C1D-AE91-7F7F-A839-4B7CAD8A3C7C</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>4</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z3O23OUM0F9K77</Id><Name>example46.co.uk.</Name><CallerReference>10FD5C37-D15B-E08B-9025-700F20B67F5D</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>6</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZZ9CLNT8FKRS4</Id><Name>example47.com.</Name><CallerReference>2D6971E2-884C-4945-8EB6-E41D04E09BCC</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>6</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z23Y6T6X7AOPBQ</Id><Name>comms.example32.com.</Name><CallerReference>GTA-API-comms.example32.com</CallerReference><Config><Comment>Created by example22</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>12</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZY3O4NAQX329B</Id><Name>example48.co.uk.</Name><CallerReference>37AD64A9-CFB7-9973-B9AF-1920C16A8F13</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>6</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z3DLAK2ARXGLCC</Id><Name>example47.co.uk.</Name><CallerReference>5751DC49-8BE3-CACF-9BC7-2727C394F79B</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>6</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z2AKZBB69598AI</Id><Name>example5offers.co.uk.</Name><CallerReference>91088D8F-82DB-DD43-96E3-79FE54B111DF</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>4</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1H0K7GJ2L34Y0</Id><Name>example49.co.uk.</Name><CallerReference>540CB864-842C-C339-B309-D764383BC3C3</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>17</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z3BPEMB94G7F0L</Id><Name>example50.com.</Name><CallerReference>E2B05976-41CA-517A-950B-A3F80F56D79A</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>6</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z23D2BT7F24A3W</Id><Name>example51.com.</Name><CallerReference>A8510391-3BB4-BA5C-8CE5-809594919FDF</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>14</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZOLBFJ3W5VHST</Id><Name>example52.uk.com.</Name><CallerReference>F0F66E27-64E5-82EF-A325-0909E9E91E77</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>63</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z30STYHGVBJ1RL</Id><Name>example53.co.uk.</Name><CallerReference>16A904A9-C482-0FF5-A330-8F8D2888C50E</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>25</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZSQK7PYB5WBPT</Id><Name>example54.co.uk.</Name><CallerReference>420ABD9D-018D-22EF-A3F9-F136D3CA9DF2</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>23</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZQV90FEAV3ZZR</Id><Name>iphone.example53.co.uk.</Name><CallerReference>F9227C9E-2FB7-7526-BFDD-C05BF508DC61</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>23</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1FZLAZ6M177MZ</Id><Name>example55.co.uk.</Name><CallerReference>2C47AFA9-DDB1-C266-BC5E-93C0C2B94735</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>19</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z2OSFGU9M2N0LS</Id><Name>example56.co.uk.</Name><CallerReference>02A4D0C4-CC96-F8D1-A8C8-CE7F8ACE1D14</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>24</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z3ZRGFOV3PKO8</Id><Name>example57.co.uk.</Name><CallerReference>CC542B94-18A1-B388-9456-167008FDBA30</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>19</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z9SI91ISJN9ZN</Id><Name>example58.co.uk.</Name><CallerReference>51AE7338-D212-5A70-B739-E66A52C1C6DD</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>10</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z3TLI9WNJFH3KV</Id><Name>example59.co.uk.</Name><CallerReference>7AE23800-EA2A-AAFE-B864-53609472D989</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>9</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z4PP79MURHYTZ</Id><Name>example60.com.</Name><CallerReference>FC5E5098-2448-64D3-AAA0-082C9076F343</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>10</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z3TN8MCZ1ORH9J</Id><Name>example61.co.uk.</Name><CallerReference>3C66B8F6-423C-C552-B5DA-880699BDD299</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>9</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z1WT6B4MJCAIG1</Id><Name>example62.co.uk.</Name><CallerReference>10DE5367-A870-2014-873C-A5F215FF7D32</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>9</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/ZENOYIJAJ1FC6</Id><Name>example63.com.</Name><CallerReference>90B05DA1-FA9A-6FA1-823E-67A667C13E44</CallerReference><Config><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>9</ResourceRecordSetCount></HostedZone>'

It looks like the non-working version is matching the last \</HostedZone> on the line instead of the next instance after the desired domain entry.

It looks to me like the AWS API will work if the specified domain happens to be the last (or only) entry in the list returned, but if there are any after it, this bug will be triggered.

**Comment by Neilpang** [comment]
@AllenJB 
Yes, it seems that the bug will happen if you have multiple domains in your account.

In my testing account, I have only one domain, that's why I passed my overall tests.

I will fix it soon.

Thanks.
