### ISSUE TITLE
od: not found (Busybox 1.16.1 on Synology NAS with PPC E500v2)

### ISSUE THREAD

**Issue by nilsbyte** [Neilpang/acme.sh#595]
I successfully installed acme.sh on my Synology DS210+ with Busybox 1.16.1. It seems that od binary is missing here. I am using `dns_freedns` and I have exported username and password (contains numbers, characters and symbols) before executing this command:

`
./acme.sh --issue --post-hook "kill -USR1 'cat /run/httpd/httpd-sys.pid'" -d sub.mydomain.com --dns dns_freedns --certpath /usr/syno/etc/ssl/ssl.crt/server.crt --keypath /usr/syno/etc/ssl/ssl.key/server.key --fullchainpath /usr/syno/etc/ssl/ssl.inter
`

I always get the error that od is missing and after that there is an error message stating that i could not be logged in at FreeDNS. Subsequently the TXT record creation fails.

What can I do? I saw that there is a workaround for environments without od, but it looks like it does not work.

**Comment by Neilpang** [comment]
Can you give me a full `--debug 2` log ?

https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

**Comment by nilsbyte** [comment]
I did a normal debug at level 1 and it showed nothing suspicious except the mentioned stuff. I will do a debug 2 log tomorrow. stay tuned.

**Comment by Neilpang** [comment]
I know the reason now.  fixing it.

**Comment by Neilpang** [comment]
fixed,  please try again.

**Comment by nilsbyte** [comment]
Yes! It works now!

However. The problem with my command above (`--fullchainpath /usr/syno/etc/ssl/ssl.intercrt/server-ca.crt`) is, that it uses the cert from fullchainpath (`/root/.acme.sh/sub.mydomain.com/fullchain.cer`) and puts it where the intermediate cert has to be on my NAS. How can I tell `acme.sh` to copy the intermediate cert instead of the fullcert?

**Comment by Neilpang** [comment]
@nilsbyte 

```sh
--capath 
```

**Comment by nilsbyte** [comment]
Ok, problem. My testing around resulted in this.

(domain anonymized) 

```
Sign failed: "detail":"Error creating new cert :: Too many certificates already issued for exact set of domains: anonymous.domain.com"
```

What can I do in such a case? Sorry for asking these questions, I am new to this.

**Comment by Neilpang** [comment]
>> We also have a Duplicate Certificate limit of 5 certificates per week. A certificate is considered a duplicate of an earlier certificate if they contain the exact same set of hostnames, ignoring capitalization and ordering of hostnames. 

https://letsencrypt.org/docs/rate-limits/

**Comment by Neilpang** [comment]
You don't need to call `--issue` command every time you change the path.

Just use : `--install-cert` command:

https://github.com/Neilpang/acme.sh#3-install-the-issued-cert-to-apachenginx-etc

**Comment by nilsbyte** [comment]
Ah, I see. Thank you very much!
