### ISSUE TITLE
Error "Subject does not start with '/'" when used acme.sh via git-bash.exe

### ISSUE THREAD

**Issue by nolimitdev** [Neilpang/acme.sh#597]
I know acme.sh should be working via cygwin but git-bash.exe is very popular now. It is much simplier to use unix tools via portable git-bash then install huge cygwin.

Steps to reproduce:
1.) open git-bash.exe and install acme using commands
`git clone https://github.com/Neilpang/acme.sh.git c:/acme-sh`
`cd c:/acme-sh`
`./acme.sh --install --force`
Good, bash is found, so change the shebang to use bash as preferred.
OK

2.) reopen git-bash.exe to take effect of acme.sh alias in .bash_profile and try to issue cert using command:
`acme.sh --issue -d example.com`
Subject does not start with '/'.
problems making Certificate Request
Create CSR error.

More info about this error: http://stackoverflow.com/questions/31506158/running-openssl-from-a-bash-script-on-windows-subject-does-not-start-with

It can be fixed by changing `-subj "/CN=$_csr_cn"` to `-subj "//CN=$_csr_cn"` (double slash) and it will be working now on git-bash.exe. But it breaks on unix - this error appears: "Subject Attribute /CN has no known NID, skipped". Is it possible to support git-bash.exe without breaking other environments? Then you could add to tested OS "Windows (git-bash.exe with curl, openssl and crontab included)".

**Comment by Neilpang** [comment]
fixed,  please check.

**Comment by nolimitdev** [comment]
Yes, it works like a charm now :) Thank you!
