### ISSUE TITLE
Support Godaddy domain api

### ISSUE THREAD

**Issue by Neilpang** [Neilpang/acme.sh#60]
Can anyone do me a favor to lend me a domain at godaddy ?

I don't have a domain there for testing.

**Comment by vmmello** [comment]
@Neilpang, first thanks for developing acme.sh! It's much easier to get started with it than with the official LE client.

Do you still want to "borrow" a domain at GoDaddy? What exactly will you run with it?

A company that I partner with has tens of unused domains at GoDaddy, eventually I can lend one to you, though I need more details of what actions you need done on that domain.

**Comment by Neilpang** [comment]
Hi @vmmello 
Thanks in advance.
I need a domain in godaddy to test their domain api.

Maybe, you will need to push the domain to my godady account,  that means the ownership of the domain is changed.   I don't know if there is an option in godaddy to add an adminstrator to your domain without changing the ownership.  Please take care.


And, I may need to test this domain for a few weeks, since I may not have enough time.

I will not resolve the domain,  just test domain api, and add txt record to issue let's encrypt certs.

I think that's all I need now.  

I know this may be hard to accept. Please think about it.

Thanks.

**Comment by vmmello** [comment]
@Neilpang,

We'll be able to temporarily transfer a domain to your GoDaddy account for you to test for some weeks.

What's your username and e-mail at GoDaddy? GoDaddy requires both. If you prefer, you can just tell me your e-mail at acme.sh and I send you the details.

**Comment by Neilpang** [comment]
@vmmello  Let's talk on email:    info(A-T)acme.sh

**Comment by Neilpang** [comment]
Thanks to @vmmello ,  the godaddy api is supported now.

30de13b4df55837231253ba55120e80af8a3f87f


Thanks.

**Comment by vmmello** [comment]
That was fast! Thanks @Neilpang !
