### ISSUE TITLE
handling multiple vhosts and certs

### ISSUE THREAD

**Issue by tbrowder** [Neilpang/acme.sh#609]
I have about 17 domains on vhosts, on one server, for which I want to maintain individual certs.  I have already successfully created two certonly while testing: one using the standalone and one using apache.

Some questions, please:

1. What, if any, is the difference between the two methods? I use my own, source-built apache and openssl on Debian 8, 64-bit.

2. What is the best way to maintain the multiple certs? I understand I will need to make separate creation runs for each domain, but the docs say only one renew run is needed.  However, I will need a separate run to copy each cert's products into place, then restart apache.  My first thought is this:

+ create a single wrapper script to create all certs at once using standalone or apache
+ create a single wrapper script to copy the products into place
+ create a single wrapper script for the cron job which will:
    - run one instance of acme.sh for renewing (using webroot for validation)
    - for each cert, if it has been updated, copy it into place
    - if one or more certs have been updated, restart apache

(Note I will probably use Perl 6 for some of the scripting.)

In general, does that sound proper and reasonable?

**Comment by Neilpang** [comment]
>> What, if any, is the difference between the two methods? I use my own, source-built apache and openssl on Debian 8, 64-bit.

I think you are using  webroot mode and apache mode.
In webroot mode, acme.sh writes the challenge file to the webroot folder, and delete the challenge file after validation.

In apache mode, acme.sh configure a dynamic alias in apache to do validation,  it doesn't write files to the webroot folder.

if you host multiple website in one server, I would suggest you use webroot mode,  it has a better performance than apache mode.


>> What is the best way to maintain the multiple certs? 
You don't need to maintain the certs,  acme.sh does.

For each website,  just use `--issue` and `--install-cert` command:

```sh
acme.sh --issue -d example.com ........

acme.sh --install-cert  \
        -d example.com \
        --keypath /path/to/apache/ssl/key.pem
        --fullchainpath  /path/to/apache/ssl/cert.pem \
        --reload-cmd "service apache2 force-reload"
```

The cert will be renewed every 59 days automatically,  and then acme.sh will copy/install the cert/key to the target position automatically.

https://github.com/Neilpang/acme.sh#3-install-the-issued-cert-to-apachenginx-etc

**Comment by tbrowder** [comment]
But how does acme.sh know when to check for renewal. Doesn't that require a cron job?  It hasn't created one yet.

Anothe question: what all can be put in the account conf file?

**Comment by Neilpang** [comment]
check your cronjob list:
```sh
crontab -l
```

There should be an cronjob entry for acme.sh.  When you install acme.sh, it installs the cronjob automatically.


>> Another question: what all can be put in the account conf file?
Never edit the account conf file by your hand, unless you are an expert.  it's for internally use only.  
But you can open it and read what is there.

**Comment by tbrowder** [comment]
Ah, the cron job IS there--I haven't used crontab user for many years (not since I discovered how easy the system crontab file is to use.

One more comment: I did use both the standalone and apache methods for my initial testing because I needed to create a cert for a non-existent server.  I use strict https for all but one of my sites and I didn't think I could use any other hands-off method for a new cert with no server.

**Comment by Neilpang** [comment]
you can not use standalone mode and apache mode on the same server,  because they both need to listen tcp 80 port.

if you have 2 servers,  one for standalone,  one for apache, that's ok.

**Comment by tbrowder** [comment]
Sorry, I confused the issue: I created only one cert at a time, and had to turn off my running apache server to free up port 80.

Thanks for your patient help, @Neilpang.  I'm ready to plunge into creating and installing all 17 certs today.   I'll return if I have any problems.

**Comment by tbrowder** [comment]
Okay, one more question:

I have issued certs using the standalone method.  After I copy them to the desired paths and get apache running and create a webroot dir for each server, how do I get the renewal cron job to use the webroot validation method?

**Comment by Neilpang** [comment]
Do not use standalone mode on the same server if you already have apache running on it.

Please use apache mode or webroot mode instead.

The cert will be renewed automatically.

**Comment by tbrowder** [comment]
It looks like this will cure the chicken-and-egg problem of converting new or running domains to an automatic acme system:

1.  Use the standalone method to generate the desired certs.  The apache or other server will have to be shut down during the process. Restart the server after all certs are generated.

2.  Create the necessary directories to support the webroot validation method.

3.  Edit the acme.sh domain conf files to point to the webroot directories.

4.  Install the certs by copying them with acme.sh to the final, desired position.

5.  Modify the apache conf files to use the new certs.

6.  Do a graceful restart and all should be well, and automatic updating should work.

**Comment by Neilpang** [comment]
@tbrowder 

Yes, sometimes.  because the ssl conf is very important and critical.  so, acme.sh doesn't do it for you.
It's our goal not do any harm to your system.
You must change the critical conf file by yourself.

**Comment by tbrowder** [comment]
Does acme.sh have any special requirements for the webroot dir like the certbot naming conventions?

**Comment by Neilpang** [comment]
@tbrowder 
I don't know any "naming conventions".  But acme.sh doesn't have any special requirements.

**Comment by tbrowder** [comment]
Okay, so I can name it anything as long as it is writable?

**Comment by Neilpang** [comment]
@tbrowder 
yes

**Comment by tbrowder** [comment]
Do you see any reason to make it a hidden directory?

**Comment by Neilpang** [comment]
@tbrowder 
yes,  http method.
