### ISSUE TITLE
Simple Question about install

### ISSUE THREAD

**Issue by TheruSantana** [Neilpang/acme.sh#610]
A simple question, I executed the commands in sequence:

First:
`curl https://get.acme.sh | sh`
So I had a **positive** response about the download and installation. Great

Second:
`acme.sh --issue -d inglescomleoreis.com -d www.inglescomleoreis.com -w /home2/r6g6w9b2/www`
So I had a **positive** response about the process, certificate issued and location of them. Great

Third:
`acme.sh --install-cert -d inglescomleoreis.com`
When I run this third command I did not get any **positive** or **negative** response from the script. It just runs (I believe) so I now do not know if the certificates are actually properly installed in Apache or not ...

Is there any **test** for me to find out if it's all right or not? I looked in the log and I did not understand what is there.

Thanks a lot!

**Comment by Neilpang** [comment]
you must specify the other parameters :  --certpath, --keypath etc,   otherwise acme.sh can not know where to install the cert.

**Comment by TheruSantana** [comment]
Thanks for your answer. Is there any way to find out these paths in apache? I am using hostgator but the support unfortunately refuses to inform me.

**Comment by Neilpang** [comment]
@TheruSantana   Can you login as root ?

you need to enable https for your website first.  When you enable https for your website, you will know where the files are located.

https://github.com/Neilpang/acme.sh/wiki/Blogs-and-tutorials

**Comment by TheruSantana** [comment]
Thanks man.
