### ISSUE TITLE
Perl 6 version?

### ISSUE THREAD

**Issue by tbrowder** [Neilpang/acme.sh#612]
Any objection to creating a Perl 6 version of acme.sh?

**Comment by Neilpang** [comment]
implement in Perl ?
I don't write Perl.  But I don't mind anyone writing one.

**Comment by tbrowder** [comment]
On Sun, Feb 12, 2017 at 7:18 PM, neil <notifications@github.com> wrote:
> implement in Perl ?
> I don't write Perl. But I don't mind anyone writing one.

Thanks!

-Tom

**Comment by bittorf** [comment]
it's about portability and lowering dependencies. perl6 seems to be the opposite, does'nt it?
