### ISSUE TITLE
Using existing CSR - Error - Can not read key length from csr

### ISSUE THREAD

**Issue by TomFreudenberg** [Neilpang/acme.sh#614]
Hi, thanks for your tool!

I run in an issue when using existing CSR files. This occurs when using `--signcsr` or `--showcsr`. Those will stop with message:

```
Can not read key length from csr: file.csr
```

[Code L3434](https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L3434)

I have done some debug and found you regex was too _sharp_.

in function `_readKeyLengthFromCSR()` [Code L980](https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L980)

You are _grepping_ for `"^ *Public-Key:.*"` but the resulting output (in my case, openssl 0.9.8zh, Mac OSX) is `RSA Public Key: (4096 bit)` without a minus between `Public Key` and there can be tabs as well as spaces in front.

I changed you regex in [Code L993](https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L993) to:

```
echo "$_outcsr" | _egrep_o "^.*Public(-| )Key:.*" | cut -d '(' -f 2 | cut -d ' ' -f 1
```

Maybe you are interested in this.

Cheers
Tom

**Comment by Neilpang** [comment]
fixed  thank you.

**Comment by TomFreudenberg** [comment]
Hi Neil @Neilpang please check my additional comment on your commit at https://github.com/Neilpang/acme.sh/commit/72af092cc1ac37908954366edf3abf05d7fae4be#commitcomment-20894340

**Comment by Neilpang** [comment]
@TomFreudenberg 
Thanks,  I saw your comment.

I will think about it later.

**Comment by TomFreudenberg** [comment]
Hi @Neilpang 

thanks, that works for me.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
@Neilpang sorry did not work ... I hadn't updated your script first time test.

You Regex needs to be like

```
"^ *(RSA )?Public.Key:.*"
```

**Comment by JackWindows** [comment]
I think there is a mistake in the code right now:
In [Code L1141](https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L1141)
```
echo "$_outcsr" | tr "\t" " " | (_egrep_o "^ *Public.Key:.*" || _egrep_o "RSA Public.Key:.*") | cut -d '(' -f 2 | cut -d ' ' -f 1
```
The ```||``` operator here is wrong, you cannot re-read the piped text twice, so the latter part ```_egrep_o "RSA Public.Key:.*"``` will never return a match.
The right way to do this is changing
```
(_egrep_o "^ *Public.Key:.*" || _egrep_o "RSA Public.Key:.*")
```
to
```
while read line ; do ( ! ( echo $line |  _egrep_o "^ *Public.Key:.*" ) || ! ( echo $line | _egrep_o "RSA Public Key: .*")) ; done
```

**Comment by Neilpang** [comment]
@JackWindows   Thank you.
I will fix it soon.

**Comment by Neilpang** [comment]
@JackWindows 
fixed.  please try again.
