### ISSUE TITLE
acme.sh file names confusion (nodejs config)

### ISSUE THREAD

**Issue by aug-riedinger** [Neilpang/acme.sh#618]
Thanks a lot for this repo. Been using letsencrypt before with a lot of struggle and it's never been so easy with acme.sh 😄 

That said, I'm slightly confused with the filenames produced during the process. Especially, my ssl config says I need to add full chain with I won't make it work. Hope I could get some help here!

I get from [ssltest](https://www.ssllabs.com/ssltest/analyze.html)

> This server's certificate chain is incomplete. Grade capped to B.

Looking on [the web](https://community.letsencrypt.org/t/node-js-configuration/5175), I found that I need the following config to make it work:

```
var https = require('https');
var fs = require('fs');
var options = {
     key: fs.readFileSync('/path/to/privkey.pem'),
     cert: fs.readFileSync('/path/to/fullchain.pem'),
     ca: fs.readFileSync('/path/to/chain.pem')
}
var server = https.createServer(options, handlerFunction);
server.listen(8080, '127.0.0.1');
```

[This page](http://www.benjiegillam.com/2012/06/node-dot-js-ssl-certificate-chain/) suggests the files:

```
key: "/path/to/server.key",
cert: "/path/to/mydomain.crt",
ca: "/path/to/mydomain.ca-bundle"
```

And from acme.sh, I have:

```
-rw-r--r-- 1 root root 1647 Feb  8 17:55 ca.cer
-rw-r--r-- 1 root root 3452 Feb  8 17:55 fullchain.cer
-rw-r--r-- 1 root root 1805 Feb  8 17:55 example.com.cer
-rw-r--r-- 1 root root  512 Feb  8 17:55 example.com.conf
-rw-r--r-- 1 root root  944 Feb  8 17:55 example.com.csr
-rw-r--r-- 1 root root  175 Feb  8 17:55 example.com.csr.conf
-rw-r--r-- 1 root root 1675 Feb  8 17:55 example.com.key
```

Any idea which file goes where? Shouldn't the filenames be specified to avoid confusion? What do all the `example.com.*` correspond to? Why so many files?

Thanks for support

**Comment by Neilpang** [comment]
Please read the output message after you issue the cert.  you will now where the cert/key/fullchain files are.

**Comment by aug-riedinger** [comment]
I finally figured it out, but thought it would be interesting to raise the
idea of having some common file names across various ssl implementations to
make it easy.

I guess it is not trivial though.
