### ISSUE TITLE
acme.sh make changes in .bashrc PS= line

### ISSUE THREAD

**Issue by Reborns** [Neilpang/acme.sh#622]
Hi, 

I have a line in my .bashrc file 
`PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]\[\033[01;31m\]\h \[\e[0;36m\]\t \[\033[01;33m\]\W\[\033[01;34m\] # \[\033[00m\]"`

after running acme.sh --upgrade this line is changed to 
`PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\]\[\]\h \[\e[0;36m\]     \[\]\W\[\] # \[\]"`
this happening every time when i run acme.sh --upgrade
I am on Debian Jessie x64

**Comment by Neilpang** [comment]
I see.
