### ISSUE TITLE
cloudxns dns模式

### ISSUE THREAD

**Issue by kalagxw** [Neilpang/acme.sh#625]
Debug log
-----------------
[Thu Feb 16 17:14:50 CST 2017] txtdomain='_acme-challenge.kxxxx.top'
[Thu Feb 16 17:14:50 CST 2017] txt='7B8FDw6GLE6MLJ1pD6GEuBXP81NqdMJL2YPkv6m8jgY'
[Thu Feb 16 17:14:50 CST 2017] d_api='/root/.acme.sh/dnsapi/dns_cx.sh'
[Thu Feb 16 17:14:50 CST 2017] Found domain api file: /root/.acme.sh/dnsapi/dns_cx.sh
[Thu Feb 16 17:14:50 CST 2017] First detect the root zone
[Thu Feb 16 17:14:50 CST 2017] ep='domain'
[Thu Feb 16 17:14:50 CST 2017] url='https://www.cloudxns.net/api2/domain'
[Thu Feb 16 17:14:50 CST 2017] cdate='2017-02-16 09:14:50 UTC'
[Thu Feb 16 17:14:50 CST 2017] data
[Thu Feb 16 17:14:50 CST 2017] sec=' 7ad27d200xxxxxx6d80b550https://www.cloudxns.net/api2/domain2017-02-16 09:14:50 UTC3dfcaxxxxxf0'
[Thu Feb 16 17:14:50 CST 2017] hmac='66b73b2878bcxxxxxxxxx45550c054f'
[Thu Feb 16 17:14:50 CST 2017] GET
[Thu Feb 16 17:14:50 CST 2017] url='https://www.cloudxns.net/api2/domain'
[Thu Feb 16 17:14:50 CST 2017] timeout
[Thu Feb 16 17:14:50 CST 2017] _CURL='curl -L --silent --dump-header /root/.acme          .sh/http.header '
[Thu Feb 16 17:14:51 CST 2017] ret='0'
[Thu Feb 16 17:14:51 CST 2017] invalid domain
[Thu Feb 16 17:14:51 CST 2017] Error add txt for domain:_acme-challenge.kxxxxxx.top
[Thu Feb 16 17:14:51 CST 2017] pid
[Thu Feb 16 17:14:51 CST 2017] No need to restore nginx, skip.
[Thu Feb 16 17:14:51 CST 2017] _clearupdns
[Thu Feb 16 17:14:51 CST 2017] Dns not added, skip.

**Comment by Neilpang** [comment]
我试了自己的可以, 
请检查你的 key 是对的.

然后给个 `--debug 2` log
