### ISSUE TITLE
DNS Update with Hosteurope

### ISSUE THREAD

**Issue by nilsbyte** [Neilpang/acme.sh#629]
Is anyone willing to create a script for the DNS way to use with HostEurope? I don't have the knowledge to do this.

**Comment by Neilpang** [comment]
@nilsbyte 
Is the domain api free ? If you can give me an account there with a domain to test, I'd like to have a try.

**Comment by nilsbyte** [comment]
I don't know if they have an API. For DNS, they have something called AutoDNS. Other than that, they have a pretty old fashioned administrative backend for managing such things.

Here is a screenshot:
https://www.hosteurope.de/fileadmin/faq/images/domains/2016-07-20_DNSEintraege.png

I only have my paid account at the moment.

**Comment by Neilpang** [comment]
Here is an example: https://gist.github.com/Aikhjarto/11006704
you can learn it and write your own dns hook.
See https://github.com/Neilpang/acme.sh/tree/master/dnsapi#use-custom-api
