### ISSUE TITLE
Syslog logs debug messages even when --debug not set

### ISSUE THREAD

**Issue by dkerr64** [Neilpang/acme.sh#637]
We may disagree on how to specify what should be logged to syslog, but surely we can agree not to log debug messages unless --debug is specified...

 _debug(), _debug2() and _debug3() all log to syslog before checking whether --debug is set or not.  The culprit is LOG_LEVEL is by default set to 1, and in _debug() you are testing for this before testing whether --debug is set or not.  _debug2() and _debug3() are not as badly affected because LOG_LEVEL is less than their threshold, but it would still be best to test for --debug first.

Please fix... acme.sh is now flooding syslog (when SYS_LOG set) with dozens of debug messages whether requested or not.

Thanks
David

**Comment by Neilpang** [comment]
Hi @dkerr64 

in the default level,  only debug() message and info() message are written to log/syslog,  there is no debug2() or debug3() message.

That was designed like that, not a bug.   The info() message is usually not enough for tracing/debugging.  The info() messages are just some brief notes.   
As for logging, it's designed a little more detailed than info(),  so, the debug() messages are also written to log/syslog.

Please check.

**Comment by dkerr64** [comment]
Yes, debug 2 and 3 are not logged to syslog, my mistake sorry.  But _debug is and it should not be unless I run with --debug.  We've argued this in another thread and in my opinion the default should be _err only.

But it is just ridiculous to log _debug to syslog by default.  No other tool / application does this.  It just clutters up my syslog.   Last night when the cron job ran I am getting 155 error, info and debug messages into my syslog from acme.sh.   Yes you read that right, 155.  All I want is ERRORS to be logged.

I don't understand why you would not provide the granularity a sys admin needs to control what goes into syslog.  but PLEASE get rid of the debug messages at least.  Of that 155,  26 are info messages... I'd really rather not have those as well.   And buried in there are 3 ERROR messages that I really need to know about.  It is really hard to notice those are there when there are 155 messages in total.

PLEASE.  Else I'll have to do my own patching,  but surely I am not the only person that will have this issue?

**Comment by dkerr64** [comment]
Further comments on this... you are treating syslog as if it was an _application_ log, it is not it is a _system_ log.  Messages in syslog are mixed with messages from many other applications and services.  It does not matter that the messages sent to syslog are not enough to trace/debug a problem because that is not the intended purpose... for that we would look into the _application_ log.  When you place messages into syslog you need to be a good neighbor and not flood it with info/debug messages that rightly belong in an application log and not a system log.  Syslog should contain the minimum to alert a sys admin to a potential problem with the system.  The way to do this properly is to provide a mechanism to select what level of logging to put in syslog with a reasonable default (which I continue to suggest be errors only).

**Comment by dkerr64** [comment]
Let me try the security argument with you.  One thing you should never do is put login credentials into a syslog message.  Yet that is exactly what you are doing by default.  It is just not secure... system logs can be exported to other systems, are monitored by external tools, etc.  Many of the DNS API plugin scripts printout the login credentials / keys / secrets in debug messages and by default you are putting them into the system log.  Very bad idea.

Syslog is not something you turn on/off during a debug session... it is a setting that you leave on permanently in a production environment, so that monitoring tools or a system admin can detect something going wrong and act on it.  Acting on it would then involve looking into the specific application log, if it exists, or running the application again to try and reproduce the error.

As currently implemented, syslog feature in acme.sh is unusable. It exposes users DNS service login credentials, it is incredibly noisy... dumping even more than you dump to stdout and not configurable in any way.

Working as designed is no excuse for something that is just plain wrong.

**Comment by Neilpang** [comment]
fixed at https://github.com/Neilpang/acme.sh/pull/638

you can try now.  only the error message is send to syslog now.  but you can request a higher syslog level to see me info/debug/debug2 messages.

I think that's what you want.

As for the credentials, it was known concern, I'm thinking about it.

**Comment by dkerr64** [comment]
Thank you.

**Comment by dkerr64** [comment]
You should consider using standard syslog levels in your code / account.conf as defined in RFC 5424.  These would be recognized by any sys admin...
```
              0       Emergency: system is unusable
              1       Alert: action must be taken immediately
              2       Critical: critical conditions
              3       Error: error conditions
              4       Warning: warning conditions
              5       Notice: normal but significant condition
              6       Informational: informational messages
              7       Debug: debug-level messages

              Table 2. Syslog Message Severities
```
So in acme.sh error would be 3, info 6, debug 7.  As you have multiple debug levels can use 8 and 9 to represent them as they are not defined in the RFC.  This would leave flexibility for future adding of other levels.

**Comment by Neilpang** [comment]
syslog level changed at https://github.com/Neilpang/acme.sh/pull/639

try again.

**Comment by dkerr64** [comment]
Thank you.
