### ISSUE TITLE
Le_HTTPPort=NNNNN

### ISSUE THREAD

**Issue by wion** [Neilpang/acme.sh#646]
Hi @Neilpang,

I'm updating our doc for adding Let's Encrypt certs for sites hosted at WebFaction, because they've now started allowing site owners to add the certs (including _key_ and _intermediate_ certs) via the administration dashboard. Still a manual process though, no automatic renewals. An account can either 'upload' or 'copy/paste' the cert data (we choose to copy/paste data directly from the command-line)...
https://github.com/content-strategy-forum/csf-docs/blob/master/Administrators/WebFaction/creating-ssl-certs-on-webfaction.md

I have a few silly questions I need to run by you for clarification, if you don't mind:

**Q1: `Le_HTTPPort=NNNNN`**

When first running [test certs](https://github.com/content-strategy-forum/csf-docs/blob/master/Administrators/WebFaction/creating-ssl-certs-on-webfaction.md#5-run-a-certificate-test), the command requires using `Le_HTTPPort=NNNNN` (with associated port number) to bind the certs to a port. This all works fine for creating the initial certs. 

My question here is about renewing certs later. Once initial certs have been created and binded to a port, can the `Le_HTTPPort=NNNNN` be dropped in the renewal command? Something like this instead?

```
acme.sh --issue --standalone -d domain.tld -d www.domain.tld
```

**Q2: `--standalone`**

I see your entry for this in the wiki doc on parameters, but it still doesn't explain what "standalone" means. What's the difference between using this parameter and not using it?

**Q3: `--accountemail`**

When I first installed _acme.sh_, I think I used the `--accountemail` parameter to add an email. However, I've never seen any email notifications for a domain where the certs have expired (twice now). I've check the usual places (junk folders, etc). I'm suspecting something is wrong there, but, my questions here for now...

* What command should I run if I want to change the email address? When should I run the command; when installing acme.sh or when creating certs for a new domain?
* What if I want to remove any associated email entirely? Is there a command for that, or is that just a fresh install of _acme.sh_?

**Q4: renewal dates/notices**

Your instructions say that acme.sh renews certs after 60 days, which is what Let's Encrypt recommends too, apparently. But I'm assuming this is only applicable for situations where people are renewing certs automatically, right?

In the case for people like me on WebFaction servers, they require a manual renewal process. I just created new certs for a domain on 17 February, and the expiration date was indicated as 17 May, which is Let's Encrypt's 90 day validity period, of course. 

That's all fine, I don't mind manually renewing, but I was just a little confused by your instructions about renewing after 60 days. That apparently doesn't apply in manual situations.

**Comment by FernandoMiguel** [comment]
when we talk about renewal at 60 days, usually we mean via a cron that takes care of that function.

also keep in mind that LE only accepts a few ports where to validate the SSL request, not any random port

**Comment by wion** [comment]
> when we talk about renewal at 60 days, usually we mean via a cron that takes care of that function.

Okay. Thank you, @FernandoMiguel . That addresses my Q4 item. And I understand about the ports,  no problems there.

**Comment by Neilpang** [comment]
@wion 

>> My question here is about renewing certs later. Once initial certs have been created and binded to a port, can the Le_HTTPPort=NNNNN be dropped in the renewal command? Something like this instead?

Yes, the acme.sh can remember the port, so you just renew the cert, acme.sh knows how to re-do the initial process.

BTW, you don't need to use the env variable `Le_HTTPPort`,  we have a command option: `--http-port NNNN`,  please use that instead.


>> I see your entry for this in the wiki doc on parameters, but it still doesn't explain what "standalone" means. What's the difference between using this parameter and not using it?

In standalone mode,  acme.sh starts a http server internally,  listening at `80`(or `--http-port NNNN` port) to finish the validation.   So, this mode is using when you don't have a webserver running. otherwise there would be a conflict ont `80` port.


>> What command should I run if I want to change the email address? 

We have a command `--update-account`, for updating your account info.

>>When should I run the command; when installing acme.sh or when creating certs for a new domain?

Anytime after you install acme.sh.


>> What if I want to remove any associated email entirely? Is there a command for that, or is that just a fresh install of acme.sh?

In acme protocol, there is an operation `deactivate account`, which is to un-register the account,  but acme.sh has not implement this command yet.

For now, you can just uninstall acme.sh, and remove the `~/.acme.sh` folder,  then re-install again. you will get a fresh new account.


>> Q4: renewal dates/notices

You can renew the cert anytime you want, maybe with `--force` option.  `60` days is just a safe note, just forget it.  Do whatever you want, as long as your site is not broken after `90` days.

**Comment by wion** [comment]
@Neilpang, thank you very much! You're responses are clear and directly helpful!

> In standalone mode, acme.sh starts a http server internally, listening at 80(or --http-port NNNN port) to finish the validation. So, this mode is using when you don't have a webserver running. otherwise there would be a conflict ont 80 port.

I'm wondering, then, if people like me on WebFaction servers can drop the `--standalone` parameter in the command. It seems to me it's not necessary in our case since we're installing acme.sh on the host's server (at least as far as my doc instructs) and using `--http-port NNNN` to provide the specific port. Is that a safe assumption? Or should it be included anyway as safety?

**Comment by Neilpang** [comment]
@wion 
Tell me the commandline options you are using.

**Comment by wion** [comment]
For example this is a test command:

```
acme.sh --http-port NNNN --test --issue --standalone -d domain.tld -d www.domain.tld
```

And the real one would just be without the `--test`` option. But I'm wondering if the real one could just be:

```
acme.sh --http-port NNNN --issue -d domain.tld -d www.domain.tld
```
?

**Comment by wion** [comment]
To clarify, I'm running it now with `--standalone` included and it works, but I'm just wondering if it's redundant in our case, where acme.sh is installed on the hosts Apache server.

**Comment by Neilpang** [comment]
@wion 
You must explicitly specify which mode you want to use on the command line.  It's not redundant .

**Comment by wion** [comment]
Okay. Thanks. I'll just keep using what works. ;)

**Comment by MohammadHejazi** [comment]
I just want to point out that the actual command option is `--httpport` not `--http-port` according to docs (https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert).

**Comment by wion** [comment]
The docs could be a typo. For example, this option seems to be valid with a hyphen: `--update-account`.

@Neilpang, can you clarify?

**Comment by Neilpang** [comment]
@MohammadHejazi  @wion 


The doc is right.   and I was changing the names,  don't worry, if the name is working now, it will work forever.

I just change the names to better ones.
