### ISSUE TITLE
Renewal failed - verify error

### ISSUE THREAD

**Issue by nicobsa** [Neilpang/acme.sh#649]
Hello,

I have some errors while renewing the certs on my server.
acme.sh call this URL : 
https://acme-v01.api.letsencrypt.org/acme/challenge/CNby-kssSRW1vUXgDfjedRlEFtFy6uIylPnzGWuaunw/679182888 : return an error  :  "error": {
    "type": "urn:acme:error:connection",
    "detail": "Could not connect to www.remontees-mecaniques.net",
    "status": 400
  },

which try to check this url : https://www.remontees-mecaniques.net/.well-known/acme-challenge/Tvnry9clBwjPH_X_mbMAZHTaXr29l6VDb_EXUl-CwmQ (this one works on my computer,

------------------

Debug log

[lundi 20 février 2017, 13:06:59 (UTC+0100)] url='https://acme-v01.api.letsencrypt.org/acme/challenge/9SyAmr_k26vf9wujlKiyb5y3NfGUSM9KPVsLBsoL0gk/679195014'
[lundi 20 février 2017, 13:06:59 (UTC+0100)] timeout
[lundi 20 février 2017, 13:06:59 (UTC+0100)] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header '
[lundi 20 février 2017, 13:07:00 (UTC+0100)] ret='0'
[lundi 20 février 2017, 13:07:00 (UTC+0100)] www.remontees-mecaniques.net:Verify error:Could not connect to www.remontees-mecaniques.net
[lundi 20 février 2017, 13:07:00 (UTC+0100)] Debug: get token url.
[lundi 20 février 2017, 13:07:00 (UTC+0100)] GET
[lundi 20 février 2017, 13:07:00 (UTC+0100)] url='http://www.remontees-mecaniques.net/.well-known/acme-challenge/4Ybr-3lPx_8-Xww_h7SOpAxiqasw74lRc7RK9LGwykU'
[lundi 20 février 2017, 13:07:00 (UTC+0100)] timeout='1'
[lundi 20 février 2017, 13:07:00 (UTC+0100)] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --connect-timeout 1'
4Ybr-3lPx_8-Xww_h7SOpAxiqasw74lRc7RK9LGwykU.DT-4Zalg5idj9LV5E-q9lfXs8sj5y_AxYRE2zbPRhNU[lundi 20 février 2017, 13:07:00 (UTC+0100)] ret='0'
[lundi 20 février 2017, 13:07:00 (UTC+0100)] Skip for removelevel:
[lundi 20 février 2017, 13:07:00 (UTC+0100)] pid
[lundi 20 février 2017, 13:07:00 (UTC+0100)] Using config home:/root/.acme.sh
[lundi 20 février 2017, 13:07:00 (UTC+0100)] httpdconfname='apache2.conf'
[lundi 20 février 2017, 13:07:00 (UTC+0100)] httpdroot='/etc/apache2'
[lundi 20 février 2017, 13:07:00 (UTC+0100)] httpdconf='/etc/apache2/apache2.conf'
[lundi 20 février 2017, 13:07:00 (UTC+0100)] httpdconfname='apache2.conf'
[lundi 20 février 2017, 13:07:00 (UTC+0100)] Restored: /etc/apache2/apache2.conf.
[lundi 20 février 2017, 13:07:00 (UTC+0100)] Restored successfully.
[lundi 20 février 2017, 13:07:00 (UTC+0100)] No need to restore nginx, skip.
[lundi 20 février 2017, 13:07:00 (UTC+0100)] _clearupdns
[lundi 20 février 2017, 13:07:00 (UTC+0100)] Dns not added, skip.
[lundi 20 février 2017, 13:07:00 (UTC+0100)] _on_issue_err
[lundi 20 février 2017, 13:07:00 (UTC+0100)] Please add '--debug' or '--log' to check more details.
[lundi 20 février 2017, 13:07:00 (UTC+0100)] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

-----------------

Is there a cache on lets'encrypt server to be reset to allow this check correctly ?
(I have some probleme some weekes ago with the dns "onekisnemble.net and ose.ski" which was resolved after open an issue here)
I was make a mistake when I call the creation, but, here, I check my command line

acme.sh --issue -d www.remontees-mecaniques.net -d antoine.fuzier.remontees-mecaniques.net -d archives.remontees-mecaniques.net -d files.remontees-mecaniques.net -d geofrider.remontees-mecaniques.net -d kilano.remontees-mecaniques.net -d lacpse.remontees-mecaniques.net -d membres.remontees-mecaniques.net -d remontees-mecaniques.net -d rodoaf.remontees-mecaniques.net -d webmail.remontees-mecaniques.net --apache --force --debug

Could you help me ?

Thanks

**Comment by Neilpang** [comment]
Give me the full log of `--debug 2`

**Comment by nicobsa** [comment]
Hi,

here is the end of the trace (while checking the website) : 

[lundi 20 février 2017, 13:16:37 (UTC+0100)] checking
[lundi 20 février 2017, 13:16:37 (UTC+0100)] GET
[lundi 20 février 2017, 13:16:37 (UTC+0100)] url='https://acme-v01.api.letsencrypt.org/acme/challenge/_W7w8IHqo9TyxliLrerBA_KuctDTSc0qCH3ihxhxFMA/679235580'
[lundi 20 février 2017, 13:16:37 (UTC+0100)] timeout
[lundi 20 février 2017, 13:16:37 (UTC+0100)] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.JMIf9VG5jW '
[lundi 20 février 2017, 13:16:37 (UTC+0100)] ret='0'
[lundi 20 février 2017, 13:16:37 (UTC+0100)] original='{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:unauthorized",
    "detail": "Invalid response from http://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw: \"\u003c!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"\u003e\n\u003chtml\u003e\u003chead\u003e\n\u003ctitle\u003e404 Not Found\u003c/title\u003e\n\u003c/head\u003e\u003cbody\u003e\n\u003ch1\u003eNot Found\u003c/h1\u003e\n\u003cp\"",
    "status": 403
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_W7w8IHqo9TyxliLrerBA_KuctDTSc0qCH3ihxhxFMA/679235580",
  "token": "5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw",
  "keyAuthorization": "5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw.DT-4Zalg5idj9LV5E-q9lfXs8sj5y_AxYRE2zbPRhNU",
  "validationRecord": [
    {
      "url": "http://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw",
      "hostname": "www.remontees-mecaniques.net",
      "port": "80",
      "addressesResolved": [
        "37.187.79.92"
      ],
      "addressUsed": "37.187.79.92"
    },
    {
      "url": "https://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw",
      "hostname": "www.remontees-mecaniques.net",
      "port": "443",
      "addressesResolved": [
        "37.187.79.92"
      ],
      "addressUsed": "37.187.79.92"
    }
  ]
}'
[lundi 20 février 2017, 13:16:37 (UTC+0100)] response='{"type":"http-01","status":"invalid","error":{"type":"urn:acme:error:unauthorized","detail":"Invalid response from http://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw: \"\u003c!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"\u003e\n\u003chtml\u003e\u003chead\u003e\n\u003ctitle\u003e404 Not Found\u003c/title\u003e\n\u003c/head\u003e\u003cbody\u003e\n\u003ch1\u003eNot Found\u003c/h1\u003e\n\u003cp\"","status": 403},"uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/_W7w8IHqo9TyxliLrerBA_KuctDTSc0qCH3ihxhxFMA/679235580","token":"5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw","keyAuthorization":"5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw.DT-4Zalg5idj9LV5E-q9lfXs8sj5y_AxYRE2zbPRhNU","validationRecord":[{"url":"http://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw","hostname":"www.remontees-mecaniques.net","port":"80","addressesResolved":["37.187.79.92"],"addressUsed":"37.187.79.92"},{"url":"https://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw","hostname":"www.remontees-mecaniques.net","port":"443","addressesResolved":["37.187.79.92"],"addressUsed":"37.187.79.92"}]}'
[lundi 20 février 2017, 13:16:37 (UTC+0100)] error='"error":{"type":"urn:acme:error:unauthorized","detail":"Invalid response from http://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw: '
[lundi 20 février 2017, 13:16:37 (UTC+0100)] errordetail='Invalid response from http://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw: '
[lundi 20 février 2017, 13:16:37 (UTC+0100)] www.remontees-mecaniques.net:Verify error:Invalid response from http://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw:
[lundi 20 février 2017, 13:16:37 (UTC+0100)] Debug: get token url.
[lundi 20 février 2017, 13:16:37 (UTC+0100)] GET
[lundi 20 février 2017, 13:16:37 (UTC+0100)] url='http://www.remontees-mecaniques.net/.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw'
[lundi 20 février 2017, 13:16:37 (UTC+0100)] timeout='1'
[lundi 20 février 2017, 13:16:37 (UTC+0100)] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.JezLKTaSB8  --connect-timeout 1'
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /.well-known/acme-challenge/5FNwHrVuArb3RvqyNTxtKRErg5heWy0ehhnYQVbzuJw was not found on this server.</p>
</body></html>
[lundi 20 février 2017, 13:16:37 (UTC+0100)] ret='0'
[lundi 20 février 2017, 13:16:37 (UTC+0100)] no webroot specified, skip
[lundi 20 février 2017, 13:16:37 (UTC+0100)] pid
[lundi 20 février 2017, 13:16:37 (UTC+0100)] No need to restore nginx, skip.
[lundi 20 février 2017, 13:16:37 (UTC+0100)] _clearupdns
[lundi 20 février 2017, 13:16:37 (UTC+0100)] Dns not added, skip.
[lundi 20 février 2017, 13:16:37 (UTC+0100)] _on_issue_err
[lundi 20 février 2017, 13:16:37 (UTC+0100)] Please add '--debug' or '--log' to check more details.
[lundi 20 février 2017, 13:16:37 (UTC+0100)] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[lundi 20 février 2017, 13:16:38 (UTC+0100)] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.1t  3 May 2016
apache:
apache doesn't exists.
nc:
[v1.10-40]
connect to somewhere:   nc [-options] hostname port[s] [ports] ...
listen for inbound:     nc -l -p port [-options] [hostname] [port]
options:
        -c shell commands       as `-e'; use /bin/sh to exec [dangerous!!]
        -e filename             program to exec after connect [dangerous!!]
        -b                      allow broadcasts
        -g gateway              source-routing hop point[s], up to 8
        -G num                  source-routing pointer: 4, 8, 12, ...
        -h                      this cruft
        -i secs                 delay interval for lines sent, ports scanned
        -k                      set keepalive option on socket
        -l                      listen mode, for inbound connects
        -n                      numeric-only IP addresses, no DNS
        -o file                 hex dump of traffic
        -p port                 local port number
        -r                      randomize local and remote ports
        -q secs                 quit after EOF on stdin and delay of secs
        -s addr                 local source address
        -T tos                  set Type Of Service
        -t                      answer TELNET negotiation
        -u                      UDP mode
        -v                      verbose [use twice to be more verbose]
        -w secs                 timeout for connects and final net reads
        -z                      zero-I/O mode [used for scanning]
port numbers can be individual or ranges: lo-hi [inclusive];
hyphens in port names must be backslash escaped (e.g. 'ftp\-data').

**Comment by nicobsa** [comment]
It now ok, the certif is renewed now

[lundi 20 février 2017, 13:22:10 (UTC+0100)] 11:Le_CertCreateTime='1487593330'
[lundi 20 février 2017, 13:22:10 (UTC+0100)] 12:Le_CertCreateTimeStr='lundi 20 février 2017, 12:22:10 (UTC+0000)'
[lundi 20 février 2017, 13:22:10 (UTC+0100)] 13:Le_NextRenewTimeStr='vendredi 21 avril 2017, 12:22:10 (UTC+0000)'
[lundi 20 février 2017, 13:22:10 (UTC+0100)] 14:Le_NextRenewTime='1492690930'
[lundi 20 février 2017, 13:22:10 (UTC+0100)] _on_issue_success


do you made some thing on servers ?

**Comment by Neilpang** [comment]
@nicobsa  No, nothing.

**Comment by nicobsa** [comment]
hummm strange ! ...

**Comment by Neilpang** [comment]
sometimes your server may have cache

**Comment by nicobsa** [comment]
ok

Thanks for "none" XD
Thanks for all, and for acme.sh !
