### ISSUE TITLE
Where is ssl certificate key?

### ISSUE THREAD

**Issue by LexiconCode** [Neilpang/acme.sh#652]
I am new to acme.sh. I executed the following command successfully.

./acme.sh  --signcsr  --csr /acme.sh/0000_csr-certbot.pem -d testingwebsite.com  --tls

Generating the following  in '/root/.acme.sh/testingwebsite.com'
ca.cer
fullchain.cer
testingwebsite.com.cer
testingwebsite.com.conf
testingwebsite.com.csr

Before copying these files outside the directory I was expecting to find *.key

To set up nginx SSL
ssl_certificate /path/to/signed_cert_plus_intermediates;
ssl_certificate_key /path/to/private_key;

**Comment by Neilpang** [comment]
You use `signcsr`,  acme.sh doesn't know where the key is.
You should have your key when you generate the csr.

**Comment by LexiconCode** [comment]
Thank you for your reply. I'm migrating from certbot letsencrypt which was configured with lighttpd to acme with nginx.

Previously the configuration of lighttpd was done automatically by certbot. Due to my unusual setup acme I have to configure the web server configuration by hand.

looking in my old set up 'letsencrypt\live\testingwebsite.com' 
cert.pem
chain.pem
combined.pem
fullchain.pem
privkey.pem

What would be the correct way to import my previous set up into acme.sh

**Comment by Neilpang** [comment]
The east way is to issue a new cert(with new private key):

```sh
acme.sh --issue .......
```
