### ISSUE TITLE
Problem/question with acme.sh cron renew and apache (still running)

### ISSUE THREAD

**Issue by ArfyFR** [Neilpang/acme.sh#657]
Hi,

Acme is up to date, -v says "https://github.com/Neilpang/acme.sh v2.6.7"
About our apache:
```
apache2 -v
Server version: Apache/2.2.22 (Debian)
Server built:   Jul 20 2016 11:32:01
```

Problem: the root get emails which says "Error renew <url>", 
Subject: 
```
Cron <root@tools> "/root/.acme.sh"/acme.sh --cron --home
"/root/.acme.sh" > /dev/null (failed)
```
Body:
```
[Wed Feb 22 00:00:02 CET 2017] LISTEN     0      0             <IP>:443                      *:*      users:(("apache2",17156,5),("apache2",17155,5),("apache2",17153,5),("apache2",17147,5),("apache2",17145,5),("apache2",16894,5),("apache2",16892,5),("apache2",16615,5),("apache2",16610,5),("apache2",16335,5),("apache2",16333,5),("apache2",1469,5))
[Wed Feb 22 00:00:03 CET 2017] tcp port 443 is already used by (("apache2",17156,5),("apache2",17155,5),("apache2",17153,5),("apache2",17147,5),("apache2",17145,5),("apache2",16894,5),("apache2",16892,5),("apache2",16615,5),("apache2",16610,5),("apache2",16335,5),("apache2",16333,5),("apache2",1469,5))
[Wed Feb 22 00:00:03 CET 2017] Please stop it first
[Wed Feb 22 00:00:03 CET 2017] _on_before_issue.
[Wed Feb 22 00:00:03 CET 2017] Error renew <url>, Go ahead to next one.
```
(I replaced IP and url)

Here is the crontab -l:
`0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null`

Now I have the same error on other servers

Temporary resolution:

- stop apache
- do again a `acme.sh  --issue --tls --standalone -d <url>`
- install it again : `acme.sh --installcert --apache -d <url> --certpath      /etc/ssl/certs/<url><.crt  --keypath       /etc/ssl/private/server.key  --fullchainpath /etc/ssl/certs/startssl.root.bundle.crt --reloadcmd     "service apache2 restart"`

Steps to reproduce
------------------
Wait for the cron or type the command by hand
` acme.sh --apache --renew-all`

See Debug log with option "--debug"
( ret code 4 is Network failure)

Debug log
-----------------
```
[Sat Feb 18 21:07:45 CET 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/<the_challenge_1>'
[Sat Feb 18 21:07:45 CET 2017] timeout
[Sat Feb 18 21:07:45 CET 2017] _WGET='wget -q'
[Sat Feb 18 21:07:46 CET 2017] ret='0'
[Sat Feb 18 21:07:46 CET 2017] <url>:Verify error:Could not connect to <url>
[Sat Feb 18 21:07:46 CET 2017] Debug: get token url.
[Sat Feb 18 21:07:46 CET 2017] GET
[Sat Feb 18 21:07:46 CET 2017] url='http://<url>/.well-known/acme-challenge/<the_challenge_2>'
[Sat Feb 18 21:07:46 CET 2017] timeout='1'
[Sat Feb 18 21:07:46 CET 2017] _WGET='wget -q --timeout=1'
[Sat Feb 18 21:07:46 CET 2017] Please refer to https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html for error code: 4
[Sat Feb 18 21:07:46 CET 2017] ret='4'

acme.sh  --issue .....   --debug 2

```

What did I wrong ?

**Comment by Neilpang** [comment]
1. Do not stop apache.

2. Then: `acme.sh --issue --apache  -d <url>`

3. Then: `acme.sh --installcert  -d <url> --certpath /etc/ssl/certs/<url><.crt --keypath /etc/ssl/private/server.key --fullchainpath /etc/ssl/certs/startssl.root.bundle.crt --reloadcmd "service apache2 restart" `

**Comment by ArfyFR** [comment]
Oh, ok thanks, it worked.

Question: will it be renewed with the cron now/next time ?

**Comment by Neilpang** [comment]
Yes
