### ISSUE TITLE
How to switch from dns to webroot

### ISSUE THREAD

**Issue by teschulz** [Neilpang/acme.sh#661]
When I first got the certificate for adi.com, I issued it with --dns and entered the required records on our dns server. That worked. Now I would like to switch to using our webserver using webroot, but something is remembering that we used dns even if I do a new issue. I even tried deleting all of the files from the first issue and tried to issue again, but it still wants to use dns. Any ideas?

**Comment by Neilpang** [comment]
You don't need to `switch`.  if you use webroot mode later than dns mode,  then webroot mode will be taking effect.

Please give me `--debug 2` log.

**Comment by teschulz** [comment]
OK, things are a little different than I thought. The reason that I thought that DNS was being tried is because the adi.com.csr.conf file has DNS in front of each domain name. What looks to be happening when trying to use webroot is that each domain name is expected to have a web site that can give out the key. But in our case only www.adi.com will be able to do that.  Following is the command  I used:

./acme.sh --debug 2 --issue --force --webroot /home/projects/www/documents -d adi.com -d mackerel.adi.com -d www.adi.com -d hlr.adi.com -d spr.adi.com -d ecr.adi.com -d ftp.adi.com -d corp.adi.com -d apollo.adi.com -d iris.adi.com -d proteus.adi.com -d rt.adi.com -d mail.adi.com -d seahorse.adi.com -d bluegill.adi.com -d dolphin.adi.com

Attached is the log.
[opps.log.txt](https://github.com/Neilpang/acme.sh/files/800004/opps.log.txt)

**Comment by teschulz** [comment]
What I attached above is a capture of the output the the screen. Here is the log file as written directly to the disk. Each has information that  the other does not have.
[acme.sh.log.txt](https://github.com/Neilpang/acme.sh/files/800187/acme.sh.log.txt)

**Comment by Neilpang** [comment]
You only give one webroot folder ` --webroot /home/projects/www/documents`,  but you give multiple domains,  that means you must point all the domains in the savme webroot folder.   Is that true ?

Are all the domains pointing to the same server and  bind to the same website folder in `/home/projects/www/documents`  ?

**Comment by teschulz** [comment]
> You only give one webroot folder --webroot /home/projects/www/documents, but you
> give multiple domains, that means you must point all the domains in the same webroot folder.
> Is that true ?
I think the  answer is yes, but see below.

> Are all the domains pointing to the same server and bind to the same website folder in
> /home/projects/www/documents ?

Let me see if I can explain the situation better. Our main website is www.adi.com and that is the one that uses  the webroot folder that I specified. A connection to http://adi.com will redirect  to www.adi.com and so will also get to our main web site.

Some of the other domains are for specialized web servers such as several versions of bugzilla and svn. Others are for email. And one is for general purpose testing. None of those can serve up anything placed in the specified document root or any document root. But for these sites to use the certificate, the certificate has to claim to be valid for all of them.

**Comment by Neilpang** [comment]
Yes, I understand.

But it's required to validate every domin/sub-domain before you can issue a cert. 

It's no problem to validate  `www.adi.com ` and `adi.com `, since they are redirected to the same server.  but the other domains, like `mail.adi.com` or `ftp.adi.com`, are not pointing to the same server.  They can not be validated.

There are 3 options you can use to issue cert to the other domains:

1. Run acme.sh on each server that needs a cert, and issue cert only for the domains that are pointing to the server.  For example: in the server `ftp.adi.com`,  run `acme.sh --issue -d ftp.adi.com ....`, requesting cert for the domain `ftp.adi.com` only.

1. If you really want to request cert for all the domains in one cert,  you need configure redirect from the other server to the main server. For example: let's assume you are running acme.sh on `adi.com`.
You must rewrite/redirect the following urls on `ftp.adi.com`:
```
http://ftp.adi.com/.well-known/acme-challenge/*  to http://adi.com/.well-known/acme-challenge/*
```

1. you can also configure `stateless` mode on the other servers: https://github.com/Neilpang/acme.sh/wiki/Stateless-Mode

**Comment by teschulz** [comment]
I  see that what I am trying to do will not  work. I assumed that all the domain names could be validated through the main web  server. I will  close this in a day or two to allow for any last minute comments.

**Comment by Neilpang** [comment]
Yes,  every domain in the cert must be validated.

**Comment by teschulz** [comment]
I am going to go back to dns and use dns_nsupdate. Form the example for that, it looks like acme.sh assumes that  the key name is 'update'.  Is that correct?

**Comment by Neilpang** [comment]
yes,  just follow the guide.

**Comment by teschulz** [comment]
The documentation shows setting NSUPDATE_KEY to the key itself, but the code wants NSUPDATE_KEY to be the key file which makes much more sense. It looks like I am all set. I will close  this tomorrow.

**Comment by Neilpang** [comment]
If you find there is any error in the doc, please fix  it and give me a PR
Thanks.

**Comment by teschulz** [comment]
It is working fine with dns_nsupdate, closing.
