### ISSUE TITLE
--reloadcmd not called after manual dns renew action.

### ISSUE THREAD

**Issue by PiBa-NL** [Neilpang/acme.sh#662]
Found something that looks like a bug when using manual dns TXT record in combination with --reloadcmd..

First call acme.sh issue, this shows the TXT record to add..
Then call acme.sh renew, to validate the TXT record, and get the issued certificate.

Expected result --reloadcmd is called and also stored in the domain.conf file. It is however not..

A possible fix shown here where --reloadcmd is also used with the renew command: https://github.com/pfsense/FreeBSD-ports/pull/312/files

**Comment by Neilpang** [comment]
Hi @PiBa-NL ,

If you use dns manual mode, please follow these steps:


1. `acme.sh --issue  -d ....  --dns `
1. `acme.sh --renew-d xxxxx `
1. `acme.sh --install-cert   -d xxxxx   --reloadcmd .....  `


You should call `--install-cert` after the cert is issued success.  Then the reloadcmd is saved and called, and it will be called in future renew automatically.

**Comment by PiBa-NL** [comment]
But where/how does my own script know the issue of step 2 was successful? _chk_post_hook is also called upon failure and does not seem to have parameters telling it failed/succeeded. Or is the only method for that to check if a new cert was written out to disk.? I was hoping that some hook/cmd would always be called.

**Comment by Neilpang** [comment]
@PiBa-NL   You will add the txt record by hand ?  or, you have your own script to add txt record via some api automatically ?

**Comment by PiBa-NL** [comment]
We need to add the txt by hand if choosing the manual method, but the 'acme package' on pfSense currently gives the user 2 buttons for issuing or renewing. And i would like to automatically load the certificate whenever one is issued successful. It seemed to me like that is when --reloadcmd would be called.

**Comment by Neilpang** [comment]
I mean if you are sure to use  dns manual method,   you have to follow the 3 steps I posted above.
From the exit code of the step 1 or step 2, you can know whether it's success or error.

Yes, you can reload the server in `--reloadcmd` or `--post-hook` or `--renew-hook`, they will be called after the cert is issued/renewed.

**Comment by PiBa-NL** [comment]
> Yes, you can reload the server in --reloadcmd or --post-hook or --renew-hook, they will be called after the cert is issued/renewed.

But the certificate **is issued** at step 2, but **reloadcmd is not called**, imho thats 'unexpected'.

Then if you then try again and step1+step2 are run then reloadcmd **is called** , i still do think thats inconsistent.. And the 3rd step while 'needed' to make it work with the script as it currently is, it seems unnecessary.
Ill check if the post-hook or renew-hook work differently. Maybe they will 'solve' my use case though are a bit more tricky to use..

Thanks for your replies 👍

**Comment by Neilpang** [comment]
@PiBa-NL 
Do not hesitate if have any problems or requirements,  please let me, I'd try my best to help you.

**Comment by dessant** [comment]
The underlying issue is that the config options are not updated from new parameters and not taken into account after the first call has created the config file. I too find it unexpected, and it reduces the usability of the client.

One would want to run in standalone mode when the server is bootstapped and the first certificate is issued, then switch to webroot ( and optionally --reloadcmd) for renewals, but this is not possible without manually editing the config file to change both options.

Previous discussion on the topic: https://github.com/Neilpang/acme.sh/issues/544.
