### ISSUE TITLE
new-authz's are leaking in case of authorization failure; on many attempts, that leads to 429 Too many currently pending authorizations

### ISSUE THREAD

**Issue by shimile** [Neilpang/acme.sh#663]
Steps to reproduce
------------------
Try to issue a SAN/UCC cert for a large amount of subdomains (in stateless mode if it matters), some of them failing authz for whatever reason (many times it would be the users' fault, but I think it doesn't matter, if the script can be resilient to that) - then user trying to fix issues one by one; Meanwhile, the pending authz requests are NOT re-used, and are also not cleared by either a successful or failed verify; With enough attempts to re-create the cert, eventually there would be 300 pending authz requests and then the user can't do anything for a full week until they all expire and LE lets the user issue certs again.

Suggested solutions
------------------
1. Keep and re-use authz's on repeating attempts for the same domains/subdomains
2. Finish authz's in case of failure, so they get cleared and not accumulated in letsencrypt's queue - if that is possible (can't say I understand the protocol in depth at the moment, sorry!)
3. Allow for an option (maybe it should even be the default with an optional --strict flag to reverse it) to just not add failed subdomains to the requested cert, and just emit an error to stderr (cron will notify the admin of the failure); So at least all the other subdomains sharing the cert won't fail; This is especially important in renewals, I think. Due to the short span of LE's certs and their plan to make these even shorter in the future, seems to me that breaking just the one site that can't renew (so presumably it doesn't get to the server requesting the cert for it anyway, so doesn't work anyway) - instead of breaking all the certs of the domain using a SAN/UCC cert...

**Comment by Neilpang** [comment]
>> and are also not cleared by either a successful or failed verify;

Not really.   no matter the verification is success or failed, the authz token will be cleared.

If you have too many domains to issue,  please use the staging server first, when it's working, switch to production server then.

```sh
#staging server
acme.sh --issue .....   --test
```

**Comment by shimile** [comment]
If that is the case, then how did they accumulate and got to the rate limit of 300? The cert had 30 SANs in it. If every failure resulted in the authz to be cleared and no longer being pending, how was the 300 limit achieved?

Yes, I learned about the staging later, though, this shouldn't be required if they're cleared - that's my whole point. The issue with the testing is that the acme account is different, and then, the challenge string you have to return from the web servers must be different. That means changing the config back and forth when working with testing/prod for all those tens of hostnames (not all hostnames necessarily being served by the same server, mind you). In my case it's tens. It could be hundreds or thousands for other people, and the same with large clusters serving requests which all need to be updated back and forth instead of just having static nginx configuration :-)

**Comment by FernandoMiguel** [comment]
@shimile in case of large amounts of domains , you might need to request an exception
https://letsencrypt.org/docs/rate-limits/

**Comment by Neilpang** [comment]
>> If that is the case, then how did they accumulate and got to the rate limit of 300? The cert had 30 SANs in it. If every failure resulted in the authz to be cleared and no longer being pending, how was the 300 limit achieved?

I guess, the process stopped before verification.  If you have logs, it could help us know.


I think staging server is the best option for you.

**Comment by shimile** [comment]
no, I don't have large domains; and I would not have met the limits if a cleanup of the authz's after a failure to verify the challenge did indeed took place; the issue happened because I repeatedly failed. this is similar to a program that allocates memory and forgets to release it after it's no longer in use - there we call it "memory leak". per https://community.letsencrypt.org/t/error-429-too-many-pending-authorizations/27273 this is a buggy client behaviour. I will be cautious not to do this again.

Yes, the process stopped before verification, that is my point. it does new-authz on every subdomain, only after it finishes, it does the verify; if any new-authz fails, verification does not happen, and old authz isn't cleared. I don't have the logs but that's what happens. My point is that the authz's need to be cleared in case of failure, prior to exiting. Alternatively, if possible the flow can be changed to make new-authz, then verify (which will clear it, I guess?), and after all the authz-verifies end, do the sign. that way, you'll accumulate just one pending authz per each run - the last one that failed.

**Comment by Neilpang** [comment]
>> if any new-authz fails, verification does not happen

Why  new-authz would fail ?  Can you give me some log ?  It should never fail at the moment.


>> Alternatively, if possible the flow can be changed to make new-authz, then verify (which will clear it, I guess?), 

No,  we used to do that like you said in our early versions, but if dns method is used, we the dns record may need some time to take effect. so, we change to the current behavior,  requesting all the new-authz tokens,  then deploy all the tokens,  then start to verify all the domains one by one.

**Comment by shimile** [comment]
> Why new-authz would fail ? Can you give me some log ? It should never fail at the moment.

Not due to the client error. I'm using stateless mode. In stateless, I put a static response in Nginx so acme.sh can run in a separate unprivileged process, and still have its' requests authenticated. I followed this guide: https://github.com/Neilpang/acme.sh/wiki/Stateless-Mode

Now, if I messed up (I totally take the fault for it! But still I think acme.sh could save someone from shoorting himself in the foot if it can!) - and forgot to add the challenge lines on some subdomains, or I did but it broke due to other configs (reason doesn't really matter) - then the authz will fail. And when repeatedly run - will accumulate pending requests. That was my scenario.

**Comment by Neilpang** [comment]
@shimile 
Show me the log, and what command you are using.

**Comment by shimile** [comment]
@Neilpang, here is how such a failure looks like:

[Fri Feb 24 10:42:40 IST 2017] Verifying:sub1.domain.net
[Fri Feb 24 10:42:40 IST 2017] Stateless mode for domain:sub1.domain.net
[Fri Feb 24 10:42:46 IST 2017] sub1.domain.net:Verify error:Invalid response from http://sub1.domain.net/.well-known/acme-challenge/<redacted> [<redacted>]: 404
[Fri Feb 24 10:42:46 IST 2017] Please add '--debug' or '--log' to check more details.
[Fri Feb 24 10:42:46 IST 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

The command is:
acme.sh --issue --keylength ec-256 --stateless -d domain.net -d sub1.domain.net -d sub2.domain.net [...] 30 like these --fullchainpath /etc/ssl/nginx/domain.net.crt --keypath /etc/ssl/nginx/domain.net.key

**Comment by Neilpang** [comment]
Can you please visit the sub domain in your browser ?

```
http://sub1.domain.net/.well-known/acme-challenge/test
```

**Comment by shimile** [comment]
@Neilpang, without testing, I can assure you, that since the issue was misconfiguration of the .well-known catch-all regexp, it would return 404.

Again, I think I am mis-understood. The issue is NOT in what acme.sh is doing; It is what it is NOT doing, in case of a user (not acme.sh, user! me! and other people...) error - it leaves all the web authz requests in pending state; Depending on when was the failure (let's say it was after 70 subdomains with a successful authz, where the .well-known catch all is configured correctly), you could be adding 70 pending requests that will never finish; After 3 attempts of trial and error (fixing the last failure every time), you'll already have 240 pending requests in the queue. The next time you try, even with everything fixed, after the 60th subdomain, you'll hit the 300 limit; Then you can't do anything for a full week until they all expire.

**Comment by Neilpang** [comment]
@shimile  fixed,  next time when there is error validating the domains,  all the pending authz code will be cleared.  you will not trigger the 300 limit again.

**Comment by shimile** [comment]
Thanks,

May I know how much time you spent on fixing this?

**Comment by Neilpang** [comment]
@shimile   one hour or so.

**Comment by Neilpang** [comment]
Thanks  shimile@GitHub.

**Comment by shimile** [comment]
You're welcome :)
