### ISSUE TITLE
Forgot tld

### ISSUE THREAD

**Issue by ygator** [Neilpang/acme.sh#665]
I did
`./acme.sh --issue --dns -d a.example -d b.example.com -d c.example.com`
and should have done
`./acme.sh --issue --dns -d example.com -d a.example -d b.example.com -d c.example.com`

Now it does not know about example.com and it is being called a.example.com

How can I correct this?

Also if later I want to add say d.example.com how to I do that?

Thanks

**Comment by Neilpang** [comment]
When you use the second command:
```
./acme.sh --issue --dns -d example.com -d a.example -d b.example.com -d c.example.com
```


You will get a new cert in the new dir: `~/.acme.sh/example.com/`,  it should work.

**Comment by ygator** [comment]
Thanks.  Do I need to do something with the previous cert like delete or revoke it or something?

**Comment by Neilpang** [comment]
you can delete the previous folder

**Comment by ygator** [comment]
Ok.  Everything is setup correctly now and working.  Thanks a lot.
