### ISSUE TITLE
Create Key Error.  Create Account Key Error

### ISSUE THREAD

**Issue by Coscend** [Neilpang/acme.sh#667]
RE:  Seeking Assistance
Hello Neil, 

acme.sh seems to be very useful and relevant tool to generate SSL Certificate from Let's Encrypt due to its simplicity, ease of use and the least number of additional dependencies.  We would appreciate your assistance with resolving this issue.  

While generating the certificate, we are getting the following error: 
```
"config file is empty, can not read CA_KEY_HASH
...
Create key error
Create account key error"
```

To test, we successfully installed SSL certificate from Let’s Encrypt through Certbot, using both standalone and Web root plugins. 

Environment: CentOS 7.2 (release 1511).
Ports 80 and 88 are open in OS and hardware firewall.
HAProxy routes traffic from port 80 to acme.sh on port 88.

Sincerely,

Hemant @Coscend

Debug log
-----------------

```
acme.sh  --issue -d ... -w <OUR_DOMAIN.COM>  --debug 2
```
```
[Fri Feb 24 23:19:51 CST 2017] DOMAIN_PATH='/usr/local/acme-sh-2.6.7/certs/<OUR_DOMAIN.COM>'
[Fri Feb 24 23:19:51 CST 2017] Le_NextRenewTime
[Fri Feb 24 23:19:51 CST 2017] _on_before_issue
[Fri Feb 24 23:19:51 CST 2017] Le_LocalAddress
[Fri Feb 24 23:19:51 CST 2017] Check for domain='<OUR_DOMAIN.COM>'
[Fri Feb 24 23:19:51 CST 2017] _currentRoot='/usr/local/acme-sh-2.6.7/certs'
[Fri Feb 24 23:19:51 CST 2017] **config file is empty, can not read CA_KEY_HASH**
[Fri Feb 24 23:19:51 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Fri Feb 24 23:19:51 CST 2017] Use default length 2048
[Fri Feb 24 23:19:51 CST 2017] length='2048'
[Fri Feb 24 23:19:51 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Fri Feb 24 23:19:51 CST 2017] Use length 2048
[Fri Feb 24 23:19:51 CST 2017] Using RSA: 2048
[Fri Feb 24 23:19:51 CST 2017] **Create key error.**
[Fri Feb 24 23:19:51 CST 2017] **Create account key error.**
[Fri Feb 24 23:19:51 CST 2017] **_on_issue_err**
[Fri Feb 24 23:19:51 CST 2017] Please check log file for more details: /usr/local/acme-sh-2.6.7/data/acme.sh.log
[Fri Feb 24 23:19:51 CST 2017] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2k  26 Jan 2017
apache:
apache doesn't exists.
nc:
Ncat 6.40 ( http://nmap.org/ncat )
```

**Comment by Neilpang** [comment]
Can you please give me a full low ?

**Comment by Coscend** [comment]
Hello Neil,

 

Thank you for your e-mail.  As you requested, here is the full log when running the command:

./acme.sh --issue -d <OUR_DOMAIN.COM> -w /usr/local/acme-sh-2.6.7/cert --debug 2

 

Full Debug log

[Sat Feb 25 11:09:17 CST 2017] Lets find script dir.

[Sat Feb 25 11:09:17 CST 2017] _SCRIPT_='/usr/local/acme-sh-2.6.7/acme.sh'

[Sat Feb 25 11:09:17 CST 2017] _script='/usr/local/acme-sh-2.6.7/acme.sh'

[Sat Feb 25 11:09:17 CST 2017] _script_home='/usr/local/acme-sh-2.6.7'

[Sat Feb 25 11:09:17 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data

[Sat Feb 25 11:09:17 CST 2017] LE_WORKING_DIR='/usr/local/acme-sh-2.6.7'

https://github.com/Neilpang/acme.sh

v2.6.7

[Sat Feb 25 11:09:17 CST 2017] Using api: 

[Sat Feb 25 11:09:17 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data

[Sat Feb 25 11:09:17 CST 2017] DOMAIN_PATH='/usr/local/acme-sh-2.6.7/cert/<OUR_DOMAIN.COM>'

[Sat Feb 25 11:09:17 CST 2017] 1:Le_Domain='<OUR_DOMAIN.COM>'

[Sat Feb 25 11:09:17 CST 2017] 2:Le_Alt='no'

[Sat Feb 25 11:09:17 CST 2017] 3:Le_Webroot='/usr/local/acme-sh-2.6.7/cert'

[Sat Feb 25 11:09:17 CST 2017] 4:Le_PreHook=''

[Sat Feb 25 11:09:17 CST 2017] 5:Le_PostHook=''

[Sat Feb 25 11:09:17 CST 2017] 6:Le_RenewHook=''

[Sat Feb 25 11:09:17 CST 2017] 7:Le_API='https://acme-v01.api.letsencrypt.org'

[Sat Feb 25 11:09:17 CST 2017] _on_before_issue

[Sat Feb 25 11:09:17 CST 2017] '/usr/local/acme-sh-2.6.7/cert' does not contain 'no'

[Sat Feb 25 11:09:17 CST 2017] Le_LocalAddress

[Sat Feb 25 11:09:17 CST 2017] Check for domain='<OUR_DOMAIN.COM>'

[Sat Feb 25 11:09:17 CST 2017] _currentRoot='/usr/local/acme-sh-2.6.7/cert'

[Sat Feb 25 11:09:17 CST 2017] '/usr/local/acme-sh-2.6.7/cert' does not contain 'apache'

[Sat Feb 25 11:09:17 CST 2017] config file is empty, can not read CA_KEY_HASH

[Sat Feb 25 11:09:17 CST 2017] _saved_account_key_hash

[Sat Feb 25 11:09:17 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data

[Sat Feb 25 11:09:17 CST 2017] Use default length 2048

[Sat Feb 25 11:09:17 CST 2017] length='2048'

[Sat Feb 25 11:09:17 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data

[Sat Feb 25 11:09:17 CST 2017] _createkey for file:/usr/local/acme-sh-2.6.7/key/key

[Sat Feb 25 11:09:17 CST 2017] Use length 2048

[Sat Feb 25 11:09:17 CST 2017] Using RSA: 2048

[Sat Feb 25 11:09:17 CST 2017] Create key error.

[Sat Feb 25 11:09:17 CST 2017] Create account key error.

[Sat Feb 25 11:09:17 CST 2017] _on_issue_err

[Sat Feb 25 11:09:17 CST 2017] Please check log file for more details: /usr/local/acme-sh-2.6.7/data/acme.sh.log

[Sat Feb 25 11:09:17 CST 2017] Diagnosis versions: 

openssl:openssl

OpenSSL 1.0.2k  26 Jan 2017

apache:

apache doesn't exists.

nc:

Ncat 6.40 ( http://nmap.org/ncat )

**Comment by Coscend** [comment]
Hello Neil,
Thank you for your e-mail.  As you requested, here is the full log when running the command:
`./acme.sh --issue -d <OUR_DOMAIN.COM> -w /usr/local/acme-sh-2.6.7/cert --debug 2`

Full Debug log
```
[Sat Feb 25 11:09:17 CST 2017] Lets find script dir.
[Sat Feb 25 11:09:17 CST 2017] _SCRIPT_='/usr/local/acme-sh-2.6.7/acme.sh'
[Sat Feb 25 11:09:17 CST 2017] _script='/usr/local/acme-sh-2.6.7/acme.sh'
[Sat Feb 25 11:09:17 CST 2017] _script_home='/usr/local/acme-sh-2.6.7'
[Sat Feb 25 11:09:17 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Sat Feb 25 11:09:17 CST 2017] LE_WORKING_DIR='/usr/local/acme-sh-2.6.7'
https://github.com/Neilpang/acme.sh
v2.6.7
[Sat Feb 25 11:09:17 CST 2017] Using api:
[Sat Feb 25 11:09:17 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Sat Feb 25 11:09:17 CST 2017] DOMAIN_PATH='/usr/local/acme-sh-2.6.7/cert/<OUR_DOMAIN.COM>'
[Sat Feb 25 11:09:17 CST 2017] 1:Le_Domain='<OUR_DOMAIN.COM>'
[Sat Feb 25 11:09:17 CST 2017] 2:Le_Alt='no'
[Sat Feb 25 11:09:17 CST 2017] 3:Le_Webroot='/usr/local/acme-sh-2.6.7/cert'
[Sat Feb 25 11:09:17 CST 2017] 4:Le_PreHook=''
[Sat Feb 25 11:09:17 CST 2017] 5:Le_PostHook=''
[Sat Feb 25 11:09:17 CST 2017] 6:Le_RenewHook=''
[Sat Feb 25 11:09:17 CST 2017] 7:Le_API='https://acme-v01.api.letsencrypt.org'
[Sat Feb 25 11:09:17 CST 2017] _on_before_issue
[Sat Feb 25 11:09:17 CST 2017] '/usr/local/acme-sh-2.6.7/cert' does not contain 'no'
[Sat Feb 25 11:09:17 CST 2017] Le_LocalAddress
[Sat Feb 25 11:09:17 CST 2017] Check for domain='<OUR_DOMAIN.COM>'
[Sat Feb 25 11:09:17 CST 2017] _currentRoot='/usr/local/acme-sh-2.6.7/cert'
[Sat Feb 25 11:09:17 CST 2017] '/usr/local/acme-sh-2.6.7/cert' does not contain 'apache'
[Sat Feb 25 11:09:17 CST 2017] config file is empty, can not read CA_KEY_HASH
[Sat Feb 25 11:09:17 CST 2017] _saved_account_key_hash
[Sat Feb 25 11:09:17 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Sat Feb 25 11:09:17 CST 2017] Use default length 2048
[Sat Feb 25 11:09:17 CST 2017] length='2048'
[Sat Feb 25 11:09:17 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Sat Feb 25 11:09:17 CST 2017] _createkey for file:/usr/local/acme-sh-2.6.7/key/key
[Sat Feb 25 11:09:17 CST 2017] Use length 2048
[Sat Feb 25 11:09:17 CST 2017] Using RSA: 2048
[Sat Feb 25 11:09:17 CST 2017] Create key error.
[Sat Feb 25 11:09:17 CST 2017] Create account key error.
[Sat Feb 25 11:09:17 CST 2017] _on_issue_err
[Sat Feb 25 11:09:17 CST 2017] Please check log file for more details: /usr/local/acme-sh-2.6.7/data/acme.sh.log
[Sat Feb 25 11:09:17 CST 2017] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.2k  26 Jan 2017
apache:
apache doesn't exists.
nc:
Ncat 6.40 ( http://nmap.org/ncat )
```

**Comment by Neilpang** [comment]
@Coscend 
Do you know what the `-w` parameter is for ?

It's the webroot folder,  not the certs folder.

https://github.com/Neilpang/acme.sh#2-just-issue-a-cert

https://github.com/Neilpang/acme.sh/wiki/Blogs-and-tutorials

**Comment by Coscend** [comment]
Neil,

Thank you for correcting our -w parameter.  With the new command, we are still receiving the same error.  We would appreciate your guidance on what we are missing.
Command:
`./acme.sh --issue -d <OUR_DOMAIN.COM> -w /usr/local/apache2/httpd-2.4.17/htdocs --debug 2
`
htdocs directory has index.html being served by HTTPD listening through port 80.

Error:
```
'/usr/local/apache2/httpd-2.4.17/htdocs' does not contain 'apache'
config file is empty, can not read CA_KEY_HASH
...
Create key error
Create account key error"
```
Sincerely,
Hemant @Coscend

Debug log
------------
```
[Sun Feb 26 23:03:24 CST 2017] Lets find script dir.
[Sun Feb 26 23:03:24 CST 2017] _SCRIPT_='/usr/local/acme-sh-2.6.7/acme.sh'
[Sun Feb 26 23:03:24 CST 2017] _script='/usr/local/acme-sh-2.6.7/acme.sh'
[Sun Feb 26 23:03:24 CST 2017] _script_home='/usr/local/acme-sh-2.6.7'
[Sun Feb 26 23:03:24 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Sun Feb 26 23:03:24 CST 2017] LE_WORKING_DIR='/usr/local/acme-sh-2.6.7'
https://github.com/Neilpang/acme.sh
v2.6.7
[Sun Feb 26 23:03:24 CST 2017] Using api: 
[Sun Feb 26 23:03:24 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Sun Feb 26 23:03:24 CST 2017] DOMAIN_PATH='/usr/local/acme-sh-2.6.7/cert/<OUR_DOMAIN.COM>'
[Sun Feb 26 23:03:24 CST 2017] 1:Le_Domain='<OUR_DOMAIN.COM>'
[Sun Feb 26 23:03:24 CST 2017] 2:Le_Alt='no'
[Sun Feb 26 23:03:24 CST 2017] 3:Le_Webroot='/usr/local/apache2/httpd-2.4.17/htdocs'
[Sun Feb 26 23:03:24 CST 2017] 4:Le_PreHook=''
[Sun Feb 26 23:03:24 CST 2017] 5:Le_PostHook=''
[Sun Feb 26 23:03:24 CST 2017] 6:Le_RenewHook=''
[Sun Feb 26 23:03:24 CST 2017] 7:Le_API='https://acme-v01.api.letsencrypt.org'
[Sun Feb 26 23:03:24 CST 2017] _on_before_issue
[Sun Feb 26 23:03:24 CST 2017] '/usr/local/apache2/httpd-2.4.17/htdocs' does not contain 'no'
[Sun Feb 26 23:03:24 CST 2017] Le_LocalAddress
[Sun Feb 26 23:03:24 CST 2017] Check for domain='<OUR_DOMAIN.COM>'
[Sun Feb 26 23:03:24 CST 2017] _currentRoot='/usr/local/apache2/httpd-2.4.17/htdocs'
[Sun Feb 26 23:03:24 CST 2017] '/usr/local/apache2/httpd-2.4.17/htdocs' does not contain 'apache'
[Sun Feb 26 23:03:24 CST 2017] config file is empty, can not read CA_KEY_HASH
[Sun Feb 26 23:03:24 CST 2017] _saved_account_key_hash
[Sun Feb 26 23:03:24 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Sun Feb 26 23:03:24 CST 2017] Use default length 2048
[Sun Feb 26 23:03:24 CST 2017] length='2048'
[Sun Feb 26 23:03:24 CST 2017] Using config home:/usr/local/acme-sh-2.6.7/data
[Sun Feb 26 23:03:24 CST 2017] _createkey for file:/usr/local/acme-sh-2.6.7/key/key
[Sun Feb 26 23:03:24 CST 2017] Use length 2048
[Sun Feb 26 23:03:24 CST 2017] Using RSA: 2048
[Sun Feb 26 23:03:24 CST 2017] Create key error.
[Sun Feb 26 23:03:24 CST 2017] Create account key error.
[Sun Feb 26 23:03:24 CST 2017] _on_issue_err
[Sun Feb 26 23:03:24 CST 2017] Please check log file for more details: /usr/local/acme-sh-2.6.7/data/acme.sh.log
[Sun Feb 26 23:03:24 CST 2017] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.2k  26 Jan 2017
apache:
apache doesn't exists.
nc:
Ncat 6.40 ( http://nmap.org/ncat )
```

**Comment by Neilpang** [comment]
can you please let me know how you installed acme.sh  ?

**Comment by Coscend** [comment]
Neil,

Thank you for assisting us in digging out the cause.  Below is the information you requested.

Unzipped acme.sh-master.zip in /usr/local/acme-sh-2.6.7. 
cd acme.sh-master
```
./acme.sh --install  \
--home  /usr/local/acme-sh-2.6.7 \
--config-home /usr/local/acme-sh-2.6.7/data \
--certhome  /usr/local/acme-sh-2.6.7/cert \
--accountemail  "E-mail@<OurMailDomain.com" \
--accountkey  /usr/local/acme-sh-2.6.7/key/key \
--accountconf /usr/local/acme-sh-2.6.7/account.conf \
--useragent  "this is my client."
```

It created the following directories and files:
```
/usr/local/acme-sh-2.6.7/account.conf
/usr/local/acme-sh-2.6.7/acme.sh
/usr/local/acme-sh-2.6.7/acme.sh.csh
/usr/local/acme-sh-2.6.7/acme.sh.env
/usr/local/acme-sh-2.6.7/deploy
/usr/local/acme-sh-2.6.7/dnsapi
/usr/local/acme-sh-2.6.7/data
```

It added the following to 
```
.bashrc: . "/usr/local/acme-sh-2.6.7/acme.sh.env"
.cshrc:  source "/usr/local/acme-sh-2.6.7/acme.sh.csh"
```
Sincerely,
Hemant @Coscend

**Comment by Neilpang** [comment]
fixed.  please try again.

**Comment by Coscend** [comment]
Neil,

Thank you.  acme.sh program successfully generated the necessary SSL certificate.

Sincerely,

Hemant @Coscend
