### ISSUE TITLE
DNSMadeEasy implementation fails to remove _acme-challenge TXT record

### ISSUE THREAD

**Issue by thedaveCA** [Neilpang/acme.sh#681]
I was testing the DNSMadeEasy implementation and I observed that the _acme-challenge TXT record is not removed after a certificate is successfully issued, whereas other implementations (Cloudflare) do remove the record once the certificate issued.

Looking in the code, I believe I see why: 

```
dns_me_rm() {
  fulldomain=$1

}
```

Given that it seems that deleting records is completely unimplemented, I don't think additional logs would be useful, but if they're needed, add a note and I can happily comply.

**Comment by Neilpang** [comment]
Let's see what @justmwa  say first.

**Comment by Neilpang** [comment]
@thedaveCA 
Don't worry too much.   the dnsmadEasy api can `update` the record if there is already an existing one. So there should be only txt record at most.

**Comment by Neilpang** [comment]
@thedaveCA 

Please try again.

**Comment by thedaveCA** [comment]
Okay, so the dns_me_rm() function works perfectly, thanks. And thanks for the quick fix!

However, I'm seeing another problem: response='{error: ["Missing API key or HMAC"]}'

I tracked it down to a previous change (my version was a bit older, it seems), this line:

`hmac=$(printf "%s" "$cdate" | _hmac sha1 "$(printf "%s" "$ME_Secret" | _hex_dump | tr -d " ")" hex)`

If I revert this back to an older version, it works: 

`hmac=$(printf "%s" "$cdate" | _hmac sha1 "$(_hex "$ME_Secret")" hex)`

**Comment by Neilpang** [comment]
@thedaveCA 
Please upgrade to the latest code and try again.
```sh
acme.sh --upgrade
```

**Comment by Neilpang** [comment]
@justmwa   can you please have a try also ?

**Comment by justmwa** [comment]
Worked for me before latest code and works for me still after --upgrade.

**Comment by Neilpang** [comment]
@thedaveCA   How is going on ?

**Comment by thedaveCA** [comment]
Sorry about the delay, I'm not sure what's up with my test environment, but when I did a fresh install everything was fine, so I upgraded my live environment and it's also fine. Thanks again!
