### ISSUE TITLE
Calling --reloadcmd or --post-hook after automatic (cron) dns renew action?

### ISSUE THREAD

**Issue by ksuuk** [Neilpang/acme.sh#696]
I tried simulate the situation with command -  "/root/.acme.sh"/acme.sh --force --cron --home "/root/.acme.sh" --post-hook "service dovecot restart". But the --post-hook command did not executed. Also tried --post-hook instead --reloadcmd, but still nothing.

So how restart affected services when cron renews certificate?

And may I suggest, that instead of writing long custom cron lines, You add some configfile, for example ~/.acme.sh/cron.conf etc, which standard, by Your script installed cron line, always parses and executes commands from that file?

**Comment by Neilpang** [comment]
https://github.com/Neilpang/acme.sh/wiki/Using-'--pre-hook',-'--post-hook',-'--renew-hook'-and-'--reload-cmd'
