### ISSUE TITLE
Reload services which use certificate, after automatic cron renew?

### ISSUE THREAD

**Issue by ksuuk** [Neilpang/acme.sh#697]
As I did ask how to do it, but You pointed out, what is possible ( https://github.com/Neilpang/acme.sh/issues/696 ), so I rephrase my question.

Situation - acme.sh is already installed and certificate issued with the command acme.sh --issue --dns -d www.example.com and TXT key is added into domain.com DNS zone file and certificate is in use. Certificate is located in default path "/root/.acme.sh/www.example.com and apache, dovecot and postfix are configured to read certificate directly from the default certificate location "/root/.acme.sh/www.example.com.

Crontab includes:
5 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null 
So after 60 days cron renews this certificate.

Question - how can same cron, after renewing the certificate, reload these services which are using this renewed certificate? If this is not possible, please consider to implement such functionality.

**Comment by Neilpang** [comment]
```
acme.sh --install-cert  -d example.com  --reload-cmd "service apache force-reload && service dovecot restart && service postfix restart"
```

**Comment by ksuuk** [comment]
@Neilpang 

Ok, got the about config syntax idea after looking into www.domain.com.conf file. BTW, correct command is  --reloadcmd ( Unknown parameter : --reload-cmd ).

And one more question, why cron script doesn't show next renewal time information?

"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"
[Sun Mar  5 12:10:08 EET 2017] Renew: 'www.domain.com'
[Sun Mar  5 12:10:08 EET 2017] Skip, Next renewal time is:
[Sun Mar  5 12:10:08 EET 2017] Add '--force' to force to renew.
[Sun Mar  5 12:10:08 EET 2017] Skipped www.domain.com

**Comment by Neilpang** [comment]
>> And one more question, why cron script doesn't show next renewal time information?

please show me the "www.domain.com.conf" file.

**Comment by ksuuk** [comment]
@Neilpang 

Le_Domain='www.domain.com'
Le_Alt='no'
Le_Webroot='dns'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v01.api.letsencrypt.org'
Le_Keylength=''

Le_LinkCert=''
Le_LinkIssuer='https://acme-v01.api.letsencrypt.org/acme/issuer-cert'
Le_CertCreateTime='1488672836'
Le_CertCreateTimeStr='Sun Mar  5 00:13:56 UTC 2017'
Le_NextRenewTimeStr=''
Le_NextRenewTime='1493770436'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath=''
Le_ReloadCmd='service dovecot restart && service postfix restart && service httpdssl restart'
Le_RealFullChainPath=''

**Comment by Neilpang** [comment]
what is your os version ?

**Comment by ksuuk** [comment]
RedHat based customized distro, seems some function doesn't print out the Le_NextRenewTimeStr value, but seems this pure cosmetic feature, so as long the automatic renew based Le_NextRenewTime information work, I can live with that.

**Comment by Neilpang** [comment]
We use the `_time2str()` function to convert the datetime value to datetime string.

https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L1281

Please take a look at the function, and tell me what happens to you.  And if possible please tell me how to fix the `_time2str()` to work on your system.

Thanks.

**Comment by ksuuk** [comment]
Strange, as date gives out correct information:

date -u
Sun Mar  5 11:48:07 UTC 2017
date -u -r acme.sh
Sat Mar  4 18:06:57 UTC 2017

But somehow it's not added into conf file. But no big deal, I can live without it.

**Comment by Neilpang** [comment]
Please try:
```
date -u -d@1493770436
```

**Comment by ksuuk** [comment]
date -u -d@1493770436
date: invalid date `@1493770436'

Seems my date is too old:(.

**Comment by Neilpang** [comment]
try:
```
date --help
```

**Comment by ksuuk** [comment]
Was:
date --version
date (coreutils) 4.5.3

Is now:
date --version
date (GNU coreutils) 5.97

and it gives correct result:
date -u -d@1493770436
Wed May  3 00:13:56 UTC 2017

**Comment by Neilpang** [comment]
good
