### ISSUE TITLE
Implement account registration update

### ISSUE THREAD

**Issue by heldchen** [Neilpang/acme.sh#70]
as the default configuration of `le.sh` no email adress is used, some users might want to add/change their email later on to receive expiration notifications from let's encrypt. the ACME protocol allows updating the email adress assigned to the account. there's [a post on let's encrypt's community](https://community.letsencrypt.org/t/how-do-i-change-the-admin-email-address-used-for-key-recovery/9330/3) which explains how updating an existing account would be done:

> However, there's another good reason you might want to change the email address on an account: So that you get expiration emails. This is supported in the ACME protocol and in the Boulder software: POST a signed update to your account object (aka registration object) with a new value for the Contacts field. However, unfortunately this is not yet implemented in the Python client. We have an open issue for it: https://github.com/letsencrypt/letsencrypt/issues/1215

maybe `le.sh` could provide an "updateAccount" function that takes the current `ACCOUNT_EMAIL` value and POSTs it to LE?

**Comment by Neilpang** [comment]
keep it open, will fix it later.

**Comment by raphaelokon** [comment]
This is probably related – adding a delete function to the registration:
https://github.com/letsencrypt/letsencrypt/issues/2689#issuecomment-199421357

**Comment by Neilpang** [comment]
@heldchen ,  @raphaelokon 

```
acme.sh  --updateaccount  --accountemail  my@domain.com
```
