### ISSUE TITLE
freebsd cron job failed:“env: bash: No such file or directory“

### ISSUE THREAD

**Issue by amutu** [Neilpang/acme.sh#719]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

freebsd的bash安装在/usr/local/bin下面，默认/usr/local/bin不在系统的默认的PATH中，或者cron job的PATH中。安装acme.sh的时候交互式shell可能是包含这个PATH的，所以安装时可以检测到，cron运行时会报这个错误。建议保险起见，把~/.acme.sh/acme.sh的第一行设置为#!/usr/bin/env sh.

**Comment by amutu** [comment]
这是从man 5 crontab中看到的内容

> Several environment variables are set up automatically by the cron(8)
     daemon.  SHELL is set to /bin/sh, PATH is set to /usr/bin:/bin, and
     LOGNAME and HOME are set from the /etc/passwd line of the crontab's
     owner.  HOME, PATH and SHELL may be overridden by settings in the
     crontab; LOGNAME may not.

**Comment by Neilpang** [comment]
谢谢, 已经修了,  如果检测到 bash 就会使用bash的绝对路径, 不再使用env.
请下载最新版本 安装.
