### ISSUE TITLE
cron job reported: chown: invalid user: ‘UNKNOWN:UNKNOWN’

### ISSUE THREAD

**Issue by ovizii** [Neilpang/acme.sh#721]
Steps to reproduce
------------------

**Cron job sent me this email:**
**Subject**: Cron <root@server> "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
**Content**: chown: invalid user: ‘UNKNOWN:UNKNOWN’

Debug log
-----------------

I added --debug to my cron job, then ran the command by hand and got no errors. Might be different when run by the cron daemon. Will update this thread tomorrow after the next cron execution.

Any other hints where to look?

**Comment by Neilpang** [comment]
You can enable the log:
```
acme.sh --update-account --log 
```

**Comment by ovizii** [comment]
I ran that command and only got: 
```
 acme.sh --update-account --log
[Tue Mar 14 08:47:13 CET 2017] Registering account
[Tue Mar 14 08:47:15 CET 2017] Already registered
[Tue Mar 14 08:47:15 CET 2017] Update success.
[Tue Mar 14 08:47:16 CET 2017] ACCOUNT_THUMBPRINT='vPOshqrjuwUaEcK-yaddayadda'
```'

The log doesn't reveal any issues. Hm, I guess we can let this one rest if you have no other ideas.

**Comment by Neilpang** [comment]
Yes,  The command is just enable logging.   Next time you see  error in cronjob,  you will find the log.

**Comment by Neilpang** [comment]
please try again.

**Comment by ovizii** [comment]
Thanks, I'll let you know tomorrow what the cron job produced log says.

**Comment by ovizii** [comment]
no errors in last night's logs; it did an  Auto upgraded to: 2.6.7 then skipped updates showing me the next renewal time is in May.

Looks good!
