### ISSUE TITLE
生成证书的时候，怎么添加上owner信息？

### ISSUE THREAD

**Issue by maicss** [Neilpang/acme.sh#722]
网站现在已经在跑了。在Chrome下和Safari下好好的，但是Firefox下就报不安全。

![image](https://cloud.githubusercontent.com/assets/9784767/23897425/13640d7e-08e8-11e7-9c6c-13ba0775d2d0.png)

是因为没有owner信息的原因吗？

**Comment by Neilpang** [comment]
不知道这个 owner 信息是什么意思,  普通的DV 证书 值证明域名, 并不能证明所有者.  除非是 EV 或者 OV

**Comment by Neilpang** [comment]
我在windows 上的 firefox 打开没问题.

**Comment by maicss** [comment]
我后来又试，居然又好了，简直醉，也不知道这么调试。算了。谢谢你啦，谢谢你的回答和你的代码～～
