### ISSUE TITLE
Wget support is broken

### ISSUE THREAD

**Issue by nextgens** [Neilpang/acme.sh#724]
_get() is hopelessly broken if curl isn't available: from the man page:

"Specification of an empty string as the header value will clear all previous user-defined headers."

https://github.com/Neilpang/acme.sh/blob/master/acme.sh#L1622

**Comment by Neilpang** [comment]
Did you see any problem ?

for wget,  the header is in reversed order:
```
wget .....    --header "$_H5" --header "$_H4" --header "$_H3" --header "$_H2" --header "$_H1" 
```

**Comment by nextgens** [comment]
Yes, aws_dns is currently broken; The get request to list the zones fails:
https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_aws.sh#L86

H3 is set, H2 is empty, H1 is set ... the request is fired with just H1 and the auth fails

**Comment by Neilpang** [comment]
fixed,  please try with the `dev` branch:
```
export BRANCH=dev
acme.sh --upgrade
```

**Comment by nextgens** [comment]
It's fixed it; thanks! You rock!
