### ISSUE TITLE
dd-wrt support

### ISSUE THREAD

**Issue by jtbr** [Neilpang/acme.sh#731]
I'm using acme.sh on a DD-WRT router, using a recent Kong build. [DD-WRT](http://dd-wrt.com/) is a minimal linux variant very similar to OpenWRT.

I have it working in at least some modes with a couple minor tweaks.

The most important one is that there is no default-provided set of trusted certificates, so SSL will not work by default with curl or wget. A set of certificates can be installed with by running `opkg install ca-certificates`. But since neither curl nor wget has a default certificate path, they need to be provided on the command line whenever they are used. I have created a path that allows specifying a CA path for acme to use. Note that this is different from a ca bundle path, which provides a single certificate file, not a full directory of trusted certificates (which is faster for a large set of certificates). Also, on DD-WRT's curl, `--cacert` does not appear to work in my testing. (DD-WRT also does not provide `readlink`, which also prevents the `--ca-bundle` acme option from working correctly).

The second one is that netstat is implemented by [busybox](https://www.busybox.net/about.html), and does not have the -p option (which on linux provides the process id for the program which is using each port). As is, netstat gets called and fails with a big help message:
```
netstat: unrecognized option: p
BusyBox v1.24.2 (2016-09-27 22:32:10 CEST) multi-call binary.

Usage: netstat [-ral] [-tuwx] [-en]

Display networking information

        -r      Routing table
        -a      All sockets
        -l      Listening sockets
                Else: connected sockets
        -t      TCP sockets
        -u      UDP sockets
        -w      Raw sockets
        -x      Unix sockets
                Else: all socket types
        -e      Other/more information
        -n      Don't resolve names
```
The only effect is that the checking for whether the port is already being used fails. I have worked around this by removing the -p option from netstat. This means the error message that would be rendered by acme can no longer specify the guilty process in case the port is being used, but the check succeeds.

I am submitting pull requests for these two points.

A few other notes for users:

- The `--tls` method (or the `--dns` method, if that will work for you) is ideal for dd-wrt, since the router configuration GUI (service httpd) uses port 80 by default. 
- As root's home directory is on a temporary filesystem, you will need to provide the `--home` parameter with a folder on a permanent file system (normally /jffs)
- Kong's recent DD-WRT builds come with [lighttpd](http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_SSL). Lighttpd wants the SSL certificate and certificate key to be together in the same file. To accomplish this, I use: 
```
./acme.sh --install-cert [your server parameters] --home [your acme home] \
  --certpath /my/path/to/host.crt \
  --keypath /my/path/to/host.key \
  --fullchainpath /my/path/to/fullchain.crt \
  --reloadcmd  "cat /my/path/to/host.crt /my/path/to/lighttpd_ssl/host.key > /my/path/to/lighttpd_ssl/hostkey.pem;  killall lighttpd;  lighttpd -f /jffs/etc/lighttpd.conf"
```
- You'll need to add the line `ssl.ca-file     = "/my/path/to/fullchain.crt"` in the relevant section in lighttpd.conf.

**Comment by jtbr** [comment]
TODO: if --ca-path parameter PR is accepted, need to update the WIKI options/parameters page

**Comment by Neilpang** [comment]
give me some time.

**Comment by Neilpang** [comment]
Please give the ` --ca-path` PR,  thanks.

**Comment by Neilpang** [comment]
Sorry, I just noticed your PR.

**Comment by Neilpang** [comment]
merged,  please try again.

**Comment by jtbr** [comment]
I can confirm that it works on my dd-wrt.  I'm updating the wiki with the new option. Thank you!
