### ISSUE TITLE
Feature request: namecheap DNS support

### ISSUE THREAD

**Issue by jtbr** [Neilpang/acme.sh#734]
Feature request for namecheap.com DNS support. I believe they are one of the larger domain registrars and handle DNS for many of those domains.

The API seems straightforward, basically these two api calls via URL:
[GetHosts](https://www.namecheap.com/support/api/methods/domains-dns/get-hosts.aspx) - get host record settings
[SetHosts](https://www.namecheap.com/support/api/methods/domains-dns/set-hosts.aspx) - set host record settings

But I think this may be a bit beyond my scripting abilities. (I also suspect there may already be another DNS  implementation which is similar and could be used as a baseline, but I haven't found it by browsing the source code)

**Comment by florid2** [comment]
My domains are hosted on namecheap too. But not eligible to use API access although I have spent over $50 in the last two years.
https://github.com/Neilpang/acme.sh/issues/527

**Comment by Neilpang** [comment]
Yes, the api is not free.

**Comment by jtbr** [comment]
Hmm. I hadn't realized that. That's annoying and seems unnecessary.

Still, if someone wants to implement it, there is a [sandbox which is freely available to anyone](https://www.namecheap.com/support/knowledgebase/article.aspx/9739/63/api--faq#c) for testing.

@florid2 According to their FAQ, you should be eligible...

**Comment by florid2** [comment]
@jtbr Yeah, after I submitted a ticket, they approved my request to enable API access. However, I do not see Namecheap API access is quite useful as it requires user to define whitelist IPs who can access API. The whitelist only accepts IP addresses, not the DDNS. 
Not sure from whom needs to access Namecheap API, Letsencrypt validation servers or the web server requesting SSL certificate? 
As I am applying certificate for my home nas, it is not easy to modify the Namecheap whitelist everytime.

**Comment by VWFeature** [comment]
If you use NameCheap, you can specify other DNS.  You can use CloudFlare, etc.
