### ISSUE TITLE
Verify error:DNS problem: SERVFAIL looking up A

### ISSUE THREAD

**Issue by Nethe** [Neilpang/acme.sh#736]
Hey there! 

just moved web files to new server and tried to generate new certs. 
When I am trying to get new certs, i am getting this error:
```
nethe@srv:~/.acme.sh$ ./acme.sh --issue -d cermakmost.cz -d www.cermakmost.cz -w /home/nethe/webroot/
[Tue Mar 21 10:39:53 CET 2017] Multi domain='DNS:www.cermakmost.cz'
[Tue Mar 21 10:39:53 CET 2017] Getting domain auth token for each domain
[Tue Mar 21 10:39:53 CET 2017] Getting webroot for domain='cermakmost.cz'
[Tue Mar 21 10:39:53 CET 2017] Getting new-authz for domain='cermakmost.cz'
[Tue Mar 21 10:39:55 CET 2017] The new-authz request is ok.
[Tue Mar 21 10:39:55 CET 2017] Getting webroot for domain='www.cermakmost.cz'
[Tue Mar 21 10:39:55 CET 2017] Getting new-authz for domain='www.cermakmost.cz'
[Tue Mar 21 10:39:57 CET 2017] The new-authz request is ok.
[Tue Mar 21 10:39:57 CET 2017] Verifying:cermakmost.cz
[Tue Mar 21 10:40:00 CET 2017] cermakmost.cz:Verify error:DNS problem: SERVFAIL looking up A for cermakmost.cz
[Tue Mar 21 10:40:00 CET 2017] Please add '--debug' or '--log' to check more details.
[Tue Mar 21 10:40:00 CET 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```
But A record is correct, when you try `dig cermakmost.cz A`
I am using Nginx, it is configured:

server {
    listen 80;

    # IPv6 Listening
    # Uncomment to allow nginx to listen on IPv6
    listen [::]:80;
    
    server_name cermakmost.cz www.cermakmost.cz;

    root /home/domains/cermakmost.cz;
    
    # Logs Settings
    access_log /var/log/nginx/cermakmost_access.log;
    error_log /var/log/nginx/cermakmost_error.log;

    # Index files
    index index.html index.htm index.php;
    client_max_body_size 10526M;

    try_files $uri $uri/ /index.php?$args;

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        fastcgi_param PATH_TRANSLATED $document_root/$fastcgi_path_info;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

     location /phpmyadmin {
           root /usr/share/;
           index index.php index.html index.htm;
           location ~ ^/phpmyadmin/(.+\.php)$ {
                   try_files $uri =404;
                   root /usr/share/;
                   fastcgi_pass 127.0.0.1:9000;
                   fastcgi_index index.php;
                   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                   include /etc/nginx/fastcgi_params;
           }
           location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
                   root /usr/share/;
           }

         location ~ /\.well-known\/acme-challenge {
        allow all;
        alias /home/nethe/webroot/;
        default_type "text/plain";
    }

Nginx still giving me this error:
`2 directory index of "/home/nethe/webroot/.well-known/acme-challenge/" is forbidden, client: 88.100.169.106, server: cermakmost.cz, request: "GET /.well-known/acme-challenge/ HTTP/1.1", host: "cermakmost.cz"
`

I tried to google something, but without any success. Does anyone of you had this issue and know how to fix it, please? 

Thanks

**Comment by Neilpang** [comment]
It seems that letsencrypt server was not able to resolve your domain.
Here are a lot of people have the same error:

https://www.google.com/search?q=letsencrypt+DNS+problem%3A+SERVFAIL+looking+up+A&pws=0&gl=us&gws_rd=cr

**Comment by Nethe** [comment]
Will try to wait a bit. 
Many thanks to you!
