### ISSUE TITLE
权限与目录问题

### ISSUE THREAD

**Issue by cryptogun** [Neilpang/acme.sh#750]
$ `pwd`
`/home/xxxxx/.acme.sh`
Nginx用，不用sudo则没有写入权限。
$ `./acme.sh  --installcert  -d  'xxxxx.com'         --fullchainpath /etc/ssl/certs/xxxxx.com.cer         --keypath       /etc/ssl/private/xxxxx.com.key         --reloadcmd  "service nginx force-reload" --debug 2`
```
[Tue Mar 28 23:55:26 CST 2017] Lets find script dir.
[Tue Mar 28 23:55:26 CST 2017] _SCRIPT_='./acme.sh'
[Tue Mar 28 23:55:26 CST 2017] _script='/home/xxxxx/.acme.sh/acme.sh'
[Tue Mar 28 23:55:26 CST 2017] _script_home='/home/xxxxx/.acme.sh'
[Tue Mar 28 23:55:26 CST 2017] Using config home:/home/xxxxx/.acme.sh
[Tue Mar 28 23:55:26 CST 2017] LE_WORKING_DIR='/home/xxxxx/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.6.7
[Tue Mar 28 23:55:26 CST 2017] Using config home:/home/xxxxx/.acme.sh
[Tue Mar 28 23:55:26 CST 2017] DOMAIN_PATH='/home/xxxxx/.acme.sh/xxxxx.com'
[Tue Mar 28 23:55:26 CST 2017] Installing key to:/etc/ssl/private/xxxxx.com.key
./acme.sh: line 4119: /etc/ssl/private/xxxxx.com.key: Permission denied
[Tue Mar 28 23:55:26 CST 2017] Installing full chain to:/etc/ssl/certs/xxxxx.com.cer
./acme.sh: line 4127: /etc/ssl/certs/xxxxx.com.cer: Permission denied
[Tue Mar 28 23:55:26 CST 2017] Run reload cmd: service nginx force-reload
./acme.sh: line 4137: service: command not found
[Tue Mar 28 23:55:26 CST 2017] Reload error for :
```
sudo了`Domain is not valid` `DOMAIN_PATH='/root/...`
$ `sudo ./acme.sh  --installcert  -d  'xxxxx.com'         --fullchainpath /etc/ssl/certs/xxxxx.com.cer         --keypath       /etc/ssl/private/xxxxx.com.key         --reloadcmd  "service nginx force-reload" --debug 2`
```
[Tue Mar 28 23:55:59 CST 2017] Lets find script dir.
[Tue Mar 28 23:55:59 CST 2017] _SCRIPT_='./acme.sh'
[Tue Mar 28 23:55:59 CST 2017] _script='/home/xxxxx/.acme.sh/acme.sh'
[Tue Mar 28 23:55:59 CST 2017] _script_home='/home/xxxxx/.acme.sh'
[Tue Mar 28 23:55:59 CST 2017] Using default home:/root/.acme.sh
[Tue Mar 28 23:55:59 CST 2017] Using config home:/root/.acme.sh
[Tue Mar 28 23:55:59 CST 2017] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.6.7
[Tue Mar 28 23:55:59 CST 2017] Using config home:/root/.acme.sh
[Tue Mar 28 23:55:59 CST 2017] DOMAIN_PATH='/root/.acme.sh/xxxxx.com'
[Tue Mar 28 23:55:59 CST 2017] Domain is not valid:'xxxxx.com'
```
'/home/xxxxx/.acme.sh/'下面才有我的域名文件夹。
还有，`fullchain.cer` 和`xxxxx.com.cer`用哪个？我看那个[博客](https://www.cyberciti.biz/faq/how-to-configure-nginx-with-free-lets-encrypt-ssl-certificate-on-debian-or-ubuntu-linux/)`--fullchainpath`却填的是后者。

**Comment by cryptogun** [comment]
发现/etc/crontab没有记录。看来不能偷懒，得去letsencrypt官网一步步来。
应该装了的呀。
$ `./acme.sh --install`
```
[Wed Mar 29 00:55:02 CST 2017] Installing to /home/xxxxx/.acme.sh
cp: ‘acme.sh’ and ‘/home/xxxxx/.acme.sh/acme.sh’ are the same file
[Wed Mar 29 00:55:02 CST 2017] Install failed, can not copy acme.sh
```

**Comment by Neilpang** [comment]
问题在于, 你安装在当前用户下, 用 sudo 是切换身份到 root, 就找不到了.  这可能是一个问题,  稍后会修掉.

另外安装失败是因为文件夹不对.

如果你一定要用 sudo, 目前的解决方案是 切换到root 再安装,然后使用. 例如:

```sh
sudo su -
curl https://get.acme.sh | sh
#或者
./acme.sh --install

exit

sudo su -

acme.sh --issue -d ......

```

这有中文帮助: https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E

还有很多教程:  https://github.com/Neilpang/acme.sh/wiki/Blogs-and-tutorials

**Comment by cryptogun** [comment]
好的谢啦。暂时用着diafygi / letsencrypt-nosudo 好像挺简单，就是没有自动化，要手动更新。
为嘛不用python，bash每次想写点什么都得google。即使是[[ ]] `` $() in != sed awk. 易用性、复用性太差。

**Comment by Neilpang** [comment]
准确的说, 不是 bash, 而是 sh,  可以跨所有 *nux 平台.
不用python 因为 Python太沉,  跨平台没有  sh 强.
