### ISSUE TITLE
在部分浏览器中提示证书有问题

### ISSUE THREAD

**Issue by desmondlee** [Neilpang/acme.sh#759]
在谷歌浏览器中访问自己的网站正常，但是用火狐浏览器、我的手机浏览器访问时，提示“您的连接不安全”或“网站证书有问题”（刚有升级acme，且重新生成了证书）。

以下是火狐的提示：

>****使用了无效的安全证书。 该证书因为其颁发者证书未知而不被信任。 该服务器可能未发送相应的中间证书。 可能需要导入一个额外的根证书。 错误代码: SEC_ERROR_UNKNOWN_ISSUER

**Comment by Neilpang** [comment]
请 谷歌搜索  检查证书链.

**Comment by luozhanxin** [comment]
we also has this questions.

**Comment by luozhanxin** [comment]
you should exec this shell in you domain direct.'cat ca.cer >> youdomain.cer',because some bowers need ca.cer.

**Comment by Neilpang** [comment]
@desmondlee 
请使用   fullchain.cer ,而不是 domain.cer

**Comment by Neilpang** [comment]
@luozhanxin

**Comment by luozhanxin** [comment]
thanks.

**Comment by desmondlee** [comment]
@Neilpang @luozhanxin 感谢两位！
