### ISSUE TITLE
请教下如果只是通过ip可以签发证书么？

### ISSUE THREAD

**Issue by ren2881971** [Neilpang/acme.sh#760]
英文太烂 还是中文说吧 。。希望见谅。
先感谢下 neilpang大大。 我现在用域名签发证书是没有问题的。
但是我想只用ip 地址签发证书，咱们现有的版本可以做到么？ 
期待回复。谢谢。

**Comment by Neilpang** [comment]
不可以.

现有的市面上绝大部分证书都是 针对域名的.

ip 证书已有, 但是很罕见,  一般人申请不到,  因为 ip 一般是共享的,  你无法证明所有权.

Letsencrypt CA 目前只签发 DV 证书.

**Comment by ren2881971** [comment]
好的 了解了  感谢回复！！！
