### ISSUE TITLE
renew a moved cert

### ISSUE THREAD

**Issue by xifi-kif** [Neilpang/acme.sh#762]
This is not really an issue, but a question, before it can become an issue =)

I had to move the certs issued with acme to a different server (with same ip, domain name, etc..).

Now my question is: how to properly set renew the issued certs in the new server?

(i have my old .acme.sh dir backup)

**Comment by Neilpang** [comment]
1. 首先, 在新机器上 安装 acme.sh 

```sh
curl  https://get.acme.sh | sh
```

2.  然后, 拷贝, 并覆盖 `~/.acme.sh/` 目录.


3.  搞定.  自动续期会自动搞定. 无须担心.

**Comment by xifi-kif** [comment]
Ok thank you, it works perfectly.
