### ISSUE TITLE
What actually happens on --install-cert to apache2?

### ISSUE THREAD

**Issue by loothi** [Neilpang/acme.sh#766]
I'm trying to figure out what the deploy to apache  `--install-cert ` actually does and what it creates? (I'm not a coder). 

I would rather just have my files, then add the location like below in my VirtualHost conf file.

```
SSLEngine on
SSLCertificateFile /path/to/your_domain_name.crt
SSLCertificateKeyFile /path/to/your_private.key
SSLCertificateChainFile /path/to/DigiCertCA.crt
```

[https://github.com/Neilpang/acme.sh/wiki/Deploy-ssl-certs-to-apache-server](https://github.com/Neilpang/acme.sh/wiki/Deploy-ssl-certs-to-apache-server) isn't written yet.
Any guidance?

**Comment by Neilpang** [comment]
@loothi 
The hook for deploy to apache server is not implemented yet, so, it's empty.

>> I would rather just have my files, then add the location like below in my VirtualHost conf file.

yes, that's what the `--install-cert` is doing now.

You can just specify the cert/key/fullchain file paths to the command `--install-cert`, it will copy the files to the specified location.

Here are a lot of guidance :  https://github.com/Neilpang/acme.sh/wiki/Blogs-and-tutorials
