### ISSUE TITLE
Issues at installation on Ubuntu 10.04 LTS

### ISSUE THREAD

**Issue by walker9** [Neilpang/acme.sh#772]
After i've seen here (https://webtoolsplus.com/setting-up-lets-encrypt-old-ubuntu/) that it's possible to install on old OS, i tried on Ubuntu 10.04 LTS with:

./acme.sh --issue -d domain.com -d www.domain.com \
--certpath /etc/ssl/certs/domain.crt \
--keypath /etc/ssl/certs/domain.key \
--fullchainpath /etc/ssl/certs/intermediate.pem \
--reloadcmd  "service apache2 restart" --debug

But an Error occured:

> openssl:openssl
OpenSSL 0.9.8o 01 Jun 2010
apache:
apache doesn't exists.
nc:

Apache2 is installed on server. Is it not possible with that?

**Comment by Neilpang** [comment]
can you please give full log ?

**Comment by walker9** [comment]
Hello there, sure it's in attachment. Hope no security releated informations on it..

[log.txt](https://github.com/Neilpang/acme.sh/files/896175/log.txt)

**Comment by FernandoMiguel** [comment]
offtopic
@walker9 you running a really old and EOL distro.
you should seriously consider upgrading to 14.04

**Comment by Neilpang** [comment]
please use `-w` to specify the webroot folder.
https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert

**Comment by walker9** [comment]
@Neilpang 
Very thanks it worked now. 

Is it normal that in adress line from browser no green lock is displayed?

Cause the security alert from browser is the same as with self signed certificates. 

Let's Encrypt Authority X3 certificate date of expiry is now 7/4/2017

**Comment by walker9** [comment]
@FernandoMiguel 
im really aware of this :)
