### ISSUE TITLE
firefox 证书提示不信任问题，使用的是fullchain.cer

### ISSUE THREAD

**Issue by bensonfx** [Neilpang/acme.sh#776]
Neilpang，感谢提供的好工具，上个issue说的有些简略，您关的有点快了，汗
nginx 配置： 
 40     ssl_certificate             /benson/.acme.sh/xx_ecc/xx.cer;
 39     ssl_certificate_key         /benson/.acme.sh/xx_ecc/xx.key;
 38     ssl_trusted_certificate     /benson/.acme.sh/xx_ecc/fullchain.cer;
根据这个网站对照：https://letsencrypt.org/certificates/
工具生成的证书链：网站公钥+Let’s Encrypt Authority X3 (IdenTrust cross-signed)
此时chrome没有问题，firefox不信任
在证书链中填加：Let’s Encrypt Authority X3 (Signed by ISRG Root X1)
测试OK

参考这个贴子，
搜letsencrypt.org/也发现有一个2015年的证书说明，
https://letsencrypt.org/certificates/这个是最新的。

**Comment by Neilpang** [comment]
我明白你的意思，  但被idtrust 签的中间证书才是正解。  而不是isrg 自己签的。   另外 中间证书并非硬编码的  而是通过acme协议获取的， 所以不会错的。  请检查你的客户端。  你是什么系统？

**Comment by bensonfx** [comment]
ubuntu 16.04 firefox

用手机验证了
小米  小米浏览器 和uc

不加第二个证书都不行
加入第二个证书
小米浏览器已信任 但uc还是不行

**Comment by Neilpang** [comment]
那是你系统的问题,  系统没有包含 idtrust 的根.

而firefox内置了 ISRG 的根, 所以你包含的两条证书里链 有一条在firefox 中生效,   但是 UC 就无能为力了.
