### ISSUE TITLE
urn:acme:error:malformed

### ISSUE THREAD

**Issue by missdeer** [Neilpang/acme.sh#780]
[Mon 10 Apr 13:06:40 CST 2017] Renew: 'test.yii.li'
[Mon 10 Apr 13:06:41 CST 2017] Single domain='test.yii.li'
[Mon 10 Apr 13:06:42 CST 2017] Getting domain auth token for each domain
[Mon 10 Apr 13:06:42 CST 2017] Verifying:test.yii.li
[Mon 10 Apr 13:06:55 CST 2017] test.yii.li:Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: response does not complete challenge","status": 400}
[Mon 10 Apr 13:06:55 CST 2017] Please check log file for more details: /home/pi/.acme.sh/acme.sh.log
[Mon 10 Apr 13:06:58 CST 2017] Error renew test.yii.li.

**Comment by Neilpang** [comment]
为什么不把log 也贴上来,   目前这些信息, 只是告诉我出错了,  我能做什么呢?

**Comment by missdeer** [comment]
[Mon 10 Apr 13:41:23 CST 2017] _is_idn_d='sh.yii.li'
[Mon 10 Apr 13:41:23 CST 2017] _idn_temp
[Mon 10 Apr 13:41:23 CST 2017] _is_idn_d='pi.yii.li'
[Mon 10 Apr 13:41:23 CST 2017] _idn_temp
[Mon 10 Apr 13:41:23 CST 2017] Lets find script dir.
[Mon 10 Apr 13:41:23 CST 2017] _SCRIPT_='/home/pi/.acme.sh/acme.sh'
[Mon 10 Apr 13:41:23 CST 2017] _script='/home/pi/.acme.sh/acme.sh'
[Mon 10 Apr 13:41:23 CST 2017] _script_home='/home/pi/.acme.sh'
[Mon 10 Apr 13:41:23 CST 2017] Using config home:/home/pi/.acme.sh
[Mon 10 Apr 13:41:23 CST 2017] LE_WORKING_DIR='/home/pi/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.6.8
[Mon 10 Apr 13:41:23 CST 2017] Using config home:/home/pi/.acme.sh
[Mon 10 Apr 13:41:24 CST 2017] DOMAIN_PATH='/home/pi/.acme.sh/sh.yii.li'
[Mon 10 Apr 13:41:24 CST 2017] Renew: 'sh.yii.li'
[Mon 10 Apr 13:41:24 CST 2017] Using config home:/home/pi/.acme.sh
[Mon 10 Apr 13:41:24 CST 2017] Using api: https://acme-v01.api.letsencrypt.org
[Mon 10 Apr 13:41:24 CST 2017] Le_NextRenewTime='1491463178'
[Mon 10 Apr 13:41:24 CST 2017] _on_before_issue
[Mon 10 Apr 13:41:24 CST 2017] 'dns' does not contain 'no'
[Mon 10 Apr 13:41:24 CST 2017] Le_LocalAddress
[Mon 10 Apr 13:41:24 CST 2017] Check for domain='sh.yii.li'
[Mon 10 Apr 13:41:24 CST 2017] _currentRoot='dns'
[Mon 10 Apr 13:41:24 CST 2017] Check for domain='pi.yii.li'
[Mon 10 Apr 13:41:24 CST 2017] _currentRoot='dns'
[Mon 10 Apr 13:41:25 CST 2017] 'dns' does not contain 'apache'
[Mon 10 Apr 13:41:25 CST 2017] _saved_account_key_hash='ztOgXRDcZysZLg95Vv8oOIlU2s5WCfqbRAXGtjSLUWQ='
[Mon 10 Apr 13:41:25 CST 2017] _saved_account_key_hash is not changed, skip register account.
[Mon 10 Apr 13:41:25 CST 2017] Read key length:
[Mon 10 Apr 13:41:25 CST 2017] _createcsr
[Mon 10 Apr 13:41:25 CST 2017] domain='sh.yii.li'
[Mon 10 Apr 13:41:25 CST 2017] domainlist='pi.yii.li'
[Mon 10 Apr 13:41:25 CST 2017] csrkey='/home/pi/.acme.sh/sh.yii.li/sh.yii.li.key'
[Mon 10 Apr 13:41:25 CST 2017] csr='/home/pi/.acme.sh/sh.yii.li/sh.yii.li.csr'
[Mon 10 Apr 13:41:25 CST 2017] csrconf='/home/pi/.acme.sh/sh.yii.li/sh.yii.li.csr.conf'
[Mon 10 Apr 13:41:25 CST 2017] _is_idn_d='pi.yii.li'
[Mon 10 Apr 13:41:25 CST 2017] _idn_temp
[Mon 10 Apr 13:41:25 CST 2017] domainlist='pi.yii.li'
[Mon 10 Apr 13:41:25 CST 2017] Multi domain='DNS:pi.yii.li'
[Mon 10 Apr 13:41:25 CST 2017] _is_idn_d='sh.yii.li'
[Mon 10 Apr 13:41:25 CST 2017] _idn_temp
[Mon 10 Apr 13:41:25 CST 2017] _csr_cn='sh.yii.li'
[Mon 10 Apr 13:41:25 CST 2017] Getting domain auth token for each domain
[Mon 10 Apr 13:41:25 CST 2017] ok, let's start to verify
[Mon 10 Apr 13:41:25 CST 2017] Verifying:sh.yii.li
[Mon 10 Apr 13:41:25 CST 2017] d='sh.yii.li'
[Mon 10 Apr 13:41:25 CST 2017] keyauthorization='Dkb1N-VfoETkWJW0sspvBs5efBKPRERuqQUKl3MnpMc.4a4nD5ID-O3M_7Dp9TLSO9g1b0R87L5y__orkAZpfh8'
[Mon 10 Apr 13:41:25 CST 2017] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/NGjfFiq9pplATvqdV-Yyb6rEmNnw61WD-6ZpgGhNSLQ/976430799'
[Mon 10 Apr 13:41:26 CST 2017] _currentRoot='dns'
[Mon 10 Apr 13:41:26 CST 2017] tigger domain validation.
[Mon 10 Apr 13:41:26 CST 2017] _t_url='https://acme-v01.api.letsencrypt.org/acme/challenge/NGjfFiq9pplATvqdV-Yyb6rEmNnw61WD-6ZpgGhNSLQ/976430799'
[Mon 10 Apr 13:41:26 CST 2017] _t_key_authz='Dkb1N-VfoETkWJW0sspvBs5efBKPRERuqQUKl3MnpMc.4a4nD5ID-O3M_7Dp9TLSO9g1b0R87L5y__orkAZpfh8'
[Mon 10 Apr 13:41:26 CST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/NGjfFiq9pplATvqdV-Yyb6rEmNnw61WD-6ZpgGhNSLQ/976430799'
[Mon 10 Apr 13:41:26 CST 2017] payload='{"resource": "challenge", "keyAuthorization": "Dkb1N-VfoETkWJW0sspvBs5efBKPRERuqQUKl3MnpMc.4a4nD5ID-O3M_7Dp9TLSO9g1b0R87L5y__orkAZpfh8"}'
[Mon 10 Apr 13:41:26 CST 2017] RSA key
[Mon 10 Apr 13:41:34 CST 2017] Get nonce.
[Mon 10 Apr 13:41:34 CST 2017] GET
[Mon 10 Apr 13:41:34 CST 2017] url='https://acme-v01.api.letsencrypt.org/directory'
[Mon 10 Apr 13:41:34 CST 2017] timeout
[Mon 10 Apr 13:41:35 CST 2017] _CURL='curl -L --silent --dump-header /home/pi/.acme.sh/http.header  --trace-ascii /tmp/tmp.7qDU54s9S9 '
[Mon 10 Apr 13:41:36 CST 2017] ret='0'
[Mon 10 Apr 13:41:36 CST 2017] _headers='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 352
Boulder-Request-Id: Kh-QE08TrVQLpAlH1apbhXOxfVfw1GPg8Bk-POUGMd0
Replay-Nonce: OvAsO3XRERFBV9-jt3yHuwnUHWBR9U-P8H5boMV8gOM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 10 Apr 2017 05:41:36 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 10 Apr 2017 05:41:36 GMT
Connection: keep-alive

'
[Mon 10 Apr 13:41:36 CST 2017] _CACHED_NONCE='OvAsO3XRERFBV9-jt3yHuwnUHWBR9U-P8H5boMV8gOM'
[Mon 10 Apr 13:41:36 CST 2017] nonce='OvAsO3XRERFBV9-jt3yHuwnUHWBR9U-P8H5boMV8gOM'
[Mon 10 Apr 13:41:36 CST 2017] POST
[Mon 10 Apr 13:41:36 CST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/NGjfFiq9pplATvqdV-Yyb6rEmNnw61WD-6ZpgGhNSLQ/976430799'
[Mon 10 Apr 13:41:36 CST 2017] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "oRz8DZ_zcdnL7JdOvPB1bny_y_MCI7uNqJ05D0WNUZKGwXU6SX7Eo3kEhHArEkaAFrjepMbPSDZ-R1TA-OyWj0OjIM9nTwfOsveLUCmpJZngMm4oQ5GnDZe-igrxDD_0kFHgO_UPGv5iyW2FcFHEyARKrUATRJI2BKDaeYq9-lgDmvuKgNnOMm_uKWznK2oabsiyqirXDN1ZsJAL2j5MexsGH7y-hFvc19tE1CsET2uzGxYkdUlQhEN-Nn9WkmcO1bKqa_lOrtTs4VGRRURXZB3HOI4AX6NdO8KlcJPPBI2VLlRkvnaNR0MJJUGyHwaa1OAxmMj5qBQ1jdekHjCMOQ"}}, "protected": "eyJub25jZSI6ICJPdkFzTzNYUkVSRkJWOS1qdDN5SHV3blVIV0JSOVUtUDhINWJvTVY4Z09NIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAib1J6OERaX3pjZG5MN0pkT3ZQQjFibnlfeV9NQ0k3dU5xSjA1RDBXTlVaS0d3WFU2U1g3RW8za0VoSEFyRWthQUZyamVwTWJQU0RaLVIxVEEtT3lXajBPaklNOW5Ud2ZPc3ZlTFVDbXBKWm5nTW00b1E1R25EWmUtaWdyeEREXzBrRkhnT19VUEd2NWl5VzJGY0ZIRXlBUktyVUFUUkpJMkJLRGFlWXE5LWxnRG12dUtnTm5PTW1fdUtXem5LMm9hYnNpeXFpclhETjFac0pBTDJqNU1leHNHSDd5LWhGdmMxOXRFMUNzRVQydXpHeFlrZFVsUWhFTi1ObjlXa21jTzFiS3FhX2xPcnRUczRWR1JSVVJYWkIzSE9JNEFYNk5kTzhLbGNKUFBCSTJWTGxSa3ZuYU5SME1KSlVHeUh3YWExT0F4bU1qNXFCUTFqZGVrSGpDTU9RIn19", "payload": "eyJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLCAia2V5QXV0aG9yaXphdGlvbiI6ICJEa2IxTi1WZm9FVGtXSlcwc3NwdkJzNWVmQktQUkVSdXFRVUtsM01ucE1jLjRhNG5ENUlELU8zTV83RHA5VExTTzlnMWIwUjg3TDV5X19vcmtBWnBmaDgifQ", "signature": "LlsNMvqRv_9TrAdck7YMkxjGLpEcV9_miqOvZclrhiojala2_R8fDoz2C-iEVGuYGmd9w_RqNXm11hqRIrHhFokalhrjMeOnlQTZZBJL5t7VQCoZgR7X1Ra5vMNOiwp3PqjBRmVDmk8nJSoTDKyl34mLV62Cooh96YBeDpVHdggVejLxC_KQZL0pBNccbQ6cArYGAZesG9wVGvgqXIVWYONw4snLGpABNtF14XbYJZbmzXxCLUL9Pxi5iCrrF8GC9nUBGSFhfFP_hvl-h2vxi9rN03VzEMnqB20rd90GLdrncGRCNlxlATeu7OAGpC_RLp-uoSWR6QiXGKwDerueeA"}'
[Mon 10 Apr 13:41:36 CST 2017] _CURL='curl -L --silent --dump-header /home/pi/.acme.sh/http.header  --trace-ascii /tmp/tmp.zRxuNKu3Tn '
[Mon 10 Apr 13:41:38 CST 2017] _ret='0'
[Mon 10 Apr 13:41:38 CST 2017] original='{
  "type": "urn:acme:error:malformed",
  "detail": "Unable to update challenge :: response does not complete challenge",
  "status": 400
}'
[Mon 10 Apr 13:41:38 CST 2017] responseHeaders='HTTP/1.1 100 Continue
Expires: Mon, 10 Apr 2017 05:41:37 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/problem+json
Content-Length: 139
Boulder-Request-Id: H6HMwI5n276s8vOgfIKa8Vqbr62u7ZgvJP2PMuSPR5c
Boulder-Requester: 6707914
Replay-Nonce: tQD_199FDds3eihKW3PVUDCgi0hMqKnrhXSv9npIAgg
Expires: Mon, 10 Apr 2017 05:41:38 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 10 Apr 2017 05:41:38 GMT
Connection: close

'
[Mon 10 Apr 13:41:38 CST 2017] response='{"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: response does not complete challenge","status": 400}'
[Mon 10 Apr 13:41:38 CST 2017] code='400'
[Mon 10 Apr 13:41:38 CST 2017] sh.yii.li:Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: response does not complete challenge","status": 400}
[Mon 10 Apr 13:41:38 CST 2017] Skip for removelevel:
[Mon 10 Apr 13:41:38 CST 2017] pid
[Mon 10 Apr 13:41:38 CST 2017] No need to restore nginx, skip.
[Mon 10 Apr 13:41:38 CST 2017] _clearupdns
[Mon 10 Apr 13:41:38 CST 2017] Dns not added, skip.
[Mon 10 Apr 13:41:38 CST 2017] _on_issue_err
[Mon 10 Apr 13:41:38 CST 2017] Please check log file for more details: /home/pi/.acme.sh/acme.sh.log
[Mon 10 Apr 13:41:38 CST 2017] _chk_vlist='sh.yii.li#Dkb1N-VfoETkWJW0sspvBs5efBKPRERuqQUKl3MnpMc.4a4nD5ID-O3M_7Dp9TLSO9g1b0R87L5y__orkAZpfh8#https://acme-v01.api.letsencrypt.org/acme/challenge/NGjfFiq9pplATvqdV-Yyb6rEmNnw61WD-6ZpgGhNSLQ/976430799#dns-01#dns,pi.yii.li#JBBfxE6AORLDiFGLQFqkxzvZx-_4caTRMTKmt3qm52A.4a4nD5ID-O3M_7Dp9TLSO9g1b0R87L5y__orkAZpfh8#https://acme-v01.api.letsencrypt.org/acme/challenge/1KidMr1kbvTrlIoiFgUsMBrve5bxwE_1JSIgvA0jvOo/976432004#dns-01#dns,'
[Mon 10 Apr 13:41:38 CST 2017] start to deactivate authz
[Mon 10 Apr 13:41:38 CST 2017] tigger domain validation.
[Mon 10 Apr 13:41:38 CST 2017] _t_url='https://acme-v01.api.letsencrypt.org/acme/challenge/NGjfFiq9pplATvqdV-Yyb6rEmNnw61WD-6ZpgGhNSLQ/976430799'
[Mon 10 Apr 13:41:38 CST 2017] _t_key_authz='Dkb1N-VfoETkWJW0sspvBs5efBKPRERuqQUKl3MnpMc.4a4nD5ID-O3M_7Dp9TLSO9g1b0R87L5y__orkAZpfh8'
[Mon 10 Apr 13:41:38 CST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/NGjfFiq9pplATvqdV-Yyb6rEmNnw61WD-6ZpgGhNSLQ/976430799'
[Mon 10 Apr 13:41:39 CST 2017] payload='{"resource": "challenge", "keyAuthorization": "Dkb1N-VfoETkWJW0sspvBs5efBKPRERuqQUKl3MnpMc.4a4nD5ID-O3M_7Dp9TLSO9g1b0R87L5y__orkAZpfh8"}'
[Mon 10 Apr 13:41:39 CST 2017] Use cached jwk for file: /home/pi/.acme.sh/ca/acme-v01.api.letsencrypt.org/account.key
[Mon 10 Apr 13:41:39 CST 2017] Use _CACHED_NONCE='tQD_199FDds3eihKW3PVUDCgi0hMqKnrhXSv9npIAgg'
[Mon 10 Apr 13:41:39 CST 2017] nonce='tQD_199FDds3eihKW3PVUDCgi0hMqKnrhXSv9npIAgg'
[Mon 10 Apr 13:41:39 CST 2017] POST
[Mon 10 Apr 13:41:39 CST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/NGjfFiq9pplATvqdV-Yyb6rEmNnw61WD-6ZpgGhNSLQ/976430799'
[Mon 10 Apr 13:41:39 CST 2017] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "oRz8DZ_zcdnL7JdOvPB1bny_y_MCI7uNqJ05D0WNUZKGwXU6SX7Eo3kEhHArEkaAFrjepMbPSDZ-R1TA-OyWj0OjIM9nTwfOsveLUCmpJZngMm4oQ5GnDZe-igrxDD_0kFHgO_UPGv5iyW2FcFHEyARKrUATRJI2BKDaeYq9-lgDmvuKgNnOMm_uKWznK2oabsiyqirXDN1ZsJAL2j5MexsGH7y-hFvc19tE1CsET2uzGxYkdUlQhEN-Nn9WkmcO1bKqa_lOrtTs4VGRRURXZB3HOI4AX6NdO8KlcJPPBI2VLlRkvnaNR0MJJUGyHwaa1OAxmMj5qBQ1jdekHjCMOQ"}}, "protected": "eyJub25jZSI6ICJ0UURfMTk5RkRkczNlaWhLVzNQVlVEQ2dpMGhNcUtucmhYU3Y5bnBJQWdnIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAib1J6OERaX3pjZG5MN0pkT3ZQQjFibnlfeV9NQ0k3dU5xSjA1RDBXTlVaS0d3WFU2U1g3RW8za0VoSEFyRWthQUZyamVwTWJQU0RaLVIxVEEtT3lXajBPaklNOW5Ud2ZPc3ZlTFVDbXBKWm5nTW00b1E1R25EWmUtaWdyeEREXzBrRkhnT19VUEd2NWl5VzJGY0ZIRXlBUktyVUFUUkpJMkJLRGFlWXE5LWxnRG12dUtnTm5PTW1fdUtXem5LMm9hYnNpeXFpclhETjFac0pBTDJqNU1leHNHSDd5LWhGdmMxOXRFMUNzRVQydXpHeFlrZFVsUWhFTi1ObjlXa21jTzFiS3FhX2xPcnRUczRWR1JSVVJYWkIzSE9JNEFYNk5kTzhLbGNKUFBCSTJWTGxSa3ZuYU5SME1KSlVHeUh3YWExT0F4bU1qNXFCUTFqZGVrSGpDTU9RIn19", "payload": "eyJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLCAia2V5QXV0aG9yaXphdGlvbiI6ICJEa2IxTi1WZm9FVGtXSlcwc3NwdkJzNWVmQktQUkVSdXFRVUtsM01ucE1jLjRhNG5ENUlELU8zTV83RHA5VExTTzlnMWIwUjg3TDV5X19vcmtBWnBmaDgifQ", "signature": "k-QbEM7-qhlvFlICxKr7ewTKuTX8u2bOHH4TOXa78MofDOKAk8Gn2vSxIEBwGcgZs2mGJ0KsCn1gqMLyimvxXRp7LN_BfHFeyjPvlsycI4AKf9h-5oDWY1-mlt3TJoOMz-MquM50tiQSSDWzNcBsrfkTWADRN9dEKUiezZwVLsMkNNxwELVc6-cns-JxJs55kXFzVaUAXKquzxfCRqVdxEv6GXMXX5LqAVuYsBigxws2Pp-1qe4zVxiU9CftFcbr7ixHwZcrK1tUNGffHkmoofXk7Hx7-Yc_M6Le3C4lbB_mkAwX-ydvEKwq7IwyBy3FbleOt92_DMLJtTc-nNZHYg"}'
[Mon 10 Apr 13:41:39 CST 2017] _CURL='curl -L --silent --dump-header /home/pi/.acme.sh/http.header  --trace-ascii /tmp/tmp.xGsm5189Km '
[Mon 10 Apr 13:41:41 CST 2017] _ret='0'
[Mon 10 Apr 13:41:41 CST 2017] original='{
  "type": "urn:acme:error:malformed",
  "detail": "Unable to update challenge :: response does not complete challenge",
  "status": 400
}'
[Mon 10 Apr 13:41:41 CST 2017] responseHeaders='HTTP/1.1 100 Continue
Expires: Mon, 10 Apr 2017 05:41:40 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/problem+json
Content-Length: 139
Boulder-Request-Id: VTeAZa9HZM-0QOKtnLl26OvsRFKBzo5tWVjhxM3MP1k
Boulder-Requester: 6707914
Replay-Nonce: YWV8ZIhTRLAnO8gCZ_lgXgIo-dmv9JpBk3TcrwIhTWU
Expires: Mon, 10 Apr 2017 05:41:41 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 10 Apr 2017 05:41:41 GMT
Connection: close

'
[Mon 10 Apr 13:41:41 CST 2017] response='{"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: response does not complete challenge","status": 400}'
[Mon 10 Apr 13:41:41 CST 2017] code='400'
[Mon 10 Apr 13:41:41 CST 2017] tigger domain validation.
[Mon 10 Apr 13:41:41 CST 2017] _t_url='https://acme-v01.api.letsencrypt.org/acme/challenge/1KidMr1kbvTrlIoiFgUsMBrve5bxwE_1JSIgvA0jvOo/976432004'
[Mon 10 Apr 13:41:41 CST 2017] _t_key_authz='JBBfxE6AORLDiFGLQFqkxzvZx-_4caTRMTKmt3qm52A.4a4nD5ID-O3M_7Dp9TLSO9g1b0R87L5y__orkAZpfh8'
[Mon 10 Apr 13:41:41 CST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/1KidMr1kbvTrlIoiFgUsMBrve5bxwE_1JSIgvA0jvOo/976432004'
[Mon 10 Apr 13:41:41 CST 2017] payload='{"resource": "challenge", "keyAuthorization": "JBBfxE6AORLDiFGLQFqkxzvZx-_4caTRMTKmt3qm52A.4a4nD5ID-O3M_7Dp9TLSO9g1b0R87L5y__orkAZpfh8"}'
[Mon 10 Apr 13:41:41 CST 2017] Use cached jwk for file: /home/pi/.acme.sh/ca/acme-v01.api.letsencrypt.org/account.key
[Mon 10 Apr 13:41:41 CST 2017] Use _CACHED_NONCE='YWV8ZIhTRLAnO8gCZ_lgXgIo-dmv9JpBk3TcrwIhTWU'
[Mon 10 Apr 13:41:41 CST 2017] nonce='YWV8ZIhTRLAnO8gCZ_lgXgIo-dmv9JpBk3TcrwIhTWU'
[Mon 10 Apr 13:41:41 CST 2017] POST
[Mon 10 Apr 13:41:41 CST 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/1KidMr1kbvTrlIoiFgUsMBrve5bxwE_1JSIgvA0jvOo/976432004'
[Mon 10 Apr 13:41:41 CST 2017] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "oRz8DZ_zcdnL7JdOvPB1bny_y_MCI7uNqJ05D0WNUZKGwXU6SX7Eo3kEhHArEkaAFrjepMbPSDZ-R1TA-OyWj0OjIM9nTwfOsveLUCmpJZngMm4oQ5GnDZe-igrxDD_0kFHgO_UPGv5iyW2FcFHEyARKrUATRJI2BKDaeYq9-lgDmvuKgNnOMm_uKWznK2oabsiyqirXDN1ZsJAL2j5MexsGH7y-hFvc19tE1CsET2uzGxYkdUlQhEN-Nn9WkmcO1bKqa_lOrtTs4VGRRURXZB3HOI4AX6NdO8KlcJPPBI2VLlRkvnaNR0MJJUGyHwaa1OAxmMj5qBQ1jdekHjCMOQ"}}, "protected": "eyJub25jZSI6ICJZV1Y4WkloVFJMQW5POGdDWl9sZ1hnSW8tZG12OUpwQmszVGNyd0loVFdVIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAib1J6OERaX3pjZG5MN0pkT3ZQQjFibnlfeV9NQ0k3dU5xSjA1RDBXTlVaS0d3WFU2U1g3RW8za0VoSEFyRWthQUZyamVwTWJQU0RaLVIxVEEtT3lXajBPaklNOW5Ud2ZPc3ZlTFVDbXBKWm5nTW00b1E1R25EWmUtaWdyeEREXzBrRkhnT19VUEd2NWl5VzJGY0ZIRXlBUktyVUFUUkpJMkJLRGFlWXE5LWxnRG12dUtnTm5PTW1fdUtXem5LMm9hYnNpeXFpclhETjFac0pBTDJqNU1leHNHSDd5LWhGdmMxOXRFMUNzRVQydXpHeFlrZFVsUWhFTi1ObjlXa21jTzFiS3FhX2xPcnRUczRWR1JSVVJYWkIzSE9JNEFYNk5kTzhLbGNKUFBCSTJWTGxSa3ZuYU5SME1KSlVHeUh3YWExT0F4bU1qNXFCUTFqZGVrSGpDTU9RIn19", "payload": "eyJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLCAia2V5QXV0aG9yaXphdGlvbiI6ICJKQkJmeEU2QU9STERpRkdMUUZxa3h6dlp4LV80Y2FUUk1US210M3FtNTJBLjRhNG5ENUlELU8zTV83RHA5VExTTzlnMWIwUjg3TDV5X19vcmtBWnBmaDgifQ", "signature": "QvtflIEG6ZEVJEcFTegh_HeultZISO2vz0xAaGnouyw9IZmaD3AospksWNaEB3BLyqLQ2eGeH81YZlitlffGYUD1oO93LHuuQLlDHzl2Iaun_4LLaquROh8j6SJ4ZbAmf-XweeQDhbTRllO7gYovvpI-WL1sfDtf0gJI9FFTMhbpegCQTOyRF5SuBZNxdaOS4UwzfS41abjOTtKESqn2qaMqwKcWz7-8p_5JLjN-P2ZRV3ScEg4RKwy5xCjlAkNovbSqVPMENLWO0kJu8gkJrI7SbC6YTAA1-w9xExw_MqrlENg9Scekx_LfxsQpcIkSepEfHXIZuTrL9uEypUXteA"}'
[Mon 10 Apr 13:41:42 CST 2017] _CURL='curl -L --silent --dump-header /home/pi/.acme.sh/http.header  --trace-ascii /tmp/tmp.WU9OazFur9 '
[Mon 10 Apr 13:41:43 CST 2017] _ret='0'
[Mon 10 Apr 13:41:43 CST 2017] original='{
  "type": "urn:acme:error:malformed",
  "detail": "Unable to update challenge :: response does not complete challenge",
  "status": 400
}'
[Mon 10 Apr 13:41:43 CST 2017] responseHeaders='HTTP/1.1 100 Continue
Expires: Mon, 10 Apr 2017 05:41:43 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/problem+json
Content-Length: 139
Boulder-Request-Id: atA2IbUafsKESRGqBf7qYiB8A_sImaEdchkZksyGS9M
Boulder-Requester: 6707914
Replay-Nonce: 3nPvf4dEVDgmip0UJq3s-B0mObAaaJoQn9aMnd7QnVQ
Expires: Mon, 10 Apr 2017 05:41:43 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 10 Apr 2017 05:41:43 GMT
Connection: close

'
[Mon 10 Apr 13:41:43 CST 2017] response='{"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: response does not complete challenge","status": 400}'
[Mon 10 Apr 13:41:43 CST 2017] code='400'
[Mon 10 Apr 13:41:44 CST 2017] Diagnosis versions: 
openssl:openssl
OpenSSL 1.0.1t  3 May 2016
apache:
apache doesn't exists.
nc:
OpenBSD netcat (Debian patchlevel 1.105-7)
usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
	  [-P proxy_username] [-p source_port] [-q seconds] [-s source]
	  [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
	  [-x proxy_address[:port]] [destination] [port]
	Command Summary:
		-4		Use IPv4
		-6		Use IPv6
		-b		Allow broadcast
		-C		Send CRLF as line-ending
		-D		Enable the debug socket option
		-d		Detach from stdin
		-h		This help text
		-I length	TCP receive buffer length
		-i secs		Delay interval for lines sent, ports scanned
		-j		Use jumbo frame
		-k		Keep inbound sockets open for multiple connects
		-l		Listen mode, for inbound connects
		-n		Suppress name/port resolutions
		-O length	TCP send buffer length
		-P proxyuser	Username for proxy authentication
		-p port		Specify local port for remote connects
        	-q secs		quit after EOF on stdin and delay of secs
		-r		Randomize remote ports
		-S		Enable the TCP MD5 signature option
		-s addr		Local source address
		-T toskeyword	Set IP Type of Service
		-t		Answer TELNET negotiation
		-U		Use UNIX domain socket
		-u		UDP mode
		-V rtable	Specify alternate routing table
		-v		Verbose
		-w secs		Timeout for connects and final net reads
		-X proto	Proxy protocol: "4", "5" (SOCKS) or "connect"
		-x addr[:port]	Specify proxy address and port
		-Z		DCCP mode
		-z		Zero-I/O mode [used for scanning]
	Port numbers can be individual or ranges: lo-hi [inclusive]

**Comment by missdeer** [comment]
https://sh.yii.li/apk/err.txt

**Comment by Neilpang** [comment]
你用的 dns 手动模式, 无法自动renew.

请使用 cloudflare api 自动模式 重新 issue 一次.

**Comment by missdeer** [comment]
Resolved. 
Thanks in advance.
