### ISSUE TITLE
debug log without senstive data

### ISSUE THREAD

**Issue by FernandoMiguel** [Neilpang/acme.sh#783]
would it be possible for a debug option to output all the required details for an issue reporting without leaking sensitive data like api keys or email addresses?

**Comment by Neilpang** [comment]
what do you want to hide?
we already have functions: `_secure_debug()`, `_secure_debug2()`.
You can search where those functions are used.

**Comment by FernandoMiguel** [comment]
@Neilpang api keys, email addresses, some of the results of LE API like the TXT records, etc
anything that would show in --debug 2 that would allow for someone to gain access to an infrastructure.

thanks

**Comment by Neilpang** [comment]
I understand, but we should replace `_debug()` function with `_secure_debug()` for the key infos

**Comment by Neilpang** [comment]
Please upgrade to the latest 2.8.8  version,  your cf api key and secret should already be hidden.

**Comment by FernandoMiguel** [comment]
I think you mean v2.6.8.
but yeah, that's a good improvement there.

are any of the output entries from LE sensitive too?

**Comment by Neilpang** [comment]
Yes, it's 2.6.8

I'm not 100% sure, but I don't think the entries is sensitive.

I have hidden some sensitive already, but if you find anything else need to be hidden, please tell me.

**Comment by FernandoMiguel** [comment]
afaik, it's all looking OK.
i still dont like those tokens visible, nor are they useful for any debug, but not sure how sensitive they are.


thanks
