### ISSUE TITLE
Reloading not working after successfull certificate renew

### ISSUE THREAD

**Issue by Firm** [Neilpang/acme.sh#787]
Hi,

Script version is 2.6.9. Crontab line:
0 0 * * *	/root/.acme.sh/acme.sh --cron --home "/root/.acme.sh" --reloadcmd "/usr/sbin/nginx -s reload" > /dev/null

Looks as reloadcmd is ignored. Checked with --force --debug 2 options. Certificate is renewed but nginx is not reloaded.

**Comment by Neilpang** [comment]
`--reloadcmd` is **NOT** for `--cron` command.

Read: https://github.com/Neilpang/acme.sh#3-install-the-issued-cert-to-apachenginx-etc

**Comment by dorelljames** [comment]
@Neilpang so how do we set up cron with the capability to reload server after all certs have been renewed?

**Comment by Neilpang** [comment]
@dorelljames 
The "reloadcmd" is  **NOT**  for "cron"  to reload services after **ALL**  the certs are renewed.
Since each cert may need to reload a different service after it's renewed.
So,  "reloadcmd" is only valid for "issue" or "renew" command.  When your issue the cert, you specify how to reload the service for this cert.

Read the doc, and the wiki,  you  will know how to use such options.

**Comment by dorelljames** [comment]
@Neilpang thanks for the prompt response. I think I figured it out but just one last question. I kind of left out the `reloadcmd` option when I initially issued certs for X sites. Do you suggest that I just update the config file for those sites and place the correct server reload command for each site? Or if there's a much easier way, I'd like to know please.

**Comment by Neilpang** [comment]
@dorelljames 
Never edit the config files by your hand.
As I said it's also valid for renew command.

```sh
acme.sh --renew  -d example.com   --reloacmd "my new reload cmd"
```
The renewal of the cert will be skipped,  but the new reload cmd will be updated(remembered)

**Comment by Neilpang** [comment]
@dorelljames 
Sorry, this is a mistake.

it not valid for renew,  but valid for "installcert" command.

```sh
acme.sh --installcert   -d example.com   --reloacmd "my new reload cmd"
```
the new reload cmd will be updated(remembered)

**Comment by dorelljames** [comment]
Thanks @Neilpang. I'll work on updating those.

**Comment by dorelljames** [comment]
Thanks once again @Neilpang. All good now.

I created a bash script to update all the sites I had certs. If anyone would find it useful, see below:

Script meant to be created/executed inside in `.acme.sh/`

```bash
#!/bin/bash

for d in */; do
    if [ "$d" != "ca/" ] && [ "$d" != "deploy/" ] && [ "$d" != "dnsapi/" ]; then # skip acme.sh directories
        domain=$(echo $d | rev | cut -c 2- | rev)
        reloadcmd="service nginx reload" # change per your needs
        /root/.acme.sh/acme.sh --installcert -d "$domain" --reloadcmd "$reloadcmd"
    fi
done
```

**Comment by yanhuixie** [comment]
> @dorelljames Sorry, this is a mistake.
> 
> it not valid for renew, but valid for "installcert" command.
> 
> ```shell
> acme.sh --installcert   -d example.com   --reloacmd "my new reload cmd"
> ```
> 
> the new reload cmd will be updated(remembered)

多谢大佬解惑，这么重要的内容，建议最好能体现在文档里。

**Comment by Neilpang** [comment]
文档里面从来都是用的 installcert

https://github.com/acmesh-official/acme.sh/wiki/%E8%AF%B4%E6%98%8E

**Comment by BrightVan** [comment]
> 文档里面从来都是用的 installcert
> 
> https://github.com/acmesh-official/acme.sh/wiki/%E8%AF%B4%E6%98%8E
上面有提到acme会记住reloacmd，那么如何查看这个记住的内容在哪呢？（突然reloacmd没起作用，忘记之前怎么写的了），以及怎么快速测试呢，而不是等三个月后出问题再排查

**Comment by Neilpang** [comment]
```
acme.sh  --info  -d  example.com

```

**Comment by BrightVan** [comment]
> ```
> acme.sh  --info  -d  example.com
> ```

thanks，建议把这个加在中文文档部分，昨天也发现了，持久化内容在~/.acme.sh/example.com/example.conf文件里

**Comment by Neilpang** [comment]
不要建议, 要的话自己来改.  文档对公众是开放编辑的.

**Comment by BrightVan** [comment]
> 

Ok，已经添加了。不知是否有编辑reloadCmd的命令，可能也有点必要，重新安装的话，有点没必要。

**Comment by Neilpang** [comment]
good. thanks.

不建议手动编辑conf 文件.   但是如果你非要编辑conf 文件,  也不需要 base64 编码, 直接写原文.  acme.sh 会自动识别.

这些也可以补充道文档里面.

**Comment by Neilpang** [comment]
因为 conf 文件的位置和内容格式以后可能会改变.  conf 一直都是内部使用, 从不建议用户直接更改.
例如, 后面有可能会改为用 sqlite 或者mysql 格式存储.  所以一般不建议自己修改.

**Comment by BrightVan** [comment]
> 因为 conf 文件的位置和内容格式以后可能会改变. conf 一直都是内部使用, 从不建议用户直接更改. 例如, 后面有可能会改为用 sqlite 或者mysql 格式存储. 所以一般不建议自己修改.

我添加了这部分说明，不过这也不会造成不兼容啊，如果以后改成其他的格式，肯定要从现有的文件中迁移啊
