### ISSUE TITLE
Running two acme.sh scripts concurrently

### ISSUE THREAD

**Issue by anotherjames** [Neilpang/acme.sh#788]
I understand this may not be something you wish to help/support, but:

If two/multiple acme.sh scripts are run at the same time, could there be race conditions, or should that theoretically be ok?

We have a set up that is doing this (long story), and are experiencing some odd issues around invalid responses, a bit like #684. We noticed that there's a temporary file that's created containing a timestamp, so we'd guess that if it ran for the same site within the same second, problems could occur.

Thanks for any help/advice :-)

**Comment by Neilpang** [comment]
It may cause problems.
But you can specify  different `--home`s or `--config-home`s to run concurrently.
For example:

for instance A:

```sh
acme.sh --home /home/user/acme.sh_A/   --issue .......
```

for instance B:
```sh
acme.sh --home /home/user/acme.sh_B/   --issue .......
```


Or, you can specify different config-home.

for instance A:

```sh
acme.sh --config-home  /home/user/acme.sh_A/   --issue .......
```

for instance B:
```sh
acme.sh --config-home  /home/user/acme.sh_B/   --issue .......
```

**Comment by anotherjames** [comment]
Thank you!
