### ISSUE TITLE
Removing Cloudflares DNS Record fails

### ISSUE THREAD

**Issue by stephan13360** [Neilpang/acme.sh#794]
I recently switched to Cloudflare and tried to issue a certificate with the Cloudflare DNS Mode. Adding the TXT Record and issuing the certificate works fine, but removing the TXT records throws an error.

I installed a fresh Version of acme.sh and ran the following command:

/root/.acme.sh/acme.sh --issue --dns dns_cf --ecc --keylength ec-2048 --ocsp-must-staple -d aaa.sherbers.de --debug 2

Relevent part from debug log:

[Sat Apr 15 21:20:07 CEST 2017] _clearupdns
[Sat Apr 15 21:20:07 CEST 2017] txt='dkrnrXomYrui2phIMk-yVEeQAaZhhwK7OOs13qBMuHg'
[Sat Apr 15 21:20:07 CEST 2017] d_api='/root/.acme.sh/dnsapi/dns_cf.sh'
[Sat Apr 15 21:20:07 CEST 2017] First detect the root zone
[Sat Apr 15 21:20:07 CEST 2017] h='aaa.sherbers.de'
[Sat Apr 15 21:20:07 CEST 2017] zones?name=aaa.sherbers.de
[Sat Apr 15 21:20:07 CEST 2017] GET
[Sat Apr 15 21:20:07 CEST 2017] url='https://api.cloudflare.com/client/v4/zones?name=aaa.sherbers.de'
[Sat Apr 15 21:20:07 CEST 2017] timeout
[Sat Apr 15 21:20:07 CEST 2017] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.UOkcibq7pF '
[Sat Apr 15 21:20:09 CEST 2017] ret='0'
[Sat Apr 15 21:20:09 CEST 2017] response='{"success":false,"errors":[{"code":9106,"message":"Missing X-Auth-Email header"},{"code":9107,"message":"Missing X-Auth-Key header"}],"messages":[],"result":null}'

So he remove command seems to be missing the Auth headers in the Post request.

Full debug Log:

[fulldebug.txt](https://github.com/Neilpang/acme.sh/files/923837/fulldebug.txt)

**Comment by stephan13360** [comment]
I ran some more tests and found this:

When I am in a bash session where I ran the exports commands:

export CF_Key="sdfsdfsdfljlbjkljlkjsdfoiwje"
export CF_Email="xxxx@sss.com"

it works fine. The TXT Records are removed. But when I later login again and use the saved credentials from account.conf, they only seem to be used for adding the Records but not for removing them.

**Comment by Neilpang** [comment]
Sorry,  it was caused by my last fix.

Please try with the latest code.

Thanks.

**Comment by stephan13360** [comment]
That fixed it. Works fine now.
