### ISSUE TITLE
关于证书问题..NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by airforce-captain** [Neilpang/acme.sh#801]
我这边是公司自建dns ，在一级域名下有多个二级域名，分别指向不同的服务器IP地址。通过acme.sh 申请了通配证书，也申请成功签署到证书，没有报错。

但是有个很奇怪的问题，同一份证书，一两个子域名在使用证书后，提示:

` 您的连接不是私密连接  NET::ERR_CERT_AUTHORITY_INVALID `

但是其他子域名是正常的。

报错的子域名使用PC端浏览器访问，无论是firefox, chrome,IE 都没有提示问题，唯独使用安卓手机自带浏

览器会报错，同时向有报错的子域名网站提交POST请求的时候，会失败，提示：

`x509: certificate signed by unknown authority`

但是查看证书，使用者名称中，都有包含此报错子域名的。证书也是显示有效的.

我生成证书的步骤是：

`acme  --issue  --dns  -d  example.com   -d  sub1.example.com ........-d subN.example.com  `

得到TXT 值后，加入DNS 记录中.,然后等待刷新后操作：
`acme --renew -d  example.com   -d  sub1.example.com ........-d subN.example.com `

这个subN 表示我有大约10几个子域名.

或许我不该在这里提交issue，可能这个问题是 let's encrypt 本身的签发机制的问题也说不定，我只好在这
里反馈一下，看看有没有帮助了。

**Comment by Neilpang** [comment]
证书链的问题,  你确定证书链全的吗?
https://certificatechain.io/

**Comment by Neilpang** [comment]
另外, 用你的 android 手机 访问其他的 没有问题的子域名,  看看是不是正常.

**Comment by airforce-captain** [comment]
貌似都不可以了，难道之前的是缓存？
现在安卓访问所有更新了证书的都提示报错，但是用PC 端浏览器访问就无问题.

我的证书申请机器是FreeBSD 8.4     OpenSSL 1.0.2h  3 May 2016

**Comment by airforce-captain** [comment]
之前在let's encrypt 网站的说明中，有一个根据web页面生成的证书也有这种问题，网站是`https://www.sslforfree.com`，后来我找到这个acme.sh 之后生成的证书就不会有这种问题.

**Comment by Neilpang** [comment]
你确定证书链全的吗?

**Comment by Neilpang** [comment]
能不能把域名贴出来.

**Comment by airforce-captain** [comment]
https://jenkins.eastfeet.com

这个是应用了新证书的测试站点，linux 机器.


另外，我不知道怎么检查证书链.FreeBSD 系统  --!

**Comment by Neilpang** [comment]
你的证书链不全.  如果你不直达奥怎么检查, 请谷歌搜索 如何检查证书链.

这是检查的结果:  https://www.ssllabs.com/ssltest/analyze.html?d=jenkins.eastfeet.com&latest

显示你的证书链不全.

用生成的 `fullchain.cer` 代替 `domain.cer`.

然后重启web 服务.

**Comment by Neilpang** [comment]
或者 把  `ca.cer`   append 到 你的证书文件后面.

**Comment by airforce-captain** [comment]
使用fullchain.cer 替换了domain.cer 后，手机访问ok了。

这期间，我漏了一个步骤没说，那就是我申请了证书后，在源机上，使用scp 将对应的domain.cer ,domain.key 传送到目标机器上的。跟这个有没有关系 ？

另外，证书链不全这个如何补全？ 顺手给个传送门吧。
