### ISSUE TITLE
Acme - Pfsense - Unable to update challenge

### ISSUE THREAD

**Issue by kasiub** [Neilpang/acme.sh#807]
Hello,

I am using acme 0.1.16 with Pfsense 2.3.3

I am trying to generate certificates with DNS manual method.

I have the issue in staging / production with all the certificates I have tried.

I able to issue the certificate and added the TXT field into the DNS but I have troubles to complete the certificate renewal:

TestDomain
Renewing certificateaccount: Staging
server: letsencrypt-staging

/usr/local/pkg/acme/acme.sh --renew -d 'test.frederic.re' --home '/tmp/acme/TestDomain/' --accountconf '/tmp/acme/TestDomain/accountconf.conf' --force --reloadCmd '/tmp/acme/TestDomain/reloadcmd.sh' --dns --dnssleep '240' --log-level 3 --log '/tmp/acme/TestDomain/acme_issuecert.log'

Array
(
[path] => /etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/
[PATH] => /etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/
)
[Wed Apr 26 10:42:06 CEST 2017] Renew: 'test.frederic.re'
[Wed Apr 26 10:42:06 CEST 2017] Single domain='test.frederic.re'
[Wed Apr 26 10:42:06 CEST 2017] Getting domain auth token for each domain
[Wed Apr 26 10:42:06 CEST 2017] Verifying:test.frederic.re
[Wed Apr 26 10:42:12 CEST 2017] test.frederic.re:Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}
[Wed Apr 26 10:42:12 CEST 2017] Please check log file for more details: /tmp/acme/TestDomain/acme_issuecert.log

Into the /tmp/acme/TestDomain/acme_issuecert.log:

[Wed Apr 26 10:41:36 CEST 2017] curl exists=0
[Wed Apr 26 10:41:36 CEST 2017] wget exists=127
[Wed Apr 26 10:41:36 CEST 2017] _CURL='curl -L --silent --dump-header /tmp/acme/TestDomain//http.header '
[Wed Apr 26 10:41:37 CEST 2017] _ret='0'
[Wed Apr 26 10:41:37 CEST 2017] original='{
  "type": "urn:acme:error:malformed",
  "detail": "Unable to update challenge :: The challenge is not pending.",
  "status": 400
}'

I don't think I am able to run acme debug with Pfsense.

Do you have any idea?

Thanks

**Comment by mgscreativa** [comment]
The same happens to me

> /usr/local/acme.sh/acme.sh --renewAll

> vps.XXXXXX.com:Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}
>Please check log file for more details: /usr/local/acme.sh/acme.sh.log
>Error renew vps.XXXXXX.com.

**Comment by Neilpang** [comment]
@mgscreativa 
Please give the `--debug 2` log.

**Comment by mgscreativa** [comment]
Here.

> [vie abr 28 13:02:08 ART 2017] Lets find script dir.
> [vie abr 28 13:02:08 ART 2017] _SCRIPT_='/usr/local/acme.sh/acme.sh'
> [vie abr 28 13:02:08 ART 2017] _script='/usr/local/acme.sh/acme.sh'
> [vie abr 28 13:02:08 ART 2017] _script_home='/usr/local/acme.sh'
> [vie abr 28 13:02:08 ART 2017] Using config home:/usr/local/acme.sh
> [vie abr 28 13:02:08 ART 2017] LE_WORKING_DIR='/usr/local/acme.sh'
> https://github.com/Neilpang/acme.sh
> v2.6.9
> [vie abr 28 13:02:08 ART 2017] Using config home:/usr/local/acme.sh
> [vie abr 28 13:02:08 ART 2017] _stopRenewOnError
> [vie abr 28 13:02:08 ART 2017] di='/etc/acme.sh/vps.debois.com.ar/'
> [vie abr 28 13:02:08 ART 2017] d='vps.debois.com.ar'
> [vie abr 28 13:02:08 ART 2017] Using config home:/usr/local/acme.sh
> [vie abr 28 13:02:08 ART 2017] DOMAIN_PATH='/etc/acme.sh/vps.debois.com.ar'
> [vie abr 28 13:02:08 ART 2017] Renew: 'vps.debois.com.ar'
> [vie abr 28 13:02:08 ART 2017] Using config home:/usr/local/acme.sh
> [vie abr 28 13:02:08 ART 2017] Using api: https://acme-v01.api.letsencrypt.org
> [vie abr 28 13:02:08 ART 2017] Le_NextRenewTime
> [vie abr 28 13:02:09 ART 2017] _on_before_issue
> [vie abr 28 13:02:09 ART 2017] 'dns' does not contain 'no'
> [vie abr 28 13:02:09 ART 2017] Le_LocalAddress
> [vie abr 28 13:02:09 ART 2017] Check for domain='vps.debois.com.ar'
> [vie abr 28 13:02:09 ART 2017] _currentRoot='dns'
> [vie abr 28 13:02:09 ART 2017] 'dns' does not contain 'apache'
> [vie abr 28 13:02:09 ART 2017] _saved_account_key_hash='KGP+MPyKRQVjvrOhPlZ+ZfowRGnfMqlS0LyQmaKqz3g='
> [vie abr 28 13:02:09 ART 2017] _saved_account_key_hash is not changed, skip register account.
> [vie abr 28 13:02:09 ART 2017] Read key length:4096
> [vie abr 28 13:02:09 ART 2017] _createcsr
> [vie abr 28 13:02:09 ART 2017] domain='vps.debois.com.ar'
> [vie abr 28 13:02:09 ART 2017] domainlist
> [vie abr 28 13:02:09 ART 2017] csrkey='/etc/acme.sh/vps.debois.com.ar/vps.debois.com.ar.key'
> [vie abr 28 13:02:09 ART 2017] csr='/etc/acme.sh/vps.debois.com.ar/vps.debois.com.ar.csr'
> [vie abr 28 13:02:09 ART 2017] csrconf='/etc/acme.sh/vps.debois.com.ar/vps.debois.com.ar.csr.conf'
> [vie abr 28 13:02:09 ART 2017] Single domain='vps.debois.com.ar'
> [vie abr 28 13:02:09 ART 2017] _is_idn_d='vps.debois.com.ar'
> [vie abr 28 13:02:09 ART 2017] _idn_temp
> [vie abr 28 13:02:09 ART 2017] _csr_cn='vps.debois.com.ar'
> [vie abr 28 13:02:09 ART 2017] Getting domain auth token for each domain
> [vie abr 28 13:02:09 ART 2017] ok, let's start to verify
> [vie abr 28 13:02:09 ART 2017] Verifying:vps.debois.com.ar
> [vie abr 28 13:02:09 ART 2017] d='vps.debois.com.ar'
> [vie abr 28 13:02:09 ART 2017] keyauthorization='C3zn1kmUTVMb-Rk9HRdCFx-Q2Mu33icJZELhugCksTQ.X46xSZjHB0GA5IX-WSaOeZu6nCnJkmshQAcVyQ1vJdk'
> [vie abr 28 13:02:09 ART 2017] uri='https://acme-v01.api.letsencrypt.org/acme/challenge/6I4OOaCbeM-DfaA10PwKGVa8KiWqEmVEvMdBl3CwEFU/1096174071'
> [vie abr 28 13:02:09 ART 2017] _currentRoot='dns'
> [vie abr 28 13:02:09 ART 2017] tigger domain validation.
> [vie abr 28 13:02:09 ART 2017] _t_url='https://acme-v01.api.letsencrypt.org/acme/challenge/6I4OOaCbeM-DfaA10PwKGVa8KiWqEmVEvMdBl3CwEFU/1096174071'
> [vie abr 28 13:02:09 ART 2017] _t_key_authz='C3zn1kmUTVMb-Rk9HRdCFx-Q2Mu33icJZELhugCksTQ.X46xSZjHB0GA5IX-WSaOeZu6nCnJkmshQAcVyQ1vJdk'
> [vie abr 28 13:02:09 ART 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/6I4OOaCbeM-DfaA10PwKGVa8KiWqEmVEvMdBl3CwEFU/1096174071'
> [vie abr 28 13:02:09 ART 2017] payload='{"resource": "challenge", "keyAuthorization": "C3zn1kmUTVMb-Rk9HRdCFx-Q2Mu33icJZELhugCksTQ.X46xSZjHB0GA5IX-WSaOeZu6nCnJkmshQAcVyQ1vJdk"}'
> [vie abr 28 13:02:09 ART 2017] RSA key
> [vie abr 28 13:02:09 ART 2017] Get nonce.
> [vie abr 28 13:02:09 ART 2017] GET
> [vie abr 28 13:02:09 ART 2017] url='https://acme-v01.api.letsencrypt.org/directory'
> [vie abr 28 13:02:09 ART 2017] timeout
> [vie abr 28 13:02:09 ART 2017] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  --trace-ascii /tmp/tmp.KCBso065rk '
> [vie abr 28 13:02:10 ART 2017] ret='0'
> [vie abr 28 13:02:10 ART 2017] _headers='HTTP/1.1 200 OK
> Server: nginx
> Content-Type: application/json
> Content-Length: 352
> Boulder-Request-Id: 2zGsBvmXcjKep5B3sCXlDl49h5KL8WjsHn48oPy7H-I
> Replay-Nonce: 8ikI2wymXQa2-jSlOMEpLSIut3lICutACipyvtsiK2k
> X-Frame-Options: DENY
> Strict-Transport-Security: max-age=604800
> Expires: Fri, 28 Apr 2017 16:02:10 GMT
> Cache-Control: max-age=0, no-cache, no-store
> Pragma: no-cache
> Date: Fri, 28 Apr 2017 16:02:10 GMT
> Connection: keep-alive
> '
> [vie abr 28 13:02:10 ART 2017] _CACHED_NONCE='8ikI2wymXQa2-jSlOMEpLSIut3lICutACipyvtsiK2k'
> [vie abr 28 13:02:10 ART 2017] nonce='8ikI2wymXQa2-jSlOMEpLSIut3lICutACipyvtsiK2k'
> [vie abr 28 13:02:10 ART 2017] POST
> [vie abr 28 13:02:10 ART 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/6I4OOaCbeM-DfaA10PwKGVa8KiWqEmVEvMdBl3CwEFU/1096174071'
> [vie abr 28 13:02:10 ART 2017] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "oWMQGOXq7ql3OiuCCqdkdUMo73ruJ1SymSQS7sjlnQOSdqKNDQww_Tl2xvs3WH2aOtsqeI2DL862PUfX-IUGDmXp3GAvZ1qhJW73GscoYgfX_Ov913pbSwvb4Lnh8v_SQPY-uWvlAjdbQtu0NW4iz2vExmLh1RGVmf38YpWgh48HidmtZ_fL8k5O-a55VkEjE2QMqChujQtItHrnUPBqmvQgnksdpH4RY_AXanLZCenwWXCiiMmN4zZIditaHjsRKT1lRZltxJYwif_P9aGMiSQo8LhsK0utP_IsCBZ4QdWN2j-bZUKUqj-vLW-TBTNkspoo_MEIHjMqLITfZ7YVbQ"}}, "protected": "eyJub25jZSI6ICI4aWtJMnd5bVhRYTItalNsT01FcExTSXV0M2xJQ3V0QUNpcHl2dHNpSzJrIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAib1dNUUdPWHE3cWwzT2l1Q0NxZGtkVU1vNzNydUoxU3ltU1FTN3NqbG5RT1NkcUtORFF3d19UbDJ4dnMzV0gyYU90c3FlSTJETDg2MlBVZlgtSVVHRG1YcDNHQXZaMXFoSlc3M0dzY29ZZ2ZYX092OTEzcGJTd3ZiNExuaDh2X1NRUFktdVd2bEFqZGJRdHUwTlc0aXoydkV4bUxoMVJHVm1mMzhZcFdnaDQ4SGlkbXRaX2ZMOGs1Ty1hNTVWa0VqRTJRTXFDaHVqUXRJdEhyblVQQnFtdlFnbmtzZHBINFJZX0FYYW5MWkNlbndXWENpaU1tTjR6WklkaXRhSGpzUktUMWxSWmx0eEpZd2lmX1A5YUdNaVNRbzhMaHNLMHV0UF9Jc0NCWjRRZFdOMmotYlpVS1Vxai12TFctVEJUTmtzcG9vX01FSUhqTXFMSVRmWjdZVmJRIn19", "payload": "eyJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLCAia2V5QXV0aG9yaXphdGlvbiI6ICJDM3puMWttVVRWTWItUms5SFJkQ0Z4LVEyTXUzM2ljSlpFTGh1Z0Nrc1RRLlg0NnhTWmpIQjBHQTVJWC1XU2FPZVp1Nm5DbkprbXNoUUFjVnlRMXZKZGsifQ", "signature": "YOsGtKJnTiRHXKUB0GCdvSH8_B-kCIk2D4vbJV3FFsQZox_8K4FVL-iDWXvywSEfLP5DgRgkaI9sA-OKftWumYfrA0kfw3wint_GVZqcM8w1pOPrE4Kg1A7MmL9pAaFULRpBi65DNvSrbIH8BjJQBJ7pTgN9w575S6TnNVdcBr8wVfQcKO07tO0Ce7mHXbwSlLwW8A3t3clYz9KW4JDJ-fHte8fNVZUcGWtnO5XCwVoGu7LyZyw6tLmERV7XD42tw8qH3JFVAzTYwNqK_5TuGWdNz_DQOPtaFognM2rP3cJkg5kM4O6rdy3E9_2VfWV8APqyLdUqXRijPxx41gYrlw"}'
> [vie abr 28 13:02:10 ART 2017] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  --trace-ascii /tmp/tmp.axuP0W0WCx '
> [vie abr 28 13:02:10 ART 2017] _ret='0'
> [vie abr 28 13:02:11 ART 2017] original='{
>   "type": "urn:acme:error:malformed",
>   "detail": "Unable to update challenge :: The challenge is not pending.",
>   "status": 400
> }'
> [vie abr 28 13:02:11 ART 2017] responseHeaders='HTTP/1.1 100 Continue
> Expires: Fri, 28 Apr 2017 16:02:10 GMT
> Cache-Control: max-age=0, no-cache, no-store
> Pragma: no-cache
> 
> HTTP/1.1 400 Bad Request
> Server: nginx
> Content-Type: application/problem+json
> Content-Length: 132
> Boulder-Request-Id: 3ZgiZHSypS4YU6MkI1UsJ6JvkfF2ep-iK4Un6O1WkKw
> Boulder-Requester: 13490759
> Replay-Nonce: dQ-nYlwkfVb5GHRTfEuZE_u1VaQd1uaHeMqiu0K00E8
> Expires: Fri, 28 Apr 2017 16:02:10 GMT
> Cache-Control: max-age=0, no-cache, no-store
> Pragma: no-cache
> Date: Fri, 28 Apr 2017 16:02:10 GMT
> Connection: close
> '
> [vie abr 28 13:02:11 ART 2017] response='{"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}'
> [vie abr 28 13:02:11 ART 2017] code='400'
> [vie abr 28 13:02:11 ART 2017] vps.debois.com.ar:Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}
> [vie abr 28 13:02:11 ART 2017] Skip for removelevel:
> [vie abr 28 13:02:11 ART 2017] pid
> [vie abr 28 13:02:11 ART 2017] No need to restore nginx, skip.
> [vie abr 28 13:02:11 ART 2017] _clearupdns
> [vie abr 28 13:02:11 ART 2017] Dns not added, skip.
> [vie abr 28 13:02:11 ART 2017] _on_issue_err
> [vie abr 28 13:02:11 ART 2017] Please check log file for more details: /usr/local/acme.sh/acme.sh.log
> [vie abr 28 13:02:11 ART 2017] _chk_vlist='vps.debois.com.ar#C3zn1kmUTVMb-Rk9HRdCFx-Q2Mu33icJZELhugCksTQ.X46xSZjHB0GA5IX-WSaOeZu6nCnJkmshQAcVyQ1vJdk#https://acme-v01.api.letsencrypt.org/acme/challenge/6I4OOaCbeM-DfaA10PwKGVa8KiWqEmVEvMdBl3CwEFU/1096174071#dns-01#dns,'
> [vie abr 28 13:02:11 ART 2017] start to deactivate authz
> [vie abr 28 13:02:11 ART 2017] tigger domain validation.
> [vie abr 28 13:02:11 ART 2017] _t_url='https://acme-v01.api.letsencrypt.org/acme/challenge/6I4OOaCbeM-DfaA10PwKGVa8KiWqEmVEvMdBl3CwEFU/1096174071'
> [vie abr 28 13:02:11 ART 2017] _t_key_authz='C3zn1kmUTVMb-Rk9HRdCFx-Q2Mu33icJZELhugCksTQ.X46xSZjHB0GA5IX-WSaOeZu6nCnJkmshQAcVyQ1vJdk'
> [vie abr 28 13:02:11 ART 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/6I4OOaCbeM-DfaA10PwKGVa8KiWqEmVEvMdBl3CwEFU/1096174071'
> [vie abr 28 13:02:11 ART 2017] payload='{"resource": "challenge", "keyAuthorization": "C3zn1kmUTVMb-Rk9HRdCFx-Q2Mu33icJZELhugCksTQ.X46xSZjHB0GA5IX-WSaOeZu6nCnJkmshQAcVyQ1vJdk"}'
> [vie abr 28 13:02:11 ART 2017] Use cached jwk for file: /usr/local/acme.sh/ca/acme-v01.api.letsencrypt.org/account.key
> [vie abr 28 13:02:11 ART 2017] Use _CACHED_NONCE='dQ-nYlwkfVb5GHRTfEuZE_u1VaQd1uaHeMqiu0K00E8'
> [vie abr 28 13:02:11 ART 2017] nonce='dQ-nYlwkfVb5GHRTfEuZE_u1VaQd1uaHeMqiu0K00E8'
> [vie abr 28 13:02:11 ART 2017] POST
> [vie abr 28 13:02:11 ART 2017] url='https://acme-v01.api.letsencrypt.org/acme/challenge/6I4OOaCbeM-DfaA10PwKGVa8KiWqEmVEvMdBl3CwEFU/1096174071'
> [vie abr 28 13:02:11 ART 2017] body='{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "oWMQGOXq7ql3OiuCCqdkdUMo73ruJ1SymSQS7sjlnQOSdqKNDQww_Tl2xvs3WH2aOtsqeI2DL862PUfX-IUGDmXp3GAvZ1qhJW73GscoYgfX_Ov913pbSwvb4Lnh8v_SQPY-uWvlAjdbQtu0NW4iz2vExmLh1RGVmf38YpWgh48HidmtZ_fL8k5O-a55VkEjE2QMqChujQtItHrnUPBqmvQgnksdpH4RY_AXanLZCenwWXCiiMmN4zZIditaHjsRKT1lRZltxJYwif_P9aGMiSQo8LhsK0utP_IsCBZ4QdWN2j-bZUKUqj-vLW-TBTNkspoo_MEIHjMqLITfZ7YVbQ"}}, "protected": "eyJub25jZSI6ICJkUS1uWWx3a2ZWYjVHSFJUZkV1WkVfdTFWYVFkMXVhSGVNcWl1MEswMEU4IiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAib1dNUUdPWHE3cWwzT2l1Q0NxZGtkVU1vNzNydUoxU3ltU1FTN3NqbG5RT1NkcUtORFF3d19UbDJ4dnMzV0gyYU90c3FlSTJETDg2MlBVZlgtSVVHRG1YcDNHQXZaMXFoSlc3M0dzY29ZZ2ZYX092OTEzcGJTd3ZiNExuaDh2X1NRUFktdVd2bEFqZGJRdHUwTlc0aXoydkV4bUxoMVJHVm1mMzhZcFdnaDQ4SGlkbXRaX2ZMOGs1Ty1hNTVWa0VqRTJRTXFDaHVqUXRJdEhyblVQQnFtdlFnbmtzZHBINFJZX0FYYW5MWkNlbndXWENpaU1tTjR6WklkaXRhSGpzUktUMWxSWmx0eEpZd2lmX1A5YUdNaVNRbzhMaHNLMHV0UF9Jc0NCWjRRZFdOMmotYlpVS1Vxai12TFctVEJUTmtzcG9vX01FSUhqTXFMSVRmWjdZVmJRIn19", "payload": "eyJyZXNvdXJjZSI6ICJjaGFsbGVuZ2UiLCAia2V5QXV0aG9yaXphdGlvbiI6ICJDM3puMWttVVRWTWItUms5SFJkQ0Z4LVEyTXUzM2ljSlpFTGh1Z0Nrc1RRLlg0NnhTWmpIQjBHQTVJWC1XU2FPZVp1Nm5DbkprbXNoUUFjVnlRMXZKZGsifQ", "signature": "AkqmLXZ4VDQASXIviHlB0FuouyA2jkOJgnK5-x0Ck84GdCezE8tOCWagmIjKZjVpFQbab00tVlQWZoxQEieHpaKh5JoZ1d1A1FnDtXXSRVuBXTahxF9w122agRutF1b9Zd7h0d8c4k4imJowNrErdxfercjbXzx0-aDmKKRPzTKiYqMf0A4yt8-u-rsATlahjB7gF8ang_zu4zcN9efUCFyRHbXir0azt2RM_EcYhLdbcXB9iJEdGN-Two2-jQKY21-hMB5Vwe_3mEJWD_c4rX8bFQPVFfJeydyUJAz1RgfZCzyVtPuMkWnFqmgMhAujouUuTcyPfvJi02CMqEmfSw"}'
> [vie abr 28 13:02:11 ART 2017] _CURL='curl -L --silent --dump-header /usr/local/acme.sh/http.header  --trace-ascii /tmp/tmp.9LOzs9R9wX '
> [vie abr 28 13:02:11 ART 2017] _ret='0'
> [vie abr 28 13:02:11 ART 2017] original='{
>   "type": "urn:acme:error:malformed",
>   "detail": "Unable to update challenge :: The challenge is not pending.",
>   "status": 400
> }'
> [vie abr 28 13:02:11 ART 2017] responseHeaders='HTTP/1.1 100 Continue
> Expires: Fri, 28 Apr 2017 16:02:11 GMT
> Cache-Control: max-age=0, no-cache, no-store
> Pragma: no-cache
> 
> HTTP/1.1 400 Bad Request
> Server: nginx
> Content-Type: application/problem+json
> Content-Length: 132
> Boulder-Request-Id: PtcEbEVJn8fP1pVJYa0kEKQuQfsdBLZIb1GkLV6x3yg
> Boulder-Requester: 13490759
> Replay-Nonce: 1YQvzUsOQLPK_EWEL0bXk_YAf1O4DBS9D16nhkpl-Ps
> Expires: Fri, 28 Apr 2017 16:02:11 GMT
> Cache-Control: max-age=0, no-cache, no-store
> Pragma: no-cache
> Date: Fri, 28 Apr 2017 16:02:11 GMT
> Connection: close
> '
> [vie abr 28 13:02:11 ART 2017] response='{"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}'
> [vie abr 28 13:02:11 ART 2017] code='400'
> [vie abr 28 13:02:11 ART 2017] Diagnosis versions:
> openssl:openssl
> OpenSSL 1.0.2k  26 Jan 2017
> apache:
> apache doesn't exists.
> nc:
> OpenBSD netcat (Debian patchlevel 1.105-7ubuntu1)
> This is nc from the netcat-openbsd package. An alternative nc is available
> in the netcat-traditional package.
> usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]
>           [-P proxy_username] [-p source_port] [-q seconds] [-s source]
>           [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
>           [-x proxy_address[:port]] [destination] [port]
>         Command Summary:
>                 -4              Use IPv4
>                 -6              Use IPv6
>                 -b              Allow broadcast
>                 -C              Send CRLF as line-ending
>                 -D              Enable the debug socket option
>                 -d              Detach from stdin
>                 -h              This help text
>                 -I length       TCP receive buffer length
>                 -i secs         Delay interval for lines sent, ports scanned
>                 -j              Use jumbo frame
>                 -k              Keep inbound sockets open for multiple connects
>                 -l              Listen mode, for inbound connects
>                 -n              Suppress name/port resolutions
>                 -O length       TCP send buffer length
>                 -P proxyuser    Username for proxy authentication
>                 -p port         Specify local port for remote connects
>                 -q secs         quit after EOF on stdin and delay of secs
>                 -r              Randomize remote ports
>                 -S              Enable the TCP MD5 signature option
>                 -s addr         Local source address
>                 -T toskeyword   Set IP Type of Service
>                 -t              Answer TELNET negotiation
>                 -U              Use UNIX domain socket
>                 -u              UDP mode
>                 -V rtable       Specify alternate routing table
>                 -v              Verbose
>                 -w secs         Timeout for connects and final net reads
>                 -X proto        Proxy protocol: "4", "5" (SOCKS) or "connect"
>                 -x addr[:port]  Specify proxy address and port
>                 -Z              DCCP mode
>                 -z              Zero-I/O mode [used for scanning]
>         Port numbers can be individual or ranges: lo-hi [inclusive]
> [vie abr 28 13:02:11 ART 2017] Return code: 1
> [vie abr 28 13:02:11 ART 2017] Error renew vps.debois.com.ar.
>

**Comment by Neilpang** [comment]
You are using `--dns` mode,  the manually mode.  it can not be renewed.  You must issue again.
you can also use dns api mode or webroot or standalone mode, that can renew automatically.

**Comment by Neilpang** [comment]
@mgscreativa

**Comment by mgscreativa** [comment]
Great! Is this command what you suggest?

> /usr/local/acme.sh/acme.sh --issue --standalone -d vps.debois.com.ar --keylength 4096 --force

**Comment by Neilpang** [comment]
@mgscreativa 
Yes, as long as your `80` port is free and your domain is pointing to your server.

**Comment by mgscreativa** [comment]
great, my renew command should look like this

service apache2 stop &&  /usr/local/acme.sh/acme.sh --renewAll && service apache2 start

**Comment by mgscreativa** [comment]
what should I do if I don't want to stop the webserver?

**Comment by Neilpang** [comment]
@mgscreativa 

No,  you don't need to stop your apache server.  you can use `--apache` mode to issue cert:
```
acme.sh  --issue  --apache  --d example.com
```
This will issue the cert , but not change your apache server conf.

**Comment by mgscreativa** [comment]
so 

> /usr/local/acme.sh/acme.sh --issue --apache -d vps.debois.com.ar --keylength 4096 --force

then 

> /usr/local/acme.sh/acme.sh --renewAll && service apache2 reload

Will do the trick?

**Comment by Neilpang** [comment]
@mgscreativa 
You don't need to call `--renewall`,  the default cron job should take care of that.
```sh
crontab -l
```

Please read the doc from top to bottom: 
https://github.com/Neilpang/acme.sh#3-install-the-issued-cert-to-apachenginx-etc

You will know how to use it.

here are a lot of guides:  https://github.com/Neilpang/acme.sh/wiki/Blogs-and-tutorials

**Comment by mgscreativa** [comment]
Great! thanks!

**Comment by CMCDragonkai** [comment]
@Neilpang 

> You are using --dns mode, the manually mode. it can not be renewed. You must issue again.
> you can also use dns api mode or webroot or standalone mode, that can renew automatically.

The README mentions that you can use the `--renew` option with DNS manual mode. Does this mean we must always use `--issue`? https://github.com/Neilpang/acme.sh#8-use-dns-mode

Because I ran with `--renew` and go the same error with  `{"type":"urn:acme:error:malformed","detail":"No such challenge","status": 404}`.

Or is `--renew` ONLY meant to be used after running an `--issue` each time?

**Comment by ezeev** [comment]
I'm also getting the same error and am confused by the readme per @CMCDragonkai's last comment. This worked a few months ago. Did something break recently for dns validation?

**Comment by CMCDragonkai** [comment]
You basically have to call `--issue` each 3 months to renew manual dns.

**Comment by FernandoMiguel** [comment]
As stated before, manual dns should not be used in production as it requires to manually reissue new certs.
Please consider using dns api providers instead

**Comment by ezeev** [comment]
@FernandoMiguel @CMCDragonkai - this is for a small, for fun side project. I just found out the root of my problem. My domain / DNS provider (namecheap) appears to be blocking TXT records for lets encrypt certs.
