### ISSUE TITLE
Using --nginx mode, acme.sh can't find a server_name that exists

### ISSUE THREAD

**Issue by DaveQB** [Neilpang/acme.sh#808]
Steps to reproduce
------------------
acme.sh --issue --nginx  --force  --debug --log  
(followed by 31 -d <domain> arguments)

Debug log
-----------------

acme.sh  --issue .....   --debug 2
```
[Thu Apr 27 17:45:41 AEST 2017] _isRealNginxConf wsgridiron.info /etc/nginx/sites-enabled/wspirates

[Thu Apr 27 17:45:41 AEST 2017] Can not find conf file for domain wsgridiron.info
[Thu Apr 27 17:45:41 AEST 2017] pid
[Thu Apr 27 17:45:41 AEST 2017] No need to restore nginx, skip.
[Thu Apr 27 17:45:41 AEST 2017] _clearupdns
[Thu Apr 27 17:45:41 AEST 2017] Dns not added, skip.
[Thu Apr 27 17:45:41 AEST 2017] _on_issue_err```

[Thu Apr 27 17:47:02 AEST 2017] code='202'
```

Yet:

```
grep -o  wsgridiron.info /etc/nginx/sites-enabled/wspirates  
wsgridiron.info  
wsgridiron.info  
wsgridiron.info  
wsgridiron.info     
```

I switched to --nginx mode after trying to list multiple domains each with their own webroot, but it seems you can only have 1 webroot with acme.sh
Such as:

-d 1.domain.com -d 2.domain.com -w /var/www/domain.com -d 3.domain.com -d 4.domain.com -w /var/www/domain2.com

For some reason acme tried to use /var/www/domain2.com for 1.domain.com. Anyway, that's another topic.

Thanks!

**Comment by Neilpang** [comment]
if you have different  webroot for the domains,  you  MUST specify webroots for EVERY domain in the command line, even though some of the domains may share the same webroot folder.

example:

```
acme.sh --issue  \
 -d 1.domain.com -w /var/www/domain.com \
 -d 2.domain.com -w /var/www/domain.com \
 -d 3.domain.com -w /var/www/domain2.com \
 -d 4.domain.com -w /var/www/domain2.com


```

**Comment by DaveQB** [comment]
@Neilpang Thank you so much for the fast response! I didn't deduce that from the docs. I'll try that. Not sure why the --nginx option is not working. Too many server_name values for acme to search through? Hmmm

**Comment by Neilpang** [comment]
Give me the full log and the nginx conf file, otherwise I can not fix it.

**Comment by DaveQB** [comment]
@Neilpang  Can I get that to you on a private channel please?

**Comment by Neilpang** [comment]
Yes, write email to me: `info[AT]`acme.sh

**Comment by DaveQB** [comment]
@Neilpang  Thank you

**Comment by Neilpang** [comment]
fixed.  Please try with the latest `dev` branch:

```sh
export BRANCH=dev
acme.sh --upgrade
```

I will merge it to master if it works for you.

Thanks.
