### ISSUE TITLE
DNS的Linode方案存在问题

### ISSUE THREAD

**Issue by cnrat** [Neilpang/acme.sh#818]
URL中的'&'符号无法被curl处理，导致Linode API返回的JSON是无法验证ApiKey的报错。

**Comment by Neilpang** [comment]
能不能给个 `--debug 2` 的输出.   说具体一点.

**Comment by cnrat** [comment]
@Neilpang 你把domain.list的API请求完整URL用curl跑一下就知道问题了，debug我现在没有在家里，最早也要12个小时后才能提供，其实问题我已经定位啦~参考 http://stackoverflow.com/questions/13339469/how-to-include-an-character-in-a-bash-curl-statement

**Comment by Neilpang** [comment]
我并没有 linode 的账号.
等你给出log 再看吧.

**Comment by cnrat** [comment]
@Neilpang Linode的API Key不太可能发出来吧。你的log里面只能看到递归拆解域名，然后提示找不到域名而已。
问题所在就是你
LINODE_API_URL="https://api.linode.com/?api_key=$LINODE_API_KEY&api_action="
里面的&符号，curl无法处理这个符号，所以作为参数的api_action并没有真正被当成参数上送。
任何dns脚本里面，如果url本身包含了&实际上都有这个问题。
所以这实在跟Linode没什么必然联系，只是curl使用问题。

**Comment by Neilpang** [comment]
不需要你发api key,  你可以隐藏部分字符, 不影响判断就好.
url 里面带 & 的 很多.  curl 知道如何处理. 我怀疑你的问题不在这里. 
我猜测是不是你的 api key 或者 secret 里面包含了 & 符号.

还是见了log 再说吧.

**Comment by cnrat** [comment]
@Neilpang 确定跟curl版本有关系，我回去看看我路由器上的curl是什么版本吧。
