### ISSUE TITLE
我想问一下如何删除列表中不再使用的证书项目

### ISSUE THREAD

**Issue by wujingwang** [Neilpang/acme.sh#820]
您好
      我想问一下如何删除列表中不再使用的证书项目，谢谢！
HSYG-ST01:~# ./acme.sh --list
Main_Domain           KeyLength  SAN_Domains  Created                       Renew
heshang365.com        "ec-256"   no           Wed May  3 14:06:11 UTC 2017  Sun Jul  2 14:06:11 UTC 2017
ssl.heshang365.com    "2048"     no
ssl.heshang365.com    "ec-256"   no           Wed May  3 14:13:05 UTC 2017  Sun Jul  2 14:13:05 UTC 2017
www.alphalabs.net.cn  "2048"     no
www.domain.com        "2048"     no
www.heshang365.com    "2048"     no

Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
```
acme.sh  --remove  -d example.com
```

**Comment by wujingwang** [comment]
Thank you very much
