### ISSUE TITLE
Automatic dns mode renewal fails with current challenge.

### ISSUE THREAD

**Issue by ksuuk** [Neilpang/acme.sh#824]
Hi,

I had impression, that once issued and challenge added to dns, certificates will automatically updated and challenge stays the always same? If this is the idea, then what I did wrong? 

I did install acme.sh into multiple servers 3 months ago:
wget -O -  https://get.acme.sh | sh

Issued certificate:
acme.sh --issue --dns -d test.example.com

Got and added _acme-challenge.example.com to dns and then:
acme.sh --renew -d test.example.com

And added scripts to execute after renewal:
acme.sh --install-cert -d test.example.com --reloadcmd "service dovecot restart && service postfix restart"

Today, got error from all servers cron -s, like:

[Thu May  4 00:32:03 EEST 2017] Add the following TXT record:
[Thu May  4 00:32:03 EEST 2017] Domain: '_acme-challenge.test.example.com'
[Thu May  4 00:32:03 EEST 2017] TXT value: 'jvm0-SNNTkI5OrTRXRlKvTsXImvCq2dCjsO0JS7T9kU'
[Thu May  4 00:32:03 EEST 2017] Please be aware that you prepend _acme-challenge. before your domain
[Thu May  4 00:32:03 EEST 2017] so the resulting subdomain will be: _acme-challenge.test.example.com
[Thu May  4 00:32:03 EEST 2017] Please add the TXT records to the domains, and retry again.
[Thu May  4 00:32:03 EEST 2017] Please add '--debug' or '--log' to check more details.
[Thu May  4 00:32:03 EEST 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Thu May  4 00:32:03 EEST 2017] Error renew test.example.com.

**Comment by FernandoMiguel** [comment]
--dns is mostly for testing purposes and will probably be fased out in the future. 
It's preferable to use a dns api rather than manual as it requires new dns records to be entered manually into the DNS zone before renewal

**Comment by Neilpang** [comment]
everytime your renew the cert, the txt value is different.

**Comment by ksuuk** [comment]
@Neilpang 

Hmm, but then using dns method there is no not automated renewal? And as I have also in each server port 80/443 used, so I cant use any other then dns method and I must manually change each server key in dns. Or do You have plan to somehow automate this for ISC bind server?

**Comment by ksuuk** [comment]
@FernandoMiguel

But I'm running ISC based bind server. Does it have API and usable with acme.sh?

**Comment by ksuuk** [comment]
@Neilpang 
I'm using now the NSUPDATE api - https://github.com/Neilpang/acme.sh/tree/master/dnsapi#7-use-nsupdate-to-automatically-issue-cert, but I'd suggest adding into manual information, that dns mode renewal does not work automatically and challenge key will be changed every time and dns must be manually modified every time.
