### ISSUE TITLE
dns_nsupdate.sh error -  key xxxx is unreadable

### ISSUE THREAD

**Issue by ksuuk** [Neilpang/acme.sh#825]
Hi,

Wanted to set up nsupdate api ( https://github.com/Neilpang/acme.sh/tree/master/dnsapi#7-use-nsupdate-to-automatically-issue-cert ) with ISC BIND dns server.

Key is correct and working when testing it manually witn nsupdate (nsupdate -k keyfile commands.txt). But somehow acme.sh and dns_nsupdate.sh doesn't either find or can't read the key:

export NSUPDATE_SERVER="dns.domain.com"
export NSUPDATE_KEY="SRCKBnrkq1xKnfopBoOHH4Jdfdfdfdgpdffdfdfdfdfd8vLRJ10yVQRqYRp/djQ2Xvu6YV9A=="

[Thu May  4 16:27:33 EEST 2017] d_api='/root/.acme.sh/dnsapi/dns_nsupdate.sh'
[Thu May  4 16:27:33 EEST 2017] Found domain api file: /root/.acme.sh/dnsapi/dns_nsupdate.sh
[Thu May  4 16:27:33 EEST 2017] you must specify a path to the nsupdate key file
[Thu May  4 16:27:33 EEST 2017] Error add txt for domain:_acme-challenge.test.domain.com

After manually adding to account.conf it shows the key but still gives error:

NSUPDATE_SERVER="dns.domain.com"
NSUPDATE_KEY="SRCKBnrkq1xKnfopBoOHH4Jdfdfdfdgpdffdfdfdfdfd8vLRJ10yVQRqYRp/djQ2Xvu6YV9A=="

[Thu May  4 16:28:05 EEST 2017] d_api='/root/.acme.sh/dnsapi/dns_nsupdate.sh'
[Thu May  4 16:28:05 EEST 2017] Found domain api file: /root/.acme.sh/dnsapi/dns_nsupdate.sh
[Thu May  4 16:28:05 EEST 2017] key SRCKBnrkq1xKnfopBoOHH4Jdfdfdfd'gpdffdfdfdfdfd8vLRJ10yVQRqYRp/djQ2Xvu6YV9A== is unreadable
[Thu May  4 16:28:05 EEST 2017] Error add txt for domain:_acme-challenge.test.domain.com

**Comment by Neilpang** [comment]
I think NSUPDATE_KEY should be the key file path, not the key.
There might be a doc error in the doc.

**Comment by ksuuk** [comment]
@Neilpang 

Yes, manual contains error:

False:

export NSUPDATE_KEY="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=="

Correct:

export NSUPDATE_KEY="/etc/named/keys/update.key"

**Comment by Neilpang** [comment]
@ksuuk 
Can you please update the  doc and send a PR ?

Thanks.
