### ISSUE TITLE
[Feature request]Support tls-sni-01 validation in other mode

### ISSUE THREAD

**Issue by CzBiX** [Neilpang/acme.sh#836]
Support `tls-sni-01` validation in mode other than standalone, such as web root and stateless.

**Comment by Neilpang** [comment]
what do you mean ?

**Comment by FernandoMiguel** [comment]
@Neilpang and I were discussing this here
https://github.com/Neilpang/acme.sh/issues/821#issuecomment-298934886

problem at the moment is that your server needs a starting SSL to issue a cert.

**Comment by Neilpang** [comment]
can you please try to use webroot mode ?

I know your 80 port is blocked,  but there are so many dns provider support to redirect  http request to https request automatically.
Then you can use webroot mode.


And if it's possible, you can also use dns api mode, if you dns provider has an api.

Thanks.

**Comment by Neilpang** [comment]
@FernandoMiguel 

Yes,  but that's a little more complicated than expected.

**Comment by FernandoMiguel** [comment]
@Neilpang i'm aware. hence providing the background of the discussion

**Comment by CzBiX** [comment]
@FernandoMiguel Yep, it must to use standalone tls mode in the first issue. Maybe a little complicated, just like `--create-account-key` for professional use.

@Neilpang Thanks for your tips. I didn't even know there are dns providers support redirect http request.
I will try to use dns api at the moment, but I still hope this feature will be implemented in the furture.

**Comment by Neilpang** [comment]
@CzBiX 
Yes, dns api mode is the best choice for you.

And if you just host the website in your home, and 80 port is even blocked,  I would guess the website is not too important.   Then I would think using `--prehook` and `--posthook`  to stop and restart the web server every 2 months is acceptable.

Thanks.

**Comment by CzBiX** [comment]
After I read IETF at https://tools.ietf.org/html/draft-ietf-acme-acme-04, I realize the `tls-sni-01` is not work as I expected to. It's not possible pass `tls-sni-01` verify via put auth file in web root.
