### ISSUE TITLE
Renew non-www domain cert

### ISSUE THREAD

**Issue by schwindelbub** [Neilpang/acme.sh#837]
Hello,

I have created an cert for a non-www domain. This works fine, weeks ago. Thanks for this!
Now it should be extended. So the cron runs - with an error.

If I starts it manually I get the error message: acme.sh trys to create a cert for cert.example.com AND for www.cert.example.com. But www.cert.example.com isn't configured - and should not - and the request for the well-known file fails. Why will acme.sh create an cert for both domains?

acme.sh --renew -d cert.example.com:
[Mi 10. Mai 18:59:04 CEST 2017] Renew: 'cert.example.com'  
[Mi 10. Mai 18:59:04 CEST 2017] Single domain='cert.example.com'
[Mi 10. Mai 18:59:04 CEST 2017] Getting domain auth token for each domain
[Mi 10. Mai 18:59:04 CEST 2017] Getting webroot for domain='cert.example.com'
[Mi 10. Mai 18:59:04 CEST 2017] Getting new-authz for domain='cert.example.com'
[Mi 10. Mai 18:59:06 CEST 2017] The new-authz request is ok.
[Mi 10. Mai 18:59:06 CEST 2017] Verifying:cert.example.com
[Mi 10. Mai 18:59:10 CEST 2017] cert.example.com:Verify error:Could not connect to www.cert.example.com
[Mi 10. Mai 18:59:10 CEST 2017] Please check log file for more details: /root/.acme.sh/acme.sh.log

acme.sh --version
https://github.com/Neilpang/acme.sh
v2.6.9

cat /proc/version
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.43-2 (2017-04-30)

Best regards
Schwindelbub

**Comment by Neilpang** [comment]
@schwindelbub 

The error message `Could not connect to www.cert.example.com` is not reported by acme.sh,   it was reported by the Letsencrypt CA server.

That means, when the lets'encrypt CA server visits the domain `cert.example.com`, it was redirected(301 or 302) to the domain `www.cert.example.com`.

Please check your website config, apache or nginx,  whether there is such a redirect.  And you can open the url in your browser to see the situation :   `http://cert.example.com`

**Comment by schwindelbub** [comment]
Ok, unterstand. But who says letsencrypt to encrypt and to connect www.cert.example.com? Does amce.sh this?
There is no redirect. The domain www.cert.example.com simply doesn't exist! Not even in the DNS. Thats correct. It should not.

Prepends acme.sh auomatically .www?

I have ~20 other domains with letsencrypt and amce.sh with out problems.

**Comment by Neilpang** [comment]
Nobody says www.cert.example.com.     acme.sh won't be that stupid to prepend "www." .

can you please open the url in your browser:  http://cert.example.com

what happens ?
