### ISSUE TITLE
After key file is copied to install destination, it is readable by all

### ISSUE THREAD

**Issue by nitrotm** [Neilpang/acme.sh#847]
Steps to reproduce
------------------

```
  /root/.acme.sh/acme.sh --install-cert -d "$HOSTNAME" \
    --key-file               "/etc/nginx/ssl/$HOSTNAME.key" \
    --fullchain-file         "/etc/nginx/ssl/$HOSTNAME.crt" \
    --reloadcmd              "service nginx force-reload"
```

Problem
-----------------

/etc/nginx/ssl/$HOSTNAME.key as permission '-rw-r--r--' meaning anybody on the server can extract the server's private key. That's a huge security risk and it must default to at least '-rw-r-----'.

**Comment by Neilpang** [comment]
Sorry, we don't change the permissions:
https://github.com/Neilpang/acme.sh/wiki/how-about-the-private-key-access-modes,--chmod,-or-chown-or-umask
