### ISSUE TITLE
Can you somehow switch the authentication mechanism?

### ISSUE THREAD

**Issue by ovizii** [Neilpang/acme.sh#852]
running acme.sh 2.6.9 

say I initially setup a domain to auth via DNS how can I switch it to the the "normal" way via .well-known ? 
I've looked at all sorts of config files I could find related to this but didn't see any way to achieve this.

**Comment by FernandoMiguel** [comment]
the config is saved on DOMAIN/DOMAIN.conf file
for DNS you can see
Le_Webroot='dns_cf'

I dont think @Neilpang likes people changing the conf manually.
I guess you can always issue a new one with the new conf with --force

**Comment by ovizii** [comment]
Thanks for the reply, I have: 
`Le_Webroot='/mnt/nginx_proxy/www'`

and yet in my last log I saw:
```
[Wed 17 May 00:00:07 CEST 2017] Try new-authz for the 0 time.
[Wed 17 May 00:00:07 CEST 2017] url='https://acme-v01.api.letsencrypt.org/acme/new-authz'
[Wed 17 May 00:00:07 CEST 2017] payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "mydomain.tld"}}'
```
due to the identifier type DNS I assumed it was trying to auth via DNS, my msitake.

**Comment by Neilpang** [comment]
Is your problem solved ?

**Comment by ovizii** [comment]
If you can confirm that 

`payload='{"resource": "new-authz", "identifier": {"type": "dns", "value": "mydomain.tld"}}'`

does not mean that mydomain.tld is being authenticated via DNS and rather via what I see inside mydomain.conf

`Le_Webroot='/mnt/nginx_proxy/www'`

then all is good.

**Comment by Neilpang** [comment]
yes

**Comment by TiloGit** [comment]
old topic but I had this (wanted to switch DNS provider) 
I end up with a new folder called _ecc, I changed the folder names around which seems to work (now the `acme.sh --install-cert`  pick up the new cert)

```console
 localazureuser@myserver:~$ ll -h ~/.acme.sh
total 260K
drwx------  8 localazureuser localazureuser 4.0K Dec  4 17:52 ./
drwxr-xr-x 14 localazureuser localazureuser 4.0K Oct  2 15:43 ../
-rw-rw-r--  1 localazureuser localazureuser  590 Dec  4 17:44 account.conf
-rwxrwxr-x  1 localazureuser localazureuser 216K Jul  4 17:04 acme.sh*
-rw-rw-r--  1 localazureuser localazureuser  108 Feb 14  2022 acme.sh.env
drwxrwxr-x  3 localazureuser localazureuser 4.0K Feb 14  2022 ca/
drwxrwxr-x  2 localazureuser localazureuser 4.0K Jul  4 17:04 deploy/
drwxrwxr-x  2 localazureuser localazureuser 4.0K Jul  4 17:04 dnsapi/
-rw-rw-r--  1 localazureuser localazureuser  494 Dec  4 17:44 http.header
drwxrwxr-x  2 localazureuser localazureuser 4.0K Jul  4 17:04 notify/
drwxrwxr-x  2 localazureuser localazureuser 4.0K Dec  4 17:30 wiki.mydom.com_ecc/
drwxrwxr-x  3 localazureuser localazureuser 4.0K Feb 14  2022 wiki.mydom.com/
```
