### ISSUE TITLE
Cron works fail.

### ISSUE THREAD

**Issue by ac1982** [Neilpang/acme.sh#856]
Steps to reproduce
------------------

```
//in Ubuntu bash, user root.
crontab -e
0 0 * * * "/home/user/.acme.sh"/acme.sh --cron --home "/home/user/.acme.sh" > /dev/null
// it does not work.   log : --cron: command not found
```

But if edit /etc/crontab, it works fine.

```
//in Ubuntu bash, user root.
nano /etc/crontab
0 0 * * * root "/home/user/.acme.sh"/acme.sh --cron --home "/home/user/.acme.sh" > /dev/null
```

I'v no idea about this. So maybe someone could explain what it happened.

**Comment by Neilpang** [comment]
tell me your os version

**Comment by ac1982** [comment]
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-79-generic x86_64)

**Comment by Neilpang** [comment]
@ac1982  Most of my server are running on ubuntu 16.04, but they seem to work fine.

**Comment by Neilpang** [comment]
did you install acme.sh under a normal user or root ?

**Comment by ac1982** [comment]
Install it as root. and also import the path when use `crontab -e`
like this:
```
PATH=/usr/bin:/usr/local/bin:/usr/local/sbin:/root/.acme.sh
// and the really command in crontab -e is :
0 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null

```

**Comment by Neilpang** [comment]
@ac1982 
Can you please try to find what the user is when the cronjob is running ?
For example,  add the following crontab entry to your root crontabs.

```
0 0 * * *  whoami>/tmp/whoami.txt
```

when the crontab run, check the temp file  /tmp/whoami.txt

**Comment by ac1982** [comment]
I login as root, so the `crontab -e` should be the root.
And I follow your step to run cron, it tell as what I said: the user is root.
Is there something wrong with these codes in `crontab -e `
```
SHELL=/bin/bash
PATH=/usr/bin:/usr/local/bin:/usr/local/sbin:/root/.acme.sh
```

**Comment by Neilpang** [comment]
You don't need to set `SHELL`  or `PATH`.
If they are just for acme.sh,   just remove them.  acme.sh knows how to deal with that.

**Comment by ac1982** [comment]
My other commands need set path. 
So, I just used it like the second way as global schedule in `/etc/crontab`.
Anyway, there is a solution here. I just want to know what happened.

**Comment by Firm** [comment]
I have similar issue with crontab -e job at CentOS 6. When running script from crontab I found that script fails in

`if _startswith "$1" '-'; then _process "$@"; else "$@"; fi`

string. Starting from shell `if` passes execution to `_process` but running from cron passes it to 2nd block. That's why crontab-based execution fails.

**Comment by Firm** [comment]
I've changed the code to
`  if _startswith "$1" '-'; then echo 'true'; else echo 'false';fi
exit`
and could confirm that it prints true when running from shell and gives me false when started from crontab.

**Comment by Firm** [comment]
I fixed it. Having this line in crontab's root causes acme.sh to fail:
`PATH=$PATH:/sbin:/usr/sbin:/usr/bin`

**Comment by csytan** [comment]
@Firm This fixed it for me as well. I added `/bin` (location of grep in Ubuntu) to my `PATH`.
