### ISSUE TITLE
Cert generation works on smartOS (Illumos Core)

### ISSUE THREAD

**Issue by raininja** [Neilpang/acme.sh#857]
Just wanted to let you know that generating a cert worked fine on smartOS.  The link to my blog is [https://denki.ninja](url) 

Thanks for your work here, excellent script you've created.

**Comment by Neilpang** [comment]
Thanks for the info.
But I could not find an info about acme.sh on your blog.

Would you mind writing down your process  on your blog ? so that I can link it to the acme.sh wiki: https://github.com/Neilpang/acme.sh/wiki

That could help others.
