### ISSUE TITLE
dnsapi/dns_dynu.sh uses request dns/getroot - site says invalid

### ISSUE THREAD

**Issue by jmcgnh** [Neilpang/acme.sh#874]
It seems I have to open this issue here, can't open an issue at forked repo shar0119/acme.sh (or I'm just ignorant on how to do that). Tagging @shar0119

I tried using dns_dynu.sh and it failed for me. The problem appears to be the request dns/getroot made by the _get_root() function - this request is not documented in the Dynu API and, when I try it, is responded to with "Invalid request".

{"type":"Argument Exception","message":"Invalid request."}

In the absence of this facility, it looks to me like one must retrieve the list of domains with request dns/domains and locate a tail-match with the current hostname.

**Comment by Neilpang** [comment]
@shar0119
