### ISSUE TITLE
Could not connect to domain with port 8081

### ISSUE THREAD

**Issue by fredbcode** [Neilpang/acme.sh#875]
Hello

I'm trying acme.sh with an "exotic" port (8081) and I have an issue with renew 

I'm trying this: ->My line in crontab

/root/.acme.sh/acme.sh -d mydomain--httpport 8081 --fullchain-file /etc/lighttpd/ssl/fullchain.crt --cert-file /etc/lighttpd/ssl/host.crt --key-file /etc/lighttpd/ssl/host.crt --cron --home "/root/.acme.sh" --log "/var/log/certif.log" --log-level 2 --reloadcmd "cat /etc/lighttpd/ssl/host.crt /etc/lighttpd/ssl/host.key > /etc/lighttpd/ssl/hostkey.pem"

And just after "The new-authz request is ok" I have:  Could not connect to domain xx.xx.xx.xx

Something seems wrong in log

```
[mercredi 14 juin 2017, 16:46:13 (UTC+0200)] code='202'
[mercredi 14 juin 2017, 16:46:13 (UTC+0200)] sleep 2 secs to verify
[mercredi 14 juin 2017, 16:46:15 (UTC+0200)] checking
[mercredi 14 juin 2017, 16:46:15 (UTC+0200)] GET
[mercredi 14 juin 2017, 16:46:15 (UTC+0200)] url='https://acme-v01.api.letsencrypt.org/acme/challenge/VxvtUDOEOc0fc9UuPCL67jLwM/1339812778'
[mercredi 14 juin 2017, 16:46:15 (UTC+0200)] timeout
[mercredi 14 juin 2017, 16:46:15 (UTC+0200)] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header '
[mercredi 14 juin 2017, 16:46:16 (UTC+0200)] ret='0'
[mercredi 14 juin 2017, 16:46:16 (UTC+0200)] original='{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:connection",
    "detail": "Could not connect to mydomain.xx",
    "status": 400
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/VxvtUDOki2mP99E1EVJuvuOc0fc9UuPCL6jLwM/1339812778",
  "token": "NoZBXRSka1ps23kwN7qAHA0VeZvEj6mqaFRGzSBA",
  "keyAuthorization": "NoZBXRSkaps23kwN-BQ7qAHA0VeZvEGA2rEleT7lItkFzGAv7CYsHXvCPNEHsTEXXzAvdO78",
  "validationRecord": [
    {
      "url": "http://nas.traceroot.fr/.well-known/acme-challenge/NoZXRSka1ps23kwNQ7qAHA0VeZvEj6mqaFRGzSBA",
      "hostname": "mydomain.xx",
      **"port": "80"**,
      "addressesResolved": [
        "xx.xx.xx.xx"
      ],
      "addressUsed": "xx.xx.xx.xx",
      "addressesTried": []
    }
  ]
}'
```
As you can see curl try with port 80 ? Why ? With 443 I would have understood  
Maybe there is something I misunderstand ?

Thanks

**Comment by FernandoMiguel** [comment]
Validation needs to be done over port 80 or 443.
HTTP PORT command is for when using with a reverse proxy in front of acme.sh

**Comment by fredbcode** [comment]
Argh no way to change this ?

**Comment by FernandoMiguel** [comment]
It's the supported ones by let's encrypt to validate ownership of a domain 
Otherwise something rogue could fake it.

What are you trying to achieve? Maybe there's an easy alternative

**Comment by fredbcode** [comment]
Ok, for specific reason my web server (nas) only listen on this port, so if I understand right I need to find a network trick like NAT

**Comment by FernandoMiguel** [comment]
You mean whatever httpd is running on your NAS is listening on that port?
You can use acme.sh with standalone and listen on port 80

Or you can portfw at your router 

Or you can use dns01 for validation

**Comment by fredbcode** [comment]
> You mean whatever httpd is running on your NAS is listening on that port?
Yes

OK I will try, thanks for your help
