### ISSUE TITLE
关于cron的建议

### ISSUE THREAD

**Issue by dingdayu** [Neilpang/acme.sh#880]
这个工具很方便，我放到我的服务器上，并启用了cron的自动更新，但是，我在写博客时，写到计划脚本部分，忽然意识到，--cron时并没有重启nginx或者Apache。

```
"/home/****/.acme.sh"/acme.sh --cron --home "/home/****/.acme.sh"
```

并对此进行求证，安装工具的提示：

```
"/home/dingdayu/.acme.sh"/acme.sh --cron --home "/home/dingdayu/.acme.sh" --force --debug --log ./log.log
```
发现没有重启nginx的部分，并在登陆账号（****）和root下分别尝试，并且，执行后，在浏览器中查看证书有效期，仍是原来的，以此证明nginx并没有重载证书。

> 但是查看代码部分，发现其实是存在`nginx -s reload` 的，一步步追查，可以追查到：

`nginx -s reload` > `_restoreNginx ` > `_clearup` > `issue`

但是不知的是：为何nginx并为重载证书文件。

**Comment by Neilpang** [comment]
cron 不负责 重启nginx.
你在生成每个证书的时候, 需要制定如何重启服务,以及重启那个服务.
请仔细于阅读这一节:
https://github.com/Neilpang/acme.sh/wiki/%E8%AF%B4%E6%98%8E#3-copy%E5%AE%89%E8%A3%85-%E8%AF%81%E4%B9%A6

**Comment by dingdayu** [comment]
好的多谢，不过我想，既然是计划脚本，并且能检测到nginx，是应该重载配置的吧。这样逻辑上也是通顺的，或者在cron>crontab时，加上"--reloadcmd 'nginx -s reload'"(我想后面这个建议确实手动输入比较好。)
