### ISSUE TITLE
"url": missing from JWK_HEADER

### ISSUE THREAD

**Issue by Takios** [Neilpang/acme.sh#881]
Hello,

this issue happens with [Pebble](https://github.com/letsencrypt/pebble).
When registering a new account with Pebble, I get a Bad Request error code:

[Fri Jun 16 15:07:44 CEST 2017] Register account Error: {"type":"urn:ietf:params:acme:error:malformedRequest","detail":"JWS header parameter 'url' required.","status": 400}

It seems that the "url" parameter is missing from the request:
```
[Fri Jun 16 15:07:44 CEST 2017] JWK_HEADER='{"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "1ufzgVPwKV0vSh06Ft87gl2bGmT629yriGoR0OPvQuZqsjvmZFHVJZczR8ycJ0cRQNkz9IkUFE2gKL4qF8PC1UL-ul6egpw6O8v3nOWcQIhI83mV8OXh8Fc4-n4ipNCqktLdtIYYNQm24WveiosssjY0-cVbw3M_pco5fS0deKl7hCVn0C66ZSuvzW5wFO8HIRIGDrcmafIesK-rCwuVL5AkxOiSA87c8RPIbxsPYODrrV5oeUFIu1iSdFF4Zwdjsd74qQOWaXHhsuPzxdOVi11qjU7Nty8V__bszMHn_BGWt3dA0ol24rVG6Fkbtd4Pu1EANuv-rUb_UUsN1W6bJw"}}'
```
Even though [this is not implemented in Boulder](https://github.com/letsencrypt/boulder/blob/release/docs/acme-divergences.md#section-541), we would prefer to use Pebble over Boulder for an internal use case that does not require the might and complexity of boulder.

[Relevant RFC section](https://tools.ietf.org/html/draft-ietf-acme-acme-05#section-5.4.1)

Greetings

**Comment by Neilpang** [comment]
@Takios 
let me take a look.

**Comment by cpu** [comment]
> we would prefer to use Pebble over Boulder for an internal use case that does not require the might and complexity of boulder.

Can I ask about the internal use-case? I'm curious :-)

(Apologies for the off-topic comment @Neilpang - I hope you don't mind)

**Comment by Neilpang** [comment]
@Takios 
I just added a new branch `url` : https://github.com/Neilpang/acme.sh/tree/url

at: https://github.com/Neilpang/acme.sh/commit/f3dc5dd12fbe4b369595a90a8a048d23158f3cc4

Please have a try.

**Comment by Takios** [comment]
@Neilpang Yes, that works :)

@cpu older development environment without internet access. Let's leave it at that ;)
