### ISSUE TITLE
/directory is not being honored

### ISSUE THREAD

**Issue by Takios** [Neilpang/acme.sh#882]
Hello,

this issue happens with [Pebble](https://github.com/letsencrypt/pebble).

Pebble explicitly uses different endpoint paths than boulder and advertises them in their /dir (for example /nonce-plz instead of /acme/new-nonce). If I understood  https://github.com/Neilpang/acme.sh/pull/834#issuecomment-300655533 correctly, we will eventually be able to set a different path for the directory eventually.

But at the moment, even when setting the path to /directory directly in Pebble, acme.sh does not honor the paths given there.

I would prefer using Pebble over Boulder for an internal use case where the might and complexity of Boulder is not needed.

Greetings

**Comment by Neilpang** [comment]
@Takios 
Yes,  I'm implementing the `directory` feature now.

**Comment by Neilpang** [comment]
@Takios

I just added a new branch `server`:  https://github.com/Neilpang/acme.sh/tree/server

supported the `--server` parameter.  

please have a try:

```sh
acme.sh --issue  --server https://acme-staging.api.letsencrypt.org/directory  -d example.com  --standalon 
```

**Comment by Takios** [comment]
@Neilpang Thanks! I'll be able to test it monday.

**Comment by Takios** [comment]
I just tested the branch but I'm getting an url malformed error.
The following gist includes a --debug 3 log and the curl call taken from a "bash -x acme.sh ...", showing that the url string for curl is empty.
https://gist.github.com/Takios/e0b1f1fb78cdd515ab797b51f09ba2f8

**Comment by Takios** [comment]
Instead of "new-reg", pebble has the "new-account" key for registration, which seems to be correct according to the acme draft: https://tools.ietf.org/html/draft-ietf-acme-acme-06#page-24. Changing that key to "new-reg" in the pebble source code does make registering possible.

I wonder if it is wise to workaround this in acme.sh by first checking new-account and if it does not exist check for new-reg. 

Still, the error message could be made clearer in case a required key is not given (or assume a sensible default) ;)

**Comment by Neilpang** [comment]
@Takios 
I didn't noticed that they changed the name in the spec.
but it's fixed now.  please try again.

When I check your log, it seems that you don't have a `new-authz` entry point. You must add it.

**Comment by Takios** [comment]
We went back to testing with boulder and I can confirm that the --server option works.
