### ISSUE TITLE
Error reading CN in existing CSR with OpenSSL 1.1.0f 

### ISSUE THREAD

**Issue by Higorineth** [Neilpang/acme.sh#888]
Since I upgraded my debian to stretch, I got an error 
"new-authz error: {"type":"urn:acme:error:malformed","detail":"Error creating new authz :: DNS name does not have enough labels","status": 400}"

my command was
./acme.sh --test --signcsr --csr test.csr --dns dns_ovh

and a strange directory named " exemple.com, ST" appeared in .acme.sh/ along with my usual domaines.

I ran openssl to check my CSR
```
**$openssl req -in test.csr -noout -text
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: C = GB, ST = Some-State, O = Internet Widgits Pty Ltd, CN = exemple.com
        Subject Public Key Info:**
```
I checked the openssl version
```
**$openssl version
OpenSSL 1.1.0f  25 May 2017**
```
On another box (debian jessie) no issue with the same CSR
```
**$openssl version
OpenSSL 1.0.1t  3 May 2016**

**$openssl req -in test.csr -noout -text
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: C=GB, ST=Some-State, O=Internet Widgits Pty Ltd, CN=exemple.com
        Subject Public Key Info:**
```
It's look like the new spaces around the '=' signes in the last openssl version confuses acme.sh 

my CSR:
[test.csr.txt](https://github.com/Neilpang/acme.sh/files/1082648/test.csr.txt)

PS:
I upgraded acme.sh with ./acme.sh --upgrade 
same issue

**Comment by Neilpang** [comment]
fixed  please  try again.

**Comment by Higorineth** [comment]
Work's fine.

Thanks.
