### ISSUE TITLE
请问这个acme.sh 是一直在维护的吗

### ISSUE THREAD

**Issue by jimeng2016** [Neilpang/acme.sh#897]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

**Comment by Neilpang** [comment]
当然,  有什么问题吗

**Comment by jimeng2016** [comment]
没问题，我现在用的就是这个，挺好的。除了这个社区，有QQ群可以加入吗

**Comment by Neilpang** [comment]
![1090254299](https://user-images.githubusercontent.com/8305679/27365665-da07ba10-5673-11e7-893b-58a904c68302.jpg)

微信群

**Comment by jimeng2016** [comment]
不好意思，我刚看到这个信息。二维码失效了

**Comment by jimeng2016** [comment]
能麻烦您在发一次吗

**Comment by Neilpang** [comment]
@jimeng2016 

![1500621218](https://user-images.githubusercontent.com/8305679/27686216-62066718-5d04-11e7-982f-42e341d912c4.jpg)

**Comment by jimeng2016** [comment]
ok，已经加入。非常感谢
