### ISSUE TITLE
Docker daemon does not run with PID 1

### ISSUE THREAD

**Issue by hlavki** [Neilpang/acme.sh#900]
Docker daemon (crond) doesn't run with PID 1 so when you run docker stop, it waits (10 seconds by default) and then kills it.

```
PID   USER     TIME   COMMAND
    1 root       0:00 sh /entry.sh daemon
    6 root       0:00 crond -f
```

**Comment by Neilpang** [comment]
Thank you for pointing this out.
I will fix it soon.

Thanks.
