### ISSUE TITLE
Add subdomains

### ISSUE THREAD

**Issue by just-us** [Neilpang/acme.sh#912]
Hi there,

Just wondering how I attach subdomains to an already issued certificate? Do I use the --update-account command?

Thanks

**Comment by Neilpang** [comment]
you just need to `--issue` a new cert again.

**Comment by mayphilc** [comment]
Hi Neil, im going out of my mind trying this.
initially i issued a cert to my domain wth this:
acme.sh --issue -d MYDOMAIN.com -d http://www.MYDOMAIN.com -w ~/www/MYDOMAIN.COM --dns dns_gd

now i want to add cdn.mydomain.com and static.mydomain.com so i reissued like you just said with this:
acme.sh --issue -d mydomain.com -d http://www.mydomain.com -d cdn.mydomain.com -d static.mydomain.com -w ~/www/mydomain.COM --dns dns_gd

but it fails. i dont know if it makes a difference or not but the webroots for the subdomains are in the same directory as the webroot for the main domain

**Comment by FernandoMiguel** [comment]
Http is not part of the domain.
You can't use -w and -dns at the same time

**Comment by mayphilc** [comment]
it worked when i issued it the first time

**Comment by mayphilc** [comment]
literally the only difference this timme is i added the subdomains so what is the proper syntax?

**Comment by JonnyTech** [comment]
I too have this problem and notice that we are both using godaddy...

**Comment by mayphilc** [comment]
its not a godaddy limitation at all
i created a subdomain with its own webroot
cant issue a damn cert
worked just fine before

**Comment by FernandoMiguel** [comment]
because the 1st time it used the webroot for both.
if you want to use DNS api, you cant use it at the same time as webroot.

you can however use different methods of validation per domain.

**Comment by mayphilc** [comment]
can you be more specific and provide an example using the above mentioned syntax, pretend i have no clue what youre talking about, thanks a ton

**Comment by mayphilc** [comment]
or can you explain how to rectify this?

**Comment by FernandoMiguel** [comment]
try
`acme.sh --issue -d mydomain.com -d www.mydomain.com -d cdn.mydomain.com -d static.mydomain.com  --dns dns_gd`

**Comment by mayphilc** [comment]
thank you, will that work even though it has no trailing www, and this is all on an addon domain not the main account domain?

**Comment by mayphilc** [comment]
i have to wait nnow because i have too many failed attempts and have hit the limit that letsencrypt allows for fails/hour :/

**Comment by FernandoMiguel** [comment]
always use --test until you are sure

**Comment by mayphilc** [comment]
AWESOME INFO
can i combine --force --test ?

**Comment by FernandoMiguel** [comment]
yes

**Comment by mayphilc** [comment]
holy cow it worked! hombre, you are my hero. now to wait an hour and do without the --test!

**Comment by mayphilc** [comment]
so to clarify, if i use -d i do not need to specify a webroot because it gets that from dns?

**Comment by FernandoMiguel** [comment]
pick one: https://github.com/Neilpang/acme.sh/wiki/How-to-issue-a-cert

**Comment by FernandoMiguel** [comment]
test/staging certs are not valid

**Comment by mayphilc** [comment]
no, i did --force without the --test and it didnt error at all, it even deployed. now im getting a mixed content error using that domain as a cdn for my website

**Comment by mayphilc** [comment]
is it common for the process to succeed but the domain still be insecure?

**Comment by FernandoMiguel** [comment]
did you reload nginx?

**Comment by mayphilc** [comment]
im on apache, but i think i see whats happening here i just dont know why or how to fix it. 
so my main domain shows insecure, but when i open an image from it in a browser, thats secure. i dont get it because until i did this it was all secure....

https://www.mobilewarlords.com
https://cdn.mobilewarlords.com/uploads/2018/11/native-advertising-medias-web-journalisme.jpg

**Comment by mayphilc** [comment]
now miraculously it works?!?!?!?!?!

**Comment by FernandoMiguel** [comment]
- it's DNS
- can't be DNS
- oh crap it was DNS
- it's always DNS

**Comment by FernandoMiguel** [comment]
next up: http/2

**Comment by KaKi87** [comment]
Hello,

It would be nice to be able to add a subdomain to an existing domain without having to write the whole `--issue` command.

For instance, I have a domain, on which I use dozens of subdomains with wildcard SSL, and some of those subdomains have subsubdomains, which I must add as subwildcards, since `*.*` is not allowed.

So, to add one, I must `--list` first, then `--issue` while copy/pasting every single subwildcard I'm already using and adding the new one, which is really annoying.

Thanks
