### ISSUE TITLE
ANSI colour escape codes appearing in syslog when run under cron

### ISSUE THREAD

**Issue by matt-xtaz** [Neilpang/acme.sh#913]
I have acme.sh configured to log to syslog with SYS_LOG='6'. When the cron runs the output appears in syslog but it contains the ANSI colour escape sequence codes. If I run the cron manually on the command line with --no-color added on the end then there are no codes in the syslog, however if I add the same --no-color to the crontab then the codes still appear and no-color has no effect.

From glancing at the code it looks like you have a check to see if it's running interactively or not. I assume something is not quite right here. I've copied the code that you use to set INTERACTIVE to 1 or nothing and that works as expected.

**Comment by Neilpang** [comment]
you don't need to add `--no-color` in the crontab.   it doesn't output color at all in crontab.

`--no-color` is only for  interactive shell to disable color.

**Comment by matt-xtaz** [comment]
Then something is wrong with the logic I think. Both with and without --no-color in the crontab line I get escape sequences in the syslog like this when the cron runs.

Jun 30 11:59:13 tao acme.sh: [Fri 30 Jun 2017 11:59:13 BST] ^[[1;31;32m===Starting cron===^[[0m
Jun 30 11:59:13 tao acme.sh: [Fri 30 Jun 2017 11:59:13 BST] ^[[1;31;32mRenew: 'example.com'^[[0m
Jun 30 11:59:13 tao acme.sh: [Fri 30 Jun 2017 11:59:13 BST] Skip, Next renewal time is: ^[[1;31;32mSat 26 Aug 2017 18:18:57 UTC^[[0m
Jun 30 11:59:13 tao acme.sh: [Fri 30 Jun 2017 11:59:13 BST] Add '^[[1;31;40m--force^[[0m' to force to renew.
Jun 30 11:59:13 tao acme.sh: [Fri 30 Jun 2017 11:59:13 BST] Skipped example.com_ecc
Jun 30 11:59:13 tao acme.sh: [Fri 30 Jun 2017 11:59:13 BST] ^[[1;31;32m===End cron===^[[0m

If I run the cron command manually on the command line then it shows the same sequences in the syslog, if I add --no-color then the sequences are removed. But from cron it doesn't matter if --no-color is on there or not, the sequences are still there.

**Comment by Neilpang** [comment]
show me your crontab:

```
crontab -l

```

**Comment by matt-xtaz** [comment]
$ crontab -l
53 0 * * * "/var/db/acme/.acme.sh"/acme.sh --cron --home "/var/db/acme/.acme.sh" > /dev/null

**Comment by Neilpang** [comment]
how about adding `--no-color` to crontab ?

```sh
53 0 * * * "/var/db/acme/.acme.sh"/acme.sh --cron --home "/var/db/acme/.acme.sh" --no-color > /dev/null
```

**Comment by matt-xtaz** [comment]
As I mentioned originally, I tried that! Weirdly that works and removes the ANSI codes if I run that in the interactive command line shell. But if I let it run inside the cronjob it still shows the ANSI codes in the syslog. I am assuming that there is something not quite right in the logic that checks if it's running interactively or not. If you can't reproduce it then it could be specific to my O/S. I'm running FreeBSD rather than Linux. I did make a test script that does the same as acme.sh does where it tests for if t = 1, that is set to 1 or null as expected, so it's not this part.

**Comment by Neilpang** [comment]
I just tested the cronjob in my FreeBSD machine:

here is my cronjob:
```sh
# crontab -l
47 21  * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
```

`21:47` is my local time.

I just wait for the cronjob to run.
Then I checked the log file,  but it has not color code at all.


Let's see the code:

```
__INTERACTIVE=""
if [ -t 1 ]; then
  __INTERACTIVE="1"
fi

__green() {
  if [ "$__INTERACTIVE${ACME_NO_COLOR}" = "1" ]; then
    printf '\033[1;31;32m'
  fi
  printf -- "%b" "$1"
  if [ "$__INTERACTIVE${ACME_NO_COLOR}" = "1" ]; then
    printf '\033[0m'
  fi
}
```

In cronjob, this statement `if [ -t 1 ]; then`  should be `false`,  so `__INTERACTIVE` should be empty.

And `ACME_NO_COLOR` is not set, so,  it's empty too.

So,  `if [ "$__INTERACTIVE${ACME_NO_COLOR}" = "1" ]; then` is `false` too.

So, the error code should not be output to the log.

**Comment by matt-xtaz** [comment]
OK. Now I am really confused. I have just done some more testing and now I can't reproduce it at all?! It's working as expected. I have no idea what's changed, or what's going on there. But clearly I must have changed something between when it didn't work properly and now when it does. OK, apologies for making you waste time on this. It's obviously something that I did. Thanks!
