### ISSUE TITLE
Readme could be improved by making it more clear what this project accomplishes

### ISSUE THREAD

**Issue by EdSchouten** [Neilpang/acme.sh#916]
Context: I just stumbled upon this repository by accident; someone posted a link on social media. I have no first-hand experience using LetsEncrypt. Feel free to close if considered stupid. ;-)

Reading the introduction without ever having heard of ACME before, it's unclear what this project is trying to accomplish. I guess this could be improved as follows:

- Before listing features ("IPv6 support", add an opening sentence along the lines of: "acme.sh is a utility that you can use to do X."
- All of the text in the readme has the name of the protocol abbreviated ("ACME"). It would make sense to write it out at least once ("Automatic Certificate Management Environment").
- Make "ACME" a clickable link to some kind of page that explains what it is (e.g., [Wikipedia](https://en.wikipedia.org/wiki/Automated_Certificate_Management_Environment) or [the specification](https://github.com/ietf-wg-acme/acme/)).

**Comment by Neilpang** [comment]
we have a line after the `IPv6 support`
>> It's probably the easiest & smartest shell script to automatically issue & renew the free certificates from Let's Encrypt.

I think that's enough.

**Comment by jd7h** [comment]
Given that the most important information in the README should be at the top, and not half-way a list with no heading, I think it @EdSchouten makes a valid point.

**Comment by Neilpang** [comment]
Hi guys, @EdSchouten  @jd7h 

Why not send a PR as you wish ?
