### ISSUE TITLE
dnsapi is limited to one DNS account only

### ISSUE THREAD

**Issue by 2globalnomads** [Neilpang/acme.sh#929]
GD_KEY and GD_SECRET are saved to account.conf. Now system limited to one DNS only. This is a bit similar problem as using web root mode for verification: it works only when each domain has their own certificate issued with a manually specified --webroot.

Could webroot and/or DNS access keys be saved to the domain config instead of account config and have domain-specific parameters?

**Comment by Neilpang** [comment]
You can use different webroot for each domain:
https://github.com/Neilpang/acme.sh/issues/923#issuecomment-312551403


For the GD_KEY  in account conf,  it's a known requirement,  I will add a new parameter to save it in domain conf.

**Comment by 2globalnomads** [comment]
Perfect, thanks!

**Comment by Neilpang** [comment]
closed,  here was already an issue:  
https://github.com/Neilpang/acme.sh/issues/799
