### ISSUE TITLE
使用--dns方式，已经添加了txt解析，然后--renew的时候400错误

### ISSUE THREAD

**Issue by gmailzj** [Neilpang/acme.sh#932]
Challenge error: {"type":"urn:acme:error:malformed","detail":"Unable to update challenge :: The challenge is not pending.","status": 400}

**Comment by Neilpang** [comment]
更新到最新版 再试.

**Comment by xiahuaijia** [comment]
遇到同样问题 
acme.sh --upgrade --auto-upgrade
这样更新之后还是一样的问题

**Comment by tangbaobao** [comment]
同样的问题，
acme.sh  --renew   -d mydomain.com -d www.mydomain.com
mydomain.com没问题，后面一个是400错误

**Comment by Neilpang** [comment]
@xiahuaijia   @tangbaobao 

更新到最新版,   另外能不能贴出来 log.

**Comment by tangbaobao** [comment]
重启了vps之后再试就成功了。。真 玄学问题，我昨天搞了一晚上，版本一直是最新的

**Comment by Neilpang** [comment]
@tangbaobao 
你用什么方式验证的, 是webroot 还是dns ?

你可以开启 log,   下次自动更新再出问题你就可以查看log 了:

```sh
acme.sh --update-account  --log
```

**Comment by tangbaobao** [comment]
webroot一直不能成功，dns从昨天折腾到现在终于搞定了。
谢谢。

**Comment by Neilpang** [comment]
@tangbaobao

**Comment by tangbaobao** [comment]
我去研究下怎么改成dns api模式，谢了~

**Comment by xiahuaijia** [comment]
我用手动添加txt 解析成功了.  之前测试 dns api 是通过的.  用的是 dnspod
