### ISSUE TITLE
Test if one or more renews are required

### ISSUE THREAD

**Issue by Tadly** [Neilpang/acme.sh#948]
I require to use `standalone` but upone renewal, apache is obviously hogging the port acme.sh is trying to use.

Currently I have all domains configured to `pre` stop apache and `post` start apache.
```bash
...
Le_PreHook='systemctl stop apache2'
Le_PostHook='systemctl start apache2'
...
```

As all my domains expire at the same time, this causes apache to stop, start, stop, start... until all certs are renewed.

I'd be nice to have a way to check if there are certs which need renewing so I could than:
 1. stop apache
 2. renew all certs
 3. start apache

**Comment by Neilpang** [comment]
why not use  apache mode ?

**Comment by Tadly** [comment]
It changes the apache conf (which I'm not to big of a fan of, no matter how fail-save it is) and back when I first started it didn't work for my environment.

I'll give it another shot though. I honestly totally forgot this option even exists.
I'll let you know if it works out for me.

I still think it'd be nice to have a way of checking *if* there are certs that require renewing.
Maybe a sort of dry-run or something

**Comment by Neilpang** [comment]
apache mode will not change any of your conf.

I don't like any body to change my apache conf too.

**Comment by Tadly** [comment]
My bad, it doesn't replace it but temporarily swaps it if I understood the output correctly.

Seems to be working nicely though.
I'll change to that then, thanks for your help :)

**Comment by Neilpang** [comment]
correct,   it slightly modifies the apache conf,  and  restore back when finished.
