### ISSUE TITLE
Clarification around _initpath and _isEccKey

### ISSUE THREAD

**Issue by candlerb** [Neilpang/acme.sh#950]
There are some places where `_initpath()` is called with the key length as the second argument; and other places where it is called with the pseudo-boolean flag `isEcc` (which can be empty string or "isEcc").  It then passes this value to `_isEccKey()`

It took me a little while to convince myself this was correct, and I think it's worth a comment in the source code that both are allowed. e.g.

~~~
#keylength or isEcc flag
_isEccKey() {


#[domain]  [keylength or isEcc flag]
_initpath() {
~~~

**Comment by Neilpang** [comment]
sorry for the confusion.
If you send a PR, I'd like to merge.

Thanks.
