### ISSUE TITLE
PEM format

### ISSUE THREAD

**Issue by Tntdruid** [Neilpang/acme.sh#951]
Steps to reproduce
------------------

Debug log
-----------------

```
acme.sh  --issue .....   --debug 2
```

Hello,

Any way to sign a cert whit PEM format? My python script only works whit cert in PEM format

**Comment by Neilpang** [comment]
it is in PEM format.
just rename the  `*.cer`  to `*.pem`

**Comment by Tntdruid** [comment]
Thanks
