### ISSUE TITLE
How do I get X,Y?

### ISSUE THREAD

**Issue by yakeing** [Neilpang/acme.sh#955]
EC key
-----------------

```
read EC key
Private-Key: (256 bit)
priv:
    00:d0:a8:ba:1b:f6:21:4c:eb:46:32:eb:71:00:a0:
    c6:53:81:ba:1b:f6:21:4c:eb:46:32:eb:32:03:90:
    54:c5:95
pub:
    04:ad:d2:ba:1b:f6:21:4c:eb:46:32:eb:18:de:18:
    0a:05:66:***************************:ea:60:2d:
    9a:59:4c:****************************:be:3f:e6:
    d8:ac:e0:ba:1b:f6:21:4c:eb:46:32:eb:61:2e:d3:
    65:35:60:55:b5
ASN1 OID: prime256v1
NIST CURVE: P-256
```

pubtext = 04add2ba*****65356055b5 (130)

 $xend = pubtext / 4 (32.5=130/4) ????

 x="$(printf $pubtext | cut -d : -f 2-$xend)"
 x=adadd2***** (delete 04)
 x=pub (2-$xend) hex+base64_encode+urlencode 
string(43) "8yKVj5HpSX1tkKf_oO******"

y="$(printf $pubtext | cut -d : -f $xend-10000)"
 y=*******55b5
 y=pub ($xend-10000) hex+base64_encode+urlencode
string(43) "NyZJFC92LahzIErI--Of******"

JWS verification error

**Comment by yakeing** [comment]
就是x，y的拆分方法看不懂
---
1.是不是先取得 ` pub ` 的代码然后把里面的分隔符 ( : ) 去掉,  ` pubtext ` 是130个字符

  如:
```
    pubtext = 04add2ba*****65356055b5
```
2.这个 $xend 是 pubtext 除以四得到的吗?
 
 如:
```
    $xend = pubtext (130) / 4
```
  如果是这样的话 ` $xend ` 等于 32.5 了

3.  ` X ` , ` Y ` 的值就是把 ` pubtext ` 第一个和第二个字符  ` 04 `  去掉然后
  得到 128 个字符 , 然后把分两半 ` X ` 和 ` Y ` 每个得 64 字符再把 (16进制)
   ` X ` 和 ` Y ` 转 2进制 进行 base64 和 urlencode 编码 得到 string(43)

是这样吗? 应该不是 因为我的这样做返回 ` JWS verification error `

[![image](https://oauth.applinzi.com/SvgLabel/4D4D4D/Language/007EC6/PHP/image.svg)](https://github.com/Neilpang/acme.sh/blob/master/acme.sh)

**Comment by Neilpang** [comment]
加上  `--debug 3` 可以看到完整的拆分过程.
具体(x,y) 点的存储格式可以阅读相关的rfc.
不过, 你说的基本正确,   前面有一个字节表示后面的点是否是压缩格式, 所以这个字节要去掉.

**Comment by yakeing** [comment]
抱歉!

恕我愚昧, 关于 (x,y) 点的存储格式 太复杂看不懂.

还有就是我用的是 ` PHP ` 语言 关于 ` Linux sh ` 命令也不太懂.

[![image](https://oauth.applinzi.com/SvgLabel/4D4D4D/Language/007EC6/PHP/image.svg)](https://github.com/Neilpang/acme.sh/blob/master/acme.sh)

操作如下
---

### pub code 

  string(130) "04f322958f91e9497d6d90a7ffa0efcefa1a12f6dd7646f74dc4cac6b99e2130e6372649142f762da873204ac8fbe39fd1defacec41db60b4eb16567f6deaa3d6b" (16 hex)

---

### 编码后获取的结果

```
    jwk='{
        "crv": "P-256",
         "kty": "EC",
         "x": "8yKVj5HpSX1tkKf_oO_O-hoS9t12RvdNxMrGuZ4hMOY",  (ASCII)
        "y": "NyZJFC92LahzIErI--Of0d76zsQdtgtOsWVn9t6qPWs" (ASCII)
    }'
```
---

### 服务器返回错误的结果

```
    string(95) "{
      "type": "urn:acme:error:malformed",
      "detail": "JWS verification error",
      "status": 400
    }"
```

- JWS验证错误


X Y 是不是错误了??

**Comment by yakeing** [comment]
相关资料查阅:

Automatic Certificate Management Environment (ACME)
draft-ietf-acme-acme-05

[![image](https://oauth.applinzi.com/SvgLabel/4D4D4D/RFC/F66000/ACME/image.svg)](https://tools.ietf.org/id/draft-ietf-acme-acme-05.html#rfc.section.5.3)

Appendix A.  Example JSON Web Key Sets

[![image](https://oauth.applinzi.com/SvgLabel/4D4D4D/RFC/F66000/7517/image.svg)](https://tools.ietf.org/html/rfc7517#appendix-A)

Example JWS Using ECDSA P-256 SHA-256

[![image](https://oauth.applinzi.com/SvgLabel/4D4D4D/RFC/F66000/7515/image.svg)](https://tools.ietf.org/html/rfc7515#appendix-A.3)

**Comment by Neilpang** [comment]
加上 `--debug 3`,  你能看到所有的拆分 和签名过程, 及所有中间结果.

然后用你的代码, 用同样的 key 对同样的数据签名, 对比就知道你哪里出错了.
