### ISSUE TITLE
Le_RenewalDays being ignored?

### ISSUE THREAD

**Issue by pcolmer** [Neilpang/acme.sh#956]
I'm using the latest version (2.7.3) inside the Discourse Docker container.

The Discourse instance has a certificate that was created on 26th May and will be expiring on 24th August.

No matter what  Le_RenewalDays is set to inside the .conf file for the domain, acme.sh insists that it will not renew the cert until 14th August.

I haven't got Le_RenewalDays set anywhere else. Have I misunderstood something regarding how the renewal date is calculated (I've tried increasing and decreasing the value in the conf file without any apparent change in behaviour)?

Using --debug or --debug 2 didn't give any output that seemed relevant to the calculation of the renewal date.

**Comment by Neilpang** [comment]
Le_RenewalDays  is only working when you issue/renew a cert.

The next renewal time is calculated when the cert is issued.
