### ISSUE TITLE
Stateless mode: security risk?

### ISSUE THREAD

**Issue by osirisinferi** [Neilpang/acme.sh#959]
I read about your [stateless authentication method](https://github.com/Neilpang/acme.sh/wiki/Stateless-Mode), but I'm afraid this poses a security risk.

If a webserver is configured in the stateless mode way, it doesn't require any intervention on the servers part. As the ACME protocol doesn't require the client to actually be on the server, it's possible to initiate the issuing of a certificate "remotely".

If a server is configured to automatically pass any challenge provided to it, anyone with knowledge of this, can issue certificates for any domain configured as such.

I'm sure this is a grave security risk, only secured by security by obscurity.

**Comment by Neilpang** [comment]
Not really.

You must control the account private key also to issue the cert for the domain.

**Comment by osirisinferi** [comment]
Ah, because the interaction with the ACME server is JWK signed with said key?
