### ISSUE TITLE
does acme.sh create new private key on certificate renewal?

### ISSUE THREAD

**Issue by cibomato** [Neilpang/acme.sh#962]
I'd like to use HPKP to strenghten my SSL cert and I plan to pin my leaf cert issued by letsencrypt. Because of the short lifetime of this cert, I'd like to know whether acme.sh creates new keys during a renewal of the cert or not? If a new private key is used, it would be useless to pin the leaf cert, if I understood things right!?

**Comment by Neilpang** [comment]
closed in favor of  https://github.com/Neilpang/acme.sh/issues/873
