### ISSUE TITLE
[enhance req] crontab tool not avalaible

### ISSUE THREAD

**Issue by lefevred** [Neilpang/acme.sh#966]
in some distributions, crontab is not avalaible, but another tool is replacing it (like fcrontab in the ipfire distrib for firewall).

I think it would be good to have a kind of shell variable to define where is the "cron-like" binary, and its name.

Just a though.
Regards

**Comment by lefevred** [comment]
after a minor 
          sed -i 's/crontab/fcrontab/g' acme.sh
it all works fine :)

# ./acme.sh --install
[Tue Aug  8 11:12:27 CEST 2017] It is recommended to install nc first, try to install 'nc' or 'netcat'.
[Tue Aug  8 11:12:27 CEST 2017] We use nc for standalone server if you use standalone mode.
[Tue Aug  8 11:12:27 CEST 2017] If you don't use standalone mode, just ignore this warning.
[Tue Aug  8 11:12:27 CEST 2017] Installing to /root/.acme.sh
[Tue Aug  8 11:12:27 CEST 2017] Installed to /root/.acme.sh/acme.sh
[Tue Aug  8 11:12:28 CEST 2017] Installing alias to '/root/.bashrc'
[Tue Aug  8 11:12:29 CEST 2017] OK, Close and reopen your terminal to start using acme.sh
[Tue Aug  8 11:12:29 CEST 2017] Installing cron job
2017-08-08 11:12:29  INFO listing root's fcrontab
2017-08-08 11:12:30  INFO listing root's fcrontab
2017-08-08 11:12:30  INFO installing file /tmp/fcr-DsJUgh for user root
/tmp/fcr-DsJUgh:72: Mismatched quotes: skipping line.
Modifications will be taken into account right now.
[Tue Aug  8 11:12:30 CEST 2017] Good, bash is found, so change the shebang to use bash as preferred.
[Tue Aug  8 11:12:37 CEST 2017] OK

**Comment by Neilpang** [comment]
can you please let me know what OS you are using ?

**Comment by lefevred** [comment]
Sure, this is : http://www.ipfire.org/

**Comment by lefevred** [comment]
otherwise, perfect work, it runs like a charm :)

**Comment by Neilpang** [comment]
please try again.
