### ISSUE TITLE
Plan to build docker image on Docker Hub with release number?

### ISSUE THREAD

**Issue by m31271n** [Neilpang/acme.sh#980]
Current image tags is not conresponding to a specific release. 

![2017-08-20-172203_1168x887_scrot](https://user-images.githubusercontent.com/12194646/29493619-86a0d224-855f-11e7-9ad6-0b156255e10a.png)

I think a unambiguous tag is good for production evironment, such as `neilpang/acme.sh:2.7.2`

**Comment by Neilpang** [comment]
Sorry,  I don't think it's necessary.
Since the autoupgrde is enabled in the docker image, so it would always keep using the latest code. 
There is no need to tag it.
