### ISSUE TITLE
dns_nsupdate renewed the domain and cleared the domain config file.

### ISSUE THREAD

**Issue by ksuuk** [Neilpang/acme.sh#984]
First cert I got manually:
acme.sh --issue --dns -d test.domain.com

Then later "upgraded" it to use automatic renewal:
acme.sh --issue --force --dns dns_nsupdate -d test.domain.com

And 3 months later domain was automatically renewed. But then the cronjob stasted complain:
Please specify at least one validation method: '--webroot', '--standalone', '--apache', '--nginx' or '--dns' etc.
[Tue Aug 22 00:55:00 EEST 2017] Error renew test.domain.com.

Turns out, that renewal cleared the whole test.domain.com.conf file as this contains only one line:
Le_RealFullChainPath=''

But it contained before:
Le_Domain='test.domain.com'
Le_Alt='no'
Le_Webroot='dns_nsupdate'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v01.api.letsencrypt.org/directory'
Le_Keylength=''

Le_LinkCert='https://acme-v01.api.letsencrypt.org/acme/cert/xzxzxzxzxzxzxzxzxzxzzxzx'
Le_LinkIssuer='https://acme-v01.api.letsencrypt.org/acme/issuer-cert'
Le_CertCreateTime='1498078116'
Le_CertCreateTimeStr='Wed Jun 21 20:48:36 UTC 2017'
Le_NextRenewTimeStr='Sun Aug 20 20:48:36 UTC 2017'
Le_NextRenewTime='1503175716'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath=''
Le_ReloadCmd='service dovecot restart && service postfix restart && date -u -r /etc/ssl/certs/mail.crt | mail -s Renewed alert@domain.com'
Le_RealFullChainPath=''

I'm using VER=2.7.3. How to fix it and get a current working config?

**Comment by ksuuk** [comment]
Edit: Tested, removed the whole ~/.acme.sh/test.domain.com folder, and issued domain again:
acme.sh --issue --dns dns_nsupdate -d test.domain.com
acme.sh --install-cert -d test.domain.com --reloadcmd "service dovecot restart && service postfix restart && date -u -r /etc/ssl/certs/mail.crt | mail -s Renewed alert@domain.com"

Got new certificate and also new configuration file was created. But why the config file content was removed within automatic renewal?

**Comment by Neilpang** [comment]
Please enable log,  and wait to see what will happen next time renewal.

```
acme.sh  --update-account --log
```

**Comment by ksuuk** [comment]
Ok, I will. 

BTW, same did happened with different servers, different domains and linux versions. Also some (Centos 5X) give errors during renewal (maybe You are using to new sed commands or something, sed-4.1.5-8.el5 is used there):

Cron <root@server> "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
sed: -e expression #1, char 161: unknown option to `s'

**Comment by Neilpang** [comment]
sorry, can you please try again:

```
"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"  --debug 2
```

**Comment by frkca** [comment]
Most likely also related to #1969 - just for those searching for it :-) Thanks @Neilpang !
