### ISSUE TITLE
return codes in renew hook are not passed to acme.sh

### ISSUE THREAD

**Issue by schachtnerth** [Neilpang/acme.sh#999]
Steps to reproduce
------------------
1. Create a new certificate
2. Renew the certificate using acme.sh and also specify a shell script as --renew-hook parameter
3. In case, there's an issue during the renew-hook script and it exits with a return value of != 0, the acme.sh recognizes that and prints a message "Error when run renew hook.". This means, acme.sh is aware of the fact that there was a problem during hook processing. The return code of acme.sh is still 0, though.

It would be good if acme.sh ...
EITHER used the same return code as the renew hook
OR exits with its own (non-zero) return code.

Best regards,
Tom

**Comment by Neilpang** [comment]
fixed
